Repository storybookjs/storybook, pull requests merged in 2018-08, with the labels that each got.

#3938 Documentation Updates
  docs/README.md
  docs/src/pages/basics/introduction/index.md
  docs/src/pages/basics/quick-start-guide/index.md
  docs/src/pages/basics/slow-start-guide/index.md
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation

#3939 Clean READMEs
  .npmignore
  README.md
  addons/actions/README.md
  addons/backgrounds/README.md
  addons/centered/README.md
  addons/events/README.md
  addons/graphql/README.md
  addons/info/README.md
  addons/knobs/README.md
  addons/links/README.md
  addons/notes/README.md
  addons/options/README.md
  addons/storyshots/storyshots-core/README.md
  app/angular/README.md
  app/angular/docs/react_storybook_screenshot.png
  app/angular/docs/storybooks_io_logo.png
  app/marko/README.md
  app/marko/docs/marko_storybook_screenshot.png
  app/marko/docs/storybooks_io_logo.png
  app/mithril/README.md
  app/mithril/docs/demo.gif
  app/mithril/docs/react_storybook_screenshot.png
  app/mithril/docs/storybooks_io_logo.png
  app/polymer/README.md
  app/polymer/docs/demo.gif
  app/polymer/docs/react_storybook_screenshot.png
  app/polymer/docs/storybooks_io_logo.png
  app/react-native/readme.md
  app/react/README.md
  app/react/docs/demo.gif
  app/react/docs/react_storybook_screenshot.png
  app/react/docs/storybooks_io_logo.png
  app/vue/README.md
  app/vue/docs/demo.gif
  app/vue/docs/react_storybook_screenshot.png
  app/vue/docs/storybooks_io_logo.png
  lib/addons/README.md
  lib/channel-postmessage/README.md
  lib/channel-websocket/README.md
  lib/channels/README.md
  lib/cli/README.md
  lib/client-logger/README.md
  lib/codemod/README.md
  lib/components/README.md
  lib/core/README.md
  lib/node-logger/README.md
  lib/ui/README.md
  media/demo.gif
Labels: documentation, maintenance

#3941 Improve BettercodeHub
  .bettercodehub.yml
Labels: maintenance

#3942 Fix typo in addon-viewport
  addons/viewport/src/shared/index.js
Labels: bug, patch

#3922 horizontal display for addon-knobs radios UI
  addons/knobs/src/components/types/Radio.js
Labels: addon: knobs, feature request

#3954 UPGRADE all minor dependencies
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/events/package.json
  addons/graphql/package.json
  addons/info/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/notes/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/html/package.json
  app/marko/package.json
  app/mithril/package.json
  app/polymer/package.json
  app/react-native/package.json
  app/react/package.json
  app/vue/package.json
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/component-with-di/__snapshots__/di.component.stories.storyshot
  examples/cra-kitchen-sink/package.json
  examples/html-kitchen-sink/package.json
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/polymer-cli/package.json
  examples/vue-kitchen-sink/package.json
  lib/cli/package.json
  lib/codemod/package.json
  lib/components/package.json
  lib/core/package.json
  lib/ui/package.json
  package.json
  yarn.lock
Labels: dependencies:update

#3957 More dependency upgrades (major version bumps)
  addons/a11y/package.json
  addons/a11y/src/components/Report/Item.js
  addons/events/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storysource/package.json
  app/react-native/package.json
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/__snapshots__/addon-centered.stories.storyshot
  examples/cra-kitchen-sink/package.json
  examples/html-kitchen-sink/package.json
  examples/html-kitchen-sink/stories/__snapshots__/addon-centered.stories.storyshot
  examples/marko-cli/package.json
  examples/react-native-vanilla/__tests__/__snapshots__/storyshots.js.snap
  examples/vue-kitchen-sink/src/stories/__snapshots__/addon-centered.stories.storyshot
  lib/cli/package.json
  lib/components/package.json
  lib/components/src/icons/chevronRight.js
  lib/components/src/icons/index.js
  lib/components/src/index.js
  lib/core/package.json
  lib/ui/package.json
  lib/ui/src/modules/ui/components/stories_panel/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/tree_decorators.js
  package.json
  scripts/jest-ts-babel.js
  yarn.lock
Labels: dependencies:update

#3962 add a11y link to gallery
  docs/src/pages/addons/addon-gallery/index.md
Labels: documentation

#3959 [BUG FIX] Use fixed version of react-dev-utils
  app/react-native/package.json
  app/react/package.json
  lib/core/package.json
  yarn.lock
Labels: babel / webpack, bug

#3966 Fix Seamless Typescript Integration section in readme
  app/react-native/readme.md
Labels: documentation

#3958 Make addon-options work with story parameters
  addons/options/README.md
  addons/options/preview.js
  addons/options/src/preview/index.js
  examples/marko-cli/src/stories/addon-knobs.stories.js
  examples/marko-cli/src/stories/index.stories.js
Labels: addon: options, feature request

#3951 Document generic addons and knobs select migration
  CHANGELOG.md
  MIGRATION.md
Labels: documentation

#3963 sorting by kind and nested stories
  lib/ui/src/modules/ui/libs/filters.js
  lib/ui/src/modules/ui/libs/filters.test.js
Labels: bug

#3885 Stylize webpack references
  docs/src/pages/configurations/custom-webpack-config/index.md
Labels: documentation

#3976 Allow extending extensions without a full control mode
  lib/core/src/server/__snapshots__/mergeConfigs.test.js.snap
  lib/core/src/server/config.js
  lib/core/src/server/mergeConfigs.js
  lib/core/src/server/mergeConfigs.test.js
Labels: babel / webpack, core, feature request

#3961 Improve typescript config docs
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation

#4008 Fixed homepage links [skip ci]
  app/angular/package.json
  app/html/package.json
  app/polymer/package.json
  app/svelte/package.json
  app/vue/package.json
Labels: maintenance

#4009 Fix custom webpack config warnings
  lib/core/src/server/config/interpret-files.js
  lib/core/src/server/loadCustomWebpackConfig.js
  lib/core/src/server/serverRequire.js
Labels: bug, core

#4022 Replace demo.gif
  README.md
  app/angular/README.md
  app/html/README.md
  app/html/docs/demo.png
  app/marko/README.md
  app/marko/docs/demo.gif
  app/mithril/README.md
  app/polymer/README.md
  app/react/README.md
  app/svelte/README.md
  app/vue/README.md
  docs/src/components/Homepage/Demo/images/demo.gif
  docs/src/components/Homepage/Demo/images/storybook-intro.gif
  docs/src/components/Homepage/Demo/index.js
  media/demo.gif
  media/storybook-intro.gif
Labels: documentation

#4024 Bring .jsx back
  lib/core/src/server/config/webpack.config.js
  lib/core/src/server/config/webpack.config.prod.js
Labels: bug, core

#4031 Remove git info extraction
  lib/core/src/server/build-dev.js
Labels: maintenance

#4030 Remove deprecation of --db-path and --enable-db
  lib/core/src/server/build-dev.js
  lib/core/src/server/build-static.js
Labels: core, maintenance

#4040 Removed obsolete travis references
  docs/.travis.yml
  docs/package.json
  docs/scripts/travis/after_success.sh
  docs/scripts/travis/before_install.sh
  scripts/travis/after_success.sh
  scripts/travis/before_install.sh
Labels: cleanup

#4037 Storyshots puppeteer images do not match
  addons/storyshots/storyshots-puppeteer/src/index.js
Labels: addon: storyshots, bug

#4045 Storyshots puppeteer images do not match
  addons/storyshots/storyshots-puppeteer/src/index.js
Labels: addon: storyshots, bug

#4064 Storybook Badge
  README.md
Labels: documentation

#4068 Faster CircleCI
  .circleci/config.yml
  .teamcity/OpenSourceProjects_Storybook/Project.kt
Labels: maintenance

#4004 Fix autodetection of used components in info addon
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/Story.js
  examples/cra-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
Labels: bug

#4060 #3780: Do not display wrong warning when loading ".js" or ".json"
  lib/core/src/server/serverRequire.js
Labels: bug, core

#4076 Add missing `@babel/plugin-proposal-class-properties` dependency
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  app/angular/package.json
  app/html/package.json
  app/marko/package.json
  app/mithril/package.json
  app/polymer/package.json
  app/react/package.json
  app/vue/package.json
  examples/vue-kitchen-sink/package.json
  lib/cli/package.json
  lib/codemod/package.json
  lib/core/package.json
  lib/node-logger/package.json
  package.json
  yarn.lock
Labels: babel / webpack, bug, core

#4074 adds closing tag in component state example
  docs/src/pages/basics/faq/index.md
Labels: documentation

#4080 Remove danger from circleci because it's not working for forked PRs
  .circleci/config.yml
Labels: maintenance

#4012 feature: noStoriesOf loader option support for custome story
  addons/storysource/README.md
  addons/storysource/src/loader/__snapshots__/inject-decorator.test.js.snap
  addons/storysource/src/loader/generate-helpers.js
  addons/storysource/src/loader/index.js
  addons/storysource/src/loader/inject-decorator.js
  addons/storysource/src/loader/inject-decorator.test.js
  lib/cli/test/snapshots/angular-cli/package.json
  lib/cli/test/snapshots/marko/package.json
  lib/cli/test/snapshots/meteor/package.json
  lib/cli/test/snapshots/mithril/package.json
  lib/cli/test/snapshots/polymer/package.json
  lib/cli/test/snapshots/react/package.json
  lib/cli/test/snapshots/react_project/package.json
  lib/cli/test/snapshots/react_scripts/package.json
  lib/cli/test/snapshots/react_static/package.json
  lib/cli/test/snapshots/react_static_next/package.json
  lib/cli/test/snapshots/update_package_organisations/package.json
  lib/cli/test/snapshots/vue/package.json
Labels: addon: storysource, feature request

#4092 Do not stale "good first issue"
  .github/stale.yml
Labels: maintenance

#4081 fixed 4025 - allow setting background via name
  addons/backgrounds/README.md
  addons/backgrounds/src/BackgroundPanel.js
Labels: addon: backgrounds, feature request

#4100 Disabled import for TabWrapper
  lib/addons/src/index.js
Labels: bug
