Repository storybookjs/storybook, pull requests merged in 2018-12, with the labels that each got.

#4899 fix(): deprecations with replacing setOptions with withOptions
  examples/angular-cli/.storybook/config.ts
  examples/marko-cli/.storybook/config.js
  examples/mithril-kitchen-sink/.storybook/config.js
  examples/official-storybook/stories/addon-a11y.stories.js
  examples/official-storybook/stories/addon-actions.stories.js
  examples/polymer-cli/.storybook/config.js
  examples/riot-kitchen-sink/.storybook/config.js
  examples/svelte-kitchen-sink/.storybook/config.js
  examples/vue-kitchen-sink/.storybook/config.js
  examples/vue-kitchen-sink/src/stories/__snapshots__/addon-centered.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/custom-decorators.stories.storyshot
Labels: maintenance

#4904 Remove use of const
  addons/a11y/manager.js
Labels: bug, patch

#4902 Add CRA TypeScript support for .storybook folder
  app/react/src/server/__mocks__/mockRules.js
  app/react/src/server/cra-config.js
  app/react/src/server/cra-config.test.js
  app/react/src/server/framework-preset-cra.js
  jest.config.js
Labels: cra, feature request, presets

#4907 Fix React Native async storage. Added missing return
  app/react-native/src/preview/index.js
Labels: app: react-native, bug

#4908 Document configuration options for Storyshots test
  addons/storyshots/storyshots-core/README.md
Labels: addon: storyshots, documentation, patch

#4906 Add Vanilla example to docs site
  docs/src/pages/examples/_examples.yml
  docs/src/pages/examples/thumbnails/vanilla.png
Labels: documentation

#4905 Update index.md
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch, typescript

#4919 Core - More granular methods separation in "build-static" and "build-dev"
  lib/core/src/server/build-dev.js
  lib/core/src/server/build-static.js
  package.json
  yarn.lock
Labels: core, maintenance, ready

#4929 Move 'core-js/modules/es6.promise' into storyshots for angular
  addons/storyshots/storyshots-core/src/frameworks/angular/loader.js
  examples/angular-cli/angularshots.test.js
Labels: addon: storyshots, app: angular, bug

#4934 Fix typos and grammatical errors in markdown documents
  CONTRIBUTING.md
  MAINTAINERS.md
  MIGRATION.md
  README.md
  RELEASES.md
  ROADMAP.md
  docs/README.md
Labels: documentation, patch

#4933 add link to ember guide in docs
  docs/gatsby-config.js
Labels: documentation, patch

#4948 Fix typo/grammer
  MIGRATION.md
Labels: documentation

#4758 TS Migration: addon-notes
  .eslintignore
  .eslintrc.js
  addons/notes/package.json
  addons/notes/src/__tests__/index.ts
  addons/notes/src/index.ts
  addons/notes/src/public_api.ts
  addons/notes/src/react.js
  addons/notes/src/register.js
  addons/notes/src/register.tsx
  addons/notes/src/typings.d.ts
  addons/notes/tsconfig.json
  package.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: addon: notes, maintenance, typescript

#4967 Fix storyshots by compiling JS modules
  .babelrc.js
  examples/official-storybook/webpack.config.js
Labels: bug

#4979 Update README.md
  addons/info/README.md
Labels: documentation

#4981 Add core-js to addons
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/centered/package.json
  addons/cssresources/package.json
  addons/events/package.json
  addons/google-analytics/package.json
  addons/graphql/package.json
  addons/info/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/notes/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  addons/options/package.json
  addons/viewport/package.json
Labels: maintenance

#4973 [docs] Update TS config docs
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation

#4928 fix: Add missing peer dependencies to addon-knobs
  addons/knobs/package.json
Labels: addon: knobs, dependencies

#4961 add forwardRef support to addon-info
  addons/info/package.json
  addons/info/src/components/Node.js
  addons/info/src/components/Story.js
  examples/official-storybook/components/ForwardedRefButton.js
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  examples/official-storybook/stories/addon-info.stories.js
Labels: addon: info, feature request

#4991 RESET lockfile
  lib/components/src/layout/__snapshots__/index.stories.storyshot
  yarn.lock
Labels: cleanup, dependencies:update

#4988 Make applyPresets function signature more consistent
  lib/core/src/server/presets.js
Labels: maintenance

#4974 Fix link to addons intro from guide-react-native/index.md
  docs/src/pages/basics/guide-react-native/index.md
Labels: documentation

#4971 Feat: Add support for Flow to @addons/storysource
  __mocks__/inject-decorator.flow-stories.txt
  addons/storysource/README.md
  addons/storysource/src/loader/__snapshots__/inject-decorator.test.js.snap
  addons/storysource/src/loader/inject-decorator.test.js
  addons/storysource/src/loader/parsers/index.js
  addons/storysource/src/loader/parsers/parser-flow.js
Labels: addon: storysource, compatibility with other tools, feature request

#4960 FIX version of packages, fixes #4956
  addons/storyshots/storyshots-core/package.json
  docs/package.json
  docs/yarn.lock
Labels: bug

#4989 [docs] Update description of standalone's mode option
  docs/src/pages/configurations/standalone-options/index.md
Labels: documentation

#4983 add markdown support for jsdoc comments
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/Story.js
  addons/info/src/index.test.js
  app/preact/package.json
  examples/preact-kitchen-sink/package.json
  lib/cli/package.json
  yarn.lock
Labels: addon: info, feature request

#5015 Include macro instructions for Storyshots docs
  addons/storyshots/storyshots-core/README.md
Labels: documentation

#5012 Fix typo in docs
  docs/src/pages/configurations/theming/index.md
Labels: documentation

#5022 Typo fixes
  docs/src/pages/configurations/theming/index.md
Labels: documentation

#5016 ADD alias to react & react-dom
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: app: react, babel / webpack, bug

#5042 FIX alias for react(-dom) to resolve to the user's version
  lib/core/package.json
  lib/core/src/server/preview/iframe-webpack.config.js
  yarn.lock
Labels: bug, core

#5047 Remove unnecessary dependencies, fix aliasing
  app/react/package.json
  lib/core/package.json
  lib/core/src/server/manager/manager-webpack.config.js
  lib/core/src/server/preview/iframe-webpack.config.js
  lib/ui/paths.js
Labels: app: react, babel / webpack, bug, patch

#4855 Added options knob (based on next)
  addons/knobs/README.md
  addons/knobs/package.json
  addons/knobs/src/components/__tests__/Options.js
  addons/knobs/src/components/__tests__/RadioButtons.js
  addons/knobs/src/components/types/Checkboxes.js
  addons/knobs/src/components/types/Options.js
  addons/knobs/src/components/types/Radio.js
  addons/knobs/src/components/types/index.js
  addons/knobs/src/index.js
  examples/official-storybook/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/official-storybook/stories/addon-knobs.stories.js
  lib/components/src/form/input.js
  yarn.lock
Labels: addon: knobs, feature request

#5054 Tech/cleaner netlify logs
  lib/core/src/server/cli/prod.js
  scripts/netlify-build.sh
Labels: cleanup

#4482 Fix propTypes not showing in PropType table
  addons/info/src/components/types/PrettyPropType.js
  addons/info/src/components/types/proptypes.js
  examples/cra-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
Labels: addon: info, bug

#4589 feat(InfoAddon): add css classes
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/Story.js
  examples/cra-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
Labels: addon: info, feature request

#4480 Update docs to use docgen loader instead of plugin
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation

#4977 TypeScript migration: @storybook/channels
  .eslintrc.js
  addons/viewport/src/manager/components/tests/viewportInfo.test.js
  examples/angular-cli/.storybook/tsconfig.json
  examples/angular-cli/angular.json
  examples/angular-cli/jest.config.js
  examples/angular-cli/src/karma.ts
  examples/angular-cli/src/tsconfig.app.json
  examples/angular-cli/src/tsconfig.spec.json
  jest.config.js
  lib/channels/package.json
  lib/channels/src/index.js
  lib/channels/src/index.test.js
  lib/channels/src/index.test.ts
  lib/channels/src/index.ts
  lib/channels/tsconfig.json
  package.json
  yarn.lock
Labels: maintenance, typescript

#5067 Fixed isUIHidden param.
  app/react-native/src/preview/index.js
Labels: app: react-native, bug

#4962 Change React Native On Device Layout to absolute position
  app/react-native/src/preview/components/OnDeviceUI/index.js
  app/react-native/src/preview/components/OnDeviceUI/navigation/index.js
  app/react-native/src/preview/components/OnDeviceUI/navigation/visibility-button.js
  app/react-native/src/preview/components/OnDeviceUI/style.js
  app/react-native/src/preview/components/StoryListView/index.js
  app/react-native/src/preview/components/StoryListView/style.js
Labels: app: react-native, feature request

#4927 Core - Simplify custom webpack config
  app/angular/src/server/options.js
  app/ember/src/server/options.js
  app/react/src/server/options.js
  examples/angular-cli/.storybook/webpack.config.ts
  examples/ember-cli/.storybook/webpack.config.js
  examples/html-kitchen-sink/.storybook/webpack.config.js
  examples/marko-cli/.storybook/webpack.config.js
  examples/mithril-kitchen-sink/.storybook/webpack.config.js
  examples/official-storybook/webpack.config.js
  examples/polymer-cli/.storybook/webpack.config.js
  examples/riot-kitchen-sink/.storybook/webpack.config.js
  examples/svelte-kitchen-sink/.storybook/webpack.config.js
  examples/vue-kitchen-sink/.storybook/webpack.config.js
  lib/core/src/server/preview/custom-webpack-preset.js
Labels: babel / webpack, core

#5058 Use new story format in official storybook
  examples/official-storybook/config.js
  examples/official-storybook/stories/core.stories.js
  examples/official-storybook/stories/core/async.stories.inactive.js
  examples/official-storybook/stories/core/errors.stories.js
  examples/official-storybook/stories/core/events.stories.js
  examples/official-storybook/stories/core/parameters.stories.js
Labels: api: stories, feature request

#5082 Load Symbol polyfill before any other code
  lib/core/src/server/common/polyfills.js
Labels: bug

#5018 Typescript-Migration: @storybook/addons
  .eslintignore
  addons/notes/package.json
  addons/notes/src/index.ts
  addons/notes/src/register.tsx
  addons/notes/src/typings.d.ts
  addons/notes/tsconfig.json
  addons/storyshots/storyshots-core/package.json
  lib/addons/package.json
  lib/addons/src/index.js
  lib/addons/src/index.ts
  lib/addons/src/make-decorator.js
  lib/addons/src/make-decorator.test.ts
  lib/addons/src/make-decorator.ts
  lib/addons/src/public_api.ts
  lib/addons/src/storybook-channel-mock.ts
  lib/addons/src/typings.d.ts
  lib/addons/tsconfig.json
  lib/channels/package.json
  package.json
  scripts/build-pack.sh
  scripts/prepare.js
  tsconfig.json
  yarn.lock
Labels: api: addons, maintenance, needs review, typescript

#5046 TypeScript migration: @storybook/channel-websocket
  lib/channel-websocket/package.json
  lib/channel-websocket/src/index.js
  lib/channel-websocket/src/index.ts
  lib/channel-websocket/src/typings.d.ts
  lib/channel-websocket/tsconfig.json
  scripts/build-pack.sh
Labels: maintenance, typescript

#5121 Add a new Community Addon to addon-gallery
  docs/src/pages/addons/addon-gallery/index.md
Labels: documentation, patch
