Repository storybookjs/storybook, pull requests merged in 2018-07, with the labels that each got.

#3785 Support other type of webpack configs
  lib/core/package.json
  lib/core/src/server/config.js
  lib/core/src/server/loadCustomWebpackConfig.js
  yarn.lock
Labels: babel / webpack, feature request, typescript

#3744 Replaced 'dotenv-webpack' with 'universal-dotenv' to support multiple dot env files (like CRA)
  app/angular/bin/build.js
  app/angular/src/server/build.js
  app/html/bin/build.js
  app/html/src/server/build.js
  app/marko/bin/build.js
  app/marko/src/server/build.js
  app/mithril/bin/build.js
  app/mithril/src/server/build.js
  app/polymer/bin/build.js
  app/polymer/src/server/build.js
  app/react-native/package.json
  app/react-native/src/server/config/webpack.config.js
  app/react-native/src/server/config/webpack.config.prod.js
  app/react/bin/build.js
  app/react/src/server/build.js
  app/vue/bin/build.js
  app/vue/src/server/build.js
  lib/core/package.json
  lib/core/src/server/config/env.js
  lib/core/src/server/config/webpack.config.js
  lib/core/src/server/config/webpack.config.prod.js
  yarn.lock
Labels: babel / webpack, feature request, maintenance

#3829 Fix non-polyfilled themed UI components
  lib/ui/src/modules/ui/components/search_box.js
  lib/ui/src/modules/ui/components/shortcuts_help.js
Labels: bug

#3678 Refactor addon-jest to use a parameter-based pattern
  addons/jest/README.md
  addons/jest/package.json
  addons/jest/src/index.js
  examples/angular-cli/.storybook/withTests.ts
  examples/angular-cli/addon-jest.testresults.json
  examples/angular-cli/src/stories/addon-jest.stories.ts
  examples/html-kitchen-sink/stories/addon-jest.stories.js
  examples/official-storybook/stories/addon-jest.stories.js
Labels: addon: jest, feature request

#3838 Small readme bugfix
  addons/jest/README.md
Labels: documentation

#3845 Removed usages of hoc-style addons from the docs
  addons/info/README.md
  docs/src/pages/addons/using-addons/index.md
  docs/src/pages/basics/writing-stories/index.md
  docs/src/pages/configurations/typescript-config/index.md
Labels: api: addons, documentation

#3844 Added a test for parameter combination
  lib/core/src/client/preview/client_api.test.js
Labels: api: stories, maintenance

#3856 Fix typo
  docs/src/pages/basics/guide-vue/index.md
Labels: app: vue, documentation, patch

#3863 Upgrade universal-dotenv to fix babel-runtime
  app/react-native/package.json
  lib/core/package.json
  yarn.lock
Labels: bug

#3874 Upgrade universal-dotenv to fix core-js dependency
  app/react-native/package.json
  lib/core/package.json
  yarn.lock
Labels: bug

#3877 storybook with Node HTTP Server
  docs/src/pages/basics/exporting-storybook/index.md
Labels: documentation

#3876 [addon-a11y] improve documentation
  addons/a11y/README.md
Labels: addon: a11y, documentation, patch

#3866 Fix knobs for React < 16.3
  addons/knobs/package.json
  addons/knobs/src/components/types/Array.js
  addons/knobs/src/components/types/Color.js
  addons/knobs/src/components/types/Date/index.js
  addons/knobs/src/components/types/Number.js
  addons/knobs/src/components/types/Object.js
  addons/knobs/src/components/types/Text.js
Labels: addon: knobs, bug

#3884 MOVE ui into it's own group
  examples/official-storybook/stories/__snapshots__/addon-backgrounds.stories.storyshot
  examples/official-storybook/stories/addon-backgrounds.stories.js
  lib/ui/src/modules/ui/components/__snapshots__/menu_item.stories.storyshot
  lib/ui/src/modules/ui/components/menu_item.stories.js
  lib/ui/src/modules/ui/components/search_box.stories.js
  lib/ui/src/modules/ui/components/shortcuts_help.stories.js
  lib/ui/src/modules/ui/components/stories_panel/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/__snapshots__/text_filter.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/index.stories.js
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/index.stories.js
  lib/ui/src/modules/ui/components/stories_panel/text_filter.stories.js
Labels: maintenance

#3891 Fix typo in exporting storybook instructions
  docs/src/pages/basics/exporting-storybook/index.md
Labels: documentation

#3882 Fix addons panel when using preact
  lib/components/src/tabs/tabs.js
Labels: compatibility with other tools, feature request, patch

#3846 Group deprecated stories
  examples/official-storybook/stories/__snapshots__/addon-actions.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-backgrounds.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-events.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-notes.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-viewport.stories.storyshot
  examples/official-storybook/stories/addon-actions.stories.js
  examples/official-storybook/stories/addon-backgrounds.stories.js
  examples/official-storybook/stories/addon-events.stories.js
  examples/official-storybook/stories/addon-info.stories.js
  examples/official-storybook/stories/addon-notes.stories.js
  examples/official-storybook/stories/addon-viewport.stories.js
Labels: maintenance

#3852 Use react-dev-utils@next
  app/react-native/package.json
  app/react-native/src/server/config/webpack.config.js
  app/react/package.json
  lib/core/package.json
  lib/core/src/server/config/webpack.config.js
  lib/core/src/server/config/webpack.config.prod.js
  yarn.lock
Labels: app: react, app: react-native, dependencies, dependencies:update

#3788 added arrow to a11y addon HeaderBar
  addons/a11y/package.json
  addons/a11y/src/components/Report/Item.js
Labels: addon: a11y, feature request

#3910 doc(test): image test is official-storybook, not cra-kitchen-sink
  CONTRIBUTING.md
Labels: documentation, patch

#3911 dependencies(vue): Update vue-loader to 15.x.x
  app/vue/package.json
  app/vue/src/server/wrapInitialConfig.js
  examples/vue-kitchen-sink/package.json
  examples/vue-kitchen-sink/webpack.config.js
  yarn.lock
Labels: BREAKING CHANGE, app: vue, feature request

#3894 Add radio buttons knob type #3872
  addons/knobs/README.md
  addons/knobs/src/components/__tests__/RadioButtons.js
  addons/knobs/src/components/types/Radio.js
  addons/knobs/src/components/types/index.js
  addons/knobs/src/index.js
  examples/angular-cli/src/stories/addon-knobs.stories.ts
  examples/crna-kitchen-sink/storybook/stories/Knobs/index.js
  examples/html-kitchen-sink/stories/addon-knobs.stories.js
  examples/official-storybook/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/official-storybook/stories/addon-knobs.stories.js
  examples/react-native-vanilla/__tests__/__snapshots__/storyshots.js.snap
  examples/react-native-vanilla/storybook/stories/Knobs/index.js
Labels: addon: knobs, feature request

#3918 Add additional device options to addon-viewport
  addons/viewport/src/manager/components/tests/Panel.test.js
  addons/viewport/src/shared/index.js
Labels: addon: viewport, feature request, patch

#3914 REFACTOR layout and REMOVE usplit component
  lib/components/src/layout/__snapshots__/index.stories.storyshot
  lib/components/src/layout/desktop.js
  lib/components/src/layout/usplit.js
Labels: maintenance, ui

#3924 Typo
  docs/src/pages/addons/using-addons/index.md
Labels: documentation, patch

#3926 Update GumGum examples to include source link
  docs/src/pages/examples/_examples.yml
Labels: documentation, patch

#3934 Fix company name for percy.io
  docs/src/pages/testing/css-style-testing/index.md
Labels: documentation, patch

#3923 addons-jest : bug with the jest parameter
  addons/jest/src/index.js
Labels: bug, patch

#3930 Add customizePage method to imageSnapshot
  addons/storyshots/storyshots-core/README.md
  addons/storyshots/storyshots-puppeteer/README.md
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storyshots/storyshots-puppeteer/src/index.js
  lib/cli/test/snapshots/polymer/package.json
Labels: addon: storyshots, feature request

#3935 Fix grammar,spelling and punctuation!
  CONTRIBUTING.md
Labels: documentation
