Repository storybookjs/storybook, pull requests merged in 2019-10, with the labels that each got.

#8235 Bump react-native-swipe-gestures to 1.0.4
  app/react-native/package.json
  yarn.lock
Labels: app: react-native, dependencies:update

#8236 Fix require cycles in addons hooks
  lib/addons/src/hooks.ts
Labels: api: addons, bug

#8237 Line 94 (New Line)
  README.md
Labels: documentation, patch

#8256 REMOVE hooks from extracted StoryItem
  lib/client-api/src/story_store.ts
Labels: api: stories, core, feature request, performance issue

#8254 Added `AntDesign` to Preset Gallery
  docs/src/pages/presets/preset-gallery/index.md
Labels: documentation, patch

#8261 Validate the state content in addon-ondevice-notes
  addons/ondevice-notes/src/components/Notes.tsx
Labels: addon: notes, app: react-native, bug

#8263 REGEN lockfile
  addons/actions/src/containers/ActionLogger/index.tsx
  addons/jest/src/hoc/provideJestResult.tsx
  addons/knobs/src/components/Panel.tsx
  addons/knobs/src/components/types/Color.tsx
  addons/knobs/src/components/types/Date.tsx
  app/react-native/src/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view.tsx
  app/react-native/src/preview/components/OnDeviceUI/index.tsx
  app/react-native/src/preview/index.tsx
  docs/src/templates/_docstemplate.jsx
  lib/api/src/index.tsx
  lib/cli/generators/.eslintrc.js
  lib/cli/test/fixtures/react_babel_6/package.json
  lib/ui/src/components/sidebar/treeview/treeview.js
  yarn.lock
Labels: maintenance

#8257 docs(deployment): add instructions about deployment on ZEIT Now
  docs/src/pages/basics/exporting-storybook/index.md
Labels: documentation, patch

#8260 #8211
  lib/components/src/typography/DocumentFormatting.tsx
  lib/components/src/typography/DocumentWrapper.tsx
Labels: bug, patch, theming

#8275 Update Addons-Storysource README.md
  addons/storysource/README.md
Labels: addon: storysource, documentation, patch

#8271 UI: Preferred color scheme awareness
  docs/src/pages/configurations/theming/index.md
  lib/core/src/client/preview/start.test.js
  lib/core/src/typings.d.ts
  lib/core/tsconfig.json
  lib/theming/src/convert.ts
  lib/theming/src/create.ts
  lib/theming/src/tests/util.test.js
  lib/theming/src/typings.d.ts
  lib/theming/src/utils.ts
  scripts/jest.init.js
Labels: feature request, ui

#8273 Fix link to Storybook's storybook
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch

#8283 Official examples: apply babel-preset-minify only in production mode
  examples/official-storybook/webpack.config.js
Labels: babel / webpack, maintenance

#8282 Fix button knob story
  examples/official-storybook/stories/addon-knobs/with-knobs.stories.js
Labels: babel / webpack, maintenance

#8285 Remove duplicate code
  app/react/src/client/preview/globals.ts
  app/vue/src/client/preview/globals.ts
  lib/core/src/server/templates/base-manager-head.html
  lib/core/src/server/templates/base-preview-head.html
Labels: app: react, cleanup

#8289 Fix local `yarn lint`
  .eslintignore
  .eslintrc.js
  addons/events/src/components/Event.tsx
  examples/angular-cli/.eslintignore
  examples/angular-cli/.eslintrc.js
  examples/angular-cli/src/stories/addon-jest.stories.ts
  examples/cra-kitchen-sink/src/components/LifecycleLogger.js
  examples/ember-cli/.eslintignore
  lib/cli-sb/README.md
  lib/cli-storybook/README.md
  lib/ui/src/components/layout/container.js
Labels: cleanup

#8246 UPGRADE chromatic to test
  examples/official-storybook/config.js
  examples/official-storybook/package.json
  package.json
  yarn.lock
Labels: dependencies:update

#8258 Upgrade regenerator-runtime to 0.13 in all packages
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/marko/package.json
  app/mithril/package.json
  app/polymer/package.json
  app/preact/package.json
  app/rax/package.json
  app/react/package.json
  app/riot/package.json
  app/svelte/package.json
  app/vue/package.json
  lib/codemod/package.json
  lib/core/package.json
  lib/node-logger/package.json
  lib/source-loader/package.json
  package.json
Labels: dependencies:update

#8287 Addon-knobs: Fix issues caused by rerenders
  addons/knobs/src/KnobManager.test.js
  addons/knobs/src/KnobManager.ts
  addons/knobs/src/KnobStore.ts
  app/riot/package.json
  examples/official-storybook/stories/addon-knobs/with-knobs-decorators.stories.js
  examples/official-storybook/stories/addon-knobs/with-knobs.stories.js
  lib/addons/src/hooks.ts
  lib/client-api/src/hooks.test.js
  yarn.lock
Labels: addon: knobs, api: addons, bug, patch

#8100 Core: Show exception rather than error on react error boundary
  app/react/src/client/preview/render.tsx
  app/react/src/client/preview/types.ts
Labels: bug, core, high priority, patch

#8291 Remove mentions of @types/storybook__react
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#8064 ADD cli test in github actions
  .github/workflows/tests-cli.yml
  .github/workflows/tests-unit.yml
  .travis.yml
  docs/package.json
Labels: cli, maintenance

#8281 Don't use `global` package in templates
  lib/cli/generators/.eslintrc.js
  lib/cli/generators/HTML/template/stories/index.stories.js
Labels: bug, cli, patch

#8299 Update `read-pkg-up` usage to work with version `7`
  addons/storyshots/storyshots-core/src/frameworks/hasDependency.js
Labels: addon: storyshots, bug, high priority

#8300 Remove `weak` dependency for Node 12 compat
  package.json
  yarn.lock
Labels: compatibility with other tools, maintenance

#8309 Update storysource README and imagery
  addons/storysource/README.md
  addons/storysource/docs/demo.gif
  addons/storysource/docs/theming-light-dark.png
Labels: addon: storysource, documentation, patch

#8133 Merge pull request #8133 from storybookjs/multiple
  lib/core/src/client/preview/start.js
Labels: csf, feature request

#8266 Upgrade react-syntax-highlighter to the latest version
  addons/storysource/package.json
  addons/storysource/src/StoryPanel.js
  jest.config.js
  lib/components/package.json
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
  yarn.lock
Labels: dependencies:update

#8197 IMPROVE type of storyFn for react
  app/react/src/client/preview/types.ts
Labels: app: react, bug, typescript

#8317 CSF: Ignore __esModule export
  lib/core/src/client/preview/start.js
  lib/core/src/client/preview/start.test.js
Labels: bug, csf, patch

#8310 Remove redundant dependency on hoist-non-react-statics (#6349)
  addons/a11y/package.json
Labels: dependencies

#8313 Addon-docs: Story parameter for disabling docs
  addons/docs/docs/recipes.md
  addons/docs/src/blocks/DocsPage.tsx
  addons/docs/src/blocks/Story.tsx
  examples/official-storybook/stories/addon-docs/addon-docs.stories.js
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
Labels: addon: docs, feature request

#8323 Remove `next` tag from docs
  addons/docs/README.md
Labels: documentation, patch

#8312 MDX: Better ergonomics for documenting CSF
  addons/docs/docs/recipes.md
  addons/docs/src/blocks/index.ts
  addons/docs/src/mdx/__snapshots__/mdx-compiler-plugin.test.js.snap
  addons/docs/src/mdx/__testfixtures__/story-function-var.mdx
  addons/docs/src/mdx/mdx-compiler-plugin.js
  addons/docs/src/mdx/mdx-compiler-plugin.test.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.mdx
Labels: addon: docs, csf, feature request

#8120 add missing types for recommended addon-centered imports
  addons/centered/ember.d.ts
  addons/centered/html.d.ts
  addons/centered/mithril.d.ts
  addons/centered/package.json
  addons/centered/preact.d.ts
  addons/centered/react.d.ts
  addons/centered/svelte.d.ts
  addons/centered/vue.d.ts
Labels: bug, patch, typescript

#7929 Addon-docs: support vue inline rendering
  addons/docs/docs/docspage.md
  addons/docs/package.json
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/frameworks/react/config.js
  addons/docs/src/frameworks/vue/config.js
  addons/storyshots/storyshots-core/src/Stories2SnapsConverter.ts
  examples/angular-cli/.storybook/config.ts
  examples/vue-kitchen-sink/.storybook/config.js
  examples/vue-kitchen-sink/src/stories/Button.vue
  examples/vue-kitchen-sink/src/stories/addon-docs.stories.mdx
  examples/vue-kitchen-sink/src/stories/components/button.stories.js
  examples/vue-kitchen-sink/src/stories/custom-decorators.stories.js
  yarn.lock
Labels: addon: docs, app: vue, feature request

#8341 Fix typo in duplicated story warning
  lib/client-api/src/story_store.ts
Labels: documentation, patch

#8348 Remove spurious flag to build in Ember
  docs/src/pages/guides/guide-ember/index.md
Labels: documentation, patch

#8354 Publish top-level .js and .d.ts files
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/contexts/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/events/package.json
  addons/graphql/package.json
  addons/info/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/notes/package.json
  addons/ondevice-actions/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  addons/options/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/marko/package.json
  app/mithril/package.json
  app/polymer/package.json
  app/preact/package.json
  app/rax/package.json
  app/react-native-server/package.json
  app/react-native/package.json
  app/react/package.json
  app/riot/package.json
  app/svelte/package.json
  app/vue/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/channels/package.json
  lib/cli/package.json
  lib/client-api/package.json
  lib/client-logger/package.json
  lib/codemod/package.json
  lib/components/package.json
  lib/core-events/package.json
  lib/core/package.json
  lib/node-logger/package.json
  lib/router/package.json
  lib/source-loader/package.json
  lib/theming/package.json
  lib/ui/package.json
Labels: maintenance, patch

#8365 MDX: Docs for annotating CSF with arbitrary MDX
  addons/docs/docs/recipes.md
Labels: csf, documentation, patch

#8359 Fix typo in Introduction: React UI Testing page
  docs/src/pages/testing/react-ui-testing/index.md
Labels: documentation, patch

#8374 Fix typo in writing stories section
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8369 Update button.svelte
  lib/cli/generators/SVELTE/template/stories/button.svelte
Labels: app: svelte, bug, cli, patch

#8378 Fix link
  addons/docs/docs/docspage.md
Labels: documentation, patch

#8269 Angular: Fix angular2-template-loader / raw-loader version conflicts
  app/angular/package.json
  app/angular/src/server/framework-preset-angular.ts
  app/angular/src/server/ngx-template-loader/index.ts
  yarn.lock
Labels: app: angular, bug, patch

#8393 Fix svelte typo
  docs/src/pages/guides/guide-svelte/index.md
Labels: documentation, patch

#8403 Addon-docs: Fix typo in default config
  addons/docs/src/frameworks/react/config.js
Labels: addon: docs, bug

#8402 chore: replace link URL from stroybook-chrome-screenshot to storycap
  docs/src/pages/addons/addon-gallery/index.md
Labels: documentation, patch

#8408 Addon API: Clean preview hooks when removing a story
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
Labels: bug, client-api, patch

#8407 Official-storybook: Add a story with duplicate decorators
  examples/official-storybook/stories/addon-knobs/with-knobs.stories.js
Labels: maintenance

#8411 CSF: Warn when CSF and `storiesOf` mixed in one file
  lib/client-api/src/client_api.ts
Labels: bug, patch

#8415 Addon-docs: Don't error in React when there's no `prepareForInline`
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/frameworks/react/config.js
Labels: addon: docs, bug

#8351 [Security] Bump lodash from 4.17.11 to 4.17.15
  addons/docs/package.json
  addons/events/package.json
  addons/knobs/package.json
  app/react/package.json
  examples/official-storybook/package.json
  lib/api/package.json
  lib/client-api/package.json
  lib/codemod/package.json
  lib/router/package.json
  lib/ui/package.json
  package.json
Labels: dependencies:update, patch, security

#8410 Update index.ts of jest addon to make withTests type generic
  addons/jest/src/index.ts
Labels: addon: jest, bug, patch, typescript

#8416 React: Move Create React App support to external preset
  MIGRATION.md
  app/react/README.md
  app/react/package.json
  app/react/src/server/framework-preset-cra.ts
  docs/src/pages/configurations/typescript-config/index.md
  docs/src/pages/guides/guide-react/index.md
  docs/src/pages/presets/preset-gallery/index.md
  lib/cli/generators/REACT_SCRIPTS/index.js
Labels: app: react, cra, feature request

#8259 Fix custom themes breaking the welcome demo.
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.enzyme.test.js.snap
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.snapshotWithOptionsFunction.test.js.snap
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.foo
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.storyshot
  app/react/src/demo/Welcome.tsx
Labels: app: react, bug, patch, theming

#8421 Presets-doc: Fixing the advanced configuration
  docs/src/pages/presets/writing-presets/index.md
Labels: documentation, patch

#8419 Addon-docs: Fix react inline stories
  addons/docs/src/frameworks/react/config.js
Labels: addon: docs, bug

#7966 Addon-docs: Support MDX source in Preview w/ no Story blocks
  addons/docs/src/blocks/Preview.tsx
  addons/docs/src/mdx/__snapshots__/mdx-compiler-plugin.test.js.snap
  addons/docs/src/mdx/__testfixtures__/previews.mdx
  addons/docs/src/mdx/mdx-compiler-plugin.js
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
Labels: addon: docs, feature request, in progress

#8424 Correct usage of getchannel
  addons/backgrounds/README.md
Labels: documentation, patch

#8430 Tech/cypress in orbs
  .circleci/config.yml
  .gitignore
  cypress/fixtures/example.json
  cypress/helper.ts
  cypress/integration/knobs.spec.ts
  cypress/integration/navigation.spec.ts
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: do not merge

#8429 add missing import to code example
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch

#8449 CLI: Add preset-create-react-app to CRA presets template
  lib/cli/generators/REACT_SCRIPTS/template-csf/.storybook/presets.js
Labels: bug, cli

#8442 Addon-centered: Fix zoom issues for non-Firefox browsers
  lib/ui/src/components/preview/iframe.js
Labels: addon: centered, bug

#8440 Source-loader: Fix CSF typescript parser
  __mocks__/inject-decorator.ts.csf.txt
  lib/source-loader/src/server/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.snap
  lib/source-loader/src/server/abstract-syntax-tree/generate-helpers.js
  lib/source-loader/src/server/abstract-syntax-tree/inject-decorator.csf.test.js
  lib/source-loader/src/server/abstract-syntax-tree/traverse-helpers.js
Labels: bug, source-loader

#8452 CLI: Add CRA preset to MDX template
  lib/cli/generators/REACT_SCRIPTS/template-mdx/.storybook/presets.js
Labels: bug, cli

#8454 UI: Remove emotion from NoDocs.js
  lib/core/src/client/preview/NoDocs.js
Labels: app: react, bug, patch

#8451 CLI: React-scripts TS template & test
  lib/cli/bin/generate.js
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/.storybook/addons.ts
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/.storybook/config.ts
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/.storybook/presets.js
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/src/stories/0-Welcome.stories.tsx
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/src/stories/1-Button.stories.tsx
  lib/cli/test/fixtures/react_scripts_ts/README.md
  lib/cli/test/fixtures/react_scripts_ts/package.json
  lib/cli/test/fixtures/react_scripts_ts/public/favicon.ico
  lib/cli/test/fixtures/react_scripts_ts/public/index.html
  lib/cli/test/fixtures/react_scripts_ts/public/logo192.png
  lib/cli/test/fixtures/react_scripts_ts/public/logo512.png
  lib/cli/test/fixtures/react_scripts_ts/public/manifest.json
  lib/cli/test/fixtures/react_scripts_ts/public/robots.txt
  lib/cli/test/fixtures/react_scripts_ts/src/App.css
  lib/cli/test/fixtures/react_scripts_ts/src/App.test.tsx
  lib/cli/test/fixtures/react_scripts_ts/src/App.tsx
  lib/cli/test/fixtures/react_scripts_ts/src/index.css
  lib/cli/test/fixtures/react_scripts_ts/src/index.tsx
  lib/cli/test/fixtures/react_scripts_ts/src/logo.svg
  lib/cli/test/fixtures/react_scripts_ts/src/react-app-env.d.ts
  lib/cli/test/fixtures/react_scripts_ts/src/serviceWorker.ts
  lib/cli/test/fixtures/react_scripts_ts/tsconfig.json
  lib/cli/test/run_tests.sh
Labels: cli, feature request

#8460 :pencil: added react pakistan example
  docs/src/pages/examples/_examples.yml
  docs/src/pages/examples/thumbnails/react-pakistan.jpg
Labels: addon: docs, patch

#8448 Update Docs class name escape hatches
  addons/docs/docs/theming.md
Labels: documentation, patch

#8397 Add cypress to Storybook CI
  .circleci/config.yml
  .github/workflows/tests-unit.yml
  .gitignore
  cypress.json
  cypress/.eslintrc.json
  cypress/fixtures/example.json
  cypress/helper.ts
  cypress/integration/knobs.spec.ts
  cypress/integration/navigation.spec.ts
  cypress/plugins/index.js
  cypress/plugins/webpack.config.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  examples/ember-cli/package.json
  examples/official-storybook/stories/app-acceptance.stories.js
  package.json
  scripts/build-storybooks.js
  yarn.lock
Labels: maintenance

#8427 Incorrect minimal required node version
  package.json
Labels: dependencies

#8462 CLI: Add component meta to framework templates
  lib/cli/generators/ANGULAR/template-csf/src/stories/0-Welcome.stories.ts
  lib/cli/generators/ANGULAR/template-csf/src/stories/1-Button.stories.ts
  lib/cli/generators/ANGULAR/template-mdx/src/stories/0-Welcome.stories.mdx
  lib/cli/generators/ANGULAR/template-mdx/src/stories/1-Button.stories.mdx
  lib/cli/generators/MARKO/template-csf/stories/index.stories.js
  lib/cli/generators/METEOR/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/METEOR/template-csf/stories/1-Button.stories.js
  lib/cli/generators/MITHRIL/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/MITHRIL/template-csf/stories/1-Button.stories.js
  lib/cli/generators/PREACT/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/PREACT/template-csf/stories/1-Button.stories.js
  lib/cli/generators/RAX/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/REACT/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/REACT/template-csf/stories/1-Button.stories.js
  lib/cli/generators/REACT/template-mdx/stories/0-Welcome.stories.mdx
  lib/cli/generators/REACT/template-mdx/stories/1-Button.stories.mdx
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/src/stories/0-Welcome.stories.tsx
  lib/cli/generators/REACT_SCRIPTS/template-csf-ts/src/stories/1-Button.stories.tsx
  lib/cli/generators/REACT_SCRIPTS/template-csf/src/stories/0-Welcome.stories.js
  lib/cli/generators/REACT_SCRIPTS/template-csf/src/stories/1-Button.stories.js
  lib/cli/generators/REACT_SCRIPTS/template-mdx/src/stories/0-Welcome.stories.mdx
  lib/cli/generators/REACT_SCRIPTS/template-mdx/src/stories/1-Button.stories.mdx
  lib/cli/generators/SFC_VUE/template-csf/src/stories/0-Welcome.stories.js
  lib/cli/generators/SFC_VUE/template-csf/src/stories/1-Button.stories.js
  lib/cli/generators/SFC_VUE/template-mdx/src/stories/0-Welcome.stories.mdx
  lib/cli/generators/SFC_VUE/template-mdx/src/stories/1-Button.stories.mdx
  lib/cli/generators/SVELTE/template-csf/stories/index.stories.js
  lib/cli/generators/VUE/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/VUE/template-csf/stories/1-Button.stories.js
  lib/cli/generators/VUE/template-mdx/stories/0-Welcome.stories.mdx
  lib/cli/generators/VUE/template-mdx/stories/1-Button.stories.mdx
  lib/cli/generators/WEBPACK_REACT/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/WEBPACK_REACT/template-csf/stories/1-Button.stories.js
  lib/cli/generators/WEBPACK_REACT/template-mdx/stories/0-Welcome.stories.mdx
  lib/cli/generators/WEBPACK_REACT/template-mdx/stories/1-Button.stories.mdx
Labels: cli, feature request

#8465 Update Storyshots README w/ instructions per loading method
  addons/storyshots/storyshots-core/README.md
Labels: documentation, patch

#8320 Typescript: Migrate @storybook/mithril
  addons/docs/src/blocks/Preview.tsx
  addons/jest/src/index.ts
  app/mithril/package.json
  app/mithril/src/client/index.ts
  app/mithril/src/client/preview/globals.ts
  app/mithril/src/client/preview/index.js
  app/mithril/src/client/preview/index.ts
  app/mithril/src/client/preview/render.ts
  app/mithril/src/client/preview/types.ts
  app/mithril/src/server/build.ts
  app/mithril/src/server/framework-preset-mithril.ts
  app/mithril/src/server/index.ts
  app/mithril/src/server/options.ts
  app/mithril/src/typings.d.ts
  app/mithril/tsconfig.json
  yarn.lock
Labels: app: mithril, maintenance, typescript

#7668 Angular: Convert angular-cli stories to CSF
  examples/angular-cli/jest.config.js
  examples/angular-cli/src/stories/__snapshots__/addon-actions.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-background.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-centered.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-jest.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-links.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/addon-notes.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/app.component.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/core.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/custom-pipes.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/custom-providers.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/custom-styles.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/index.stories.storyshot
  examples/angular-cli/src/stories/addon-actions.stories.ts
  examples/angular-cli/src/stories/addon-jest.stories.ts
  examples/angular-cli/src/stories/addon-knobs.stories.ts
  examples/angular-cli/src/stories/addon-links.stories.ts
  examples/angular-cli/src/stories/addon-notes.stories.ts
  examples/angular-cli/src/stories/app.component.stories.ts
  examples/angular-cli/src/stories/component-with-di/__snapshots__/di.component.stories.storyshot
  examples/angular-cli/src/stories/component-with-di/di.component.stories.ts
  examples/angular-cli/src/stories/component-with-style/__snapshots__/styled.component.stories.storyshot
  examples/angular-cli/src/stories/component-with-style/styled.component.stories.ts
  examples/angular-cli/src/stories/core.stories.ts
  examples/angular-cli/src/stories/custom-pipes.stories.ts
  examples/angular-cli/src/stories/custom-providers.stories.ts
  examples/angular-cli/src/stories/custom-styles.stories.ts
  examples/angular-cli/src/stories/customControlValueAccessor/__snapshots__/custom-cva-component.stories.storyshot
  examples/angular-cli/src/stories/customControlValueAccessor/custom-cva-component.stories.ts
  examples/angular-cli/src/stories/inheritance/__snapshots__/inheritance.stories.storyshot
  examples/angular-cli/src/stories/inheritance/inheritance.stories.ts
  examples/angular-cli/src/stories/metadata-combined.stories.ts
  examples/angular-cli/src/stories/metadata-individual.stories.ts
  examples/angular-cli/src/stories/metadata-shared.stories.ts
  examples/angular-cli/src/stories/module-context/__snapshots__/module-context-forRoot.stories.storyshot
  examples/angular-cli/src/stories/module-context/__snapshots__/module-context.stories.storyshot
  examples/angular-cli/src/stories/on-push/__snapshots__/on-push.stories.storyshot
  examples/angular-cli/src/stories/on-push/on-push.stories.ts
Labels: app: angular, csf, maintenance

#8412 Core: Check module type in configure
  lib/core/src/client/preview/start.js
Labels: core, maintenance

#8469 MDX: Handle `<Story>` name starting with number
  addons/docs/src/mdx/__snapshots__/mdx-compiler-plugin.test.js.snap
  addons/docs/src/mdx/__testfixtures__/story-definitions.mdx
  addons/docs/src/mdx/mdx-compiler-plugin.js
Labels: bug, mdx, patch

#8477 ADD a step in circleci to upload storybook for angular
  .circleci/config.yml
  examples/angular-cli/package.json
  package.json
Labels: maintenance

#8459 Build: Fix flaky story
  lib/ui/src/components/layout/layout.stories.js
  lib/ui/src/components/layout/persist.js
Labels: maintenance

#8391 Enabled error details webpack
  lib/core/src/server/dev-server.js
Labels: babel / webpack, feature request

#8445 Addon-docs: Fix React.forwardedRef/memo props
  addons/docs/src/lib/getPropDefs.ts
  examples/official-storybook/stories/addon-docs/forward-ref.stories.js
  examples/official-storybook/stories/addon-docs/react-memo.stories.js
Labels: addon: docs, bug, patch

#8491 React-native-server: Convert port to number in CLI options
  app/react-native-server/src/server/cli.js
Labels: app: react-native-server, bug, patch

#8493 highlight ts and tsx syntax
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: feature request, ui

#8503 Add "@types/react-textarea-autosize" to dependencies
  lib/components/package.json
Labels: dependencies, patch, typescript

#8497 docs: fix typo in MIGRATION (inadverttly -> inadvertently)
  MIGRATION.md
Labels: documentation, patch

#8400 feat: adds new app "web-components"
  addons/docs/src/frameworks/web-components/config.js
  addons/docs/web-components/config.js
  addons/docs/web-components/index.js
  addons/docs/web-components/preset.js
  app/web-components/README.md
  app/web-components/bin/build.js
  app/web-components/bin/index.js
  app/web-components/package.json
  app/web-components/src/client/index.ts
  app/web-components/src/client/preview/globals.ts
  app/web-components/src/client/preview/index.ts
  app/web-components/src/client/preview/render.ts
  app/web-components/src/client/preview/types.ts
  app/web-components/src/server/build.ts
  app/web-components/src/server/framework-preset-web-components.ts
  app/web-components/src/server/index.ts
  app/web-components/src/server/options.ts
  app/web-components/src/typings.d.ts
  app/web-components/standalone.js
  app/web-components/tsconfig.json
  examples/web-components-kitchen-sink/.storybook/addons.js
  examples/web-components-kitchen-sink/.storybook/config.js
  examples/web-components-kitchen-sink/.storybook/presets.js
  examples/web-components-kitchen-sink/README.md
  examples/web-components-kitchen-sink/demo-wc-card.js
  examples/web-components-kitchen-sink/package.json
  examples/web-components-kitchen-sink/src/DemoWcCard.js
  examples/web-components-kitchen-sink/src/demoWcCardStyle.css.js
  examples/web-components-kitchen-sink/stories/addon-a11y.stories.js
  examples/web-components-kitchen-sink/stories/addon-actions.stories.js
  examples/web-components-kitchen-sink/stories/addon-backgrounds.stories.js
  examples/web-components-kitchen-sink/stories/addon-docs.stories.mdx
  examples/web-components-kitchen-sink/stories/addon-knobs.stories.js
  examples/web-components-kitchen-sink/stories/card.stories.js
  examples/web-components-kitchen-sink/stories/welcome.stories.js
  lib/cli/generators/WEB-COMPONENTS/index.js
  lib/cli/generators/WEB-COMPONENTS/template/.storybook/config.js
  lib/cli/generators/WEB-COMPONENTS/template/stories/index.stories.js
  yarn.lock
Labels: app: html, feature request

#8498 Core: Allow custom postcss config
  docs/src/pages/configurations/custom-postcss-config/index.md
  examples/html-kitchen-sink/.postcssrc.yml
  examples/html-kitchen-sink/package.json
  examples/html-kitchen-sink/stories/welcome.css
  lib/core/package.json
  lib/core/src/server/preview/base-webpack.config.js
  lib/core/src/server/preview/custom-webpack-preset.js
Labels: core, feature request

#8517 chore: add types for react demo
  app/react/demo.d.ts
Labels: app: react, help wanted, typescript

#8535 Addon-docs: document story description
  addons/docs/docs/docspage.md
Labels: documentation, patch

#8549 Remove outdated and unused `jsx-to-string` library
  addons/info/package.json
  yarn.lock
Labels: addon: info, dependencies

#8546 Prevent form submission as search is done while typing
  lib/ui/src/components/sidebar/SidebarSearch.tsx
Labels: bug, patch, ui

#8545 Increase TooltipLinkList max-height to accommodate more links
  lib/components/src/tooltip/TooltipLinkList.tsx
Labels: bug, patch, ui

#8543 documentation - remove extra word in addons/info readme
  addons/info/README.md
Labels: documentation, patch

#8551 UI docs: Remove dead link from example
  lib/ui/README.md
Labels: documentation, patch

#8488 CLI: Add flag to disable version checks
  lib/api/src/modules/versions.ts
  lib/api/src/tests/versions.test.js
  lib/core/src/server/build-dev.js
  lib/core/src/server/cli/dev.js
  lib/core/src/server/manager/manager-webpack.config.js
Labels: cli, feature request, high priority

#7648 Core: Allow linking to kind/component ID
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.js
Labels: core, feature request

#8559 Update links to Webpack require.context docs
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8489 Addon-docs: Vue slots/events props table + generalization
  __mocks__/inject-decorator.stories.txt
  addons/docs/README.md
  addons/docs/common/index.js
  addons/docs/package.json
  addons/docs/src/blocks/Props.tsx
  addons/docs/src/frameworks/common/index.ts
  addons/docs/src/frameworks/react/config.js
  addons/docs/src/frameworks/react/extractProps.ts
  addons/docs/src/frameworks/vue/config.js
  addons/docs/src/frameworks/vue/extractProps.ts
  addons/docs/src/lib/propsUtils.ts
  addons/docs/src/typings.d.ts
  examples/official-storybook/components/DocgenButton.js
  examples/official-storybook/components/ForwardRefButton.js
  examples/official-storybook/components/ImportedPropsButton.js
  examples/official-storybook/components/MemoButton.js
  examples/official-storybook/stories/addon-docs/addon-docs.stories.js
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
  examples/official-storybook/stories/addon-docs/forward-ref.stories.js
  examples/official-storybook/stories/addon-docs/props.stories.mdx
  examples/official-storybook/stories/addon-docs/react-memo.stories.js
  examples/official-storybook/stories/addon-info/react-docgen.stories.js
  examples/vue-kitchen-sink/.storybook/config.js
  examples/vue-kitchen-sink/src/stories/Button.vue
  examples/vue-kitchen-sink/src/stories/Welcome.vue
  examples/vue-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/custom-decorators.stories.storyshot
  examples/vue-kitchen-sink/src/stories/addon-actions.stories.js
  examples/vue-kitchen-sink/src/stories/addon-docs.stories.mdx
  examples/vue-kitchen-sink/src/stories/addon-links.stories.js
  examples/vue-kitchen-sink/src/stories/components/InfoButton.vue
  examples/vue-kitchen-sink/src/stories/components/__snapshots__/info-button.stories.storyshot
  examples/vue-kitchen-sink/src/stories/components/info-button.stories.js
  examples/vue-kitchen-sink/src/stories/components/welcome.stories.js
  examples/vue-kitchen-sink/src/stories/custom-rendering.stories.js
  lib/components/src/blocks/PropsTable/PropRow.tsx
  lib/components/src/blocks/PropsTable/PropsTable.stories.tsx
  lib/components/src/blocks/PropsTable/PropsTable.tsx
  lib/components/src/blocks/PropsTable/SectionRow.stories.tsx
  lib/components/src/blocks/PropsTable/SectionRow.tsx
  lib/source-loader/src/server/abstract-syntax-tree/__snapshots__/inject-decorator.test.js.snap
Labels: addon: docs, app: react, app: vue, feature request

#8560 Chore: Updated slack logo in docs
  docs/src/components/Footer/images/slack-icon.png
  docs/src/components/Footer/index.js
Labels: documentation, patch

#8563 Addon-docs: Publish web-components preset
  addons/docs/package.json
  lib/cli/generators/WEB-COMPONENTS/index.js
Labels: addon: docs, feature request

#8562 Added example of a decorator in Storybook config
  docs/src/pages/addons/introduction/index.md
Labels: documentation, patch

#8567 Addon-docs: Add props loader to vue preset
  addons/docs/README.md
  addons/docs/docs/multiframework.md
  addons/docs/package.json
  addons/docs/vue/preset.js
  examples/vue-kitchen-sink/.storybook/webpack.config.js
Labels: addon: docs, app: vue, feature request

#8558 Angular: bump zone.js version in peer dependencies
  app/angular/package.json
Labels: app: angular, dependencies

#8566 fixed link to go to the correct section of the docs
  docs/src/pages/configurations/custom-webpack-config/index.md
Labels: documentation, patch

#8574 Addon-docs: Modify Typeset doc block to accept units
  lib/components/src/blocks/Typeset.stories.tsx
  lib/components/src/blocks/Typeset.tsx
Labels: addon: docs, feature request

#8576 Fix typo compponent to component
  lib/codemod/src/transforms/csf-to-mdx.js
  lib/codemod/src/transforms/mdx-to-csf.js
Labels: documentation, patch

#8579 Web-components: Use framework id 'web-components'
  app/web-components/src/client/preview/index.ts
Labels: app: web-components, bug

#8578 WC-kitchen-sink: Add babel-loader dependency
  examples/web-components-kitchen-sink/package.json
Labels: app: web-components, maintenance

#8580 Upgrade babel-plugin-react-docgen to 3.2.0
  app/react/package.json
  yarn.lock
Labels: app: react, dependencies

#8581 Upgrade babel-plugin-react-docgen to 4.0.0-beta.1
  app/react/package.json
  yarn.lock
Labels: addon: docs, app: react, dependencies

#8584 React-native-server: Changed default port to number in CLI options
  app/react-native-server/src/server/cli.js
Labels: app: react-native-server, bug, patch

#8589 FIX now deploy maybe
  examples/official-storybook/package.json
  package.json
Labels: maintenance

#8590 Addon-docs: Generalize Description doc block
  MIGRATION.md
  addons/docs/docs/multiframework.md
  addons/docs/src/blocks/Description.tsx
  addons/docs/src/blocks/DocsPage.tsx
  addons/docs/src/blocks/Props.tsx
  addons/docs/src/frameworks/common/index.ts
  addons/docs/src/frameworks/react/config.js
  addons/docs/src/frameworks/react/extractProps.ts
  addons/docs/src/frameworks/vue/config.js
  addons/docs/src/frameworks/vue/extractProps.ts
  addons/docs/src/lib/docgenUtils.ts
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
  examples/official-storybook/stories/addon-info/react-docgen.stories.js
Labels: BREAKING PRERELEASE, addon: docs, feature request

#8588 Typescript: Use native package types now available
  addons/knobs/src/typings.d.ts
  lib/addons/src/typings.d.ts
  lib/ui/src/settings/typings.d.ts
Labels: maintenance

#8573 Core: Global addDecorator/addParameters
  addons/docs/html/config.js
  addons/docs/src/frameworks/angular/config.js
  addons/docs/src/frameworks/common/config.js
  addons/docs/src/frameworks/common/makePreset.ts
  addons/docs/src/frameworks/html/config.js
  addons/docs/src/frameworks/react/config.ts
  addons/docs/src/frameworks/vue/config.tsx
  addons/docs/src/typings.d.ts
  addons/docs/vue/config.js
  addons/docs/web-components/config.js
  lib/client-api/src/client_api.test.ts
  lib/client-api/src/client_api.ts
  lib/client-api/src/index.ts
Labels: addon: docs, core, feature request

#8585 Addon-docs: Props / Description for web-components
  addons/docs/README.md
  addons/docs/src/frameworks/web-components/config.js
  addons/docs/src/frameworks/web-components/customElements.ts
  addons/docs/src/public_api.ts
  addons/docs/web-components/README.md
  examples/web-components-kitchen-sink/.storybook/config.js
  examples/web-components-kitchen-sink/custom-elements.json
  examples/web-components-kitchen-sink/stories/addon-docs.stories.mdx
  examples/web-components-kitchen-sink/stories/card.stories.js
Labels: addon: docs, feature request

#8592 Web-components: Move custom-elements utils to app
  addons/docs/src/frameworks/web-components/config.js
  addons/docs/src/frameworks/web-components/customElements.ts
  addons/docs/src/public_api.ts
  addons/docs/web-components/README.md
  app/web-components/src/client/customElements.ts
  app/web-components/src/client/index.ts
  examples/web-components-kitchen-sink/.storybook/config.js
Labels: BREAKING PRERELEASE, addon: docs, app: web-components, maintenance

#8471 Add the missing dependency in storybook/ui
  lib/ui/package.json
Labels: maintenance, ui

#8205 FIX cli init #6002 - throw error "Cannot create property 'dependencies' on boolean 'false'"
  lib/cli/generators/ANGULAR/index.js
  lib/cli/generators/EMBER/index.js
  lib/cli/generators/HTML/index.js
  lib/cli/generators/MARKO/index.js
  lib/cli/generators/METEOR/index.js
  lib/cli/generators/MITHRIL/index.js
  lib/cli/generators/POLYMER/index.js
  lib/cli/generators/PREACT/index.js
  lib/cli/generators/RAX/index.js
  lib/cli/generators/REACT/index.js
  lib/cli/generators/REACT_NATIVE/index.js
  lib/cli/generators/REACT_SCRIPTS/index.js
  lib/cli/generators/RIOT/index.js
  lib/cli/generators/SFC_VUE/index.js
  lib/cli/generators/SVELTE/index.js
  lib/cli/generators/VUE/index.js
  lib/cli/generators/WEBPACK_REACT/index.js
  lib/cli/lib/helpers.js
Labels: bug, cli, patch

#8480 Fix react native style
  app/react-native/src/preview/components/OnDeviceUI/addons/index.tsx
  app/react-native/src/preview/components/OnDeviceUI/navigation/bar.tsx
  app/react-native/src/preview/components/OnDeviceUI/navigation/button.tsx
  app/react-native/src/preview/components/OnDeviceUI/navigation/visibility-button.tsx
  app/react-native/src/preview/components/OnDeviceUI/panel.tsx
  app/react-native/src/preview/components/StoryListView/index.tsx
Labels: app: react-native, bug

#8610 Missing Comma
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8615 FIX cli
  lib/cli/generators/ANGULAR/index.js
  lib/cli/generators/EMBER/index.js
  lib/cli/generators/HTML/index.js
  lib/cli/generators/MARKO/index.js
  lib/cli/generators/METEOR/index.js
  lib/cli/generators/MITHRIL/index.js
  lib/cli/generators/POLYMER/index.js
  lib/cli/generators/PREACT/index.js
  lib/cli/generators/RAX/index.js
  lib/cli/generators/REACT/index.js
  lib/cli/generators/REACT_NATIVE/index.js
  lib/cli/generators/REACT_SCRIPTS/index.js
  lib/cli/generators/RIOT/index.js
  lib/cli/generators/SFC_VUE/index.js
  lib/cli/generators/SVELTE/index.js
  lib/cli/generators/VUE/index.js
  lib/cli/generators/WEB-COMPONENTS/index.js
  lib/cli/generators/WEBPACK_REACT/index.js
Labels: bug, cli, high priority

#8612 UPGRADES
  addons/a11y/src/components/Report/__snapshots__/HighlightToggle.test.js.snap
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
  addons/graphql/package.json
  addons/info/src/__snapshots__/index.test.js.snap
  addons/storyshots/storyshots-puppeteer/package.json
  app/angular/package.json
  docs/package.json
  docs/yarn.lock
  examples/cra-ts-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/preact-kitchen-sink/src/stories/__snapshots__/addon-centered.stories.storyshot
  lib/core/package.json
  lib/router/src/router.tsx
  package.json
  yarn.lock
Labels: dependencies:update, doc-dependencies:update

#8598 Addon-docs/web-components: Add attributes to props table
  addons/docs/src/frameworks/web-components/config.js
  examples/web-components-kitchen-sink/custom-elements.json
  examples/web-components-kitchen-sink/custom-elements.md
  examples/web-components-kitchen-sink/src/DemoWcCard.js
  examples/web-components-kitchen-sink/src/demoWcCardStyle.css.js
Labels: addon: docs, app: web-components, bug

#8627 Clean up Channel test
  lib/channels/src/index.test.ts
Labels: maintenance

#8363 Stop inserting HTML tags from error messages
  lib/core/src/client/preview/start.js
Labels: bug

#8632 Addon-docs: Fix props table in no props case
  lib/components/src/blocks/PropsTable/PropsTable.tsx
Labels: addon: docs, bug

#8629 Addon-docs: Fix story scroll-to heuristics
  addons/docs/src/blocks/DocsContainer.tsx
  lib/core/src/client/preview/start.js
Labels: addon: docs, bug, patch

#8633 Addon-notes: Add key to render function
  addons/notes/src/register.tsx
Labels: addon: notes, bug, patch

#8643 Ondevice-knobs: Fix peer dep
  addons/ondevice-knobs/package.json
Labels: addon: knobs, app: react-native, bug

#8644 Ondevice-knobs: Fix peer dep
  addons/ondevice-knobs/package.json
Labels: addon: knobs, app: react-native, bug

#8642 Added documentation note for vue decorators.
  docs/src/pages/basics/writing-stories/index.md
Labels: app: vue, documentation, patch
