Repository storybookjs/storybook, pull requests merged in 2019-06, with the labels that each got.

#6940 Improve tsconfig.app.json detection for app/angular
  lib/cli/generators/ANGULAR/angular-helpers.js
  lib/cli/generators/ANGULAR/index.js
  lib/cli/generators/ANGULAR/template/.storybook/tsconfig.json
  lib/cli/lib/helpers.js
Labels: app: angular, maintenance, patch, typescript

#6944 [documentation] Fixed function signature
  addons/storyshots/storyshots-puppeteer/README.md
Labels: documentation

#6900 feat: merge global parameters
  lib/client-api/src/client_api.js
  lib/client-api/src/client_api.test.js
Labels: bug, core

#6946 Fix webpack `process.*` variable definitions
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: babel / webpack, bug

#6929 Add 'addParameters' to index.d.ts for angular.
  app/angular/src/client/preview/index.d.ts
Labels: app: angular, maintenance, typescript

#6952 Updated @storybook/addon-jest README.md installation instructions
  addons/jest/README.md
Labels: documentation

#6887 Mention TSX index file requirement in README
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#6912 Typo in writing-addons/index.md
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch

#6719 Add copy button for individual story
  lib/ui/package.json
  lib/ui/src/components/preview/__snapshots__/preview.stories.storyshot
  lib/ui/src/components/preview/preview.js
Labels: feature request, ui

#6971 Add a migration guide for Angular 7 and Storybook 5.0.x to 5.1.x
  MIGRATION.md
Labels: app: angular, bug, documentation

#6969 Added homepage, description & keywords
  package.json
Labels: documentation

#6847 Feature/jest design changes
  addons/jest/src/components/Indicator.ts
  addons/jest/src/components/Message.tsx
  addons/jest/src/components/Panel.tsx
Labels: addon: jest, bug

#6957 WIP: Remove zonejs from devDeps; allow ^0.8.0 || ^0.9.0
  app/angular/package.json
Labels: app: angular, bug

#6968 FIX the customCanvas option
  app/react-native-server/src/client/manager/provider.js
  lib/api/src/modules/layout.ts
  lib/ui/src/components/preview/preview.js
  lib/ui/src/containers/nav.js
  lib/ui/src/containers/preview.js
Labels: app: react-native-server, bug, ui

#6956 FIX race condition in startup of verdaccio && FIX typos
  scripts/run-registry.js
Labels: maintenance

#6977 Update RN guide for 5.1
  docs/src/pages/guides/guide-react-native/index.md
Labels: app: react-native-server, documentation

#6759 Better addon apis & devkits for addons
  .circleci/config.yml
  .teamcity/OpenSourceProjects_Storybook/buildTypes/OpenSourceProjects_Storybook_Bootstrap.kt
  ADDONS_SUPPORT.md
  README.md
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
  addons/backgrounds/src/containers/BackgroundSelector.tsx
  addons/design-assets/README.md
  addons/design-assets/package.json
  addons/design-assets/register.js
  addons/design-assets/src/constants.ts
  addons/design-assets/src/panel.tsx
  addons/design-assets/src/register.tsx
  addons/design-assets/tsconfig.json
  dev-kits/addon-parameter/README.md
  dev-kits/addon-parameter/package.json
  dev-kits/addon-parameter/register.js
  dev-kits/addon-parameter/src/constants.ts
  dev-kits/addon-parameter/src/register.tsx
  dev-kits/addon-parameter/tsconfig.json
  dev-kits/addon-roundtrip/README.md
  dev-kits/addon-roundtrip/package.json
  dev-kits/addon-roundtrip/register.js
  dev-kits/addon-roundtrip/src/constants.ts
  dev-kits/addon-roundtrip/src/index.ts
  dev-kits/addon-roundtrip/src/panel.tsx
  dev-kits/addon-roundtrip/src/register.tsx
  dev-kits/addon-roundtrip/tsconfig.json
  docs/.babelrc
  docs/package.json
  docs/src/components/Docs/Content/index.js
  docs/src/components/Docs/Content/style.css
  docs/src/components/Highlight.js
  docs/src/pages/addons/api/index.md
  docs/src/pages/addons/writing-addons/index.md
  docs/yarn.lock
  examples/dev-kits/README.md
  examples/dev-kits/addons.js
  examples/dev-kits/config.js
  examples/dev-kits/package.json
  examples/dev-kits/stories/addon-roundtrip.js
  examples/official-storybook/addons.js
  examples/official-storybook/package.json
  examples/official-storybook/stories/__snapshots__/addon-design-assets.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  examples/official-storybook/stories/addon-design-assets.stories.js
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/addons/src/index.ts
  lib/api/package.json
  lib/api/src/index.tsx
  lib/api/src/modules/addons.ts
  lib/api/src/modules/stories.ts
  lib/api/src/store.ts
  lib/components/src/ActionBar/ActionBar.tsx
  lib/components/src/addon-panel/addon-panel.tsx
  lib/components/src/index.ts
  lib/components/src/syntaxhighlighter/__snapshots__/syntaxhighlighter.stories.storyshot
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
  package.json
  yarn.lock
Labels: api: addons, do not merge, documentation

#6988 Fix typo in Context addon README
  addons/contexts/README.md
Labels: addon: contexts, documentation, patch

#6987 Don't mutate user's babel config
  lib/core/src/server/utils/load-custom-babel-config.js
Labels: babel / webpack, bug, core, patch

#6950 CHANGE ResizeDetector to SizeMe
  lib/ui/package.json
  lib/ui/src/app.js
  yarn.lock
Labels: maintenance, performance issue, ui

#6991 Don't redefine `process` variable
  lib/core/src/server/manager/manager-webpack.config.js
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: babel / webpack, bug, core, patch

#6970 Fix links that are not working with plain left click
  addons/notes/src/Panel.tsx
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/components/src/placeholder/placeholder.stories.tsx
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
  lib/ui/src/settings/about.js
Labels: bug, patch, ui

#6999 docs: Clarify how to get local example running
  CONTRIBUTING.md
Labels: documentation, patch

#7001 Fix grammar in index.md
  docs/src/pages/configurations/default-config/index.md
Labels: documentation, patch

#7008 chore: set react version to 16.8.3 to match react native
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/events/package.json
  addons/info/package.json
  addons/jest/package.json
  addons/storyshots/storyshots-core/package.json
  app/react-native-server/package.json
  dev-kits/addon-parameter/package.json
  dev-kits/addon-roundtrip/package.json
  examples/cra-kitchen-sink/package.json
  examples/cra-ts-kitchen-sink/package.json
  examples/dev-kits/package.json
  examples/official-storybook/package.json
  lib/api/package.json
  lib/components/package.json
  lib/ui/package.json
  package.json
  yarn.lock
Labels: dependencies, patch

#6935 Migrate @storybook/addon-graphql to typescript
  addons/graphql/package.json
  addons/graphql/src/components/FullScreen/index.tsx
  addons/graphql/src/components/FullScreen/style.ts
  addons/graphql/src/index.ts
  addons/graphql/src/manager.tsx
  addons/graphql/src/preview.js
  addons/graphql/src/preview.tsx
  addons/graphql/src/register.ts
  addons/graphql/src/shared.ts
  addons/graphql/src/typings.d.ts
  addons/graphql/tsconfig.json
Labels: addon: graphql, do not merge, maintenance, typescript

#6438 Fix for issue 5932, adding default options to action(s)
  addons/actions/src/preview/__tests__/action.test.js
  addons/actions/src/preview/action.ts
  addons/actions/src/preview/actions.ts
Labels: addon: actions, bug

#7007 Fixing Grammar
  docs/src/pages/guides/guide-react/index.md
Labels: documentation, patch

#7011 Export all components interfaces
  lib/components/src/Button/Button.tsx
  lib/components/src/addon-panel/addon-panel.tsx
  lib/components/src/bar/bar.tsx
  lib/components/src/bar/button.ts
  lib/components/src/bar/separator.tsx
  lib/components/src/icon/svg.tsx
  lib/components/src/spaced/Spaced.tsx
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
  lib/components/src/tabs/tabs.tsx
  lib/components/src/tooltip/ListItem.tsx
  lib/components/src/tooltip/Tooltip.tsx
  lib/components/src/tooltip/WithTooltip.tsx
  lib/components/src/typography/link/link.tsx
Labels: maintenance, typescript

#7013 specifying where to get `withInfo`
  addons/info/README.md
Labels: addon: info, documentation, patch

#7019 Makes header consistent with sb.js.org
  docs/src/components/Docs/Nav/style.css
  docs/src/new-components/basics/shared/site.js
  docs/src/new-components/layout/PageLayout.js
  docs/src/pages/basics/introduction/index.md
  docs/src/pages/guides/quick-start-guide/index.md
Labels: documentation, patch

#7026 documentation: Add note to addon-backgrounds docs Readme. #6915
  addons/backgrounds/README.md
Labels: documentation, patch

#7016 fix: add missing core-js dependency
  app/react-native/package.json
Labels: app: react-native, dependencies, patch

#7051 core-js 3 errors fix
  app/angular/package.json
  app/polymer/package.json
  app/react-native-server/package.json
  app/react/package.json
  examples/dev-kits/package.json
  examples/ember-cli/package.json
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/polymer-cli/package.json
  examples/preact-kitchen-sink/package.json
  examples/riot-kitchen-sink/package.json
  examples/vue-kitchen-sink/package.json
  lib/cli/test/fixtures/riot/package.json
  lib/cli/test/fixtures/sfc_vue/package.json
  lib/cli/test/fixtures/webpack_react/package.json
  lib/cli/test/fixtures/webpack_react_frozen_lock/package.json
  lib/core/package.json
  lib/core/src/server/manager/manager-webpack.config.js
  lib/core/src/server/preview/iframe-webpack.config.js
  lib/ui/package.json
  lib/ui/scripts/__tests__/coreJsAutoUpgradePlugin.js
  lib/ui/scripts/coreJsAutoUpgradePlugin.js
  lib/ui/scripts/webpackDllsConfig.js
  package.json
  yarn.lock
Labels: babel / webpack, bug, patch

#7050 Maintenance: Quick fix for graphql (last query line blanks)
  addons/graphql/src/shared.ts
Labels: addon: graphql, bug, patch

#7053 ADD addon/queryparams
  addons/queryparams/README.md
  addons/queryparams/package.json
  addons/queryparams/src/constants.ts
  addons/queryparams/src/index.ts
  addons/queryparams/src/typings.d.ts
  addons/queryparams/tsconfig.json
  examples/official-storybook/package.json
  examples/official-storybook/stories/__snapshots__/addon-queryparams.stories.storyshot
  examples/official-storybook/stories/addon-queryparams.stories.js
Labels: feature request

#7059 Fixes typo in Introduction doc
  docs/src/pages/basics/introduction/index.md
Labels: documentation, patch

#7057 FIX syntax highlighter plain text not visible
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/components/src/typography/DocumentFormatting.tsx
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
Labels: bug, patch, theming

#7064 CHANGE netlify so it only builds docs
  docs/yarn.lock
  netlify.toml
  scripts/netlify-build.sh
Labels: maintenance

#7082 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, patch

#7080 FIX warning of loading prop not being a string
  lib/ui/src/components/sidebar/SidebarItem.js
Labels: bug, ui

#6938 Fix unresponsive textarea from addon-event
  addons/events/package.json
  addons/events/src/components/Event.js
Labels: addon: events, bug

#7081 Add missing dependencies to ui/react
  app/react/package.json
  lib/ui/package.json
Labels: maintenance

#7073 FIX sidebar loading visibility
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/sidebar/SidebarItem.js
Labels: bug, patch, ui

#7077 chore(notes): add angular documentation
  addons/notes/README.md
Labels: addon: notes, app: angular, documentation, patch

#7086 UPGRADE the plugin for core-js fix
  lib/core/package.json
  lib/ui/package.json
  package.json
  yarn.lock
Labels: babel / webpack, bug, high priority, patch

#7094 Addon-contexts, RN-server: Add core-js dep
  addons/contexts/package.json
  app/react-native-server/package.json
Labels: addon: contexts, dependencies, patch

#7091 FIX unnecessary large bundlesize
  addons/storysource/src/StoryPanel.js
Labels: maintenance, patch, performance issue

#7061 Update CODE_OF_CONDUCT.md with contact details
  CODE_OF_CONDUCT.md
Labels: documentation, patch

#6939 Fix crash when invalid args for library polished's functions
  lib/components/src/tooltip/Tooltip.tsx
  lib/theming/src/index.ts
  lib/theming/src/tests/util.test.js
  lib/theming/src/utils.ts
  lib/ui/src/components/notifications/item.js
Labels: bug, theming

#7088 ADD packtracker to official example
  .circleci/config.yml
  examples/official-storybook/package.json
  yarn.lock
Labels: maintenance

#7095 Add corejs migration notes
  MIGRATION.md
Labels: documentation, patch

#7096 Updated template to not import addons
  lib/cli/generators/REACT_NATIVE/template/storybook/index.js
Labels: app: react-native, bug, cli, patch

#7100 cli: replaced merge-dirs dependency by fs-extra
  lib/cli/generators/ANGULAR/index.js
  lib/cli/generators/EMBER/index.js
  lib/cli/generators/HTML/index.js
  lib/cli/generators/MARKO/index.js
  lib/cli/generators/METEOR/index.js
  lib/cli/generators/MITHRIL/index.js
  lib/cli/generators/POLYMER/index.js
  lib/cli/generators/PREACT/index.js
  lib/cli/generators/RAX/index.js
  lib/cli/generators/REACT/index.js
  lib/cli/generators/REACT_NATIVE/index.js
  lib/cli/generators/REACT_SCRIPTS/index.js
  lib/cli/generators/RIOT/index.js
  lib/cli/generators/SFC_VUE/index.js
  lib/cli/generators/SVELTE/index.js
  lib/cli/generators/VUE/index.js
  lib/cli/generators/WEBPACK_REACT/index.js
  lib/cli/package.json
  yarn.lock
Labels: dependencies, patch, security

#6993 Tech/improve bootstrap list
  .gitignore
  CONTRIBUTING.md
  addons/storyshots/storyshots-puppeteer/package.json
  package.json
  scripts/bootstrap.js
  scripts/reset.js
  yarn.lock
Labels: maintenance

#7105 UI: Fix about page version check message
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
  lib/ui/src/settings/about.js
  lib/ui/src/settings/about.stories.js
Labels: bug, patch, ui

#6016 fix rendering code block in @storybook/addon-info
  addons/info/package.json
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/Node.js
  addons/info/src/components/Story.js
  addons/info/src/components/markdown/code.js
  addons/info/src/components/markdown/text.js
  addons/info/src/index.test.js
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  yarn.lock
Labels: addon: info, feature request

#6861 add ability to have multiple sections in the notes panel
  addons/notes/README.md
  addons/notes/src/Panel.tsx
  addons/notes/src/shared.ts
Labels: addon: notes, feature request

#6922 Make compatible with yarn Pnp
  lib/core/package.json
  lib/ui/package.json
  yarn.lock
Labels: compatibility with other tools, dependencies

#7009 Add SCSS to presets gallery
  docs/src/pages/presets/preset-gallery/index.md
Labels: documentation, patch

#6382 Refactor story_store
  app/react-native/readme.md
  lib/client-api/src/story_store.js
  lib/client-api/src/story_store.test.js
  lib/core/src/client/preview/start.js
  lib/core/src/client/preview/start.test.js
  lib/core/src/client/preview/url.js
  lib/core/src/client/preview/url.test.js
  scripts/reset.js
Labels: core, maintenance

#7107 Addon-docs: Basic skeleton, UI viewMode handling
  addons/docs/README.md
  addons/docs/package.json
  addons/docs/register.js
  addons/docs/src/public_api.ts
  addons/docs/src/register.ts
  addons/docs/src/shared.ts
  addons/docs/tsconfig.json
  examples/official-storybook/addons.js
  examples/official-storybook/package.json
  examples/official-storybook/stories/__snapshots__/addon-docs.stories.storyshot
  examples/official-storybook/stories/addon-docs.stories.js
  lib/client-api/src/story_store.js
  lib/core/src/client/preview/start.js
  lib/core/src/client/preview/url.js
  lib/ui/src/app.js
  lib/ui/src/components/layout/container.js
  lib/ui/src/components/layout/desktop.js
  lib/ui/src/components/layout/mobile.js
  lib/ui/src/components/preview/__snapshots__/preview.stories.storyshot
  lib/ui/src/components/preview/preview.js
Labels: addon: docs, feature request

#7139 Fixes a small typo
  docs/src/pages/configurations/custom-webpack-config/index.md
Labels: documentation, patch

#7141 fix(addons-info): change stylesheetBase info height from 110vh to 100vh
  addons/info/src/components/Story.js
Labels: addon: info, bug, patch

#7118 CLI: Use process.env.CI if available
  lib/core/src/server/cli/dev.js
Labels: cli, feature request

#7112 Tech/remove redundant storyshots
  examples/cra-kitchen-sink/src/storyshots.test.js
  examples/official-storybook/stories/__snapshots__/addon-a11y.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-actions.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-backgrounds.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-centered.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-contexts.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-cssresources.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-design-assets.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-events.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-graphql.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-jest.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-links.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-notes.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-options.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-queryparams.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-storyshots.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-viewport.stories.storyshot
  examples/official-storybook/stories/__snapshots__/app-acceptance.stories.storyshot
  examples/official-storybook/stories/__snapshots__/other-demo.stories.storyshot
  examples/official-storybook/stories/__snapshots__/other-dirname.stories.storyshot
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  examples/official-storybook/tests/storyshots.test.js
Labels: maintenance

#7110 Addon-docs: Module story format & framework param
  app/angular/src/client/index.js
  app/angular/src/client/preview/index.js
  app/ember/src/client/index.js
  app/ember/src/client/preview/index.js
  app/html/src/client/index.js
  app/html/src/client/preview/index.js
  app/marko/src/client/index.js
  app/marko/src/client/preview/index.js
  app/mithril/src/client/index.js
  app/mithril/src/client/preview/index.js
  app/polymer/src/client/index.js
  app/polymer/src/client/preview/index.js
  app/preact/src/client/index.js
  app/preact/src/client/preview/index.js
  app/react-native/src/index.ts
  app/react/src/client/index.js
  app/react/src/client/preview/index.js
  app/riot/src/client/index.js
  app/riot/src/client/preview/index.js
  app/svelte/src/client/index.js
  app/svelte/src/client/preview/index.js
  app/vue/src/client/index.js
  app/vue/src/client/preview/index.js
  examples/angular-cli/src/stories/__snapshots__/core.stories.storyshot
  examples/official-storybook/config.js
  examples/riot-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  lib/core/src/client/preview/start.js
Labels: addon: docs, feature request

#7151 UPGRADE lazy-universal-dotenv
  lib/core/package.json
  yarn.lock
Labels: dependencies, patch

#6972 IMPROVE HMR error reporting, no refreshes needed for error recovery
  app/react/src/client/preview/render.js
  examples/cra-kitchen-sink/src/stories/App.stories.js
  examples/official-storybook/stories/core/errors.stories.js
  lib/client-api/src/config_api.js
  lib/client-api/src/story_store.js
  lib/core/package.json
  lib/core/src/client/preview/start.js
  lib/core/src/server/preview/preview-preset.js
  lib/core/src/server/templates/base-preview-body.html
  lib/core/src/server/templates/base-preview-head.html
  yarn.lock
Labels: babel / webpack, bug

#7158 Fix/indenting for addon-notes & addon-info on markdown code blocks
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/markdown/code.js
  addons/notes/src/Panel.tsx
  examples/official-storybook/stories/__snapshots__/addon-docs.stories.storyshot
  examples/official-storybook/stories/addon-info.stories.js
  examples/official-storybook/stories/addon-notes.stories.js
Labels: addon: info, addon: notes, bug, patch, ui

#7119 Addon-docs: DocsPage and doc blocks
  MIGRATION.md
  addons/docs/blocks.js
  addons/docs/package.json
  addons/docs/src/blocks/Description.tsx
  addons/docs/src/blocks/DocsContainer.tsx
  addons/docs/src/blocks/DocsContext.ts
  addons/docs/src/blocks/DocsPage.tsx
  addons/docs/src/blocks/Meta.tsx
  addons/docs/src/blocks/Preview.tsx
  addons/docs/src/blocks/Props.tsx
  addons/docs/src/blocks/Source.tsx
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/blocks/Wrapper.tsx
  addons/docs/src/blocks/index.ts
  addons/docs/src/blocks/shared.ts
  addons/docs/src/lib/getPropDefs.ts
  examples/official-storybook/config.js
  examples/vue-kitchen-sink/.storybook/addons.js
  examples/vue-kitchen-sink/.storybook/config.js
  examples/vue-kitchen-sink/package.json
  lib/components/src/blocks/BlockBackgroundStyles.tsx
  lib/components/src/blocks/ColorPalette.stories.tsx
  lib/components/src/blocks/ColorPalette.tsx
  lib/components/src/blocks/Description.stories.tsx
  lib/components/src/blocks/Description.tsx
  lib/components/src/blocks/DocsPage.stories.tsx
  lib/components/src/blocks/DocsPage.tsx
  lib/components/src/blocks/DocsPageExampleCaption.md
  lib/components/src/blocks/DocsPageExampleCaption.mdx
  lib/components/src/blocks/EmptyBlock.stories.tsx
  lib/components/src/blocks/EmptyBlock.tsx
  lib/components/src/blocks/IFrame.tsx
  lib/components/src/blocks/IconGallery.stories.tsx
  lib/components/src/blocks/IconGallery.tsx
  lib/components/src/blocks/Preview.stories.tsx
  lib/components/src/blocks/Preview.tsx
  lib/components/src/blocks/PropsTable/PropDef.ts
  lib/components/src/blocks/PropsTable/PropRow.stories.tsx
  lib/components/src/blocks/PropsTable/PropRow.tsx
  lib/components/src/blocks/PropsTable/PropsTable.stories.tsx
  lib/components/src/blocks/PropsTable/PropsTable.tsx
  lib/components/src/blocks/Source.stories.tsx
  lib/components/src/blocks/Source.tsx
  lib/components/src/blocks/Story.stories.tsx
  lib/components/src/blocks/Story.tsx
  lib/components/src/blocks/Typeset.stories.tsx
  lib/components/src/blocks/Typeset.tsx
  lib/components/src/blocks/index.ts
  lib/components/src/index.ts
  lib/components/src/syntaxhighlighter/__snapshots__/syntaxhighlighter.stories.storyshot
  lib/ui/src/components/panel/panel.stories.js
Labels: addon: docs, feature request

#7172 Github org rename
  addons/design-assets/package.json
  addons/queryparams/package.json
  app/rax/README.md
  app/rax/package.json
  dev-kits/addon-parameter/package.json
  dev-kits/addon-roundtrip/package.json
  docs/src/pages/addons/writing-addons/index.md
  examples/cra-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/rax-kitchen-sink/.storybook/config.js
  lib/cli/generators/RAX/template/.storybook/config.js
Labels: maintenance, patch

#7171 Upgrade core-js to 3.x in devkits
  addons/design-assets/package.json
  addons/queryparams/package.json
  dev-kits/addon-parameter/package.json
  dev-kits/addon-roundtrip/package.json
Labels: dependencies

#7173 Fix unstretched preview background wrapper
  lib/ui/src/components/preview/background.js
Labels: addon: viewport, bug, patch, ui

#7145 Addon-docs: MDX support
  addons/docs/README.md
  addons/docs/__snapshots__/mdx-compiler-plugin.test.js.snap
  addons/docs/common/index.js
  addons/docs/common/preset.js
  addons/docs/fixtures/decorators.mdx
  addons/docs/fixtures/parameters.mdx
  addons/docs/fixtures/previews.mdx
  addons/docs/fixtures/story-current.mdx
  addons/docs/fixtures/story-def-text-only.mdx
  addons/docs/fixtures/story-definitions.mdx
  addons/docs/fixtures/story-missing-props.mdx
  addons/docs/fixtures/story-object.mdx
  addons/docs/fixtures/story-references.mdx
  addons/docs/fixtures/vanilla.mdx
  addons/docs/mdx-compiler-plugin.js
  addons/docs/mdx-compiler-plugin.test.js
  addons/docs/package.json
  addons/docs/react/index.js
  addons/docs/react/preset.js
  addons/docs/src/blocks/DocsContainer.tsx
  addons/docs/src/typings.d.ts
  addons/docs/vue/index.js
  addons/docs/vue/preset.js
  examples/official-storybook/config.js
  examples/official-storybook/presets.js
  examples/official-storybook/stories/addon-docs.stories.js
  examples/official-storybook/stories/addon-docs.stories.mdx
  examples/official-storybook/stories/notes/notes.mdx
  lib/core/src/client/preview/start.js
  yarn.lock
Labels: addon: docs, feature request

#7174 Addon-docs: Convert to module format codemod
  .babelrc.js
  lib/codemod/README.md
  lib/codemod/package.json
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/basic.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/basic.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/decorators.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/decorators.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/module.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/module.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/multi.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/multi.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/parameters.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/parameters.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/story-parameters.input.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/story-parameters.output.js
  lib/codemod/src/transforms/__tests__/convert-to-module-format.test.js
  lib/codemod/src/transforms/convert-to-module-format.js
Labels: addon: docs, feature request

#6937 feat(cli): Adds a new info command which prints local environment information
  lib/cli/bin/generate.js
  lib/cli/package.json
  yarn.lock
Labels: cli, feature request

#7154 Docs mode with `--docs` flag
  jest.config.js
  lib/api/src/index.tsx
  lib/api/src/modules/layout.ts
  lib/api/src/modules/url.ts
  lib/api/src/tests/layout.test.js
  lib/api/src/tests/url.test.js
  lib/api/src/typings.d.ts
  lib/core/src/server/build-dev.js
  lib/core/src/server/build-static.js
  lib/core/src/server/cli/dev.js
  lib/core/src/server/cli/prod.js
  lib/core/src/server/manager/manager-webpack.config.js
  lib/ui/src/components/layout/container.js
  lib/ui/src/index.js
Labels: addon: docs, feature request

#7185 Addon-docs: Support non-story exports in module format
  lib/components/src/blocks/PropsTable/PropRow.stories.tsx
  lib/components/src/blocks/PropsTable/PropsTable.stories.tsx
  lib/core/src/client/preview/start.js
  lib/core/src/client/preview/start.test.js
Labels: addon: docs, feature request

#7177 Migrate addon viewport to TS
  addons/viewport/package.json
  addons/viewport/src/Tool.tsx
  addons/viewport/src/constants.js
  addons/viewport/src/constants.ts
  addons/viewport/src/defaults.ts
  addons/viewport/src/legacy_preview/index.ts
  addons/viewport/src/legacy_preview/withViewport.ts
  addons/viewport/src/models/Viewport.ts
  addons/viewport/src/models/ViewportAddonParameter.ts
  addons/viewport/src/models/index.ts
  addons/viewport/src/register.tsx
  addons/viewport/tsconfig.json
Labels: addon: viewport, maintenance, typescript

#7191 Add myself to automention for vue
  .github/automention.yml
Labels: maintenance

#7117 Addon-docs: Source loader library
  .babelrc.js
  examples/angular-cli/.storybook/webpack.config.ts
  examples/ember-cli/.storybook/webpack.config.js
  examples/ember-cli/package.json
  examples/html-kitchen-sink/.storybook/webpack.config.js
  examples/html-kitchen-sink/package.json
  examples/marko-cli/.storybook/webpack.config.js
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/.storybook/webpack.config.js
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/official-storybook/webpack.config.js
  examples/polymer-cli/.storybook/webpack.config.js
  examples/polymer-cli/package.json
  examples/preact-kitchen-sink/.storybook/webpack.config.js
  examples/preact-kitchen-sink/package.json
  examples/rax-kitchen-sink/.storybook/webpack.config.js
  examples/rax-kitchen-sink/package.json
  examples/riot-kitchen-sink/.storybook/webpack.config.js
  examples/riot-kitchen-sink/package.json
  examples/svelte-kitchen-sink/.storybook/webpack.config.js
  examples/svelte-kitchen-sink/package.json
  examples/vue-kitchen-sink/.storybook/webpack.config.js
  examples/vue-kitchen-sink/package.json
  lib/source-loader/package.json
  lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.test.js.snap
  lib/source-loader/src/abstract-syntax-tree/default-options.js
  lib/source-loader/src/abstract-syntax-tree/generate-helpers.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.test.js
  lib/source-loader/src/abstract-syntax-tree/parse-helpers.js
  lib/source-loader/src/abstract-syntax-tree/parsers/index.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-flow.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-js.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-ts.js
  lib/source-loader/src/abstract-syntax-tree/traverse-helpers.js
  lib/source-loader/src/build.js
  lib/source-loader/src/dependencies-lookup/getRidOfUselessFilePrefixes.js
  lib/source-loader/src/dependencies-lookup/readAsObject.js
  lib/source-loader/src/events.js
  lib/source-loader/src/index.js
  lib/source-loader/src/preview.js
Labels: addon: docs, addon: storysource, feature request

#7203 Fix source-loader CI errors
  examples/angular-cli/.storybook/webpack.config.ts
  examples/ember-cli/.storybook/webpack.config.js
  examples/html-kitchen-sink/.storybook/webpack.config.js
  examples/marko-cli/.storybook/webpack.config.js
  examples/mithril-kitchen-sink/.storybook/webpack.config.js
  examples/official-storybook/webpack.config.js
  examples/polymer-cli/.storybook/webpack.config.js
  examples/preact-kitchen-sink/.storybook/webpack.config.js
  examples/rax-kitchen-sink/.storybook/webpack.config.js
  examples/riot-kitchen-sink/.storybook/webpack.config.js
  examples/svelte-kitchen-sink/.storybook/webpack.config.js
  examples/vue-kitchen-sink/.storybook/webpack.config.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.test.js
Labels: maintenance

#7202 Module format: use story field for name/parameters annotation
  addons/docs/__snapshots__/mdx-compiler-plugin.test.js.snap
  addons/docs/mdx-compiler-plugin.js
  examples/official-storybook/stories/addon-docs.stories.js
  examples/official-storybook/stories/core/errors.stories.js
  examples/official-storybook/stories/core/events.stories.js
  examples/official-storybook/stories/core/parameters.stories.js
  examples/official-storybook/stories/core/scroll.stories.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/basic.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/decorators.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/parameters.output.js
  lib/codemod/src/transforms/__testfixtures__/convert-to-module-format/story-parameters.output.js
  lib/codemod/src/transforms/convert-to-module-format.js
  lib/components/src/blocks/DocsPage.stories.tsx
  lib/components/src/blocks/Source.stories.tsx
  lib/core/src/client/preview/start.js
  lib/ui/src/components/sidebar/SidebarItem.stories.js
  lib/ui/src/settings/shortcuts.stories.js
Labels: BREAKING CHANGE, addon: docs

#6472 Story sorting
  docs/src/pages/configurations/options-parameter/index.md
  examples/cra-kitchen-sink/.storybook/config.js
  lib/client-api/src/story_store.js
  lib/client-api/src/story_store.test.js
  lib/ui/README.md
  lib/ui/src/components/sidebar/treeview/utils.js
  lib/ui/src/components/sidebar/treeview/utils.test.js
Labels: feature request, ui

#7216 Fix module format stories w/ parameters & no name
  examples/official-storybook/stories/core/decorators.stories.js
  lib/ui/src/components/preview/iframe.stories.js
Labels: maintenance

#7214 Addon-docs: Fix source-loader in monorepo examples
  examples/official-storybook/webpack.config.js
  lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.test.js.snap
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.test.js
  lib/source-loader/src/dependencies-lookup/readAsObject.js
  lib/source-loader/src/preview.js
  lib/ui/src/components/notifications/item.stories.js
  lib/ui/src/components/notifications/notifications.stories.js
  lib/ui/src/components/sidebar/Sidebar.stories.js
  lib/ui/src/components/sidebar/SidebarHeading.stories.js
  lib/ui/src/components/sidebar/SidebarStories.stories.js
Labels: addon: docs, bug

#7229 Addon-docs: Add .story.mdx support to preset
  addons/docs/common/preset.js
Labels: addon: docs, feature request

#7187 Fix react native server
  .eslintignore
  addons/ondevice-actions/src/components/ActionLogger/Inspect.tsx
  addons/ondevice-backgrounds/src/BackgroundPanel.js
  addons/ondevice-backgrounds/src/container.js
  addons/ondevice-knobs/src/PropForm.js
  addons/ondevice-notes/src/index.js
  addons/ondevice-notes/src/register.js
  app/react-native-server/src/client/manager/provider.js
  app/react-native/src/index.ts
  app/react-native/src/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view.tsx
  app/react-native/src/preview/components/OnDeviceUI/animation.ts
  app/react-native/src/preview/components/OnDeviceUI/index.tsx
  app/react-native/src/preview/components/OnDeviceUI/navigation/index.tsx
  app/react-native/src/preview/components/StoryListView/index.tsx
  app/react-native/src/preview/components/StoryView/index.tsx
  app/react-native/src/preview/index.tsx
  examples-native/crna-kitchen-sink/App.js
  examples-native/crna-kitchen-sink/metro.config.js
  examples-native/crna-kitchen-sink/storybook/addons.js
  examples-native/crna-kitchen-sink/storybook/stories/index.js
  lib/cli/generators/REACT_NATIVE/index.js
  lib/cli/generators/REACT_NATIVE/template/storybook/stories/index.js
  lib/client-api/src/story_store.js
Labels: app: react-native, app: react-native-server, bug, patch
