Repository storybookjs/storybook, pull requests merged in 2019-09, with the labels that each got.

#7946 Addon-docs: Fix inline stories using react hooks
  lib/components/src/blocks/Story.stories.tsx
  lib/components/src/blocks/Story.tsx
Labels: addon: docs, app: react, bug

#7962 docspage.md broken link fix
  addons/docs/docs/docspage.md
Labels: addon: docs, documentation

#7974 Addon-docs: Fix MDX theme bleed with reset context
  addons/docs/src/blocks/Story.tsx
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
Labels: addon: docs, bug

#7979 CLI: Force welcome stories to show up first in load order
  lib/cli/generators/ANGULAR/template/src/stories/0-Welcome.stories.ts
  lib/cli/generators/ANGULAR/template/src/stories/1-Button.stories.ts
  lib/cli/generators/EMBER/template/stories/0-Welcome.stories.js
  lib/cli/generators/EMBER/template/stories/1-Button.stories.js
  lib/cli/generators/METEOR/template/stories/0-Welcome.stories.js
  lib/cli/generators/METEOR/template/stories/1-Button.stories.js
  lib/cli/generators/MITHRIL/template/stories/0-Welcome.stories.js
  lib/cli/generators/MITHRIL/template/stories/1-Button.stories.js
  lib/cli/generators/PREACT/template/stories/0-Welcome.stories.js
  lib/cli/generators/PREACT/template/stories/1-Button.stories.js
  lib/cli/generators/RAX/template/stories/0-Welcome.stories.js
  lib/cli/generators/RAX/template/stories/1-Button.stories.js
  lib/cli/generators/REACT/template/stories/0-Welcome.stories.js
  lib/cli/generators/REACT/template/stories/1-Button.stories.js
  lib/cli/generators/REACT_SCRIPTS/template/src/stories/0-Welcome.stories.js
  lib/cli/generators/REACT_SCRIPTS/template/src/stories/1-Button.stories.js
  lib/cli/generators/RIOT/template/stories/0-Welcome.stories.js
  lib/cli/generators/RIOT/template/stories/1-Button.stories.js
  lib/cli/generators/SFC_VUE/template/src/stories/0-Welcome.stories.js
  lib/cli/generators/SFC_VUE/template/src/stories/1-Button.stories.js
  lib/cli/generators/VUE/template/stories/0-Welcome.stories.js
  lib/cli/generators/VUE/template/stories/1-Button.stories.js
  lib/cli/generators/WEBPACK_REACT/template/stories/0-Welcome.stories.js
  lib/cli/generators/WEBPACK_REACT/template/stories/1-Button.stories.js
Labels: bug, cli, high priority

#7965 Addon-docs: Error handling for invalid Story id
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
  examples/official-storybook/stories/hooks.stories.js
  examples/vue-kitchen-sink/src/stories/addon-docs.stories.mdx
  lib/components/src/blocks/Story.tsx
Labels: addon: docs, bug

#7990 UI: Fix enableShortcuts option
  lib/api/src/modules/shortcuts.ts
  lib/ui/src/containers/nav.js
Labels: bug, high priority, ui

#7992 API: Fix useEfect in inline Docs
  examples/official-storybook/stories/hooks.stories.js
  lib/addons/src/hooks.ts
  lib/client-api/src/hooks.test.js
  lib/core-events/src/index.ts
  lib/core/src/client/preview/start.js
Labels: addon: docs, bug

#7997 Addon backgrounds: README image updated
  addons/backgrounds/README.md
Labels: addon: backgrounds, documentation

#7991 Addon-docs: Doc blocks fixes for dark theme
  lib/components/src/blocks/ColorPalette.tsx
  lib/components/src/blocks/PropsTable/PropsTable.tsx
  lib/components/src/typography/DocumentFormatting.tsx
Labels: addon: docs, bug, high priority

#8015 Addon-docs: Fix LI styling for dark color theme
  lib/components/src/typography/DocumentFormatting.tsx
Labels: addon: docs, bug, high priority, theming

#7994 Addon-docs: Scroll story into view
  addons/docs/src/blocks/Anchor.tsx
  addons/docs/src/blocks/DocsContainer.tsx
  addons/docs/src/blocks/DocsPage.tsx
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/blocks/index.ts
  addons/docs/src/typings.d.ts
  lib/components/src/blocks/Story.tsx
Labels: addon: docs, bug, high priority

#8026 Update recipes.md
  addons/docs/docs/recipes.md
Labels: cleanup

#8027 Addon-knobs: allow array values in select and options knobs
  addons/knobs/src/__types__/knob-test-cases.ts
  addons/knobs/src/components/types/Options.tsx
  addons/knobs/src/components/types/Select.tsx
Labels: addon: knobs, bug, high priority, typescript

#8030 Guides: Update all guides to CSF
  docs/src/pages/basics/writing-stories/index.md
  docs/src/pages/guides/guide-angular/index.md
  docs/src/pages/guides/guide-ember/index.md
  docs/src/pages/guides/guide-html/index.md
  docs/src/pages/guides/guide-marko/index.md
  docs/src/pages/guides/guide-mithril/index.md
  docs/src/pages/guides/guide-preact/index.md
  docs/src/pages/guides/guide-rax/index.md
  docs/src/pages/guides/guide-react/index.md
  docs/src/pages/guides/guide-react/new.md
  docs/src/pages/guides/guide-riot/index.md
  docs/src/pages/guides/guide-svelte/index.md
  docs/src/pages/guides/guide-vue/index.md
Labels: csf, documentation

#8036 Angular: remove webpack-env from tsconfig types
  app/angular/tsconfig.json
Labels: app: angular, bug

#8045 MIGRATE to new github actions
  .github/main.workflow
  .github/workflows/issues.yml
  .github/workflows/label.yml
  .github/workflows/nodejs.yml
  .github/workflows/pull_request-automention-prs.yml
  .github/workflows/pull_request-dangerfile-js-pull.yml
Labels: addon: docs, maintenance

#8037 DocsPage: show docs.storyDescription above story
  addons/docs/src/blocks/DocsPage.tsx
  examples/official-storybook/stories/demo/button.stories.js
Labels: addon: docs, feature request

#8049 CHANGE the now config
  .gitignore
  addons/centered/src/rax.js
  examples/angular-cli/package.json
  examples/cra-kitchen-sink/package.json
  examples/cra-react15/package.json
  examples/cra-ts-kitchen-sink/package.json
  examples/dev-kits/package.json
  examples/ember-cli/package.json
  examples/html-kitchen-sink/package.json
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/polymer-cli/package.json
  examples/preact-kitchen-sink/package.json
  examples/rax-kitchen-sink/package.json
  examples/riot-kitchen-sink/package.json
  examples/svelte-kitchen-sink/package.json
  examples/vue-kitchen-sink/package.json
  now.json
  package.json
  scripts/now.js
  yarn.lock
Labels: maintenance

#8032 UI: Debounce to sidebar search filter
  lib/ui/src/components/sidebar/treeview/treeview.js
Labels: feature request, ui

#8034 CLI: Add wrapper packages: sb & storybook
  lib/cli-sb/README.md
  lib/cli-sb/index.js
  lib/cli-sb/package.json
  lib/cli-storybook/README.md
  lib/cli-storybook/index.js
  lib/cli-storybook/package.json
  scripts/verdaccio.yaml
Labels: cli, maintenance

#8097 Core: Fix error handling
  app/react/src/client/preview/element_check.test.tsx
  app/react/src/client/preview/element_check.ts
  app/react/src/client/preview/render.tsx
  app/vue/src/client/preview/index.ts
  examples/official-storybook/stories/core/errors.stories.js
  examples/official-storybook/stories/core/parameters.stories.js
  examples/vue-kitchen-sink/__snapshots__/vueshots.test.js.snap
  examples/vue-kitchen-sink/src/stories/core-errors.stories.js
  lib/cli-sb/package.json
  lib/cli-storybook/package.json
  lib/core/src/client/preview/start.js
  lib/core/src/server/templates/base-preview-head.html
Labels: app: react, bug, core, patch

#8113 Update index.md
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8125 help users by pointing to further documentation
  addons/a11y/README.md
Labels: addon: a11y, documentation, patch

#8130 Fix spellingerror in changelog
  CHANGELOG.md
Labels: documentation, patch

#8118 add missing type def to addon-knobs fixes #8105
  addons/knobs/package.json
Labels: bug, patch, typescript

#8150 Fix typo
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#7675 Addon-contexts: Remove peer dependencies
  addons/contexts/package.json
  addons/contexts/src/manager/ContextsManager.tsx
  addons/contexts/src/manager/components/ToolBar.tsx
  addons/contexts/src/manager/components/ToolBarControl.tsx
  addons/contexts/src/manager/components/ToolBarMenu.tsx
  addons/contexts/src/manager/components/ToolBarMenuOptions.tsx
  addons/contexts/src/manager/libs/useChannel.ts
  addons/contexts/src/preview/frameworks/preact.ts
  addons/contexts/src/preview/frameworks/react.ts
  addons/contexts/src/preview/frameworks/vue.ts
  addons/contexts/src/register.ts
Labels: addon: contexts, bug

#7951 Addon-backgrounds: Customizable Grid Cell Size
  addons/backgrounds/src/constants.ts
  addons/backgrounds/src/containers/BackgroundSelector.tsx
  addons/backgrounds/src/containers/GridSelector.tsx
  examples/official-storybook/stories/addon-backgrounds.stories.js
Labels: addon: backgrounds, feature request

#8156 REMOVE addon/center peerDependencies
  addons/centered/package.json
  addons/centered/src/mithril.tsx
  addons/centered/src/preact.tsx
  addons/centered/src/rax.js
  addons/centered/src/react.tsx
Labels: addon: centered, bug

#8163 FIX 8083
  lib/addons/src/hooks.ts
Labels: addon: contexts, api: addons, bug, client-api, patch

#8146 Document environment variables usage in HTML
  docs/src/pages/configurations/env-vars/index.md
Labels: documentation, patch

#8106 CLI: Fix variable collisions in storiesof-to-csf
  lib/cli/story.js
  lib/codemod/package.json
  lib/codemod/src/lib/utils.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/basic.input.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/basic.output.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/collision.input.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/collision.output.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/digit.input.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/digit.output.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/exports.output.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/multi.output.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/story-parameters.output.js
  lib/codemod/src/transforms/__tests__/storiesof-to-csf.test.js
  lib/codemod/src/transforms/storiesof-to-csf.js
Labels: bug, cli, csf, patch

#8145 Update package.json
  lib/ui/package.json
  yarn.lock
Labels: dependencies, patch

#8168 demo is down
  docs/src/pages/examples/_examples.yml
Labels: documentation

#8061 Addon-docs: CSS classes for escape-hatch theming wrapper/content
  addons/docs/README.md
  addons/docs/docs/docspage.md
  addons/docs/docs/faq.md
  addons/docs/docs/mdx.md
  addons/docs/docs/recipes.md
  addons/docs/docs/theming.md
  addons/docs/src/blocks/DocsContainer.tsx
  examples/official-storybook/preview-head.html
  lib/api/src/version.ts
  lib/components/src/html.tsx
Labels: addon: docs, bug, patch, theming

#8159 fix: Allow JSX.Element story
  app/preact/src/client/preview/types.ts
Labels: app: preact, bug, patch, typescript

#8155 Improve error logging
  lib/core/src/server/build-dev.js
Labels: core, maintenance, patch

#8182 Core: Fix lib/core whitelist
  lib/core/package.json
Labels: bug, core

#8186 fix recommended typescript config in docs
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#8056 UI: Fix document title not updating
  lib/ui/src/components/preview/preview.js
  lib/ui/src/containers/preview.js
Labels: bug, high priority, ui

#8194 Fix links to live examples
  docs/src/pages/basics/live-examples/index.md
Labels: documentation, patch

#8119 fix: add @types/webpack-env to apps that depend on it, fixes #8110
  app/html/package.json
  app/preact/package.json
  app/react/package.json
  app/vue/package.json
Labels: bug, patch, typescript

#8202 Fix typo in Decorator doc
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8006 Addon-knobs: Handle undefined array value
  addons/knobs/src/components/types/Array.tsx
Labels: addon: knobs, bug, patch

#8206 UI: Move addon dependencies to devDependencies
  lib/ui/package.json
Labels: bug, patch, ui

#8207 Build: Upgrade from node8 to node10
  .circleci/config.yml
  .travis.yml
Labels: maintenance

#8213 Use the extracted linting configs
  .eslintrc.js
  .remarkrc.js
  addons/centered/src/parameters.ts
  addons/centered/src/styles.ts
  addons/knobs/src/components/Panel.tsx
  addons/viewport/src/Tool.tsx
  examples/angular-cli/src/stories/customControlValueAccessor/custom-cva.component.ts
  lib/cli/lib/initiate.js
  lib/core/src/server/build-dev.js
  lib/ui/src/keyboard/keyCodes.ts
  package.json
  prettier.config.js
  scripts/bootstrap.js
  yarn.lock
Labels: maintenance

#8217 Fix loader typo in migration guide
  MIGRATION.md
Labels: documentation, patch

#7948 UI: Add shortcuts, events for collapse/expand all
  lib/api/src/modules/channel.ts
  lib/api/src/modules/shortcuts.ts
  lib/core-events/src/index.ts
  lib/ui/src/components/sidebar/treeview/treeview.js
  lib/ui/src/containers/nav.js
  lib/ui/src/settings/shortcuts.js
  lib/ui/src/settings/shortcuts.stories.js
Labels: feature request, ui

#7928 State to props
  addons/a11y/src/components/Report/Item.tsx
Labels: addon: a11y, maintenance

#7862 convert state to hooks in color blindness file for a11y addon
  addons/a11y/src/components/ColorBlindness.tsx
Labels: addon: a11y, addon: backgrounds, maintenance

#7737 Migrate @storybook/addon-ondevice-notes to Typescript
  addons/ondevice-notes/package.json
  addons/ondevice-notes/src/components/Notes.tsx
  addons/ondevice-notes/src/index.ts
  addons/ondevice-notes/src/register.tsx
  addons/ondevice-notes/src/typings.d.ts
  addons/ondevice-notes/tsconfig.json
Labels: addon: notes, maintenance, typescript

#7736 Migrate @storybook/addon-ondevice-backgrounds to Typescript
  addons/ondevice-backgrounds/package.json
  addons/ondevice-backgrounds/src/BackgroundPanel.tsx
  addons/ondevice-backgrounds/src/Swatch.tsx
  addons/ondevice-backgrounds/src/constants.ts
  addons/ondevice-backgrounds/src/container.tsx
  addons/ondevice-backgrounds/src/index.tsx
  addons/ondevice-backgrounds/src/register.tsx
  addons/ondevice-backgrounds/tsconfig.json
Labels: addon: backgrounds, maintenance, typescript

#8028 Add paramKey for addon-storysource
  addons/storysource/src/manager.js
Labels: addon: storysource, feature request

#7993 Refactor: Use Array.includes instead of indexOf
  addons/knobs/src/components/Panel.tsx
  app/riot/src/client/preview/rendering/stringified.js
Labels: maintenance

#8218 UI: Improve code indentation
  addons/a11y/package.json
  addons/a11y/src/index.ts
  addons/design-assets/package.json
  addons/links/package.json
  addons/links/src/index.ts
  addons/queryparams/package.json
  app/ember/package.json
  app/ember/src/client/preview/render.js
  app/html/package.json
  app/html/src/client/preview/render.ts
  app/marko/package.json
  app/marko/src/client/preview/render.js
  app/mithril/package.json
  app/mithril/src/client/preview/render.js
  app/polymer/package.json
  app/polymer/src/client/preview/render.js
  app/preact/package.json
  app/preact/src/client/preview/render.tsx
  app/rax/package.json
  app/rax/src/client/preview/render.js
  app/react/package.json
  app/riot/package.json
  app/riot/src/client/preview/render.js
  app/svelte/package.json
  app/svelte/src/client/preview/render.js
  app/vue/package.json
  app/vue/src/client/preview/render.ts
  dev-kits/addon-parameter/package.json
  dev-kits/addon-roundtrip/package.json
  docs/package.json
  examples/cra-react15/package.json
  examples/official-storybook/package.json
  examples/rax-kitchen-sink/package.json
  lib/client-api/package.json
  lib/client-api/src/story_store.ts
  lib/components/package.json
  lib/components/src/syntaxhighlighter/formatter.test.js
  lib/components/src/syntaxhighlighter/formatter.ts
  lib/core/package.json
  lib/core/src/server/build-dev.js
  lib/core/src/server/preview/custom-webpack-preset.js
  lib/theming/package.json
  lib/theming/src/ensure.ts
  package.json
  scripts/run-registry.js
  yarn.lock
Labels: maintenance

#8121 React: Add DecoratorFn type to exports
  app/react/src/client/index.ts
  app/react/src/client/preview/index.ts
Labels: bug, patch, typescript

#8200 Hitting some flakiness in now deploys, this might help
  scripts/bootstrap.js
Labels: maintenance

#7747 Update angular example to v8
  addons/storyshots/storyshots-core/src/frameworks/angular/app.component.ts
  app/angular/src/client/preview/angular/components/app.component.ts
  app/angular/src/server/__tests__/angular-cli_config.test.ts
  app/angular/src/server/angular-cli_config.ts
  app/angular/src/server/framework-preset-angular-cli.ts
  examples/angular-cli/angular.json
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/ngrx-store.stories.ts
  package.json
  yarn.lock
Labels: app: angular, maintenance

#8117 Addon-links: Update linkTo type to accept function
  addons/links/package.json
  addons/links/src/preview.test.js
  addons/links/src/preview.ts
Labels: addon: links, bug, typescript

#8225 Update index.md in /writing-stories
  docs/src/pages/basics/writing-stories/index.md
Labels: documentation, patch

#8228 UPGRADE telejson to new version with typings included and bugs fixed
  lib/api/package.json
  lib/api/src/typings.d.ts
  lib/channel-postmessage/package.json
  lib/channel-postmessage/src/typings.d.ts
  lib/ui/package.json
  yarn.lock
Labels: bug, core, patch

#8071 Change example repository with new CRA and Typesc…
  docs/src/pages/configurations/typescript-config/index.md
Labels: cra, documentation, patch, typescript

#8234 FIX a critical api missing
  lib/channels/src/index.ts
Labels: bug, high priority
