Repository storybookjs/storybook, pull requests merged in 2019-03, with the labels that each got.

#5808 Update README.md
  README.md
Labels: documentation, patch

#5806 Allow local decorators via params
  examples/official-storybook/stories/core/decorators.stories.js
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/client-api/src/client_api.js
Labels: api: stories, core, feature request

#5807 Close tooltips on iframe clicks on keypresses
  lib/components/src/tooltip/WithTooltip.js
Labels: bug, ui

#5805 Sort storiesHash so grouped keys appear together.
  lib/ui/src/core/stories.js
  lib/ui/src/core/stories.test.js
Labels: bug, core

#5790 add gov.uk story book react site
  docs/src/pages/examples/_examples.yml
  docs/src/pages/examples/thumbnails/gov-uk.png
Labels: documentation

#5816 FIX build-storybook with simplebar esm files
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: bug

#5787 FIX theming bugs
  examples/official-storybook/config.js
  examples/official-storybook/stories/core/parameters.stories.js
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/channel-postmessage/src/index.ts
  lib/theming/src/ensure.ts
  lib/ui/package.json
  lib/ui/src/components/layout/container.js
  lib/ui/src/core/addons.js
  lib/ui/src/core/context.js
  lib/ui/src/core/init-provider-api.js
  lib/ui/src/core/initial-state.js
  lib/ui/src/core/layout.js
  lib/ui/src/core/store.js
  lib/ui/src/core/stories.js
Labels: bug, release, theming

#5802 fix(addon-notes): inline code markdown
  addons/notes/src/Panel.test.js
  addons/notes/src/Panel.tsx
Labels: addon: notes, bug, release

#5813 Document individual story decorators migration
  MIGRATION.md
Labels: documentation

#5819 ADD warning for decorators added "mid-kind"
  examples/angular-cli/src/stories/component-with-di/di.component.stories.ts
  examples/angular-cli/src/stories/custom-pipes.stories.ts
  examples/angular-cli/src/stories/custom-providers.stories.ts
  examples/angular-cli/src/stories/custom-styles.stories.ts
  lib/client-api/src/client_api.js
Labels: bug, release, ui

#5826 Enable CORS on versions.json
  docs/static/_headers
Labels: maintenance

#5829 Restore viewport behaviour
  MIGRATION.md
  addons/viewport/README.md
  addons/viewport/preview.js
  addons/viewport/src/Tool.js
  addons/viewport/src/constants.js
  addons/viewport/src/legacy_preview/index.js
  addons/viewport/src/legacy_preview/withViewport.js
  examples/official-storybook/config.js
  examples/official-storybook/extra-viewports.json
  examples/official-storybook/stories/__snapshots__/addon-viewport.stories.storyshot
  examples/official-storybook/stories/addon-viewport.stories.js
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
Labels: addon: viewport, bug, release

#5828 REMOVE previously deprecated default export from backgrounds
  MIGRATION.md
  addons/backgrounds/mithril.js
  addons/backgrounds/src/constants.ts
  addons/backgrounds/src/deprecated.ts
  addons/backgrounds/src/index.ts
  addons/backgrounds/vue.js
Labels: addon: backgrounds, documentation, release

#5833 Cleanup & document a11y migration
  MIGRATION.md
  addons/a11y/README.md
  addons/a11y/src/index.js
  examples/html-kitchen-sink/stories/addon-a11y.stories.js
  examples/official-storybook/config.js
  examples/official-storybook/stories/__snapshots__/addon-a11y.stories.storyshot
  examples/official-storybook/stories/addon-a11y.stories.js
Labels: addon: a11y, maintenance, release

#5842 Misc migration notes
  MIGRATION.md
Labels: documentation, release

#5846 Deprecate withA11Y
  addons/a11y/src/index.js
Labels: maintenance

#5848 Fix typo
  examples/angular-cli/src/stories/ngrx-store.stories.ts
Labels: app: angular, cleanup

#5845 Add MIGRATION.md entry for addon-cssresources 5.x attribute change
  MIGRATION.md
Labels: addon: cssresources, documentation, release

#5849 Fix code example in "writing-addons" docs
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation

#5850 Fix: SidebarItem feels "laggy" when clicked
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/sidebar/SidebarItem.js
Labels: bug, release

#5856 Ensure the theme is insta-loaded from local storage
  lib/ui/src/core/layout.js
Labels: bug, ui

#5858 Tech/workaround persisted options with defaults
  lib/ui/src/core/layout.js
Labels: addon: options, bug, release, ui

#5843 FIX base theme initialization and theme bootup
  addons/knobs/src/components/__tests__/Panel.js
  examples/official-storybook/config.js
  lib/theming/src/base.ts
  lib/theming/src/create.ts
  lib/theming/src/ensure.ts
  lib/theming/src/tests/create.test.js
  lib/theming/src/themes/dark.ts
  lib/theming/src/themes/light.ts
  lib/ui/package.json
  lib/ui/src/components/sidebar/SidebarHeading.stories.js
  lib/ui/src/core/layout.js
  lib/ui/src/index.js
  lib/ui/src/settings/shortcuts.test.js
  scripts/compile-js.js
Labels: bug, release, theming

#5854 Update ember docs for ember-cli-storybook@0.1.0
  docs/src/pages/basics/guide-ember/index.md
Labels: app: ember, documentation

#5633 Trigger frontpage deploy in CI
  .circleci/config.yml
  package.json
  scripts/build-frontpage.js
Labels: documentation, release

#5870 Corrected import path for `themes`
  docs/src/pages/configurations/theming/index.md
Labels: documentation

#5881 Fix typo in MIGRATION.md related to webpack config
  MIGRATION.md
Labels: documentation

#5885 storysource: update documentation for v5
  addons/storysource/README.md
Labels: documentation

#5884 Fix imported package for "dark" theme
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#5896 Split versions.json into two files
  docs/gatsby-node.js
  docs/src/versions/latest.json
  docs/src/versions/next.json
  docs/static/versions.json
  docs/versions.json
Labels: maintenance, patch

#5900 Fix typo in example, use MyPanel component
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch

#5905 Readme updated to reference jsDelivr for the badge
  README.md
Labels: documentation, patch

#5930 Updated list of peerDependencies for mithriljs.
  docs/src/pages/basics/guide-mithril/index.md
Labels: app: mithril, documentation, patch

#5920 A copy change
  docs/src/pages/basics/introduction/index.md
Labels: cleanup, patch

#5909 lib client-api/src/client_api: check type of module.id as fileName
  lib/client-api/src/client_api.js
  lib/client-api/src/client_api.test.js
Labels: bug, core

#5929 updated docs to reflect proper params passed to webpack.config.js
  docs/src/pages/configurations/typescript-config/index.md
Labels: babel / webpack, documentation, patch, typescript

#5928 Docs: Typescript Configuration Examples for v5
  docs/src/pages/configurations/typescript-config/index.md
Labels: babel / webpack, documentation, patch, typescript

#5811 [Addon: Knobs] - Performance Fix: added debouncing between keystrokes to speed up component rendering
  addons/knobs/package.json
  addons/knobs/src/registerKnobs.js
Labels: addon: knobs, bug, performance issue

#5943 ADD delay to rendering the acceptance stories
  examples/official-storybook/stories/app-acceptance.stories.js
Labels: maintenance

#5946 Bump version number in live examples page
  docs/src/pages/basics/live-examples/index.md
Labels: documentation, patch

#5947 Fixed missing iframe.html in output directory
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: bug, cli, patch

#5738 Migrate addon a11y to TS
  addons/a11y/package.json
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/ColorBlindness.tsx
  addons/a11y/src/components/Report/Elements.js
  addons/a11y/src/components/Report/Elements.tsx
  addons/a11y/src/components/Report/Info.tsx
  addons/a11y/src/components/Report/Item.tsx
  addons/a11y/src/components/Report/Rules.tsx
  addons/a11y/src/components/Report/Tags.tsx
  addons/a11y/src/components/Report/index.js
  addons/a11y/src/components/Report/index.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/a11y/src/constants.ts
  addons/a11y/src/index.ts
  addons/a11y/src/register.tsx
  addons/a11y/src/typings.d.ts
  addons/a11y/tsconfig.json
  examples/official-storybook/config.js
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
Labels: addon: a11y, maintenance, typescript

#5961 Add core JS dependencies across the stack where it was missing
  addons/notes/package.json
  app/react-native/package.json
  lib/addons/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/channels/package.json
  lib/client-logger/package.json
  lib/components/package.json
  lib/core-events/package.json
  lib/router/package.json
  lib/theming/package.json
  lib/ui/package.json
Labels: babel / webpack, bug, core, patch

#5964 Core: support unicode chars in story IDs
  examples/official-storybook/stories/core/__snapshots__/unicode.stories.storyshot
  examples/official-storybook/stories/core/unicode.stories.js
  lib/router/src/tests/id.test.js
  lib/router/src/utils.ts
Labels: bug, core, patch

#5911 Remove custom presets warning
  lib/core/src/server/common/custom-presets.js
Labels: bug, core, patch

#5976 Update README.md demo projects version > 5.0.0
  README.md
Labels: documentation

#5972 add missing `addDecorator` import
  addons/a11y/README.md
Labels: documentation, patch

#5967 Fix example of setting defaultViewport per story
  addons/viewport/README.md
Labels: documentation, patch

#5978 SYNC prettier printWidth with eslint && FIX resulting linting warnings
  addons/actions/src/components/ActionLogger/index.tsx
  addons/actions/src/preview/decorateAction.ts
  addons/actions/src/preview/withActions.ts
  addons/backgrounds/src/components/ColorIcon.tsx
  addons/backgrounds/src/containers/BackgroundSelector.tsx
  addons/notes/src/Panel.tsx
  addons/notes/src/index.ts
  addons/storyshots/storyshots-core/src/frameworks/angular/helpers.ts
  app/angular/src/client/preview/angular/decorators.ts
  app/angular/src/client/preview/angular/helpers.ts
  app/angular/src/demo/welcome.component.ts
  examples/angular-cli/src/karma.ts
  examples/angular-cli/src/stories/addon-background.stories.ts
  examples/angular-cli/src/stories/addon-knobs.stories.ts
  examples/angular-cli/src/stories/all-knobs.component.ts
  examples/angular-cli/src/stories/component-with-di/di.component.ts
  examples/cra-ts-kitchen-sink/src/components/Button.stories.tsx
  lib/addons/src/index.ts
  lib/addons/src/make-decorator.test.ts
  lib/addons/src/make-decorator.ts
  lib/channels/src/index.test.ts
  lib/router/src/utils.ts
  lib/theming/src/create.ts
  lib/theming/src/global.ts
  lib/ui/src/keyboard/keyCodes.ts
  lib/ui/src/keyboard/platform.ts
  lib/ui/src/keyboard/scanCode.ts
  lib/ui/src/libs/shortcut.ts
  tslint.json
Labels: maintenance, typescript

#5979 Change viewport styling to more closely match v4
  addons/viewport/src/Tool.js
Labels: addon: viewport, maintenance, patch

#5983 fix(stories): `selectStory` correct behavior on call with one parameter
  lib/ui/src/core/stories.js
  lib/ui/src/core/stories.test.js
Labels: bug, patch

#5984 feta(a11y): add 'incomplete' tab
  addons/a11y/src/components/A11YPanel.tsx
  examples/cra-kitchen-sink/.storybook/config.js
Labels: addon: a11y, feature request

#5987 Updated React reference to Vue
  docs/src/pages/guides/guide-vue/index.md
Labels: cleanup

#5993 bug fix (addons/viewport): viewport iframe dimensions
  addons/viewport/src/Tool.js
Labels: addon: viewport, bug, patch

#5990 Fixed a typo in the react native example
  docs/src/pages/guides/guide-react-native/index.md
Labels: bug, cli

#5991 Addon-a11y: fix design icons
  addons/a11y/src/components/Report/Item.tsx
  addons/a11y/src/components/Report/Rules.tsx
Labels: addon: a11y, bug, patch

#5999 Update index.md
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#5844 ADD parameters to compile-js to no longer copy .ts files into dist
  scripts/compile-js.js
Labels: maintenance, typescript

#5996 Addon-a11y: 'element' arg in config not ignored
  addons/a11y/src/index.ts
Labels: addon: a11y, bug, patch

#5997 docs: use npm command for npm example
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
  lib/ui/src/settings/about.js
Labels: documentation, patch

#6006 Fix theming doc typo
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#5868 FIX an issue when re-rendering lit-html elements after rendering a non-lit-html element
  app/polymer/src/client/preview/render.js
Labels: app: polymer, bug

#5998 Fix #5785 - welcome component in dark theme
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.enzyme.test.js.snap
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.snapshotWithOptionsFunction.test.js.snap
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.foo
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.storyshot
  app/angular/src/demo/welcome.component.ts
  app/react/src/demo/Welcome.js
  examples/cra-kitchen-sink/src/stories/__snapshots__/welcome.storyshot
  examples/ember-cli/app/styles/app.css
  examples/html-kitchen-sink/stories/welcome.css
  examples/mithril-kitchen-sink/src/Welcome.js
  examples/official-storybook/stories/__snapshots__/other-demo.stories.storyshot
  examples/preact-kitchen-sink/src/Welcome.js
  examples/preact-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/riot-kitchen-sink/src/stories/Welcome.tag
  examples/svelte-kitchen-sink/src/stories/__snapshots__/index.storyshot
  examples/svelte-kitchen-sink/src/stories/views/WelcomeView.svelte
  examples/vue-kitchen-sink/src/stories/Welcome.vue
  lib/cli/generators/MITHRIL/template/stories/Welcome.js
  lib/cli/generators/PREACT/template/stories/Welcome.js
  lib/cli/generators/RIOT/template/stories/Welcome.tag
  lib/cli/generators/SFC_VUE/template/src/stories/Welcome.vue
  lib/cli/generators/VUE/template/stories/Welcome.js
  lib/cli/test/fixtures/update_package_organisations/stories/Welcome.js
Labels: bug, cli, patch

#6013 SYNC printWidth prettier config
  addons/storysource/README.md
  addons/storysource/src/loader/default-options.js
Labels: addon: storysource, maintenance

#6015 CLEANUP - remove unused storyshots
  examples/cra-kitchen-sink/src/stories/__snapshots__/App.stories.storyshot
  examples/cra-kitchen-sink/src/stories/__snapshots__/cra-svgr.stories.storyshot
  lib/components/src/ActionBar/__snapshots__/panel_actionbar.stories.storyshot
  lib/components/src/brand/__snapshots__/Logo.stories.storyshot
  lib/components/src/brand/__snapshots__/StorybookLogo.stories.storyshot
  lib/components/src/form/__snapshots__/button.stories.storyshot
  lib/components/src/placeholder/__snapshots__/placeholder.stories.storyshot
  lib/ui/src/components/sidebar/__snapshots__/SidebarItem.stories.storyshot
  lib/ui/src/components/sidebar/__snapshots__/SidebarSearch.stories.storyshot
  lib/ui/src/components/sidebar/__snapshots__/nav.stories.storyshot
  lib/ui/src/components/sidebar/treeview/__snapshots__/treeview.stories.storyshot
Labels: cleanup

#5988 Improve typings of theming lib
  lib/components/src/syntaxhighlighter/__snapshots__/syntaxhighlighter.stories.storyshot
  lib/theming/src/base.ts
  lib/theming/src/create.ts
  lib/theming/src/index.ts
  lib/ui/src/settings/__snapshots__/about.stories.storyshot
Labels: maintenance, theming, typescript

#6022 Modified the Knobs onChange debounce function so that knob storage occurs on keypress but rendering waits until debouncing has completed
  addons/knobs/src/registerKnobs.js
Labels: addon: knobs, bug, patch

#6026 fix(a11y): remove bg color from reports
  addons/a11y/src/components/Report/Info.tsx
Labels: addon: notes, bug, theming

#6048 Improve Docs (grammar/wording changes)
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#6043 [bug]Error message when removing value from number knob
  addons/knobs/src/components/PropForm.js
Labels: addon: knobs, bug

#6064 add lerna badge in README
  README.md
Labels: documentation

#6068 ADD gatsby-plugin-styled-components to FIX the FOUC in the new header
  docs/gatsby-config.js
  docs/package.json
  docs/yarn.lock
Labels: documentation, patch

#6072 [Docs] Vue guide typo
  docs/src/pages/guides/guide-vue/index.md
Labels: documentation, patch

#6044 fix(addon/a11y): run scan only when addon tab is active
  addons/a11y/src/components/A11YPanel.test.js
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
  addons/a11y/src/index.ts
Labels: addon: a11y, bug, patch

#6027 [bug] Fixing search item in menu
  lib/ui/src/containers/nav.js
  lib/ui/src/core/layout.js
  lib/ui/src/core/shortcuts.js
Labels: bug, patch, ui

#6054 Update syntaxhighlighter.stories.js
  lib/components/src/syntaxhighlighter/__snapshots__/syntaxhighlighter.stories.storyshot
  lib/components/src/syntaxhighlighter/syntaxhighlighter.stories.js
Labels: components, maintenance

#5612 @storybook/angular add autoprefixing like angular-cli
  app/angular/package.json
  app/angular/src/server/framework-preset-angular.js
Labels: app: angular, babel / webpack, feature request

#6046 Update index.md
  docs/src/pages/guides/quick-start-guide/index.md
Labels: documentation, patch

#6084 Minor grammar change
  docs/src/pages/configurations/standalone-options/index.md
Labels: documentation, patch

#6079 Use community AsyncStorage instead of deprecated React Native one
  app/react-native/package.json
  app/react-native/src/preview/index.js
  yarn.lock
Labels: app: react-native, compatibility with other tools, dependencies, patch

#6101 Tech/sorting package json
  addons/actions/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  app/react-native/package.json
  app/react/src/server/__mocks__/react-scripts-2-0-0/package.json
  app/react/src/server/__mocks__/react-scripts-2-1-0/package.json
  examples/angular-cli/package.json
  examples/cra-kitchen-sink/package.json
  examples/cra-ts-kitchen-sink/package.json
  examples/ember-cli/package.json
  examples/html-kitchen-sink/package.json
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/polymer-cli/package.json
  examples/preact-kitchen-sink/package.json
  examples/riot-kitchen-sink/package.json
  examples/svelte-kitchen-sink/package.json
  examples/vue-kitchen-sink/package.json
  lib/channels/package.json
  lib/cli/test/fixtures/angular-cli-v6/package.json
  lib/cli/test/fixtures/angular-cli-v7/package.json
  lib/cli/test/fixtures/react_babel_config_js/package.json
  lib/cli/test/fixtures/react_babel_custom_preset/package.json
  lib/cli/test/fixtures/react_babel_pkg_json/package.json
  lib/cli/test/fixtures/react_babelrc/package.json
  lib/cli/test/fixtures/react_babelrc_js/package.json
  lib/cli/test/fixtures/react_scripts_v2/package.json
  lib/cli/test/fixtures/react_scripts_v2_forked/package.json
  lib/cli/test/fixtures/react_static/package.json
  lib/cli/test/fixtures/react_static_next/package.json
  lib/cli/test/fixtures/riot/package.json
  lib/cli/test/fixtures/sfc_vue/package.json
  lib/cli/test/fixtures/webpack_react/package.json
  package.json
  yarn.lock
Labels: maintenance

#6105 docs(configurations): fix markdown for react-typescript
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#6106 open brandUrl in new window
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/sidebar/SidebarHeading.js
Labels: feature request, ui

#6108 Update Vue "manual setup" steps
  docs/src/pages/guides/guide-vue/index.md
Labels: documentation, patch

#6042 fix (addon/backgrounds): addon panel doesn't hide
  addons/backgrounds/src/containers/BackgroundSelector.tsx
Labels: addon: backgrounds, bug, patch

#6021 docs(addons): add hint about addon tab order
  docs/src/pages/addons/using-addons/index.md
Labels: documentation

#6119 Simplify the setting of the no-border on iframe
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/preview/__snapshots__/preview.stories.storyshot
  lib/ui/src/components/preview/components.js
  lib/ui/src/components/preview/iframe.js
Labels: cleanup

#6120 FIX brandImage staying storybook's logo when theme is created with brandTitle
  lib/theming/src/create.ts
Labels: bug, theming

#6086 Updated Readme.md
  addons/viewport/README.md
Labels: documentation

#6118 Addon-a11y: added 'name' param for generate unique key for item
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/Report/index.tsx
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
Labels: addon: a11y, bug

#6121 Fix expo
  examples-native/crna-kitchen-sink/app.json
  examples-native/crna-kitchen-sink/package.json
  examples-native/crna-kitchen-sink/yarn.lock
Labels: dependencies:update

#6082 Add --debug-webpack option
  lib/core/src/server/build-static.js
  lib/core/src/server/cli/dev.js
  lib/core/src/server/cli/prod.js
  lib/core/src/server/dev-server.js
  lib/core/src/server/logConfig.js
Labels: babel / webpack, feature request, patch

#6104 Restore v4 webpack extend mode behavior AND deprecate it
  MIGRATION.md
  addons/a11y/src/components/A11YPanel.tsx
  docs/src/pages/configurations/custom-webpack-config/index.md
  examples/angular-cli/.storybook/webpack.config.ts
  examples/cra-ts-kitchen-sink/.storybook/webpack.config.js
  examples/ember-cli/.storybook/webpack.config.js
  examples/html-kitchen-sink/.storybook/webpack.config.js
  examples/marko-cli/.storybook/webpack.config.js
  examples/mithril-kitchen-sink/.storybook/webpack.config.js
  examples/polymer-cli/.storybook/webpack.config.js
  examples/preact-kitchen-sink/.storybook/webpack.config.js
  examples/riot-kitchen-sink/.storybook/webpack.config.js
  examples/svelte-kitchen-sink/.storybook/webpack.config.js
  examples/vue-kitchen-sink/.storybook/webpack.config.js
  lib/core/src/server/preview/custom-webpack-preset.js
Labels: babel / webpack, bug, patch

#6050 [bug] (addon-cssresources) - `STORY_RENDERED` causes picked CSS to reset
  addons/cssresources/src/css-resource-panel.test.js
  addons/cssresources/src/css-resource-panel.tsx
Labels: addon: cssresources, bug, patch

#6124 Add missing button titles
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/preview/__snapshots__/preview.stories.storyshot
  lib/ui/src/components/preview/preview.js
  lib/ui/src/components/sidebar/SidebarHeading.js
  lib/ui/src/components/sidebar/SidebarSearch.js
Labels: accessibility, patch, ui

#6131 Add aria label to search box
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/sidebar/SidebarSearch.js
Labels: accessibility, bug

#6134 Fix deprecations in examples
  examples/cra-kitchen-sink/.storybook/config.js
  examples/cra-ts-kitchen-sink/.storybook/config.js
  examples/ember-cli/stories/index.stories.js
  examples/preact-kitchen-sink/.storybook/config.js
  examples/preact-kitchen-sink/src/stories/addon-backgrounds.stories.js
Labels: maintenance

#6143 Make update notifications much less aggressive
  lib/ui/src/core/context.js
  lib/ui/src/core/versions.js
  lib/ui/src/core/versions.test.js
Labels: maintenance, patch

#6129 Fix linting errors in docs
  docs/src/pages/configurations/theming/index.md
  docs/src/pages/guides/guide-react/new.md
  docs/src/pages/guides/guide-riot/index.md
  docs/src/pages/guides/guide-vue/index.md
Labels: documentation

#5904 brandImage to occupy 100% of the width of <BrandArea/>
  examples/official-storybook/tests/__snapshots__/storyshots.test.js.snap
  lib/ui/src/components/sidebar/SidebarHeading.js
Labels: bug, theming

#6181 fix(MIGRATION): add missing commas
  MIGRATION.md
Labels: documentation, patch

#6182 fix: Add the raw method to the react-native implementation
  app/react-native/src/index.js
  app/react-native/src/preview/index.js
Labels: app: react-native, bug

#6094 Fix performance of Angular rerender
  addons/knobs/src/registerKnobs.js
  app/angular/package.json
  app/angular/src/client/preview/angular/components/app.component.ts
  app/angular/src/client/preview/angular/helpers.ts
  app/angular/src/client/preview/render.js
  examples/angular-cli/src/stories/addon-knobs.stories.ts
  examples/angular-cli/tsconfig.json
  tslint.json
Labels: app: angular, bug, performance issue

#6183 Publish crna-kitchen-sink app to expo
  .circleci/config.yml
  .gitignore
  .teamcity/OpenSourceProjects_Storybook/Project.kt
  .teamcity/OpenSourceProjects_Storybook/buildTypes/OpenSourceProjects_Storybook_Build_2.kt
  .teamcity/OpenSourceProjects_Storybook/buildTypes/OpenSourceProjects_Storybook_NativeSmokeTests.kt
  examples-native/crna-kitchen-sink/app.json
  examples-native/crna-kitchen-sink/package.json
  package.json
  scripts/crna-publish.js
  yarn.lock
Labels: app: react-native, maintenance

#6177 Add migration instructions for RN 5.1
  MIGRATION.md
Labels: app: react-native, documentation

#6149 Fix #6077: issue with selectedPanel reset
  lib/api/src/modules/layout.ts
  lib/api/src/tests/layout.test.js
Labels: bug, patch, ui

#6193 chore(angular): typo fix
  app/angular/src/demo/welcome.component.ts
Labels: app: angular, bug, patch

#5922 Allow for theming of the notes addon panel
  addons/notes/src/Panel.tsx
Labels: addon: notes, feature request, theming

#6202 Replace the term `instance` with `instant` in exporting storybook documentation
  docs/src/pages/basics/exporting-storybook/index.md
Labels: documentation, patch

#6199 fix(README): Update links to INITIAL_VIEWPORTS
  addons/viewport/README.md
Labels: documentation, patch

#6203 fix(knobs): color type button z-index
  addons/knobs/src/components/types/Color.js
Labels: addon: knobs, bug, patch

#6207 Replace old intro animation with new animation
  media/storybook-intro.gif
Labels: documentation, patch

#6195 Added missing option documentation
  MIGRATION.md
  addons/options/README.md
  docs/src/pages/configurations/options-parameter/index.md
Labels: documentation, patch

#6206 Update storysource readme with v5 webpack config
  addons/storysource/README.md
Labels: documentation, patch

#6209 fix(client-api): add core-js as a dep
  lib/client-api/package.json
Labels: core, dependencies

#6186 Add fonts and color to styling in info addon
  addons/info/src/__snapshots__/index.test.js.snap
  addons/info/src/components/Story.js
  examples/cra-kitchen-sink/src/stories/__snapshots__/index.stories.storyshot
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
Labels: addon: info, bug

#6180 fix: regexp in config.js
  addons/storyshots/storyshots-core/.storybook/config.js
  addons/storyshots/storyshots-core/.storybook/configTest.js
  addons/storyshots/storyshots-core/README.md
  docs/src/pages/configurations/typescript-config/index.md
  examples/html-kitchen-sink/.storybook/config.js
  lib/cli/generators/ANGULAR/template/.storybook/config.js
  lib/cli/generators/EMBER/template/.storybook/config.js
  lib/cli/generators/HTML/template/.storybook/config.js
  lib/cli/generators/MARKO/template/.storybook/config.js
  lib/cli/generators/METEOR/template/.storybook/config.js
  lib/cli/generators/MITHRIL/template/.storybook/config.js
  lib/cli/generators/POLYMER/template/.storybook/config.js
  lib/cli/generators/PREACT/template/.storybook/config.js
  lib/cli/generators/REACT/template/.storybook/config.js
  lib/cli/generators/RIOT/template/.storybook/config.js
  lib/cli/generators/SFC_VUE/template/.storybook/config.js
  lib/cli/generators/VUE/template/.storybook/config.js
  lib/cli/generators/WEBPACK_REACT/template/.storybook/config.js
  lib/cli/test/fixtures/react_babel_config_js/.storybook/config.js
  lib/cli/test/fixtures/react_babel_custom_preset/.storybook/config.js
  lib/cli/test/fixtures/react_babel_pkg_json/.storybook/config.js
  lib/cli/test/fixtures/react_babelrc/.storybook/config.js
  lib/cli/test/fixtures/react_babelrc_js/.storybook/config.js
Labels: addon: storyshots, bug, cli, patch

#6221 Remove myself from code owners
  .github/CODEOWNERS
Labels: maintenance

#6132 feat(svelte): adding svelte cli generator
  addons/storyshots/storyshots-puppeteer/package.json
  docs/package.json
  lib/cli/generators/SVELTE/index.js
  lib/cli/generators/SVELTE/template/.storybook/addons.js
  lib/cli/generators/SVELTE/template/.storybook/config.js
  lib/cli/generators/SVELTE/template/stories/button.svelte
  lib/cli/generators/SVELTE/template/stories/index.stories.js
  lib/cli/lib/initiate.js
  lib/cli/lib/project_types.js
  lib/cli/package.json
  package.json
Labels: app: svelte, cli, feature request

#6238 fix(tooltip): event bindings, logger import
  lib/components/src/tooltip/WithTooltip.js
Labels: bug, components, patch

#6236 Forked CRA support on Windows
  app/react/src/server/cra-config.js
  app/react/src/server/cra-config.test.js
Labels: app: react, bug, cra, patch

#6159 Fix addon-knobs ObjectType knob react warning #5276
  addons/knobs/src/components/types/Object.js
Labels: addon: knobs, bug, patch

#6245 fix(cra-config): use node-logger instead of console
  app/react/src/server/cra-config.js
Labels: cleanup, cra, patch

#6249 Workaround broken treebeard animations
  addons/options/README.md
  lib/ui/src/modules/api/defaultState.js
  lib/ui/src/modules/ui/components/stories_panel/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/__snapshots__/index.stories.storyshot
  lib/ui/src/modules/ui/components/stories_panel/stories_tree/index.js
Labels: bug, ui

#6045 Show active viewport dimensions & button to rotate
  addons/viewport/src/Tool.js
Labels: addon: viewport, feature request

#6254 Update type definition for panelPosition to enum of strings
  docs/src/pages/configurations/options-parameter/index.md
Labels: documentation, patch, ui

#6252 Add custom grid size
  examples/cra-kitchen-sink/.storybook/config.js
  examples/cra-kitchen-sink/package.json
  lib/theming/src/base.ts
  lib/theming/src/create.ts
  lib/theming/src/tests/create.test.js
  lib/ui/src/components/preview/background.js
Labels: addon: backgrounds, feature request, theming

#6244 use Fuse.js package instead of fuzzy-search for customizable search threshold
  lib/api/src/version.ts
  lib/ui/package.json
  lib/ui/src/components/sidebar/treeview/utils.js
  yarn.lock
Labels: bug, ui

#6246 Migrate addon links to TS
  addons/links/package.json
  addons/links/src/constants.ts
  addons/links/src/index.ts
  addons/links/src/manager.ts
  addons/links/src/preview.ts
  addons/links/src/react/components/link.test.js
  addons/links/src/react/components/link.tsx
  addons/links/src/react/index.js
  addons/links/src/react/index.ts
  addons/links/src/typings.d.ts
  addons/links/tsconfig.json
  addons/storyshots/storyshots-core/src/api/integrityTestTemplate.js
Labels: addon: links, maintenance, typescript

#6190 Allow forced renders in @storybook/html
  app/html/src/client/preview/render.js
  examples/html-kitchen-sink/.storybook/config.js
  examples/html-kitchen-sink/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/html-kitchen-sink/stories/addon-knobs.stories.js
Labels: app: html, feature request

#6242 adds an example of a boolean knob
  examples/ember-cli/app/templates/components/welcome-banner.hbs
  examples/ember-cli/stories/addon-knobs.stories.js
Labels: addon: knobs, maintenance

#6240 Addon-actions: safe render for cyclic obj
  addons/actions/src/containers/ActionLogger/index.tsx
Labels: addon: actions, bug, patch

#6259 FIX storybook having a incompatible version of webpack with vue-cli
  app/angular/package.json
  app/polymer/package.json
  app/react/package.json
  examples/ember-cli/package.json
  examples/marko-cli/package.json
  examples/mithril-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/polymer-cli/package.json
  examples/preact-kitchen-sink/package.json
  examples/riot-kitchen-sink/package.json
  examples/vue-kitchen-sink/package.json
  lib/cli/test/fixtures/riot/package.json
  lib/cli/test/fixtures/sfc_vue/package.json
  lib/cli/test/fixtures/webpack_react/package.json
  lib/core/package.json
  lib/ui/package.json
  package.json
  yarn.lock
Labels: babel / webpack, dependencies

#6218 Feature/highlight a11y violation on component
  addons/a11y/package.json
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/Report/Elements.tsx
  addons/a11y/src/components/Report/HighlightToggle.test.js
  addons/a11y/src/components/Report/HighlightToggle.tsx
  addons/a11y/src/components/Report/Item.tsx
  addons/a11y/src/components/Report/__snapshots__/HighlightToggle.test.js.snap
  addons/a11y/src/components/Report/index.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
  addons/a11y/src/constants.ts
  addons/a11y/src/redux-config.tsx
  addons/notes/src/Panel.tsx
  lib/api/src/version.ts
  yarn.lock
Labels: addon: a11y, feature request

#6260 CHANGE instances of yarn to npm in docs
  addons/storyshots/storyshots-puppeteer/README.md
Labels: documentation

#6126 fix(preview): zoom iframe content instead zoom iframe wrapper
  lib/ui/src/components/preview/__snapshots__/preview.stories.storyshot
  lib/ui/src/components/preview/components.js
  lib/ui/src/components/preview/iframe.js
  lib/ui/src/components/preview/preview.js
Labels: bug, ui

#6232 Knobs: Rename ALL panel to Other for ungrouped knobs
  addons/knobs/src/components/Panel.js
  addons/knobs/src/components/__tests__/Panel.js
  addons/knobs/src/components/__tests__/__snapshots__/Panel.js.snap
  addons/ondevice-knobs/src/panel.js
  examples/official-storybook/stories/__snapshots__/addon-knobs.stories.storyshot
  examples/official-storybook/stories/addon-knobs.stories.js
Labels: addon: knobs, bug, patch

#6267 [bug] Enforces corejs v2 for babel
  lib/core/src/server/common/babel.js
Labels: babel / webpack, bug, patch

#6281 Upgrade `@babel/preset-env`
  app/riot/package.json
  lib/cli/package.json
  lib/cli/test/fixtures/react_project/package.json
  lib/cli/test/fixtures/sfc_vue/package.json
  lib/core/package.json
  package.json
  yarn.lock
Labels: babel / webpack, bug, patch

#6286 fix(addon-a11y): move redux to dependencies
  addons/a11y/package.json
Labels: addon: a11y, maintenance

#6290 Set expanded stores to objects instead of arrays
  lib/ui/src/components/sidebar/treeview/treeview.js
Labels: bug, patch, ui

#6297 Fixed Colorblindness Emulation
  addons/a11y/src/components/ColorBlindness.tsx
  addons/a11y/src/register.tsx
Labels: addon: a11y, bug, patch

#6313 fixed mistype in returning parameter
  addons/storysource/README.md
Labels: documentation, patch

#6314 Fix {name, url} options deprecation message
  lib/api/src/modules/layout.ts
Labels: documentation, patch

#6315 Added missing background color for left panel
  app/react-native/src/preview/components/OnDeviceUI/panel.js
Labels: app: react-native, bug, ui

#6222 forwardRef elements use displayName if available
  addons/info/src/components/Node.js
  examples/official-storybook/components/ForwardedRefButtonWDisplayName.js
  examples/official-storybook/stories/__snapshots__/addon-info.stories.storyshot
  examples/official-storybook/stories/addon-info.stories.js
Labels: addon: info, bug, patch

#6325 Remove styling of elements after re-running the the accessibility rules
  addons/a11y/src/components/A11YPanel.tsx
Labels: addon: a11y, bug

#6318 documentation: fix debug flag; highlight deprecation and debug info
  docs/src/pages/configurations/custom-webpack-config/index.md
Labels: documentation, patch

#6324 Clean up unused code
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#6317 Upgrade babel-plugin-react-docgen
  app/react/package.json
  yarn.lock
Labels: dependencies
