Repository storybookjs/storybook, pull requests merged in 2020-02, with the labels that each got.

#9717 Add docs re storyshots "disable" parameter
  addons/storyshots/storyshots-core/README.md
Labels: documentation, patch

#9577 Fix @storybook/addon-storyshots not being able to read config from main.ts
  addons/storyshots/storyshots-core/src/frameworks/configure.ts
Labels: addon: storyshots, feature request

#8769 Add angular 8 and 9 cli fixtures
  lib/cli/test/fixtures/angular-cli-v8/.editorconfig
  lib/cli/test/fixtures/angular-cli-v8/.gitignore
  lib/cli/test/fixtures/angular-cli-v8/README.md
  lib/cli/test/fixtures/angular-cli-v8/angular.json
  lib/cli/test/fixtures/angular-cli-v8/package.json
  lib/cli/test/fixtures/angular-cli-v8/src/app/app.component.html
  lib/cli/test/fixtures/angular-cli-v8/src/app/app.component.scss
  lib/cli/test/fixtures/angular-cli-v8/src/app/app.component.spec.ts
  lib/cli/test/fixtures/angular-cli-v8/src/app/app.component.ts
  lib/cli/test/fixtures/angular-cli-v8/src/app/app.module.ts
  lib/cli/test/fixtures/angular-cli-v8/src/assets/.gitkeep
  lib/cli/test/fixtures/angular-cli-v8/src/browserslist
  lib/cli/test/fixtures/angular-cli-v8/src/environments/environment.prod.ts
  lib/cli/test/fixtures/angular-cli-v8/src/environments/environment.ts
  lib/cli/test/fixtures/angular-cli-v8/src/favicon.ico
  lib/cli/test/fixtures/angular-cli-v8/src/index.html
  lib/cli/test/fixtures/angular-cli-v8/src/karma.conf.js
  lib/cli/test/fixtures/angular-cli-v8/src/main.ts
  lib/cli/test/fixtures/angular-cli-v8/src/polyfills.ts
  lib/cli/test/fixtures/angular-cli-v8/src/styles.scss
  lib/cli/test/fixtures/angular-cli-v8/src/test.ts
  lib/cli/test/fixtures/angular-cli-v8/src/tsconfig.app.json
  lib/cli/test/fixtures/angular-cli-v8/src/tsconfig.spec.json
  lib/cli/test/fixtures/angular-cli-v8/src/tslint.json
  lib/cli/test/fixtures/angular-cli-v8/tsconfig.json
  lib/cli/test/fixtures/angular-cli-v8/tslint.json
  lib/cli/test/fixtures/angular-cli-v9/.editorconfig
  lib/cli/test/fixtures/angular-cli-v9/.gitignore
  lib/cli/test/fixtures/angular-cli-v9/README.md
  lib/cli/test/fixtures/angular-cli-v9/angular.json
  lib/cli/test/fixtures/angular-cli-v9/browserslist
  lib/cli/test/fixtures/angular-cli-v9/karma.conf.js
  lib/cli/test/fixtures/angular-cli-v9/package.json
  lib/cli/test/fixtures/angular-cli-v9/src/app/app-routing.module.ts
  lib/cli/test/fixtures/angular-cli-v9/src/app/app.component.html
  lib/cli/test/fixtures/angular-cli-v9/src/app/app.component.spec.ts
  lib/cli/test/fixtures/angular-cli-v9/src/app/app.component.ts
  lib/cli/test/fixtures/angular-cli-v9/src/app/app.module.ts
  lib/cli/test/fixtures/angular-cli-v9/src/assets/.gitkeep
  lib/cli/test/fixtures/angular-cli-v9/src/environments/environment.prod.ts
  lib/cli/test/fixtures/angular-cli-v9/src/environments/environment.ts
  lib/cli/test/fixtures/angular-cli-v9/src/favicon.ico
  lib/cli/test/fixtures/angular-cli-v9/src/index.html
  lib/cli/test/fixtures/angular-cli-v9/src/main.ts
  lib/cli/test/fixtures/angular-cli-v9/src/polyfills.ts
  lib/cli/test/fixtures/angular-cli-v9/src/styles.css
  lib/cli/test/fixtures/angular-cli-v9/src/test.ts
  lib/cli/test/fixtures/angular-cli-v9/tsconfig.app.json
  lib/cli/test/fixtures/angular-cli-v9/tsconfig.json
  lib/cli/test/fixtures/angular-cli-v9/tsconfig.spec.json
  lib/cli/test/fixtures/angular-cli-v9/tslint.json
Labels: app: angular, maintenance

#8388 fix #8128: addon-centered clashing with addon-docs for react
  addons/centered/src/react.tsx
Labels: addon: centered, bug, compatibility with other tools

#9701 Angular: Emit decorator metadata by default
  app/angular/src/server/__tests__/ts_config.test.ts
  app/angular/src/server/ts_config.ts
Labels: app: angular, bug, patch

#9706 Cra-ts-kitchen-sink: Fix stories glob pattern
  examples/cra-ts-kitchen-sink/.storybook/main.js
Labels: maintenance, patch

#9716 Merge pull request #9716 from sakito21/fix/docs-configurations-typescript-config
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch, typescript

#9724 Svelte: Fix Svelte 3 slots for decorators
  app/svelte/src/client/preview/render.ts
Labels: app: svelte, bug, patch

#9697 Addon-a11y: Add preset
  MIGRATION.md
  addons/a11y/README.md
  addons/a11y/package.json
  addons/a11y/preset.js
  addons/a11y/src/preset/addDecorator.ts
  addons/a11y/src/preset/index.ts
  app/server/package.json
  examples/angular-cli/.storybook/preview.ts
  examples/cra-kitchen-sink/.storybook/preview.js
  examples/cra-ts-kitchen-sink/.storybook/preview.ts
  examples/ember-cli/.storybook/preview.js
  examples/html-kitchen-sink/.storybook/preview.js
  examples/html-kitchen-sink/stories/addon-a11y.stories.js
  examples/marko-cli/.storybook/preview.js
  examples/mithril-kitchen-sink/.storybook/preview.js
  examples/official-storybook/preview.js
  examples/preact-kitchen-sink/.storybook/preview.js
  examples/rax-kitchen-sink/src/stories/addon-a11y.stories.js
  examples/riot-kitchen-sink/.storybook/preview.js
  examples/svelte-kitchen-sink/.storybook/preview.js
  examples/vue-kitchen-sink/.storybook/preview.js
  examples/web-components-kitchen-sink/.storybook/preview.js
  examples/web-components-kitchen-sink/stories/addon-a11y.stories.js
Labels: addon: a11y, feature request

#9667 Core: Add Yarn 2 compatibility
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/centered/package.json
  addons/contexts/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/essentials/package.json
  addons/events/package.json
  addons/google-analytics/package.json
  addons/graphql/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/options/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/marionette/package.json
  app/marko/package.json
  app/mithril/package.json
  app/preact/package.json
  app/rax/package.json
  app/riot/package.json
  app/svelte/package.json
  app/vue/package.json
  app/web-components/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/client-api/package.json
  lib/core/package.json
  lib/core/src/server/build-dev.js
  lib/core/src/server/common/babel-cache-preset.js
  lib/core/src/server/dev-server.js
  lib/core/src/server/manager/manager-webpack.config.js
  lib/core/src/server/preview/iframe-webpack.config.js
  lib/core/src/server/utils/resolve-path-in-sb-cache.js
  lib/source-loader/package.json
Labels: compatibility with other tools, feature request, yarn / npm

#9325 Correct the file path for the Button story
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.enzyme.test.js.snap
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.shallow.test.js.snap
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.shallowWithOptions.test.js.snap
  addons/storyshots/storyshots-core/stories/__snapshots__/storyshot.snapshotWithOptionsFunction.test.js.snap
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.foo
  addons/storyshots/storyshots-core/stories/required_with_context/__snapshots__/Welcome.stories.storyshot
  app/react/src/demo/Welcome.tsx
  examples/mithril-kitchen-sink/src/Welcome.js
  examples/preact-kitchen-sink/src/Welcome.js
  examples/preact-kitchen-sink/src/stories/__snapshots__/welcome.stories.storyshot
  lib/cli/generators/MITHRIL/template-csf/stories/Welcome.js
  lib/cli/generators/PREACT/template-csf/stories/Welcome.js
  lib/cli/generators/RAX/template-csf/stories/Welcome.js
Labels: app: react, bug

#9653 CHANGE example urls to netlify urls
  docs/src/pages/addons/writing-addons/index.md
  docs/src/pages/basics/live-examples/index.md
Labels: documentation, patch

#9753 Fix dev server error - back out bad change
  lib/core/src/server/dev-server.js
Labels: bug, core

#9748 fix prettier warning
  lib/core/src/server/common/babel.js
Labels: cleanup, patch

#9646 Core: Fix manager assets to be routed in express
  examples/dev-kits/logo.svg
  examples/dev-kits/manager.js
  lib/core/src/server/dev-server.js
Labels: bug, core

#9708 Insert 'yarn' command between 'cd storybook' and 'yarn bootstrap (--core)'
  CONTRIBUTING.md
Labels: documentation, patch

#9759 Examples: Fix build on master
  .eslintrc.js
  addons/docs/src/frameworks/react/lib/inspection/acornParser.ts
  addons/knobs/src/__types__/knob-test-cases.ts
  app/react/package.json
  app/react/src/server/cra-config.ts
  app/riot/src/client/preview/rendering/stringified.js
  app/vue/package.json
  examples/angular-cli/src/stories/moduleMetadata/dummy.service.ts
  examples/cra-ts-kitchen-sink/src/stories/Button.tsx
  examples/preact-kitchen-sink/src/stories/__snapshots__/addon-centered.stories.storyshot
  lib/components/src/tabs/tabs.tsx
  lib/core-events/src/index.test.ts
  yarn.lock
Labels: bug, cra

#9782 Examples: Remove addon-notes remnants
  addons/notes/package.json
  docs/src/pages/addons/using-addons/index.md
  docs/src/pages/addons/writing-addons/index.md
  examples/riot-kitchen-sink/package.json
  examples/server-kitchen-sink/.storybook/main.js
  examples/server-kitchen-sink/package.json
  examples/vue-kitchen-sink/package.json
  lib/cli/generators/ANGULAR/index.js
  lib/cli/generators/ANGULAR/template-csf/.storybook/main.js
  lib/cli/generators/ANGULAR/template-mdx/.storybook/main.js
  lib/cli/package.json
  yarn.lock
Labels: maintenance

#9783 Patch 3 - typo fix by copy rewrite
  docs/src/pages/presets/introduction/index.md
Labels: documentation, patch

#9780 Changed import of react-syntax-highlighter from esm to cjs
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, components

#9648 Core: Support custom addons using JSX
  addons/actions/src/manager.tsx
  examples/marko-cli/src/stories/hello.stories.js
  lib/cli/test/fixtures/react_babel_6/.babelrc
  lib/cli/test/fixtures/react_babel_6/index.html
  lib/cli/test/fixtures/react_babel_6/index.js
  lib/cli/test/fixtures/react_babel_6/package.json
  lib/cli/test/fixtures/react_babel_6/rollup.config.js
  lib/core/package.json
  lib/core/src/server/manager/babel-loader-manager.js
  lib/core/src/server/manager/manager-webpack.config.js
  lib/core/src/server/preview/babel-loader-preview.js
  lib/core/src/server/preview/iframe-webpack.config.js
  yarn.lock
Labels: babel / webpack, bug, core

#9787 Replace lodash named imports with specific imports
  addons/docs/src/blocks/Props.tsx
  addons/docs/src/frameworks/react/lib/defaultValues/createDefaultValue.ts
  addons/docs/src/frameworks/react/lib/defaultValues/createFromRawDefaultProp.ts
  addons/docs/src/frameworks/react/lib/inspection/acornParser.ts
  addons/docs/src/frameworks/react/propTypes/createType.ts
  addons/docs/src/frameworks/react/propTypes/generateFuncSignature.ts
  addons/docs/src/frameworks/react/propTypes/handleProp.ts
  addons/docs/src/frameworks/react/propTypes/rawDefaultPropResolvers.ts
  addons/docs/src/frameworks/react/propTypes/sortProps.ts
  addons/docs/src/frameworks/react/typeScript/handleProp.ts
  addons/docs/src/lib/docgen/createPropDef.ts
  addons/docs/src/lib/docgen/extractDocgenProps.ts
  addons/docs/src/lib/docgen/flow/createDefaultValue.ts
  addons/docs/src/lib/docgen/flow/createType.ts
  addons/docs/src/lib/docgen/typeScript/createDefaultValue.ts
  addons/docs/src/lib/docgen/typeScript/createType.ts
  addons/docs/src/lib/docgen/utils/docgenInfo.ts
  addons/docs/src/lib/jsdocParser.ts
  docs/src/pages/examples/index.jsx
  docs/src/pages/index.jsx
  docs/src/stories/implementations.js
  lib/components/src/blocks/PropsTable/PropJsDoc.tsx
  lib/components/src/blocks/PropsTable/PropRow.tsx
  lib/components/src/blocks/PropsTable/PropValue.tsx
Labels: maintenance

#9141 UI: Add initialActive option parameter
  docs/src/pages/configurations/options-parameter/index.md
  lib/api/src/index.tsx
  lib/api/src/modules/layout.ts
  lib/ui/src/components/layout/layout.stories.js
  lib/ui/src/components/layout/mobile.js
Labels: feature request, ui

#9775 Examples: Change main.js to main.ts to show it's possible
  examples/cra-ts-kitchen-sink/.storybook/main.ts
  examples/cra-ts-kitchen-sink/package.json
  examples/cra-ts-kitchen-sink/tsconfig.json
  yarn.lock
Labels: maintenance, typescript

#9699 Addon-docs: Add preset options for vue-docgen-api
  addons/docs/src/frameworks/vue/preset.ts
  addons/docs/vue/README.md
Labels: addon: docs, feature request

#9795 import react-syntax-highlighter/create-element from cjs
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, components

#9806 Fixes screenshot url in README.md
  addons/info/README.md
Labels: documentation

#9804 Remove duplicate "AntDesign" section
  docs/src/pages/presets/preset-gallery/index.md
Labels: documentation, patch

#9810 Core: Remove legacy data from Story Store
  MIGRATION.md
  lib/client-api/src/client_api.test.ts
  lib/client-api/src/client_api.ts
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
  lib/client-api/src/types.ts
Labels: BREAKING CHANGE

#9823 Fix broken links in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#8897 FIX #8504 - HTML elements get their classes dropped in MDX
  examples/cra-ts-kitchen-sink/src/stories/Classes.stories.mdx
  lib/components/src/html.tsx
  lib/components/src/typography/DocumentFormatting.tsx
Labels: addon: docs, bug, mdx, patch

#9833 Fix module.export syntax error in 'Storybook for HTML' README
  docs/src/pages/guides/guide-html/index.md
Labels: documentation, patch

#9842 FIX deepscan issues
  addons/a11y/src/components/Report/Item.tsx
  addons/contexts/src/preview/frameworks/vue.ts
  addons/storysource/src/StoryPanel.tsx
  app/angular/src/server/angular-cli_config.ts
  app/riot/src/client/preview/rendering/stringified.js
  dev-kits/addon-parameter/src/register.tsx
  dev-kits/addon-roundtrip/src/panel.tsx
  examples/cra-kitchen-sink/src/components/LifecycleLogger.js
  examples/official-storybook/stories/deprecated/addon-actions.stories.js
  lib/api/src/store.ts
  lib/components/src/tabs/tabs.tsx
  lib/core/src/server/build-static.js
  lib/ui/src/components/layout/container.tsx
Labels: maintenance

#9820 Typescript: Improve @storybook/ui types
  addons/storysource/src/StoryPanel.tsx
  app/server/package.json
  examples/angular-cli/addon-jest.testresults.json
  lib/api/package.json
  lib/api/src/index.tsx
  lib/api/src/init-provider-api.ts
  lib/api/src/lib/stories.ts
  lib/api/src/modules/addons.ts
  lib/api/src/modules/layout.ts
  lib/api/src/modules/stories.ts
  lib/ui/src/FakeProvider.tsx
  lib/ui/src/app.stories.js
  lib/ui/src/app.stories.tsx
  lib/ui/src/app.tsx
  lib/ui/src/components/layout/app.mockdata.tsx
  lib/ui/src/components/layout/container.tsx
  lib/ui/src/components/layout/desktop.stories.tsx
  lib/ui/src/components/layout/desktop.tsx
  lib/ui/src/components/layout/layout.stories.js
  lib/ui/src/components/layout/mobile.stories.tsx
  lib/ui/src/components/layout/mobile.tsx
  lib/ui/src/components/panel/panel.stories.js
  lib/ui/src/components/panel/panel.stories.tsx
  lib/ui/src/components/panel/panel.tsx
  lib/ui/src/components/preview/PreviewProps.tsx
  lib/ui/src/components/preview/components.ts
  lib/ui/src/components/preview/iframe.stories.js
  lib/ui/src/components/preview/iframe.stories.tsx
  lib/ui/src/components/preview/iframe.tsx
  lib/ui/src/components/preview/preview.mockdata.tsx
  lib/ui/src/components/preview/preview.stories.js
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/stringifyQueryParams.tsx
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/components/preview/wrappers.tsx
  lib/ui/src/components/sidebar/Sidebar.tsx
  lib/ui/src/components/sidebar/SidebarStories.tsx
  lib/ui/src/components/sidebar/treeview/treeview.mockdata.ts
  lib/ui/src/components/sidebar/treeview/utils.ts
  lib/ui/src/containers/nav.test.js
  lib/ui/src/containers/panel.stories.js
  lib/ui/src/containers/panel.stories.tsx
  lib/ui/src/containers/preview.tsx
  lib/ui/src/containers/sidebar.test.ts
  lib/ui/src/containers/sidebar.tsx
  lib/ui/src/index.tsx
  lib/ui/src/provider.ts
  lib/ui/src/settings/SettingsFooter.stories.js
  lib/ui/src/settings/SettingsFooter.stories.tsx
  lib/ui/src/settings/shortcuts.stories.tsx
  lib/ui/src/typings.ts
Labels: maintenance, ui

#9844 Theming: Update link to addon-docs theming
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#9857 typo themeing -> theming
  docs/src/pages/configurations/theming/index.md
Labels: documentation, patch

#9861 Ts/better api consumer
  lib/api/package.json
  lib/api/src/index.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/containers/notifications.tsx
  lib/ui/src/containers/panel.tsx
  lib/ui/src/containers/preview.tsx
  lib/ui/src/containers/sidebar.tsx
Labels: api: addons, core, performance issue, typescript

#9834 Storyshots: Fix support for jsx/tsx config files
  __mocks__/fs.js
  addons/storyshots/storyshots-core/src/frameworks/configure.test.ts
  addons/storyshots/storyshots-core/src/frameworks/configure.ts
Labels: addon: storyshots, bug, patch

#9747 Remove : prop types in lib/components
  lib/api/package.json
  lib/components/package.json
  lib/components/src/tabs/tabs.tsx
  lib/source-loader/package.json
  lib/theming/package.json
  lib/ui/package.json
  lib/ui/paths.js
  lib/ui/scripts/createDlls.js
  lib/ui/src/components/sidebar/SidebarStories.tsx
Labels: components, maintenance

#9797 Addon-viewport: Fix Galaxy S9's viewport size
  addons/viewport/src/defaults.ts
Labels: addon: viewport, bug

#9863 CLI: fix React Scripts csf-ts story templates
  lib/cli/.babelrc.json
Labels: bug, cli, patch

#9867 Core: Use telejson for websockets channel
  lib/channel-websocket/package.json
  lib/channel-websocket/src/index.ts
  yarn.lock
Labels: app: react-native, app: react-native-server, bug

#9874 Generate custom-elements.json from Stencil
  addons/docs/web-components/README.md
Labels: addon: docs, patch

#9880 Project root cleanup
  .prettierignore
  ROADMAP.md
  examples/svelte-kitchen-sink/jest.config.js
  scripts/svelte-transform.js
Labels: maintenance

#9879 TS improvements
  lib/addons/package.json
  lib/addons/src/index.ts
  lib/api/src/init-provider-api.ts
  lib/api/src/lib/stories.ts
  lib/api/src/modules/layout.ts
  lib/router/src/router.tsx
Labels: maintenance, typescript

#9882 UPDATE to latest version of eslint config
  .ci/danger/dangerfile.ts
  .eslintrc.js
  package.json
  yarn.lock
Labels: maintenance

#9881 chore(deps): Migrate to leven
  lib/cli/package.json
  lib/cli/src/generate.js
  yarn.lock
Labels: dependencies

#9885 Fix typo on AsyncStorage section
  MIGRATION.md
Labels: documentation, patch

#9894 Fix docs configuration file typos
  docs/src/pages/guides/guide-ember/index.md
  docs/src/pages/guides/guide-marko/index.md
  docs/src/pages/guides/guide-mithril/index.md
  docs/src/pages/guides/guide-preact/index.md
  docs/src/pages/guides/guide-rax/index.md
  docs/src/pages/guides/guide-riot/index.md
Labels: documentation, patch

#9888 fix(cli): capture unknown arguments the native way
  lib/cli/src/generate.js
Labels: high priority, patch

#9866 CLI: Add Yarn 2 compatibility
  .github/workflows/tests-cli.yml
  app/ember/package.json
  lib/cli/package.json
  lib/cli/src/generators/EMBER/index.js
  lib/cli/src/generators/METEOR/index.js
  lib/cli/src/generators/MITHRIL/index.js
  lib/cli/src/generators/REACT_SCRIPTS/index.js
  lib/cli/src/latest_version.js
  lib/cli/test/.gitignore
  lib/cli/test/berryfy_package_json.js
  lib/cli/test/fixtures/riot/package.json
  lib/cli/test/run_tests_yarn_2.sh
Labels: cli, compatibility with other tools, feature request, yarn / npm

#9902 Fix: Add downlevel dts
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/centered/package.json
  addons/contexts/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/essentials/package.json
  addons/events/package.json
  addons/graphql/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/options/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/marko/package.json
  app/mithril/package.json
  app/preact/package.json
  app/rax/package.json
  app/react/package.json
  app/riot/package.json
  app/server/package.json
  app/svelte/package.json
  app/vue/package.json
  app/web-components/package.json
  dev-kits/addon-decorator/package.json
  dev-kits/addon-parameter/package.json
  dev-kits/addon-preview-wrapper/package.json
  dev-kits/addon-roundtrip/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/channels/package.json
  lib/cli/package.json
  lib/client-api/package.json
  lib/client-logger/package.json
  lib/codemod/package.json
  lib/components/package.json
  lib/core-events/package.json
  lib/core/package.json
  lib/node-logger/package.json
  lib/postinstall/package.json
  lib/router/package.json
  lib/source-loader/package.json
  lib/theming/package.json
  lib/ui/package.json
  package.json
  scripts/compile-tsc.js
  yarn.lock
Labels: bug, typescript

#9877 Refactor Client API: pull metadata handling code into the store.
  MIGRATION.md
  addons/a11y/src/preset/addDecorator.ts
  addons/knobs/src/preset/addDecorator.ts
  app/vue/src/client/preview/index.ts
  examples/angular-cli/src/stories/__snapshots__/core.stories.storyshot
  examples/angular-cli/src/stories/addon-background.stories.ts
  examples/angular-cli/src/stories/addon-centered.stories.ts
  examples/official-storybook/preview.js
  examples/official-storybook/stories/core/parameters.stories.js
  examples/riot-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/custom-decorators.stories.storyshot
  lib/client-api/src/client_api.test.ts
  lib/client-api/src/client_api.ts
  lib/client-api/src/decorators.test.js
  lib/client-api/src/decorators.ts
  lib/client-api/src/hooks.test.js
  lib/client-api/src/index.ts
  lib/client-api/src/parameters.test.ts
  lib/client-api/src/parameters.ts
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
  lib/client-api/src/types.ts
  lib/core/src/server/preview/entries.js
  lib/core/src/server/preview/iframe-webpack.config.js
  package.json
  yarn.lock
Labels: BREAKING CHANGE, client-api

#9913 Update example main.js for Ember
  docs/src/pages/guides/guide-ember/index.md
Labels: documentation, patch

#9907 Centered: remove `typesVersions` attribute
  .gitignore
  addons/centered/package.json
  scripts/reset.js
Labels: addon: centered, bug, typescript

#9873 Props: Fix typescript unspecified default value
  addons/docs/src/frameworks/react/__testfixtures__/8143-ts-imported-types/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9493-ts-display-name/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9591-ts-import-types/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9592-ts-styled-props/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9721-ts-deprecated-jsdoc/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9764-ts-extend-props/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9827-ts-default-values/properties.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/ts-function-component/properties.snapshot
  addons/docs/src/frameworks/react/typeScript/handleProp.ts
Labels: addon: docs, block: props, bug, patch

#9906 chore: change rax link
  README.md
Labels: documentation, patch

#9916 Add missing dependencies or peerDependencies
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/centered/package.json
  addons/centered/src/mithril.tsx
  addons/centered/src/preact.tsx
  addons/centered/src/rax.js
  addons/centered/src/react.tsx
  addons/contexts/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/docs/src/frameworks/angular/config.ts
  addons/docs/src/frameworks/common/config.ts
  addons/docs/src/frameworks/ember/config.js
  addons/docs/src/frameworks/react/config.ts
  addons/docs/src/frameworks/vue/config.tsx
  addons/essentials/package.json
  addons/events/package.json
  addons/google-analytics/package.json
  addons/graphql/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/knobs/src/KnobManager.ts
  addons/links/package.json
  addons/options/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/viewport/package.json
  app/marionette/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/client-api/package.json
  lib/node-logger/package.json
  lib/source-loader/package.json
  lib/ui/package.json
  yarn.lock
Labels: maintenance

#9447 Addon-knobs: Add `disableForceUpdate` option
  addons/knobs/src/KnobManager.ts
  addons/knobs/src/registerKnobs.ts
  addons/knobs/src/type-defs.ts
Labels: addon: knobs, feature request

#9790 Addon-docs: Restore IE11 compat on Windows by transpiling correctly acorn-jsx for this OS (#8884)
  addons/docs/src/frameworks/common/preset.ts
Labels: addon: docs, bug

#9932 Add preset for Links Addon
  MIGRATION.md
  addons/links/preset.js
  addons/links/register.js
  addons/links/src/constants.ts
  addons/links/src/manager.ts
  addons/links/src/preset/addDecorator.ts
  addons/links/src/preset/index.ts
  addons/links/src/preview.ts
  addons/links/src/register.ts
Labels: addon: links, feature request

#9950 Cleanup docs wrt registering addons
  MIGRATION.md
  addons/a11y/README.md
  addons/actions/README.md
  addons/backgrounds/README.md
  addons/contexts/README.md
  addons/cssresources/README.md
  addons/design-assets/README.md
  addons/events/README.md
  addons/google-analytics/README.md
  addons/jest/README.md
  addons/knobs/README.md
  addons/links/README.md
  addons/viewport/README.md
  docs/src/pages/addons/using-addons/index.md
  docs/src/pages/addons/writing-addons/index.md
  docs/src/pages/presets/writing-presets/index.md
Labels: documentation

#9958 fix: remove useless \ in the documentation
  addons/docs/docs/recipes.md
Labels: documentation, patch

#9960 Core: Fix `configFilename` containing backticks
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: bug, core

#9940 ADD stories for layout in mdx as example and regression test
  examples/official-storybook/stories/core/layout.stories.mdx
Labels: maintenance

#9966 Documentation of writing add-on: replace 'withFoo' with the name of addon used in sample below 'withMyAddon'
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch

#9976 Update index.md
  docs/src/pages/guides/quick-start-guide/index.md
Labels: documentation, patch

#9971 CI: Fix GitHub unit test workflow
  .github/workflows/tests-cli.yml
  .github/workflows/tests-puppeteer.yml
  .github/workflows/tests-unit.yml
Labels: maintenance, patch

#9974 docs: add example for more meaningful static storybookUrl file path
  addons/storyshots/storyshots-puppeteer/README.md
Labels: documentation, patch

#9949 Addon-Queryparams: Add addon preset
  MIGRATION.md
  addons/queryparams/README.md
  addons/queryparams/preset.js
  addons/queryparams/src/index.ts
  addons/queryparams/src/preset/addDecorator.ts
  addons/queryparams/src/preset/index.ts
  examples/official-storybook/main.js
  examples/official-storybook/stories/addon-queryparams.stories.js
Labels: addon: queryparams, feature request

#9972 fix: missing } in the docs addon documentation
  addons/docs/docs/recipes.md
Labels: documentation, patch

#9986 Fix custom webpack config docs
  docs/src/pages/configurations/custom-webpack-config/index.md
Labels: documentation, patch

#9709 Cra-kitchen-sink : Add Named Color Palette Example(MDX)
  examples/official-storybook/stories/addon-docs/colorpalette.stories.mdx
Labels: addon: docs, feature request

#9999 Update Writing-Addon doc
  docs/src/pages/addons/writing-addons/index.md
Labels: documentation, patch
