Repository storybookjs/storybook, pull requests merged in 2020-12, with the labels that each got.

#12382 Angular: Run setProps in the NgZone
  app/angular/src/client/preview/angular/helpers.ts
Labels: app: angular, bug

#13055 Core: Replace preset-env polyfills with babel-polyfills
  app/react/src/server/framework-preset-react.ts
  lib/core/package.json
  lib/core/src/server/common/babel.ts
  lib/core/src/server/common/es6Transpiler.ts
  scripts/run-e2e-config.ts
  yarn.lock
Labels: maintenance

#13275 Core: Ensure node `name` does not contain leading/trailing whitespace
  lib/api/src/lib/stories.ts
  lib/api/src/tests/stories.test.js
  lib/client-api/src/story_store.ts
Labels: bug, core

#13329 Makes @babel/core an optional peer dependency
  app/react/package.json
Labels: maintenance

#12665 Addon-docs: Fix type aliases and enum types from Angular Compodoc JSON
  addons/docs/src/frameworks/angular/compodoc.test.ts
  addons/docs/src/frameworks/angular/compodoc.ts
  addons/docs/src/frameworks/angular/types.ts
  examples/angular-cli/src/stories/component-with-enums/__snapshots__/enums.component.stories.storyshot
  examples/angular-cli/src/stories/component-with-enums/enums.component.html
  examples/angular-cli/src/stories/component-with-enums/enums.component.stories.ts
  examples/angular-cli/src/stories/component-with-enums/enums.component.ts
Labels: addon: docs, app: angular, block: argstable, bug, hacktoberfest-accepted

#13346 Fix babel link
  docs/configure/babel.md
Labels: documentation, patch

#12980 UI: Add support for expand/collapse keyboard shortcuts
  lib/ui/src/components/sidebar/useExpanded.ts
Labels: bug, ui

#13276 Update deprecated type
  addons/docs/src/frameworks/react/__testfixtures__/8740-ts-multi-props/input.tsx
  docs/snippets/react/button-story-rename-story.ts.mdx
  docs/snippets/react/button-story-with-emojis.ts.mdx
  docs/snippets/react/button-story.ts.mdx
Labels: documentation, patch, typescript

#12863 Composition: Filter out disabled refs in getAutoRefs
  lib/cli/src/js-package-manager/JsPackageManager.ts
  lib/core/src/server/manager/manager-config.ts
Labels: bug, composition, tracked

#13330 Core: Add typescript as optional peer dependency
  app/react/package.json
  lib/core/package.json
Labels: maintenance

#13289 Dependencies: Rebuild yarn.lock
  .eslintrc.js
  addons/a11y/src/components/Report/Rules.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/a11y/src/typings.d.ts
  addons/actions/package.json
  addons/actions/src/preview/action.ts
  addons/actions/src/typings.d.ts
  addons/cssresources/src/css-resource-panel.test.tsx
  addons/docs/src/blocks/Meta.tsx
  addons/docs/src/frameworks/react/__testfixtures__/9626-js-default-values/docgen.snapshot
  addons/docs/src/frameworks/react/__testfixtures__/9626-js-default-values/input.js
  addons/docs/src/frameworks/vue/prepareForInline.ts
  addons/docs/src/mdx/mdx-compiler-plugin.js
  addons/jest/src/components/Panel.tsx
  app/angular/src/client/preview/angular/helpers.ts
  app/react/package.json
  dev-kits/addon-decorator/package.json
  dev-kits/addon-parameter/package.json
  dev-kits/addon-preview-wrapper/package.json
  dev-kits/addon-roundtrip/package.json
  examples/official-storybook/components/FlowTypeButton.js
  examples/official-storybook/components/TableComponent.js
  examples/svelte-kitchen-sink/src/stories/__snapshots__/addon-links.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/__snapshots__/welcome.stories.storyshot
  lib/cli/src/extract.ts
  lib/core/package.json
  lib/core/src/server/manager/manager-webpack.config.ts
  lib/core/src/server/preview/virtualModuleEntry.template.js
  lib/core/src/server/templates/base-manager-head.html
  lib/core/src/server/templates/base-preview-head.html
  lib/ui/src/components/sidebar/useExpanded.ts
  package.json
  scripts/run-registry.ts
  scripts/utils/serve.ts
  tsconfig.json
  yarn.lock
Labels: maintenance

#13352 Addon-docs: ArgTypes optional on Meta
  addons/docs/src/blocks/Meta.tsx
Labels: addon: docs, bug, patch, typescript

#13343 Addon-storyshots: Add React as peer dependency
  addons/storyshots/storyshots-core/package.json
Labels: addon: storyshots, dependencies

#13348 Core: Fix IE11 compatibility by using XHR and plain ES5
  lib/core/src/server/dev-server.ts
  lib/core/src/server/templates/base-manager-head.html
  lib/core/src/server/templates/base-preview-head.html
Labels: bug, core, patch

#13215 Angular: Overhaul preview renderer
  MIGRATION.md
  app/angular/jest.config.js
  app/angular/package.json
  app/angular/setup-jest.ts
  app/angular/src/client/preview/angular-beta/ComponentClassFromStoryComponent.ts
  app/angular/src/client/preview/angular-beta/ComponentClassFromStoryTemplate.ts
  app/angular/src/client/preview/angular-beta/NgComponentAnalyzer.test.ts
  app/angular/src/client/preview/angular-beta/NgComponentAnalyzer.ts
  app/angular/src/client/preview/angular-beta/NgModulesAnalyzer.test.ts
  app/angular/src/client/preview/angular-beta/NgModulesAnalyzer.ts
  app/angular/src/client/preview/angular-beta/RenderNgAppService.test.ts
  app/angular/src/client/preview/angular-beta/RenderNgAppService.ts
  app/angular/src/client/preview/angular-beta/app.token.ts
  app/angular/src/client/preview/render.ts
  app/angular/src/client/preview/types-6-0.ts
  app/angular/src/server/__tests__/angular-cli_config.test.ts
  app/angular/tsconfig.spec.json
  examples/angular-cli/src/stories/module-context/chips.module.ts
  jest.config.js
  tsconfig.json
  yarn.lock
Labels: app: angular, maintenance

#13341 Storyshots: Fix missing `done` attribute on type definition
  addons/storyshots/storyshots-core/src/api/StoryshotsOptions.ts
Labels: addon: storyshots, bug, patch, typescript

#13180 docs(MIGRATION): add preset information for addon-backgrounds in 6.1
  MIGRATION.md
Labels: documentation, patch

#13355 UI: Fix display of custom brand image
  lib/ui/src/components/sidebar/Brand.tsx
  lib/ui/src/components/sidebar/Heading.stories.tsx
  lib/ui/src/components/sidebar/Heading.tsx
Labels: bug, patch, ui

#13368 CLI: Fix stories path in Introduction.stories.mdx
  lib/cli/src/frameworks/common/Introduction.stories.mdx
Labels: bug, cli, patch

#13161 Documentation: Updates theming documentation
  docs/configure/storybook-custom-theme.png
  docs/configure/storybook-starter-custom-theme.png
  docs/configure/theming.md
  docs/snippets/common/storybook-theme-example-variables.ts.mdx
  docs/snippets/common/your-theme.js.mdx
Labels: documentation, patch

#13225 CLI: Replace inquirer with prompts
  app/react/package.json
  lib/cli/package.json
  lib/cli/src/initiate.ts
  lib/core/package.json
  lib/core/src/server/build-dev.ts
  package.json
  scripts/bootstrap.js
  scripts/build-package.js
  scripts/test.js
  scripts/utils/cli-utils.js
  yarn.lock
Labels: cli, dependencies, performance issue

#13386 Addon-docs: Handle svelte docgen failures gracefully
  addons/docs/src/frameworks/svelte/extractArgTypes.ts
  examples/svelte-kitchen-sink/src/stories/error.stories.js
  examples/svelte-kitchen-sink/src/stories/views/ErrorView.svelte
Labels: addon: docs, app: svelte, block: argstable, bug, patch

#13344 Core: Fix `--static-dir` with absolute path on Windows
  lib/core/package.json
  lib/core/src/server/build-static.ts
  lib/core/src/server/dev-server.ts
  lib/core/src/server/utils/static-files.test.ts
  lib/core/src/server/utils/static-files.ts
  yarn.lock
Labels: bug, core

#13404 Adjust addon titles and table of contents
  docs/addons/addons-api.md
  docs/addons/install-addons.md
  docs/addons/introduction.md
  docs/addons/writing-addons.md
  docs/addons/writing-presets.md
  docs/toc.js
Labels: documentation

#13397 Typo in addon-controls documentation
  addons/controls/README.md
Labels: documentation, patch

#13401 (docs): include in the what's a story documentation an Angular snippet
  docs/get-started/whats-a-story.md
Labels: documentation, patch

#13407 Docs: Fix bad quotes in showRoots example
  docs/snippets/common/storybook-manager-disable-roots.js.mdx
Labels: documentation, patch

#13320 CI: Speed up CircleCI workflows
  .circleci/config.yml
  .github/workflows/tests-cli.yml
  .github/workflows/trigger-circle-ci-workflow.yml
  jest.config.js
  package.json
  scripts/test.js
Labels: maintenance, run e2e extended test suite

#13423 UI: Fix null ref in sidebar
  lib/ui/src/components/sidebar/useExpanded.ts
  lib/ui/src/components/sidebar/useHighlighted.ts
Labels: bug, patch, ui

#13425 Core: Generate bundle size report for prebuilt manager
  lib/core/package.json
  lib/core/src/server/manager/manager-webpack.config.ts
  yarn.lock
Labels: core, maintenance

#13432 Main.js: Add previewHead, previewBody, managerHead presets
  docs/addons/writing-presets.md
  docs/snippets/common/storybook-main-preview-head.js.mdx
  lib/core/src/server/manager/manager-webpack.config.ts
  lib/core/src/server/preview/iframe-webpack.config.ts
  lib/core/src/server/utils/template.test.ts
Labels: configuration, feature request, presets

#13431 Core: Fix `modulesCount` cache storage and retrieval
  lib/core/src/server/dev-server.ts
Labels: bug, core

#13424 Perf: Replace react-hotkeys with useEffect keybinding
  lib/ui/package.json
  lib/ui/src/components/sidebar/Search.tsx
  lib/ui/src/components/sidebar/SearchResults.tsx
  lib/ui/src/components/sidebar/useExpanded.ts
  lib/ui/src/components/sidebar/useHighlighted.ts
  lib/ui/src/keybinding.ts
  lib/ui/src/settings/index.tsx
  yarn.lock
Labels: maintenance, performance issue

#13439 Components: Cleanup circular dependencies
  lib/components/src/Zoom/ZoomElement.tsx
  lib/components/src/Zoom/ZoomIFrame.tsx
  lib/components/src/Zoom/browserSupportsCssZoom.ts
Labels: components, maintenance

#13434 Update react-popper-tooltip and @popperjs/core for react17
  lib/components/package.json
  yarn.lock
Labels: dependencies, patch

#13443 Grammar corrections
  MIGRATION.md
Labels: documentation

#13438 Chore: How to add to Storybook addon catalog documentation.
  docs/addons/addon-catalog.md
  docs/addons/addon-display.png
  docs/addons/writing-addons.md
  docs/toc.js
Labels: documentation, patch

#13452 CLI: Add overrides to CRA ESLint config
  lib/cli/src/generators/REACT_SCRIPTS/index.ts
  lib/cli/src/generators/baseGenerator.ts
  lib/cli/src/js-package-manager/JsPackageManager.ts
  lib/cli/src/js-package-manager/PackageJson.ts
Labels: bug, cli, cra

#13457 Addon-docs: Remove unused titleFunction export
  addons/docs/src/public_api.ts
  examples/official-storybook/stories/addon-docs/meta-string-template.stories.mdx
  examples/official-storybook/stories/addon-docs/title-generators.ts
Labels: addon: docs, maintenance

#13430 Perf: Lazy load OverlayScrollbars
  lib/components/src/ScrollArea/GlobalScrollAreaStyles.tsx
  lib/components/src/ScrollArea/OverlayScrollbars.tsx
  lib/components/src/ScrollArea/ScrollArea.tsx
Labels: maintenance, performance issue, run e2e extended test suite

#13382 Angular: Fix `configFile: undefined` in ts-loader options
  app/angular/src/server/ts_config.ts
Labels: app: angular, bug, typescript

#13451 Update addon descriptions to match frontpage
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/controls/package.json
  addons/docs/package.json
  addons/links/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storysource/package.json
  addons/toolbars/package.json
  addons/viewport/package.json
Labels: documentation

#13466 Svelte: Statically load docgen info for svelte components
  addons/docs/src/frameworks/svelte/extractArgTypes.ts
  addons/docs/src/frameworks/svelte/preset.ts
  addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts
  examples/svelte-kitchen-sink/src/stories/button.stories.js
Labels: app: svelte, bug, patch

#13476 Addon-docs: Tighten preset webpack pattern for mdx stories
  addons/docs/src/frameworks/common/preset.ts
Labels: addon: docs, bug, patch

#13488 Improve docs for loading fonts locally
  docs/configure/images-and-assets.md
  docs/get-started/setup.md
Labels: documentation, patch

#13474 Core: Use fs-extra emptyDir so build works on docker volume
  lib/core/src/server/build-static.ts
Labels: bug, compatibility with other tools, core, patch, run e2e extended test suite

#13487 Addon-docs: Fix angular without compodoc
  addons/docs/src/frameworks/angular/compodoc.ts
Labels: addon: docs, app: angular, bug, patch, run e2e extended test suite

#12395 Web-components: Add typescript types and CLI template
  app/web-components/src/client/index.ts
  app/web-components/src/client/preview/types-6-0.ts
  app/web-components/src/client/preview/types.ts
  app/web-components/types-6-0.d.ts
  lib/cli/src/frameworks/web-components/js/Button.js
  lib/cli/src/frameworks/web-components/js/Button.stories.js
  lib/cli/src/frameworks/web-components/js/Header.js
  lib/cli/src/frameworks/web-components/js/Header.stories.js
  lib/cli/src/frameworks/web-components/js/Page.js
  lib/cli/src/frameworks/web-components/js/Page.stories.js
  lib/cli/src/frameworks/web-components/ts/Button.stories.ts
  lib/cli/src/frameworks/web-components/ts/Button.ts
  lib/cli/src/frameworks/web-components/ts/Header.stories.ts
  lib/cli/src/frameworks/web-components/ts/Header.ts
  lib/cli/src/frameworks/web-components/ts/Page.stories.ts
  lib/cli/src/frameworks/web-components/ts/Page.ts
  scripts/run-e2e-config.ts
Labels: app: web-components, cli, feature request, run e2e extended test suite, typescript

#13479 Perf: Bundle only required syntax highlighter languages
  addons/docs/blocks.d.ts
  addons/storysource/src/StoryPanel.tsx
  lib/components/src/index.ts
  lib/components/src/syntaxhighlighter/syntaxhighlighter-types.ts
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: maintenance, performance issue

#13501 Core: Fix typing of dev CLI options
  lib/core/src/server/cli/dev.ts
Labels: core, maintenance, typescript

#13110 Perf: Reuse SVG icon paths by using symbols
  examples/official-storybook/preview.js
  lib/components/src/icon/icon.tsx
  lib/components/src/index.ts
  lib/ui/src/app.tsx
  lib/ui/src/components/sidebar/Menu.stories.tsx
  lib/ui/src/components/sidebar/TreeNode.tsx
Labels: maintenance, performance issue, ui

#13509 fix(docs): correct react viewport snippet's import
  docs/snippets/react/my-component-story-configure-viewports.js.mdx
Labels: documentation, patch

#13523 Removing references to CLI tests from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, patch

#13521 CLI: Ensure --host option changes the network host
  lib/core/src/server/dev-server.test.ts
  lib/core/src/server/dev-server.ts
Labels: bug, cli, patch

#13518 Typescript: Fix qs import in @storybook/client-api
  lib/client-api/src/queryparams.ts
Labels: bug, core, patch, typescript

#13158 Server: Forward globals in fetchStoryHtml
  app/server/README.md
  app/server/src/client/preview/render.ts
  app/server/src/client/preview/types.ts
Labels: app: server, args, feature request

#13533 Addon-docs: Use theme text color header anchors
  addons/docs/src/blocks/mdx.tsx
Labels: addon: docs, bug, mdx, theming

#12770 Replace "ES7" with "ES2017"
  app/web-components/README.md
Labels: documentation, patch

#13535 Addon-jest: Infer parameter from story filename if not provided
  addons/jest/README.md
  addons/jest/src/index.ts
  addons/jest/src/shared.test.ts
  addons/jest/src/shared.ts
  addons/jest/tsconfig.json
  examples/official-storybook/stories/addon-jest.stories.js
Labels: addon: jest, feature request
