Repository storybookjs/storybook, pull requests merged in 2020-01, with the labels that each got.

#9284 Fix minor spelling mistake
  docs/src/pages/guides/guide-react/index.md
Labels: documentation, patch

#9281 fix: adjust web component name in cli
  app/web-components/README.md
Labels: documentation

#9291 Storyshots Puppeteer: don't infer story ID from its name
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storyshots/storyshots-puppeteer/src/__tests__/url.test.ts
  addons/storyshots/storyshots-puppeteer/src/puppeteerTest.ts
  addons/storyshots/storyshots-puppeteer/src/url.ts
  examples/official-storybook/stories/addon-storyshots.stories.js
  examples/official-storybook/storyshots-puppeteer/__image_snapshots__/storyshots-image-runner-js-image-snapshots-addons-storyshots-block-1-snap.png
  examples/official-storybook/storyshots-puppeteer/__image_snapshots__/storyshots-image-runner-js-image-snapshots-addons-storyshots-block-story-1-snap.png
Labels: addon: storyshots, bug, csf

#9280 Merge pull request #9280 from weyert/bugfixes/fix-simplify-issue
  lib/core/src/server/common/babel.js
Labels: babel / webpack, bug, core

#9307 Addon-docs: Tweak props table paragraph spacing
  examples/official-storybook/components/DocgenButton.js
  lib/components/src/blocks/PropsTable/PropRow.tsx
Labels: block: props, bug, theming

#9303 React: Upgrade babel-plugin-react-docgen to 4.0.0
  app/react/package.json
  yarn.lock
Labels: app: react, dependencies

#9308 Add minimal typescript example to official-storybook
  examples/official-storybook/components/TsButton.tsx
  examples/official-storybook/stories/addon-docs/ts-button.stories.tsx
Labels: addon: docs, maintenance

#9320 Router: Add storyNameFromExport to avoid breaking changes
  lib/router/package.json
  lib/router/src/utils.ts
Labels: bug, core

#9315 CSF: Use `__namedExportsOrder` array in loader if provided
  examples/official-storybook/stories/core/named-export-order.stories.js
  lib/core/src/client/preview/start.js
Labels: BREAKING PRERELEASE, core, csf, feature request

#9331 Addon-docs: Fix scroll behavior on page navigation
  addons/docs/src/blocks/Meta.tsx
  addons/docs/src/blocks/utils.ts
  examples/official-storybook/stories/addon-docs/addon-docs-blocks.stories.js
Labels: addon: docs, bug

#9333 Revert "Source-loader: Disable no-implicit-any linting"
  lib/source-loader/src/server/build.js
Labels: bug, source-loader, typescript

#9337 Axe storyshots: move to original @wordpress/jest-puppeteer-axe package
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storyshots/storyshots-puppeteer/src/axeTest.ts
  yarn.lock
Labels: addon: storyshots, dependencies

#9321 Addon-Docs: Handle leaf/non-leaf mixture in docs-mode navigation
  examples/official-storybook/stories/addon-docs/mixed-leaves-component.stories.js
  examples/official-storybook/stories/addon-docs/mixed-leaves-folder.stories.js
  examples/official-storybook/stories/core/named-export-order.stories.js
  lib/ui/src/containers/nav.js
  lib/ui/src/containers/nav.test.js
Labels: addon: docs, bug, ui

#9346 React: Check CRA is installed before showing warning
  app/react/src/server/framework-preset-cra.ts
Labels: app: react, bug

#9347 Presets: Fix register.js addons entry
  lib/core/src/server/presets.js
  lib/core/src/server/presets.test.js
Labels: bug, core

#9354 Core: Fix HMR for global decorators in main.js config
  lib/client-api/src/config_api.ts
  lib/core/src/server/preview/iframe-webpack.config.js
Labels: bug, core

#9356 Nav UI: Nodes are components only if they contain ALL leaf nodes
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.js
Labels: bug, ui

#9220 chore(rax): supplement rax
  .babelrc.js
  .eslintignore
  .github/autolabeler.yml
  .github/automention.yml
  ADDONS_SUPPORT.md
  README.md
  addons/contexts/package.json
  addons/contexts/rax.js
  addons/contexts/src/preview/frameworks/rax.ts
  addons/storyshots/storyshots-core/src/frameworks/SupportedFramework.ts
  addons/storyshots/storyshots-core/src/frameworks/rax/loader.ts
  addons/storyshots/storyshots-core/src/frameworks/rax/renderTree.ts
  addons/storyshots/storyshots-core/src/typings.d.ts
  examples/rax-kitchen-sink/.storybook/main.js
  examples/rax-kitchen-sink/babel.config.js
  examples/rax-kitchen-sink/build.json
  examples/rax-kitchen-sink/jest-addon.config.js
  examples/rax-kitchen-sink/jest.config.js
  examples/rax-kitchen-sink/package.json
  examples/rax-kitchen-sink/public/index.html
  examples/rax-kitchen-sink/public/rax-logo.png
  examples/rax-kitchen-sink/src/app.js
  examples/rax-kitchen-sink/src/components/App/App.test.js
  examples/rax-kitchen-sink/src/components/App/__snapshots__/App.test.js.snap
  examples/rax-kitchen-sink/src/components/App/index.js
  examples/rax-kitchen-sink/src/components/App/index.stylesheet
  examples/rax-kitchen-sink/src/components/Welcome/Welcome.test.js
  examples/rax-kitchen-sink/src/components/Welcome/__snapshots__/Welcome.test.js.snap
  examples/rax-kitchen-sink/src/components/Welcome/index.js
  examples/rax-kitchen-sink/src/document/index.jsx
  examples/rax-kitchen-sink/src/index.js
  examples/rax-kitchen-sink/src/stories/addon-contexts.stories.js
  examples/rax-kitchen-sink/src/stories/addon-jest.stories.js
  examples/rax-kitchen-sink/src/stories/index.stories.js
  examples/rax-kitchen-sink/src/stories/note.md
  package.json
  yarn.lock
Labels: app: rax, feature request

#9249 feat(ui, components): style the loader with the design-system
  lib/components/src/Loader/Loader.tsx
  lib/components/src/shared/animation.ts
  lib/ui/src/app.stories.js
  lib/ui/src/components/preview/preview.js
  lib/ui/src/components/preview/preview.stories.js
  lib/ui/src/components/sidebar/SidebarItem.tsx
Labels: feature request, ui

#9257 Make canvas link a link
  lib/components/src/bar/button.tsx
  lib/components/src/blocks/Toolbar.tsx
  lib/theming/package.json
  lib/theming/src/index.ts
  lib/ui/src/components/preview/preview.js
  yarn.lock
Labels: accessibility, components, other, patch, ui

#9362 Addon-docs / web-components: Rename 'props' to 'properties' in props table
  addons/docs/src/frameworks/web-components/config.js
Labels: addon: docs, maintenance

#9364 Official-storybook: Prop table example for multiple named exports
  examples/official-storybook/components/ButtonGroup.js
  examples/official-storybook/stories/addon-docs/addon-docs-blocks.stories.js
Labels: addon: docs, maintenance

#9359 CLI: Fix `sb init` to use spawn.sync if creating package.json
  .vscode/launch.json
  lib/cli/lib/helpers.js
  lib/cli/lib/npm_init.js
Labels: bug, cli

#9360 cssresources-addon: Do not use SyntaxHighlighter with the very long code-content.
  addons/cssresources/package.json
  addons/cssresources/src/css-resource-panel.tsx
Labels: addon: cssresources, feature request

#9365 Upgrade @types/webpack-env and @types/node to fix conflicting types
  app/react/package.json
  yarn.lock
Labels: dependencies:update

#9252 Remove `textTransform: 'capitalize'` from component `bar/button`
  lib/components/src/bar/button.tsx
Labels: ui

#9368 Document showRoots for 5.3 by parameters
  MIGRATION.md
  docs/src/pages/configurations/options-parameter/index.md
Labels: documentation

#9377 add toolbar documentation
  docs/src/pages/basics/toolbar-guide/index.md
Labels: documentation

#9180 Use TS strict mode in a11y addon sources
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/ColorBlindness.tsx
  addons/a11y/src/components/Report/HighlightToggle.tsx
  addons/a11y/src/components/Report/Rules.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/a11y/src/index.ts
  addons/a11y/tsconfig.json
Labels: addon: a11y, maintenance, typescript

#9381 Addon-docs: Fix link CORS errors using channel navigate event
  addons/docs/package.json
  addons/docs/src/blocks/DocsContainer.tsx
  addons/docs/src/blocks/mdx.tsx
  examples/official-storybook/stories/addon-docs/markdown.stories.mdx
  lib/api/package.json
  lib/api/src/index.tsx
  lib/api/src/modules/url.ts
  lib/core-events/src/index.ts
Labels: addon: docs, bug

#9388 Merge `master` into `next` for 5.3.0 release
  addons/knobs/package.json
  addons/notes/README.md
  addons/storysource/theming-light-dark.png
  app/react/package.json
  app/riot/package.json
  docs/src/pages/basics/writing-stories/index.md
  docs/src/pages/configurations/theming/index.md
  docs/src/pages/guides/guide-ember/index.md
  docs/src/pages/guides/guide-svelte/index.md
  docs/src/pages/presets/preset-gallery/index.md
  docs/src/versions/latest.json
  examples-native/crna-kitchen-sink/package.json
  examples/official-storybook/stories/addon-docs/forward-ref.stories.js
  examples/official-storybook/stories/addon-docs/react-memo.stories.js
  examples/vue-kitchen-sink/src/stories/__snapshots__/core-errors.stories.storyshot
  examples/vue-kitchen-sink/src/stories/core-errors.stories.js
  lib/codemod/src/lib/utils.js
  lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/digit.output.js
  lib/core/package.json
  package.json
  yarn.lock
Labels: maintenance

#9398 Core: Fix generated entry to import at top of file
  lib/core/src/server/preview/iframe-webpack.config.js
  yarn.lock
Labels: bug, core

#9402 Fix typo in addParameter() example doc
  docs/src/pages/configurations/options-parameter/index.md
Labels: documentation, patch

#9406 CHANGE docs & examples to prefer webpackFinal over webpack property
  addons/docs/README.md
  app/web-components/README.md
  docs/src/pages/basics/faq/index.md
  docs/src/pages/configurations/custom-webpack-config/index.md
  docs/src/pages/configurations/typescript-config/index.md
  docs/src/pages/presets/writing-presets/index.md
  examples/ember-cli/.storybook/main.js
  examples/marko-cli/.storybook/main.js
  examples/mithril-kitchen-sink/.storybook/main.js
  examples/official-storybook/main.js
  examples/polymer-cli/.storybook/main.js
  examples/preact-kitchen-sink/.storybook/main.js
  examples/rax-kitchen-sink/.storybook/main.js
  examples/riot-kitchen-sink/.storybook/main.js
  examples/svelte-kitchen-sink/.storybook/main.js
  lib/cli/generators/WEBPACK_REACT/template-csf/.storybook/main.js
  lib/cli/generators/WEBPACK_REACT/template-mdx/.storybook/main.js
Labels: documentation, patch

#9410 Source-loader: Disable eslint entirely for generated code
  lib/source-loader/src/server/build.js
Labels: bug, source-loader

#8883 Addon-a11y: Support manual run
  addons/a11y/README.md
  addons/a11y/src/components/A11YPanel.test.js
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/__snapshots__/A11YPanel.test.js.snap
  addons/a11y/src/constants.ts
  addons/a11y/src/index.ts
  lib/components/src/icon/icon.tsx
Labels: addon: a11y, feature request

#9416 Addon-knobs: Fix null knob values in select
  addons/knobs/src/components/types/Select.tsx
  examples/official-storybook/stories/addon-knobs/with-knobs.stories.js
Labels: addon: knobs, bug, patch

#9390 Angular: Fix missing architect properties
  app/angular/src/server/angular-cli_config.ts
Labels: app: angular, bug, patch

#9424 Core: Preserve kind load order on HMR when no sortFn is provided
  lib/client-api/src/client_api.test.ts
  lib/client-api/src/story_store.ts
Labels: bug, core, patch

#9425 UI: Fix edge case where only one legacy separator is defined
  lib/api/src/modules/stories.ts
Labels: bug, patch, ui

#9426 Emphasize the happy path in storyshots README.
  addons/storyshots/storyshots-core/README.md
Labels: documentation

#9417 Source-loader: Disable linting altogether
  lib/source-loader/src/server/build.js
Labels: bug, patch, source-loader

#9440 Merge pull request #9440 from ludo237/patch-3
  docs/src/pages/guides/guide-vue/index.md
Labels: documentation, patch

#8486 Change viewport styling to more closely match v4
  addons/viewport/src/Tool.tsx
Labels: addon: viewport, bug, patch

#9459 Adding missing '=' for Svelte config
  docs/src/pages/guides/guide-svelte/index.md
Labels: documentation, patch

#9448 Updated documentation with syntax highlighting.
  docs/src/pages/guides/guide-react-native/index.md
Labels: documentation

#9482 Core: Fix default story sort
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
Labels: bug, core, patch

#9485 Core: Fix addon/preset detection for local addons
  lib/core/src/server/presets.js
  lib/core/src/server/presets.test.js
Labels: bug, core, patch, presets

#9486 Core: Fix presets register panel
  lib/core/src/server/presets.js
  lib/core/src/server/presets.test.js
Labels: addon: notes, bug, core, patch

#9492 Merge pull request #9492 from storybookjs/9490-fix-source-loader-imports
  examples/official-storybook/stories/core/interleaved-exports.stories.js
  lib/source-loader/src/server/__snapshots__/build.test.js.snap
  lib/source-loader/src/server/abstract-syntax-tree/traverse-helpers.js
  lib/source-loader/src/server/build.js
  lib/source-loader/src/server/build.test.js
Labels: bug, patch, source-loader

#9497 Core: Fix typo for loading addon-notes/register-panel
  lib/core/src/server/presets.js
  lib/core/src/server/presets.test.js
Labels: bug, core, patch

#9494 Merge pull request #9494 from jsjoeio/patch-2
  MIGRATION.md
Labels: app: react-native, documentation, patch

#9504 Core: Fix default sorting of docs-only stories
  examples/official-storybook/intro.stories.mdx
  examples/official-storybook/main.js
  lib/client-api/src/client_api.test.ts
  lib/client-api/src/story_store.ts
Labels: bug, core

#9505 Source-loader: Bypass if file has no exports
  examples/official-storybook/stories/core/reexport-source-loader.stories.js
  lib/source-loader/src/server/build.js
Labels: bug, source-loader

#9510 Add BBC to list of examples
  docs/src/pages/examples/_examples.yml
  docs/src/pages/examples/thumbnails/bbc.jpg
Labels: documentation, patch

#9509 chore(deps): update husky to v4
  package.json
  yarn.lock
Labels: dependencies:update

#9508 Refactor: use startsWith
  lib/core/src/server/presets.js
Labels: code refactoring, maintenance

#9524 Fix typos in "Writing presets"
  docs/src/pages/presets/writing-presets/index.md
Labels: documentation, patch

#9513 Addon-docs: Preserve Source indentation by default
  lib/components/src/blocks/Source.tsx
Labels: bug, ui

#9525 Addon-docs Props: Convert default prop value to string
  examples/cra-ts-kitchen-sink/src/stories/Button.tsx
  lib/components/src/blocks/PropsTable/PropValue.tsx
Labels: block: props, bug, patch

#9526 Update addon storyshot puppeteer doc
  MIGRATION.md
  addons/storyshots/storyshots-puppeteer/README.md
Labels: addon: storyshots, documentation, patch

#9545 Core: Fix legacy story URLs
  lib/client-api/src/story_store.ts
  lib/core/src/client/preview/start.js
  lib/core/src/client/preview/url.js
  lib/core/src/client/preview/url.test.js
Labels: bug, core, patch

#9538 Node-logger: Move `@types/npmlog` to dependencies
  lib/node-logger/package.json
  yarn.lock
Labels: bug, patch, typescript

#9536 Clean usage of `@types/webpack-env` dep in all packages
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/centered/package.json
  addons/cssresources/package.json
  addons/docs/package.json
  addons/essentials/tsconfig.json
  addons/events/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/notes/package.json
  addons/ondevice-backgrounds/tsconfig.json
  addons/ondevice-notes/tsconfig.json
  addons/options/package.json
  addons/queryparams/package.json
  app/angular/package.json
  app/angular/src/client/index.ts
  app/angular/tsconfig.json
  app/html/package.json
  app/mithril/package.json
  app/preact/package.json
  app/svelte/package.json
  app/svelte/tsconfig.json
  app/vue/package.json
  app/web-components/package.json
  examples/angular-cli/package.json
  lib/client-api/package.json
  lib/components/tsconfig.json
  lib/router/tsconfig.json
  lib/theming/tsconfig.json
  package.json
  yarn.lock
Labels: bug, patch, typescript

#9541 Update index.md
  docs/src/pages/guides/guide-react-native/index.md
Labels: documentation

#9540 Fixed Angular button example story
  lib/cli/generators/ANGULAR/template-csf/src/stories/1-Button.stories.ts
Labels: app: angular, bug, cli, patch

#7981 Add/app marionette js
  README.md
  app/marionette/README.md
  app/marionette/bin/build.js
  app/marionette/bin/index.js
  app/marionette/package.json
  app/marionette/src/client/index.js
  app/marionette/src/client/preview/element_check.js
  app/marionette/src/client/preview/globals.js
  app/marionette/src/client/preview/index.js
  app/marionette/src/client/preview/render.js
  app/marionette/src/server/build.js
  app/marionette/src/server/framework-preset-marionette.js
  app/marionette/src/server/index.js
  app/marionette/src/server/options.js
  app/marionette/standalone.js
  lib/cli/generators/MARIONETTE/index.js
  lib/cli/generators/MARIONETTE/template/.storybook/config.js
  lib/cli/generators/MARIONETTE/template/stories/index.stories.js
  lib/cli/lib/detect.js
  lib/cli/lib/initiate.js
  lib/cli/lib/project_types.js
  lib/cli/package.json
  yarn.lock
Labels: feature request

#9229 Merge pull request #9229 from storybookjs/core/preview-layouts
  examples/official-storybook/stories/core/layout.stories.js
  lib/core/src/client/preview/start.js
Labels: core, feature request

#9565 Typescript: Migrate `@storybook/polymer
  addons/a11y/src/components/Report/HighlightToggle.tsx
  addons/contexts/src/manager/components/ToolBar.test.tsx
  addons/contexts/src/manager/components/ToolBarControl.test.tsx
  app/polymer/package.json
  app/polymer/src/client/index.ts
  app/polymer/src/client/preview/globals.ts
  app/polymer/src/client/preview/index.ts
  app/polymer/src/client/preview/render.ts
  app/polymer/src/client/preview/types.ts
  app/polymer/src/server/build.ts
  app/polymer/src/server/framework-preset-polymer.ts
  app/polymer/src/server/index.ts
  app/polymer/src/server/options.ts
  app/polymer/src/typings.d.ts
  app/polymer/tsconfig.json
  examples/cra-ts-kitchen-sink/src/stories/docgen-tests/types/ts-types.tsx
  lib/components/src/tooltip/TooltipMessage.stories.tsx
  lib/components/src/tooltip/WithTooltip.tsx
Labels: app: polymer, cleanup, typescript

#9453 feat(addon-docs): named colors with ColorPalette
  lib/components/src/blocks/ColorPalette.stories.tsx
  lib/components/src/blocks/ColorPalette.tsx
Labels: addon: docs, feature request

#9567 Addon-docs: Remove hard-coded lineHeight in Typeset block
  lib/components/src/blocks/Typeset.tsx
Labels: bug, ui

#9560 Addon-docs: Fix TS false default value in prop table
  examples/cra-ts-kitchen-sink/src/stories/Button.tsx
  lib/components/src/blocks/PropsTable/PropValue.tsx
Labels: addon: docs, bug, patch

#9574 CLI: Improve Rax template
  ADDONS_SUPPORT.md
  lib/cli/generators/RAX/index.js
  lib/cli/generators/RAX/template-csf/stories/1-View.stories.js
Labels: app: rax, cli, maintenance

#9571 Revert "Revert "Add BBC to list of examples""
  app/marionette/src/server/build.js
  app/marionette/src/server/index.js
  docs/src/pages/examples/_examples.yml
  docs/src/pages/examples/thumbnails/bbc.jpg
Labels: documentation

#9569 IMPROVE the build-storybooks script
  scripts/build-storybooks.js
Labels: maintenance

#9566 api: adding useSharedState, useStoryState
  examples/dev-kits/manager.js
  examples/dev-kits/stories/addon-usestorystate.tsx
  lib/api/src/index.tsx
  lib/client-api/src/hooks.ts
  lib/core-events/src/index.ts
Labels: api: addons, client-api, core, feature request

#9579 Bumped react-dev-utils dependency to v10.
  app/react/package.json
  lib/core/package.json
  yarn.lock
Labels: dependencies

#9587 Fix CSF in MDX recipe
  addons/docs/docs/recipes.md
Labels: documentation, patch

#9097 Typescript: Export IStory in `@storybook/angular`
  app/angular/src/client/index.ts
Labels: bug, patch, typescript

#9530 Fix broken link to repo in empty knobs panel
  addons/knobs/src/components/Panel.tsx
Labels: addon: knobs, bug, patch

#9603 FIX some dependencies & ts problems on next
  examples/cra-kitchen-sink/.storybook/main.js
  examples/cra-react15/.storybook/main.js
  examples/cra-ts-kitchen-sink/src/stories/Button.tsx
  lib/components/src/tabs/tabs.tsx
  yarn.lock
Labels: maintenance

#9601 Added missing = in angular guide
  docs/src/pages/guides/guide-angular/index.md
Labels: documentation, patch

#9597 Remove duplicate text
  docs/src/pages/guides/guide-react/index.md
Labels: documentation, patch

#9609 Addon-docs: Revert breaking source indentation fix
  lib/components/src/blocks/Source.tsx
Labels: addon: docs, block: source, bug

#9535 Enabling HMR logging in browser console
  lib/core/src/server/preview/preview-preset.js
Labels: babel / webpack, feature request

#9613 Update Custom Body Documentation
  docs/src/pages/configurations/add-custom-body/index.md
Labels: documentation, patch

#9616 fix(addon-storyshots): Remove excess slashes from jest transform warning
  addons/storyshots/storyshots-core/src/Stories2SnapsConverter.ts
Labels: addon: storyshots, bug, patch

#9617 Improve Typescript Configuration documentation page
  docs/src/pages/configurations/typescript-config/index.md
Labels: documentation, patch

#9612 Publish: Remove docs to reduce package size
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/events/package.json
  addons/graphql/package.json
  addons/info/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/notes/package.json
  addons/options/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  lib/cli/package.json
Labels: maintenance, patch

#9620 Merge pull request #9620 from richardhuf84/next
  addons/knobs/README.md
Labels: documentation, patch

#9633 MIGRATE ember to new "import { hbs } from 'ember-cli-htmlbars'"
  .gitignore
  addons/docs/ember/README.md
  addons/knobs/README.md
  app/ember/package.json
  app/ember/src/server/framework-preset-babel-ember.ts
  docs/src/pages/guides/guide-ember/index.md
  examples/ember-cli/.eslintrc.js
  examples/ember-cli/.storybook/preview.js
  examples/ember-cli/config/optional-features.json
  examples/ember-cli/package.json
  examples/ember-cli/stories/addon-a11y.stories.js
  examples/ember-cli/stories/addon-actions.stories.js
  examples/ember-cli/stories/addon-backgrounds.stories.js
  examples/ember-cli/stories/addon-centered.stories.js
  examples/ember-cli/stories/addon-knobs.stories.js
  examples/ember-cli/stories/addon-links.stories.js
  examples/ember-cli/stories/addon-notes.stories.js
  examples/ember-cli/stories/index.stories.js
  examples/ember-cli/stories/welcome-banner.stories.js
  lib/cli/generators/EMBER/template-csf/stories/0-Welcome.stories.js
  lib/cli/generators/EMBER/template-csf/stories/1-Button.stories.js
  lib/cli/test/fixtures/ember-cli/package.json
  yarn.lock
Labels: app: ember, maintenance

#9638 Clarify and expand on addon-docs manual config
  addons/docs/README.md
Labels: addon: docs, documentation, patch

#9552 Core: Document main.js config
  addons/docs/README.md
  addons/docs/angular/README.md
  addons/docs/ember/README.md
  addons/docs/react/README.md
  addons/docs/vue/README.md
  docs/gatsby-config.js
  docs/src/pages/addons/using-addons/index.md
  docs/src/pages/addons/writing-addons/index.md
  docs/src/pages/basics/writing-stories/index.md
  docs/src/pages/configurations/custom-webpack-config/index.md
  docs/src/pages/configurations/overview/index.md
  docs/src/pages/configurations/typescript-config/index.md
  docs/src/pages/presets/introduction/index.md
  docs/src/pages/presets/writing-presets/index.md
Labels: documentation

#9643 fix(addon-docs): ColorPalette style
  lib/components/src/blocks/ColorPalette.tsx
Labels: addon: docs, bug, patch

#9585 Netlify for examples again
  netlify.toml
  now.json
  package.json
Labels: maintenance

#9647 Add Paddings addon to addon gallery
  docs/src/pages/addons/addon-gallery/index.md
Labels: documentation, patch

#9652 Merge pull request #9652 from storybookjs/fix/9462-sass-loading
  app/react/package.json
  yarn.lock
Labels: bug, cra, patch

#9090 UI: Add `viewMode` parameter to control story nav UI
  addons/docs/docs/recipes.md
  examples/cra-react15/.storybook/main.js
  examples/official-storybook/stories/addon-docs/subcomponents.stories.js
  examples/official-storybook/stories/addon-docs/ts-button.stories.tsx
  lib/api/src/modules/stories.ts
  lib/ui/src/components/sidebar/SidebarStories.test.ts
  lib/ui/src/components/sidebar/SidebarStories.tsx
Labels: addon: docs, feature request

#9547 Source-loader: Overhaul to remove decorators, support user-configurable source
  addons/docs/src/blocks/Source.tsx
  addons/storysource/package.json
  addons/storysource/src/StoryPanel.js
  addons/storysource/src/StoryPanel.tsx
  addons/storysource/src/events.ts
  addons/storysource/src/index.ts
  addons/storysource/src/manager.tsx
  addons/storysource/src/preview.js
  addons/storysource/src/preview.ts
  addons/storysource/tsconfig.json
  examples/html-kitchen-sink/stories/__snapshots__/source-loader.stories.storyshot
  examples/html-kitchen-sink/stories/button.html
  examples/html-kitchen-sink/stories/source-loader.stories.js
  lib/components/package.json
  lib/components/src/index.ts
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
  lib/components/src/typings.d.ts
  lib/source-loader/package.json
  lib/source-loader/preview.js
  lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.snap
  lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.test.js.snap
  lib/source-loader/src/abstract-syntax-tree/default-options.js
  lib/source-loader/src/abstract-syntax-tree/generate-helpers.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.csf.test.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.js
  lib/source-loader/src/abstract-syntax-tree/inject-decorator.test.js
  lib/source-loader/src/abstract-syntax-tree/parse-helpers.js
  lib/source-loader/src/abstract-syntax-tree/parsers/index.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-flow.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-js.js
  lib/source-loader/src/abstract-syntax-tree/parsers/parser-ts.js
  lib/source-loader/src/abstract-syntax-tree/traverse-helpers.js
  lib/source-loader/src/build.js
  lib/source-loader/src/client/events.js
  lib/source-loader/src/client/preview.js
  lib/source-loader/src/dependencies-lookup/readAsObject.js
  lib/source-loader/src/index.ts
  lib/source-loader/src/server/build.js
  lib/source-loader/src/server/dependencies-lookup/getRidOfUselessFilePrefixes.js
  lib/source-loader/src/server/dependencies-lookup/readAsObject.js
  lib/source-loader/src/types.ts
  lib/source-loader/tsconfig.json
  yarn.lock
Labels: addon: storysource, maintenance, source-loader

#9661 documentation fix #9498 - theming + addon-docs incompatible
  MIGRATION.md
  addons/docs/docs/theming.md
  docs/src/pages/configurations/theming/index.md
Labels: addon: docs, bug, patch, theming

#9665 Merge pull request #9665 from storybookjs/fix/styled-form-fields
  lib/components/src/form/field/field.tsx
Labels: bug, patch, ui

#9383 Merge pull request #9383 from baker-travis/knob-groups-overflow-not-scrolling
  lib/components/src/bar/bar.tsx
Labels: bug, ui

#9557 fix(webcomponents): make types play nicely with lit-element
  app/web-components/src/client/preview/types.ts
Labels: app: web-components, bug, patch, typescript

#9627 @storybook/addon-cssresources - Hide Code
  addons/cssresources/README.md
  addons/cssresources/src/CssResource.ts
  addons/cssresources/src/css-resource-panel.test.js
  addons/cssresources/src/css-resource-panel.tsx
Labels: addon: cssresources, feature request

#9655 Fix default value for web components prop table docs
  addons/docs/src/frameworks/web-components/config.js
Labels: addon: docs, app: web-components, block: props, bug

#9095 configure tabs: title, visibility, order and disable
  examples/official-storybook/manager.js
  examples/official-storybook/stories/addon-docs/docs-only.stories.mdx
  examples/official-storybook/stories/addon-docs/markdown.stories.mdx
  examples/official-storybook/stories/addon-graphql.stories.js
  examples/official-storybook/stories/addon-notes.stories.js
  lib/ui/src/components/preview/preview.js
  lib/ui/src/containers/preview.js
Labels: feature request, in progress, ui

#9687 check if docsOnly is set to hide the addon panels
  lib/ui/src/components/layout/desktop.js
Labels: addon: docs, bug

#9324 Fix jsconfig support with CRA
  app/react/src/server/__snapshots__/cra-config.test.ts.snap
  app/react/src/server/cra-config.test.ts
  app/react/src/server/cra-config.ts
Labels: app: react, babel / webpack, bug, compatibility with other tools, cra, patch
