Repository storybookjs/storybook, pull requests merged in 2020-08, with the labels that each got.

#11749 Updates for the workflows section docs
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/interaction-testing.md
  docs/workflows/package-composition.md
  docs/workflows/publish-storybook.md
  docs/workflows/snapshot-testing.md
  docs/workflows/stories-for-multiple-components.md
  docs/workflows/storybook-composition.md
  docs/workflows/template-component-with-controls-optimized.mp4
  docs/workflows/testing-with-storybook.md
  docs/workflows/unit-testing.md
Labels: documentation

#11752 Addon-docs: Add Story.story for CSF stories with MDX docs
  addons/docs/docs/recipes.md
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/mdx/__testfixtures__/csf-imports.mdx
  addons/docs/src/mdx/__testfixtures__/csf-imports.output.snapshot
  addons/docs/src/mdx/mdx-compiler-plugin.js
  addons/docs/src/mdx/mdx-compiler-plugin.test.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.mdx
Labels: addon: docs, feature request, mdx

#11750 Update Docs docs to replace existing <Props /> references
  addons/docs/docs/docspage.md
  addons/docs/docs/props-tables.md
Labels: documentation

#10525 Addon-Docs: Fix Ember extractArgTypes
  addons/docs/src/frameworks/ember/jsondoc.js
Labels: addon: docs, app: ember, args, bug, in progress

#10512 Addon-Docs: Fix Ember extractArgTypes default value
  addons/docs/src/frameworks/ember/jsondoc.js
  examples/ember-cli/app/components/welcome-banner.js
Labels: addon: docs, app: ember, block: props, bug, in progress

#11760 Addon-docs: Fix Ember args
  addons/docs/src/frameworks/ember/jsondoc.js
  examples/ember-cli/stories/welcome-banner.stories.js
Labels: app: ember, args, bug

#11761 Addon-docs: Add `docs.description` parameter
  MIGRATION.md
  addons/docs/src/blocks/Description.tsx
  addons/docs/src/blocks/DocsContainer.tsx
  addons/docs/src/blocks/DocsStory.tsx
  examples/official-storybook/stories/demo/button.stories.js
Labels: addon: docs, block: other, feature request

#11730 Addon-a11y: Fix inherited parameters
  addons/a11y/src/a11yRunner.ts
Labels: addon: a11y, bug

#11745 Composition: Fix missing version property in autoref
  lib/core/src/server/manager/manager-config.js
Labels: bug, composition

#11759 Addon-docs: Make vue-docgen optional peer deps
  addons/docs/package.json
  app/vue/package.json
  yarn.lock
Labels: addon: docs, app: vue, dependencies

#11765 Source-loader: Fix storiesOf missing `__STORY__` variable
  lib/source-loader/src/build.js
Labels: bug, source-loader

#11767 Core: Fix handling of initial hashes
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.js
Labels: bug, core

#11766 Core: Add `STORY_SPECIFIED` event for initial sidebar selection/URL
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.js
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
  lib/core-events/src/index.ts
Labels: bug, core

#11642 Addon-knobs: Fix search params with URI encoding
  examples/official-storybook/stories/addon-knobs/with-knobs.stories.js
  lib/ui/package.json
  lib/ui/src/components/preview/utils/stringifyQueryParams.tsx
Labels: addon: knobs, bug

#11770 Addon-docs: Fix link font size to inherit
  examples/official-storybook/stories/addon-docs/docs-only.stories.mdx
  lib/components/src/blocks/Description.stories.tsx
  lib/components/src/typography/DocumentFormatting.tsx
  lib/components/src/typography/DocumentFormattingSample.md
Labels: addon: docs, bug, theming

#11771 Core: Fix link to deprecated configure
  lib/core/src/client/preview/loadCsf.ts
Labels: core, documentation

#11781 CSF: Support mixed `.x` and deprecated `.story.x` parameters
  examples/angular-cli/src/stories/__snapshots__/core.stories.storyshot
  examples/riot-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/core.stories.storyshot
  examples/vue-kitchen-sink/src/stories/__snapshots__/custom-decorators.stories.storyshot
  lib/core/src/client/preview/loadCsf.test.ts
  lib/core/src/client/preview/loadCsf.ts
Labels: bug, core, source-loader

#11757 Update TOC format, setup with currently ready pages
  docs/toc.js
Labels: documentation

#11797 UPGRADE telejson
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  yarn.lock
Labels: dependencies:update, performance issue

#11795 do not use zoom on docs content
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/tools/zoom.tsx
Labels: addon: docs, bug

#11805 Addon-controls: Fix ArgsTable bugs and styling
  lib/components/src/blocks/ArgsTable/ArgJsDoc.tsx
  lib/components/src/blocks/ArgsTable/ArgRow.stories.tsx
  lib/components/src/blocks/ArgsTable/ArgRow.tsx
  lib/components/src/blocks/ArgsTable/ArgValue.tsx
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
  lib/components/src/blocks/ArgsTable/NoControlsWarning.tsx
  lib/components/src/controls/Boolean.tsx
Labels: addon: controls, bug, ui

#11768 Addon-docs: Prettier, collapsible values in ArgsTable
  lib/components/src/blocks/ArgsTable/ArgRow.stories.tsx
  lib/components/src/blocks/ArgsTable/ArgRow.tsx
  lib/components/src/blocks/ArgsTable/ArgValue.tsx
  lib/components/src/blocks/ArgsTable/ArgsTable.stories.tsx
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
Labels: addon: docs, block: props, feature request

#11814 Addon-docs: Add inline rendering support for HTML
  MIGRATION.md
  addons/docs/README.md
  addons/docs/src/frameworks/html/config.tsx
Labels: addon: docs, app: html, bug

#11806 Updates for the writing docs section
  docs/toc.js
  docs/writing-docs/build-documentation.md
  docs/writing-docs/doc-blocks.md
  docs/writing-docs/docs-page.md
  docs/writing-docs/introduction.md
  docs/writing-docs/mdx.md
  docs/writing-docs/storybook-docs-build.png
Labels: documentation

#11803 Workflows documentation update for Storybook start/build with --docs flag
  docs/workflows/publish-storybook.md
Labels: documentation

#11778 Updates for the writing stories section
  docs/writing-stories/args.md
  docs/writing-stories/decorators.md
  docs/writing-stories/introduction.md
  docs/writing-stories/naming-components-and-hierarchy.md
  docs/writing-stories/parameters.md
Labels: documentation

#11777 Get started section updates
  docs/get-started/browse-stories.md
  docs/get-started/conclusion.md
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
Labels: documentation

#11776 updates for the configure section
  docs/configure/environment-variables.md
  docs/configure/features-and-behavior.md
  docs/configure/integration.md
  docs/configure/overview.md
  docs/configure/sidebar-and-urls.md
  docs/configure/story-rendering.md
  docs/configure/storybook-addons.md
  docs/configure/theming.md
  docs/configure/user-interface.md
  docs/toc.js
Labels: documentation

#11779 Updates for the essentials section
  docs/essentials/actions.md
  docs/essentials/backgrounds.md
  docs/essentials/controls.md
  docs/essentials/introduction.md
  docs/essentials/toolbars-and-globals.md
  docs/essentials/viewports.md
Labels: documentation

#11751 Updates for the api section docs
  docs/api/addons-api.md
  docs/api/addons.md
  docs/api/argtypes.md
  docs/api/cli-options.md
  docs/api/csf.md
  docs/api/mdx-documentation-only.png
  docs/api/mdx-page.png
  docs/api/mdx-simple.png
  docs/api/mdx.md
  docs/api/new-frameworks.md
  docs/api/presets.md
  docs/api/stories.md
  docs/api/writing-presets.md
  docs/toc.js
Labels: documentation

#11817 docs: fix code snippet
  docs/src/pages/configurations/options-parameter/index.md
Labels: documentation

#11811 CLI: CSF typings for react stories
  app/react/src/client/index.ts
  app/react/src/client/preview/types-6-0.ts
  app/react/types-6-0.d.ts
  examples/official-storybook/stories/demo/typed-button.stories.tsx
  lib/addons/src/types.ts
  lib/cli/src/frameworks/react/ts/Button.stories.tsx
  lib/cli/src/frameworks/react/ts/Button.tsx
  lib/cli/src/frameworks/react/ts/Header.stories.tsx
  lib/cli/src/frameworks/react/ts/Page.stories.tsx
  lib/cli/src/generators/baseGenerator.ts
  scripts/run-e2e-config.ts
Labels: bug, cli, cra, typescript

#11824 Upgrade telejson to 5.0.1
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  yarn.lock
Labels: dependencies, performance issue

#11807 6.0 docs snippets initial setup
  docs/api/argtypes.md
  docs/api/cli-options.md
  docs/api/csf.md
  docs/api/new-frameworks.md
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/guides/guide-react-native/index.md
  docs/snippets/angular/button-story.js.mdx
  docs/snippets/react/button-story.js.mdx
  docs/snippets/react/button-story.md.mdx
  docs/snippets/react/button-story.ts.mdx
  docs/workflows/snapshot-testing.md
Labels: documentation

#11829 Core: Fix undefined serialization
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  yarn.lock
Labels: bug

#11825 CLI: Add CSF types for Angular
  app/angular/src/client/index.ts
  app/angular/src/client/preview/types-6-0.ts
  app/angular/types-6-0.d.ts
  examples/angular-cli/src/stories/addon-controls.stories.ts
  examples/angular-cli/src/stories/core.stories.ts
  lib/cli/src/frameworks/angular/Button.stories.ts
  lib/cli/src/frameworks/angular/Header.stories.ts
  lib/cli/src/frameworks/angular/Page.stories.ts
  scripts/run-e2e-config.ts
Labels: app: angular, cli, feature request, typescript

#11792 Storyshots: Don't ship typescript files in dist
  scripts/prepare.js
Labels: addon: storyshots, bug, typescript

#10218 Changes import of options/optionsKnob
  addons/knobs/README.md
Labels: addon: knobs, documentation

#11850 Update 6.0 docs sidebar titles
  docs/api/addons-api.md
  docs/api/addons.md
  docs/api/argtypes.md
  docs/api/cli-options.md
  docs/api/csf.md
  docs/api/frameworks-feature-support.md
  docs/api/mdx.md
  docs/api/new-frameworks.md
  docs/configure/integration.md
  docs/configure/overview.md
  docs/configure/sidebar-and-urls.md
  docs/configure/story-rendering.md
  docs/configure/storybook-addons.md
  docs/configure/theming.md
  docs/essentials/introduction.md
  docs/essentials/toolbars-and-globals.md
  docs/get-started/browse-stories.md
  docs/get-started/conclusion.md
  docs/get-started/install.md
  docs/get-started/introduction.md
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/testing/automated-visual-testing/index.md
  docs/testing/interaction-testing/index.md
  docs/testing/manual-testing/index.md
  docs/testing/react-ui-testing/index.md
  docs/testing/static/image-diff-1.png
  docs/testing/static/image-diff-2.png
  docs/testing/static/image-diff-3.png
  docs/testing/static/login_form.png
  docs/testing/static/specs-addon.png
  docs/testing/static/storybook-iframe-screenshot.png
  docs/testing/static/storybook-screenshot.png
  docs/testing/static/storyshots-diff-view.png
  docs/testing/static/storyshots-first-run.png
  docs/testing/structural-testing/index.md
  docs/toc.js
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/interaction-testing.md
  docs/workflows/package-composition.md
  docs/workflows/publish-storybook.md
  docs/workflows/snapshot-testing.md
  docs/workflows/stories-for-multiple-components.md
  docs/workflows/storybook-composition.md
  docs/workflows/unit-testing.md
  docs/workflows/visual-testing.md
  docs/writing-docs/build-documentation.md
  docs/writing-docs/doc-blocks.md
  docs/writing-docs/docs-page.md
  docs/writing-docs/introduction.md
  docs/writing-docs/mdx.md
  docs/writing-stories/args.md
  docs/writing-stories/decorators.md
  docs/writing-stories/introduction.md
  docs/writing-stories/naming-components-and-hierarchy.md
  docs/writing-stories/parameters.md
Labels: documentation

#11841 Chore: add snippets for the essentials docs section for 6.0
  docs/essentials/actions.md
  docs/essentials/backgrounds.md
  docs/essentials/controls.md
  docs/essentials/introduction.md
  docs/essentials/toolbars-and-globals.md
  docs/essentials/viewports.md
  docs/snippets/common/addon-consume-globaltype.js.mdx
  docs/snippets/common/button-story-action-event-handle.js.mdx
  docs/snippets/common/button-story-configure-backgrounds.js.mdx
  docs/snippets/common/button-story-controls-color-picker.js.mdx
  docs/snippets/common/button-story-controls-red-input.js.mdx
  docs/snippets/common/button-story-disable-backgrounds.js.mdx
  docs/snippets/common/button-story-hide-nocontrols-warning.js.mdx
  docs/snippets/common/button-story-matching-argtypes.js.mdx
  docs/snippets/common/button-story-onclick-action-argtype.js.mdx
  docs/snippets/common/button-story-override-background-color.js.mdx
  docs/snippets/common/gizmo-story-controls-customization.js.mdx
  docs/snippets/common/my-component-story-use-globaltype-backwards-compat.js.mdx
  docs/snippets/common/my-component-story-use-globaltype.js.mdx
  docs/snippets/common/storybook-main-disable-addon.js.mdx
  docs/snippets/common/storybook-preview-change-viewports.js.mdx
  docs/snippets/common/storybook-preview-configure-background-colors.js.mdx
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
  docs/snippets/common/storybook-preview-expanded-controls.js.mdx
  docs/snippets/common/storybook-preview-granular-viewports.js.mdx
  docs/snippets/common/storybook-preview-locales-globaltype.js.mdx
  docs/snippets/common/storybook-preview-merge-viewports.js.mdx
  docs/snippets/common/storybook-preview-use-global-type.js.mdx
  docs/snippets/common/storybook-preview-viewport-add-devices.js.mdx
  docs/snippets/common/storybook-preview-viewport-use-new-devices.js.mdx
  docs/snippets/common/widget-story-controls-enum.js.mdx
  docs/snippets/react/my-component-story-configure-viewports.js.mdx
  docs/snippets/react/table-story-fully-customize-controls.js.mdx
Labels: documentation

#11842 Chore add snippets for configure section for 6.0
  docs/configure/environment-variables.md
  docs/configure/features-and-behavior.md
  docs/configure/integration.md
  docs/configure/overview.md
  docs/configure/sidebar-and-urls.md
  docs/configure/story-rendering.md
  docs/configure/theming.md
  docs/snippets/angular/storybook-angular-inline-css-loader.js.mdx
  docs/snippets/common/component-story-dynamic-title.js.mdx
  docs/snippets/common/foo-bar-baz-story.js.mdx
  docs/snippets/common/my-component-story-import-json.js.mdx
  docs/snippets/common/my-component-story-import-static-asset.js.mdx
  docs/snippets/common/other-foo-bar-story.js.mdx
  docs/snippets/common/storybook-config-layout.js.mdx
  docs/snippets/common/storybook-install-theme-packages.sh.mdx
  docs/snippets/common/storybook-main-add-sass-config.js.mdx
  docs/snippets/common/storybook-main-add-ts-config.js.mdx
  docs/snippets/common/storybook-main-default-setup.js.mdx
  docs/snippets/common/storybook-main-js-md-files.js.mdx
  docs/snippets/common/storybook-main-simplified-config.js.mdx
  docs/snippets/common/storybook-main-using-existing-config.js.mdx
  docs/snippets/common/storybook-manager-custom-theme.js.mdx
  docs/snippets/common/storybook-manager-dark-theme.js.mdx
  docs/snippets/common/storybook-manager-disable-roots.js.mdx
  docs/snippets/common/storybook-preview-body-example.html.mdx
  docs/snippets/common/storybook-preview-body-font-size.html.mdx
  docs/snippets/common/storybook-preview-custom-canvas.js.mdx
  docs/snippets/common/storybook-preview-custom-code-renderer.js.mdx
  docs/snippets/common/storybook-preview-docs-dark-theme.js.mdx
  docs/snippets/common/storybook-preview-extended-theme-variables.js.mdx
  docs/snippets/common/storybook-preview-head-example.html.mdx
  docs/snippets/common/storybook-read-environment-variables.js.mdx
  docs/snippets/common/storybook-run-webpack-config.sh.mdx
  docs/snippets/common/storybook-serve-static-assets-script-multifolder.json.mdx
  docs/snippets/common/storybook-serve-static-assets-script.json.mdx
  docs/snippets/common/storybook-set-environment-variables.sh.mdx
  docs/snippets/common/storybook-theme-example-variables.ts.mdx
  docs/snippets/common/storybook-theming-styled-import.js.mdx
  docs/snippets/common/your-theme.js.mdx
  docs/snippets/react/component-story-static-asset-cdn.js.mdx
  docs/snippets/react/component-story-static-asset-with-import.js.mdx
  docs/snippets/react/component-story-static-asset-without-import.js.mdx
  docs/snippets/react/component-styled-variables-object-notation.js.mdx
  docs/snippets/react/component-styled-variables-template-literals.js.mdx
Labels: documentation

#11826 Chore: adds snippets for get started section for 6.0
  docs/get-started/install.md
  docs/get-started/setup.md
  docs/snippets/angular/button-story-with-args.ts.mdx
  docs/snippets/angular/button-story.ts.mdx
  docs/snippets/common/storybook-execute.sh.mdx
  docs/snippets/common/storybook-install.sh.mdx
  docs/snippets/common/your-component.js.mdx
  docs/snippets/common/your-component.ts.mdx
  docs/snippets/react/button-story-with-args.js.mdx
  docs/snippets/react/button-story-with-args.ts.mdx
  docs/snippets/react/button-story.ts.mdx
  docs/snippets/react/storybook-preview-with-styled-components-decorator.js.mdx
Labels: documentation

#11854 Feature snippets for frameworks
  docs/essentials/auto-generated-controls/angular.mdx
  docs/essentials/auto-generated-controls/ember.mdx
  docs/essentials/auto-generated-controls/fallback.mdx
  docs/essentials/auto-generated-controls/react.mdx
  docs/essentials/auto-generated-controls/vue.mdx
  docs/essentials/auto-generated-controls/web-components.mdx
  docs/essentials/controls-feature-react.mdx
  docs/essentials/controls.md
Labels: documentation

#11847 New docs: Fix addon-docs framework support
  docs/frameworks.js
Labels: documentation

#11836 Chore writing docs section code snippets
  docs/snippets/angular/button-component-with-proptypes.ts.mdx
  docs/snippets/common/badge-story.mdx.mdx
  docs/snippets/common/button-group-story-subcomponents.js.mdx
  docs/snippets/common/button-group-story-subcomponents.ts.mdx
  docs/snippets/common/button-story-disable-docspage-component.js.mdx
  docs/snippets/common/button-story-disable-docspage-component.ts.mdx
  docs/snippets/common/button-story-disable-docspage.js.mdx
  docs/snippets/common/button-story-remix-docspage.js.mdx
  docs/snippets/common/button-story-remix-docspage.ts.mdx
  docs/snippets/common/checkbox-story-csf.js.mdx
  docs/snippets/common/checkbox-story.mdx.mdx
  docs/snippets/common/component-story-csf-argstable-customization.js.mdx
  docs/snippets/common/component-story-csf-description.js.mdx
  docs/snippets/common/component-story-custom-source.js.mdx
  docs/snippets/common/component-story-mdx-argstable-propsblock.mdx.mdx
  docs/snippets/common/component-story-mdx-argtypes.mdx.mdx
  docs/snippets/common/component-story-mdx-decorators-params.mdx.mdx
  docs/snippets/common/component-story-mdx-dedent.mdx.mdx
  docs/snippets/common/component-story-mdx-description.mdx.mdx
  docs/snippets/common/component-story-mdx-embed.mdx.mdx
  docs/snippets/common/component-story-mdx-reference-storyid.mdx.mdx
  docs/snippets/common/component-story-mdx-story-by-name.mdx.mdx
  docs/snippets/common/mdx-canvas-multiple-stories.mdx.mdx
  docs/snippets/common/my-component-story.js.mdx
  docs/snippets/common/my-component-with-story-content.mdx.mdx
  docs/snippets/common/storybook-build-documentation.json.mdx
  docs/snippets/common/storybook-preview-disable-docspage.js.mdx
  docs/snippets/common/storybook-preview-documentation.json.mdx
  docs/snippets/common/storybook-preview-prepareforinline.js.mdx
  docs/snippets/react/button-component-with-proptypes.js.mdx
  docs/snippets/react/button-component-with-proptypes.ts.mdx
  docs/writing-docs/build-documentation.md
  docs/writing-docs/doc-blocks.md
  docs/writing-docs/docs-page.md
  docs/writing-docs/mdx.md
Labels: documentation

#11856 Update README for 6.0
  README.md
Labels: documentation

#11855 Docs: random fixes
  docs/get-started/introduction.md
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/snippets/react/button-story.md.mdx
  docs/snippets/react/button-story.mdx.mdx
  docs/snippets/react/your-component.js.mdx
  docs/snippets/react/your-component.ts.mdx
  docs/writing-stories/introduction.md
Labels: documentation

#11866 Docs tweaks
  addons/actions/README.md
  addons/backgrounds/README.md
  addons/controls/README.md
  addons/toolbars/README.md
  addons/viewport/README.md
  docs/api/presets.md
  docs/configure/integration.md
  docs/essentials/auto-generated-controls/react.mdx
  docs/get-started/install.md
  docs/snippets/common/mdx-canvas-multiple-stories.mdx.mdx
  docs/snippets/common/my-component-with-story-content.mdx.mdx
  docs/toc.js
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/interaction-testing.md
  docs/workflows/package-composition.md
  docs/workflows/snapshot-testing.md
  docs/workflows/stories-for-multiple-components.md
  docs/workflows/unit-testing.md
  docs/writing-docs/doc-blocks.md
Labels: documentation

#11869 Reorder essentials
  docs/essentials/introduction.md
  docs/toc.js
  docs/workflows/stories-for-multiple-components.md
Labels: documentation

#11871 more docs editing and polish
  docs/api/addons.md
  docs/api/argtypes.md
  docs/api/csf.md
  docs/configure/integration.md
  docs/essentials/actions.md
  docs/essentials/addon-actions-screenshot.png
  docs/essentials/backgrounds.md
  docs/essentials/controls.md
  docs/essentials/toolbars-and-globals.md
  docs/get-started/browse-stories.md
  docs/get-started/install.md
  docs/get-started/introduction.md
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/workflows/package-composition.md
  docs/writing-docs/introduction.md
  docs/writing-stories/introduction.md
Labels: documentation

#11874 Documentation: Break out integration.md into different pages & add emojis to sidebar links
  docs/configure/babel.md
  docs/configure/images-and-assets.md
  docs/configure/integration.md
  docs/configure/styling-and-css.md
  docs/configure/typescript.md
  docs/configure/webpack.md
  docs/toc.js
Labels: documentation

#11879 Remove angular dummy snippet
  docs/get-started/whats-a-story.md
  docs/snippets/angular/button-story.js.mdx
Labels: documentation

#11880 Fix malformed markdown in 6.0 documentation that was causing bugs
  docs/get-started/setup.md
  docs/writing-stories/introduction.md
Labels: documentation

#11876 Document preview entries in presets
  MIGRATION.md
  docs/api/writing-presets.md
Labels: documentation

#11878 Chore: Updates for the code snippets
  docs/configure/environment-variables.md
  docs/configure/images-and-assets.md
  docs/configure/theming.md
  docs/configure/webpack.md
  docs/get-started/install.md
  docs/snippets/common/badge-story.mdx.mdx
  docs/snippets/common/checkbox-story.mdx.mdx
  docs/snippets/common/component-story-mdx-argstable-propsblock.mdx.mdx
  docs/snippets/common/component-story-mdx-argtypes.mdx.mdx
  docs/snippets/common/component-story-mdx-decorators-params.mdx.mdx
  docs/snippets/common/component-story-mdx-dedent.mdx.mdx
  docs/snippets/common/component-story-mdx-description.mdx.mdx
  docs/snippets/common/component-story-mdx-reference-storyid.mdx.mdx
  docs/snippets/common/component-story-mdx-story-by-name.mdx.mdx
  docs/snippets/common/mdx-canvas-multiple-stories.mdx.mdx
  docs/snippets/common/my-component-with-story-content.mdx.mdx
  docs/snippets/common/storybook-build-documentation.json.mdx
  docs/snippets/common/storybook-execute.sh.mdx
  docs/snippets/common/storybook-install-theme-packages.sh.mdx
  docs/snippets/common/storybook-install.sh.mdx
  docs/snippets/common/storybook-preview-documentation.json.mdx
  docs/snippets/common/storybook-run-webpack-config.sh.mdx
  docs/snippets/common/storybook-serve-static-assets-script-multifolder.json.mdx
  docs/snippets/common/storybook-serve-static-assets-script.json.mdx
  docs/snippets/common/storybook-set-environment-variables.sh.mdx
  docs/writing-docs/build-documentation.md
Labels: documentation

#11867 Add install snippets
  docs/get-started/install.md
  docs/get-started/installation-problems/angular.mdx
  docs/get-started/installation-problems/ember.mdx
  docs/get-started/installation-problems/html.mdx
  docs/get-started/installation-problems/marko.mdx
  docs/get-started/installation-problems/mithril.mdx
  docs/get-started/installation-problems/preact.mdx
  docs/get-started/installation-problems/rax.mdx
  docs/get-started/installation-problems/react.mdx
  docs/get-started/installation-problems/riot.mdx
  docs/get-started/installation-problems/svelte.mdx
  docs/get-started/installation-problems/vue.mdx
  docs/get-started/installation-problems/web-components.mdx
Labels: documentation

#11872 Chore add workflows snippets for 6.0 docs
  docs/snippets/common/component-cypress-test.js.mdx
  docs/snippets/common/isomorphic-fetch-mock.js.mdx
  docs/snippets/common/storybook-main-disable-refs.js.mdx
  docs/snippets/common/storybook-main-ref-local.js.mdx
  docs/snippets/common/storybook-main-ref-remote.js.mdx
  docs/snippets/common/storybook-main-with-mock-decorator.js.mdx
  docs/snippets/common/storybook-preview-with-mock-decorator.js.mdx
  docs/snippets/common/storybook-storyshots-config.js.mdx
  docs/snippets/react/app-story-with-mock.js.mdx
  docs/snippets/react/button-test.js.mdx
  docs/snippets/react/component-story-with-query.js.mdx
  docs/snippets/react/list-story-template.js.mdx
  docs/snippets/react/list-story-template.ts.mdx
  docs/snippets/react/list-story-unchecked.js.mdx
  docs/snippets/react/list-story-unchecked.ts.mdx
  docs/snippets/react/list-story-with-subcomponents.js.mdx
  docs/snippets/react/list-story-with-subcomponents.ts.mdx
  docs/snippets/react/list-story-with-unchecked-children.js.mdx
  docs/snippets/react/page-story-with-args-composition.js.mdx
  docs/snippets/react/page-story-with-args-composition.ts.mdx
  docs/snippets/react/simple-page-implementation.js.mdx
  docs/snippets/react/simple-page-implementation.ts.mdx
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/interaction-testing.md
  docs/workflows/package-composition.md
  docs/workflows/snapshot-testing.md
  docs/workflows/stories-for-multiple-components.md
  docs/workflows/storybook-composition.md
  docs/workflows/unit-testing.md
Labels: documentation

#11882 adds faq to the documentation
  docs/toc.js
  docs/workflows/faq.md
Labels: documentation

#11885 Core: Improve support for main.ts/preview.ts files
  lib/core/package.json
  yarn.lock
Labels: bug, core, patch

#11889 Addon-docs: Fix ArgsTable regression
  MIGRATION.md
  addons/docs/src/blocks/ArgsTable.tsx
  addons/docs/src/blocks/DocsPage.tsx
  examples/official-storybook/stories/addon-docs/addon-docs.stories.mdx
  examples/official-storybook/stories/notes/notes.mdx
Labels: addon: docs, block: argstable, bug, patch

#11891 documentation: fixed storybook-preview-configure-globaltypes typo
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
Labels: documentation

#11895 Codemod: Fix csf-hoist-story-annotations for variable default exports
  lib/codemod/src/transforms/__testfixtures__/csf-hoist-story-annotations/.output.snapshot
  lib/codemod/src/transforms/__testfixtures__/csf-hoist-story-annotations/variable.input.js
  lib/codemod/src/transforms/__testfixtures__/csf-hoist-story-annotations/variable.output.snapshot
  lib/codemod/src/transforms/csf-hoist-story-annotations.js
Labels: bug, cli, patch

#11897 [addon-controls] Delete useless wording "annotation" in README
  addons/controls/README.md
Labels: documentation

#11758 Add documentation on using context to avoid mocking container dependencies
  docs/snippets/react/mock-context-container-global.js.mdx
  docs/snippets/react/mock-context-container-provider.js.mdx
  docs/snippets/react/mock-context-container.js.mdx
  docs/snippets/react/mock-context-create.js.mdx
  docs/snippets/react/mock-context-in-use.js.mdx
  docs/workflows/build-pages-with-storybook.md
Labels: documentation, patch

#11900 Chore: fixes to the documentation links and snippets
  docs/api/presets.md
  docs/api/writing-presets.md
  docs/get-started/setup.md
  docs/snippets/common/storybook-main-simplified-config.js.mdx
  docs/writing-docs/docs-page.md
  docs/writing-docs/mdx.md
Labels: documentation, patch

#11901 Docs typo: replace `:` with `.`
  docs/api/new-frameworks.md
Labels: documentation, patch

#11903 Docs: Fix more typos and capitalization
  docs/api/new-frameworks.md
Labels: documentation, patch

#11910 Addon-essentials: Fix missing toolbars addon
  addons/essentials/README.md
  addons/essentials/package.json
  addons/essentials/src/index.ts
  examples/cra-ts-essentials/.storybook/preview.js
Labels: addon: essentials, bug, patch

#11911 [DOCS] Update links
  CHANGELOG.md
  MIGRATION.md
  README.md
  addons/a11y/README.md
  addons/controls/README.md
  addons/docs/README.md
  addons/docs/docs/docspage.md
  addons/docs/docs/mdx.md
  addons/docs/docs/multiframework.md
  addons/docs/docs/props-tables.md
  addons/docs/docs/recipes.md
  addons/docs/docs/theming.md
  addons/storyshots/storyshots-core/README.md
  addons/storysource/README.md
  app/angular/README.md
  app/aurelia/README.md
  app/ember/README.md
  app/html/README.md
  app/marionette/README.md
  app/marko/README.md
  app/mithril/README.md
  app/preact/README.md
  app/rax/README.md
  app/react/README.md
  app/riot/README.md
  app/server/README.md
  app/svelte/README.md
  app/vue/README.md
  app/web-components/README.md
  docs/get-started/install.md
  docs/workflows/unit-testing.md
Labels: documentation, help wanted, patch

#11920 Source-loader: Fix `.add` detection
  __mocks__/inject-parameters.ts.csf.txt
  lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.snap
  lib/source-loader/src/abstract-syntax-tree/parse-helpers.js
Labels: bug, patch, source-loader

#11921 fix(withA11y docs): Fix function call code example
  MIGRATION.md
Labels: documentation

#11925 Fix install command for addon-controls
  addons/controls/README.md
Labels: documentation, patch

#11932 Update widget-story-controls-enum.js.mdx
  docs/snippets/common/widget-story-controls-enum.js.mdx
Labels: documentation, patch

#11948 Remove deprecated addParameters from docs snippet
  addons/docs/react/README.md
Labels: documentation

#11943 Fix link to testing-with-storybook
  docs/get-started/whats-a-story.md
Labels: documentation

#11940 Fixed link for ArgTypes in controls.md
  docs/essentials/controls.md
Labels: documentation

#11949 CLI: Fix welcome links on Introduction MDX
  docs/api/presets.md
  lib/cli/src/frameworks/common/Introduction.stories.mdx
Labels: bug, cli, patch

#11953 Chore: updates for the presets docs
  docs/api/presets.md
  docs/snippets/common/storybook-main-preset-config.js.mdx
  docs/snippets/common/storybook-preset-configuration.js.mdx
Labels: documentation, patch

#11957 Examples page
  docs/get-started/conclusion.md
  docs/get-started/examples.md
  docs/toc.js
Labels: documentation, patch

#11959 Chore: add story layout page
  docs/configure/story-layout.md
  docs/snippets/common/storybook-preview-layout.param.js.mdx
  docs/toc.js
Labels: documentation, patch

#11952 docs(cli): fix typo in docs
  docs/api/cli-options.md
Labels: documentation

#11955 docs(parameters): fix example file name
  docs/writing-stories/parameters.md
Labels: documentation

#11956 docs: add correct links in Addon Controls readme
  addons/controls/README.md
Labels: documentation

#11951 Fix links to "Viewport" and "Toolbars & globals" pages
  docs/essentials/introduction.md
Labels: documentation

#11973 CLI: Fix RN link
  lib/cli/src/initiate.ts
Labels: app: react-native, bug, cli, patch

#11978 Docs: Fix broken link on configure > overview page
  docs/configure/overview.md
Labels: documentation, patch

#11985 Fix url linking to argTypes documentation
  docs/essentials/controls.md
Labels: documentation, patch

#11987 Addon-docs: Fix blocks type export
  addons/docs/blocks.d.ts
Labels: addon: docs, bug, typescript

#11993 CLI: Fix upgrade error
  lib/cli/src/upgrade.ts
Labels: bug, cli, patch

#11995 Change semi-colons in args object to commas
  addons/controls/README.md
Labels: documentation

#11939 fix: bump jest-specific-snapshot to v4
  addons/docs/package.json
  addons/storyshots/storyshots-core/package.json
  lib/codemod/package.json
  lib/postinstall/package.json
  yarn.lock
Labels: dependencies, tracked

#12015 Build: Remove documentation scripts and fix README
  CONTRIBUTING.md
  package.json
  scripts/bootstrap.js
Labels: maintenance

#12011 fix(docs): Props > ArgsTable & add props in docs
  docs/snippets/common/button-story-remix-docspage.js.mdx
  docs/snippets/common/button-story-remix-docspage.ts.mdx
Labels: documentation

#12012 Addon-docs: Fix extractArgTypes for unknown component
  addons/docs/src/frameworks/angular/compodoc.ts
  addons/docs/src/frameworks/common/enhanceArgTypes.ts
  addons/docs/src/frameworks/web-components/config.js
  addons/docs/src/frameworks/web-components/custom-elements.ts
  examples/angular-cli/.storybook/preview.ts
  examples/angular-cli/src/stories/addon-controls.stories.ts
  examples/angular-cli/src/stories/addon-docs.stories.mdx
  examples/angular-cli/src/stories/doc-button/doc-button.component.ts
  examples/angular-cli/src/stories/doc-button/doc-button.stories.ts
  examples/angular-cli/src/stories/issues/12009-unknown-component.stories.ts
  examples/angular-cli/src/stories/issues/__snapshots__/12009-unknown-component.stories.storyshot
  examples/web-components-kitchen-sink/stories/issues/11831-unknown-component.stories.js
Labels: addon: docs, args, bug

#11934 UI: update upgrade command in about section
  lib/ui/src/settings/about.tsx
Labels: maintenance

#12017 Update overview.md
  docs/configure/overview.md
Labels: documentation

#12033 ArgsTable: Error when subcomponents is an array
  addons/docs/src/blocks/ArgsTable.tsx
  examples/official-storybook/stories/addon-docs/array-subcomponents.stories.js
Labels: addon: docs, block: argstable, maintenance

#12043 Doc: Update toolbars-and-globals.md
  docs/essentials/toolbars-and-globals.md
Labels: documentation

#12044 Addon-docs: Fix CSF names importing in MDX
  addons/docs/src/mdx/__testfixtures__/csf-imports.mdx
  addons/docs/src/mdx/__testfixtures__/csf-imports.output.snapshot
  addons/docs/src/mdx/mdx-compiler-plugin.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.mdx
Labels: addon: docs, bug, mdx

#12048 Addon-controls: Fix argType inference priority
  examples/cra-ts-essentials/src/stories/Button.stories.tsx
  examples/cra-ts-essentials/src/stories/Button.tsx
  examples/cra-ts-essentials/src/stories/button.css
  lib/client-api/src/ensureArgTypes.ts
  lib/client-api/src/inferArgTypes.ts
  lib/client-api/src/story_store.ts
Labels: addon: controls, addon: docs, bug

#12045 [Docs] Added a missing import statement
  docs/snippets/react/button-story-default-export-with-component.ts.mdx
Labels: documentation

#12057 Addon-docs: Fix main check for absolute config dirs
  addons/controls/src/preset/ensureDocsBeforeControls.ts
Labels: addon: docs, bug

#12060 [docs] Update incorrect import in example in mdx.md
  addons/docs/docs/mdx.md
Labels: documentation

#12053 [docs] Update wording in writing-stories/args
  docs/writing-stories/args.md
Labels: documentation, patch

#12062 Fixing my own grammar mistakes on the examples page
  docs/get-started/examples.md
Labels: documentation, patch

#12068 Updated docs/theming.md to have correct links to Storybook Docs
  docs/configure/theming.md
Labels: documentation

#12002 As we are using JSX syntax. we should use .tsx [documentation] [patch]
  docs/snippets/react/button-story.tsx.mdx
Labels: documentation, patch

#12066 Fix docs for panelPosition / initialActive options
  docs/configure/features-and-behavior.md
Labels: documentation

#12080 Docs - fix configure overview babel and webpack links
  docs/configure/overview.md
Labels: documentation

#11999 Chore: updates to the writing docs section
  docs/api/argtypes.md
  docs/snippets/common/component-story-mdx-argstable-block.mdx.mdx
  docs/writing-docs/doc-blocks.md
  docs/writing-docs/docs-page.md
Labels: documentation, patch

#11818 ArgsTable: Fix styles to allow long text to wrap
  lib/components/src/blocks/ArgsTable/ArgValue.tsx
Labels: addon: docs, block: argstable, bug

#12063 Add Story type to example
  docs/snippets/react/button-story-with-args.ts.mdx
Labels: documentation

#12072 React: Fix CSF component typing
  app/react/src/client/preview/types-6-0.ts
Labels: app: react, bug, csf, typescript

#12081 Angular: Make CLI templates compatible with TS strict mode
  lib/cli/src/frameworks/angular/button.component.ts
  lib/cli/src/frameworks/angular/header.component.ts
  lib/cli/src/frameworks/angular/page.component.ts
  scripts/run-e2e-config.ts
Labels: app: angular, bug, cli, typescript

#12083 Fixed typo: changed yarn install to yarn add
  docs/configure/theming.md
Labels: documentation

#12088 fix: remove redundant 'also'
  docs/configure/sidebar-and-urls.md
Labels: documentation, patch

#12102 Update button-test.js.mdx
  docs/snippets/react/button-test.js.mdx
Labels: documentation, patch

#12087 Core: Add frameworkPath to options to support custom frameworks
  docs/api/new-frameworks.md
  lib/core/src/server/preview/iframe-webpack.config.js
  lib/core/src/server/preview/virtualModuleStory.template.js
Labels: core, feature request

#12003 Addon-A11y: Fix manual run & timeline
  addons/a11y/src/a11yRunner.ts
  addons/a11y/src/components/A11YPanel.tsx
  addons/a11y/src/components/A11yContext.tsx
  examples/official-storybook/stories/addon-a11y/typography.stories.js
Labels: addon: a11y, bug

#12104 Fix broken link in cli readme
  lib/cli/README.md
Labels: documentation, patch

#12107 Addon-docs: Fix source code for Template.bind({}) in MDX
  addons/docs/src/mdx/__testfixtures__/story-args.output.snapshot
  addons/docs/src/mdx/mdx-compiler-plugin.js
Labels: addon: docs, block: source, bug, mdx

#12115 Fix typo in introduction.md
  docs/writing-stories/introduction.md
Labels: documentation, patch

#12099 Source-loader: Fix default exports of type TSAsExpression
  examples/react-ts/main.ts
  examples/react-ts/src/button.stories.tsx
  lib/source-loader/src/abstract-syntax-tree/traverse-helpers.js
Labels: bug, source-loader, typescript

#12118 Updating and optimizing circleCI Config
  .circleci/config.yml
Labels: maintenance

#12127 SyntaxError Fixed
  docs/snippets/common/storybook-merged-argtypes.js.mdx
Labels: documentation

#12130 fix: duplicate line in snippet
  docs/snippets/react/button-story-with-args.ts.mdx
Labels: documentation

#12136 Fix link to the root configuration
  docs/writing-stories/naming-components-and-hierarchy.md
Labels: documentation

#12137 Chore: Fixes the doc block link to point at the correct api page
  docs/writing-docs/doc-blocks.md
Labels: documentation, patch

#12085 Composition: Verify refs in node
  lib/api/src/modules/refs.ts
  lib/api/src/tests/refs.test.js
  lib/core/src/server/manager/manager-config.js
Labels: bug, composition

#12151 Fix typo
  docs/writing-stories/introduction.md
Labels: documentation

#12149 docs: add correct react native link
  README.md
Labels: documentation

#12148 Addon-viewport: Add preset to fix windows import
  addons/viewport/preset.js
  addons/viewport/register.js
  addons/viewport/src/preset/index.ts
Labels: addon: essentials, addon: viewport, bug

#12154 Addon-docs: Fix MDX IDs from CSF imports
  addons/docs/src/mdx/__testfixtures__/csf-imports.output.snapshot
  addons/docs/src/mdx/mdx-compiler-plugin.js
Labels: addon: docs, bug, mdx

#12110 React: Simplify component type for CSF typing
  app/react/src/client/preview/types-6-0.ts
Labels: app: react, maintenance, typescript

#12140 Update link in warning hint text
  lib/api/src/modules/stories.ts
Labels: documentation

#12164 Addon-docs: Fix inline rendering for DOM nodes in HTML
  addons/docs/src/frameworks/html/config.tsx
Labels: addon: docs, app: html, bug

#12158 Addon-docs: Fix ArgsTable union type handling in Vue/TS
  addons/docs/src/lib/docgen/extractDocgenProps.ts
Labels: addon: docs, app: vue, block: argstable, bug

#12165 Addon-docs: Fix Vue ArgsTable sanitizing of item.type.elements to item.type.value
  addons/docs/src/lib/docgen/extractDocgenProps.ts
Labels: addon: docs, app: vue, block: argstable, bug

#12207 Build: Remove outdated CLI tests
  .github/workflows/tests-cli.yml
  lib/cli/package.json
  lib/cli/test/berryfy_package_json.js
  lib/cli/test/run_tests_yarn_2.sh
  lib/cli/test/test_latest_cra.sh
Labels: cli, maintenance

#12203 Correct globs in documentation
  docs/snippets/common/storybook-main-default-setup.js.mdx
Labels: documentation

#12211 Addon-essentials: Log info on config override
  addons/essentials/src/index.ts
Labels: addon: essentials, bug

#12216 Fix typo
  MIGRATION.md
Labels: documentation

#12227 Chore: add image to Story layout page
  docs/configure/layout-params-story-centered.png
  docs/configure/story-layout.md
Labels: documentation, patch

#12229 Mithril: Add Mithril v2.0.0 to peer dependencies
  app/mithril/package.json
Labels: app: mithril, dependencies

#12230 Addon-controls: Fix controls from args
  addons/docs/src/frameworks/common/enhanceArgTypes.test.ts
  addons/docs/src/frameworks/common/enhanceArgTypes.ts
  addons/docs/src/frameworks/react/react-argtypes.stories.tsx
  examples/official-storybook/stories/addon-docs/imported.stories.tsx
  examples/official-storybook/stories/addon-docs/props.stories.mdx
  lib/cli/versions.json
  lib/client-api/src/index.ts
  lib/client-api/src/inferControls.ts
  lib/client-api/src/story_store.ts
Labels: addon: controls, args, bug

#12171 UI: Fix `disable` parameter to hide addon panel
  MIGRATION.md
  lib/api/src/modules/addons.ts
  lib/api/src/tests/addons.test.js
  lib/ui/src/containers/panel.stories.tsx
Labels: api: addons, bug

#12233 UI: Fix eject and copy URLs for composition
  lib/ui/src/components/preview/tools/copy.tsx
  lib/ui/src/components/preview/tools/eject.tsx
Labels: bug, ui

#12160 Update examples.md
  docs/get-started/examples.md
Labels: documentation, help wanted

#12257 Fixed a docs typo
  docs/api/cli-options.md
Labels: documentation

#12244 Fix broken link to jest addon docs
  docs/workflows/snapshot-testing.md
Labels: documentation
