Repository storybookjs/storybook, pull requests merged in 2021-07, with the labels that each got.

#15461 CLI: Fix NPM typo
  lib/cli/src/js-package-manager/NPMProxy.ts
Labels: bug, cli, patch

#15428 Addon-docs: Cache DocsContext on window to prevent duplication
  addons/docs/src/blocks/DocsContext.ts
Labels: addon: docs, compatibility with other tools, maintenance

#15372 Core: Fix double rebuilds by removing aggregateTimeout
  lib/builder-webpack4/src/preview/iframe-webpack.config.ts
  lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  lib/manager-webpack4/src/manager-webpack.config.ts
  lib/manager-webpack5/src/manager-webpack.config.ts
Labels: babel / webpack, bug, patch

#15410 Angular: Fix circular reference not being handled in moduleMetadata
  app/angular/package.json
  app/angular/src/client/preview/angular-beta/AbstractRenderer.ts
  app/angular/src/client/preview/angular-beta/RendererService.test.ts
  app/angular/src/client/preview/angular-beta/RendererService.ts
  yarn.lock
Labels: app: angular, bug, patch

#15459 UI: Fix sidebar toggle in fullscreen mode
  lib/api/src/modules/layout.ts
  lib/ui/src/components/preview/tools/menu.tsx
Labels: bug, ui

#15466 Addon-a11y: Reverse help and description labels in accordion
  addons/a11y/src/components/Report/Info.tsx
  addons/a11y/src/components/Report/Item.tsx
Labels: accessibility, addon: a11y, maintenance

#15468 Fix misc broken links
  addons/links/README.md
  addons/links/src/react/components/RoutedLink.tsx
  lib/ui/README.md
Labels: documentation, patch

#15482 Migration: Add webpack@5 hoisting instructions
  MIGRATION.md
Labels: documentation, patch

#15480 Build: Update Yarn cache setup in GitHub Actions workflow
  .github/workflows/tests-unit.yml
Labels: maintenance

#15470 Chore: (Docs) Updates the loader docs
  docs/snippets/angular/loader-story.mdx.mdx
  docs/snippets/angular/loader-story.ts.mdx
  docs/snippets/common/storybook-preview-global-loader.js.mdx
  docs/snippets/react/loader-story.js.mdx
  docs/snippets/react/loader-story.mdx.mdx
  docs/snippets/svelte/loader-story.js.mdx
  docs/snippets/svelte/loader-story.mdx.mdx
  docs/snippets/svelte/storybook-preview-global-loader.js.mdx
  docs/snippets/vue/loader-story.3.js.mdx
  docs/snippets/vue/loader-story.mdx.mdx
  docs/writing-stories/loaders.md
Labels: documentation, patch

#15491 Addon-docs/Angular: Fix numeric args default value handling
  addons/docs/src/frameworks/angular/compodoc.ts
Labels: addon: docs, app: angular, block: argstable, bug, patch

#7848 Addon-docs: Add docs to standalone example
  examples/standalone-preview/package.json
  examples/standalone-preview/storybook.html
  examples/standalone-preview/storybook.ts
  package.json
  yarn.lock
Labels: addon: docs, maintenance, standalone

#15489 fix: shortcut for navigating to previous language in official-storybook example
  examples/official-storybook/preview.js
Labels: cleanup, other, tiny

#15496 Chore: (Docs) Minor adjustments to the theming docs
  docs/configure/theming.md
Labels: documentation, patch

#15497 Addon-a11y: Fix package.json README link
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/docs/package.json
  addons/essentials/package.json
  addons/jest/package.json
  addons/links/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/preact/package.json
  app/react/package.json
  app/server/package.json
  app/svelte/package.json
  app/vue/package.json
  app/vue3/package.json
  app/web-components/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/channels/package.json
  lib/cli-sb/package.json
  lib/cli-storybook/package.json
  lib/cli/package.json
  lib/client-api/package.json
  lib/client-logger/package.json
  lib/codemod/package.json
  lib/components/package.json
  lib/core-client/package.json
  lib/core-common/package.json
  lib/core-events/package.json
  lib/core-server/package.json
  lib/core/package.json
  lib/csf-tools/package.json
  lib/manager-webpack4/package.json
  lib/manager-webpack5/package.json
  lib/node-logger/package.json
  lib/postinstall/package.json
  lib/router/package.json
  lib/source-loader/package.json
  lib/theming/package.json
  lib/ui/package.json
Labels: documentation, patch

#15483 Webpack5: Quit process after finishing a static build
  app/angular/src/server/build.ts
  lib/builder-webpack5/src/index.ts
Labels: app: angular, bug, build-storybook

#15280 Angular: Make Ivy work by default in the angular-cli example
  app/angular/src/client/preview/angular-beta/RendererFactory.test.ts
  app/angular/src/client/preview/angular-beta/RendererService.test.ts
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/__snapshots__/welcome-angular.stories.storyshot
  examples/angular-cli/src/stories/__snapshots__/welcome-storybook.stories.storyshot
  examples/angular-cli/src/stories/addons/actions/__snapshots__/addon-actions.stories.storyshot
  examples/angular-cli/src/stories/addons/backgrounds/__snapshots__/addon-background.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/addon-docs.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/simple.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/iframe/__snapshots__/iframe.stories.storyshot
  examples/angular-cli/src/stories/addons/jest/__snapshots__/addon-jest.stories.storyshot
  examples/angular-cli/src/stories/addons/links/__snapshots__/addon-links.stories.storyshot
  examples/angular-cli/src/stories/basics/component-with-ng-content/__snapshots__/ng-content-about-parent.stories.storyshot
  examples/angular-cli/src/stories/basics/component-with-provider/__snapshots__/di.component.stories.storyshot
  examples/angular-cli/src/stories/basics/component-with-provider/di.component.ts
  examples/angular-cli/src/stories/basics/component-without-selector/__snapshots__/without-selector-ng-component-outlet.stories.storyshot
  examples/angular-cli/src/stories/basics/ng-module/__snapshots__/import-module-for-root.stories.storyshot
  examples/angular-cli/src/stories/basics/ng-module/__snapshots__/import-module.stories.storyshot
  examples/angular-cli/src/stories/core/decorators/componentWrapperDecorator/__snapshots__/decorators.stories.storyshot
  examples/angular-cli/src/stories/core/moduleMetadata/__snapshots__/in-export-default.stories.storyshot
  examples/angular-cli/src/stories/core/moduleMetadata/__snapshots__/in-stories.stories.storyshot
  examples/angular-cli/src/stories/core/moduleMetadata/__snapshots__/merge-default-and-story.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/all-parameters.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/layout.parameters.stories.storyshot
  examples/angular-cli/src/stories/core/styles/__snapshots__/story-styles.stories.storyshot
  examples/angular-cli/src/stories/legacy/__snapshots__/component-in-story.stories.storyshot
  examples/angular-cli/src/stories/legacy/__snapshots__/storiesOf.stories.storyshot
  examples/angular-cli/src/stories/others/issues/__snapshots__/12009-unknown-component.stories.storyshot
  yarn.lock
Labels: app: angular, maintenance

#15504 docs: fix typo in snippet storybook-preview-configure-globaltypes.js.mdx
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
Labels: documentation, patch

#15523 Build: Fix cache setup in GitHub Actions workflow
  .github/workflows/tests-unit.yml
Labels: maintenance

#15478 docs: add missing space
  docs/writing-docs/build-documentation.md
Labels: documentation, patch

#15527 Composition: Fix refs ordering
  examples/angular-cli/.storybook/main.js
  lib/api/src/modules/refs.ts
Labels: bug, composition, patch

#15501 Addon-docs/Angular: Add unique id to Angular stories
  addons/docs/package.json
  addons/docs/src/frameworks/angular/prepareForInline.ts
  examples/angular-cli/src/stories/addons/docs/__snapshots__/duplicate.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/duplicate.stories.mdx
  yarn.lock
Labels: addon: docs, app: angular, bug

#15526 Essentials: Add outline addon to monorepo
  addons/essentials/package.json
  addons/essentials/src/index.ts
  addons/outline/README.md
  addons/outline/package.json
  addons/outline/preset.js
  addons/outline/register.js
  addons/outline/src/OutlineSelector.tsx
  addons/outline/src/constants.ts
  addons/outline/src/helpers.ts
  addons/outline/src/outlineCSS.ts
  addons/outline/src/preset/addDecorator.tsx
  addons/outline/src/register.tsx
  addons/outline/src/typings.d.ts
  addons/outline/src/withOutline.ts
  addons/outline/tsconfig.json
  examples/official-storybook/stories/addon-outline.stories.js
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-prod
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod
  lib/core-server/src/__snapshots__/vue-3-cli_manager-dev
  lib/core-server/src/__snapshots__/vue-3-cli_manager-prod
  lib/core-server/src/__snapshots__/vue-3-cli_preview-dev
  lib/core-server/src/__snapshots__/vue-3-cli_preview-prod
  nx.json
  package.json
  workspace.json
  yarn.lock
Labels: addon: essentials, maintenance

#15535 chore: Fix a typo
  docs/api/cli-options.md
Labels: documentation, patch

#15545 Essentials: Add measure addon to monorepo
  addons/essentials/package.json
  addons/measure/README.md
  addons/measure/package.json
  addons/measure/preset.js
  addons/measure/register.js
  addons/measure/src/Tool.tsx
  addons/measure/src/box-model/canvas.ts
  addons/measure/src/box-model/labels.ts
  addons/measure/src/box-model/visualizer.ts
  addons/measure/src/constants.ts
  addons/measure/src/index.ts
  addons/measure/src/preset/addDecorator.tsx
  addons/measure/src/register.tsx
  addons/measure/src/typings.d.ts
  addons/measure/src/util.ts
  addons/measure/src/withMeasure.ts
  addons/measure/tsconfig.json
  addons/outline/src/index.ts
  examples/angular-cli/src/stories/__snapshots__/welcome-storybook.stories.storyshot
  examples/angular-cli/src/stories/core/styles/__snapshots__/story-styles.stories.storyshot
  examples/official-storybook/components/addon-measure/ShadowRoot.js
  examples/official-storybook/components/addon-measure/Visualization.js
  examples/official-storybook/stories/addon-measure/BoxModel.stories.js
  examples/official-storybook/stories/addon-measure/Grid.stories.js
  examples/official-storybook/stories/addon-measure/ShadowRoot.stories.js
  examples/official-storybook/stories/addon-measure/SmallNode.stories.js
  examples/official-storybook/stories/addon-measure/StackingLabels.stories.js
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-prod
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod
  lib/core-server/src/__snapshots__/vue-3-cli_manager-dev
  lib/core-server/src/__snapshots__/vue-3-cli_manager-prod
  lib/core-server/src/__snapshots__/vue-3-cli_preview-dev
  lib/core-server/src/__snapshots__/vue-3-cli_preview-prod
  nx.json
  package.json
  workspace.json
  yarn.lock
Labels: addon: essentials, maintenance

#15337 Web-components: Dynamic source snippets
  addons/docs/src/frameworks/web-components/config.js
  addons/docs/src/frameworks/web-components/config.ts
  addons/docs/src/frameworks/web-components/prepareForInline.ts
  addons/docs/src/frameworks/web-components/sourceDecorator.test.ts
  addons/docs/src/frameworks/web-components/sourceDecorator.ts
  docs/frameworks.js
  examples/web-components-kitchen-sink/src/components/sb-button.stories.ts
  examples/web-components-kitchen-sink/src/components/sb-button.ts
  examples/web-components-kitchen-sink/src/stories/addons/docs/dynamic-source.stories.mdx
  examples/web-components-kitchen-sink/yarn.lock
  jest.config.js
Labels: addon: docs, app: web-components, block: source, feature request

#15533 Official-storybook: Add example of embedding story object in MDX
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.js
  examples/official-storybook/stories/addon-docs/csf-with-mdx-docs.stories.mdx
Labels: csf3, maintenance

#15540 docs: update the command to update the snapshot
  docs/contribute/code.md
Labels: documentation, patch

#15449 UI: Fix toggle button for custom theming
  lib/components/src/controls/Boolean.tsx
  lib/ui/src/components/sidebar/Search.tsx
  lib/ui/src/components/sidebar/Tree.tsx
Labels: bug, ui

#15550 Adding information on Angular app creation
  docs/get-started/install.md
Labels: documentation, patch

#15529 Document webpack instance in presets
  docs/addons/writing-presets.md
Labels: documentation, patch

#15546 Examples: Add no-manager-cache to all examples
  examples/angular-cli/package.json
  examples/cra-kitchen-sink/package.json
  examples/cra-react15/package.json
  examples/cra-ts-essentials/package.json
  examples/cra-ts-kitchen-sink/package.json
  examples/ember-cli/package.json
  examples/html-kitchen-sink/package.json
  examples/official-storybook/package.json
  examples/preact-kitchen-sink/package.json
  examples/react-ts-webpack4/package.json
  examples/react-ts/package.json
  examples/svelte-kitchen-sink/package.json
  examples/vue-3-cli/package.json
  examples/vue-cli/package.json
  examples/vue-kitchen-sink/package.json
  examples/web-components-kitchen-sink/package.json
Labels: maintenance

#12155 Add example codesnippet for using ArgsTable with stories
  docs/snippets/common/component-story-mdx-argstable-block-for-component.mdx.mdx
  docs/snippets/common/component-story-mdx-argstable-block-for-story.mdx.mdx
  docs/writing-docs/doc-blocks.md
Labels: documentation, help wanted, in progress, patch

#15556 Build: Fix `publish` step on CircleCI
  .circleci/config.yml
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/argtypes.snapshot
  addons/docs/src/frameworks/angular/compodoc.ts
  scripts/run-e2e.ts
  scripts/verdaccio.yaml
Labels: maintenance

#15549 Controls: Fix color matching behavior for non-string types
  lib/client-api/src/inferControls.test.ts
  lib/client-api/src/inferControls.ts
Labels: addon: controls, bug

#15557 Update MIGRATION.md to clarify default values inference
  MIGRATION.md
Labels: documentation, patch

#15558 CSF: Add CSF3 typings
  examples/react-ts/src/AccountForm.stories.tsx
  lib/addons/src/types.ts
Labels: csf3, feature request, typescript

#15561 [Documentation : Configure Addons] fix broken link to withRoundTrip example
  docs/addons/configure-addons.md
Labels: documentation, patch

#13711 Addon-backgrounds: Respect user's reduced motion settings
  addons/backgrounds/src/decorators/withBackground.ts
  addons/backgrounds/src/helpers/index.ts
Labels: addon: backgrounds, feature request

#15563 Angular: Fix actions argType auto generation
  addons/docs/src/frameworks/angular/compodoc.ts
Labels: app: angular, block: argstable, bug

#15568 Chore:(Docs) Fix toolbar docs with better examples and minor polish
  docs/essentials/toolbars-and-globals.md
  docs/snippets/angular/my-component-story-use-globaltype-backwards-compat.ts.mdx
  docs/snippets/angular/my-component-story-use-globaltype.mdx.mdx
  docs/snippets/angular/my-component-story-use-globaltype.ts.mdx
  docs/snippets/react/my-component-story-use-globaltype-backwards-compat.js.mdx
  docs/snippets/react/my-component-story-use-globaltype.js.mdx
  docs/snippets/react/my-component-story-use-globaltype.mdx.mdx
  docs/snippets/svelte/my-component-story-use-globaltype-backwards-compat.js.mdx
  docs/snippets/svelte/my-component-story-use-globaltype.js.mdx
  docs/snippets/svelte/my-component-story-use-globaltype.mdx.mdx
  docs/snippets/vue/my-component-story-use-globaltype-backwards-compat.js.mdx
  docs/snippets/vue/my-component-story-use-globaltype.js.mdx
  docs/snippets/vue/my-component-story-use-globaltype.mdx.mdx
  docs/snippets/web-components/my-component-story-use-globaltype-backwards-compat.js.mdx
  docs/snippets/web-components/my-component-story-use-globaltype.js.mdx
Labels: documentation, patch

#14439 Addon-docs: Add transparency support to color swatch
  lib/components/src/blocks/ColorPalette.tsx
Labels: addon: docs, block: other, feature request

#15528 Chore: (Docs) Polish the Workflows-Build pages documentation
  docs/snippets/angular/apollo-module.mock-apollo-module.ts.mdx
  docs/snippets/angular/document-screen-fetch.ts.mdx
  docs/snippets/angular/document-screen-with-graphql.ts.mdx
  docs/snippets/angular/documentscreen-story-msw-graphql-query.ts.mdx
  docs/snippets/angular/documentscreen-story-msw-rest-request.ts.mdx
  docs/snippets/react/component-story-with-query.js.mdx
  docs/snippets/react/document-screen-fetch.js.mdx
  docs/snippets/react/document-screen-with-graphql.js.mdx
  docs/snippets/react/documentscreen-story-msw-graphql-query.js.mdx
  docs/snippets/react/documentscreen-story-msw-rest-request.js.mdx
  docs/snippets/svelte/apollo-wrapper-component.with-mock-implementation.js.mdx
  docs/snippets/svelte/document-screen-fetch.js.mdx
  docs/snippets/svelte/document-screen-with-grapqhl.js.mdx
  docs/snippets/svelte/documentscreen-story-msw-graphql-query.js.mdx
  docs/snippets/svelte/documentscreen-story-msw-rest-request.js.mdx
  docs/snippets/vue/apollo-wrapper-component.with-mock-implementation-3.js.mdx
  docs/snippets/vue/document-screen-fetch.3.js.mdx
  docs/snippets/vue/document-screen-with-graphql.3.js.mdx
  docs/snippets/vue/documentscreen-story-msw-graphql-query.3.js.mdx
  docs/snippets/vue/documentscreen-story-msw-rest-request.3.js.mdx
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/faq.md
Labels: documentation, patch

#15592 Types: Export BaseStoryFn and BaseStoryObject
  lib/addons/src/types.ts
Labels: csf3, feature request, typescript

#15594 [Documentation] Add an unit test snipet for preact
  docs/snippets/preact/button-test.js.mdx
  docs/workflows/unit-testing.md
Labels: documentation, patch

#14309 Publish Storybook Docs: Raise warning about overwriting
  docs/workflows/publish-storybook.md
Labels: documentation, patch

#15559 UI: Allow keyboard shortcut to copy code in preview blocks
  lib/components/src/blocks/Preview.tsx
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: feature request, ui

#15581 Avoid slow regex.match call in renderJsx
  addons/docs/src/frameworks/react/jsxDecorator.tsx
Labels: app: react, block: source, maintenance, performance issue

#15607 Components: Lazy-load syntax highlighter
  lib/components/src/blocks/Preview.tsx
Labels: bug, components

#15615 Trailing comma handling for "-s" command line paramenter
  lib/core-server/src/cli/__tests__/utils.test.ts
  lib/core-server/src/cli/utils.ts
Labels: bug, cli, patch

#15620 docs(recipes): Fix grammatical error
  addons/docs/docs/recipes.md
Labels: documentation, patch

#15625 Controls: Adjust no addon-docs warning message
  addons/controls/src/preset/ensureDocsBeforeControls.ts
Labels: documentation, patch

#15621 Examples: Fix react-ts to be runnable standalone
  examples/react-ts/.babelrc
  examples/react-ts/main.ts
  examples/react-ts/package.json
  yarn.lock
Labels: maintenance, typescript

#11936 Vue: Add support for tsx
  addons/docs/src/frameworks/react/jsxDecorator.tsx
  app/vue/src/server/framework-preset-vue.ts
  lib/components/src/blocks/ColorPalette.tsx
Labels: app: vue, feature request, help wanted, in progress, typescript

#15613 Fix docs on granular viewports
  docs/snippets/common/storybook-preview-granular-viewports.js.mdx
Labels: documentation, patch

#14394 Controls: Clean up arg unboxing and switch statements
  lib/components/src/blocks/ArgsTable/ArgControl.tsx
  lib/components/src/controls/options/Options.tsx
Labels: addon: controls, maintenance, run e2e extended test suite

#15636 Chore: (Docs) Minor fixes to the list-story-reuse mdx snippet
  docs/snippets/angular/list-story-reuse-data.ts.mdx
Labels: documentation, patch

#15637 Chore: (Docs) Adds measure and outline main readme
  README.md
Labels: documentation, patch

#15649 Chore: (Docs) Adds documentation and changes for the measure and outline addon
  docs/essentials/addon-measure-optimized.mp4
  docs/essentials/addon-outline-optimized.mp4
  docs/essentials/measure-and-outline.md
  docs/frameworks.js
  docs/toc.js
Labels: documentation, patch

#15654 Controls: Don't set arg in validateOptions if it would be `undefined`
  lib/client-api/src/args.test.ts
  lib/client-api/src/args.ts
Labels: addon: controls, bug, patch

#15399 remove glob-base dependency
  lib/core-common/package.json
  lib/core-common/src/utils/__tests__/to-require-context.test.ts
  lib/core-common/src/utils/to-require-context.ts
  yarn.lock
Labels: dependencies, security

#15668 CSF3: Fix custom render function
  lib/client-api/src/index.ts
Labels: bug, csf3, patch

#15671 Allow Button to accept href attribute
  lib/components/src/Button/Button.stories.tsx
  lib/components/src/Button/Button.tsx
Labels: bug, components

#15676 Controls: Fix boolean toggle style to match underlying value
  lib/components/src/controls/Boolean.tsx
Labels: addon: controls, bug

#15674 CLI: Fix debug webpack output in static build
  lib/core-server/src/build-static.ts
Labels: bug, cli

#15616 Upgrade react-refresh plugin to fix fast refresh on Webpack5
  app/react/package.json
  docs/frameworks.js
  yarn.lock
Labels: app: react, dependencies, webpack5

#15687 Fix some transitive peer dependency warnings
  lib/core/package.json
  lib/csf-tools/package.json
  yarn.lock
Labels: dependencies

#15693 Update Wix Style Example Link
  docs/get-started/examples.md
Labels: documentation, patch

#15689 CLI: Fix Svelte CLI template markup
  lib/cli/src/frameworks/svelte/Header.svelte
  lib/cli/src/frameworks/svelte/Page.svelte
Labels: app: svelte, bug, cli

#15696 Chore: (Docs) Adjusts a11y image and location
  addons/a11y/README.md
  addons/a11y/docs/screenshot.png
Labels: documentation, patch

#15618 CSF3: Add startCase to auto-generated titles
  lib/core-client/src/preview/autoTitle.test.ts
  lib/core-client/src/preview/autoTitle.ts
Labels: csf3, feature request

#15697 CSF3: Add auto-titles from standard glob patterns
  lib/core-common/src/utils/__tests__/normalize-stories.test.ts
  lib/core-common/src/utils/normalize-stories.ts
Labels: csf3, feature request

#15698 Server: Upgrade to csf3
  app/server/README.md
  app/server/src/client/preview/index.ts
  app/server/src/lib/compiler/__testfixtures__/a11y.snapshot
  app/server/src/lib/compiler/__testfixtures__/actions.snapshot
  app/server/src/lib/compiler/__testfixtures__/backgrounds.snapshot
  app/server/src/lib/compiler/__testfixtures__/controls.snapshot
  app/server/src/lib/compiler/__testfixtures__/kitchen_sink.snapshot
  app/server/src/lib/compiler/__testfixtures__/links.snapshot
  app/server/src/lib/compiler/__testfixtures__/multiple_stories.snapshot
  app/server/src/lib/compiler/__testfixtures__/params.snapshot
  app/server/src/lib/compiler/__testfixtures__/params_override.snapshot
  app/server/src/lib/compiler/__testfixtures__/yaml.snapshot
  app/server/src/lib/compiler/__testfixtures__/yml.snapshot
  app/server/src/lib/compiler/index.ts
  app/server/src/lib/compiler/stringifier.ts
  app/server/src/lib/compiler/types.ts
  examples/server-kitchen-sink/.storybook/main.js
  examples/server-kitchen-sink/stories/addons/a11y.stories.json
  examples/server-kitchen-sink/stories/addons/actions.stories.json
  examples/server-kitchen-sink/stories/addons/backgrounds.stories.json
  examples/server-kitchen-sink/stories/addons/controls.stories.json
  examples/server-kitchen-sink/stories/demo.stories.json
  examples/server-kitchen-sink/stories/html_content/scripts.stories.json
  examples/server-kitchen-sink/stories/html_content/styles.stories.json
  examples/server-kitchen-sink/stories/kitchen_sink.stories.json
  examples/server-kitchen-sink/stories/params.stories.json
  examples/server-kitchen-sink/stories/welcome.stories.json
  examples/server-kitchen-sink/stories/yaml.stories.yaml
  examples/server-kitchen-sink/stories/yml.stories.yml
Labels: app: server, csf3

#15682 Build: Upgrade to Yarn 3
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-sources.cjs
  examples/web-components-kitchen-sink/.yarnrc.yml
  examples/web-components-kitchen-sink/package.json
  examples/web-components-kitchen-sink/yarn.lock
  lib/ui/package.json
  yarn.lock
Labels: maintenance

#15713 Chore: (Docs) Fixes the images within Storyshots addon to prevent 404
  addons/storysource/README.md
Labels: documentation, patch
