Repository storybookjs/storybook, pull requests merged in 2021-02, with the labels that each got.

#13777 UI: Fix copy to clipboard for insecure deployments
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, patch, ui

#13524 Documenting hand-install of essentials
  docs/essentials/introduction.md
Labels: documentation, patch

#13779 README: Add web-components and promote popular frameworks
  README.md
Labels: documentation, patch

#13659 Addon-docs: Fix Component description in Svelte
  addons/docs/src/frameworks/svelte/config.ts
  addons/docs/src/frameworks/svelte/extractComponentDescription.test.ts
  addons/docs/src/frameworks/svelte/extractComponentDescription.ts
  examples/svelte-kitchen-sink/src/stories/views/ControlShowcaseView.svelte
Labels: addon: docs, app: svelte, block: other, bug

#13752 CI: Upgrade cache GH Action & remove fallback caches
  .github/workflows/tests-unit.yml
Labels: maintenance

#13784 Core: Generate manager cache in smoke test, but don't use/clear any cache
  lib/core/src/server/dev-server.ts
Labels: cli, core, feature request

#13787 CI: Remove generic cache key from Circle CI
  .circleci/config.yml
Labels: maintenance

#13760 Svelte: Fixes component name in docgen-loader
  addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts
Labels: app: svelte, bug, patch

#13730 CLI: Add try/catch on readFileAsJson to improve error message
  lib/cli/src/helpers.ts
Labels: cli, feature request

#13749 Chore: Adds missing Angular snippets
  docs/configure/images-and-assets.md
  docs/essentials/controls.md
  docs/essentials/viewport.md
  docs/get-started/whats-a-story.md
  docs/snippets/angular/app-story-with-mock.ts.mdx
  docs/snippets/angular/button-group-story.ts.mdx
  docs/snippets/angular/button-story-component-args-primary.ts.mdx
  docs/snippets/angular/button-story-component-decorator.ts.mdx
  docs/snippets/angular/button-story-decorator.ts.mdx
  docs/snippets/angular/button-story-default-docs-code.ts.mdx
  docs/snippets/angular/button-story-default-export-with-component.ts.mdx
  docs/snippets/angular/button-story-rename-story.ts.mdx
  docs/snippets/angular/button-story-using-args.ts.mdx
  docs/snippets/angular/button-story-with-addon-example.ts.mdx
  docs/snippets/angular/button-story-with-args.ts.mdx
  docs/snippets/angular/button-story-with-blue-args.ts.mdx
  docs/snippets/angular/button-story-with-emojis.ts.mdx
  docs/snippets/angular/button-story-with-parameters.ts.mdx
  docs/snippets/angular/button-story.ts.mdx
  docs/snippets/angular/button-test.ts.mdx
  docs/snippets/angular/component-story-custom-args-complex.ts.mdx
  docs/snippets/angular/component-story-custom-args-icons.ts.mdx
  docs/snippets/angular/component-story-static-asset-cdn.ts.mdx
  docs/snippets/angular/component-story-static-asset-with-import.ts.mdx
  docs/snippets/angular/component-story-static-asset-without-import.ts.mdx
  docs/snippets/angular/list-story-expanded.ts.mdx
  docs/snippets/angular/list-story-reuse-data.ts.mdx
  docs/snippets/angular/list-story-starter.ts.mdx
  docs/snippets/angular/list-story-template.ts.mdx
  docs/snippets/angular/list-story-unchecked.ts.mdx
  docs/snippets/angular/list-story-with-subcomponents.ts.mdx
  docs/snippets/angular/my-component-story-configure-viewports.ts.mdx
  docs/snippets/angular/my-component-with-env-variables.ts.mdx
  docs/snippets/angular/page-story-with-args-composition.ts.mdx
  docs/snippets/angular/page-story.ts.mdx
  docs/snippets/angular/simple-page-implementation.ts.mdx
  docs/snippets/angular/table-story-fully-customize-controls.ts.mdx
  docs/snippets/angular/your-component.ts.mdx
  docs/workflows/build-pages-with-storybook.md
  docs/workflows/stories-for-multiple-components.md
  docs/workflows/unit-testing.md
  docs/writing-docs/doc-blocks.md
Labels: documentation, patch

#13786 Build: Do not recompile packages in publish step of the CI
  scripts/run-registry.ts
Labels: maintenance, run e2e extended test suite

#13715 Build: Generate version file with preval macro
  lib/api/package.json
  lib/api/scripts/generateVersion.js
  lib/api/src/typings.d.ts
  lib/api/src/version.ts
  yarn.lock
Labels: maintenance, run e2e extended test suite

#13714 Build: Exclude all test and story files from transpilation
  addons/a11y/tsconfig.json
  addons/actions/tsconfig.json
  addons/backgrounds/tsconfig.json
  addons/controls/tsconfig.json
  addons/cssresources/tsconfig.json
  addons/design-assets/tsconfig.json
  addons/docs/tsconfig.json
  addons/essentials/tsconfig.json
  addons/events/tsconfig.json
  addons/google-analytics/tsconfig.json
  addons/graphql/tsconfig.json
  addons/jest/tsconfig.json
  addons/knobs/tsconfig.json
  addons/links/tsconfig.json
  addons/queryparams/tsconfig.json
  addons/storysource/tsconfig.json
  addons/toolbars/tsconfig.json
  addons/viewport/tsconfig.json
  lib/addons/tsconfig.json
  lib/api/tsconfig.json
  lib/channel-postmessage/tsconfig.json
  lib/channel-websocket/tsconfig.json
  lib/channels/tsconfig.json
  lib/cli/tsconfig.json
  lib/client-api/tsconfig.json
  lib/client-logger/tsconfig.json
  lib/components/tsconfig.json
  lib/core-events/tsconfig.json
  lib/core/tsconfig.json
  lib/node-logger/tsconfig.json
  lib/router/tsconfig.json
  lib/source-loader/tsconfig.json
  lib/theming/tsconfig.json
  lib/ui/tsconfig.json
Labels: maintenance, run e2e extended test suite

#13809 Addon-docs: Add support for Vue 3
  addons/docs/package.json
  addons/docs/src/frameworks/html/config.tsx
  addons/docs/src/frameworks/vue3/config.ts
  addons/docs/src/frameworks/vue3/extractArgTypes.ts
  addons/docs/src/frameworks/vue3/prepareForInline.ts
  addons/docs/src/frameworks/vue3/preset.ts
  addons/docs/vue3/README.md
Labels: addon: docs, app: vue3, feature request, run e2e extended test suite

#13812 CLI: Fix opening localhost in browser by default
  lib/core/src/server/dev-server.ts
Labels: bug, cli, patch, run e2e extended test suite

#13819 Addon-docs/Vue3: Resolve vue3 package for addon-docs preset
  addons/docs/src/frameworks/vue3/preset.ts
Labels: addon: docs, app: vue3, bug

#13822 CLI: only kill other processes on fail
  scripts/build-package.js
Labels: maintenance

#13828 Addon-storyshots: Add support for Vue 3
  addons/storyshots/storyshots-core/README.md
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-core/src/frameworks/SupportedFramework.ts
  addons/storyshots/storyshots-core/src/frameworks/vue3/loader.ts
  addons/storyshots/storyshots-core/src/frameworks/vue3/renderTree.ts
  examples/vue-3-cli/jest.config.js
  examples/vue-3-cli/package.json
  examples/vue-3-cli/src/stories/Button.vue
  examples/vue-3-cli/src/stories/Header.stories.js
  examples/vue-3-cli/src/stories/Header.vue
  examples/vue-3-cli/src/stories/Page.stories.js
  examples/vue-3-cli/src/stories/Page.vue
  examples/vue-3-cli/src/stories/__snapshots__/Button.stories.storyshot
  examples/vue-3-cli/src/stories/__snapshots__/Header.stories.storyshot
  examples/vue-3-cli/src/stories/__snapshots__/Page.stories.storyshot
  examples/vue-3-cli/tsconfig.json
  examples/vue-3-cli/vuethreeshots.test.js
  jest.config.js
  yarn.lock
Labels: addon: storyshots, app: vue3, feature request, run e2e extended test suite

#13813 docs(vue-kitchen-sink): improve punctuation
  examples/vue-kitchen-sink/src/stories/addon-docs.stories.mdx
Labels: documentation

#13857 Upgrade to danger-js@main
  .github/workflows/label.yml
  .github/workflows/pull_request-dangerfile-js-pull.yml
Labels: maintenance

#13858 Angular: Fix deprecation for consistency
  app/angular/src/client/preview/angular-beta/StorybookModule.ts
Labels: cleanup

#13740 Addon-docs/Angular: Add dynamic source snippets
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/argtypes.snapshot
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/compodoc.snapshot
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/input.ts
  addons/docs/src/frameworks/angular/config.ts
  addons/docs/src/frameworks/angular/sourceDecorator.ts
  app/angular/package.json
  app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.test.ts
  app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts
  app/angular/src/client/preview/angular-beta/__testfixtures__/input.component.ts
  app/angular/src/renderer.ts
  examples/angular-cli/addon-jest.testresults.json
  examples/angular-cli/src/stories/__snapshots__/addon-controls.stories.storyshot
  examples/angular-cli/src/stories/addon-controls.stories.ts
  examples/angular-cli/src/stories/addons/docs/doc-button/doc-button.component.ts
  examples/angular-cli/src/stories/addons/docs/simple.stories.mdx
Labels: addon: docs, app: angular, block: source, feature request, run e2e extended test suite

#13846 Core: Add tests for the preset behavior of core
  app/react/src/server/options.ts
  lib/core/src/server/__snapshots__/manager-dev
  lib/core/src/server/__snapshots__/manager-prod
  lib/core/src/server/__snapshots__/preview-dev
  lib/core/src/server/__snapshots__/preview-prod
  lib/core/src/server/build-static.ts
  lib/core/src/server/core-presets.test.ts
  lib/core/src/server/dev-server.ts
  lib/core/src/server/manager/manager-config.ts
  lib/core/src/server/manager/virtualModuleRef.template.js
  lib/core/src/server/preview/iframe-webpack.config.ts
  package.json
Labels: core, maintenance, presets

#13842 Storyshots: Support main.js usage
  addons/storyshots/storyshots-core/preset.js
  addons/storyshots/storyshots-puppeteer/preset.js
  examples/react-ts/main.ts
Labels: addon: storyshots, bug, patch

#13853 add extra instructions for developing on windows
  CONTRIBUTING.md
Labels: documentation, patch

#13785 Svelte: Improved decorators
  addons/docs/src/frameworks/svelte/HOC.svelte
  addons/docs/src/frameworks/svelte/prepareForInline.ts
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-core/src/frameworks/svelte/renderTree.ts
  app/svelte/src/client/preview/PreviewRender.svelte
  app/svelte/src/client/preview/SlotDecorator.svelte
  app/svelte/src/client/preview/decorators.ts
  app/svelte/src/client/preview/index.ts
  app/svelte/src/client/preview/render.ts
  app/svelte/src/typings.d.ts
  docs/snippets/svelte/button-group-story.js.mdx
  docs/snippets/svelte/button-story-component-decorator.js.mdx
  docs/snippets/svelte/button-story-decorator.js.mdx
  docs/snippets/svelte/button-story.mdx.mdx
  docs/snippets/svelte/page-story.js.mdx
  docs/snippets/svelte/storybook-preview-global-decorator.js.mdx
  docs/snippets/svelte/your-component-with-decorator.js.mdx
  docs/snippets/svelte/your-component.js.mdx
  examples/svelte-kitchen-sink/src/components/Context.svelte
  examples/svelte-kitchen-sink/src/stories/BorderDecorator.svelte
  examples/svelte-kitchen-sink/src/stories/__snapshots__/decorators.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/decorators.stories.js
Labels: app: svelte, feature request

#13869 Addon-docs: Configure syntax highlighter language by story parameter
  addons/docs/src/blocks/Source.tsx
  addons/docs/src/frameworks/angular/config.ts
  docs/writing-docs/doc-blocks.md
Labels: addon: docs, app: angular, block: source, feature request

#13855 Vue 3: Fix decorators and add more examples
  app/vue3/src/client/preview/index.ts
  app/vue3/src/client/preview/types-6-0.ts
  app/vue3/src/client/preview/types.ts
  examples/vue-3-cli/.storybook/preview.js
  examples/vue-3-cli/.storybook/preview.ts
  examples/vue-3-cli/src/stories/DynamicHeading.stories.ts
  examples/vue-3-cli/src/stories/DynamicHeading.ts
Labels: app: vue3, bug

#13827 UI: Add a 'main' role to the Main component for a11y
  lib/ui/src/components/layout/container.tsx
Labels: accessibility, feature request, ui

#13871 Build: Rework `test` NPM script
  .circleci/config.yml
  .github/workflows/tests-unit.yml
  CONTRIBUTING.md
  lib/cli/src/versions.json
  package.json
  scripts/test.js
Labels: maintenance

#13872 Build: Move all the `yarn install` in the `build` CI job
  .circleci/config.yml
  scripts/run-registry.ts
Labels: maintenance

#13889 rename tests
  lib/core/src/server/__snapshots__/manager-dev
  lib/core/src/server/__snapshots__/manager-prod
  lib/core/src/server/__snapshots__/preview-dev
  lib/core/src/server/__snapshots__/preview-prod
  lib/core/src/server/core-presets.test.ts
Labels: cleanup

#13544 Addon-controls: Files control
  docs/essentials/controls.md
  examples/official-storybook/stories/addon-controls.stories.tsx
  lib/components/src/blocks/ArgsTable/ArgControl.tsx
  lib/components/src/controls/Files.tsx
  lib/components/src/controls/index.tsx
Labels: addon: controls, feature request

#13891 Angular: Bump to `11.2.0` and add missing peer dep in Storyshot addon
  addons/docs/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-core/src/frameworks/angular/renderTree.ts
  app/angular/package.json
  examples/angular-cli/package.json
  yarn.lock
Labels: addon: storyshots, app: angular, dependencies

#13895 UI: Fix theming for focused search bar
  lib/ui/src/components/sidebar/Search.tsx
Labels: bug, patch, theming, ui

#13894 Addon-docs/Vue3: Attach app context from preview to inline stories
  addons/docs/package.json
  addons/docs/src/frameworks/react/jsxDecorator.tsx
  addons/docs/src/frameworks/vue3/prepareForInline.ts
  examples/vue-3-cli/.storybook/preview.ts
  examples/vue-3-cli/src/stories/GlobalUsage.stories.js
  examples/vue-3-cli/src/stories/GlobalUsage.vue
Labels: app: vue3, bug

#13901 Canonical discord links
  CONTRIBUTING.md
  MIGRATION.md
  README.md
  SECURITY.md
  addons/controls/README.md
  examples/vue-3-cli/src/stories/Introduction.stories.mdx
  lib/cli/src/frameworks/common/Introduction.stories.mdx
Labels: documentation, patch

#13878 Misc: Clean TS config and bump `@storybook/preset-create-react-app`
  examples/angular-cli/tsconfig.json
  examples/cra-kitchen-sink/package.json
  examples/cra-react15/package.json
  examples/cra-ts-essentials/package.json
  examples/cra-ts-essentials/tsconfig.json
  examples/cra-ts-kitchen-sink/package.json
  examples/cra-ts-kitchen-sink/tsconfig.json
  lib/cli/src/versions.json
  tsconfig.json
  yarn.lock
Labels: maintenance

#13898 Addon-controls: Add include/exclude configuration options
  addons/docs/src/blocks/ArgsTable.tsx
  docs/essentials/controls.md
  docs/snippets/common/component-story-disable-controls-regex.js.mdx
  docs/snippets/common/component-story-disable-controls-regex.mdx.mdx
  examples/official-storybook/stories/addon-controls.stories.tsx
  lib/client-api/src/filterArgTypes.ts
  lib/client-api/src/index.ts
  lib/client-api/src/inferControls.ts
Labels: addon: controls, feature request

#13666 Add catalog metadata to the addons
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/controls/package.json
  addons/cssresources/package.json
  addons/design-assets/package.json
  addons/docs/package.json
  addons/events/package.json
  addons/google-analytics/package.json
  addons/graphql/package.json
  addons/jest/package.json
  addons/knobs/package.json
  addons/links/package.json
  addons/queryparams/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storysource/package.json
  addons/toolbars/package.json
  addons/viewport/package.json
Labels: maintenance

#13900 Svelte: Support TypeScript and preprocessors
  addons/docs/package.json
  addons/docs/src/frameworks/svelte/preset.ts
  addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts
  app/svelte/src/server/framework-preset-svelte.ts
  examples/svelte-kitchen-sink/.storybook/main.js
  examples/svelte-kitchen-sink/jest.config.js
  examples/svelte-kitchen-sink/package.json
  examples/svelte-kitchen-sink/src/components/Button.svelte
  examples/svelte-kitchen-sink/src/components/Button.test.js
  examples/svelte-kitchen-sink/src/stories/__snapshots__/addon-actions.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/__snapshots__/addon-docs.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/__snapshots__/argstable.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/__snapshots__/welcome.stories.storyshot
  examples/svelte-kitchen-sink/src/stories/addon-actions.stories.js
  examples/svelte-kitchen-sink/src/stories/addon-docs.stories.mdx
  examples/svelte-kitchen-sink/src/stories/views/ArgsTableView.svelte
  examples/svelte-kitchen-sink/svelte.config.js
  examples/svelte-kitchen-sink/tsconfig.json
  scripts/utils/jest-transform-svelte.js
  yarn.lock
Labels: app: svelte, feature request, typescript

#13675 Addon-controls: Infer color and date controls
  addons/controls/preset.js
  addons/controls/src/preset/addParameter.ts
  docs/essentials/addon-controls-args-variant-optimized.png
  docs/essentials/addon-controls-args-variant-string.png
  docs/essentials/controls.md
  docs/snippets/common/button-story-controls-color-picker.js.mdx
  docs/snippets/common/button-story-controls-color-picker.mdx.mdx
  docs/snippets/common/button-story-controls-primary-variant.js.mdx
  docs/snippets/common/button-story-controls-primary-variant.mdx.mdx
  docs/snippets/common/button-story-controls-radio-group.js.mdx
  docs/snippets/common/button-story-controls-radio-group.mdx.mdx
  docs/snippets/common/button-story-controls-red-input.js.mdx
  docs/snippets/common/storybook-addon-controls-custom-matchers.js.mdx
  examples/official-storybook/stories/addon-controls.stories.tsx
  lib/client-api/src/inferControls.ts
  lib/core/src/server/__snapshots__/preview-dev
  lib/core/src/server/__snapshots__/preview-prod
Labels: addon: controls, feature request

#13906 Fix PropDescriptor babel warnings
  addons/docs/src/blocks/ArgsTable.tsx
  lib/client-api/src/index.ts
Labels: cleanup

#13717 CLI: Add safe check for eslint overrides
  lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: bug, cli, patch

#13758 Fix import in badge-story-starter-example.mdx.mdx
  docs/snippets/common/badge-story-starter-example.mdx.mdx
Labels: documentation, patch

#13876 CLI: Don't try to add packages that are already installed
  lib/cli/src/generators/baseGenerator.ts
  lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: maintenance, run e2e extended test suite

#13910 Improve snippet for single-story hoisting
  docs/snippets/common/button-story-hoisted.js.mdx
Labels: documentation, patch

#13912 Addon-actions: Change to override default values
  addons/actions/src/preset/addArgs.test.ts
  addons/actions/src/preset/addArgs.ts
Labels: addon: actions, args, bug

#13916 Components: Add missing `regenerator-runtime` dependency
  lib/components/package.json
  scripts/run-e2e.ts
Labels: bug, components

#13884 UI: Select search input value on /
  lib/ui/src/components/sidebar/Search.tsx
Labels: feature request, search, ui

#13915 Vue 3: Add example for reactive toolbar decorator
  examples/vue-3-cli/.storybook/preview-head.html
  examples/vue-3-cli/.storybook/preview.ts
  examples/vue-3-cli/src/stories/ThemeDecorator.stories.js
Labels: cleanup, other

#13920 Vue 3: Add example for overriding args/props
  examples/vue-3-cli/src/stories/OverrideArgs.stories.js
  examples/vue-3-cli/src/stories/OverrideArgs.vue
Labels: app: vue3, documentation, other

#13932 Build: Ensure consistency of Chromatic snapshots of Zoom stories
  lib/components/src/Zoom/Zoom.stories.tsx
Labels: maintenance

#13746 Chore: types.ts comment URL changed
  lib/addons/src/types.ts
Labels: documentation, patch

#13803 Core: Sync args state to URL
  addons/controls/README.md
  addons/controls/src/ControlsPanel.tsx
  addons/controls/src/components/NoControlsWarning.tsx
  addons/controls/src/register.tsx
  addons/controls/src/title.ts
  docs/writing-stories/args.md
  lib/api/package.json
  lib/api/src/index.tsx
  lib/api/src/lib/stories.ts
  lib/api/src/modules/stories.ts
  lib/api/src/modules/url.ts
  lib/client-api/src/args.test.ts
  lib/client-api/src/args.ts
  lib/client-api/src/story_store.test.ts
  lib/client-api/src/story_store.ts
  lib/client-api/src/types.ts
  lib/client-logger/src/index.ts
  lib/components/src/blocks/ArgsTable/NoControlsWarning.tsx
  lib/core/src/client/preview/parseArgsParam.test.ts
  lib/core/src/client/preview/parseArgsParam.ts
  lib/core/src/client/preview/start.test.ts
  lib/core/src/client/preview/url.test.ts
  lib/core/src/client/preview/url.ts
  lib/router/package.json
  lib/router/src/router.tsx
  lib/router/src/utils.test.ts
  lib/router/src/utils.ts
  lib/ui/src/components/preview/utils/stringifyQueryParams.tsx
  lib/ui/src/components/sidebar/mockdata.ts
  package.json
Labels: addon: controls, args, core, feature request

#13937 Args: Prefer react runtime default values
  addons/docs/src/frameworks/react/extractArgTypes.ts
Labels: addon: controls, addon: docs, args, bug

#13592 Core: Load middleware.cjs if it exists
  lib/core/src/server/utils/middleware.ts
Labels: core, maintenance

#13945 [Docs] Add Audi to examples page
  docs/get-started/examples.md
Labels: documentation, patch

#13946 chore: manually sync version for router
  lib/router/package.json
Labels: cleanup

#13951 Core: Improve preset handling test coverage
  lib/core/src/server/__snapshots__/angular-cli_manager-dev
  lib/core/src/server/__snapshots__/angular-cli_manager-prod
  lib/core/src/server/__snapshots__/angular-cli_preview-dev
  lib/core/src/server/__snapshots__/angular-cli_preview-prod
  lib/core/src/server/__snapshots__/cra-ts-essentials_manager-dev
  lib/core/src/server/__snapshots__/cra-ts-essentials_manager-prod
  lib/core/src/server/__snapshots__/cra-ts-essentials_preview-dev
  lib/core/src/server/__snapshots__/cra-ts-essentials_preview-prod
  lib/core/src/server/__snapshots__/html-kitchen-sink_manager-dev
  lib/core/src/server/__snapshots__/html-kitchen-sink_manager-prod
  lib/core/src/server/__snapshots__/html-kitchen-sink_preview-dev
  lib/core/src/server/__snapshots__/html-kitchen-sink_preview-prod
  lib/core/src/server/__snapshots__/vue-3-cli_manager-dev
  lib/core/src/server/__snapshots__/vue-3-cli_manager-prod
  lib/core/src/server/__snapshots__/vue-3-cli_preview-dev
  lib/core/src/server/__snapshots__/vue-3-cli_preview-prod
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_manager-dev
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_manager-prod
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_preview-dev
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_preview-prod
  lib/core/src/server/core-presets.test.ts
Labels: core, maintenance

#13591 chore: update to the autodetected-controls docs for ember. fixes #13590
  docs/essentials/auto-generated-controls/ember.mdx
  docs/get-started/install.md
  docs/get-started/installation-command-section/angular.mdx
  docs/get-started/installation-command-section/ember.mdx
  docs/get-started/installation-command-section/html.mdx
  docs/get-started/installation-command-section/marko.mdx
  docs/get-started/installation-command-section/mithril.mdx
  docs/get-started/installation-command-section/preact.mdx
  docs/get-started/installation-command-section/rax.mdx
  docs/get-started/installation-command-section/react.mdx
  docs/get-started/installation-command-section/riot.mdx
  docs/get-started/installation-command-section/svelte.mdx
  docs/get-started/installation-command-section/vue.mdx
  docs/get-started/installation-command-section/web-components.mdx
  docs/get-started/installation-problems/ember.mdx
Labels: documentation, patch

#13959 Fix framework-preset tests
  app/angular/src/server/options.ts
  app/html/src/server/options.ts
  app/vue3/src/server/options.ts
  app/web-components/src/server/options.ts
  lib/core/src/server/__snapshots__/angular-cli_manager-dev
  lib/core/src/server/__snapshots__/angular-cli_manager-prod
  lib/core/src/server/__snapshots__/angular-cli_preview-dev
  lib/core/src/server/__snapshots__/angular-cli_preview-prod
  lib/core/src/server/__snapshots__/html-kitchen-sink_preview-dev
  lib/core/src/server/__snapshots__/html-kitchen-sink_preview-prod
  lib/core/src/server/__snapshots__/vue-3-cli_preview-dev
  lib/core/src/server/__snapshots__/vue-3-cli_preview-prod
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_preview-dev
  lib/core/src/server/__snapshots__/web-components-kitchen-sink_preview-prod
  lib/core/src/server/core-presets.test.ts
Labels: maintenance

#13968 docs(CONTRIBUTING): suggest using `next` in forks
  CONTRIBUTING.md
Labels: documentation, patch

#13975 Webpack5: Fix warnings display in build-storybook
  lib/builder-webpack5/src/index.ts
Labels: bug, core, webpack5

#13963 Preact: Add CSF types
  app/preact/src/client/index.ts
  app/preact/src/client/preview/types-6-0.ts
  app/preact/types-6-0.d.ts
Labels: app: preact, feature request, typescript

#13956 Angular: Correctly destroy angular application between each render
  app/angular/src/client/preview/angular-beta/ElementRendererService.ts
  app/angular/src/client/preview/angular-beta/RendererService.test.ts
  app/angular/src/client/preview/angular-beta/RendererService.ts
  examples/angular-cli/src/stories/basics/component-with-ng-on-destroy/component-with-on-destroy.stories.ts
Labels: app: angular, bug

#13939 Angular: Support angular components without selector
  app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.test.ts
  app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts
  app/angular/src/client/preview/angular-beta/StorybookModule.test.ts
  app/angular/src/client/preview/angular-beta/StorybookWrapperComponent.ts
  examples/angular-cli/src/stories/basics/component-without-selector/__snapshots__/without-selector-ng-component-outlet.stories.storyshot
  examples/angular-cli/src/stories/basics/component-without-selector/__snapshots__/without-selector-ng-factory-resolver.stories.storyshot
  examples/angular-cli/src/stories/basics/component-without-selector/__snapshots__/without-selector.stories.storyshot
  examples/angular-cli/src/stories/basics/component-without-selector/without-selector-ng-component-outlet.stories.ts
  examples/angular-cli/src/stories/basics/component-without-selector/without-selector-ng-factory-resolver.stories.ts
  examples/angular-cli/src/stories/basics/component-without-selector/without-selector.component.ts
  examples/angular-cli/src/stories/basics/component-without-selector/without-selector.stories.ts
Labels: app: angular, feature request

#13845 Addon-docs: Fix ArgsTable tab renamed to `Story` when using args
  addons/docs/src/blocks/ArgsTable.tsx
Labels: addon: docs, block: argstable, bug

#13969 CLI: Don't allow empty string as outputDir option
  lib/core-server/src/build-static.ts
  lib/core-server/src/core-presets.test.ts
Labels: bug, build-storybook, cli

#13982 Webpack5: Add semver to builder-webpack5 dependencies
  lib/builder-webpack5/package.json
Labels: bug, webpack5

#13983 Webpack5: Fix compilation error display
  lib/core-server/src/build-dev.ts
Labels: bug, webpack5

#13981 Vue 3: Map args with setup hook & remove automatic props mapping
  app/vue3/src/client/preview/index.ts
  app/vue3/src/client/preview/render.ts
  examples/vue-3-cli/src/stories/Button.stories.js
  examples/vue-3-cli/src/stories/Button.vue
  examples/vue-3-cli/src/stories/DynamicHeading.stories.ts
  examples/vue-3-cli/src/stories/GlobalUsage.stories.js
  examples/vue-3-cli/src/stories/Header.stories.js
  examples/vue-3-cli/src/stories/OverrideArgs.stories.js
  examples/vue-3-cli/src/stories/Page.stories.js
  examples/vue-3-cli/src/stories/ThemeDecorator.stories.js
  lib/cli/src/frameworks/vue3/Button.stories.js
  lib/cli/src/frameworks/vue3/Button.vue
  lib/cli/src/frameworks/vue3/Header.stories.js
  lib/cli/src/frameworks/vue3/Page.stories.js
Labels: app: vue3, feature request

#13986 Webpack5: Remove outdated html-webpack-plugin types
  lib/builder-webpack5/package.json
Labels: bug, typescript, webpack5

#13680 documentation fixed typo
  docs/snippets/common/storybook-manager-custom-theme.js.mdx
Labels: documentation, patch

#13993 Webpack4: Upgrade html-webpack-plugin and remove external types
  lib/builder-webpack4/package.json
  yarn.lock
Labels: babel / webpack, dependencies, typescript, webpack5

#13733 Move to a fork of react-sizeme with updated React peer dependency
  addons/a11y/package.json
  addons/a11y/src/components/Report/Rules.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/jest/package.json
  addons/jest/src/components/Panel.tsx
  addons/queryparams/src/typings.d.ts
  lib/ui/package.json
  lib/ui/src/app.tsx
  yarn.lock
Labels: dependencies

#13996 Addon-docs: Support story.mdx, stories.mdx
  MIGRATION.md
  addons/docs/src/frameworks/common/preset.ts
  examples/official-storybook/main.ts
  examples/official-storybook/stories/addon-docs/stories.mdx
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod
  lib/core-server/src/__snapshots__/html-kitchen-sink_preview-dev
  lib/core-server/src/__snapshots__/html-kitchen-sink_preview-prod
  lib/core-server/src/__snapshots__/vue-3-cli_preview-dev
  lib/core-server/src/__snapshots__/vue-3-cli_preview-prod
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-dev
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-prod
  lib/core-server/src/core-presets.test.ts
Labels: addon: docs, feature request

#13998 fix typo
  docs/get-started/install.md
Labels: cleanup, patch

#13999 Core: Fix core/builder dependencies
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/cli/src/versions.json
  lib/core-common/package.json
  lib/core-server/package.json
  yarn.lock
Labels: core, dependencies

#14001 Core: Use webpack4 to build Manager UI instead of webpack5
  lib/core-common/types/index.ts
  lib/core-server/package.json
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-prod
  lib/core-server/src/__snapshots__/html-kitchen-sink_manager-dev
  lib/core-server/src/__snapshots__/html-kitchen-sink_manager-prod
  lib/core-server/src/__snapshots__/vue-3-cli_manager-dev
  lib/core-server/src/__snapshots__/vue-3-cli_manager-prod
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_manager-dev
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_manager-prod
  lib/core-server/src/manager/builder.ts
  lib/core-server/src/manager/manager-webpack.config.ts
Labels: babel / webpack, core, maintenance

#13992 Yarn PnP: Add missing dependencies for Webpack 4/5 work
  addons/docs/package.json
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/core-server/package.json
Labels: maintenance

#14007 Webpack5: Fix progress plugin version conflict
  lib/builder-webpack4/src/presets/custom-webpack-preset.ts
  lib/builder-webpack5/src/index.ts
  lib/builder-webpack5/src/presets/custom-webpack-preset.ts
Labels: bug, webpack5

#13991 Components: Add missing `regenerator-runtime` dependency
  lib/components/package.json
Labels: bug, components

#14016 Core: Refactor ProgressPlugin handling
  lib/builder-webpack4/src/index.ts
  lib/builder-webpack5/src/index.ts
  lib/cli/src/versions.json
  lib/core-common/package.json
  lib/core-common/src/types.ts
  lib/core-common/src/utils/print-duration.ts
  lib/core-common/src/utils/progress-reporting.ts
  lib/core-server/package.json
  lib/core-server/src/build-static.ts
  lib/core-server/src/dev-server.ts
  lib/core-server/src/manager/builder.ts
  lib/core-server/src/utils/progress-reporting.ts
Labels: bug, core, webpack5

#14015 Deps: upgrade react-dev-utils to get newer immer
  app/react/package.json
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  yarn.lock
Labels: dependencies

#14002 Addon-Docs: Do not create extra Vue instance for Dynamic source rendering
  addons/docs/src/frameworks/vue/sourceDecorator.ts
Labels: addon: docs, app: vue, bug

#12824 Addon-controls: Add JSON tree editor for Object/Array Type args
  .eslintignore
  addons/docs/src/frameworks/react/react-argtypes.stories.tsx
  examples/official-storybook/stories/addon-controls.stories.tsx
  lib/components/package.json
  lib/components/src/blocks/ArgsTable/ArgControl.tsx
  lib/components/src/controls/Number.tsx
  lib/components/src/controls/Object.tsx
  lib/components/src/controls/react-editable-json-tree/LICENSE.md
  lib/components/src/controls/react-editable-json-tree/components/JsonAddValue.js
  lib/components/src/controls/react-editable-json-tree/components/JsonArray.js
  lib/components/src/controls/react-editable-json-tree/components/JsonFunctionValue.js
  lib/components/src/controls/react-editable-json-tree/components/JsonNode.js
  lib/components/src/controls/react-editable-json-tree/components/JsonObject.js
  lib/components/src/controls/react-editable-json-tree/components/JsonValue.js
  lib/components/src/controls/react-editable-json-tree/index.js
  lib/components/src/controls/react-editable-json-tree/types/dataTypes.js
  lib/components/src/controls/react-editable-json-tree/types/deltaTypes.js
  lib/components/src/controls/react-editable-json-tree/types/inputUsageTypes.js
  lib/components/src/controls/react-editable-json-tree/utils/objectTypes.js
  lib/components/src/controls/react-editable-json-tree/utils/parse.js
  lib/components/src/controls/react-editable-json-tree/utils/styles.js
  lib/components/src/form/input/input.tsx
  lib/router/src/utils.ts
Labels: addon: controls, feature request

#14032 CLI: Fix opening localhost in browser by default
  lib/core-server/src/dev-server.ts
Labels: bug, cli

#14035 SyntaxHighlighter: Safely access clipboard on global.navigator
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, patch, ui

#14018 CLI/Vue 2: install vue-loader upon init of vue 2 storybook
  lib/cli/src/generators/VUE/index.ts
Labels: app: vue, cli, feature request

#14010 FAQ: Make link to symbols more apparent
  docs/workflows/faq.md
Labels: documentation, patch

#14041 CLI: Add builder option
  lib/cli/src/generate.ts
  lib/cli/src/generators/baseGenerator.ts
  lib/cli/src/initiate.ts
  lib/cli/src/project_types.ts
Labels: cli, feature request, webpack5

#14040 Chore: Updates link for addons
  lib/core-common/src/presets.ts
Labels: documentation, patch

#13560 Add PX Blue to examples list
  docs/get-started/examples.md
Labels: documentation, patch

#13699 UI: Fix shortcut button focus border to support high contrast
  lib/ui/src/components/sidebar/Menu.tsx
Labels: accessibility, bug, ui

#14054 Fix flaky color rendering
  lib/components/src/bar/button.tsx
Labels: maintenance, ui

#13685 UI: Add collapse roots to sidebar navigation
  examples/official-storybook/manager.js
  lib/api/src/lib/stories.ts
  lib/ui/src/components/sidebar/RefIndicator.tsx
  lib/ui/src/components/sidebar/Refs.tsx
  lib/ui/src/components/sidebar/Tree.tsx
  lib/ui/src/components/sidebar/TreeNode.tsx
  lib/ui/src/components/sidebar/useExpanded.ts
Labels: feature request, ui

#14047 IE11: Transpile prettier down to ES5
  lib/core-common/src/utils/es6Transpiler.ts
Labels: bug, ie11, patch

#14049 Core: Support null and undefined in URL args
  lib/client-api/src/args.test.ts
  lib/client-api/src/args.ts
  lib/client-api/src/story_store.ts
  lib/core-client/package.json
  lib/core-client/src/preview/parseArgsParam.test.ts
  lib/core-client/src/preview/parseArgsParam.ts
  lib/router/package.json
  lib/router/src/utils.test.ts
  lib/router/src/utils.ts
Labels: args, bug, core

#14062 UI: Enable search for stories and fix `/` event listener
  lib/api/src/lib/shortcut.ts
  lib/api/src/modules/layout.ts
  lib/api/src/modules/shortcuts.ts
  lib/ui/src/components/sidebar/Search.tsx
Labels: feature request, search, ui

#13600 fix: Link to docs for param/decorator after story
  lib/client-api/src/client_api.ts
Labels: documentation, patch

#14069 Move back to the original react-sizeme package
  addons/a11y/package.json
  addons/a11y/src/components/Report/Rules.tsx
  addons/a11y/src/components/Tabs.tsx
  addons/jest/package.json
  addons/jest/src/components/Panel.tsx
  lib/ui/package.json
  lib/ui/src/app.tsx
  yarn.lock
Labels: dependencies

#14067 Core: Namespace sidebar config options
  MIGRATION.md
  docs/configure/features-and-behavior.md
  docs/configure/sidebar-and-urls.md
  docs/snippets/common/storybook-config-layout.js.mdx
  docs/snippets/common/storybook-manager-disable-roots.js.mdx
  examples/official-storybook/manager.js
  lib/api/src/lib/stories.ts
  lib/api/src/modules/layout.ts
  lib/api/src/modules/provider.ts
  lib/api/src/modules/stories.ts
  lib/api/src/tests/layout.test.js
  lib/api/src/tests/stories.test.js
Labels: configuration, maintenance, ui
