Repository storybookjs/storybook, pull requests merged in 2021-08, with the labels that each got.

#15298 Use semantic version constraint for prettier (^2.2.1 instead of ~2.2.1)
  addons/docs/package.json
  addons/storysource/package.json
  lib/codemod/package.json
  lib/csf-tools/package.json
  lib/source-loader/package.json
  package.json
  yarn.lock
Labels: dependencies

#14811 lower babel-loader required version everywhere
  addons/docs/package.json
  addons/storyshots/storyshots-core/package.json
  examples/cra-react15/package.json
  examples/ember-cli/package.json
  examples/preact-kitchen-sink/package.json
  examples/vue-3-cli/package.json
  examples/vue-kitchen-sink/package.json
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/core-common/package.json
  lib/manager-webpack4/package.json
  lib/manager-webpack5/package.json
  lib/ui/package.json
  package.json
  yarn.lock
Labels: cra, dependencies

#15739 CLI: Add --no-open flag
  docs/api/cli-options.md
  lib/core-common/src/types.ts
  lib/core-server/src/cli/dev.ts
  lib/core-server/src/dev-server.ts
Labels: cli, feature request

#15444 fix: docs-page with mdx and id explanation
  docs/snippets/common/button-story-docspage-with-mdx.js.mdx
  docs/writing-docs/docs-page.md
Labels: documentation, patch

#15748 HTML: Dynamic source snippets
  addons/docs/src/frameworks/html/config.ts
  addons/docs/src/frameworks/html/config.tsx
  addons/docs/src/frameworks/html/prepareForInline.tsx
  addons/docs/src/frameworks/html/sourceDecorator.test.ts
  addons/docs/src/frameworks/html/sourceDecorator.ts
  docs/frameworks.js
  examples/html-kitchen-sink/.storybook/preview.js
  examples/html-kitchen-sink/stories/__snapshots__/addon-docs.stories.storyshot
  examples/html-kitchen-sink/stories/addon-docs.stories.mdx
Labels: addon: docs, app: html, block: source, feature request

#15769 Small typo in sample code for deprecated storiesOf
  lib/core/docs/storiesOf.md
Labels: documentation, patch

#15758 docs(recipes): Fix typos
  addons/docs/docs/recipes.md
Labels: documentation, patch

#15775 Core: Fix main.js glob resolution for direct paths in stories
  lib/core-common/src/utils/__tests__/to-require-context.test.ts
  lib/core-common/src/utils/to-require-context.ts
Labels: bug, core

#15774 Addon-docs/Angular: Use compodoc rawdescription where available
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/argtypes.snapshot
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/compodoc.snapshot
  addons/docs/src/frameworks/angular/compodoc.ts
  addons/docs/src/frameworks/angular/types.ts
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/addons/docs/doc-button/doc-button.component.ts
  package.json
  yarn.lock
Labels: bug, app: angular, addon: docs, block: argstable

#15742 Angular: Add global CSF3 renderer
  app/angular/src/client/preview/index.ts
  examples/angular-cli/.storybook/main.js
  examples/angular-cli/src/stories/preview/csf3/input-with-play.stories.ts
  examples/angular-cli/src/stories/preview/csf3/sb-input.component.ts
Labels: feature request, app: angular, csf3

#14356 CSF: Optionally pass Args generic type from BaseAnnotations to ArgTypes
  lib/addons/src/types.ts
Labels: maintenance, typescript, csf, args

#15788 Controls: Remove ArrayControl
  app/server/src/client/preview/render.ts
  examples/server-kitchen-sink/views/addons/controls/all.pug
  lib/components/src/controls/Array.stories.tsx
  lib/components/src/controls/Array.tsx
  lib/components/src/controls/index.tsx
  lib/components/src/controls/types.ts
Labels: maintenance, app: server, addon: controls

#15789 Server: Update example to use options and labels for options controls
  examples/server-kitchen-sink/stories/addons/controls.stories.json
Labels: maintenance, app: server

#15799 Add checkboxes to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#15808 Core: Add MDX support to built-in stories.json generation
  examples/angular-cli/.storybook/main.js
  examples/react-ts/main.ts
  examples/react-ts/src/AccountForm.stories.tsx
  examples/react-ts/src/addon-docs/docs-only.stories.mdx
  examples/react-ts/src/addon-docs/docs.stories.mdx
  lib/core-server/src/utils/stories-json.ts
  lib/csf-tools/src/CsfFile.test.ts
  lib/csf-tools/src/CsfFile.ts
  lib/csf-tools/src/index.ts
  lib/csf-tools/src/mdx/typings.d.ts
Labels: feature request, core, mdx

#15737 Controls: Add better icon for reset button
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
Labels: ui, maintenance, addon: controls

#15743 Addon-docs/Angular: Render user defined template as source if it exists
  addons/docs/src/frameworks/angular/sourceDecorator.ts
  app/angular/src/client/preview/decorateStory.test.ts
  app/angular/src/client/preview/decorateStory.ts
  app/angular/src/client/preview/types.ts
  examples/angular-cli/src/stories/__snapshots__/welcome-storybook.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/doc-button/__snapshots__/doc-button.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/doc-button/doc-button.component.scss
  examples/angular-cli/src/stories/addons/docs/doc-button/doc-button.stories.ts
  examples/angular-cli/src/stories/core/styles/__snapshots__/story-styles.stories.storyshot
Labels: feature request, app: angular, addon: docs, block: source

#15813 Chore: (Docs) Adjusts the docs for syntax highlighting
  docs/snippets/common/my-component-with-custom-syntax-highlight.mdx.mdx
  docs/workflows/faq.md
  docs/writing-docs/mdx.md
Labels: documentation, patch

#15827 Chore: (Docs) Polishes the Essentials intro documentation
  docs/essentials/introduction.md
Labels: documentation, patch

#15828 docs(@storybook/server): fix typo in server README
  app/server/README.md
Labels: documentation, patch

#15812 Controls: Fix `esm is not defined` error with built Storybook
  lib/components/src/blocks/ArgsTable/ArgControl.tsx
Labels: maintenance

#15832 CLI: Improve typings of Angular components
  .circleci/config.yml
  lib/cli/src/frameworks/angular/User.ts
  lib/cli/src/frameworks/angular/header.component.ts
  lib/cli/src/frameworks/angular/page.component.ts
Labels: maintenance

#15839 Chore: (Docs) Removes snippets from vue docs
  docs/essentials/controls.md
  docs/snippets/vue/button-story-default-docs-code.2.js.mdx
  docs/snippets/vue/component-story-custom-args-complex.2.js.mdx
  docs/writing-docs/doc-blocks.md
Labels: documentation, patch

#15837 Chore: (Docs) Adds the animation for the backgrounds addon
  addons/backgrounds/README.md
  addons/backgrounds/docs/addon-backgrounds.gif
Labels: documentation, addon: backgrounds, patch

#15844 Chore: (Docs) Updates assets for essentials (viewport/actions)
  addons/actions/README.md
  addons/actions/docs/screenshot.png
  addons/viewport/README.md
Labels: addon: actions, documentation, addon: viewport, patch

#15836 Chore: (Docs) Updates the documentation for Jest addon
  addons/jest/README.md
  addons/jest/docs/storybook-addon-jest.gif
Labels: documentation, addon: jest, patch

#15729 Controls: Add id to setter button for undefined values
  lib/components/src/controls/Boolean.tsx
  lib/components/src/controls/Number.tsx
  lib/components/src/controls/Object.tsx
  lib/components/src/controls/Text.tsx
  lib/components/src/controls/helpers.test.ts
  lib/components/src/controls/helpers.ts
Labels: feature request, addon: controls

#13416 Add section for installing with React apps built without CRA
  app/react/README.md
Labels: documentation

#15865 Chore: (Docs) Polishes the webpack docs
  docs/configure/webpack.md
  docs/snippets/common/storybook-main-ts-module-resolution.js.mdx
Labels: documentation, patch

#15747 fix `--host` example in cli docs
  docs/api/cli-options.md
Labels: documentation, patch

#15868 Chore: (Docs) Adds an asset to be used throughout the third party docs sites
  docs/get-started/storybook-third-party-docs.gif
Labels: documentation, patch

#15863 Build: Update `caniuse-lite` dependency
  yarn.lock
Labels: maintenance

#12882 Addon-docs: Fix newline handling in ArgsTable code blocks
  examples/cra-kitchen-sink/src/components/Container.js
  examples/cra-kitchen-sink/src/stories/test.stories.mdx
  examples/cra-ts-kitchen-sink/src/components/Button.tsx
  lib/components/src/blocks/ArgsTable/ArgRow.tsx
Labels: bug, ui, addon: docs, block: argstable

#15740 UI: Add skip to canvas/sidebar links
  lib/ui/src/components/preview/FramesRenderer.tsx
  lib/ui/src/components/sidebar/Heading.stories.tsx
  lib/ui/src/components/sidebar/Heading.tsx
  lib/ui/src/components/sidebar/Sidebar.tsx
  lib/ui/src/components/sidebar/Tree.stories.tsx
  lib/ui/src/components/sidebar/Tree.tsx
  lib/ui/src/components/sidebar/TreeNode.stories.tsx
  lib/ui/src/components/sidebar/TreeNode.tsx
  lib/ui/src/components/sidebar/useExpanded.ts
Labels: feature request, ui, accessibility

#15770 CSF3: Normalize windows paths in autoTitle
  examples/angular-cli/.storybook/main.js
  examples/angular-cli/src/stories/preview/csf3/story-with-autotitle.stories.ts
  examples/cra-kitchen-sink/.storybook/main.js
  examples/cra-kitchen-sink/package.json
  examples/cra-kitchen-sink/src/components/Container.js
  examples/cra-react15/.storybook/main.js
  examples/cra-react15/package.json
  examples/cra-ts-essentials/.storybook/main.js
  examples/cra-ts-essentials/package.json
  examples/cra-ts-kitchen-sink/.storybook/main.ts
  examples/cra-ts-kitchen-sink/package.json
  examples/cra-ts-kitchen-sink/src/components/Button.tsx
  lib/core-client/package.json
  lib/core-client/src/preview/autoTitle.test.ts
  lib/core-client/src/preview/autoTitle.ts
  lib/core-common/src/utils/es6Transpiler.ts
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-prod
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod
  yarn.lock
Labels: bug, compatibility with other tools, core, csf3

#15890 Addon-docs: Fix refs support in Docs pages
  examples/official-storybook/stories/addon-docs/ref.stories.mdx
  lib/components/src/index.ts
Labels: bug, addon: docs, mdx

#15874 Angular: Fix Cannot read property 'selector' of undefined
  app/angular/src/client/preview/angular-beta/utils/NgComponentAnalyzer.test.ts
  app/angular/src/client/preview/angular-beta/utils/NgComponentAnalyzer.ts
Labels: bug, app: angular

#15878 CLI/Storyshots: Specify custom sb extract Chromium exe
  addons/storyshots/storyshots-puppeteer/README.md
  addons/storyshots/storyshots-puppeteer/src/config.ts
  docs/workflows/storybook-composition.md
  lib/cli/src/extract.ts
Labels: feature request, addon: storyshots, composition

#15875 Updated package to reflect deprecation
  MIGRATION.md
Labels: documentation, app: react-native, patch

#15899 Fix resetArgs example snippet
  docs/snippets/common/args-usage-with-addons.js.mdx
Labels: documentation, patch

#15877 Misc: Generate and push repros to a GitHub repo every night
  .eslintignore
  .github/workflows/generate-repros.yml
  package.json
  scripts/repros-generator/fs-helper.mjs
  scripts/repros-generator/git-helper.mjs
  scripts/repros-generator/index.mjs
  scripts/repros-generator/templates/main/.stackblitzrc
  scripts/repros-generator/templates/main/README.md
  scripts/repros-generator/templates/next/.stackblitzrc
  scripts/repros-generator/templates/next/README.md
  yarn.lock
Labels: maintenance

#15894 Change -- to ― in whats-a-story.md
  docs/get-started/whats-a-story.md
Labels: documentation, patch

#15918 TypeScript: Fix glob pattern used in package `typesVersions` config
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/controls/package.json
  addons/docs/package.json
  addons/essentials/package.json
  addons/jest/package.json
  addons/links/package.json
  addons/measure/package.json
  addons/outline/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storysource/package.json
  addons/toolbars/package.json
  addons/viewport/package.json
  app/angular/package.json
  app/ember/package.json
  app/html/package.json
  app/preact/package.json
  app/react/package.json
  app/server/package.json
  app/svelte/package.json
  app/vue/package.json
  app/vue3/package.json
  app/web-components/package.json
  lib/addons/package.json
  lib/api/package.json
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/channels/package.json
  lib/client-api/package.json
  lib/client-logger/package.json
  lib/components/package.json
  lib/core-client/package.json
  lib/core-common/package.json
  lib/core-events/package.json
  lib/core-server/package.json
  lib/core/package.json
  lib/csf-tools/package.json
  lib/manager-webpack4/package.json
  lib/manager-webpack5/package.json
  lib/node-logger/package.json
  lib/postinstall/package.json
  lib/router/package.json
  lib/source-loader/package.json
  lib/theming/package.json
  lib/ui/package.json
Labels: bug, typescript

#15944 Made sentence more understandable
  docs/api/mdx.md
Labels: documentation, patch

#15928 Core: Add Babel mode v7
  MIGRATION.md
  app/react/src/server/framework-preset-react.ts
  app/web-components/src/server/framework-preset-web-components.ts
  docs/configure/babel.md
  examples/react-ts/main.ts
  lib/builder-webpack4/src/preview/base-webpack.config.ts
  lib/cli/package.json
  lib/cli/src/babel-config.ts
  lib/cli/src/generate.ts
  lib/cli/src/generators/baseGenerator.ts
  lib/cli/src/initiate.ts
  lib/core-common/src/types.ts
  lib/core-common/src/utils/babel.ts
  lib/core-common/src/utils/es6Transpiler.ts
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-dev
  lib/core-server/src/__snapshots__/cra-ts-essentials_manager-prod
  lib/core-server/src/__snapshots__/html-kitchen-sink_manager-dev
  lib/core-server/src/__snapshots__/html-kitchen-sink_manager-prod
  lib/core-server/src/__snapshots__/vue-3-cli_manager-dev
  lib/core-server/src/__snapshots__/vue-3-cli_manager-prod
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_manager-dev
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_manager-prod
  lib/core-server/src/presets/common-preset.ts
  lib/manager-webpack4/src/babel-loader-manager.ts
  lib/manager-webpack4/src/manager-config.ts
  lib/manager-webpack4/src/manager-webpack.config.ts
  lib/manager-webpack4/src/presets/babel-loader-manager.ts
  lib/manager-webpack4/src/presets/manager-preset.ts
  lib/manager-webpack5/src/babel-loader-manager.ts
  lib/manager-webpack5/src/manager-config.ts
  lib/manager-webpack5/src/manager-webpack.config.ts
  lib/manager-webpack5/src/presets/babel-loader-manager.ts
  lib/manager-webpack5/src/presets/manager-preset.ts
  lib/node-logger/src/index.ts
  yarn.lock
Labels: babel / webpack, maintenance

#15953 Bump cpy to 8.1.2 for security
  lib/core-server/package.json
  yarn.lock
Labels: dependencies
