Repository storybookjs/storybook, pull requests merged in 2022-09, with the labels that each got.

#19062 Vite: Fix framework option checks, and SSv6
  code/lib/builder-vite/src/codegen-iframe-script.ts
  code/lib/builder-vite/src/codegen-modern-iframe-script.ts
  code/lib/builder-vite/src/transform-iframe-html.ts
  code/lib/builder-vite/src/types/extended-options.type.ts
  code/lib/builder-vite/src/vite-config.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/core-common/src/index.ts
  code/lib/core-common/src/utils/get-framework-name.ts
Labels: bug, vite

#19063 Conditionally force vite rebuilds in sandbox
  scripts/sandbox.ts
Labels: maintenance, vite

#19072 Update to new TS reference format (?)
  code/lib/api/src/tests/stories.test.ts
  code/lib/preview-web/src/PreviewWeb.test.ts
Labels: maintenance

#19083 CLI: Fix race condition in sb init
  code/lib/cli/src/generators/baseGenerator.ts
Labels: bug, cli, patch

#19026 Vite: Automatically use vite.config.js
  MIGRATION.md
  code/frameworks/svelte-vite/src/preset.ts
  code/frameworks/vue3-vite/src/preset.ts
  code/lib/api/src/lib/stories.ts
  code/lib/api/src/modules/stories.ts
  code/lib/api/src/tests/stories.test.ts
  code/lib/builder-vite/src/build.ts
  code/lib/builder-vite/src/envs.ts
  code/lib/builder-vite/src/optimizeDeps.ts
  code/lib/builder-vite/src/plugins/strip-story-hmr-boundaries.ts
  code/lib/builder-vite/src/vite-config.ts
  code/lib/builder-vite/src/vite-server.ts
Labels: feature request, vite

#19071 Ensure if a docs render is torndown during preparation, it throws
  code/lib/preview-web/src/PreviewWeb.test.ts
  code/lib/preview-web/src/PreviewWeb.tsx
  code/lib/preview-web/src/render/Render.ts
  code/lib/preview-web/src/render/StandaloneDocsRender.test.ts
  code/lib/preview-web/src/render/StandaloneDocsRender.ts
  code/lib/preview-web/src/render/StoryRender.test.ts
  code/lib/preview-web/src/render/StoryRender.ts
  code/lib/preview-web/src/render/TemplateDocsRender.test.ts
  code/lib/preview-web/src/render/TemplateDocsRender.ts
Labels: bug, core

#19092 Build: Prefix generic addon stories in sandbox storybooks
  scripts/sandbox.ts
Labels: maintenance

#19087 Vite: cleanup custom plugins
  code/frameworks/react-vite/src/plugins/react-docgen.ts
  code/frameworks/svelte-vite/src/plugins/csf-plugin.ts
  code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts
  code/frameworks/vue3-vite/src/plugins/vue-docgen.ts
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/plugins/code-generator-plugin.ts
  code/lib/builder-vite/src/plugins/docgen-handlers/actualNameHandler.ts
  code/lib/builder-vite/src/plugins/index.ts
  code/lib/builder-vite/src/plugins/inject-export-order-plugin.ts
  code/lib/builder-vite/src/plugins/mdx-plugin.ts
  code/lib/builder-vite/src/plugins/no-fouc.ts
  code/lib/builder-vite/src/plugins/react-docgen.ts
  code/lib/builder-vite/src/plugins/source-loader-plugin.ts
  code/lib/builder-vite/src/plugins/strip-story-hmr-boundaries.ts
  code/lib/builder-vite/src/vite-config.ts
  code/yarn.lock
Labels: maintenance, vite

#19089 Exit yarn bootstrap with nonzero code if failed
  scripts/bootstrap.js
Labels: maintenance

#19082 Addon-actions: Move stories into addon
  code/__mocks__/inject-decorator.stories.txt
  code/addons/actions/template/stories/argtype.stories.ts
  code/addons/actions/template/stories/basics.stories.ts
  code/addons/actions/template/stories/basics.stories.tsx
  code/addons/actions/template/stories/configs.stories.ts
  code/addons/actions/template/stories/parameters.stories.ts
  code/addons/interactions/src/components/InteractionsPanel.stories.tsx
  code/addons/storyshots/storyshots-core/stories/required_with_context/Button.stories.js
  code/examples/angular-cli/src/stories/addons/actions/__snapshots__/addon-actions.stories.storyshot
  code/examples/angular-cli/src/stories/addons/actions/addon-actions.stories.ts
  code/examples/angular-cli/src/stories/addons/docs/simple.stories.mdx
  code/examples/angular-cli/src/stories/basics/angular-forms/customControlValueAccessor/custom-cva-component.stories.ts
  code/examples/angular-cli/src/stories/core/styles/story-styles.stories.ts
  code/examples/cra-kitchen-sink/src/stories/button.stories.js
  code/examples/cra-kitchen-sink/src/stories/decorators.stories.js
  code/examples/cra-kitchen-sink/src/stories/long-description.stories.js
  code/examples/cra-ts-kitchen-sink/src/components/Button.stories.tsx
  code/examples/cra-ts-kitchen-sink/src/stories/1-Button.stories.tsx
  code/examples/ember-cli/stories/addon-actions.stories.js
  code/examples/ember-cli/stories/welcome-banner.stories.js
  code/examples/html-kitchen-sink/stories/addon-actions.stories.js
  code/examples/html-kitchen-sink/stories/addon-docs.stories.mdx
  code/examples/html-kitchen-sink/stories/button.stories.js
  code/examples/official-storybook/stories/addon-actions.stories.js
  code/examples/official-storybook/stories/addon-docs/addon-docs-mdx.stories.mdx
  code/examples/official-storybook/stories/addon-docs/ts-button.stories.tsx
  code/examples/official-storybook/stories/addon-links/href.stories.js
  code/examples/official-storybook/stories/core/interleaved-exports.stories.js
  code/examples/official-storybook/stories/demo/button.stories.js
  code/examples/official-storybook/stories/demo/button.stories.mdx
  code/examples/official-storybook/stories/demo/csf-embedding.test.js
  code/examples/preact-kitchen-sink/src/stories/addon-actions.stories.js
  code/examples/preact-kitchen-sink/src/stories/button.stories.js
  code/examples/svelte-kitchen-sink/src/stories/addon-actions.stories.js
  code/examples/svelte-kitchen-sink/src/stories/decorators.stories.js
  code/examples/vue-kitchen-sink/src/stories/addon-actions.stories.js
  code/examples/vue-kitchen-sink/src/stories/custom-rendering.stories.js
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.test.js.snap
Labels: maintenance, addon: actions

#19085 Addon-backgrounds: Move stories into addon
  code/addons/backgrounds/template/stories/grid.stories.ts
  code/addons/backgrounds/template/stories/parameters.stories.ts
  code/examples/angular-cli/src/stories/addons/backgrounds/__snapshots__/addon-background.stories.storyshot
  code/examples/angular-cli/src/stories/addons/backgrounds/addon-background.stories.ts
  code/examples/ember-cli/stories/addon-backgrounds.stories.js
  code/examples/html-kitchen-sink/stories/addon-backgrounds.stories.js
  code/examples/official-storybook/stories/addon-backgrounds.stories.js
  code/examples/preact-kitchen-sink/src/stories/addon-backgrounds.stories.js
  code/examples/svelte-kitchen-sink/src/stories/addon-backgrounds.stories.js
  code/examples/vue-kitchen-sink/src/stories/addon-backgrounds.stories.js
  code/examples/web-components-kitchen-sink/src/stories/addons/background/addon-background.stories.ts
Labels: maintenance, addon: backgrounds

#19086 Addon-viewport: Move stories into addon
  code/addons/viewport/template/stories/parameters.stories.ts
  code/examples/official-storybook/stories/addon-viewport/custom-default.stories.js
  code/examples/official-storybook/stories/addon-viewport/default.stories.js
  code/examples/web-components-kitchen-sink/src/stories/addons/viewport/addon-viewport.stories.ts
Labels: maintenance, addon: viewport

#19088 Vite: Don't add babel dependencies during init
  code/lib/cli/src/generators/baseGenerator.ts
Labels: bug, cli, vite

#19104 Deps: Upgrade react-element-to-jsx-string and react-inspector for React 18
  code/addons/actions/package.json
  code/addons/actions/src/components/ActionLogger/index.tsx
  code/addons/actions/src/typings.d.ts
  code/renderers/react/package.json
  code/renderers/react/src/docs/jsxDecorator.tsx
  code/renderers/react/src/docs/lib/defaultValues/createFromRawDefaultProp.ts
  code/yarn.lock
Labels: dependencies

#19115 CLI: Fix include rendererAssets in npm bundle
  code/lib/cli/package.json
Labels: bug, cli

#19111 Svelte: Update sveltedoc dependencies
  code/presets/svelte-webpack/package.json
  code/renderers/svelte/package.json
  code/yarn.lock
Labels: dependencies, app: svelte

#19097 CLI: remove outdated comment in Angular starter
  code/lib/cli/rendererAssets/angular/Button.stories.ts
Labels: maintenance, cli, patch

#19095 Vite: Fix plugin types
  code/frameworks/react-vite/package.json
  code/frameworks/react-vite/src/plugins/react-docgen.ts
  code/frameworks/react-vite/src/preset.ts
  code/frameworks/svelte-vite/package.json
  code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts
  code/frameworks/svelte-vite/src/preset.ts
  code/frameworks/vue3-vite/package.json
  code/frameworks/vue3-vite/src/plugins/vue-docgen.ts
  code/frameworks/vue3-vite/src/preset.ts
  code/lib/builder-vite/package.json
  code/yarn.lock
Labels: maintenance, vite

#19084 UI: Update a handful of icons
  code/lib/components/src/icon/icons.tsx
Labels: maintenance, components

#19052 Doc blocks: Update ArgTable Reset button to use IconButton
  code/lib/blocks/src/components/ArgsTable/ArgsTable.tsx
Labels: maintenance, block: argstable

#19127 Vite: Ensure we set `DOCS_OPTIONS` in the vite builder
  code/lib/builder-vite/input/iframe.html
  code/lib/builder-vite/src/transform-iframe-html.ts
Labels: bug, addon: docs, vite

#19067 Spelling correction
  docs/writing-stories/decorators.md
Labels: documentation, patch

#19136 Chore: (Docs)Adds why page
  docs/faq.md
  docs/misc-docs-assets/why-storybook/7.0-storybook-hero-video.mp4
  docs/misc-docs-assets/why-storybook/multiverse.png
  docs/misc-docs-assets/why-storybook/whats-a-story.mp4
  docs/snippets/angular/histogram-story.mdx.mdx
  docs/snippets/angular/histogram-story.ts.mdx
  docs/snippets/html/histogram-story.js.mdx
  docs/snippets/html/histogram-story.ts.mdx
  docs/snippets/preact/histogram-story.js.mdx
  docs/snippets/preact/histogram-story.mdx.mdx
  docs/snippets/react/histogram-story.js.mdx
  docs/snippets/react/histogram-story.mdx.mdx
  docs/snippets/react/histogram-story.ts.mdx
  docs/snippets/svelte/histogram-story.js.mdx
  docs/snippets/svelte/histogram-story.mdx.mdx
  docs/snippets/vue/histogram-story.2.js.mdx
  docs/snippets/vue/histogram-story.3.js.mdx
  docs/snippets/vue/histogram-story.mdx-2.mdx
  docs/snippets/vue/histogram-story.mdx-3.mdx
  docs/snippets/vue/histogram-story.ts-2.ts.mdx
  docs/snippets/vue/histogram-story.ts-3.ts.mdx
  docs/snippets/web-components/histogram-story.js.mdx
  docs/toc.js
  docs/why-storybook.md
Labels: documentation, patch

#19019 CLI: Fix spawning child processes on windows
  code/frameworks/angular/src/builders/utils/run-compodoc.ts
  code/frameworks/angular/src/client/docs/angular-properties.test.ts
  code/lib/cli/src/add.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/js-package-manager/JsPackageManagerFactory.ts
  code/lib/cli/src/link.ts
  code/lib/cli/src/upgrade.ts
  code/lib/codemod/src/index.js
  code/renderers/web-components/src/docs/web-components-properties.test.ts
Labels: bug, cli, windows

#19105 Add parameter, loader and decorator stories to `lib/store`
  code/examples/angular-cli/src/stories/core/parameters/all-parameters.stories.ts
  code/examples/cra-kitchen-sink/src/stories/decorators.stories.js
  code/examples/html-kitchen-sink/stories/loaders.stories.js
  code/examples/official-storybook/stories/core/decorators.stories.js
  code/examples/official-storybook/stories/core/loaders.stories.js
  code/examples/official-storybook/stories/core/parameters.stories.js
  code/lib/blocks/src/blocks/Meta.tsx
  code/lib/builder-vite/src/codegen-modern-iframe-script.ts
  code/lib/store/template/stories/decorators.stories.ts
  code/lib/store/template/stories/loaders.stories.ts
  code/lib/store/template/stories/parameters.stories.ts
  code/lib/store/template/stories/preview.ts
  code/renderers/react/template/components/Pre.jsx
  code/renderers/react/template/components/index.js
  code/renderers/svelte/template/components/Pre.svelte
  code/renderers/svelte/template/components/index.js
  code/renderers/vue3/template/components/Pre.vue
  code/renderers/vue3/template/components/index.js
  scripts/sandbox.ts
Labels: maintenance

#19118 Generic stories for remaining core features
  code/examples/official-storybook/main.ts
  code/examples/official-storybook/stories/core/args.stories.tsx
  code/examples/official-storybook/stories/core/async.stories.inactive.js
  code/examples/official-storybook/stories/core/errors.stories.js
  code/examples/official-storybook/stories/core/events.stories.js
  code/examples/official-storybook/stories/core/globals.stories.js
  code/examples/official-storybook/stories/core/interleaved-exports.stories.js
  code/examples/official-storybook/stories/core/layout.stories.js
  code/examples/official-storybook/stories/core/layout.stories.mdx
  code/examples/official-storybook/stories/core/named-export-order.stories.js
  code/examples/official-storybook/stories/core/prefix.stories.js
  code/examples/official-storybook/stories/core/reexport-source-loader.stories.js
  code/examples/official-storybook/stories/core/rendering.stories.js
  code/examples/official-storybook/stories/core/scroll.stories.js
  code/examples/official-storybook/stories/core/sideloaded.stories.tsx
  code/examples/official-storybook/stories/core/unicode.stories.js
  code/examples/official-storybook/stories/hooks.stories.js
  code/examples/official-storybook/stories/title/AutoTitle.stories.js
  code/examples/official-storybook/stories/title/CustomTitle.stories.js
  code/lib/store/template/stories/argTypes.stories.ts
  code/lib/store/template/stories/args.stories.ts
  code/lib/store/template/stories/autotitle.stories.ts
  code/lib/store/template/stories/exportOrder.stories.ts
  code/lib/store/template/stories/globals.stories.ts
  code/lib/store/template/stories/hooks.stories.ts
  code/lib/store/template/stories/import.js
  code/lib/store/template/stories/interleavedExports.stories.ts
  code/lib/store/template/stories/layout.stories.ts
  code/lib/store/template/stories/names.stories.ts
  code/lib/store/template/stories/preview.ts
  code/lib/store/template/stories/rendering.stories.ts
  code/lib/store/template/stories/title.stories.ts
  code/lib/store/template/stories/unicode.stories.ts
  code/renderers/react/template/stories/errors.stories.tsx
Labels: maintenance, core

#19125 React: Fix issue with react 18 implementation
  code/lib/store/template/stories/rendering.stories.ts
  code/renderers/react/src/render.tsx
Labels: bug, app: react

#19144 FIX addon background agnostic stories
  code/addons/backgrounds/template/stories/parameters.stories.ts
Labels: cleanup

#19139 Build: Bundle addon-interactions with tsup
  code/addons/interactions/manager.js
  code/addons/interactions/package.json
  code/addons/interactions/preview.js
  code/yarn.lock
Labels: maintenance, core

#19146 Mention versioning and history in the Publish docs
  docs/sharing/publish-storybook.md
  docs/sharing/workflow-history-versioning.png
Labels: documentation

#19147 remove node12 from the matrix
  .github/workflows/tests-unit.yml
Labels: maintenance

#19064 Core: Fix static dirs targeting same destination
  code/examples/angular-cli/.storybook/main.ts
  code/examples/angular-cli/src/assets/a/a.json
  code/examples/angular-cli/src/assets/b/b.json
  code/lib/core-server/src/utils/copy-all-static-files.ts
Labels: bug, patch, core

#19054 Upgrade emotion deps again
  code/examples/official-storybook/package.json
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/theming/package.json
  code/lib/theming/scripts/fix-theme-type-export.ts
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies, theming

#19150 Chore: (Docs) Histogram stories migration to CSF 3
  docs/snippets/angular/histogram-story.mdx.mdx
  docs/snippets/angular/histogram-story.ts.mdx
  docs/snippets/html/histogram-story.js.mdx
  docs/snippets/html/histogram-story.ts.mdx
  docs/snippets/preact/histogram-story.js.mdx
  docs/snippets/preact/histogram-story.mdx.mdx
  docs/snippets/react/histogram-story.js.mdx
  docs/snippets/react/histogram-story.mdx.mdx
  docs/snippets/react/histogram-story.ts.mdx
  docs/snippets/svelte/histogram-story.js.mdx
  docs/snippets/svelte/histogram-story.mdx.mdx
  docs/snippets/vue/histogram-story.2.js.mdx
  docs/snippets/vue/histogram-story.3.js.mdx
  docs/snippets/vue/histogram-story.mdx-2.mdx
  docs/snippets/vue/histogram-story.mdx-3.mdx
  docs/snippets/vue/histogram-story.ts-2.ts.mdx
  docs/snippets/vue/histogram-story.ts-3.ts.mdx
  docs/snippets/web-components/histogram-story.js.mdx
Labels: documentation

#19159 Chore: (Docs)Fixes Preact Histogram story for CSF 3
  docs/snippets/preact/histogram-story.mdx.mdx
Labels: documentation

#19149 Build: Generic stories for addon-controls
  code/addons/controls/template/stories/basics.stories.ts
  code/addons/controls/template/stories/conditional.stories.ts
  code/addons/controls/template/stories/disable.stories.ts
  code/addons/controls/template/stories/filters.stories.ts
  code/addons/controls/template/stories/issues.stories.ts
  code/addons/controls/template/stories/matchers.stories.ts
  code/examples/angular-cli/src/stories/addons/controls/__snapshots__/addon-controls.stories.storyshot
  code/examples/angular-cli/src/stories/addons/controls/addon-controls.stories.ts
  code/examples/ember-cli/stories/addon-controls.stories.js
  code/examples/html-kitchen-sink/stories/addon-controls.stories.js
  code/examples/official-storybook/stories/addon-controls.stories.tsx
  code/examples/svelte-kitchen-sink/src/stories/__snapshots__/addon-controls.stories.storyshot
  code/examples/svelte-kitchen-sink/src/stories/addon-controls.stories.js
  code/examples/svelte-kitchen-sink/src/stories/views/ControlShowcaseView.svelte
  code/examples/vue-kitchen-sink/src/stories/__snapshots__/addon-actions.stories.storyshot
  code/examples/vue-kitchen-sink/src/stories/__snapshots__/addon-controls.stories.storyshot
  code/examples/vue-kitchen-sink/src/stories/addon-controls.stories.js
  code/examples/web-components-kitchen-sink/src/stories/addons/controls/addon-controls.stories.ts
Labels: maintenance, addon: controls

#19161 Controls: Generic stories for sorting
  code/addons/controls/template/stories/sorting.stories.ts
  code/examples/official-storybook/stories/controls-sort.stories.tsx
Labels: maintenance, addon: controls

#19162 Addon-docs: Generic stories for DocsPage
  code/addons/docs/template/stories/docspage/basic.stories.ts
  code/addons/docs/template/stories/docspage/description.stories.ts
  code/addons/docs/template/stories/docspage/extract-description.stories.ts
  code/addons/docs/template/stories/docspage/overflow.stories.ts
  code/addons/docs/template/stories/docspage/override.stories.ts
  code/addons/docs/template/stories/docspage/source.stories.ts
  code/examples/official-storybook/stories/addon-docs/addon-docs-blocks.stories.js
  code/examples/official-storybook/stories/addon-docs/addon-docs.stories.js
  code/examples/official-storybook/stories/addon-docs/array-subcomponents.stories.js
  code/examples/official-storybook/stories/addon-docs/dynamic-title.stories.js
  code/examples/official-storybook/stories/addon-docs/memo.stories.js
  code/examples/official-storybook/stories/addon-docs/mixed-leaves-component.stories.js
  code/examples/official-storybook/stories/addon-docs/mixed-leaves-folder.stories.js
  code/examples/official-storybook/stories/addon-docs/source.stories.tsx
  code/examples/official-storybook/stories/addon-docs/subcomponents.stories.js
  code/examples/official-storybook/stories/addon-docs/transform-source.stories.js
  code/examples/official-storybook/stories/addon-docs/ts-button.stories.tsx
  scripts/sandbox.ts
Labels: maintenance, addon: docs

#19168 TypeScript: Revert a few @ts-expect-errors
  code/lib/api/src/modules/versions.ts
  code/lib/builder-webpack5/src/index.ts
  code/lib/core-common/src/utils/envs.ts
  code/lib/core-common/src/utils/normalize-stories.ts
  code/lib/preview-web/src/render/StoryRender.ts
Labels: maintenance, typescript

#19166 Toolbars: Generic example stories
  code/addons/toolbars/template/stories/globals.stories.ts
  code/addons/toolbars/template/stories/preview.ts
  code/examples/angular-cli/src/stories/addons/toolbars/locales/__snapshots__/locales.stories.storyshot
  code/examples/angular-cli/src/stories/addons/toolbars/locales/locales.stories.ts
  code/examples/angular-cli/src/stories/addons/toolbars/locales/translate.pipe.ts
  code/examples/angular-cli/src/stories/addons/toolbars/locales/translate.service.ts
  code/examples/official-storybook/stories/addon-toolbars.stories.js
  code/examples/web-components-kitchen-sink/src/stories/addons/toolbars/addon-toolbars.stories.ts
Labels: maintenance, addon: toolbars

#19145 Fix issue in instrumenter with `waitFor`
  code/examples/angular-cli/src/stories/addons/interactions/addon-interactions.stories.ts
  code/lib/instrumenter/src/instrumenter.test.ts
  code/lib/instrumenter/src/instrumenter.ts
Labels: bug, addon: interactions

#19143 Add a new `hidePlayFunctionExceptions` parameter
  code/addons/interactions/src/preset/preview.ts
  code/lib/preview-web/src/PreviewWeb.mockdata.ts
  code/lib/preview-web/src/PreviewWeb.test.ts
  code/lib/preview-web/src/PreviewWeb.tsx
  code/lib/preview-web/src/render/StoryRender.ts
Labels: feature request, addon: interactions

#19114 Addon-a11y: Move stories into addon
  code/addons/a11y/src/a11yRunner.ts
  code/addons/a11y/template/stories/parameters.stories.ts
  code/addons/a11y/template/stories/tests.stories.ts
  code/cypress/integration/navigation.spec.ts
  code/examples/ember-cli/stories/addon-a11y.stories.js
  code/examples/html-kitchen-sink/.storybook/preview.js
  code/examples/html-kitchen-sink/stories/__snapshots__/addon-a11y.stories.storyshot
  code/examples/html-kitchen-sink/stories/addon-a11y.stories.js
  code/examples/official-storybook/preview.js
  code/examples/official-storybook/stories/addon-a11y/base-button.stories.js
  code/examples/official-storybook/stories/addon-a11y/button.stories.js
  code/examples/official-storybook/stories/addon-a11y/form.stories.js
  code/examples/official-storybook/stories/addon-a11y/highlight.stories.js
  code/examples/official-storybook/stories/addon-a11y/image.stories.js
  code/examples/official-storybook/stories/addon-a11y/parameters.stories.js
  code/examples/official-storybook/stories/addon-a11y/typography.stories.js
  code/examples/server-kitchen-sink/.storybook/preview.js
  code/examples/server-kitchen-sink/stories/addons/a11y.stories.json
  code/examples/web-components-kitchen-sink/.storybook/preview.js
  code/examples/web-components-kitchen-sink/src/stories/addons/a11y/addon-a11y.stories.ts
  code/lib/cli/src/upgrade.ts
  code/renderers/react/template/components/Html.jsx
  code/renderers/react/template/components/index.js
  code/renderers/svelte/template/components/Html.svelte
  code/renderers/svelte/template/components/index.js
  code/renderers/vue3/template/components/Html.vue
  code/renderers/vue3/template/components/index.js
  scripts/sandbox.ts
Labels: maintenance

#19124 Addon-links: Move stories into addon
  code/addons/links/template/stories/decorator.stories.ts
  code/addons/links/template/stories/linkto.stories.ts
  code/addons/links/template/stories/scroll.stories.ts
  code/addons/storyshots/storyshots-core/stories/required_with_context/Welcome.stories.js
  code/addons/storyshots/storyshots-core/stories/required_with_context/Welcome.stories.mdx
  code/cypress/integration/addon-links.spec.ts
  code/examples/angular-cli/src/stories/addons/docs/addon-docs.stories.mdx
  code/examples/angular-cli/src/stories/addons/links/addon-links.stories.ts
  code/examples/angular-cli/src/stories/welcome-angular.stories.ts
  code/examples/angular-cli/src/stories/welcome-storybook.stories.ts
  code/examples/cra-kitchen-sink/src/stories/welcome.stories.js
  code/examples/cra-ts-essentials/src/stories/0-Welcome.stories.tsx
  code/examples/cra-ts-kitchen-sink/src/stories/0-Welcome.stories.tsx
  code/examples/ember-cli/stories/addon-links.stories.js
  code/examples/html-kitchen-sink/stories/welcome.stories.js
  code/examples/official-storybook/stories/addon-links/button.stories.tsx
  code/examples/official-storybook/stories/addon-links/href.stories.js
  code/examples/official-storybook/stories/addon-links/link.stories.js
  code/examples/official-storybook/stories/addon-links/scroll.stories.js
  code/examples/official-storybook/stories/addon-links/select.stories.js
  code/examples/official-storybook/stories/demo/welcome.stories.js
  code/examples/preact-kitchen-sink/src/stories/addon-links.stories.js
  code/examples/preact-kitchen-sink/src/stories/welcome.stories.js
  code/examples/svelte-kitchen-sink/src/stories/addon-links.stories.js
  code/examples/vue-kitchen-sink/src/stories/addon-links.stories.js
  code/examples/vue-kitchen-sink/src/stories/components/welcome.stories.js
  code/examples/vue-kitchen-sink/src/stories/custom-rendering.stories.js
  code/renderers/react/template/components/Html.jsx
  code/renderers/svelte/template/components/Html.svelte
  code/renderers/vue3/template/components/Html.vue
  scripts/sandbox.ts
Labels: maintenance

#19152 Presets: Replace `config` with `previewAnnotations`, remove `previewEntries`
  MIGRATION.md
  code/lib/builder-vite/src/codegen-iframe-script.ts
  code/lib/builder-vite/src/codegen-modern-iframe-script.ts
  code/lib/builder-webpack5/src/presets/preview-preset.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/builder-webpack5/src/preview/virtualModuleEntry.template.js
  code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/lib/core-server/package.json
  code/lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev-posix
  code/lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod-posix
  code/lib/core-server/src/__snapshots__/html-kitchen-sink_preview-dev-posix
  code/lib/core-server/src/__snapshots__/html-kitchen-sink_preview-prod-posix
  code/lib/core-server/src/__snapshots__/vue-3-cli_preview-dev-posix
  code/lib/core-server/src/__snapshots__/vue-3-cli_preview-prod-posix
  code/lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-dev-posix
  code/lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-prod-posix
  code/lib/core-server/src/presets/common-preset.ts
  code/yarn.lock
  scripts/sandbox.ts
Labels: maintenance, vite

#19153 Added some basic interactions stories
  code/addons/interactions/src/examples/AccountFormInteractions/AccountFormInteractions.stories.mdx
  code/addons/interactions/src/examples/AccountFormInteractions/AccountFormInteractions.stories.tsx
  code/addons/interactions/src/examples/AccountFormInteractions/AccountFormInteractions.tsx
  code/addons/interactions/src/examples/Examples.stories.tsx
  code/addons/interactions/template/stories/basics.stories.ts
  code/cypress/integration/navigation.spec.ts
  code/examples/cra-ts-essentials/src/stories/testing-react/components/AccountForm.test.tsx
  code/examples/official-storybook/package.json
  code/examples/official-storybook/stories/addon-interactions/AccountForm.stories.tsx
  code/examples/official-storybook/stories/addon-interactions/AccountForm.tsx
  code/examples/react-ts/src/AccountForm.stories.tsx
  code/examples/react-ts/src/AccountForm.tsx
  code/examples/react-ts/src/__snapshots__/storyshots.test.ts.snap
  code/renderers/react/template/components/Form.jsx
  code/renderers/react/template/components/index.js
  code/renderers/svelte/template/components/Form.svelte
  code/renderers/svelte/template/components/index.js
  code/renderers/vue3/template/components/Form.vue
  code/renderers/vue3/template/components/index.js
  code/yarn.lock
Labels: maintenance, addon: interactions

#19138 Build: Bundle @storybook/cli with tsup
  code/lib/cli/.eslintrc.js
  code/lib/cli/bin/index.js
  code/lib/cli/package.json
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/cli/src/generators/AURELIA/index.ts
  code/lib/cli/src/generators/REACT_NATIVE/index.ts
  code/lib/cli/src/generators/SERVER/index.ts
  code/lib/cli/src/repro-generators/scripts.ts
  code/lib/cli/templates/angular/template-csf/.storybook/tsconfig.json
  code/lib/cli/templates/angular/template-csf/.storybook/typings.d.ts
  code/lib/cli/templates/aurelia/template-csf/.storybook/tsconfig.json
  code/lib/cli/templates/aurelia/template-csf/.storybook/typings.d.ts
  code/lib/cli/templates/react-native/template-csf/storybook/addons.js
  code/lib/cli/templates/react-native/template-csf/storybook/index.js
  code/lib/cli/templates/react-native/template-csf/storybook/rn-addons.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/Button/Button.stories.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/Button/index.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/CenterView/index.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/CenterView/style.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/Welcome/Welcome.stories.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/Welcome/index.js
  code/lib/cli/templates/react-native/template-csf/storybook/stories/index.js
  code/lib/cli/templates/server/template-csf/.storybook/preview.js
  code/lib/cli/tsconfig.json
  code/yarn.lock
Labels: maintenance, core

#19123 fix: type `storyIdToEntry` explicitly
  code/lib/store/src/StoryStore.ts
Labels: maintenance, typescript

#19129 do not remove the old framework, because that's now the renderer
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: bug, cli

#18999 fix(clipboard): try to fix clipboard issue
  code/lib/ui/src/components/preview/iframe.tsx
Labels: bug, block: source

#18888 Fix copy button copying outdated snippet
  code/frameworks/vue3-vite/preset.js
  code/lib/builder-manager/src/types.ts
  code/lib/builder-vite/src/codegen-entries.ts
  code/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, components

#19177 Updates to the sidebar
  docs/toc.js
Labels: documentation, patch

#19156 Build: Fix sandbox running multiple versions of react
  code/lib/builder-vite/src/list-stories.ts
  code/renderers/react/template/stories/hooks.stories.tsx
  scripts/sandbox.ts
  scripts/utils/filterExistsInCodeDir.ts
Labels: maintenance

#19173 Build lib/node-logger with ts-up
  code/lib/node-logger/package.json
Labels: maintenance, core

#15472 Fix: Recalculate height of ZoomElement when child element updates
  code/lib/components/src/Zoom/Zoom.tsx
  code/lib/components/src/Zoom/ZoomElement.tsx
Labels: bug, addon: docs

#19179 Remove `cra-kitchen-sink` example
  .circleci/config.yml
  CONTRIBUTING.old.md
  code/.gitignore
  code/examples/cra-kitchen-sink/.env
  code/examples/cra-kitchen-sink/.storybook/main.ts
  code/examples/cra-kitchen-sink/.storybook/manager.js
  code/examples/cra-kitchen-sink/.storybook/preview.js
  code/examples/cra-kitchen-sink/package.json
  code/examples/cra-kitchen-sink/public/favicon.ico
  code/examples/cra-kitchen-sink/public/index.html
  code/examples/cra-kitchen-sink/src/App.css
  code/examples/cra-kitchen-sink/src/App.js
  code/examples/cra-kitchen-sink/src/base.css
  code/examples/cra-kitchen-sink/src/components/Container.js
  code/examples/cra-kitchen-sink/src/components/FastRefreshExample.js
  code/examples/cra-kitchen-sink/src/components/LifecycleLogger.js
  code/examples/cra-kitchen-sink/src/components/react-demo.js
  code/examples/cra-kitchen-sink/src/index.css
  code/examples/cra-kitchen-sink/src/index.js
  code/examples/cra-kitchen-sink/src/logo.svg
  code/examples/cra-kitchen-sink/src/stories/App.stories.js
  code/examples/cra-kitchen-sink/src/stories/Lifecycle.stories.js
  code/examples/cra-kitchen-sink/src/stories/button.stories.js
  code/examples/cra-kitchen-sink/src/stories/fast-refresh.stories.js
  code/examples/cra-kitchen-sink/src/stories/force-rerender.stories.js
  code/examples/cra-kitchen-sink/src/stories/long-description.stories.js
  code/examples/cra-kitchen-sink/src/stories/test.stories.mdx
  code/examples/cra-kitchen-sink/src/stories/welcome.stories.js
  code/jest.config.js
  code/workspace.json
  code/yarn.lock
Labels: maintenance

#19187 Chore: (Docs) Minor tweaks to the Why page
  docs/why-storybook.md
Labels: documentation, patch

#19193 Chore: (Docs) Minor fixes to Vue ts play function
  docs/snippets/svelte/my-component-play-function-alt-queries.mdx.mdx
  docs/snippets/vue/my-component-play-function-alt-queries.ts.mdx
  docs/snippets/vue/my-component-play-function-query-findby.mdx.mdx
  docs/snippets/vue/my-component-play-function-waitfor.ts.mdx
  docs/snippets/vue/my-component-play-function-with-selectevent.ts.mdx
Labels: documentation, patch

#19194 Chore: (Docs) Vue Additional fixes to examples
  docs/snippets/vue/my-component-play-function-alt-queries.ts.mdx
  docs/snippets/vue/my-component-play-function-waitfor.js.mdx
  docs/snippets/vue/my-component-play-function-waitfor.ts.mdx
  docs/snippets/vue/my-component-play-function-with-canvas.js.mdx
  docs/snippets/vue/my-component-play-function-with-canvas.ts.mdx
  docs/snippets/vue/my-component-play-function-with-clickevent.ts.mdx
Labels: documentation, patch

#19195 Chore: (Docs) CSF 3 examples updates
  docs/snippets/angular/my-component-play-function-alt-queries.mdx.mdx
  docs/snippets/angular/my-component-play-function-alt-queries.ts.mdx
  docs/snippets/angular/my-component-play-function-query-findby.mdx.mdx
  docs/snippets/angular/my-component-play-function-query-findby.ts.mdx
  docs/snippets/react/my-component-play-function-alt-queries.js.mdx
  docs/snippets/react/my-component-play-function-alt-queries.mdx.mdx
  docs/snippets/react/my-component-play-function-alt-queries.ts.mdx
  docs/snippets/react/my-component-play-function-query-findby.js.mdx
  docs/snippets/react/my-component-play-function-query-findby.mdx.mdx
  docs/snippets/react/my-component-play-function-query-findby.ts.mdx
  docs/snippets/svelte/my-component-play-function-alt-queries.js.mdx
  docs/snippets/svelte/my-component-play-function-alt-queries.mdx.mdx
  docs/snippets/svelte/my-component-play-function-query-findby.js.mdx
  docs/snippets/svelte/my-component-play-function-query-findby.mdx.mdx
  docs/snippets/vue/my-component-play-function-alt-queries.js.mdx
  docs/snippets/vue/my-component-play-function-alt-queries.mdx.mdx
  docs/snippets/vue/my-component-play-function-alt-queries.ts.mdx
  docs/snippets/vue/my-component-play-function-composition.ts.mdx
  docs/snippets/vue/my-component-play-function-query-findby.js.mdx
  docs/snippets/vue/my-component-play-function-query-findby.mdx.mdx
  docs/snippets/vue/my-component-play-function-query-findby.ts.mdx
  docs/snippets/vue/my-component-play-function-waitfor.ts.mdx
  docs/snippets/vue/my-component-play-function-with-canvas.ts.mdx
  docs/snippets/vue/my-component-play-function-with-clickevent.ts.mdx
  docs/snippets/vue/my-component-play-function-with-delay.ts.mdx
  docs/snippets/vue/my-component-play-function-with-selectevent.ts.mdx
  docs/snippets/vue/register-component-with-play-function.mdx.mdx
  docs/snippets/vue/register-component-with-play-function.ts.mdx
Labels: documentation

#19185 Link renderer-specific stories inside the sandbox's real stories dir.
  code/renderers/react/template/stories/errors.stories.tsx
  code/renderers/svelte/template/stories/README.md
  code/renderers/vue3/template/stories/README.md
  scripts/sandbox.ts
Labels: maintenance

#19189 Alias decorateStory as applyDecorators for angular integration
  code/frameworks/angular/src/client/config.ts
Labels: bug, app: angular, patch

#19198 Enforce @ts-expect-error via eslint
  code/addons/links/src/utils.test.ts
  code/addons/links/src/utils.ts
  code/frameworks/angular/src/client/angular-beta/__testfixtures__/input.component.ts
  code/frameworks/angular/src/client/docs/__testfixtures__/doc-button/input.ts
  code/lib/api/src/modules/versions.ts
  code/lib/api/src/typings.d.ts
  code/lib/builder-webpack5/package.json
  code/lib/builder-webpack5/src/index.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/builder-webpack5/tsconfig.json
  code/lib/core-common/src/typings.d.ts
  code/lib/core-common/src/utils/envs.ts
  code/lib/core-common/src/utils/normalize-stories.ts
  code/lib/core-webpack/src/merge-webpack-config.test.ts
  code/lib/preview-web/src/render/StoryRender.ts
  code/renderers/react/template/stories/errors.stories.tsx
  code/yarn.lock
  scripts/.eslintrc.js
Labels: maintenance, typescript

#19227 upgrade playwright version (and lock it)
  .circleci/config.yml
  code/package.json
  code/yarn.lock
Labels: dependencies

#19235 Vite: Support runStep in Vite builder SSv6
  code/lib/builder-vite/src/codegen-iframe-script.ts
Labels: bug, vite

#19244 Remove @nicolo-ribaudo/chokidar-2
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies, maintenance

#19250 fix playwright version again
  code/package.json
  code/yarn.lock
Labels: dependencies

#19249 fix the svelte button component not accepting the onClick handler
  code/examples/svelte-kitchen-sink/src/stories/views/ActionLinkView.svelte
  code/lib/cli/rendererAssets/svelte/Button.svelte
  code/renderers/svelte/template/components/Button.svelte
  docs/snippets/svelte/button-implementation.js.mdx
Labels: bug

#19251 regen lockfile
  code/yarn.lock
  scripts/yarn.lock
Labels: dependencies

#19209 React: fix typo in react snippet component comment
  docs/snippets/react/your-component.js.mdx
Labels: documentation

#19253 fix svelte e2e test: generate preview file with js extension always
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/configure.ts
Labels: bug, app: svelte, run e2e extended test suite

#19141 Build: bundle csf-tools with tsup
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/csf-tools/package.json
  code/yarn.lock
Labels: maintenance, core

#19254 Build: Remove unused angular_modern_inline_rendering
  code/lib/cli/src/repro-generators/configs.ts
Labels: maintenance

#18930 Source-loader: Fix invalid call to CSF sanitize
  code/lib/source-loader/src/abstract-syntax-tree/parse-helpers.js
Labels: bug, source-loader

#19263 Vite: Do not add Webpack loaders when using Vite builder
  code/lib/cli/src/generators/SVELTE/index.ts
  code/lib/cli/src/generators/VUE/index.ts
  code/lib/cli/src/generators/VUE3/index.ts
Labels: bug, vite

#19216 Vite: Export storybook utilities from frameworks for better pnpm support
  code/frameworks/react-vite/package.json
  code/frameworks/react-vite/src/index.ts
  code/frameworks/svelte-vite/package.json
  code/frameworks/svelte-vite/src/index.ts
  code/frameworks/vue3-vite/package.json
  code/frameworks/vue3-vite/src/index.ts
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/codegen-modern-iframe-script.ts
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/lib/builder-vite/src/plugins/code-generator-plugin.ts
  code/yarn.lock
Labels: feature request, vite

#19257 change the vue e2e test to use webpack5, since we stopped supporting webpack4 in 7.0
  code/cypress/generated/addon-interactions.spec.ts
  code/cypress/generated/basic.spec.ts
  code/lib/cli/src/repro-generators/configs.ts
  code/presets/preact-webpack/src/index.ts
Labels: maintenance, run e2e extended test suite

#19258 fix preact e2e test: dedup @babel/plugin-transform-react-jsx babel plugin in preact
  code/cypress/generated/addon-interactions.spec.ts
  code/cypress/generated/basic.spec.ts
  code/presets/preact-webpack/src/index.ts
Labels: maintenance, run e2e extended test suite

#18805 Build lib/addons with ts-up
  code/addons/a11y/src/index.ts
  code/addons/actions/src/index.ts
  code/addons/backgrounds/src/index.ts
  code/addons/jest/src/index.ts
  code/addons/links/src/index.ts
  code/addons/measure/src/index.ts
  code/addons/outline/src/index.ts
  code/addons/storysource/src/index.ts
  code/lib/addons/package.json
  code/lib/ui/src/globals/exports.ts
Labels: maintenance

#18927 storyshots-puppeteer: add browserLaunchOptions to CommonConfig
  code/addons/storyshots/storyshots-puppeteer/README.md
  code/addons/storyshots/storyshots-puppeteer/src/config.ts
  code/addons/storyshots/storyshots-puppeteer/src/puppeteerTest.ts
Labels: feature request, addon: storyshots

#19268 cleanup after moving to tsup
  code/package.json
  code/yarn.lock
  scripts/bundle-package.ts
  scripts/dts-localize.ts
  scripts/package.json
  scripts/prebundle.ts
  scripts/yarn.lock
Labels: maintenance

#18775 Build addons-actions with ts-up
  code/addons/actions/manager.js
  code/addons/actions/package.json
  code/addons/actions/preview.js
  code/addons/actions/src/addArgs.ts
  code/addons/actions/src/addArgsHelpers.test.ts
  code/addons/actions/src/addArgsHelpers.ts
  code/addons/actions/src/addDecorator.ts
  code/addons/actions/src/index.ts
  code/addons/actions/src/preset/addDecorator.ts
  code/addons/actions/src/preview.ts
  code/addons/actions/src/runtime/__tests__/action.test.js
  code/addons/actions/src/runtime/__tests__/actions.test.js
  code/addons/actions/src/runtime/__tests__/configureActions.test.js
  code/addons/actions/src/runtime/action.ts
  code/addons/actions/src/runtime/actions.ts
  code/addons/actions/src/runtime/configureActions.ts
  code/addons/actions/src/runtime/decorateAction.ts
  code/addons/actions/src/runtime/index.ts
  code/addons/actions/src/runtime/withActions.ts
  code/lib/channel-postmessage/src/index.ts
Labels: maintenance
