Repository storybookjs/storybook, pull requests merged in 2022-02, with the labels that each got.

#17000 Core: Pre-bundle theming to avoid emotion11 conflicts
  .eslintrc.js
  lib/cli/src/versions.ts
  lib/core-server/src/__snapshots__/vue-3-cli_preview-dev-posix
  lib/core-server/src/__snapshots__/vue-3-cli_preview-prod-posix
  lib/theming/package.json
  lib/theming/paths.js
  lib/theming/src/index.ts
  lib/theming/src/typings.d.ts
  package.json
  scripts/bundle-package.ts
  scripts/dts-localize.ts
  scripts/prebundle.ts
  yarn.lock
Labels: dependencies

#17382 Core: Mock channel if not present
  lib/addons/src/index.ts
Labels: core, linear

#17395 CLI: Pin version of `@mdx-js/react` to 1.x.x until we are compatible
  lib/cli/src/generators/baseGenerator.ts
Labels: bug, patch, addon: docs, mdx

#17403 Chore: (Docs) Updates decorators docs
  docs/snippets/angular/add-localize-package-to-polyfills.ts.mdx
  docs/snippets/angular/storybook-preview-with-angular-polyfills.js.mdx
  docs/writing-stories/decorators.md
Labels: documentation, patch

#17343 Improve style handling in angular example in monorepo
  examples/angular-cli/src/stories/addons/interactions/__snapshots__/addon-interactions.stories.storyshot
  examples/angular-cli/src/stories/addons/interactions/hero-form/hero-form.component.css
  examples/angular-cli/src/stories/addons/interactions/hero-form/hero-form.component.html
Labels: maintenance, app: angular

#17411 Chore: (Docs) Minor updates to the Essentials introduction
  docs/essentials/introduction.md
  docs/snippets/common/storybook-main-default-essentials-register.js.mdx
  docs/snippets/common/storybook-main-full-individual-essentials-config.js.mdx
  docs/snippets/common/storybook-main-register-individual-actions-addon.js.mdx
Labels: documentation, patch

#17292 Core: Apply Docs mode to composed storybooks
  lib/ui/src/components/sidebar/Sidebar.tsx
Labels: bug, ui, core, composition, tiny

#17415 Fix typo in presets docs
  docs/addons/writing-presets.md
Labels: documentation, patch

#17345 CLI/React: Add interactions to cli template
  lib/cli/src/frameworks/common/header.css
  lib/cli/src/frameworks/react/js/Header.jsx
  lib/cli/src/frameworks/react/js/Header.stories.jsx
  lib/cli/src/frameworks/react/js/Page.jsx
  lib/cli/src/frameworks/react/js/Page.stories.jsx
  lib/cli/src/frameworks/react/ts/Header.stories.tsx
  lib/cli/src/frameworks/react/ts/Header.tsx
  lib/cli/src/frameworks/react/ts/Page.stories.tsx
  lib/cli/src/frameworks/react/ts/Page.tsx
  lib/cli/src/generators/baseGenerator.ts
  scripts/verdaccio.yaml
Labels: feature request, cli, app: react, addon: interactions

#17381 Core: Move CSF-related logic to its own folder
  lib/store/src/GlobalsStore.ts
  lib/store/src/StoryStore.test.ts
  lib/store/src/StoryStore.ts
  lib/store/src/csf/getValuesFromArgTypes.ts
  lib/store/src/csf/index.ts
  lib/store/src/csf/normalizeComponentAnnotations.ts
  lib/store/src/csf/normalizeInputTypes.test.ts
  lib/store/src/csf/normalizeInputTypes.ts
  lib/store/src/csf/normalizeProjectAnnotations.ts
  lib/store/src/csf/normalizeStory.test.ts
  lib/store/src/csf/normalizeStory.ts
  lib/store/src/csf/prepareStory.test.ts
  lib/store/src/csf/prepareStory.ts
  lib/store/src/csf/processCSFFile.test.ts
  lib/store/src/csf/processCSFFile.ts
  lib/store/src/index.ts
Labels: maintenance, core, run e2e extended test suite, linear

#17421 CSF3: Fix auto-title redundant filename
  MIGRATION.md
  lib/store/src/autoTitle.test.ts
  lib/store/src/autoTitle.ts
Labels: bug, core, csf3

#17404 Addon-docs: Fix typo in ArgsTable tooltip
  lib/components/src/blocks/ArgsTable/SectionRow.tsx
Labels: bug, patch, addon: docs, block: argstable

#17401 Chore: (Docs) Removes outdated support table and updates links
  ADDONS_SUPPORT.md
  addons/a11y/README.md
  addons/docs/README.md
  addons/essentials/README.md
  addons/jest/README.md
  addons/links/README.md
  addons/storyshots/storyshots-core/README.md
  addons/storysource/README.md
Labels: documentation, patch

#17304 UI: Prebundle `@storybook/components`
  .eslintrc.js
  addons/storysource/package.json
  app/angular/package.json
  examples/cra-ts-essentials/package.json
  examples/cra-ts-kitchen-sink/package.json
  examples/react-ts-webpack4/package.json
  examples/react-ts/package.json
  lib/cli/src/versions.ts
  lib/components/package.json
  lib/components/src/index.ts
  lib/theming/src/index.ts
  lib/ui/src/components/layout/desktop.stories.tsx
  lib/ui/src/components/panel/panel.stories.tsx
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/sidebar/Heading.stories.tsx
  lib/ui/src/components/sidebar/Search.stories.tsx
  lib/ui/src/components/sidebar/Tree.stories.tsx
  lib/ui/src/settings/SettingsFooter.stories.tsx
  lib/ui/src/settings/about.stories.js
  lib/ui/src/settings/release_notes.stories.tsx
  lib/ui/src/settings/shortcuts.stories.tsx
  package.json
  scripts/bundle-package.ts
  scripts/dts-localize.ts
  yarn.lock
Labels: maintenance

#17424 Web-components: Upgrade kitchen sink lockfile
  examples/web-components-kitchen-sink/yarn.lock
Labels: maintenance

#17435 Core: Ensure we show an error when `configure()` throws
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.js
Labels: bug, patch, core

#17387 Chore: (Docs) Updates to the Angular documentation
  docs/configure/css-troubleshooting/angular.mdx
  docs/configure/styling-and-css.md
  docs/get-started/install.md
  docs/get-started/installation-command-section/angular.mdx
  docs/get-started/installation-problems/angular.mdx
  docs/sharing/publish-storybook.md
  docs/snippets/angular/build-storybook-production-mode.with-builder.js.mdx
  docs/snippets/angular/custom-build-script-production.script-for-builder.js.mdx
  docs/snippets/angular/storybook-angular-inline-css-loader.js.mdx
  docs/snippets/angular/storybook-run-dev.with-builder.js.mdx
  docs/snippets/common/build-storybook-production-mode.js.mdx
Labels: documentation, patch

#17351 Fix jest-image-snapshot link
  docs/writing-tests/visual-testing.md
Labels: documentation, patch

#17327 Core: Fix `useParameter` with nullish coalescing
  lib/addons/src/hooks.test.js
  lib/addons/src/hooks.ts
Labels: bug, patch, core

#17158 Update login-form-with-play-function.mdx.mdx
  docs/snippets/react/login-form-with-play-function.mdx.mdx
Labels: documentation, patch

#17440 Chore: (Docs) Minor updates to writing writing stories intro
  docs/snippets/react/button-story.mdx-with-hooks.mdx.mdx
  docs/writing-stories/introduction.md
Labels: documentation, patch

#17437 CLI: Add addon-interactions to angular template
  .circleci/config.yml
  cypress/generated/addon-interactions.spec.ts
  lib/cli/src/frameworks/angular/Header.stories.ts
  lib/cli/src/frameworks/angular/Page.stories.ts
  lib/cli/src/frameworks/angular/header.component.ts
  lib/cli/src/frameworks/angular/page.component.ts
  lib/cli/src/generators/baseGenerator.ts
Labels: feature request, cli, app: angular, patch

#17457 Fix `ci:matrix` label in CI
  .github/workflows/tests-unit.yml
Labels: maintenance

#17456 Controls: Fix Boolean control parsing
  lib/components/src/controls/Boolean.tsx
Labels: bug, addon: controls

#17447 Core/CLI: Add `extract` function to `PreviewWeb` and use it in `sb extract` if available
  lib/cli/src/extract.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
Labels: bug, patch, core

#17465 Bump vue-docgen-api to 4.44.15
  app/vue/package.json
  app/vue3/package.json
  yarn.lock
Labels: dependencies

#17464 Remove /docs/get-started/examples page
  docs/contribute/how-to-contribute.md
  docs/get-started/examples.md
  docs/toc.js
Labels: documentation

#17484 docs: The Template is a HOC
  docs/snippets/react/page-story-slots.js.mdx
Labels: documentation, patch

#17479 Double property initialization.
  docs/snippets/react/list-story-with-subcomponents.ts.mdx
Labels: documentation, patch

#17487 UI: Add a custom title story for heading component
  lib/ui/src/components/sidebar/Heading.stories.tsx
Labels: ui, maintenance

#17511 Chore: (Docs) Removes misleading info from documentation
  docs/writing-docs/doc-blocks.md
Labels: documentation, patch

#17513 Chore: (Docs) Provides additional information to the FAQ
  docs/faq.md
Labels: documentation, patch

#17501 Webpack5: Add lazy compilation
  lib/builder-webpack4/src/preview/iframe-webpack.config.ts
  lib/builder-webpack5/src/preview/base-webpack.config.ts
  lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  lib/core-common/src/types.ts
Labels: feature request, core, webpack5

#17532 Fix incorrect docs on buildStoriesJson
  docs/configure/overview.md
Labels: documentation, patch

#17375 Build: Fix CRA repro generator and e2e test in PnP mode
  .circleci/config.yml
  .eslintrc.js
  addons/docs/package.json
  addons/docs/src/frameworks/react/lib/inspection/acornParser.ts
  addons/docs/src/frameworks/svelte/prepareForInline.ts
  addons/essentials/package.json
  addons/interactions/package.json
  app/react/package.json
  lib/builder-webpack5/package.json
  lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  lib/cli/src/generators/REACT_SCRIPTS/index.ts
  lib/cli/src/initiate.ts
  lib/cli/src/repro-generators/configs.ts
  lib/cli/src/repro-generators/scripts.ts
  lib/cli/src/repro.ts
  lib/cli/src/versions.ts
  lib/components/src/controls/Boolean.tsx
  lib/core-common/src/utils/paths.ts
  lib/core-server/package.json
  lib/core-server/src/build-static.ts
  lib/core/package.json
  lib/router/package.json
  lib/theming/package.json
  lib/ui/package.json
  scripts/run-e2e.ts
  yarn.lock
Labels: maintenance, yarn / npm

#17530 Addon-Outline: add 'o' keyboard shortcut to toggle the outline addon
  addons/outline/README.md
  addons/outline/src/OutlineSelector.tsx
Labels: feature request, addon: outline

#17505 Addon-actions: Don't override undefined args
  addons/actions/src/preset/addArgsHelpers.test.ts
  addons/actions/src/preset/addArgsHelpers.ts
Labels: bug, addon: actions

#15822 Addon-docs: Account for non-string types when converting enums
  addons/docs/src/lib/convert/__testfixtures__/proptypes/enums.js
  addons/docs/src/lib/convert/convert.test.ts
  addons/docs/src/lib/convert/proptypes/convert.ts
  addons/docs/src/lib/convert/utils.ts
Labels: bug, addon: docs

#17251 Addon-docs: Ensure that __DOCS_CONTEXT__ cannot be undefined
  addons/docs/src/blocks/DocsContext.ts
Labels: bug, addon: storyshots, addon: docs

#17531 add list-story-unchecked snippet
  docs/snippets/web-components/list-story-unchecked.js.mdx
  docs/snippets/web-components/list-story-unchecked.ts.mdx
  docs/writing-stories/stories-for-multiple-components.md
Labels: documentation, patch

#17544 Addon-docs: Fix preset handling for builder with options
  addons/docs/src/frameworks/common/preset.ts
  examples/react-ts/.storybook/main.ts
Labels: bug, addon: docs

#17552 Simplify community frameworks
  docs/frameworks.js
Labels: documentation, patch

#17524 Controls/Essentials/Interactions: Add support for main.cjs/mjs/tsx files
  addons/controls/src/preset/checkDocsLoaded.ts
  addons/essentials/package.json
  addons/essentials/src/index.ts
  addons/interactions/src/preset/checkActionsLoaded.ts
  yarn.lock
Labels: bug, addon: essentials, addon: controls, addon: interactions

#17554 Docs: Add Preact code snippet for Whats a Story
  docs/get-started/whats-a-story.md
  docs/snippets/preact/button-story.js.mdx
Labels: documentation, patch

#17546 Add brief guide to running e2e tests
  docs/contribute/code.md
Labels: documentation, patch

#17551 Chore: (Docs) Doc Blocks updates
  docs/api/argtypes.md
  docs/essentials/controls.md
  docs/faq.md
  docs/snippets/common/button-story-argtypes-with-categories.mdx.mdx
  docs/snippets/common/button-story-argtypes-with-subcategories.mdx.mdx
  docs/snippets/common/colopalette-doc-block.advanced-example.mdx.mdx
  docs/snippets/common/colorpalette-doc-block.starter-example.mdx.mdx
  docs/snippets/common/component-story-custom-source.js.mdx
  docs/snippets/common/component-story-mdx-argstable-block-for-component.with-component.mdx.mdx
  docs/snippets/common/component-story-mdx-argstable-block-for-story.with-story.mdx.mdx
  docs/snippets/common/component-story-mdx-argtypes.mdx.mdx
  docs/snippets/common/component-story-mdx-dedent.mdx.mdx
  docs/snippets/common/component-story-mdx-description.mdx.mdx
  docs/snippets/common/icongallery-doc-block.mdx.mdx
  docs/snippets/common/mdx-canvas-doc-block.mdx.mdx
  docs/snippets/common/typeset-doc.block.mdx.mdx
  docs/toc.js
  docs/writing-docs/button-story-code-doc-type-optimized.mp4
  docs/writing-docs/button-story-default-docs-code.png
  docs/writing-docs/doc-block-argstable.md
  docs/writing-docs/doc-block-canvas.md
  docs/writing-docs/doc-block-colorpalette-optimized.png
  docs/writing-docs/doc-block-colorpalette.md
  docs/writing-docs/doc-block-description.md
  docs/writing-docs/doc-block-icon-gallery-optimized.png
  docs/writing-docs/doc-block-icongallery.md
  docs/writing-docs/doc-block-source.md
  docs/writing-docs/doc-block-story.md
  docs/writing-docs/doc-block-typeset-optimized.png
  docs/writing-docs/doc-block-typeset.md
  docs/writing-docs/doc-blocks.md
  docs/writing-docs/docs-page.md
  docs/writing-docs/introduction.md
  docs/writing-docs/mdx.md
  docs/writing-stories/decorators.md
Labels: documentation, patch

#17559 Simplify community frameworks
  README.md
  docs/addons/addon-catalog.md
  docs/contribute/new-snippets.md
  docs/frameworks.js
  docs/get-started/install.md
  docs/get-started/installation-command-section/marko.mdx
  docs/get-started/installation-command-section/mithril.mdx
  docs/get-started/installation-command-section/rax.mdx
  docs/get-started/installation-command-section/riot.mdx
  docs/get-started/installation-problems/marko.mdx
  docs/get-started/installation-problems/mithril.mdx
  docs/get-started/installation-problems/rax.mdx
  docs/get-started/installation-problems/riot.mdx
  docs/writing-tests/snapshot-testing.md
  examples/README.md
  lib/components/src/blocks/DocsPageExampleCaption.md
  lib/components/src/blocks/DocsPageExampleCaption.mdx
  package.json
  tests.md
Labels: documentation

#17583 Chore: (Docs) Minor docs updates
  docs/faq.md
  docs/sharing/embed.md
Labels: documentation, patch

#17535 Addon-interactions: Mock window in browser environments
  addons/interactions/src/preset/argsEnhancers.ts
Labels: bug, addon: interactions

#17577 Core: Fix global render fn
  lib/preview-web/src/composeConfigs.test.ts
  lib/preview-web/src/composeConfigs.ts
Labels: bug, core

#17582 Chore: (Docs) Updates to the Writing Docs asides
  docs/writing-docs/build-documentation.md
  docs/writing-docs/docs-page.md
  docs/writing-docs/introduction.md
  docs/writing-docs/mdx.md
Labels: documentation, patch

#17380 Angular: Improve builder migration docs & example
  MIGRATION.md
  examples/angular-cli/package.json
Labels: documentation, app: angular

#17592 Fix mdx-csf dependencies to canary dist-tag
  addons/docs/package.json
  lib/csf-tools/package.json
  yarn.lock
Labels: dependencies
