Repository storybookjs/storybook, pull requests merged in 2022-03, with the labels that each got.

#17425 Core: Remove unused babel dependencies
  .circleci/config.yml
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/argtypes.snapshot
  addons/docs/src/frameworks/angular/__testfixtures__/doc-button/compodoc-posix.snapshot
  lib/api/src/index.tsx
  lib/builder-webpack4/package.json
  lib/builder-webpack5/package.json
  lib/ui/src/components/layout/container.tsx
  package.json
  yarn.lock
Labels: maintenance

#17574 CSF3: Fix Auto-title to respect file system capitalization
  MIGRATION.md
  examples/react-ts/src/__snapshots__/storyshots.test.ts.snap
  lib/core-server/src/utils/StoryIndexGenerator.test.ts
  lib/core-server/src/utils/stories-json.test.ts
  lib/store/src/autoTitle.test.ts
  lib/store/src/autoTitle.ts
Labels: bug, csf3

#17612 Fix typo in the sub component documentation
  docs/snippets/vue/list-story-with-sub-components.3.js.mdx
Labels: documentation, patch

#17614 Addon-interactions: Use 'global' package instead of `global`
  addons/interactions/src/preset/argsEnhancers.ts
Labels: bug, addon: interactions

#17615 remove unused dependency that's also deprecated
  examples/official-storybook/package.json
  yarn.lock
Labels: maintenance, security

#17606 Core: Fix core.builder check
  lib/core-server/src/utils/get-preview-builder.ts
Labels: bug, patch, core

#17595 chore: remove unnecessary 'as any'
  addons/a11y/src/components/Report/Rules.tsx
Labels: maintenance, typescript

#17545 Build: Give linting sub-commands a directory to run against
  package.json
Labels: maintenance

#17659 Core: Error when namedExportsOrder causes story to disappear
  examples/react-ts/src/button.stories.tsx
  lib/csf-tools/src/CsfFile.ts
Labels: bug, patch, core

#17662 Prevent lint hook from running on all files
  package.json
Labels: maintenance

#17641 Core: Fix staticDirs path issue on Windows
  lib/core-server/src/utils/__tests__/server-statics.test.ts
  lib/core-server/src/utils/server-statics.ts
Labels: bug, core, windows

#17669 Addon-docs: DocsPage story order should match the index
  lib/store/src/StoryStore.test.ts
  lib/store/src/StoryStore.ts
Labels: bug, patch, core

#17598 Core: Refactor preview rendering out of `PreviewWeb`
  addons/docs/src/blocks/Story.tsx
  lib/core-client/src/preview/start.test.ts
  lib/preview-web/README.md
  lib/preview-web/src/DocsRender.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/StoryRender.ts
Labels: maintenance, core

#17599 Core: Ensure that we do not render a story twice if re-rendered during preparing
  lib/preview-web/src/DocsRender.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/StoryRender.ts
Labels: bug, core

#17674 Webpack4: Fix useExports for angular-cli
  lib/builder-webpack4/src/preview/iframe-webpack.config.ts
Labels: bug, babel / webpack, app: angular

#17670 Examples: Build stories.json for examples that support it
  addons/docs/src/frameworks/common/preset.ts
  examples/angular-cli/.storybook/main.js
  examples/angular-cli/src/stories/addons/actions/__snapshots__/addon-actions.stories.storyshot
  examples/angular-cli/src/stories/addons/backgrounds/__snapshots__/addon-background.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/addon-docs.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/simple.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/iframe/__snapshots__/iframe.stories.storyshot
  examples/angular-cli/src/stories/addons/links/__snapshots__/addon-links.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/all-parameters.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/layout.parameters.stories.storyshot
  examples/angular-cli/src/stories/core/styles/__snapshots__/story-styles.stories.storyshot
  examples/angular-cli/src/stories/legacy/__snapshots__/component-in-story.stories.storyshot
  examples/angular-cli/src/stories/legacy/__snapshots__/storiesOf.stories.storyshot
  examples/angular-cli/src/stories/legacy/storiesOf.stories.ts
  examples/angular-cli/src/stories/others/issues/__snapshots__/12009-unknown-component.stories.storyshot
  examples/cra-kitchen-sink/.storybook/main.js
  examples/cra-ts-essentials/.storybook/main.js
  examples/cra-ts-kitchen-sink/.storybook/main.ts
  examples/ember-cli/.storybook/main.js
  examples/html-kitchen-sink/.storybook/main.js
  examples/preact-kitchen-sink/.storybook/main.js
  examples/vue-3-cli/.storybook/main.js
  examples/vue-cli/.storybook/main.js
  examples/vue-kitchen-sink/.storybook/main.js
  examples/web-components-kitchen-sink/.storybook/main.js
  examples/web-components-kitchen-sink/yarn.lock
  lib/core-server/src/core-presets.test.ts
Labels: maintenance

#17520 Add documentation for Nx 13 with Angular 13 #17419
  docs/configure/css-troubleshooting/angular.mdx
Labels: documentation, patch

#17689 Docs: Fix minor typo in Importing Stories in Tests documentation
  docs/writing-tests/importing-stories-in-tests.md
Labels: documentation, patch

#17691 Chore: (Docs) Minor addition to the faq
  docs/faq.md
Labels: documentation, patch

#17702 Web-components: Fix CSS class usage in CLI template
  lib/cli/src/frameworks/web-components/js/Page.js
  lib/cli/src/frameworks/web-components/ts/Page.ts
Labels: bug, cli, patch, app: web-components

#17687 make command for html explicit
  docs/get-started/installation-command-section/html.mdx
Labels: documentation, patch

#17697 Addon-docs: Auto-disable docs presets if docs/controls unused
  MIGRATION.md
  addons/essentials/src/index.ts
  app/angular/src/server/framework-preset-angular-docs.ts
  app/ember/preset.js
  app/ember/src/server/framework-preset-ember-docs.ts
  app/ember/src/server/options.ts
  app/ember/src/server/preset.ts
  app/html/preset.js
  app/html/src/server/framework-preset-html-docs.ts
  app/html/src/server/options.ts
  app/html/src/server/preset.ts
  app/react/src/server/framework-preset-react-docs.test.ts
  app/react/src/server/framework-preset-react-docs.ts
  app/svelte/preset.js
  app/svelte/src/server/options.ts
  app/svelte/src/server/preset.ts
  app/vue/preset.js
  app/vue/src/server/framework-preset-vue-docs.ts
  app/vue/src/server/options.ts
  app/vue/src/server/preset.ts
  app/vue3/preset.js
  app/vue3/src/server/framework-preset-vue3-docs.ts
  app/vue3/src/server/options.ts
  app/vue3/src/server/preset.ts
  app/web-components/preset.js
  app/web-components/src/server/framework-preset-web-components-docs.ts
  app/web-components/src/server/options.ts
  app/web-components/src/server/preset.ts
  examples/web-components-kitchen-sink/yarn.lock
  lib/docs-tools/README.md
  lib/docs-tools/src/hasDocsOrControls.ts
  lib/docs-tools/src/index.ts
  lib/node-logger/src/index.ts
Labels: feature request, addon: docs

#17638 Update the documentation with info on auto generating titles
  docs/configure/sidebar-and-urls.md
  docs/snippets/common/component-story-auto-title.js.mdx
  docs/snippets/common/component-story-configuration-custom.js.mdx
  docs/snippets/common/component-story-configuration.js.mdx
  docs/snippets/common/component-story-dynamic-title.js.mdx
Labels: documentation

#17716 fix : typo in props name
  docs/snippets/react/button-story-using-args.js.mdx
  docs/snippets/react/button-story-with-emojis.mdx.mdx
  docs/snippets/react/button-story-with-emojis.ts.mdx
Labels: documentation, patch

#17736 Chore: (Docs) Fix typo in preact snippets
  docs/snippets/preact/button-story-with-args.js.mdx
  docs/snippets/preact/your-component.js.mdx
Labels: documentation, patch

#17742 Fix binding of the `renderStoryToElement` passed to `DocsRender`
  lib/preview-web/src/DocsRender.ts
  lib/preview-web/src/PreviewWeb.tsx
Labels: bug

#17734 Chore: (Docs) Updates the env vars docs for sb env field
  docs/configure/environment-variables.md
  docs/snippets/common/my-component-env-var-config.js.mdx
  docs/snippets/common/my-component-env-var-config.mdx.mdx
  docs/snippets/common/storybook-main-env-field-config.js.mdx
Labels: documentation, patch

#17748 fix filesystem cache missing return
  lib/core-common/src/utils/file-cache.ts
Labels: bug

#17747 fix dts-localize script
  lib/core-common/src/utils/file-cache.ts
  scripts/dts-localize.ts
Labels: maintenance

#17765 Date control tests
  lib/components/src/controls/Date.test.ts
  lib/components/src/controls/Date.tsx
  lib/components/src/controls/helpers.test.ts
Labels: maintenance

#17764 Addon-docs/Vue: Add tests for sourceDecorator vnodeToString
  app/vue/src/client/docs/sourceDecorator.test.ts
Labels: maintenance, app: vue, addon: docs

#17726 Fix nesting issue for refs in sidebar component
  lib/api/src/index.tsx
  lib/ui/src/__tests__/index.test.ts
  lib/ui/src/components/sidebar/Sidebar.tsx
  lib/ui/src/components/sidebar/__tests__/Sidebar.test.tsx
  lib/ui/src/components/sidebar/__tests__/data.test.ts
  lib/ui/src/components/sidebar/data.ts
Labels: bug, composition

#17714 UI: Button for toggling addons panel
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/components/preview/tools/addons.tsx
Labels: feature request, ui

#17776 Chore: (Docs) Fixes the incorrect path in the snippets
  docs/snippets/html/button-story-with-args.js.mdx
  docs/snippets/html/button-story-with-args.ts.mdx
  docs/snippets/html/your-component.js.mdx
  docs/snippets/html/your-component.ts.mdx
  docs/snippets/preact/button-story.js.mdx
  docs/snippets/react/my-component-play-function-waitfor.ts.mdx
Labels: documentation, patch

#16467 UI: Fix brand logo layout shift
  lib/ui/src/components/sidebar/Heading.tsx
Labels: bug, ui, components

#16970 Add headers to enable SharedArrayBuffer in stories
  lib/core-server/src/dev-server.ts
Labels: feature request

#16992 First cut at documentation of project arg/argTypes for discussion
  docs/api/argtypes.md
  docs/snippets/common/button-story-project-args-theme.js.mdx
  docs/writing-stories/args.md
Labels: documentation, ci:matrix

#17785 Core: Ensure simultaneous first access to stories.json waits
  lib/core-server/src/utils/stories-json.test.ts
  lib/core-server/src/utils/stories-json.ts
Labels: bug, core

#17536 Controls: Add conditional controls
  addons/a11y/package.json
  addons/actions/package.json
  addons/backgrounds/package.json
  addons/controls/package.json
  addons/docs/docs/multiframework.md
  addons/docs/package.json
  addons/interactions/package.json
  addons/links/package.json
  addons/measure/package.json
  addons/outline/package.json
  addons/storyshots/storyshots-core/package.json
  addons/storyshots/storyshots-puppeteer/package.json
  app/angular/package.json
  app/html/package.json
  app/preact/package.json
  app/react/package.json
  app/server/package.json
  app/svelte/package.json
  app/vue/package.json
  app/vue3/package.json
  app/web-components/package.json
  docs/essentials/controls.md
  docs/snippets/common/component-story-conditional-controls-mutual-exclusion.js.mdx
  docs/snippets/common/component-story-conditional-controls-toggle.js.mdx
  docs/snippets/common/component-story-disable-controls.js.mdx
  docs/snippets/common/component-story-disable-controls.mdx.mdx
  examples/official-storybook/stories/addon-controls.stories.tsx
  examples/web-components-kitchen-sink/yarn.lock
  lib/addons/package.json
  lib/api/package.json
  lib/api/src/index.tsx
  lib/cli/src/versions.ts
  lib/client-api/package.json
  lib/codemod/package.json
  lib/components/package.json
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
  lib/components/src/blocks/ArgsTable/types.ts
  lib/core-client/package.json
  lib/core-server/package.json
  lib/csf-tools/package.json
  lib/docs-tools/package.json
  lib/preview-web/package.json
  lib/source-loader/package.json
  lib/store/package.json
  lib/store/src/csf/prepareStory.test.ts
  lib/store/src/csf/prepareStory.ts
  yarn.lock
Labels: feature request, args, addon: controls

#17778 Build: Add main overrides to e2e config and test runner
  .circleci/config.yml
  lib/cli/src/repro-generators/configs.ts
  lib/cli/src/repro-generators/scripts.ts
  scripts/run-e2e.ts
  scripts/verdaccio.yaml
Labels: maintenance

#17746 SyntaxHighlighter: Add prettier for code formatting
  addons/docs/src/blocks/Source.tsx
  addons/docs/src/blocks/SourceContainer.tsx
  addons/storysource/package.json
  app/angular/package.json
  app/angular/src/client/docs/sourceDecorator.ts
  app/vue/package.json
  app/vue/src/client/docs/sourceDecorator.ts
  lib/components/package.json
  lib/components/src/blocks/Source.tsx
  lib/components/src/index.ts
  lib/components/src/syntaxhighlighter/formatter.test.js
  lib/components/src/syntaxhighlighter/formatter.test.ts
  lib/components/src/syntaxhighlighter/formatter.ts
  lib/components/src/syntaxhighlighter/lazy-syntaxhighlighter.tsx
  lib/components/src/syntaxhighlighter/syntaxhighlighter-types.ts
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
  yarn.lock
Labels: dependencies, compatibility with other tools, performance issue, addon: docs

#17753 UI: Wait 100ms before showing spinner and fix story overlaying it
  examples/official-storybook/stories/core/loaders.stories.js
  examples/official-storybook/stories/core/rendering.stories.js
  lib/core-common/templates/base-preview-head.html
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/WebView.ts
Labels: ui, performance issue, on-demand store

#17713 Add contributing instructions to PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#17633 Angular: Fix multiple calls of Input setter
  app/angular/src/client/preview/angular-beta/StorybookModule.test.ts
  app/angular/src/client/preview/angular-beta/StorybookWrapperComponent.ts
Labels: bug, patch

#17812 Replace setGlobalConfig with setProjectAnnotations
  app/react/src/client/testing/index.ts
  examples/cra-ts-essentials/.storybook/main.ts
  examples/cra-ts-essentials/package.json
  examples/cra-ts-essentials/src/setupTests.ts
  examples/cra-ts-essentials/src/stories/0-Welcome.stories.tsx
  examples/cra-ts-essentials/src/stories/1-Button.stories.tsx
  examples/cra-ts-essentials/src/stories/testing-react/components/AccountForm.stories.tsx
  examples/cra-ts-essentials/src/stories/testing-react/components/Button.stories.tsx
  examples/cra-ts-essentials/src/stories/testing-react/components/Button.test.tsx
  lib/store/src/csf/testing-utils/index.ts
Labels: cleanup

#17815 add a feature flag for enabling crossOriginIsolated
  lib/core-common/src/types.ts
  lib/core-server/src/dev-server.ts
Labels: bug

#17820 add back CacheProvider from emotion to lib/theming
  lib/theming/src/index.ts
Labels: bug

#17826 add setup-node version for danger
  .github/workflows/danger-js.yml
Labels: maintenance

#17829 CLI: Add automigration to `@storybook/builder-vite`
  MIGRATION.md
  lib/cli/src/automigrate/fixes/builder-vite.test.ts
  lib/cli/src/automigrate/fixes/builder-vite.ts
  lib/cli/src/automigrate/fixes/index.ts
Labels: feature request, cli, vite

#17837 switch to use medium+
  .circleci/config.yml
Labels: maintenance

#17799 Build: Add weekly check for broken markdown links
  .github/workflows/cron-weekly.yml
  .github/workflows/markdown-link-check-config.json
Labels: maintenance

#17830 CLI: Fix vite/jest issue with mocked global
  lib/cli/src/generators/baseGenerator.ts
  lib/cli/src/project_types.ts
  lib/core-server/src/utils/get-manager-builder.ts
Labels: bug, cli, vite

#17834 Webpack: Expand version ranges of webpack in the apps (same as app/react)
  app/angular/package.json
  app/html/package.json
  app/preact/package.json
  app/svelte/package.json
  app/vue/package.json
  app/vue3/package.json
  yarn.lock
Labels: bug, babel / webpack, app: vue, app: angular, app: html, app: svelte, app: preact, app: vue3, webpack5

#17840 Build: Swap order of e2e tests around
  addons/docs/package.json
  cypress/generated/basic.spec.ts
  cypress/support/commands.js
  yarn.lock
Labels: maintenance, run e2e extended test suite
