Repository storybookjs/storybook, pull requests merged in 2022-05, with the labels that each got.

#18109 Examples: Update example to restore 6.4 auto-title behavior in UI
  MIGRATION.md
  examples/react-ts/.storybook/manager.js
  examples/react-ts/package.json
  lib/api/src/lib/stories.ts
  lib/api/src/tests/stories.test.js
  lib/ui/src/components/sidebar/__tests__/data.test.ts
  yarn.lock
Labels: maintenance, csf3

#18125 Core: Fix telemetry project root detection
  lib/telemetry/package.json
  lib/telemetry/src/anonymous-id.ts
  lib/telemetry/src/get-monorepo-type.test.ts
  lib/telemetry/src/get-monorepo-type.ts
  lib/telemetry/src/storybook-metadata.ts
  yarn.lock
Labels: bug, core

#18124 Controls: Fix URL deserialization for argTypes with mapping
  examples/react-ts/src/__snapshots__/storyshots.test.ts.snap
  examples/react-ts/src/button.stories.tsx
  examples/react-ts/src/button.tsx
  lib/store/src/args.test.ts
  lib/store/src/args.ts
Labels: bug, core, args, addon: controls

#18127 UI: Externalize `react-syntax-highlighter` from components
  lib/components/package.json
Labels: bug, ui

#17983 feat(#16235): display a11y issues number in addon tab title
  addons/a11y/src/components/A11YPanel.test.tsx
  addons/a11y/src/components/A11yContext.test.tsx
  addons/a11y/src/components/A11yContext.tsx
  addons/a11y/src/manager.test.tsx
  addons/a11y/src/manager.tsx
Labels: feature request, accessibility, addon: a11y

#17989 fix(#16232): use a11y params > element properly
  addons/a11y/src/a11yRunner.ts
  examples/official-storybook/stories/addon-a11y/parameters.stories.js
Labels: bug, addon: a11y

#18129 Telemetry: Add safecheck for crash reports
  lib/telemetry/src/index.ts
Labels: bug, core, telemetry

#18130 Addon-docs: Fix Canvas block CURRENT_SELECTION handling
  addons/docs/src/blocks/Canvas.tsx
Labels: bug, patch, addon: docs, block: other

#18106 UI: Add a parent level toolbar exclusion key for tabs
  docs/configure/features-and-behavior.md
  lib/api/src/modules/layout.ts
  lib/api/src/modules/url.ts
  lib/ui/src/app.stories.tsx
  lib/ui/src/components/layout/app.mockdata.tsx
  lib/ui/src/components/preview/preview.mockdata.tsx
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/components/preview/utils/types.tsx
Labels: feature request, ui

#18133 Core: Fix anonymous ID generation
  lib/telemetry/src/anonymous-id.ts
Labels: bug, core, telemetry

#18141 CLI: Update Introduction.stories.mdx template to be MDX2-friendly
  lib/cli/src/frameworks/common/Introduction.stories.mdx
Labels: maintenance, cli, patch, mdx

#18135 Controls: Fix undefined args handling
  examples/official-storybook/stories/core/args.stories.js
  lib/store/src/args.test.ts
  lib/store/src/args.ts
Labels: bug, core, args, addon: controls

#18149 Remove jest from cli peerDependencies
  lib/cli/package.json
  yarn.lock
Labels: dependencies, cli

#18167 add telemetry disclosure on the install, upgrade and CLI pages
  docs/api/cli-options.md
  docs/configure/upgrading.md
  docs/get-started/install.md
Labels: documentation

#18158 Components: Fix race conditions in SyntaxHighlighter
  lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: bug, components, block: source

#18173 Fix typo in Source documentation
  docs/writing-docs/doc-block-source.md
Labels: documentation, patch

#17724 CSF3: Add title prefix support for stories with custom titles
  MIGRATION.md
  examples/official-storybook/main.ts
  examples/official-storybook/stories/title/AutoTitle.stories.js
  examples/official-storybook/stories/title/CustomTitle.stories.js
  examples/react-ts/.storybook/main.ts
  examples/react-ts/src/__snapshots__/storyshots.test.ts.snap
  examples/react-ts/src/title/AutoTitle.stories.js
  examples/react-ts/src/title/CustomTitle.stories.js
  lib/client-api/src/StoryStoreFacade.ts
  lib/codemod/src/transforms/csf-2-to-3.ts
  lib/core-client/src/preview/start.test.ts
  lib/core-server/src/utils/StoryIndexGenerator.ts
  lib/core-server/src/utils/update-check.ts
  lib/csf-tools/src/CsfFile.test.ts
  lib/csf-tools/src/CsfFile.ts
  lib/store/src/autoTitle.test.ts
  lib/store/src/autoTitle.ts
Labels: feature request, csf3

#18131 API: Deprecate isToolshown, rename to showToolbar
  MIGRATION.md
  docs/addons/addons-api.md
  docs/configure/features-and-behavior.md
  docs/snippets/common/storybook-config-layout.js.mdx
  lib/api/src/index.tsx
  lib/api/src/modules/layout.ts
  lib/api/src/tests/layout.test.js
  lib/ui/src/app.stories.tsx
  lib/ui/src/components/layout/app.mockdata.tsx
  lib/ui/src/components/layout/container.tsx
  lib/ui/src/components/layout/mobile.tsx
  lib/ui/src/components/preview/preview.mockdata.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/utils/types.tsx
  lib/ui/src/containers/menu.tsx
  lib/ui/src/containers/sidebar.tsx
Labels: api: addons, ui, maintenance

#18023 Docs2: Refactor manager to use new index data
  addons/storysource/src/StoryPanel.tsx
  lib/api/src/index.tsx
  lib/api/src/initial-state.ts
  lib/api/src/lib/merge.ts
  lib/api/src/lib/stories.ts
  lib/api/src/modules/addons.ts
  lib/api/src/modules/provider.ts
  lib/api/src/modules/refs.ts
  lib/api/src/modules/stories.ts
  lib/api/src/modules/url.ts
  lib/api/src/tests/addons.test.js
  lib/api/src/tests/stories.test.ts
  lib/api/src/tests/url.test.js
  lib/ui/src/components/preview/preview.mockdata.tsx
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/components/preview/utils/types.tsx
  lib/ui/src/components/sidebar/Explorer.stories.tsx
  lib/ui/src/components/sidebar/RefIndicator.tsx
  lib/ui/src/components/sidebar/Search.stories.tsx
  lib/ui/src/components/sidebar/Search.tsx
  lib/ui/src/components/sidebar/SearchResults.stories.tsx
  lib/ui/src/components/sidebar/SearchResults.tsx
  lib/ui/src/components/sidebar/Sidebar.stories.tsx
  lib/ui/src/components/sidebar/Sidebar.tsx
  lib/ui/src/components/sidebar/Tree.stories.tsx
  lib/ui/src/components/sidebar/Tree.tsx
  lib/ui/src/components/sidebar/__tests__/Sidebar.test.tsx
  lib/ui/src/components/sidebar/__tests__/data.test.ts
  lib/ui/src/components/sidebar/data.ts
  lib/ui/src/components/sidebar/mockdata.large.ts
  lib/ui/src/components/sidebar/mockdata.ts
  lib/ui/src/components/sidebar/utils.test.js
  lib/ui/src/components/sidebar/utils.ts
  lib/ui/src/containers/preview.tsx
  lib/ui/src/index.tsx
Labels: ui, maintenance

#18099 Docs2: Handle new docs entries in the preview
  addons/docs/src/blocks/DocsContext.ts
  addons/docs/src/blocks/DocsRenderer.tsx
  addons/docs/src/blocks/Meta.tsx
  addons/docs/src/blocks/Story.tsx
  addons/docs/src/blocks/index.ts
  addons/docs/src/blocks/useStory.ts
  addons/docs/src/preview.ts
  examples/react-ts/src/docs2/MetaOf.docs.mdx
  lib/core-client/src/preview/start.test.ts
  lib/preview-web/package.json
  lib/preview-web/src/DocsRender.ts
  lib/preview-web/src/NoDocs.tsx
  lib/preview-web/src/PreviewWeb.integration.test.ts
  lib/preview-web/src/PreviewWeb.mockdata.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/StoryRender.ts
  lib/preview-web/src/renderDocs.tsx
  lib/preview-web/src/types.ts
  lib/store/src/StoryIndexStore.test.ts
  lib/store/src/StoryIndexStore.ts
  lib/store/src/StoryStore.test.ts
  lib/store/src/StoryStore.ts
  lib/store/src/csf/normalizeStory.test.ts
  lib/store/src/csf/normalizeStory.ts
  lib/store/src/csf/prepareStory.test.ts
  lib/store/src/csf/prepareStory.ts
  lib/store/src/types.ts
  scripts/jest.init.ts
  yarn.lock
Labels: maintenance, core, addon: docs, mdx

#18153 Chore: (Docs) Adds Storybook builder documentation
  docs/addons/writing-presets.md
  docs/builders/builder-api.md
  docs/builders/overview.md
  docs/builders/storybook-builder-workflow.png
  docs/builders/storybook-builders.png
  docs/builders/vite.md
  docs/builders/webpack.md
  docs/faq.md
  docs/get-started/setup.md
  docs/sharing/storybook-composition.md
  docs/snippets/common/storybook-builder-api-build-server.ts.mdx
  docs/snippets/common/storybook-builder-api-configuration-options.ts.mdx
  docs/snippets/common/storybook-builder-api-dev-server.ts.mdx
  docs/snippets/common/storybook-builder-api-interface.ts.mdx
  docs/snippets/common/storybook-builder-api-mdx.ts.mdx
  docs/snippets/common/storybook-builder-api-preview-exports.ts.mdx
  docs/snippets/common/storybook-builder-api-shutdown-server.ts.mdx
  docs/snippets/common/storybook-vite-builder-aliasing.js.mdx
  docs/snippets/common/storybook-vite-builder-config-env.js.mdx
  docs/snippets/common/storybook-vite-builder-error-optimized.js.mdx
  docs/snippets/common/storybook-vite-builder-install.npm.js.mdx
  docs/snippets/common/storybook-vite-builder-install.yarn.js.mdx
  docs/snippets/common/storybook-vite-builder-register.js.mdx
  docs/snippets/common/storybook-vite-builder-svelte-plugin.js.mdx
  docs/snippets/common/storybook-vite-builder-ts-configure.ts.mdx
  docs/toc.js
  docs/writing-docs/docs-page.md
  docs/writing-docs/mdx.md
Labels: documentation, patch

#18180 Chore: (Docs) test runner fix broken link
  docs/writing-tests/test-runner.md
Labels: documentation

#18164 Upgrade to telejson 6
  addons/actions/package.json
  app/angular/package.json
  examples/angular-cli/package.json
  lib/api/package.json
  lib/channel-postmessage/package.json
  lib/channel-websocket/package.json
  lib/core-common/package.json
  lib/core-server/package.json
  lib/manager-webpack4/package.json
  lib/manager-webpack5/package.json
  yarn.lock
Labels: dependencies, security

#18185 Composition: Fix metadata.json incorrectly overriding main.js refs versions
  lib/api/src/modules/refs.ts
  lib/api/src/tests/refs.test.js
Labels: bug, core, linear

#18187 Update Vite builder docs a bit
  docs/builders/vite.md
  docs/snippets/common/storybook-builder-api-dev-server.ts.mdx
  docs/snippets/common/storybook-vite-builder-aliasing.js.mdx
  docs/snippets/common/storybook-vite-builder-react-docgen.js.mdx
Labels: documentation, patch

#18015 Fixed PnP compatibility for bundled components package
  lib/components/package.json
  scripts/bundle-package.ts
Labels: dependencies

#18004 Core: Make renderers presets (2/N)
  app/html/src/server/framework-preset-html-docs.ts
  app/html/src/server/framework-preset-html.ts
  app/html/src/server/preset.ts
  app/preact/src/server/framework-preset-preact.ts
  app/react/src/server/framework-preset-react-docs.ts
  app/react/src/server/preset.ts
  app/server/src/server/framework-preset-server.ts
  app/svelte/src/server/framework-preset-svelte-docs.ts
  app/svelte/src/server/framework-preset-svelte.ts
  app/svelte/src/server/preset.ts
  app/vue/src/server/framework-preset-vue-docs.ts
  app/vue/src/server/framework-preset-vue.ts
  app/vue/src/server/preset.ts
  app/vue3/src/server/framework-preset-vue3-docs.ts
  app/vue3/src/server/framework-preset-vue3.ts
  app/vue3/src/server/preset.ts
  app/web-components/src/server/framework-preset-web-components-docs.ts
  app/web-components/src/server/framework-preset-web-components.ts
  app/web-components/src/server/preset.ts
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-dev-posix
  lib/core-server/src/__snapshots__/cra-ts-essentials_preview-prod-posix
  lib/core-server/src/__snapshots__/html-kitchen-sink_preview-dev-posix
  lib/core-server/src/__snapshots__/html-kitchen-sink_preview-prod-posix
  lib/core-server/src/__snapshots__/vue-3-cli_preview-dev-posix
  lib/core-server/src/__snapshots__/vue-3-cli_preview-prod-posix
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-dev-posix
  lib/core-server/src/__snapshots__/web-components-kitchen-sink_preview-prod-posix
  renderers/html/preview.js
  renderers/html/src/config.ts
  renderers/html/src/preview/config.ts
  renderers/preact/preview.js
  renderers/react/preview.js
  renderers/react/src/config.ts
  renderers/react/src/preview/config.ts
  renderers/server/preview.js
  renderers/svelte/preview.js
  renderers/svelte/src/config.ts
  renderers/svelte/src/preview/config.ts
  renderers/vue/preview.js
  renderers/vue/src/config.ts
  renderers/vue/src/preview/config.ts
  renderers/vue3/preview.js
  renderers/vue3/src/config.ts
  renderers/vue3/src/preview/config.ts
  renderers/web-components/preview.js
  renderers/web-components/src/config.ts
  renderers/web-components/src/preview/config.ts
Labels: maintenance

#18200 Chore: (Docs) Adds missing info to telemetry
  docs/configure/telemetry.md
Labels: documentation

#18215 Chore: (Docs) Minor fixes to snippets and docs
  docs/configure/overview.md
  docs/snippets/common/storybook-storyloading-with-custom-object.js.mdx
Labels: documentation, patch

#18080 Chore: (DOCS) Address broken links in monorepo
  MAINTAINERS.md
  MIGRATION.md
  README.md
  addons/storyshots/storyshots-core/README.md
  docs/addons/install-addons.md
  docs/addons/introduction.md
  docs/configure/overview.md
  docs/configure/upgrading.md
  docs/essentials/introduction.md
  docs/faq.md
  lib/components/src/blocks/DocsPageExampleCaption.md
Labels: documentation, patch

#18214 Chore: (Docs) Adds CSF 3.0 docs on auto title feature
  docs/configure/sidebar-and-urls.md
  docs/snippets/common/component-story-auto-title.csf3-story.js.mdx
  docs/snippets/common/component-story-auto-title.js.mdx
  docs/snippets/common/component-story-configuration.js.mdx
  docs/snippets/common/storybook-csf-3-auto-title-redundant.js.mdx
  docs/snippets/common/storybook-main-auto-title-custom.js.mdx
  docs/snippets/common/storybook-main-configuration-src-dir.main-js.js.mdx
  docs/snippets/common/storybook-manager-render-label-stories.js.mdx
Labels: documentation

#18208 Vue3: fix CSF3 implicit render function when storyStoreV7 is enabled
  app/vue3/src/client/preview/config.ts
Labels: bug, app: vue3

#18209 Vue: map args correctly in CSF3 implicit render function
  app/vue/src/client/preview/config.ts
  app/vue/src/client/preview/render.ts
  examples/vue-cli/src/button/Button.stories.ts
  examples/vue-cli/src/button/Button.vue
Labels: bug, app: vue

#18196 Cleanup noise from unit tests
  app/angular/setup-jest.ts
  app/angular/src/builders/build-storybook/index.spec.ts
  app/angular/src/builders/start-storybook/index.spec.ts
  app/angular/src/client/preview/angular-beta/RendererFactory.test.ts
  app/angular/src/server/__mocks-ng-workspace__/with-lib/projects/pattern-lib/tsconfig.lib.json
  app/angular/src/server/__mocks-ng-workspace__/without-projects-entry/projects/pattern-lib/tsconfig.lib.json
  examples/angular-cli/jest-config/setup.ts
  examples/angular-cli/jest.config.js
Labels: maintenance

#18003 feat(#15866): % of users in a11y simulation tool
  addons/a11y/src/components/VisionSimulator.test.tsx
  addons/a11y/src/components/VisionSimulator.tsx
Labels: feature request, accessibility, addon: a11y, needs followup

#18022 Update: [#17934] CLI docs
  docs/get-started/install.md
  docs/get-started/installation-command-section/angular.mdx
  docs/get-started/installation-command-section/ember.mdx
  docs/get-started/installation-command-section/html.mdx
  docs/get-started/installation-command-section/preact.mdx
  docs/get-started/installation-command-section/react.mdx
  docs/get-started/installation-command-section/svelte.mdx
  docs/get-started/installation-command-section/vue.mdx
  docs/get-started/installation-command-section/web-components.mdx
  lib/cli/src/automigrate/fixes/webpack5.ts
  lib/cli/src/automigrate/index.ts
  lib/core-server/src/utils/update-check.ts
Labels: documentation, patch

#18108 Web-components: Fix cleaning Lit Expression comments
  app/web-components/src/client/docs/sourceDecorator.test.ts
  app/web-components/src/client/docs/sourceDecorator.ts
Labels: bug, addon: docs, app: web-components, block: source, needs followup

#18231 Controls: Fix reset button broken for !undefined URL values
  lib/preview-web/src/Preview.tsx
  lib/preview-web/src/PreviewWeb.test.ts
Labels: bug, addon: controls

#18246 Chore: (DOCS) Adds MDX 2 documentation
  docs/configure/overview.md
  docs/faq.md
  docs/snippets/common/storybook-main-enable-mdx2.js.mdx
  docs/snippets/common/storybook-mdx2-install.npm.js.mdx
  docs/snippets/common/storybook-mdx2-install.yarn.js.mdx
  docs/writing-docs/mdx.md
Labels: documentation

#18248 ArgsTable: Gracefully handle conditional args failures
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
Labels: bug, addon: controls

#18157 security: update x-default-browser
  lib/core-client/src/typings.d.ts
  lib/core-server/package.json
  lib/core-server/src/utils/open-in-browser.ts
  lib/core-server/typings.d.ts
  lib/manager-webpack4/typings.d.ts
  lib/manager-webpack5/typings.d.ts
  yarn.lock
Labels: dependencies, patch, security

#18259 Core: Fix get-monorepo-type when no package.json at repo root
  lib/telemetry/src/get-monorepo-type.ts
Labels: bug, patch, core, linear, telemetry

#18270 Revert "security: update x-default-browser"
  lib/core-client/src/typings.d.ts
  lib/core-server/package.json
  lib/core-server/src/utils/open-in-browser.ts
  lib/core-server/typings.d.ts
  lib/manager-webpack4/typings.d.ts
  lib/manager-webpack5/typings.d.ts
  yarn.lock
Labels: bug, patch

#18274 chore: fix jest 27 in angular e2e modern inline rendering config
  lib/cli/src/repro-generators/configs.ts
Labels: maintenance, patch

#18285 Core: Use correct framework version in telemetry
  lib/core-common/src/utils/get-storybook-info.ts
  lib/telemetry/src/storybook-metadata.ts
Labels: bug, patch, telemetry

#18284 Webpack5: Apply named exports order logic for stories only
  app/react/src/server/framework-preset-react-docs.ts
  lib/builder-webpack5/src/presets/preview-preset.ts
Labels: bug, patch, webpack5

#18242 Chore: (Links Checker) configuration tweaks
  .github/workflows/markdown-link-check-config.json
Labels: maintenance

#18182 Core: Allow builders to be set in presets
  lib/core-server/src/build-dev.ts
  lib/core-server/src/build-static.ts
  lib/core-server/src/dev-server.ts
  lib/core-server/src/utils/get-builders.ts
  lib/core-server/src/utils/get-manager-builder.ts
  lib/core-server/src/utils/get-preview-builder.ts
Labels: maintenance, core

#18300 MDX: Upgrade csf-mdx libraries
  addons/docs/package.json
  examples/react-ts/.storybook/main.ts
  examples/react-ts/src/__snapshots__/storyshots.test.ts.snap
  lib/csf-tools/package.json
  yarn.lock
Labels: dependencies, patch, mdx

#18302 CLI: Fix automigration scripts
  lib/cli/src/automigrate/index.ts
  lib/cli/src/initiate.ts
Labels: bug, cli, patch

#18245 Chore: (Docs) Marks files for exclusion
  MIGRATION.md
  RELEASES.md
  examples/README.md
Labels: documentation

#18303 CLI: Improve texts for automigration
  lib/cli/src/automigrate/index.ts
Labels: maintenance, cli, patch

#18307 CSF: Fix auto-title crash on file ID and show warning
  lib/store/src/autoTitle.ts
Labels: bug, patch, core, csf3

#18305 CLI: Fix open in browser doesn't work in WSL
  lib/core-server/src/utils/open-in-browser.ts
Labels: bug, cli, patch

#18309 CLI: Fix "reset" script removing .idea directory and add "cleanup" script
  package.json
  scripts/bootstrap.js
  scripts/reset.js
  yarn.lock
Labels: maintenance

#18324 Fix not working link in cli-options.md
  docs/api/cli-options.md
Labels: documentation, patch

#18330 Core: Fix node 18 ip support
  lib/core-server/package.json
  yarn.lock
Labels: bug, patch, core

#18348 Chore: (Docs) Updates jest snippets to address jest 28
  docs/faq.md
  docs/snippets/common/storybook-test-runner-install.npm.js.mdx
  docs/snippets/common/storybook-test-runner-install.yarn.js.mdx
Labels: documentation, patch

#18345 documentation: Syntax error in vite builder docs
  docs/snippets/common/storybook-vite-builder-aliasing.js.mdx
Labels: documentation, patch

#18352 Fix link to typescript
  docs/builders/webpack.md
Labels: documentation, patch

#18353 [Fix] Broken code block storybook-main-enable-transcludemarkdown.js.mdx
  docs/snippets/common/storybook-main-enable-transcludemarkdown.js.mdx
Labels: documentation, patch

#18343 Addon-a11y: Skip flakey tests
  addons/a11y/src/components/VisionSimulator.test.tsx
Labels: maintenance, addon: a11y

#18355 Core: Add pluggable indexers
  addons/docs/src/preset.ts
  lib/core-common/src/types.ts
  lib/core-server/src/build-static.ts
  lib/core-server/src/dev-server.ts
  lib/core-server/src/presets/common-preset.ts
  lib/core-server/src/utils/StoryIndexGenerator.test.ts
  lib/core-server/src/utils/StoryIndexGenerator.ts
  lib/core-server/src/utils/stories-json.test.ts
  lib/csf-tools/index.cjs
  lib/csf-tools/index.d.ts
  lib/csf-tools/index.mjs
  lib/csf-tools/mdx.d.ts
  lib/csf-tools/mdx.js
  lib/csf-tools/package.json
  yarn.lock
Labels: feature request, api: addons, core

#18361 Turn off Emotion's warnings about potentially unsafe pseudo-selectors in SSR
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
  lib/components/src/blocks/Source.tsx
  lib/components/src/spaced/Spaced.tsx
  lib/components/src/tabs/tabs.tsx
  lib/ui/src/index.tsx
Labels: bug, ui

#18369 Fix lint warnings in `PreviewWeb` tests
  lib/preview-web/src/Preview.tsx
  lib/preview-web/src/PreviewWeb.integration.test.ts
  lib/preview-web/src/PreviewWeb.mockdata.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
Labels: maintenance

#18370 Preview: Default select to `viewMode` story
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
Labels: bug, patch, core

#18373 disable the CRA pnp test "for now"
  .circleci/config.yml
Labels: maintenance

#18379 Chore: (Docs) Adds spacing to prevent issues with the link for telemetry
  docs/get-started/install.md
Labels: documentation, patch

#18380 Fix global argTypes definition docs
  docs/snippets/common/button-story-project-args-theme.js.mdx
Labels: documentation, patch
