Repository storybookjs/storybook, pull requests merged in 2022-07, with the labels that each got.

#17034 (Theming) Replace references to `themes.normal` with `themes.light`
  addons/a11y/src/components/A11yContext.tsx
  addons/interactions/src/components/List.tsx
  addons/jest/src/components/Panel.tsx
  addons/jest/src/components/Result.tsx
  examples/official-storybook/stories/addon-a11y/highlight.stories.js
Labels: maintenance, patch

#18121 Fix homepage core-server
  lib/core-server/package.json
Labels: maintenance, core

#17935 Update Webpack Title
  lib/manager-webpack4/src/presets/manager-preset.ts
  lib/manager-webpack5/src/presets/manager-preset.ts
Labels: maintenance, linear

#16334 bug: silence unexpected control type enum for color matchers
  lib/store/src/inferControls.ts
Labels: bug, addon: controls

#17311 fix: set default theme according to preferred color scheme
  lib/api/src/modules/layout.ts
Labels: feature request, ui, theming

#18617 Future/base with next
  addons/a11y/src/components/A11yContext.tsx
  addons/interactions/README.md
  addons/interactions/src/components/List.tsx
  addons/jest/src/components/Panel.tsx
  addons/jest/src/components/Result.tsx
  addons/storyshots/storyshots-core/src/test-bodies.ts
  addons/storyshots/storyshots-puppeteer/package.json
  addons/storyshots/storyshots-puppeteer/src/config.ts
  addons/storysource/package.json
  docs/addons/writing-addons.md
  docs/builders/overview.md
  docs/builders/vite.md
  docs/configure/babel.md
  docs/configure/upgrading.md
  docs/contribute/code.md
  docs/contribute/how-to-reproduce.md
  docs/essentials/introduction.md
  docs/get-started/installation-problems/angular.mdx
  docs/get-started/installation-problems/ember.mdx
  docs/get-started/installation-problems/html.mdx
  docs/get-started/installation-problems/preact.mdx
  docs/get-started/installation-problems/react.mdx
  docs/get-started/installation-problems/svelte.mdx
  docs/get-started/installation-problems/vue.mdx
  docs/get-started/installation-problems/web-components.mdx
  docs/sharing/storybook-composition.md
  docs/snippets/common/gizmo-story-controls-customization.js.mdx
  docs/snippets/common/gizmo-story-controls-customization.mdx.mdx
  examples/official-storybook/stories/addon-a11y/highlight.stories.js
  examples/official-storybook/stories/addon-controls.stories.tsx
  lib/api/src/modules/layout.ts
  lib/blocks/src/blocks/ExternalDocsContainer.tsx
  lib/blocks/src/controls/Text.tsx
  lib/blocks/src/controls/types.ts
  lib/core-server/package.json
  lib/manager-webpack5/src/presets/manager-preset.ts
  lib/router/src/utils.test.ts
  lib/router/src/utils.ts
  lib/store/src/inferControls.ts
  lib/ui/src/components/layout/container.tsx
  lib/ui/src/components/layout/draggers.tsx
  renderers/react/src/docs/jsxDecorator.test.tsx
  renderers/react/src/docs/jsxDecorator.tsx
  yarn.lock
Labels: maintenance

#18277 Security: Update x-default-browser and fix issue with package.
  lib/core-client/src/typings.d.ts
  lib/core-server/package.json
  lib/core-server/src/utils/open-in-browser.ts
  lib/core-server/typings.d.ts
  lib/manager-webpack4/typings.d.ts
  lib/manager-webpack5/typings.d.ts
  yarn.lock
Labels: dependencies, security

#18253 Upgrade file-system-cache to 2.0.0 and remove custom types
  lib/core-common/package.json
  lib/core-common/src/types.ts
  lib/core-common/src/utils/file-cache.ts
  yarn.lock
Labels: dependencies

#18618 examples: improve HTML framework's generated typescript stories
  app/html/README.md
  lib/cli/src/frameworks/html/ts/Button.stories.ts
  lib/cli/src/frameworks/html/ts/Button.ts
  lib/cli/src/frameworks/html/ts/Header.stories.ts
  lib/cli/src/frameworks/html/ts/Page.stories.ts
  lib/cli/src/frameworks/html/ts/Page.ts
Labels: bug, typescript, app: html

#18609 Addon-docs: Include Vue methods in ArgsTable
  app/vue3/src/client/docs/extractArgTypes.ts
Labels: feature request, app: vue, addon: docs

#17485 fix: Vue example is missing a vue-template-compiler dependency
  examples/vue-kitchen-sink/package.json
  yarn.lock
Labels: maintenance

#17735 Core: Typing useArgs
  examples/official-storybook/stories/core/args.stories.tsx
  lib/addons/src/hooks.ts
Labels: maintenance, core, typescript

#18478 Components: Cleanup types
  lib/components/package.json
  lib/components/src/ScrollArea/ScrollArea.tsx
  lib/components/src/blocks/ArgsTable/ArgsTable.tsx
  lib/components/src/blocks/ArgsTable/SectionRow.tsx
  lib/components/src/blocks/ArgsTable/TabbedArgsTable.tsx
  lib/components/src/blocks/ColorPalette.tsx
  lib/components/src/blocks/DocsPage.tsx
  lib/components/src/blocks/IconGallery.tsx
  lib/components/src/blocks/Preview.tsx
  lib/components/src/blocks/Source.tsx
  lib/components/src/blocks/Story.tsx
  lib/components/src/controls/Color.tsx
  lib/components/src/controls/Object.tsx
  lib/components/src/controls/options/Options.tsx
  lib/components/src/form/field/field.tsx
  lib/components/src/placeholder/placeholder.tsx
  lib/components/src/spaced/Spaced.tsx
  lib/components/src/syntaxhighlighter/syntaxhighlighter-types.ts
  lib/components/src/tabs/tabs.tsx
  lib/components/src/tooltip/ListItem.tsx
  lib/components/src/tooltip/Tooltip.tsx
  lib/components/src/tooltip/WithTooltip.tsx
  yarn.lock
Labels: maintenance, components, typescript, needs followup

#17843 Ember: Remove global Ember usage
  app/ember/package.json
  app/ember/src/client/preview/render.ts
  yarn.lock
Labels: maintenance, app: ember

#16592 Interactions: Show exceptions by non-instrumented code in panel
  addons/interactions/src/Panel.test.ts
  addons/interactions/src/Panel.tsx
  addons/interactions/src/components/AccountForm/addon-interactions.stories.tsx
  addons/interactions/src/components/Interaction.stories.tsx
  addons/interactions/src/components/Interaction.tsx
  addons/interactions/src/components/InteractionsPanel.stories.tsx
  addons/interactions/src/components/InteractionsPanel.tsx
  addons/interactions/src/components/MethodCall.tsx
  addons/interactions/src/components/StatusBadge.stories.tsx
  addons/interactions/src/components/StatusBadge.tsx
  addons/interactions/src/components/StatusIcon.stories.tsx
  addons/interactions/src/components/StatusIcon.tsx
  addons/interactions/src/components/Subnav.stories.tsx
  addons/interactions/src/components/Subnav.tsx
  addons/interactions/src/components/TabStatus.tsx
  addons/interactions/src/mocks/index.ts
  addons/interactions/src/preset/preview.ts
  lib/core-events/src/index.ts
  lib/instrumenter/src/instrumenter.ts
  lib/preview-web/src/PreviewWeb.mockdata.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/StoryRender.ts
Labels: feature request, addon: interactions, linear

#18638 Future - prep for #18619
  lib/core-common/src/presets.ts
  lib/core-common/src/utils/interpret-require.ts
Labels: maintenance

#18637 Future - add a linter for .ejs files (our templates)
  package.json
  yarn.lock
Labels: maintenance

#18608 Future - dependencies: use `dequal` for equality checks
  addons/actions/package.json
  addons/actions/src/containers/ActionLogger/index.tsx
  addons/docs/package.json
  examples/web-components-kitchen-sink/yarn.lock
  lib/api/package.json
  lib/api/src/modules/globals.ts
  lib/api/src/modules/layout.ts
  lib/api/src/modules/url.ts
  lib/blocks/package.json
  lib/blocks/src/blocks/SourceContainer.tsx
  lib/client-api/package.json
  lib/components/package.json
  lib/router/package.json
  lib/router/src/utils.ts
  lib/store/package.json
  lib/store/src/args.ts
  yarn.lock
Labels: dependencies

#18642 Future - improve linting a bit
  lib/ui/package.json
  lib/ui/scripts/generate-exports-file.ts
  package.json
  yarn.lock
Labels: maintenance

#18647 Future - merge next into future/base
  docs/configure/overview.md
  frameworks/ember/package.json
  frameworks/ember/src/client/preview/render.ts
  lib/blocks/src/components/ArgsTable/ArgsTable.tsx
  lib/blocks/src/components/ArgsTable/SectionRow.tsx
  lib/blocks/src/components/ArgsTable/TabbedArgsTable.tsx
  lib/blocks/src/components/ColorPalette.tsx
  lib/blocks/src/components/DocsPage.tsx
  lib/blocks/src/components/IconGallery.tsx
  lib/blocks/src/components/Preview.tsx
  lib/blocks/src/components/Source.tsx
  lib/blocks/src/components/Story.tsx
  lib/blocks/src/controls/Color.tsx
  lib/blocks/src/controls/Object.tsx
  lib/blocks/src/controls/options/Options.tsx
  lib/components/package.json
  lib/components/src/ScrollArea/ScrollArea.tsx
  lib/components/src/form/field/field.tsx
  lib/components/src/placeholder/placeholder.tsx
  lib/components/src/spaced/Spaced.tsx
  lib/components/src/syntaxhighlighter/syntaxhighlighter-types.ts
  lib/components/src/tabs/tabs.tsx
  lib/components/src/tooltip/ListItem.tsx
  lib/components/src/tooltip/Tooltip.tsx
  lib/components/src/tooltip/WithTooltip.tsx
  yarn.lock
Labels: maintenance

#18377 Core: Fix builder stats typings to be optional
  docs/snippets/common/storybook-builder-api-interface.ts.mdx
  lib/core-common/src/types.ts
  lib/core-server/src/build-dev.ts
  lib/core-server/src/utils/get-builders.ts
Labels: bug, patch, core, typescript

#18251 fix(chore): add type guard for globalWindow
  lib/channel-postmessage/src/index.ts
Labels: bug, core

#18174 Svelte: Supports action auto configuration
  app/svelte/src/client/docs/extractArgTypes.test.ts
  app/svelte/src/client/docs/extractArgTypes.ts
  app/svelte/src/client/preview/render.ts
  app/svelte/templates/PreviewRender.svelte
  examples/svelte-kitchen-sink/src/stories/views/ButtonView.svelte
Labels: feature request, addon: actions, app: svelte

#18140 Angular: Fix compodoc with spaces in workspace root
  app/angular/src/builders/build-storybook/index.spec.ts
  app/angular/src/builders/start-storybook/index.spec.ts
  app/angular/src/builders/utils/run-compodoc.spec.ts
  app/angular/src/builders/utils/run-compodoc.ts
Labels: bug, app: angular, argtypes

#18255 chore: remove addon-actions from packages for install
  lib/cli/src/generators/baseGenerator.ts
Labels: bug, cli

#18649 Clarify use of .babelrc in typescript instructions
  docs/configure/overview.md
  docs/snippets/common/storybook-ts-config-babelrc.js.mdx
Labels: documentation, typescript

#18651 cleanup: remove webpack dependency
  lib/core-client/package.json
  lib/core-common/package.json
  yarn.lock
Labels: dependencies

#18573 Addon-docs: Add docs index configuration via main.js
  addons/docs/src/preset.ts
  lib/core-common/src/types.ts
  lib/core-server/src/build-static.ts
  lib/core-server/src/core-presets.test.ts
  lib/core-server/src/dev-server.ts
  lib/core-server/src/utils/StoryIndexGenerator.test.ts
  lib/core-server/src/utils/StoryIndexGenerator.ts
  lib/core-server/src/utils/stories-json.test.ts
Labels: maintenance, addon: docs

#18619 Core: Async load presets, replace interpret with esbuild-register
  lib/builder-manager/package.json
  lib/components/src/syntaxhighlighter/formatter.test.ts
  lib/core-common/package.json
  lib/core-common/src/presets.test.ts
  lib/core-common/src/presets.ts
  lib/core-common/src/utils/interpret-files.ts
  lib/core-common/src/utils/interpret-require.ts
  lib/core-server/src/build-dev.ts
  lib/core-server/src/build-static.ts
  lib/core-server/src/core-presets.test.ts
  package.json
  yarn.lock
Labels: maintenance, core

#18664 fix dts-localize script for windows
  scripts/dts-localize.ts
Labels: maintenance

#18650 Mention import.meta.env for vite builder
  docs/configure/environment-variables.md
Labels: documentation, patch, vite

#18645 Svelte: Make `svelte-loader` optional dependency
  app/svelte/package.json
  yarn.lock
Labels: maintenance, patch, app: svelte

#18648 bug: always create main with cjs extension
  lib/cli/src/generators/SVELTE/index.ts
Labels: bug, app: svelte

#18665 Document `@storybook/instrumenter`
  lib/instrumenter/README.md
Labels: documentation

#18588 Index: Support `{ csfData as default }` CSF exports
  lib/csf-tools/src/CsfFile.test.ts
  lib/csf-tools/src/CsfFile.ts
Labels: bug, csf, story index

#18674 Instrumenter: `SyncPayload` type for `sync` event
  lib/instrumenter/src/instrumenter.ts
  lib/instrumenter/src/types.ts
Labels: maintenance, typescript

#18678 docs: Add SEO section to Publish docs page
  docs/sharing/publish-storybook.md
  docs/snippets/common/seo-description.html.mdx
  docs/snippets/common/seo-noindex.html.mdx
Labels: documentation, patch

#18682 docs: Update SEO documentation for `7.0` features
  docs/sharing/publish-storybook.md
  docs/snippets/common/seo-title.js.mdx
Labels: documentation

#18690 Chore: (Docs) Minor polish to the A11y docs
  docs/writing-tests/accessibility-testing.md
Labels: documentation, patch

#18635 Addon-dcos: Refactor DocsRender/Context
  examples/external-docs/.storybook/main.cjs
  examples/external-docs/components/Template.mdx
  examples/external-docs/components/button.mdx
  examples/external-docs/components/emoji-button.mdx
  examples/external-docs/pages/button.mdx
  examples/external-docs/pages/emoji-button.mdx
  lib/blocks/src/blocks/ArgsTable.tsx
  lib/blocks/src/blocks/Canvas.tsx
  lib/blocks/src/blocks/Description.tsx
  lib/blocks/src/blocks/DocsContainer.tsx
  lib/blocks/src/blocks/DocsPage.test.ts
  lib/blocks/src/blocks/DocsRenderer.tsx
  lib/blocks/src/blocks/ExternalDocsContainer.tsx
  lib/blocks/src/blocks/ExternalPreview.test.ts
  lib/blocks/src/blocks/ExternalPreview.ts
  lib/blocks/src/blocks/Meta.tsx
  lib/blocks/src/blocks/Primary.tsx
  lib/blocks/src/blocks/Props.tsx
  lib/blocks/src/blocks/Source.tsx
  lib/blocks/src/blocks/Story.tsx
  lib/blocks/src/blocks/Subtitle.tsx
  lib/blocks/src/blocks/Title.tsx
  lib/blocks/src/blocks/external/ExternalDocsContainer.tsx
  lib/blocks/src/blocks/external/ExternalDocsContext.ts
  lib/blocks/src/blocks/external/ExternalPreview.ts
  lib/blocks/src/blocks/index.ts
  lib/blocks/src/blocks/types.ts
  lib/preview-web/src/Preview.tsx
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/docs-context/DocsContext.ts
  lib/preview-web/src/docs-context/DocsContextProps.ts
  lib/preview-web/src/docs-context/DocsRenderFunction.ts
  lib/preview-web/src/index.ts
  lib/preview-web/src/render/AbstractDocsRender.ts
  lib/preview-web/src/render/Render.ts
  lib/preview-web/src/render/StandaloneDocsRender.ts
  lib/preview-web/src/render/TemplateDocsRender.ts
  lib/preview-web/src/types.ts
Labels: maintenance, addon: docs

#18677 Remove docs tab
  addons/docs/manager.js
  addons/docs/register.js
  addons/docs/src/manager.ts
  cypress/support/commands.js
  lib/api/src/index.tsx
  lib/api/src/lib/stories.ts
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.ts
  lib/blocks/src/blocks/Meta.tsx
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/store/src/StoryIndexStore.test.ts
  lib/store/src/StoryIndexStore.ts
  lib/ui/package.json
  lib/ui/src/app.stories.tsx
  lib/ui/src/app.tsx
  lib/ui/src/components/layout/app.mockdata.tsx
  lib/ui/src/components/layout/container.tsx
  lib/ui/src/components/layout/desktop.tsx
  lib/ui/src/components/layout/mobile.stories.tsx
  lib/ui/src/components/layout/mobile.tsx
  lib/ui/src/components/preview/FramesRenderer.tsx
  lib/ui/src/components/preview/preview.mockdata.tsx
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/preview/preview.tsx
  lib/ui/src/components/preview/toolbar.tsx
  lib/ui/src/components/preview/utils/types.tsx
  lib/ui/src/containers/preview.tsx
  lib/ui/src/index.tsx
  yarn.lock
Labels: feature request, ui, addon: docs

#18693 CLI: Fix addons register in RN template
  lib/cli/src/generators/REACT_NATIVE/template-csf/storybook/rn-addons.js
Labels: bug, cli, patch

#18582 chore: upgrade @storybook/jest in examples
  addons/interactions/package.json
  addons/interactions/src/components/AccountForm/addon-interactions.stories.tsx
  addons/interactions/src/components/Interaction/Interaction.stories.tsx
  examples/angular-cli/.storybook/tsconfig.json
  examples/angular-cli/package.json
  examples/angular-cli/src/stories/__snapshots__/welcome-storybook.stories.storyshot
  examples/angular-cli/src/stories/addons/actions/__snapshots__/addon-actions.stories.storyshot
  examples/angular-cli/src/stories/addons/backgrounds/__snapshots__/addon-background.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/addon-docs.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/__snapshots__/simple.stories.storyshot
  examples/angular-cli/src/stories/addons/docs/iframe/__snapshots__/iframe.stories.storyshot
  examples/angular-cli/src/stories/addons/interactions/addon-interactions.stories.ts
  examples/angular-cli/src/stories/addons/links/__snapshots__/addon-links.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/all-parameters.stories.storyshot
  examples/angular-cli/src/stories/core/parameters/__snapshots__/layout.parameters.stories.storyshot
  examples/angular-cli/src/stories/core/styles/__snapshots__/story-styles.stories.storyshot
  examples/angular-cli/src/stories/legacy/__snapshots__/component-in-story.stories.storyshot
  examples/angular-cli/src/stories/others/issues/__snapshots__/12009-unknown-component.stories.storyshot
  examples/official-storybook/package.json
  examples/svelte-kitchen-sink/package.json
  examples/vue-3-cli/package.json
  examples/vue-kitchen-sink/package.json
  examples/web-components-kitchen-sink/package.json
  package.json
  yarn.lock
Labels: maintenance

#17498 UI: Include full URL in the "Copy Canvas Link" button
  lib/ui/src/components/preview/tools/copy.tsx
Labels: bug, ui

#18714 CLI: Fix detection of type: module when initializing storybook
  lib/cli/src/generators/baseGenerator.ts
Labels: bug, cli, patch

#18728 Set other manager-side constants in build
  lib/builder-manager/src/index.ts
  lib/builder-manager/src/utils/template.ts
Labels: bug, core

#18711 Preview: Ensure docs container re-renders when globals change
  examples/official-storybook/stories/addon-docs/container-override.stories.mdx
  lib/preview-web/src/DocsRender.ts
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
Labels: bug, patch, addon: docs

#18729 Preview: Simplify docsMode
  lib/api/src/index.tsx
  lib/api/src/lib/stories.ts
  lib/api/src/modules/layout.ts
  lib/api/src/modules/refs.ts
  lib/api/src/modules/stories.ts
  lib/api/src/tests/layout.test.js
  lib/api/src/tests/stories.test.ts
  lib/ui/src/components/sidebar/Refs.tsx
  lib/ui/src/components/sidebar/Search.stories.tsx
  lib/ui/src/components/sidebar/Search.tsx
  lib/ui/src/components/sidebar/SearchResults.tsx
  lib/ui/src/components/sidebar/Sidebar.stories.tsx
  lib/ui/src/components/sidebar/Sidebar.tsx
  lib/ui/src/components/sidebar/Tree.stories.tsx
  lib/ui/src/components/sidebar/Tree.tsx
  lib/ui/src/components/sidebar/TreeNode.tsx
  lib/ui/src/components/sidebar/__tests__/Sidebar.test.tsx
  lib/ui/src/components/sidebar/__tests__/data.test.ts
  lib/ui/src/components/sidebar/data.ts
  lib/ui/src/components/sidebar/utils.ts
Labels: maintenance, addon: docs

#18709 Remove `AddContext` from mdx packages
  addons/docs/package.json
  yarn.lock
Labels: maintenance, addon: docs

#18708 Addon-docs: Move DocsRenderer back to addon-docs
  MIGRATION.md
  addons/docs/src/DocsRenderer.tsx
  addons/docs/src/index.ts
  addons/docs/src/preview.ts
  examples/external-docs/package.json
  examples/external-docs/pages/_app.js
  examples/official-storybook/stories/addon-docs/mdx.stories.js
  lib/blocks/package.json
  lib/blocks/src/blocks/Canvas.tsx
  lib/blocks/src/blocks/Docs.tsx
  lib/blocks/src/blocks/DocsContainer.tsx
  lib/blocks/src/blocks/DocsRenderer.tsx
  lib/blocks/src/blocks/Story.tsx
  lib/blocks/src/blocks/external/ExternalDocs.tsx
  lib/blocks/src/blocks/external/ExternalPreview.ts
  lib/blocks/src/blocks/index.ts
  renderers/react/src/docs/jsxDecorator.tsx
  yarn.lock
Labels: maintenance, addon: docs

#18730 Addon-docs: Localize channel to docs context
  examples/official-storybook/stories/addon-docs/mdx.stories.js
  lib/blocks/package.json
  lib/blocks/src/blocks/ArgsTable.tsx
  lib/blocks/src/blocks/DocsContainer.tsx
  lib/blocks/src/blocks/SourceContainer.tsx
  lib/blocks/src/blocks/enhanceSource.test.ts
  lib/blocks/src/blocks/enhanceSource.ts
  lib/blocks/src/blocks/external/ExternalDocsContext.ts
  lib/blocks/src/blocks/external/ExternalPreview.ts
  lib/blocks/src/blocks/mdx.tsx
  lib/preview-web/package.json
  lib/preview-web/src/Preview.tsx
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/docs-context/DocsContext.ts
  lib/preview-web/src/docs-context/DocsContextProps.ts
  lib/preview-web/src/render/StandaloneDocsRender.ts
  lib/preview-web/src/render/TemplateDocsRender.ts
  scripts/prepare/bundle.ts
  yarn.lock
Labels: maintenance, addon: docs

#18736 Don't run the docs spec in `react@18`
  cypress/generated/addon-docs.spec.ts
Labels: maintenance

#18772 Build addons/a11y with ts-up
  addons/a11y/manager.js
  addons/a11y/package.json
  addons/a11y/preview.js
  yarn.lock
Labels: maintenance

#18747 Preview: Fix standalone MDX files not HMR-ing
  lib/preview-web/src/PreviewWeb.test.ts
  lib/preview-web/src/PreviewWeb.tsx
  lib/preview-web/src/render/StandaloneDocsRender.ts
Labels: bug, addon: docs

#18762 Pass full docs options to manager
  jest.config.js
  lib/api/src/index.tsx
  lib/api/src/modules/refs.ts
  lib/api/src/modules/stories.ts
  lib/api/src/tests/stories.test.ts
  lib/api/src/typings.d.ts
  lib/builder-manager/src/index.ts
  lib/builder-manager/src/utils/data.ts
  lib/builder-manager/src/utils/template.ts
  lib/core-common/src/types.ts
  lib/core-server/src/presets/common-preset.ts
  lib/ui/src/app.stories.tsx
  lib/ui/src/components/preview/preview.stories.tsx
  lib/ui/src/components/sidebar/Explorer.stories.tsx
  lib/ui/src/components/sidebar/Refs.stories.tsx
  lib/ui/src/components/sidebar/Refs.tsx
  lib/ui/src/components/sidebar/Sidebar.stories.tsx
  lib/ui/src/components/sidebar/Tree.tsx
  lib/ui/src/components/sidebar/TreeNode.tsx
  lib/ui/src/globals/exports.ts
  lib/ui/src/index.tsx
Labels: bug, ui, addon: docs

#18785 Build: Use updated circleci node images
  .circleci/config.yml
Labels: maintenance

#18731 Core: clear addon cache directory before starting the manager
  code/lib/builder-manager/src/index.ts
  code/lib/core-server/src/core-presets.test.ts
Labels: bug, core

#18786 Build addons/controls with tsup
  code/addons/controls/manager.js
  code/addons/controls/package.json
Labels: maintenance

#18784 Generate addons/backgrounds with ts-up
  code/addons/backgrounds/manager.js
  code/addons/backgrounds/package.json
  code/addons/backgrounds/preview.js
Labels: maintenance

#18790 remove old scripts that are no longer used
  code/packs/README.md
  scripts/build-manager-config/main.js
  scripts/build-pack.sh
Labels: maintenance

#18763 Support DocsPage in v6 store
  code/cypress/helper.ts
  code/lib/api/src/lib/stories.ts
  code/lib/api/src/modules/refs.ts
  code/lib/api/src/modules/stories.ts
  code/lib/api/src/tests/stories.test.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/client-api/src/StoryStoreFacade.ts
Labels: feature request, core, addon: docs

#15564 Preact typescript pragma fix
  code/examples/preact-kitchen-sink/.eslintrc.js
  code/examples/preact-kitchen-sink/.storybook/main.ts
  code/examples/preact-kitchen-sink/src/Button.js
  code/examples/preact-kitchen-sink/src/React.js
  code/examples/preact-kitchen-sink/src/Welcome.js
  code/examples/preact-kitchen-sink/src/stories/addon-actions.stories.js
  code/examples/preact-kitchen-sink/src/stories/addon-backgrounds.stories.js
  code/examples/preact-kitchen-sink/src/stories/addon-links.stories.js
  code/examples/preact-kitchen-sink/src/stories/button.stories.js
  code/examples/preact-kitchen-sink/src/stories/react-compat.stories.js
  code/examples/preact-kitchen-sink/src/stories/test-cases/__snapshots__/test-component.stories.storyshot
  code/examples/preact-kitchen-sink/src/stories/test-cases/no-pragma.tsx
  code/examples/preact-kitchen-sink/src/stories/test-cases/test-component.stories.tsx
  code/examples/preact-kitchen-sink/src/stories/welcome.stories.js
  code/examples/preact-kitchen-sink/tsconfig.json
  code/presets/preact-webpack/src/index.ts
  scripts/.babelrc.js
Labels: bug, app: preact

#18787 feat: add next-repro CLI command
  .gitignore
  CONTRIBUTING.md
  code/package.json
  generate-repros.sh
  scripts/next-repro-generators/index.ts
  scripts/next-repro-generators/repro-config.yml
  scripts/next-repro-generators/utils/yarn.ts
  scripts/package.json
  scripts/typings.d.ts
  scripts/yarn.lock
Labels: maintenance

#17964 UI: Add preloading to stories highlighted in the sidebar
  code/lib/api/src/modules/channel.ts
  code/lib/api/src/modules/stories.ts
  code/lib/api/src/tests/stories.test.ts
  code/lib/core-events/src/index.ts
  code/lib/preview-web/src/PreviewWeb.test.ts
  code/lib/preview-web/src/PreviewWeb.tsx
  code/lib/ui/src/components/preview/preview.tsx
  code/lib/ui/src/components/sidebar/SearchResults.tsx
  code/lib/ui/src/components/sidebar/Tree.tsx
  code/lib/ui/src/components/sidebar/useHighlighted.ts
  code/lib/ui/src/globals/exports.ts
Labels: feature request, ui, on-demand store

#18806 disable normalization of package.json
  code/lib/core-common/package.json
  code/lib/core-common/src/types.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
  code/lib/telemetry/src/storybook-metadata.ts
  code/yarn.lock
Labels: bug

#18810 Chore: (Docs) Addons URLs updates
  code/addons/a11y/README.md
  code/addons/actions/README.md
  code/addons/backgrounds/README.md
  code/addons/controls/README.md
  code/addons/essentials/README.md
  code/addons/jest/README.md
  code/addons/storyshots/storyshots-core/README.md
  code/addons/storyshots/storyshots-puppeteer/README.md
  code/addons/storysource/README.md
  code/addons/toolbars/README.md
  code/addons/viewport/README.md
Labels: documentation

#18798 [CHANGED] core-event compiler to ts-up
  code/lib/core-events/package.json
Labels: maintenance

#18817 fix yarn build command
  scripts/build-package.js
Labels: maintenance

#18819 Docs broken links fixes
  docs/addons/addon-knowledge-base.md
  docs/addons/addon-types.md
  docs/addons/writing-presets.md
  docs/api/new-frameworks.md
  docs/builders/builder-api.md
  docs/configure/babel.md
  docs/configure/storybook-addons.md
  docs/contribute/how-to-contribute.md
  docs/faq.md
  docs/writing-tests/accessibility-testing.md
Labels: documentation, patch

#18816 fix(CLI): throw error on failure in sb init
  code/lib/cli/src/generate.ts
Labels: bug, cli, patch

#18737 React: Fix callback behavior in `react@18`
  code/cypress/generated/addon-docs.spec.ts
  code/renderers/react/src/render.tsx
Labels: bug, app: react
