Repository storybookjs/storybook, pull requests merged in 2023-07, with the labels that each got.

#22791 CSF-tools: Allow type checking in story title
  code/lib/csf-tools/src/CsfFile.ts
Labels: feature request, csf

#23284 Hygiene: Misc improvements
  code/addons/a11y/src/manager.test.tsx
  code/addons/actions/src/manager.tsx
  code/addons/controls/src/manager.tsx
  code/addons/jest/src/manager.tsx
  code/addons/storysource/src/manager.tsx
  code/lib/manager-api/src/modules/url.ts
  scripts/utils/options.ts
Labels: build

#23289 Release tooling: Keep redundant commits when cherry-picking
  scripts/release/pick-patches.ts
Labels: build

#23235 Release tooling: Update docs version files when releasing
  .github/workflows/publish.yml
  scripts/release/__tests__/write-changelog.test.ts
  scripts/release/write-changelog.ts
Labels: patch, build

#23299 Release tooling: Use repo root for path-sensitive operations
  .github/workflows/publish.yml
Labels: patch, build

#23111 Build tooling: Add stale-bot action
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/stale.yml
Labels: patch, build

#23202 Settings: Add What's new? page and remove release notes page
  code/addons/docs/src/typings.d.ts
  code/addons/storyshots-core/src/typings.d.ts
  code/builders/builder-manager/src/utils/template.ts
  code/frameworks/angular/src/typings.d.ts
  code/lib/cli/src/generate.ts
  code/lib/core-events/src/index.ts
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/typings.d.ts
  code/lib/core-server/src/utils/__tests__/release-notes.test.ts
  code/lib/core-server/src/utils/release-notes.ts
  code/lib/instrumenter/src/typings.d.ts
  code/lib/manager-api/src/index.tsx
  code/lib/manager-api/src/modules/notifications.ts
  code/lib/manager-api/src/modules/release-notes.ts
  code/lib/manager-api/src/modules/url.ts
  code/lib/manager-api/src/modules/versions.ts
  code/lib/manager-api/src/modules/whatsnew.ts
  code/lib/manager-api/src/tests/url.test.js
  code/lib/manager-api/src/tests/versions.test.js
  code/lib/manager-api/src/typings.d.ts
  code/lib/preview-api/src/typings.d.ts
  code/lib/types/src/modules/api.ts
  code/lib/types/src/modules/core-common.ts
  code/ui/manager/src/FakeProvider.tsx
  code/ui/manager/src/app.stories.tsx
  code/ui/manager/src/components/notifications/NotificationItem.tsx
  code/ui/manager/src/components/sidebar/Menu.stories.tsx
  code/ui/manager/src/containers/menu.tsx
  code/ui/manager/src/containers/sidebar.tsx
  code/ui/manager/src/globals/exports.ts
  code/ui/manager/src/settings/about.tsx
  code/ui/manager/src/settings/index.tsx
  code/ui/manager/src/settings/release_notes.stories.tsx
  code/ui/manager/src/settings/release_notes_page.tsx
  code/ui/manager/src/settings/typings.d.ts
  code/ui/manager/src/settings/whats_new.tsx
  code/ui/manager/src/settings/whats_new_page.tsx
  code/ui/manager/src/typings.d.ts
Labels: feature request, ui

#23305 Unit Tests: Fix tests on Windows
  code/lib/telemetry/src/get-framework-info.test.ts
Labels: build

#23306 CI: Remove Ubuntu/Mac Unit Tests on Github Actions
  .github/workflows/tests-unit.yml
Labels: patch, build

#23303 CI: Only run Storybook scoped packages via verdaccio
  scripts/utils/yarn.ts
Labels: build

#23292 Router: Support `RegExp` in `Route` component
  code/lib/router/src/router.tsx
  code/lib/router/src/utils.ts
Labels: maintenance, core

#23274 Yarn: Fix pnp package resolution on Windows
  code/lib/cli/package.json
  code/lib/cli/src/js-package-manager/Yarn2Proxy.ts
  code/yarn.lock
Labels: bug

#23166 SyntaxHighlighter: Expose registerLanguage
  code/ui/blocks/src/components/Source.tsx
  code/ui/components/src/syntaxhighlighter/lazy-syntaxhighlighter.tsx
  code/ui/components/src/syntaxhighlighter/syntaxhighlighter.stories.tsx
  code/ui/components/src/syntaxhighlighter/syntaxhighlighter.tsx
Labels: feature request, components

#23310 Update frameworks.md
  docs/configure/frameworks.md
Labels: documentation, patch

#23330 Yarn: Pin version of @yarnpkg packages to support Node 16
  code/lib/cli/package.json
  code/yarn.lock
Labels: bug

#23142 Addon-docs: Add opt-in table of contents
  code/addons/docs/template/stories/toc/basic.stories.ts
  code/addons/docs/template/stories/toc/custom-selector.stories.ts
  code/addons/docs/template/stories/toc/custom-title.stories.ts
  code/addons/docs/template/stories/toc/ignore-selector.stories.ts
  code/builders/builder-manager/src/index.ts
  code/ui/.storybook/preview.tsx
  code/ui/blocks/package.json
  code/ui/blocks/src/blocks/DocsContainer.tsx
  code/ui/blocks/src/components/DocsPage.tsx
  code/ui/blocks/src/components/TableOfContents.tsx
  code/yarn.lock
Labels: feature request, addon: docs

#23236 Fix location of kitchen sink example files
  code/frameworks/server-webpack5/README.md
Labels: documentation, patch

#23334 Revert "Revert "Addon-docs: Add opt-in table of contents""
  code/addons/docs/template/stories/toc/basic.stories.ts
  code/addons/docs/template/stories/toc/custom-selector.stories.ts
  code/addons/docs/template/stories/toc/custom-title.stories.ts
  code/addons/docs/template/stories/toc/ignore-selector.stories.ts
  code/builders/builder-manager/src/index.ts
  code/ui/.storybook/preview.tsx
  code/ui/blocks/package.json
  code/ui/blocks/src/blocks/DocsContainer.tsx
  code/ui/blocks/src/components/DocsPage.tsx
  code/ui/blocks/src/components/TableOfContents.tsx
  code/yarn.lock
Labels: build, ci:merged

#23288 UI: Improve tabs component, more type correct, allow for `FC` as title
  code/addons/a11y/src/manager.tsx
  code/addons/actions/src/manager.tsx
  code/addons/backgrounds/src/manager.tsx
  code/addons/controls/src/manager.tsx
  code/addons/jest/src/manager.tsx
  code/addons/measure/src/manager.tsx
  code/addons/outline/src/manager.tsx
  code/addons/storysource/src/manager.tsx
  code/addons/toolbars/src/manager.tsx
  code/addons/viewport/src/manager.tsx
  code/lib/manager-api/src/lib/addons.ts
  code/lib/types/src/modules/addons.ts
  code/lib/types/src/modules/api.ts
  code/ui/components/src/tabs/tabs.helpers.tsx
  code/ui/components/src/tabs/tabs.hooks.tsx
  code/ui/components/src/tabs/tabs.stories.tsx
  code/ui/components/src/tabs/tabs.tsx
  code/ui/manager/src/components/layout/app.mockdata.tsx
  code/ui/manager/src/components/panel/panel.stories.tsx
  code/ui/manager/src/components/panel/panel.tsx
  code/ui/manager/src/components/preview/preview.mockdata.tsx
  code/ui/manager/src/components/preview/preview.tsx
  code/ui/manager/src/components/preview/toolbar.tsx
  code/ui/manager/src/components/preview/tools/addons.tsx
  code/ui/manager/src/components/preview/tools/copy.tsx
  code/ui/manager/src/components/preview/tools/eject.tsx
  code/ui/manager/src/components/preview/tools/menu.tsx
  code/ui/manager/src/components/preview/tools/remount.tsx
  code/ui/manager/src/components/preview/tools/zoom.tsx
Labels: ui, maintenance

#23298 Addons: Improve code quality by using title as `FC` & sharing state via `useAddonState`
  code/addons/a11y/src/manager.test.tsx
  code/addons/a11y/src/manager.tsx
  code/addons/actions/src/manager.tsx
  code/addons/controls/src/manager.tsx
  code/addons/links/src/manager.ts
Labels: maintenance, addon: actions, addon: a11y, addon: controls

#23349 Build: Fix TOC stories for cra/default-js
  code/addons/docs/template/stories/toc/basic.stories.ts
  code/addons/docs/template/stories/toc/custom-selector.stories.ts
  code/addons/docs/template/stories/toc/custom-title.stories.ts
  code/addons/docs/template/stories/toc/ignore-selector.stories.ts
Labels: build, ci:daily

#23354 Yarn: Downgrade yarnpkg packages and support virtual files properly
  code/lib/cli/package.json
  code/lib/cli/src/js-package-manager/Yarn2Proxy.ts
  code/yarn.lock
Labels: bug, yarn

#23291 InteractionsAddon: Improve code quality by using title as `FC` & sharing state via `useAddonState`
  code/addons/interactions/src/Panel.tsx
  code/addons/interactions/src/components/InteractionsPanel.tsx
  code/addons/interactions/src/components/Subnav.tsx
  code/addons/interactions/src/manager.tsx
  code/e2e-tests/addon-interactions.spec.ts
  code/e2e-tests/preview-web.spec.ts
Labels: maintenance, addon: interactions

#23360 Docs: Addon designs updates for 7.0
  docs/sharing/design-integrations.md
  docs/snippets/common/storybook-figma-addon-install.npm.js.mdx
  docs/snippets/common/storybook-figma-addon-install.pnpm.js.mdx
  docs/snippets/common/storybook-figma-addon-install.yarn.js.mdx
  docs/snippets/common/storybook-main-figma-addon-register.js.mdx
  docs/snippets/common/storybook-main-figma-addon-register.ts.mdx
Labels: documentation, patch

#23350 Fix duplicate name for interface and function
  docs/snippets/react/simple-page-implementation.ts.mdx
Labels: documentation, patch

#23210 Next.js: Resolving compilation issues when using @nx/react/plugin/storybook with stories that contain SVGs
  code/frameworks/nextjs/src/images/webpack.ts
Labels: bug, patch, nextjs, ci:daily

#23378 Tests: Improve consistency and coverage of e2e tests
  code/e2e-tests/addon-interactions.spec.ts
  code/e2e-tests/manager.spec.ts
  code/e2e-tests/preview-web.spec.ts
Labels: build

#23380 Tests: Improve 2e2 test consistency
  code/e2e-tests/addon-actions.spec.ts
  code/e2e-tests/addon-backgrounds.spec.ts
  code/e2e-tests/addon-controls.spec.ts
  code/e2e-tests/addon-docs.spec.ts
  code/e2e-tests/addon-interactions.spec.ts
  code/e2e-tests/addon-viewport.spec.ts
  code/e2e-tests/framework-nextjs.spec.ts
  code/e2e-tests/json-files.spec.ts
  code/e2e-tests/manager.spec.ts
  code/e2e-tests/preview-web.spec.ts
Labels: build

#23357 Settings: New about page design
  code/ui/.storybook/main.ts
  code/ui/components/src/clipboard/ClipboardCode.tsx
  code/ui/components/src/index.ts
  code/ui/manager/package.json
  code/ui/manager/src/globals/exports.ts
  code/ui/manager/src/settings/about.stories.jsx
  code/ui/manager/src/settings/about.stories.tsx
  code/ui/manager/src/settings/about.tsx
  code/ui/manager/src/settings/about_page.tsx
  code/ui/manager/src/settings/whats_new.tsx
  code/yarn.lock
Labels: feature request, ui

#23331 Sandboxes: Add Angular 15 sandbox and drop Angular 14 sandbox
  code/lib/cli/src/sandbox-templates.ts
Labels: build

#21303 Manager: :fire: Zoom Element: remove css zoom
  code/ui/components/src/Zoom/ZoomElement.tsx
  code/ui/components/src/Zoom/ZoomIFrame.tsx
  code/ui/components/src/Zoom/browserSupportsCssZoom.ts
Labels: bug

#23383 Fix parallelism in CircleCI
  .circleci/config.yml
Labels: build, ci:merged

#23297 Release tooling: Use storybook-bot for commits and PRs
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  .github/workflows/publish.yml
  scripts/release/__tests__/generate-pr-description.test.ts
Labels: patch, build

#23179 Dependencies: Move `typescript` from devDependencies to peerDependencies
  code/frameworks/react-webpack5/package.json
  code/renderers/react/package.json
  code/yarn.lock
Labels: dependencies

#23340 Mdx: Update Configure.mdx
  code/frameworks/nextjs/template/cli/js/Configure.mdx
  code/frameworks/nextjs/template/cli/ts-3-8/Configure.mdx
  code/frameworks/nextjs/template/cli/ts-4-9/Configure.mdx
  code/lib/cli/rendererAssets/common/Configure.mdx
  code/lib/cli/rendererAssets/common/assets/accessibility.png
  code/lib/cli/rendererAssets/common/assets/accessibility.svg
  code/lib/cli/rendererAssets/common/assets/addon-library.png
  code/lib/cli/rendererAssets/common/assets/assets.jpg
  code/lib/cli/rendererAssets/common/assets/assets.png
  code/lib/cli/rendererAssets/common/assets/checkmark.svg
  code/lib/cli/rendererAssets/common/assets/chromatic.svg
  code/lib/cli/rendererAssets/common/assets/context.jpg
  code/lib/cli/rendererAssets/common/assets/context.png
  code/lib/cli/rendererAssets/common/assets/discord.svg
  code/lib/cli/rendererAssets/common/assets/docs.png
  code/lib/cli/rendererAssets/common/assets/document.svg
  code/lib/cli/rendererAssets/common/assets/figma-plugin.png
  code/lib/cli/rendererAssets/common/assets/figma.svg
  code/lib/cli/rendererAssets/common/assets/github.svg
  code/lib/cli/rendererAssets/common/assets/share.png
  code/lib/cli/rendererAssets/common/assets/styling.jpg
  code/lib/cli/rendererAssets/common/assets/styling.png
  code/lib/cli/rendererAssets/common/assets/testing.png
  code/lib/cli/rendererAssets/common/assets/theming.png
  code/lib/cli/rendererAssets/common/assets/tutorials.svg
  code/lib/cli/rendererAssets/common/assets/typography.svg
  code/lib/cli/rendererAssets/common/assets/youtube.svg
Labels: feature request, nextjs, ci:daily

#23336 Svelte-Webpack: Support Svelte v4
  code/frameworks/svelte-webpack5/package.json
  code/presets/svelte-webpack/package.json
  code/yarn.lock
Labels: dependencies, patch, svelte, ci:daily

#23381 Settings: Disable whatsnew notification UI
  code/lib/core-common/src/utils/get-storybook-info.ts
  code/lib/core-events/src/index.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/withTelemetry.ts
  code/lib/manager-api/src/modules/whatsnew.ts
  code/lib/telemetry/src/types.ts
  code/lib/types/src/modules/core-common.ts
  code/ui/manager/src/components/sidebar/Menu.stories.tsx
  code/ui/manager/src/containers/menu.tsx
  code/ui/manager/src/containers/sidebar.tsx
  code/ui/manager/src/globals/exports.ts
  code/ui/manager/src/settings/about.tsx
  code/ui/manager/src/settings/whats_new.tsx
  code/ui/manager/src/settings/whats_new_footer.stories.tsx
  code/ui/manager/src/settings/whats_new_page.tsx
Labels: feature request, core, ci:daily

#23395 Release tooling: Add notes to docs about releasing manually
  CONTRIBUTING/RELEASING.md
Labels: documentation

#23398 Settings: Fix dark mode for what's new page
  code/ui/manager/src/settings/whats_new.tsx
Labels: bug, ui, ci:normal

#23404 Angular: Enable prod mode when Storybook is built
  code/frameworks/angular/src/client/preview-prod.ts
  code/frameworks/angular/src/preset.ts
Labels: bug, ci:daily

#23406 DangerJS: Require either 'patch:no', 'patch:yes' or 'patch:done' label CHERRY-PICK
  scripts/dangerfile.ts
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/label-patches.ts
  scripts/release/pick-patches.ts
  scripts/release/unreleased-changes-exists.ts
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/write-changelog.ts
Labels: build, patch:no

#23405 Angular: Fix esm issue in combination with rxjs v6
  code/frameworks/angular/src/server/framework-preset-angular-ivy.ts
Labels: bug, angular, patch:yes, ci:daily

#23386 Sandboxes: Enable Angular v15 sandbox
  .circleci/config.yml
  code/lib/cli/src/sandbox-templates.ts
Labels: build, ci:daily

#23407 Release tooling: Fix new patch labels
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/utils/get-changes.ts
Labels: build, patch:no

#23397 Configure.mdx: Replace chevron icon on Configure page to avoid @storybook/components usage
  code/frameworks/nextjs/template/cli/js/Configure.mdx
  code/frameworks/nextjs/template/cli/ts-3-8/Configure.mdx
  code/frameworks/nextjs/template/cli/ts-4-9/Configure.mdx
  code/lib/cli/rendererAssets/common/Configure.mdx
Labels: bug, ci:daily

#23201 CLI: Exit when user does not want to select a storybook project type
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/project_types.ts
Labels: bug, cli, patch:yes

#23419 E2e: Set playwright version to `1.36.0`
  .circleci/config.yml
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/utils/yarn.ts
  scripts/yarn.lock
Labels: patch:yes, build, ci:normal

#23393 Release tooling: Defer version bumping to the publish step
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  .github/workflows/publish.yml
  CONTRIBUTING/RELEASING.md
  code/__mocks__/fs-extra.js
  scripts/release/__tests__/version.test.ts
  scripts/release/version.ts
  scripts/release/write-changelog.ts
Labels: patch:yes, build

#23409 Release tooling: Fix new patch labels
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/utils/get-changes.ts
Labels: build, patch:no

#23421 Release tooling: Defer version bumping to the publish step - Cherry picking #23393
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  .github/workflows/publish.yml
  CONTRIBUTING/RELEASING.md
  code/__mocks__/fs-extra.js
  scripts/release/__tests__/version.test.ts
  scripts/release/version.ts
  scripts/release/write-changelog.ts
Labels: build, patch:no

#23391 Dependencies: Lockfile
  code/addons/a11y/tsconfig.json
  code/addons/interactions/tsconfig.json
  code/addons/links/tsconfig.json
  code/frameworks/nextjs/src/css/webpack.ts
  code/frameworks/nextjs/src/images/webpack.ts
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Navigation.stories.tsx
  code/presets/create-react-app/src/helpers/mergePlugins.ts
  code/ui/blocks/tsconfig.json
  code/ui/components/src/form/input/input.tsx
  code/ui/components/tsconfig.json
  code/ui/manager/tsconfig.json
  code/yarn.lock
  scripts/yarn.lock
Labels: dependencies, patch:no

#23342 UI: Add storyStatus to sidebar UI
  code/e2e-tests/util.ts
  code/lib/manager-api/src/index.tsx
  code/lib/manager-api/src/modules/stories.ts
  code/lib/types/src/modules/api-stories.ts
  code/ui/manager/src/components/layout/app.mockdata.tsx
  code/ui/manager/src/components/preview/iframe.stories.tsx
  code/ui/manager/src/components/sidebar/RefIndicator.tsx
  code/ui/manager/src/components/sidebar/Refs.tsx
  code/ui/manager/src/components/sidebar/Search.tsx
  code/ui/manager/src/components/sidebar/SearchResults.stories.tsx
  code/ui/manager/src/components/sidebar/SearchResults.tsx
  code/ui/manager/src/components/sidebar/Sidebar.stories.tsx
  code/ui/manager/src/components/sidebar/Sidebar.tsx
  code/ui/manager/src/components/sidebar/Tree.stories.tsx
  code/ui/manager/src/components/sidebar/Tree.tsx
  code/ui/manager/src/components/sidebar/TreeNode.stories.tsx
  code/ui/manager/src/components/sidebar/TreeNode.tsx
  code/ui/manager/src/components/sidebar/__tests__/Sidebar.test.tsx
  code/ui/manager/src/components/sidebar/mockdata.ts
  code/ui/manager/src/components/sidebar/useExpanded.ts
  code/ui/manager/src/components/sidebar/useHighlighted.ts
  code/ui/manager/src/containers/sidebar.tsx
  code/ui/manager/src/utils/status.test.ts
  code/ui/manager/src/utils/status.tsx
  code/ui/manager/src/utils/tree.test.js
  code/ui/manager/src/utils/tree.ts
Labels: feature request, ui, ci:normal, patch:no

#23422 Build: Fix inconsistent stories in nextjs example
  code/frameworks/nextjs/template/stories/Image.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-12-js/ImageFuture.stories.jsx
Labels: patch:yes, build, ci:daily

#23417 Docs: Adds the disable notification to the documentation
  docs/api/main-config-core.md
  docs/configure/overview.md
  docs/snippets/common/main-config-core-disable-update-notifications.js.mdx
  docs/snippets/common/main-config-core-disable-update-notifications.ts.mdx
Labels: documentation, patch:no

#23426 CLI: Fix language detection to properly detect Javascript
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/detect.ts
Labels: bug, cli, patch:no

#23307 Addon API: Add experimental `page` addon type
  MIGRATION.md
  code/addons/a11y/src/manager.tsx
  code/addons/actions/src/manager.tsx
  code/addons/controls/src/manager.tsx
  code/addons/interactions/src/manager.tsx
  code/addons/jest/src/manager.tsx
  code/addons/storysource/src/manager.tsx
  code/lib/manager-api/src/index.tsx
  code/lib/manager-api/src/lib/addons.ts
  code/lib/manager-api/src/modules/addons.ts
  code/lib/manager-api/src/modules/settings.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/types/src/modules/addons.ts
  code/ui/manager/src/app.stories.tsx
  code/ui/manager/src/app.tsx
  code/ui/manager/src/components/layout/app.mockdata.tsx
  code/ui/manager/src/components/layout/desktop.stories.tsx
  code/ui/manager/src/components/layout/desktop.tsx
  code/ui/manager/src/components/layout/mobile.stories.tsx
  code/ui/manager/src/components/layout/mobile.tsx
  code/ui/manager/src/components/preview/iframe.tsx
  code/ui/manager/src/components/preview/preview.tsx
  code/ui/manager/src/components/preview/toolbar.tsx
  code/ui/manager/src/index.tsx
  code/ui/manager/src/settings/index.tsx
Labels: feature request, api: addons, ui, core, ci:normal, patch:no

#23432 Release tooling: Fix double run of publish workflow
  .github/workflows/publish.yml
Labels: patch:yes, build

#23431 Telemetry: Add globals usage to project.json
  code/lib/telemetry/package.json
  code/lib/telemetry/src/storybook-metadata.ts
  code/lib/telemetry/src/types.ts
  code/yarn.lock
Labels: maintenance, patch:yes, telemetry

#23424 Core: Improve onboarding detection in what's new module
  code/lib/manager-api/src/modules/whatsnew.ts
Labels: bug, core, ci:normal, patch:no

#23311 UI: refactor Canvas component so we can improve types for PREVIEW addons and TAB addons
  code/addons/a11y/src/manager.test.tsx
  code/lib/manager-api/src/lib/addons.ts
  code/lib/manager-api/src/modules/addons.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/types/src/modules/addons.ts
  code/lib/types/src/modules/api.ts
  code/lib/types/src/modules/channelApi.ts
  code/lib/types/src/modules/csf.ts
  code/ui/manager/src/components/panel/panel.tsx
  code/ui/manager/src/components/preview/preview.tsx
  code/ui/manager/src/components/preview/utils/types.tsx
  code/ui/manager/src/components/preview/wrappers.tsx
Labels: maintenance, typescript, ci:normal, patch:no

#23335 CircleCI: Introduce ci:normal label
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/trigger-circle-ci-workflow.yml
  code/lib/cli/src/sandbox-templates.ts
  scripts/dangerfile.ts
Labels: patch:yes, build, ci:normal

#23436 CI: Skip CircleCI when no workflow argument is set
  .circleci/config.yml
Labels: patch:yes, build

#23442 Docs: (Snippets Web Components) Autodocs fix
  docs/snippets/web-components/button-story-auto-docs.js.mdx
  docs/snippets/web-components/button-story-auto-docs.ts.mdx
Labels: documentation, patch:yes, ci:normal

#23439 Docs: Adds table of contents documentation
  docs/snippets/angular/my-component-disable-toc.ts.mdx
  docs/snippets/common/my-component-disable-toc.js.mdx
  docs/snippets/common/my-component-disable-toc.ts-4-9.mdx
  docs/snippets/common/my-component-disable-toc.ts.mdx
  docs/snippets/common/storybook-preview-custom-toc.js.mdx
  docs/snippets/common/storybook-preview-custom-toc.ts.mdx
  docs/snippets/common/storybook-preview-enable-toc.js.mdx
  docs/snippets/common/storybook-preview-enable-toc.ts.mdx
  docs/snippets/web-components/my-component-disable-toc.js.mdx
  docs/snippets/web-components/my-component-disable-toc.ts.mdx
  docs/writing-docs/autodocs.md
Labels: documentation, patch:no

#23444 Docs: Adds MDX video callout
  docs/writing-docs/mdx.md
Labels: documentation, patch:yes, ci:normal

#23186 Fixed a mistake in JSDoc
  code/renderers/react/src/testing-api.ts
Labels: documentation, patch:yes, ci:normal

#23450 CI: Fix parallelism on main
  .circleci/config.yml
Labels: build, ci:daily, ci:normal, patch:no

#23472 Svelte-vite: Improve error message when sveltekit plugins are found in non-sveltekit projects
  code/frameworks/svelte-vite/src/utils.ts
Labels: maintenance, patch:no

#23475 Svelte-vite: Remove unused import
  code/frameworks/svelte-vite/src/utils.ts
Labels: maintenance, patch:no

#23415 Docs: Telemetry documentation tweaks
  docs/configure/telemetry.md
Labels: documentation, patch:no

#23477 Docs: Adds pnpm yarn automigrate scripts
  docs/configure/upgrading.md
  docs/snippets/common/storybook-automigrate.npm.js.mdx
  docs/snippets/common/storybook-automigrate.pnpm.js.mdx
  docs/snippets/common/storybook-automigrate.yarn.js.mdx
Labels: documentation, patch:yes, ci:normal

#23476 Docs: Adds set up wizard information
  docs/get-started/example-onboarding-wizard.png
  docs/get-started/example-welcome.png
  docs/get-started/install.md
Labels: documentation, ci:normal, patch:no

#23384 Dependencies: Remove references to `api` and the 2 deprecated channel packages
  code/builders/builder-vite/src/optimizeDeps.ts
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/frameworks/html-vite/package.json
  code/lib/cli/src/automigrate/helpers/getMigrationSummary.ts
  code/lib/preview-api/package.json
  code/lib/preview/src/globals/runtime.ts
  code/lib/preview/src/globals/types.ts
  code/ui/manager/package.json
  code/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: maintenance, ci:normal, patch:no

#23441 UI: Show the story status in the search results
  code/ui/.storybook/manager.tsx
  code/ui/manager/src/components/sidebar/Search.tsx
  code/ui/manager/src/components/sidebar/SearchResults.tsx
  code/ui/manager/src/components/sidebar/Sidebar.stories.tsx
  code/ui/manager/src/components/sidebar/Sidebar.tsx
  code/ui/manager/src/components/sidebar/Tree.tsx
  code/ui/manager/src/components/sidebar/types.ts
  code/ui/manager/src/utils/status.test.ts
  code/ui/manager/src/utils/status.tsx
Labels: feature request, ui, ci:normal, patch:no

#23469 UI: Create new form elements in the new Core UI (Input, TextArea, Select)
  code/ui/components/package.json
  code/ui/components/src/new/Input/Input.stories.tsx
  code/ui/components/src/new/Input/Input.tsx
  code/ui/components/src/new/Select/Select.stories.tsx
  code/ui/components/src/new/Select/Select.tsx
  code/ui/components/src/new/Select/SelectItem.tsx
  code/ui/components/src/new/Select/icons/Arrowdown.tsx
  code/ui/components/src/new/Select/icons/Arrowup.tsx
  code/ui/components/src/new/Select/icons/Check.tsx
  code/ui/components/src/new/Select/icons/ExpandAlt.tsx
  code/ui/components/src/new/Select/icons/IconWrapper.tsx
  code/ui/components/src/new/Select/icons/types.ts
  code/ui/components/src/new/Textarea/Textarea.stories.tsx
  code/ui/components/src/new/Textarea/Textarea.tsx
  code/yarn.lock
Labels: ui, maintenance, ci:normal, patch:no

#23500 Dependencies: Regen lockfiles
  code/yarn.lock
  scripts/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: dependencies, ci:normal, patch:no

#23489 Angular: Make enableProdMode optional
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/build-storybook/schema.json
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/schema.json
  code/frameworks/angular/src/builders/utils/standalone-options.ts
  code/frameworks/angular/src/preset.ts
Labels: bug, angular, patch:yes, ci:daily

#23507 Release tooling: Initial empty canary release workflow
  .github/workflows/canary-release-pr.WIP
  .github/workflows/canary-release-pr.yml
Labels: build, patch:no

#23519 Codeowners: Add file
  CODEOWNERS
Labels: patch:yes, build, ci:normal

#23467 Docs: fix readme storyshots link
  README.md
Labels: documentation, patch:yes, ci:normal

#23433 Chromatic: Fix flaky chromatic tests caused by the next/image component loading
  code/frameworks/nextjs/template/stories/Image.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/ImageLegacy.stories.jsx
Labels: patch:yes, build, ci:normal

#23458 CLI: Improve support of mono repositories
  code/builders/builder-vite/src/index.ts
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/src/index.ts
  code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/frameworks/angular/src/preset.ts
  code/frameworks/ember/src/preset.ts
  code/frameworks/html-vite/src/preset.ts
  code/frameworks/html-webpack5/src/preset.ts
  code/frameworks/nextjs/package.json
  code/frameworks/nextjs/src/font/webpack/loader/local/get-font-face-declarations.ts
  code/frameworks/preact-vite/src/preset.ts
  code/frameworks/preact-webpack5/src/preset.ts
  code/frameworks/react-vite/src/preset.ts
  code/frameworks/react-webpack5/src/preset.ts
  code/frameworks/server-webpack5/src/preset.ts
  code/frameworks/svelte-vite/src/preset.ts
  code/frameworks/svelte-webpack5/src/preset.ts
  code/frameworks/sveltekit/src/preset.ts
  code/frameworks/vue-vite/src/preset.ts
  code/frameworks/vue-webpack5/src/preset.ts
  code/frameworks/vue3-vite/src/preset.ts
  code/frameworks/vue3-webpack5/src/preset.ts
  code/frameworks/web-components-vite/src/preset.ts
  code/frameworks/web-components-webpack5/package.json
  code/frameworks/web-components-webpack5/src/preset.ts
  code/jest.config.base.js
  code/lib/cli/package.json
  code/lib/cli/src/automigrate/fixes/__test__/main-config-with-wrappers.js
  code/lib/cli/src/automigrate/fixes/__test__/main-config-without-wrappers.js
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/fixes/wrap-require-utils.ts
  code/lib/cli/src/automigrate/fixes/wrap-require.test.ts
  code/lib/cli/src/automigrate/fixes/wrap-require.ts
  code/lib/cli/src/automigrate/helpers/mainConfigFile.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/codemod/package.json
  code/lib/csf-tools/package.json
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
  code/lib/csf-tools/src/babelParse.ts
  code/lib/docs-tools/package.json
  code/package.json
  code/presets/preact-webpack/package.json
  code/presets/preact-webpack/src/index.ts
  code/presets/react-webpack/package.json
  code/presets/react-webpack/src/framework-preset-react.ts
  code/presets/web-components-webpack/package.json
  code/renderers/react/package.json
  code/yarn.lock
  docs/faq.md
  docs/snippets/common/storybook-main-pnpm-with-module-resolution.js.mdx
  docs/snippets/common/storybook-main-pnpm-with-module-resolution.ts.mdx
Labels: bug, patch:yes, ci:daily

#23556 Update CHANGELOG.prerelease.md
  CHANGELOG.prerelease.md
Labels: documentation, ci:normal, patch:no

#23538 CLI: Gracefully shutdown and cleanup execa child processes
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/repro-generators/scripts.ts
  code/lib/core-server/src/withTelemetry.ts
  scripts/build-package.js
  scripts/check-package.js
  scripts/utils/exec.ts
Labels: bug, patch:yes, telemetry, ci:daily

#23560 Update autodoc to proper default value
  docs/writing-docs/autodocs.md
Labels: documentation, patch:yes, ci:normal

#23491 Release tooling: Fixes from stable promotion
  .github/workflows/publish.yml
  CONTRIBUTING/RELEASING.md
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/label-patches.ts
  scripts/release/pick-patches.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/utils/github-client.ts
Labels: patch:yes, build, ci:normal

#23571 Release tooling: Fix getting changes from wrong tag
  CHANGELOG.prerelease.md
  docs/versions/next.json
  scripts/release/is-pr-frozen.ts
  scripts/release/pick-patches.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/git-client.ts
Labels: patch:yes, build, ci:normal

#23567 docs: update outdated link to current documentation
  code/lib/types/src/modules/addons.ts
Labels: documentation, ci:normal

#23578 Scripts: Task system task selection improvement
  scripts/utils/options.ts
Labels: build, ci:normal, patch:no

#23574 TypeScript: Downgrade to the last version of type-fest that doesn't need typescript 5.0
  code/lib/core-common/package.json
  code/package.json
  code/renderers/react/package.json
  code/renderers/svelte/package.json
  code/renderers/vue/package.json
  code/renderers/vue3/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: maintenance, patch:yes, ci:normal

#23562 docs: resolve typos in imports on highlight addon docs
  code/addons/highlight/README.md
  docs/snippets/react/component-story-highlight-addon.js.mdx
  docs/snippets/vue/component-story-highlight-addon.js.mdx
Labels: documentation, patch:yes, ci:normal

#23508 Release tooling: Support canary releases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/canary-release-pr.yml
  CONTRIBUTING/RELEASING.md
Labels: patch:yes, build, ci:normal

#23396 Dependencies: Upgrade simple-update-notifier
  code/lib/cli/package.json
  code/yarn.lock
Labels: dependencies, patch:yes, security, ci:normal

#23595 Linting: Docs entries
  docs/snippets/react/component-story-highlight-addon.js.mdx
  docs/snippets/vue/component-story-highlight-addon.js.mdx
Labels: documentation, patch:no, ci:docs

#23575 CI: Add a `ci:docs` workflow
  .circleci/config.yml
  .github/workflows/trigger-circle-ci-workflow.yml
  scripts/dangerfile.ts
Labels: build, patch:no, ci:docs

#23375 Build: Migrate `vue3-vite` to ts strict mode
  code/frameworks/vue3-vite/src/preset.ts
  code/frameworks/vue3-vite/tsconfig.json
Labels: typescript, build, ci:normal, patch:no

#23597 Dependencies: Downgrade `jest-mock`
  code/addons/interactions/package.json
  code/yarn.lock
Labels: dependencies, patch:yes, ci:normal

#23488 Added `expanded` to `CoreCommon_StorybookRefs` to fix typescript errors
  code/lib/types/src/modules/core-common.ts
Labels: bug, ci:normal, patch:no

#23598 Angular: Fix initialization of Storybook in Angular 16.1
  code/lib/cli/src/automigrate/fixes/angular-builders-multiproject.ts
  code/lib/cli/src/automigrate/fixes/angular-builders.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/helpers.ts
Labels: bug, angular, patch:yes, ci:normal

#23565 docs: replace unsupported value 'string' in controls
  code/lib/preview-api/src/modules/store/csf/normalizeInputTypes.test.ts
  docs/snippets/angular/arg-types-in-meta.ts.mdx
  docs/snippets/common/arg-types-in-meta.js.mdx
  docs/snippets/common/arg-types-in-meta.ts-4-9.mdx
  docs/snippets/common/arg-types-in-meta.ts.mdx
  docs/snippets/common/arg-types-in-preview.js.mdx
  docs/snippets/common/arg-types-in-preview.ts-4-9.mdx
  docs/snippets/common/arg-types-in-preview.ts.mdx
  docs/snippets/web-components/arg-types-in-meta.js.mdx
  docs/snippets/web-components/arg-types-in-meta.ts.mdx
Labels: documentation, patch:yes, addon: contexts, ci:normal

#23182 Core: Migrate `@storybook/core-server` to strict TypeScript
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/dev-server.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/standalone.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/copy-all-static-files.ts
  code/lib/core-server/src/utils/doTelemetry.ts
  code/lib/core-server/src/utils/get-builders.ts
  code/lib/core-server/src/utils/get-server-channel.ts
  code/lib/core-server/src/utils/getStoryIndexGenerator.ts
  code/lib/core-server/src/utils/server-address.ts
  code/lib/core-server/src/utils/server-statics.ts
  code/lib/core-server/src/utils/stories-json.ts
  code/lib/core-server/src/withTelemetry.ts
  code/lib/core-server/tsconfig.json
Labels: build, ci:normal, patch:no

#23524 Addon: Create @storybook/addon-themes
  code/addons/essentials/package.json
  code/addons/essentials/src/index.ts
  code/addons/essentials/src/themes/manager.ts
  code/addons/essentials/src/themes/preview.ts
  code/addons/themes/README.md
  code/addons/themes/docs/api.md
  code/addons/themes/docs/getting-started/bootstrap.md
  code/addons/themes/docs/getting-started/emotion.md
  code/addons/themes/docs/getting-started/material-ui.md
  code/addons/themes/docs/getting-started/styled-components.md
  code/addons/themes/docs/getting-started/tailwind.md
  code/addons/themes/jest.config.js
  code/addons/themes/manager.js
  code/addons/themes/package.json
  code/addons/themes/preview.js
  code/addons/themes/project.json
  code/addons/themes/src/constants.ts
  code/addons/themes/src/decorators/class-name.decorator.tsx
  code/addons/themes/src/decorators/data-attribute.decorator.tsx
  code/addons/themes/src/decorators/helpers.ts
  code/addons/themes/src/decorators/index.ts
  code/addons/themes/src/decorators/provider.decorator.tsx
  code/addons/themes/src/index.ts
  code/addons/themes/src/manager.tsx
  code/addons/themes/src/preview.tsx
  code/addons/themes/src/theme-switcher.tsx
  code/addons/themes/tsconfig.json
  code/yarn.lock
  docs/essentials/addon-themes-example.gif
  docs/essentials/introduction.md
  docs/essentials/themes.md
  docs/snippets/common/storybook-addon-themes-classname-decorator.js.mdx
  docs/snippets/common/storybook-addon-themes-classname-decorator.ts-4-9.mdx
  docs/snippets/common/storybook-addon-themes-classname-decorator.ts.mdx
  docs/snippets/common/storybook-addon-themes-data-attribute-decorator.js.mdx
  docs/snippets/common/storybook-addon-themes-data-attribute-decorator.ts-4-9.mdx
  docs/snippets/common/storybook-addon-themes-data-attribute-decorator.ts.mdx
  docs/snippets/common/storybook-addon-themes-jsx-provider-decorator.js.mdx
  docs/snippets/common/storybook-addon-themes-jsx-provider-decorator.ts-4-9.mdx
  docs/snippets/common/storybook-addon-themes-jsx-provider-decorator.ts.mdx
  docs/toc.js
  scripts/verdaccio.yaml
Labels: feature request, patch:yes, theming, ci:normal

#23582 Indexer: Deprecate `storyIndexers` API, add foundation for `indexers`
  code/addons/docs/src/preset.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.deprecated.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/getStoryIndexGenerator.ts
  code/lib/core-server/src/utils/stories-json.test.ts
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/types/src/index.ts
  code/lib/types/src/modules/addons.ts
  code/lib/types/src/modules/api-stories.ts
  code/lib/types/src/modules/api.ts
  code/lib/types/src/modules/core-common.ts
  code/lib/types/src/modules/indexer.ts
  code/renderers/server/src/preset.ts
  docs/snippets/common/storybook-main-csf-indexer.ts.mdx
  docs/snippets/common/storybook-main-story-indexer-main.ts.mdx
Labels: feature request, ci:normal

#23610 Maintainance: Fix codeowner docs glob
  CODEOWNERS
Labels: maintenance, patch:yes, ci:normal

#23377 Build: Migrate `preset-vue3-webpack` to ts strict mode
  code/presets/vue3-webpack/src/framework-preset-vue3-docs.ts
  code/presets/vue3-webpack/src/framework-preset-vue3.ts
  code/presets/vue3-webpack/tsconfig.json
Labels: typescript, build, ci:normal, patch:no

#23609 Release tooling: Make canaries use `v0.0.0`
  .github/workflows/canary-release-pr.yml
  CONTRIBUTING/RELEASING.md
Labels: patch:yes, build, ci:normal

#22450 Next.js: Add `@babel/core` as a dependency
  code/addons/interactions/src/components/MatcherResult.tsx
  code/addons/interactions/src/components/MethodCall.tsx
  code/frameworks/nextjs/package.json
  code/ui/blocks/src/controls/Range.tsx
  code/ui/blocks/src/controls/react-editable-json-tree/JsonNodes.tsx
  code/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: bug, patch:yes, nextjs, ci:daily

#23614 Docs: Update security policy
  SECURITY.md
Labels: documentation, ci:normal, patch:no

#23617 CI: Add missing workflow enum
  .circleci/config.yml
Labels: patch:yes, build, ci:docs

#23376 Build: Migrate `vue3-webpack5` to ts strict mode
  code/frameworks/vue3-webpack5/tsconfig.json
Labels: typescript, build, ci:normal, patch:no

#23427 CSF Tools: Use recast for printing in csf-tools
  code/lib/codemod/src/transforms/csf-2-to-3.ts
  code/lib/codemod/src/transforms/upgrade-deprecated-types.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/csf-tools/package.json
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/csf-tools/src/enrichCsf.test.ts
  code/yarn.lock
Labels: build, ci:merged, patch:no

#23644 Automigration: Fix wrap-require automigration for common js main.js files
  code/lib/cli/src/automigrate/fixes/wrap-require.ts
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: bug, patch:yes, ci:daily, automigrations

#23632 Core: Improve internal types
  code/lib/core-common/src/utils/validate-config.ts
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/utils/get-builders.ts
  code/lib/core-server/src/utils/getStoryIndexGenerator.ts
  code/lib/core-server/src/utils/server-statics.ts
  code/lib/core-server/src/withTelemetry.ts
  code/lib/node-logger/src/index.ts
Labels: maintenance, ci:normal

#23656 Core: Support `parameters.__id` and `metaId` in indexers
  code/lib/core-server/src/utils/StoryIndexGenerator.deprecated.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/__tests__/index-extraction.test.ts
  code/lib/core-server/src/utils/stories-json.test.ts
  code/lib/csf-tools/src/CsfFile.test.ts
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/preview-api/template/stories/indexer.stories.ts
  code/lib/types/src/modules/indexer.ts
Labels: maintenance, core, ci:daily

#22240 Vite: Fix config loading - project directory
  code/builders/builder-vite/src/vite-config.ts
Labels: bug, builder-vite, ci:normal, patch:no

#23652 Pull addon-themes from essentials
  code/addons/essentials/package.json
  code/addons/essentials/src/index.ts
  code/addons/essentials/src/themes/manager.ts
  code/addons/essentials/src/themes/preview.ts
  code/addons/themes/README.md
  code/addons/themes/docs/getting-started/bootstrap.md
  code/addons/themes/docs/getting-started/emotion.md
  code/addons/themes/docs/getting-started/material-ui.md
  code/addons/themes/docs/getting-started/styled-components.md
  code/addons/themes/docs/getting-started/tailwind.md
  code/yarn.lock
  docs/essentials/introduction.md
  docs/toc.js
Labels: cleanup, theming, ci:merged, patch:no
