Repository storybookjs/storybook, pull requests merged in 2023-04, with the labels that each got.

#21857 Docs: add migration guide for addon creators and addon consumers about the changes in addon APIs
  MIGRATION.md
  docs/migration-guide.md
Labels: documentation

#21868 Chore:(Docs) Adds missing snippet for webpack
  docs/snippets/common/storybook-main-ts-module-resolution.ts.mdx
Labels: documentation

#21807 Remove deprecated `component` and `propsMeta` field from Angular Story type
  MIGRATION.md
  code/addons/storyshots-core/src/frameworks/angular/types.ts
  code/frameworks/angular/src/client/angular/app.component.ts
  code/frameworks/angular/src/client/angular/app.token.ts
  code/frameworks/angular/src/client/decorateStory.test.ts
  code/frameworks/angular/src/client/decorators.test.ts
  code/frameworks/angular/src/client/types.ts
  code/frameworks/angular/template/stories/basics/component-with-ng-on-destroy/component-with-on-destroy.stories.ts
Labels: bug, ci:daily

#21875 CLI: Fix link to new framework API migrations
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: maintenance, cli

#21863 CLI: Warn when community addons are incompatible with Storybook 7
  code/lib/cli/src/automigrate/fixes/incompatible-addons.test.ts
  code/lib/cli/src/automigrate/fixes/incompatible-addons.ts
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/helpers/mainConfigFile.ts
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/utils/warnOnIncompatibleAddons.ts
Labels: bug, cli

#21879 Telemetry: Always send error events if init doesn't succeed
  code/lib/cli/src/HandledError.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: bug, telemetry

#21852 Remove deprecated flags and properties
  MIGRATION.md
  code/addons/docs/src/typings.d.ts
  code/addons/storyshots-core/src/typings.d.ts
  code/addons/toolbars/src/components/ToolbarMenuList.tsx
  code/addons/toolbars/src/types.ts
  code/frameworks/angular/src/typings.d.ts
  code/lib/core-server/src/__for-testing__/main.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/typings.d.ts
  code/lib/core-server/src/utils/getStoryIndexGenerator.ts
  code/lib/instrumenter/src/typings.d.ts
  code/lib/manager-api/src/typings.d.ts
  code/lib/preview-api/src/modules/core-client/start.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/store/StoryStore.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/preview-api/src/typings.d.ts
  code/lib/types/src/modules/core-common.ts
  code/renderers/react/template/stories/docgen-components/9721-ts-deprecated-jsdoc/argTypes.snapshot
  code/renderers/react/template/stories/docgen-components/9721-ts-deprecated-jsdoc/docgen.snapshot
  code/renderers/react/template/stories/docgen-components/9721-ts-deprecated-jsdoc/input.tsx
  code/renderers/react/template/stories/docgen-components/9721-ts-deprecated-jsdoc/properties.snapshot
  code/ui/manager/src/settings/typings.d.ts
  code/ui/manager/src/typings.d.ts
  test-storybooks/ember-cli/.storybook/main.js
Labels: maintenance, ci:daily

#21881 Upgrade satellite repos for 7.0
  code/addons/docs/package.json
  code/addons/interactions/package.json
  code/addons/links/package.json
  code/addons/storyshots-puppeteer/package.json
  code/lib/builder-vite/package.json
  code/lib/codemod/package.json
  code/lib/core-server/package.json
  code/lib/csf-tools/package.json
  code/lib/manager-api/package.json
  code/lib/preview-api/package.json
  code/lib/source-loader/package.json
  code/lib/types/package.json
  code/package.json
  code/ui/blocks/package.json
  code/ui/components/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies, ci:daily

#21888 CI: Update trigger circle ci workflow to include main
  .github/workflows/trigger-circle-ci-workflow.yml
Labels: maintenance

#21913 Build: remove pnp sandbox template
  code/lib/cli/src/sandbox-templates.ts
Labels: build

#21908 Build: no `pnp.cjs` in the root, regen lockfiles
  .yarnrc.yml
  code/yarn.lock
  node_modules/.yarn-state.yml
  scripts/yarn.lock
Labels: build

#21918 Don't use prerelease commands in Migration Guide
  docs/migration-guide.md
  docs/snippets/common/storybook-upgrade.npm.js
  docs/snippets/common/storybook-upgrade.pnpm.js
Labels: documentation

#21923 Build: Fix release badge on repros
  scripts/sandbox/publish.ts
  scripts/sandbox/utils/template.ts
Labels: build

#21928 Chore: (Docs) Tweaks to the Addon API documentation
  docs/addons/addons-api.md
  docs/snippets/common/args-usage-with-addons.js.mdx
  docs/snippets/common/storybook-addon-panel-initial.js.mdx
  docs/snippets/common/storybook-addons-api-disablequeryparams.js.mdx
  docs/snippets/common/storybook-addons-api-getchannel.js.mdx
  docs/snippets/common/storybook-addons-api-getqueryparam.js.mdx
  docs/snippets/common/storybook-addons-api-geturlstate.js.mdx
  docs/snippets/common/storybook-addons-api-imports.js.mdx
  docs/snippets/common/storybook-addons-api-makedecorator.js.mdx
  docs/snippets/common/storybook-addons-api-on.js.mdx
  docs/snippets/common/storybook-addons-api-register.js.mdx
  docs/snippets/common/storybook-addons-api-selectincurrentkind.js.mdx
  docs/snippets/common/storybook-addons-api-selectstory.js.mdx
  docs/snippets/common/storybook-addons-api-setqueryparams.js.mdx
  docs/snippets/common/storybook-addons-api-useaddonstate.js.mdx
  docs/snippets/common/storybook-addons-api-useapi.js.mdx
  docs/snippets/common/storybook-addons-api-usechannel.js.mdx
  docs/snippets/common/storybook-addons-api-useglobal.js.mdx
  docs/snippets/common/storybook-addons-api-useparameter.js.mdx
  docs/snippets/common/storybook-addons-api-usestorybookstate.js.mdx
Labels: documentation

#21931 Update Migration Guide snippets
  docs/get-started/install.md
  docs/snippets/common/init-command.npx.js.mdx
  docs/snippets/common/init-command.npx.mdx
  docs/snippets/common/init-command.pnpm.js.mdx
  docs/snippets/common/init-command.pnpm.mdx
  docs/snippets/common/storybook-upgrade.npm.js.mdx
  docs/snippets/common/storybook-upgrade.pnpm.js.mdx
Labels: documentation

#21889 Add storybook.new to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation

#21938 Addon GFM: fix node-logger dependency
  code/addons/gfm/package.json
  code/yarn.lock
Labels: maintenance, patch

#21940 Re-enable Vue2 Vite sandbox
  .circleci/config.yml
  code/lib/cli/src/sandbox-templates.ts
Labels: patch, build, ci:daily

#21941 Update `@emotion/cache` version
  code/lib/theming/package.json
  code/yarn.lock
Labels: dependencies, patch

#21922 Bug: Fix incorrect type-file for addon-actions
  code/addons/actions/package.json
Labels: maintenance, addon: actions, patch, typescript

#21946 Docs: change the `@next` mentions in `MIGRATION.md` to `@latest`
  MIGRATION.md
Labels: documentation, patch

#21213 Core: Revert Emotion `:first-child` (etc) workarounds
  code/ui/blocks/src/components/Source.tsx
  code/ui/components/src/spaced/Spaced.tsx
  code/ui/components/src/tabs/tabs.tsx
  code/ui/manager/src/index.tsx
Labels: bug, patch, addon: docs

#21947 Add platform-specific null piping for stderr for npm list command
  code/lib/cli/src/js-package-manager/NPMProxy.ts
Labels: bug, patch

#21902 Addon-docs: Include decorators by default in source decorators
  MIGRATION.md
  code/addons/docs/src/preview.ts
Labels: bug, patch, addon: docs, block: source

#21907 React: Don't show decorators in JSX snippets
  code/lib/preview-api/src/modules/addons/hooks.ts
  code/renderers/react/src/applyDecorators.ts
  code/renderers/react/src/config.ts
  code/renderers/react/template/stories/decorators.stories.tsx
Labels: bug, react, patch

#21944 Angular: Fix components disappearing on docs page on property change
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/DocsRenderer.ts
Labels: bug, angular, patch

#21952 Remove @next specifiers in docs & READMEs
  code/addons/docs/angular/README.md
  code/addons/docs/common/README.md
  code/addons/docs/ember/README.md
  code/addons/docs/react/README.md
  code/addons/docs/vue/README.md
  code/addons/docs/vue3/README.md
  code/frameworks/nextjs/README.md
  code/frameworks/preact-vite/README.md
  code/frameworks/sveltekit/README.md
  code/lib/builder-vite/README.md
  docs/addons/install-addons.md
  docs/builders/builder-api.md
  docs/builders/vite.md
  docs/configure/babel.md
  docs/configure/overview.md
  docs/configure/theming.md
  docs/configure/upgrading.md
  docs/essentials/interactions.md
  docs/essentials/introduction.md
  docs/get-started/installation-problems/angular.mdx
  docs/get-started/installation-problems/react.mdx
  docs/migration-guide.md
  docs/snippets/common/storybook-a11y-install.npm.js.mdx
  docs/snippets/common/storybook-a11y-install.pnpm.js.mdx
  docs/snippets/common/storybook-a11y-install.yarn.js.mdx
  docs/snippets/common/storybook-addon-actions-install.npm.js.mdx
  docs/snippets/common/storybook-addon-actions-install.pnpm.js.mdx
  docs/snippets/common/storybook-addon-actions-install.yarn.js.mdx
  docs/snippets/common/storybook-addon-essentials-install.npm.js.mdx
  docs/snippets/common/storybook-addon-essentials-install.pnpm.js.mdx
  docs/snippets/common/storybook-addon-essentials-install.yarn.js.mdx
  docs/snippets/common/storybook-addon-interactions-addon-full-install.npm.js.mdx
  docs/snippets/common/storybook-addon-interactions-addon-full-install.pnpm.js.mdx
  docs/snippets/common/storybook-addon-interactions-addon-full-install.yarn.js.mdx
  docs/snippets/common/storybook-coverage-addon-install.npm.js.mdx
  docs/snippets/common/storybook-coverage-addon-install.pnpm.js.mdx
  docs/snippets/common/storybook-coverage-addon-install.yarn.js.mdx
  docs/snippets/common/storybook-fallback-mdx-install.npm.js.mdx
  docs/snippets/common/storybook-fallback-mdx-install.pnpm.js.mdx
  docs/snippets/common/storybook-fallback-mdx-install.yarn.js.mdx
  docs/snippets/common/storybook-test-runner-install.npm.js.mdx
  docs/snippets/common/storybook-test-runner-install.pnpm.js.mdx
  docs/snippets/common/storybook-test-runner-install.yarn.js.mdx
  docs/snippets/common/storybook-testing-addon-install.npm.js.mdx
  docs/snippets/common/storybook-testing-addon-install.yarn.js.mdx
  docs/snippets/common/storybook-theming-packages-install.npm.js.mdx
  docs/snippets/common/storybook-theming-packages-install.pnpm.js.mdx
  docs/snippets/common/storybook-theming-packages-install.yarn.js.mdx
  docs/snippets/common/storybook-upgrade-prerelease.npm.js.mdx
  docs/snippets/common/storybook-upgrade-prerelease.pnpm.js.mdx
  docs/snippets/common/storybook-vite-builder-install.npm.js.mdx
  docs/snippets/common/storybook-vite-builder-install.yarn.js.mdx
  docs/writing-docs/mdx.md
  docs/writing-stories/play-function.md
  docs/writing-tests/accessibility-testing.md
  docs/writing-tests/importing-stories-in-tests.md
  docs/writing-tests/interaction-testing.md
  docs/writing-tests/test-coverage.md
  docs/writing-tests/test-runner.md
Labels: documentation, patch

#21932 Add Addon migration guide for Storybook 7.0 page
  docs/addons/addon-migration-guide.md
  docs/toc.js
Labels: documentation, patch

#21955 Add YouTubeCallout to Decorators docs page
  docs/writing-stories/decorators.md
Labels: documentation, patch

#21951 UI: Fix story data access to be more fault tolerant
  code/lib/manager-api/src/index.tsx
Labels: bug, ui, patch

#21839 update deprecated pnpx references
  MIGRATION.md
  code/lib/cli/src/automigrate/fixes/sb-scripts.ts
  docs/snippets/common/preview-storybook-production-mode.pnpm.js.mdx
  docs/snippets/common/storybook-msw-generate.msw-pnpm.js.mdx
  docs/snippets/common/storybook-upgrade-prerelease.pnpm.js.mdx
Labels: documentation, patch, pnpm

#21962 Viewport: Fix the `defaultOrientation` config option
  code/addons/viewport/src/Tool.tsx
  code/addons/viewport/template/stories/parameters.stories.ts
Labels: bug

#21973 Chore: (Docs) Standardize install instructions in documentation
  code/frameworks/angular/README.md
  code/frameworks/ember/README.md
  code/frameworks/html-webpack5/README.md
  code/frameworks/preact-webpack5/README.md
  code/frameworks/react-webpack5/README.md
  code/frameworks/server-webpack5/README.md
  code/frameworks/svelte-webpack5/README.md
  code/frameworks/vue-vite/README.md
  code/frameworks/vue-webpack5/README.md
  code/frameworks/vue3-vite/README.md
  code/frameworks/vue3-webpack5/README.md
  code/frameworks/web-components-webpack5/README.md
  docs/addons/writing-addons.md
  docs/builders/overview.md
  docs/builders/vite.md
  docs/get-started/installation-problems/angular.mdx
  docs/get-started/installation-problems/ember.mdx
  docs/get-started/installation-problems/html.mdx
  docs/get-started/installation-problems/preact.mdx
  docs/get-started/installation-problems/qwik.mdx
  docs/get-started/installation-problems/react.mdx
  docs/get-started/installation-problems/svelte.mdx
  docs/get-started/installation-problems/vue.mdx
  docs/get-started/installation-problems/web-components.mdx
  docs/snippets/common/init-command.npx.js.mdx
  docs/snippets/common/init-command.pnpm.js.mdx
Labels: documentation, patch

#21976 Chore (Documentation) Fix issue template to feature correct command
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, patch

#21985 docs: fix broken link in readme
  code/addons/docs/README.md
Labels: documentation, patch

#22013 React-vite: Fix perf regression by pinning vite-plugin-react-docgen-ts
  code/frameworks/react-vite/package.json
  code/yarn.lock
Labels: dependencies, react, patch, builder-vite

#22006 CLI: Fix JsPackageManager typo
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: bug, cli, patch

#22016 Patch back fixes from 7.1.0-alpha.2 (WIP) to main to fix CI
  .github/ISSUE_TEMPLATE/bug_report.yml
  code/addons/docs/README.md
  code/frameworks/angular/README.md
  code/frameworks/ember/README.md
  code/frameworks/html-webpack5/README.md
  code/frameworks/preact-webpack5/README.md
  code/frameworks/react-vite/package.json
  code/frameworks/react-webpack5/README.md
  code/frameworks/server-webpack5/README.md
  code/frameworks/svelte-webpack5/README.md
  code/frameworks/vue-vite/README.md
  code/frameworks/vue-webpack5/README.md
  code/frameworks/vue3-vite/README.md
  code/frameworks/vue3-webpack5/README.md
  code/frameworks/web-components-webpack5/README.md
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/yarn.lock
  docs/addons/writing-addons.md
  docs/builders/overview.md
  docs/builders/vite.md
  docs/get-started/installation-problems/angular.mdx
  docs/get-started/installation-problems/ember.mdx
  docs/get-started/installation-problems/html.mdx
  docs/get-started/installation-problems/preact.mdx
  docs/get-started/installation-problems/qwik.mdx
  docs/get-started/installation-problems/react.mdx
  docs/get-started/installation-problems/svelte.mdx
  docs/get-started/installation-problems/vue.mdx
  docs/get-started/installation-problems/web-components.mdx
  docs/snippets/common/init-command.npx.js.mdx
  docs/snippets/common/init-command.pnpm.js.mdx
Labels: maintenance

#21997 Update Babel configuration docs for v7
  docs/configure/babel.md
  docs/snippets/common/storybook-main-babel-mode-v7.js.mdx
  docs/snippets/common/storybook-main-custom-babel-config.js.mdx
Labels: documentation, patch

#21963 Viewport: Remove transitions when switching viewports
  code/addons/viewport/src/Tool.tsx
Labels: bug, addon: viewport, patch

#22028 Patch changes from 7.1.0-alpha.1 back to 7.0.x
  code/addons/viewport/src/Tool.tsx
  code/frameworks/angular/package.json
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/lib/cli/src/generate.ts
  code/lib/cli/src/index.ts
  code/lib/manager-api/src/modules/shortcuts.ts
  code/lib/telemetry/src/index.ts
  code/lib/telemetry/src/telemetry.ts
  code/presets/create-react-app/package.json
  code/presets/react-webpack/package.json
  code/ui/manager/src/components/layout/app.mockdata.tsx
  code/ui/manager/src/components/preview/tools/remount.tsx
  code/ui/manager/src/settings/shortcuts.stories.tsx
  code/ui/manager/src/settings/shortcuts.tsx
  code/yarn.lock
  docs/configure/babel.md
  docs/snippets/common/storybook-main-babel-mode-v7.js.mdx
  docs/snippets/common/storybook-main-custom-babel-config.js.mdx
  scripts/event-log-checker.ts
Labels: maintenance

#21919 Docs: Add code snippets for yarn pnp in migration-guide
  docs/migration-guide.md
  docs/snippets/common/init-command.yarn.js.mdx
  docs/snippets/common/storybook-upgrade-prerelease.yarn.js.mdx
  docs/snippets/common/storybook-upgrade.yarn.js.mdx
Labels: documentation, patch

#22025 Docs: Fix GitHub capitalization issue in migration-guide
  docs/migration-guide.md
Labels: documentation, patch

#22022 Fix e2e tests failing in Firefox
  code/e2e-tests/util.ts
Labels: patch, build, ci:daily

#22030 Build: Use vite@beta on sandboxes
  .github/workflows/generate-sandboxes-next.yml
  code/lib/cli/src/sandbox-templates.ts
Labels: build

#22045 Update README npm branches
  README.md
Labels: documentation, patch

#22038 Addon-docs: Remove mdx1-csf as optional peer dep
  code/addons/docs/package.json
  code/lib/builder-vite/package.json
  code/yarn.lock
Labels: dependencies, patch

#22056 UI: Fix upgrade command in about page
  code/ui/manager/src/settings/about.tsx
Labels: bug, ui, patch

#21977 Chore: (CLI) Fix CLI sandbox command
  code/lib/cli/src/sandbox.ts
Labels: cli, patch

#22058 Chore: (Docs) Snippets Minor polish to framework references
  MIGRATION.md
  docs/snippets/common/storybook-vite-builder-ts-configure.ts.mdx
Labels: documentation, patch

#22063 Chore: (Docs) Minor updates to the Essentials documentation
  docs/essentials/introduction.md
  docs/snippets/common/storybook-main-full-individual-essentials-config.js.mdx
  docs/snippets/common/storybook-main-full-individual-essentials-config.ts.mdx
Labels: documentation, patch

#22052 CLI: Mention how to setup a monorepo manually with babel in missing babelrc automigration
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
Labels: bug, cli, patch

#22033 Chore: (UI) Updates sidebar composition links
  code/ui/manager/src/components/sidebar/RefIndicator.tsx
Labels: ui, documentation, patch

#21979 Chore: Fix SvelteKit migration notice
  code/frameworks/svelte-vite/src/utils.ts
Labels: documentation, patch, sveltekit

#22048 Docs: Fix source snippets when parameters.docs.source.type = 'code'
  code/addons/docs/template/stories/docspage/basic.stories.ts
  code/e2e-tests/addon-docs.spec.ts
  code/lib/csf-plugin/src/index.ts
  code/package.json
  code/yarn.lock
  scripts/tasks/sandbox-parts.ts
Labels: bug, patch, ci:daily

#22108 Revert "Build: Update dangerfile temporarily to check for patch label"
  scripts/dangerfile.ts
Labels: patch, build

#22107 Patch changes from 7.1.0-alpha.x to 7.0.x
  MIGRATION.md
  code/addons/docs/template/stories/docspage/basic.stories.ts
  code/e2e-tests/addon-docs.spec.ts
  code/frameworks/svelte-vite/src/utils.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/sandbox.ts
  code/lib/csf-plugin/src/index.ts
  code/package.json
  code/ui/manager/src/components/sidebar/RefIndicator.tsx
  code/ui/manager/src/settings/about.tsx
  code/yarn.lock
  docs/essentials/introduction.md
  docs/snippets/common/storybook-canvas-doc-block-story.js.mdx
  docs/snippets/common/storybook-canvas-doc-block-story.ts-4-9.mdx
  docs/snippets/common/storybook-canvas-doc-block-story.ts.mdx
  docs/snippets/common/storybook-main-full-individual-essentials-config.js.mdx
  docs/snippets/common/storybook-main-full-individual-essentials-config.ts.mdx
  docs/snippets/common/storybook-vite-builder-ts-configure.ts.mdx
  docs/writing-docs/doc-blocks.md
  scripts/dangerfile.ts
  scripts/tasks/sandbox-parts.ts
Labels: maintenance

#22000 CLI: Mark qwik as using addon-interactions
  code/lib/cli/src/generators/baseGenerator.ts
Labels: maintenance, cli, patch

#22089 Documentation: Update examples and links
  README.md
Labels: documentation, patch

#22085 Core: Fix `module` guard in non-webpack environments
  code/frameworks/angular/src/client/index.ts
  code/frameworks/ember/src/index.ts
  code/renderers/html/src/index.ts
  code/renderers/preact/src/index.ts
  code/renderers/react/src/index.ts
  code/renderers/server/src/index.ts
  code/renderers/svelte/src/index.ts
  code/renderers/vue/src/index.ts
  code/renderers/vue3/src/index.ts
  code/renderers/web-components/src/index.ts
Labels: bug, patch, core

#21984 chore: remove unused dependencies
  code/addons/docs/package.json
  code/lib/docs-tools/package.json
  code/yarn.lock
Labels: dependencies, patch

#22117 fix(Docs): update code snippet link
  docs/configure/theming.md
Labels: documentation, patch

#22129 Update doc-block-markdown.md
  docs/api/doc-block-markdown.md
Labels: documentation, patch

#22131 Clarify that IconGallery only works with React icons
  docs/api/doc-block-icongallery.md
Labels: documentation, patch

#22120 Core: Add new tags to distinguish docs attachment
  code/lib/core-server/src/utils/StoryIndexGenerator.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/__mockdata__/complex/TwoStoryReferences.mdx
  code/lib/core-server/src/utils/stories-json.test.ts
Labels: bug, core

#22118 Core: Restore Docs `useParameter` using `DOCS_PREPARED`
  code/e2e-tests/addon-backgrounds.spec.ts
  code/lib/core-events/src/index.ts
  code/lib/manager-api/src/lib/stories.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.mockdata.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.ts
  code/lib/preview-api/src/modules/store/StoryStore.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/types/src/modules/api-stories.ts
  code/lib/types/src/modules/channelApi.ts
  code/ui/manager/src/globals/exports.ts
Labels: bug, addon: docs

#22087 Build: Upgrade Playwright to 1.32.3
  .circleci/config.yml
  code/package.json
  code/yarn.lock
  docs/contribute/code.md
  scripts/tasks/e2e-tests-build.ts
  scripts/utils/yarn.ts
Labels: patch, build

#22141 Build: Skip docs pages e2e tests for ssv6 examples
  code/e2e-tests/addon-backgrounds.spec.ts
Labels: build, ci:merged

#22145 Fix some issues related to code snippets in the theming doc
  docs/configure/theming.md
  docs/snippets/common/storybook-theme-example-variables.js.mdx
Labels: documentation, patch

#22146 Patch changes for 7.0.6
  .circleci/config.yml
  README.md
  code/frameworks/angular/src/client/index.ts
  code/frameworks/ember/src/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/package.json
  code/renderers/html/src/index.ts
  code/renderers/preact/src/index.ts
  code/renderers/react/src/index.ts
  code/renderers/server/src/index.ts
  code/renderers/svelte/src/index.ts
  code/renderers/vue/src/index.ts
  code/renderers/vue3/src/index.ts
  code/renderers/web-components/src/index.ts
  code/yarn.lock
  docs/api/doc-block-icongallery.md
  docs/api/doc-block-markdown.md
  docs/configure/theming.md
  docs/contribute/code.md
  docs/snippets/common/storybook-theme-example-variables.js.mdx
  scripts/tasks/e2e-tests-build.ts
  scripts/utils/yarn.ts
Labels: maintenance

#22147 Chore: (Docs) Remove comments from Angular snippets
  docs/snippets/angular/button-story-argtypes-with-subcategories.ts.mdx
  docs/snippets/angular/gizmo-story-controls-customization.ts.mdx
Labels: documentation, patch

#22136 improve sandboxes commit message
  scripts/sandbox/publish.ts
  scripts/sandbox/templates/item.ejs
  scripts/sandbox/utils/git.ts
  scripts/sandbox/utils/template.ts
Labels: patch, build

#22130 Fix broken links to StoryShots
  docs/writing-tests/visual-testing.md
Labels: documentation, patch

#22102 Update code example of framework standalone build
  MIGRATION.md
Labels: documentation, patch

#22152 Chore: (Docs) Adds FAQ entry for PNP module resolution
  docs/faq.md
  docs/snippets/common/storybook-main-pnpm-with-module-resolution.js.mdx
  docs/snippets/common/storybook-main-pnpm-with-module-resolution.ts.mdx
Labels: documentation, patch

#21954 Vue3:fix reactive decorators
  code/lib/store/template/stories/args.stories.ts
  code/lib/store/template/stories/globals.stories.ts
  code/renderers/vue3/src/decorateStory.ts
  code/renderers/vue3/src/render.test.ts
  code/renderers/vue3/src/render.ts
  code/renderers/vue3/src/types.ts
  code/renderers/vue3/template/stories/BaseLayout.vue
  code/renderers/vue3/template/stories/CustomRenderFunctionalComponent.stories.ts
  code/renderers/vue3/template/stories/CustomRenderOptionsArgsFromData.stories.ts
  code/renderers/vue3/template/stories/CustomRenderOptionsArgsFromProps.stories.ts
  code/renderers/vue3/template/stories/GlobalUsage.stories.ts
  code/renderers/vue3/template/stories/MySlotComponent.vue
  code/renderers/vue3/template/stories/OverrideArgs.vue
  code/renderers/vue3/template/stories/ReactiveArgs.stories.js
  code/renderers/vue3/template/stories/ReactiveArgs.stories.ts
  code/renderers/vue3/template/stories/ReactiveDecorators.stories.ts
  code/renderers/vue3/template/stories/ReactiveSlots.stories.ts
  code/renderers/vue3/template/stories/Reactivity.vue
  code/renderers/vue3/template/stories/ScopedSlots.stories.ts
  code/renderers/vue3/template/stories/decorators.stories.js
  code/renderers/vue3/template/stories/decorators.stories.ts
  code/renderers/vue3/tsconfig.json
  scripts/package.json
  scripts/tasks/sandbox-parts.ts
Labels: bug, vue3

#22095 CLI: Add addon query-params to list of SB7 incompatible addons
  code/lib/cli/src/automigrate/helpers/getIncompatibleAddons.ts
Labels: maintenance, cli, patch

#22154 Core: Pass parameters in `SET_INDEX` for docs entries
  code/e2e-tests/addon-backgrounds.spec.ts
  code/lib/preview-api/src/modules/core-client/start.test.ts
  code/lib/preview-api/src/modules/store/StoryStore.ts
Labels: bug, patch, core, addon: docs, ci:merged

#21797 Update styling & CSS doc to mention styling addon
  docs/configure/import-css/import-css.js.mdx
  docs/configure/import-css/import-css.ts.mdx
  docs/configure/styling-and-css.md
  docs/get-started/setup.md
  docs/toc.js
Labels: documentation, patch

#22055 Create channel url on client from window.location
  code/lib/builder-manager/src/utils/template.ts
  code/lib/builder-vite/input/iframe.html
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/lib/builder-vite/src/transform-iframe-html.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/lib/channel-websocket/src/index.ts
  code/ui/manager/src/runtime.ts
  code/ui/manager/src/settings/typings.d.ts
Labels: feature request, core

#22037 Addon-actions: Fix ESM by upgrading from uuid-browser to uuid
  code/addons/actions/package.json
  code/addons/actions/src/runtime/action.ts
  code/addons/actions/src/typings.d.ts
  code/lib/builder-vite/src/optimizeDeps.ts
  code/yarn.lock
Labels: bug, addon: actions, patch, builder-webpack5

#22191 Update v7 stricter global types
  MIGRATION.md
Labels: documentation, patch

#22190 CSF: Improve error message for bad default export
  code/lib/csf-tools/src/CsfFile.test.ts
  code/lib/csf-tools/src/CsfFile.ts
Labels: maintenance, patch, csf

#22192 Document v7 file URL behavior
  MIGRATION.md
Labels: documentation, patch

#22198 Document v7 file URL behavior
  MIGRATION.md
Labels: documentation, patch

#22183 Vite sandboxes: use stable Vite 4.3
  code/lib/cli/src/sandbox-templates.ts
Labels: builder-vite, build

#22201 Build: Fix lit sandboxes
  code/lib/cli/src/sandbox-templates.ts
Labels: patch, build

#22206 Build: Fix sandbox publish script
  scripts/sandbox/utils/git.ts
Labels: patch, build

#22173 docs: fix broken link in md
  code/lib/preview-api/docs/storiesOf.md
Labels: documentation, patch

#22143 Build: Enable strict TS by default
  Issue.md
  code/addons/backgrounds/tsconfig.json
  code/addons/docs/tsconfig.json
  code/addons/gfm/tsconfig.json
  code/addons/highlight/tsconfig.json
  code/addons/interactions/tsconfig.json
  code/addons/jest/tsconfig.json
  code/addons/measure/tsconfig.json
  code/addons/outline/tsconfig.json
  code/addons/storyshots-core/tsconfig.json
  code/addons/storyshots-puppeteer/tsconfig.json
  code/addons/storysource/tsconfig.json
  code/addons/viewport/tsconfig.json
  code/frameworks/angular/tsconfig.json
  code/frameworks/html-vite/tsconfig.json
  code/frameworks/preact-vite/tsconfig.json
  code/frameworks/react-vite/tsconfig.json
  code/frameworks/svelte-vite/tsconfig.json
  code/frameworks/sveltekit/tsconfig.json
  code/frameworks/vue3-vite/tsconfig.json
  code/frameworks/vue3-webpack5/tsconfig.json
  code/frameworks/web-components-vite/tsconfig.json
  code/lib/addons/tsconfig.json
  code/lib/channel-postmessage/tsconfig.json
  code/lib/channel-websocket/tsconfig.json
  code/lib/channels/tsconfig.json
  code/lib/client-api/tsconfig.json
  code/lib/codemod/tsconfig.json
  code/lib/core-client/tsconfig.json
  code/lib/core-events/tsconfig.json
  code/lib/core-server/package.json
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/tsconfig.json
  code/lib/csf-tools/tsconfig.json
  code/lib/docs-tools/tsconfig.json
  code/lib/instrumenter/tsconfig.json
  code/lib/manager-api-shim/tsconfig.json
  code/lib/manager-api/tsconfig.json
  code/lib/postinstall/tsconfig.json
  code/lib/router/tsconfig.json
  code/lib/source-loader/tsconfig.json
  code/lib/theming/tsconfig.json
  code/lib/types/tsconfig.json
  code/presets/vue-webpack/tsconfig.json
  code/presets/vue3-webpack/tsconfig.json
  code/renderers/server/tsconfig.json
  code/renderers/web-components/tsconfig.json
  code/tsconfig.json
  code/ui/blocks/src/blocks/Canvas.tsx
  code/ui/blocks/tsconfig.json
  code/ui/components/tsconfig.json
  code/ui/manager/tsconfig.json
  code/yarn.lock
  scripts/package.json
  scripts/strict-ts.ts
  scripts/tsconfig.json
Labels: build

#21967 fix: controls missing when navigating from story
  code/ui/components/src/tabs/tabs.hooks.tsx
Labels: bug, ui, patch

#21859 fix: allow Flow syntax in stories
  code/lib/csf-tools/src/babelParse.ts
Labels: feature request, patch, csf

#22235 Moved Vue3 TS Stories into a separate folder
  code/e2e-tests/framework-nextjs.spec.ts
  code/frameworks/nextjs/template/stories_nextjs-12-js/ImageFuture.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-12-js/Link.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Font.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Font.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Head.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/ImageLegacy.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Link.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Link.stories.module.css
  code/frameworks/nextjs/template/stories_nextjs-default-js/Navigation.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Router.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/fonts/OFL.txt
  code/frameworks/nextjs/template/stories_nextjs-default-js/fonts/RubikStorm-Regular.ttf
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.module.css
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.tsx
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Navigation.stories.tsx
  code/renderers/vue3/template/stories_vue3-vite-default-ts/BaseLayout.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderFunctionalComponent.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderOptionsArgsFromData.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderOptionsArgsFromProps.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalUsage.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalUsage.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/MySlotComponent.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/OverrideArgs.stories.js
  code/renderers/vue3/template/stories_vue3-vite-default-ts/OverrideArgs.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveArgs.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveArgs.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveDecorators.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveSlots.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/Reactivity.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ScopedSlots.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/decorators.stories.ts
  scripts/tasks/sandbox-parts.ts
Labels: maintenance, ci:daily

#22019 Remove dead code
  code/addons/toolbars/src/components/ToolbarMenuList.tsx
Labels: maintenance

#22170 Vue3: Support multiple setup functions
  code/renderers/vue3/src/render.ts
  code/renderers/vue3/template/stories/GlobalSetup.stories.ts
  code/renderers/vue3/template/stories/GlobalSetup.vue
  code/renderers/vue3/template/stories/preview.js
  code/renderers/vue3/template/stories/preview.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalUsage.vue
Labels: bug, vue3

#21870 Fix inline story style
  code/ui/blocks/src/components/Story.tsx
Labels: bug, patch, block: other

#22255 Core: Fix `DOCS_RENDERED` test
  code/lib/manager-api/src/tests/stories.test.ts
Labels: maintenance

#22279 Chore: (Docs) Removes section from the publishing docs
  docs/sharing/publish-storybook.md
  docs/snippets/common/seo-title.js.mdx
Labels: documentation, patch

#22203 ember-framework fix: wrong path
  code/frameworks/ember/preset.js
Labels: bug, ember

#22134 fix(angular): removing deprecated import to fix storyshots
  code/frameworks/angular/package.json
  code/frameworks/angular/src/client/public-api.ts
  code/yarn.lock
Labels: bug, angular

#22259 Fix vue-cli/default-js sandbox
  code/renderers/vue3/template/stories/preview.js
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalSetup.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalSetup.vue
  code/renderers/vue3/template/stories_vue3-vite-default-ts/preview.ts
  scripts/tasks/sandbox-parts.ts
Labels: maintenance

#21057 docs: Fix snippets for globalTypes
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
  docs/snippets/common/storybook-preview-locales-globaltype.js.mdx
Labels: documentation, patch

#22284 Chore: (Docs) - Fix GlobalTypes snippets
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
  docs/snippets/common/storybook-preview-configure-globaltypes.ts.mdx
  docs/snippets/common/storybook-preview-locales-globaltype.js.mdx
  docs/snippets/common/storybook-preview-locales-globaltype.ts.mdx
Labels: documentation, patch

#22169 fix: multiple mapped args return array of labels
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/store/template/stories/argMapping.stories.ts
Labels: bug, patch, args, ci:daily

#22286 Vue3: Fix compiler error when there is double tag
  code/renderers/vue3/src/docs/sourceDecorator.ts
Labels: bug, patch, vue3

#22301 Core: Add tests for mapping behaviour in #22169
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
Labels: maintenance

#22171 Update glob to v10.0.0
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/src/api/StoryshotsOptions.ts
  code/addons/storyshots-core/src/api/integrityTestTemplate.ts
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/list-stories.ts
  code/lib/core-common/package.json
  code/lib/core-common/src/utils/validate-configuration-files.ts
  code/package.json
  code/yarn.lock
  scripts/combine-compodoc.ts
  scripts/package.json
  scripts/prepare/tsc.ts
  scripts/yarn.lock
Labels: dependencies

#22229 Vue3: Rollback v7 breaking change and keep reactive v6-compatible API
  code/renderers/vue3/src/decorateStory.ts
  code/renderers/vue3/src/render.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderFunctionalComponent.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderOptionsArgsFromData.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderOptionsArgsFromProps.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveArgs.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveDecorators.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ScopedSlots.stories.ts
Labels: bug, patch, vue3, ci:daily

#22310 Comment out flaky test
  code/e2e-tests/framework-nextjs.spec.ts
Labels: maintenance

#22135 Core: Move `prepareContext` into `store.getStoryContext()`
  code/frameworks/angular/src/client/docs/sourceDecorator.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts
  code/lib/preview-api/src/modules/store/StoryStore.test.ts
  code/lib/preview-api/src/modules/store/StoryStore.ts
  code/lib/preview-api/src/modules/store/args.test.ts
  code/lib/preview-api/src/modules/store/args.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/preview-api/src/modules/store/csf/testing-utils/index.ts
  code/lib/types/src/modules/story.ts
  code/renderers/html/src/docs/sourceDecorator.test.ts
  code/renderers/html/src/docs/sourceDecorator.ts
  code/renderers/react/src/docs/jsxDecorator.test.tsx
  code/renderers/react/src/docs/jsxDecorator.tsx
  code/renderers/svelte/src/docs/sourceDecorator.ts
  code/renderers/vue/src/docs/sourceDecorator.ts
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/renderers/web-components/src/docs/sourceDecorator.test.ts
  code/renderers/web-components/src/docs/sourceDecorator.ts
  code/ui/blocks/src/blocks/Source.tsx
  code/ui/blocks/src/blocks/useArgs.ts
Labels: bug, block: source
