Repository storybookjs/storybook, pull requests merged in 2023-05, with the labels that each got.

#22050 make typings on Docs component better
  code/addons/docs/src/DocsRenderer.tsx
  code/ui/blocks/src/blocks/Docs.tsx
  code/ui/blocks/src/blocks/external/ExternalDocs.tsx
Labels: maintenance, typescript, addon: docs

#22261 fix bad typings file caused by https://github.com/egoist/tsup/issues/782
  code/addons/backgrounds/src/preview.tsx
  code/addons/links/src/preview.ts
  code/addons/measure/src/preview.tsx
  code/addons/outline/src/preview.tsx
  code/frameworks/nextjs/src/preview.tsx
  code/lib/builder-manager/src/index.ts
  code/renderers/html/src/config.ts
  code/renderers/html/src/docs/config.ts
  code/renderers/html/src/types.ts
  code/renderers/preact/src/config.ts
  code/renderers/react/src/config.ts
  code/renderers/react/src/docs/config.ts
  code/renderers/svelte/src/config.ts
  code/renderers/svelte/src/docs/config.ts
  code/renderers/svelte/src/public-api.ts
  code/renderers/vue/src/config.ts
  code/renderers/vue/src/docs/config.ts
  code/renderers/vue3/src/config.ts
  code/renderers/vue3/src/docs/config.ts
  code/renderers/web-components/src/config.ts
  code/renderers/web-components/src/docs/config.ts
  scripts/package.json
  scripts/yarn.lock
Labels: bug, patch, typescript

#22200 Build: Migrate @storybook/postinstall and @storybook/router to strict TS
  code/lib/postinstall/tsconfig.json
  code/lib/router/tsconfig.json
Labels: maintenance, typescript

#22238 Build: Use `next` branch for sandbox and repro commands
  code/lib/cli/src/generate.ts
  scripts/tasks/sandbox-parts.ts
Labels: build

#22320 Build: Migrate @storybook/preset-vue-webpack to strict TS
  code/presets/vue-webpack/src/framework-preset-vue-docs.ts
  code/presets/vue-webpack/src/framework-preset-vue.ts
  code/presets/vue-webpack/tsconfig.json
Labels: build

#22293 Build: Migrate `@storybook/html-vite` to strict TS
  code/frameworks/html-vite/tsconfig.json
Labels: build

#22309 Build: Migrate `@storybook/web-components-vite` to strict TS
  code/frameworks/web-components-vite/tsconfig.json
Labels: build

#22258 fix : Addon panel does not update after disabling/enabling an addon
  code/ui/components/src/tabs/tabs.hooks.tsx
Labels: bug, ui, patch

#22186 Migrate: skip the automigration for gf markdown when user isn't using mdx
  code/lib/cli/package.json
  code/lib/cli/src/automigrate/fixes/mdx-gfm.test.ts
  code/lib/cli/src/automigrate/fixes/mdx-gfm.ts
  code/yarn.lock
Labels: feature request, patch, automigrations

#22330 Tech: do not generate ESM dist for preset files
  code/addons/docs/package.json
  code/addons/storysource/package.json
  code/frameworks/html-vite/package.json
  code/frameworks/html-webpack5/package.json
  code/frameworks/nextjs/package.json
  code/frameworks/preact-vite/package.json
  code/frameworks/preact-webpack5/package.json
  code/frameworks/react-vite/package.json
  code/frameworks/react-webpack5/package.json
  code/frameworks/server-webpack5/package.json
  code/frameworks/svelte-vite/package.json
  code/frameworks/svelte-webpack5/package.json
  code/frameworks/sveltekit/package.json
  code/frameworks/vue-vite/package.json
  code/frameworks/vue-webpack5/package.json
  code/frameworks/vue3-vite/package.json
  code/frameworks/vue3-webpack5/package.json
  code/frameworks/web-components-vite/package.json
  code/frameworks/web-components-webpack5/package.json
  code/lib/builder-webpack5/package.json
  code/lib/core-server/package.json
  code/lib/react-dom-shim/package.json
  code/renderers/react/package.json
  scripts/prepare/bundle.ts
Labels: maintenance, patch

#22355 Enable Angular Unit tests
  code/frameworks/angular/jest.config.js
  code/frameworks/angular/package.json
  code/frameworks/angular/setup-jest.ts
  code/frameworks/angular/src/builders/build-storybook/index.spec.ts
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/index.spec.ts
  code/frameworks/angular/src/builders/utils/run-compodoc.spec.ts
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/RendererFactory.test.ts
  code/frameworks/angular/src/client/angular-beta/RendererFactory.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/docs/angular-properties.test.ts
  code/frameworks/angular/src/client/docs/compodoc.test.ts
  code/frameworks/angular/src/client/render.ts
  code/frameworks/angular/src/server/framework-preset-angular-cli.test.ts
  code/jest.config.js
  code/package.json
  code/yarn.lock
Labels: maintenance

#22365 Etoit/strict ts channels
  code/lib/channels/src/index.test.ts
  code/lib/channels/tsconfig.json
Labels: maintenance

#22339 Migrate @storybook/addon-viewbook to strict ts
  code/addons/viewport/src/Tool.tsx
  code/addons/viewport/tsconfig.json
Labels: maintenance

#22328 docs: fix typo in event handler
  docs/snippets/vue/button-story-click-handler-args.3.js.mdx
  docs/snippets/vue/button-story-click-handler-args.3.ts-4-9.mdx
  docs/snippets/vue/button-story-click-handler-args.3.ts.mdx
Labels: documentation, patch

#22331 Fix: virtual modules excluded for babel-loader
  code/lib/builder-webpack5/src/preview/babel-loader-preview.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: bug, configuration babel / webpack, patch

#22335 Build: Migrate @storybook/channel-postmessage to strict TS
  code/lib/channel-postmessage/package.json
  code/lib/channel-postmessage/src/index.ts
  code/lib/channel-postmessage/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22369 Migrate @storybook/addon-outline to strict TS
  code/addons/outline/tsconfig.json
Labels: maintenance

#22364 Build: Migrate @storybook/channel-websocket to strict TS
  code/lib/channel-websocket/package.json
  code/lib/channel-websocket/src/index.ts
  code/lib/channel-websocket/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22376 Migrate @storybook/theming to strict TS
  code/lib/theming/src/convert.ts
  code/lib/theming/src/create.ts
  code/lib/theming/src/types.ts
  code/lib/theming/tsconfig.json
Labels: maintenance

#22391 Update typescript version to include both 4.0.0 and 5.0.0 in package.json
  code/frameworks/angular/package.json
  code/yarn.lock
Labels: maintenance, patch

#22379 Add Angular Prerelease sandbox
  .circleci/config.yml
  code/e2e-tests/framework-nextjs.spec.ts
  code/lib/cli/src/sandbox-templates.ts
Labels: build, ci:daily

#22418 7.0.9 release
  code/frameworks/angular/package.json
  code/lib/builder-webpack5/src/preview/babel-loader-preview.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/yarn.lock
  docs/snippets/common/checkbox-story.mdx.mdx
  docs/snippets/common/storybook-auto-docs-mdx-docs-imports.mdx.mdx
  docs/snippets/vue/button-story-click-handler-args.3.js.mdx
  docs/snippets/vue/button-story-click-handler-args.3.ts-4-9.mdx
  docs/snippets/vue/button-story-click-handler-args.3.ts.mdx
Labels: maintenance, ci:merged

#22367 Migrate @storybook/addon-storysource to strict ts
  code/addons/storysource/package.json
  code/addons/storysource/src/StoryPanel.tsx
  code/addons/storysource/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22397 Migrate @storybook/types to strict TS
  code/lib/types/tsconfig.json
Labels: maintenance

#22411 Build: Migrate @storybook/svelte-vite to strict-ts
  code/frameworks/svelte-vite/tsconfig.json
Labels: maintenance

#22428 Migrate @storybook/react-vite and @storybook/preact-vite to strict TS
  code/frameworks/preact-vite/tsconfig.json
  code/frameworks/react-vite/tsconfig.json
Labels: maintenance

#22074 fix: removed opacity from list-item color
  code/ui/components/src/tooltip/ListItem.tsx
Labels: bug, ui, patch

#22377 Improve Error message for Angular.json file not found
  code/lib/cli/src/generators/ANGULAR/helpers.ts
  docs/faq.md
Labels: maintenance, cli, patch

#22447 Build: Migrate @storybook/core-client to strict-ts
  code/lib/core-client/tsconfig.json
Labels: maintenance

#22448 Build: Migrate @storybook/core-events to strict-ts
  code/lib/core-events/tsconfig.json
Labels: maintenance

#22370 Migrate @storybook/instrumenter to strict TS
  code/lib/instrumenter/src/instrumenter.test.ts
  code/lib/instrumenter/src/instrumenter.ts
  code/lib/instrumenter/src/types.ts
  code/lib/instrumenter/tsconfig.json
Labels: maintenance

#22458 Update setup.md with new recipes
  docs/get-started/setup.md
Labels: documentation, patch

#20840 Documentation: Add shard option to the test runner documentation
  docs/writing-tests/test-runner.md
Labels: documentation, patch

#22460 Server: Add json indexer
  code/lib/cli/src/sandbox-templates.ts
  code/renderers/server/package.json
  code/renderers/server/preset.js
  code/renderers/server/src/preset.ts
  code/renderers/server/template/cli/button.stories.json
  code/renderers/server/template/cli/header.stories.json
  code/renderers/server/template/cli/page.stories.json
  code/yarn.lock
  scripts/sandbox/generate.ts
  scripts/tasks/sandbox-parts.ts
Labels: bug, patch, server

#22443 CLI: Fix server init
  code/lib/cli/src/generators/SERVER/index.ts
  code/lib/cli/src/sandbox-templates.ts
  code/renderers/server/package.json
  code/renderers/server/preset.js
  code/renderers/server/src/preset.ts
  code/renderers/server/template/cli/button.stories.json
  code/renderers/server/template/cli/header.stories.json
  code/renderers/server/template/cli/page.stories.json
  code/yarn.lock
  scripts/sandbox/generate.ts
  scripts/tasks/sandbox-parts.ts
Labels: bug, cli, patch, server

#22375 CLI: Fix copyTemplate failures on `init`
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/cli/src/generators/AURELIA/index.ts
  code/lib/cli/src/generators/SERVER/index.ts
  code/lib/cli/src/sandbox-templates.ts
  code/renderers/server/package.json
  code/renderers/server/preset.js
  code/renderers/server/src/preset.ts
  code/renderers/server/template/cli/button.stories.json
  code/renderers/server/template/cli/header.stories.json
  code/renderers/server/template/cli/page.stories.json
  code/yarn.lock
  scripts/sandbox/generate.ts
  scripts/tasks/sandbox-parts.ts
Labels: bug, cli, angular, patch, server

#22162 CLI: Scope styles in sample components from the CLI templates
  code/frameworks/angular/template/cli/header.component.ts
  code/frameworks/angular/template/cli/page.component.ts
  code/frameworks/nextjs/template/cli/js/Header.jsx
  code/frameworks/nextjs/template/cli/js/Page.jsx
  code/frameworks/nextjs/template/cli/ts-3-8/Header.tsx
  code/frameworks/nextjs/template/cli/ts-3-8/Page.tsx
  code/frameworks/nextjs/template/cli/ts/Header.tsx
  code/frameworks/nextjs/template/cli/ts/Page.tsx
  code/lib/cli/rendererAssets/common/header.css
  code/lib/cli/rendererAssets/common/page.css
  code/renderers/html/template/cli/js/Header.js
  code/renderers/html/template/cli/js/Page.js
  code/renderers/html/template/cli/ts-3-8/Header.ts
  code/renderers/html/template/cli/ts-3-8/Page.ts
  code/renderers/html/template/cli/ts-4-9/Header.ts
  code/renderers/html/template/cli/ts-4-9/Page.ts
  code/renderers/preact/template/cli/Header.jsx
  code/renderers/preact/template/cli/Page.jsx
  code/renderers/react/template/cli/js/Header.jsx
  code/renderers/react/template/cli/js/Page.jsx
  code/renderers/react/template/cli/ts-3-8/Header.tsx
  code/renderers/react/template/cli/ts-3-8/Page.tsx
  code/renderers/react/template/cli/ts-4-9/Header.tsx
  code/renderers/react/template/cli/ts-4-9/Page.tsx
  code/renderers/svelte/template/cli/js/Header.svelte
  code/renderers/svelte/template/cli/js/Page.svelte
  code/renderers/svelte/template/cli/ts-3-8/Header.svelte
  code/renderers/svelte/template/cli/ts-3-8/Page.svelte
  code/renderers/svelte/template/cli/ts-4-9/Header.svelte
  code/renderers/svelte/template/cli/ts-4-9/Page.svelte
  code/renderers/vue/template/cli/Header.vue
  code/renderers/vue/template/cli/Page.vue
  code/renderers/vue3/template/cli/js/Header.vue
  code/renderers/vue3/template/cli/js/Page.vue
  code/renderers/vue3/template/cli/ts-3-8/Header.vue
  code/renderers/vue3/template/cli/ts-3-8/Page.vue
  code/renderers/vue3/template/cli/ts-4-9/Header.vue
  code/renderers/vue3/template/cli/ts-4-9/Page.vue
  code/renderers/web-components/template/cli/js/Header.js
  code/renderers/web-components/template/cli/js/Page.js
  code/renderers/web-components/template/cli/ts-3-8/Header.ts
  code/renderers/web-components/template/cli/ts-3-8/Page.ts
  code/renderers/web-components/template/cli/ts-4-9/Header.ts
  code/renderers/web-components/template/cli/ts-4-9/Page.ts
Labels: bug, cli, patch, ci:daily

#21773 Addon Outline: Fix additional outline border in docs mode
  code/addons/outline/src/withOutline.ts
  code/ui/blocks/src/components/Story.tsx
Labels: bug, patch, addon: outline

#22414 MIGRATION: further clarify serving Storybook builds
  MIGRATION.md
Labels: documentation, patch

#21619 UI: Show current search shortcut in search box sidebar
  code/ui/manager/src/components/sidebar/Search.stories.tsx
  code/ui/manager/src/components/sidebar/Search.tsx
Labels: bug, patch, ui: search

#22496 Toolbars: Fix title behavior in UI
  code/addons/toolbars/src/components/ToolbarMenuList.tsx
  code/addons/toolbars/src/components/ToolbarMenuListItem.tsx
  code/addons/toolbars/src/utils/get-selected.ts
Labels: bug, patch, addon: toolbars

#22109 CLI: Do not show a migration summary on sb init
  code/lib/cli/src/automigrate/index.ts
  code/lib/cli/src/automigrate/types.ts
  code/lib/cli/src/initiate.ts
Labels: bug, cli, patch

#22469 docs: fix paren placement
  docs/writing-tests/interaction-testing.md
Labels: documentation, patch

#22501 Sandboxes: Pin @vitejs/plugin-react to avoid conflict
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: other, builder-vite

#22256 Chore:(Docs) Add TS version of testing-library snippet
  docs/snippets/react/component-test-with-testing-library.ts.mdx
  docs/writing-tests/importing-stories-in-tests.md
Labels: documentation, patch

#22497 Maintenance: Fix css inconsistency in Button and Icon components
  code/ui/components/src/Button/Button.tsx
  code/ui/components/src/icon/icon.tsx
Labels: maintenance, patch

#22512 fix windows path when importing storybook-init-renderer-entry
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: bug, patch, builder-webpack5, windows

#22441 Adjust child process I/O for compodoc command
  code/frameworks/angular/src/builders/utils/run-compodoc.spec.ts
  code/frameworks/angular/src/builders/utils/run-compodoc.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
  code/lib/cli/src/js-package-manager/Yarn1Proxy.ts
  code/lib/cli/src/js-package-manager/Yarn2Proxy.ts
Labels: bug, angular, patch, ci:daily

#22392 Prompt to force initialization when storybook folder is detected
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/initiate.ts
Labels: maintenance, cli, patch

#22513 Web-components: Fix source decorator to handle document fragments
  code/renderers/web-components/src/docs/sourceDecorator.test.ts
  code/renderers/web-components/src/docs/sourceDecorator.ts
  code/renderers/web-components/src/types.ts
Labels: bug, patch, addon: docs, web-components, block: source

#22492 CLI: Remove unsupported frameworks/renderers and improve builder detection
  .spelling
  code/.eslintrc.js
  code/addons/links/package.json
  code/addons/storyshots-core/README.md
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/src/frameworks/SupportedFramework.ts
  code/addons/storyshots-core/src/frameworks/rax/loader.ts
  code/addons/storyshots-core/src/frameworks/rax/renderTree.ts
  code/addons/storyshots-core/src/frameworks/riot/loader.ts
  code/addons/storyshots-core/src/frameworks/riot/renderTree.ts
  code/addons/storyshots-core/src/typings.d.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/detect-webpack.ts
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/generators/AURELIA/index.ts
  code/lib/cli/src/generators/MARIONETTE/index.ts
  code/lib/cli/src/generators/MARKO/index.ts
  code/lib/cli/src/generators/MITHRIL/index.ts
  code/lib/cli/src/generators/RAX/index.ts
  code/lib/cli/src/generators/RIOT/index.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/project_types.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
  code/lib/postinstall/src/frameworks.ts
  docs/addons/integration-catalog.md
  docs/frameworks.js
Labels: bug, cli, patch, ci:daily

#22471 CSF: expose story id in composeStories testing utility
  code/lib/preview-api/src/modules/store/csf/testing-utils/index.ts
  code/lib/types/src/modules/composedStory.ts
  code/renderers/react/src/__test__/internals.test.tsx
Labels: bug, patch, csf

#22515 CLI: Throw errors instead of rejecting promises
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/cli/src/initiate.ts
Labels: bug, cli, patch

#22522 Chore: (Docs) Adds documentation on legacy framework deprecation and next steps
  docs/configure/frameworks.md
Labels: documentation, patch

#22514 docs: Include upgrade instructions for yarn
  docs/configure/upgrading.md
Labels: documentation, patch

#22525 Chore: (Docs) Tweaks to the styling and css section
  docs/configure/css-troubleshooting/angular.mdx
  docs/configure/styling-and-css.md
  docs/snippets/common/storybook-preview-import-global-styles.js.mdx
  docs/snippets/common/storybook-preview-import-global-styles.ts.mdx
Labels: documentation, patch

#22517 CLI: Fix storybook upgrade precheckfailure object
  code/lib/cli/src/automigrate/index.ts
  code/lib/cli/src/upgrade.ts
Labels: bug, cli, patch

#22523 CLI: Detach automigrate command from storybook init
  code/lib/cli/src/automigrate/fixes/eslint-plugin.test.ts
  code/lib/cli/src/automigrate/fixes/eslint-plugin.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/automigrate/helpers/eslintPlugin.ts
  code/lib/cli/src/automigrate/helpers/getEslintInfo.ts
  code/lib/cli/src/babel-config.ts
  code/lib/cli/src/generators/REACT_SCRIPTS/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/types.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: maintenance, cli, patch

#22561 CLI: Remove automigrate reference from init command
  code/lib/cli/src/initiate.ts
Labels: bug, cli, patch

#22559 CLI: Fix `getFrameworkPackage` logic
  code/lib/cli/src/generators/baseGenerator.ts
Labels: bug, cli, patch

#22433 Chore:(Docs) Add TS version of Svelte snippet(get-started)
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/get-started/why-storybook.md
  docs/snippets/svelte/button-story-with-args.ts-4-9.mdx
  docs/snippets/svelte/button-story-with-args.ts.mdx
  docs/snippets/svelte/button-story.ts-4-9.mdx
  docs/snippets/svelte/button-story.ts.mdx
  docs/snippets/svelte/histogram-story.ts-4-9.mdx
  docs/snippets/svelte/histogram-story.ts.mdx
  docs/snippets/svelte/your-component.ts-4-9.mdx
  docs/snippets/svelte/your-component.ts.mdx
Labels: documentation, patch

#22535 Fix broken link in Storybook and docs
  code/ui/manager/src/settings/SettingsFooter.tsx
  docs/get-started/install.md
Labels: ui, documentation, patch

#22562 7.0.12 patch release
  code/frameworks/angular/src/client/docs/sourceDecorator.ts
  code/lib/cli/src/automigrate/fixes/eslint-plugin.test.ts
  code/lib/cli/src/automigrate/fixes/eslint-plugin.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/automigrate/helpers/eslintPlugin.ts
  code/lib/cli/src/automigrate/helpers/getEslintInfo.ts
  code/lib/cli/src/babel-config.ts
  code/lib/cli/src/generators/REACT_SCRIPTS/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/types.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts
  code/lib/preview-api/src/modules/store/StoryStore.test.ts
  code/lib/preview-api/src/modules/store/StoryStore.ts
  code/lib/preview-api/src/modules/store/args.test.ts
  code/lib/preview-api/src/modules/store/args.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/preview-api/src/modules/store/csf/testing-utils/index.ts
  code/lib/types/src/modules/story.ts
  code/renderers/html/src/docs/sourceDecorator.test.ts
  code/renderers/html/src/docs/sourceDecorator.ts
  code/renderers/react/src/docs/jsxDecorator.test.tsx
  code/renderers/react/src/docs/jsxDecorator.tsx
  code/renderers/svelte/src/docs/sourceDecorator.ts
  code/renderers/vue/src/docs/sourceDecorator.ts
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/renderers/web-components/src/docs/sourceDecorator.test.ts
  code/renderers/web-components/src/docs/sourceDecorator.ts
  code/ui/blocks/src/blocks/Source.tsx
  code/ui/blocks/src/blocks/useArgs.ts
  docs/get-started/setup.md
  docs/get-started/whats-a-story.md
  docs/get-started/why-storybook.md
  docs/snippets/svelte/button-story-with-args.ts-4-9.mdx
  docs/snippets/svelte/button-story-with-args.ts.mdx
  docs/snippets/svelte/button-story.ts-4-9.mdx
  docs/snippets/svelte/button-story.ts.mdx
  docs/snippets/svelte/histogram-story.ts-4-9.mdx
  docs/snippets/svelte/histogram-story.ts.mdx
  docs/snippets/svelte/your-component.ts-4-9.mdx
  docs/snippets/svelte/your-component.ts.mdx
Labels: maintenance, ci:merged

#22327 Normalize paths exposed to vite-builder's `storybook-stories.js` file
  code/lib/builder-vite/src/list-stories.ts
Labels: bug, builder-vite, windows

#22393 Fix: remove the alias for `global`
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: bug, patch, builder-webpack5

#22584 Chore: (Docs) - Removes reference to the Storybook deployer
  docs/sharing/publish-storybook.md
Labels: documentation, patch

#22576 add legacy font formats
  code/lib/builder-manager/src/index.ts
Labels: bug, patch, builder-manager

#22455 addon-actions: Fix type of withActions
  code/addons/actions/src/decorator.ts
Labels: maintenance

#22592 Chore: (Docs) Naming components and hierarchy updates
  docs/writing-stories/naming-components-and-hierarchy.md
  docs/writing-stories/naming-hierarchy-sidebar-anatomy.png
Labels: documentation, patch

#22620 Build: Fix sandbox generation scripts
  .github/workflows/generate-sandboxes-next.yml
  code/lib/cli/src/sandbox-templates.ts
Labels: patch, build

#22625 Build: set correct ref on sandboxes Github action
  .github/workflows/generate-sandboxes-next.yml
Labels: patch, build

#22638 Build: add discord notification when generating sandboxes fails
  .github/workflows/generate-sandboxes-main.yml
  .github/workflows/generate-sandboxes-next.yml
Labels: patch, build

#22635 CLI: Fix pnpm init command
  code/lib/cli/src/js-package-manager/PNPMProxy.test.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
Labels: bug, cli, patch, reported

#22644 CLI: Account for windows paths when copying templates
  code/lib/cli/src/dirs.ts
  code/lib/cli/src/helpers.ts
Labels: bug, cli, patch

#22651 CLI: Skip prompting for eslint plugin with --yes flag
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/types.ts
  code/lib/cli/src/initiate.ts
Labels: bug, cli, patch

#22663 CLI: Improve error handling when dealing with angular.json files
  code/lib/cli/src/generators/ANGULAR/index.ts
Labels: bug, cli, patch

#22671 Remove console.log
  code/frameworks/angular/src/client/angular-beta/RendererFactory.ts
Labels: maintenance

#21473 fix: Storybook does not respect BROWSER env var
  code/lib/core-server/src/utils/open-in-browser.ts
Labels: feature request

#22575 only connect to serverChannel in development mode
  code/lib/builder-manager/src/utils/template.ts
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/ui/manager/src/runtime.ts
Labels: bug, patch, builder-manager

#22687 CLI: Only handle CTRL + C on init event
  code/lib/core-server/src/withTelemetry.ts
Labels: maintenance, cli, patch

#22668 7.0.13 patch release
  .github/workflows/generate-sandboxes-main.yml
  .github/workflows/generate-sandboxes-next.yml
  CHANGELOG.md
  code/frameworks/angular/jest.config.js
  code/frameworks/angular/package.json
  code/frameworks/angular/setup-jest.ts
  code/frameworks/angular/src/builders/build-storybook/index.spec.ts
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/index.spec.ts
  code/frameworks/angular/src/builders/utils/run-compodoc.spec.ts
  code/frameworks/angular/src/builders/utils/run-compodoc.ts
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/RendererFactory.test.ts
  code/frameworks/angular/src/client/angular-beta/RendererFactory.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/docs/angular-properties.test.ts
  code/frameworks/angular/src/client/docs/compodoc.test.ts
  code/frameworks/angular/src/client/render.ts
  code/frameworks/angular/src/server/framework-preset-angular-cli.test.ts
  code/jest.config.js
  code/lib/builder-manager/src/index.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/cli/package.json
  code/lib/cli/src/dirs.ts
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/types.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/js-package-manager/NPMProxy.test.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.test.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
  code/lib/cli/src/js-package-manager/Yarn1Proxy.test.ts
  code/lib/cli/src/js-package-manager/Yarn1Proxy.ts
  code/lib/cli/src/js-package-manager/Yarn2Proxy.test.ts
  code/lib/cli/src/js-package-manager/Yarn2Proxy.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/cli/src/upgrade.test.ts
  code/lib/cli/src/upgrade.ts
  code/lib/cli/src/utils.ts
  code/lib/core-server/src/withTelemetry.ts
  code/lib/telemetry/src/types.ts
  code/package.json
  code/ui/manager/src/settings/SettingsFooter.tsx
  code/yarn.lock
  docs/get-started/install.md
  docs/sharing/publish-storybook.md
  docs/writing-stories/naming-components-and-hierarchy.md
  docs/writing-stories/naming-hierarchy-sidebar-anatomy.png
  docs/writing-stories/parameters.md
Labels: maintenance, ci:merged

#22690 CLI: Fix error parsing on NPM proxy
  code/lib/cli/src/js-package-manager/NPMProxy.test.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
Labels: bug, cli, patch

#22691 7.0.14 patch release
  CHANGELOG.md
  code/lib/builder-manager/src/utils/template.ts
  code/lib/builder-vite/input/iframe.html
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/lib/builder-vite/src/transform-iframe-html.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/lib/channel-websocket/src/index.ts
  code/lib/cli/src/js-package-manager/NPMProxy.test.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
  code/ui/manager/src/runtime.ts
  code/ui/manager/src/settings/typings.d.ts
Labels: maintenance, ci:merged

#22697 Next.js: add compatibility with Next 13.4.3
  code/frameworks/nextjs/package.json
  code/frameworks/nextjs/src/nodePolyfills/webpack.ts
  code/frameworks/nextjs/src/preset.ts
  code/yarn.lock
Labels: bug, patch, nextjs, ci:daily

#22075 storybook webpack builder to use swc instead of babel
  code/lib/builder-webpack5/package.json
  code/lib/builder-webpack5/src/preview/babel-loader-preview.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/builder-webpack5/src/preview/loaders.ts
  code/lib/builder-webpack5/src/types.ts
  code/lib/cli/src/sandbox-templates.ts
  code/yarn.lock
Labels: maintenance, builder-webpack5, ci:daily

#22699 UI: Fix `.mp3` support for builder-manager
  code/lib/builder-manager/src/index.ts
Labels: feature request, patch, builder-manager

#22700 Vite: Fix missing @storybook/global dependency
  code/lib/builder-vite/package.json
  code/yarn.lock
Labels: bug, patch, builder-vite

#22709 Vite: Fix pnpm support by replacing @storybook/global with `window`
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/yarn.lock
Labels: bug, builder-vite, pnpm

#22711 7.0.16 release
  CHANGELOG.md
  code/lib/builder-manager/src/utils/data.ts
  code/lib/builder-manager/src/utils/template.ts
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/codegen-set-addon-channel.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/types/src/modules/core-common.ts
  code/yarn.lock
Labels: maintenance, ci:merged

#22688 doc: link 'Image, fonts, and assets' to static `preview-head.html`; enhance code snippet to demonstrate relative pathing
  docs/configure/images-and-assets.md
  docs/snippets/common/storybook-preview-head-example.html.mdx
Labels: documentation, patch

#22685 Vue3: Bring back new tests to main
  code/frameworks/nextjs/template/stories_nextjs-12-js/ImageFuture.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-12-js/Link.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Font.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Font.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Head.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/ImageLegacy.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Link.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Link.stories.module.css
  code/frameworks/nextjs/template/stories_nextjs-default-js/Navigation.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Router.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/fonts/OFL.txt
  code/frameworks/nextjs/template/stories_nextjs-default-js/fonts/RubikStorm-Regular.ttf
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.module.css
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.tsx
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Navigation.stories.tsx
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderFunctionalComponent.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/CustomRenderOptionsArgsFromData.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/ReactiveDecorators.stories.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/Reactivity.vue
  scripts/tasks/sandbox-parts.ts
Labels: build

#22750 Fix `includeNames` typo
  docs/writing-stories/naming-components-and-hierarchy.md
Labels: documentation, patch

#22713 Document v7 storySort changes
  MIGRATION.md
Labels: documentation, patch

#22717 Vue3: Fix reactive args updates in decorators
  code/addons/controls/template/stories/basics.stories.ts
  code/addons/controls/template/stories/conditional.stories.ts
  code/addons/controls/template/stories/disable.stories.ts
  code/addons/controls/template/stories/filters.stories.ts
  code/addons/controls/template/stories/issues.stories.ts
  code/addons/controls/template/stories/matchers.stories.ts
  code/addons/controls/template/stories/sorting.stories.ts
  code/lib/store/template/stories/argMapping.stories.ts
  code/lib/store/template/stories/argTypes.stories.ts
  code/lib/store/template/stories/args.stories.ts
  code/renderers/vue3/src/decorateStory.ts
  code/renderers/vue3/src/docs/sourceDecorator.ts
Labels: bug, patch, args, vue3

#22694 Build: Update Nx to latest version
  code/nx.json
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: build

#22812 Build: Revert conditional decorator story and downgrade Typescript version
  code/lib/store/template/stories/decorators.stories.ts
  code/package.json
  code/yarn.lock
Labels: build, ci:daily

#22805 Build: Fix the local storybook
  code/lib/builder-vite/package.json
  code/ui/.storybook/main.ts
Labels: bug, builder-vite

#22815 Build: Add more checks to ci:daily workflow
  .circleci/config.yml
Labels: patch, build, ci:daily

#22816 Build: Fix Nextjs E2E tests
  code/e2e-tests/framework-nextjs.spec.ts
Labels: build, ci:daily

#22824 Build: update babel dependencies to fix sandbox creation
  code/builders/builder-webpack5/package.json
  code/frameworks/nextjs/package.json
  code/frameworks/nextjs/src/babel/plugins/jsx-pragma.ts
  code/frameworks/nextjs/src/babel/plugins/next-page-config.ts
  code/frameworks/nextjs/src/babel/plugins/next-ssg-transform.ts
  code/frameworks/nextjs/src/routing/app-router-provider.tsx
  code/frameworks/react-webpack5/package.json
  code/frameworks/web-components-webpack5/package.json
  code/lib/cli/package.json
  code/lib/codemod/package.json
  code/lib/csf-tools/package.json
  code/lib/docs-tools/package.json
  code/package.json
  code/presets/react-webpack/package.json
  code/presets/web-components-webpack/package.json
  code/renderers/react/package.json
  code/renderers/server/package.json
  code/renderers/svelte/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
Labels: build

#22841 Build: fix the theme output during development
  code/lib/theming/scripts/fix-theme-type-export.ts
Labels: build

#22846 Build: cleanup the test-storybooks
  test-storybooks/ember-cli/package.json
  test-storybooks/ember-cli/yarn.lock
  test-storybooks/external-docs/package.json
  test-storybooks/external-docs/yarn.lock
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/server-kitchen-sink/yarn.lock
  test-storybooks/standalone-preview/package.json
  test-storybooks/standalone-preview/yarn.lock
Labels: build

#22847 Build: sort package json files
  package.json
  scripts/package.json
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: build

#22487 Migrate @storybook/addon-storyshots to strict TS
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/src/Stories2SnapsConverter.test.ts
  code/addons/storyshots-core/src/Stories2SnapsConverter.ts
  code/addons/storyshots-core/src/api/StoryshotsOptions.ts
  code/addons/storyshots-core/src/api/index.ts
  code/addons/storyshots-core/src/frameworks/configure.ts
  code/addons/storyshots-core/src/frameworks/frameworkLoader.ts
  code/addons/storyshots-core/tsconfig.json
  code/frameworks/angular/src/client/angular-beta/StorybookModule.ts
Labels: maintenance

#22659 migrate @storybook/addon-mdx-gfm to strict TS
  code/addons/gfm/tsconfig.json
Labels: maintenance

#22389 Build: Migrate @storybook/addon-jest to strict TS
  code/addons/jest/package.json
  code/addons/jest/src/components/Message.tsx
  code/addons/jest/src/components/Panel.tsx
  code/addons/jest/src/components/Result.tsx
  code/addons/jest/src/hoc/provideJestResult.tsx
  code/addons/jest/src/shared.ts
  code/addons/jest/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22407 Migrate @storybook/addon-storyshots-puppeteer to strict TS
  code/addons/storyshots-puppeteer/package.json
  code/addons/storyshots-puppeteer/src/config.ts
  code/addons/storyshots-puppeteer/tsconfig.json
Labels: maintenance

#22856 Chore: (Docs) Removes references to outdated APIs and packages
  MIGRATION.md
  docs/essentials/toolbars-and-globals.md
  docs/faq.md
  docs/snippets/common/storybook-client-preview.ts.mdx
Labels: documentation, patch

#22863 Chore: (Docs) Updates to the migration & upgrade docs
  docs/configure/babel.md
  docs/configure/upgrading.md
  docs/migration-guide.md
Labels: documentation, patch
