Repository storybookjs/storybook, pull requests merged in 2023-06, with the labels that each got.

#22398 Error on YN0060 - INCOMPATIBLE_PEER_DEPENDENCY
  code/renderers/svelte/package.json
  code/yarn.lock
  scripts/utils/yarn.ts
Labels: build, ci:daily

#22880 Chore: (Documentation). Adds video to the Sidebars and URLs documentation
  docs/configure/sidebar-and-urls.md
Labels: documentation, patch

#22843 Optimize webpack-builder: minify using swc
  code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: maintenance, builder-webpack5

#22399 Migrate @storybook/web-components to strict TS
  code/renderers/web-components/package.json
  code/renderers/web-components/src/docs/config.ts
  code/renderers/web-components/src/docs/custom-elements.test.ts
  code/renderers/web-components/src/docs/custom-elements.ts
  code/renderers/web-components/src/render.ts
  code/renderers/web-components/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22869 Add CODEOWNERS
  .github/CODEOWNERS
Labels: other

#22906 Server: Fix .stories.yml support
  code/lib/cli/src/sandbox-templates.ts
  code/presets/server-webpack/src/index.ts
  code/presets/server-webpack/src/loader.ts
  code/renderers/server/package.json
  code/renderers/server/src/preset.ts
  code/yarn.lock
Labels: bug, patch, server

#22835 Docs: E2E tests for Source block update fix
  code/e2e-tests/addon-docs.spec.ts
  code/ui/blocks/src/blocks/SourceContainer.tsx
Labels: bug, addon: docs, run e2e extended test suite

#22911 Add autodocs clarification
  docs/writing-docs/autodocs.md
Labels: documentation, patch

#22873 Core: Fix indexing errors by excluding node_modules stories
  MIGRATION.md
  code/builders/builder-vite/src/list-stories.ts
  code/lib/cli/src/automigrate/fixes/mdx-gfm.ts
  code/lib/core-common/src/index.ts
  code/lib/core-common/src/utils/common-glob-options.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/watch-story-specifiers.ts
Labels: bug, patch, core

#22934 Revert "Docs: E2E tests for Source block update fix"
  code/e2e-tests/addon-docs.spec.ts
Labels: maintenance

#22939 experiment with universal channel
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/codegen-set-addon-channel.ts
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/frameworks/html-vite/package.json
  code/lib/channel-postmessage/package.json
  code/lib/channel-postmessage/src/index.ts
  code/lib/channel-postmessage/src/typings.d.ts
  code/lib/channels/src/index.test.ts
  code/lib/channels/src/index.ts
  code/lib/manager-api/src/modules/channel.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.test.ts
  code/ui/blocks/src/blocks/external/ExternalPreview.ts
  code/ui/manager/package.json
  code/ui/manager/src/runtime.ts
  code/ui/manager/src/typings.d.ts
  code/yarn.lock
Labels: feature request, core

#22890 Feature: add a status API
  code/lib/manager-api/src/index.tsx
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
Labels: feature request, core

#22948 Dependencies: upgrade `overlayscrollbars`
  code/lib/core-server/package.json
  code/package.json
  code/ui/components/package.json
  code/ui/components/src/ScrollArea/GlobalScrollAreaStyles.tsx
  code/ui/components/src/ScrollArea/OverlayScrollbars.tsx
  code/ui/components/src/ScrollArea/ScrollArea.stories.tsx
  code/ui/components/src/ScrollArea/ScrollArea.tsx
  code/yarn.lock
Labels: dependencies

#22952 Dependencies: upgrade `webpack-dev-server`, remove types package for it
  code/builders/builder-webpack5/package.json
  code/yarn.lock
Labels: dependencies

#22953 Dependencies: upgrade `wait-on`
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#22402 Migrate @storybook/addon-measure to strict TS
  code/addons/measure/package.json
  code/addons/measure/src/box-model/canvas.ts
  code/addons/measure/src/box-model/labels.ts
  code/addons/measure/src/box-model/visualizer.ts
  code/addons/measure/tsconfig.json
  code/yarn.lock
Labels: maintenance

#22861 Chore: (Docs) Adds useSWC documentation as alternative to Babel
  docs/configure/babel.md
  docs/configure/overview.md
  docs/snippets/common/storybook-enable-swc-loader.js.mdx
  docs/snippets/common/storybook-enable-swc-loader.ts.mdx
Labels: documentation

#22957 Angular: Silence compodoc when running storybook with --quiet
  code/frameworks/angular/src/builders/start-storybook/index.ts
Labels: bug, cli, angular, patch, ci:merged

#22962 Dependencies: upgrade some webpack plugins
  code/builders/builder-webpack5/package.json
  code/frameworks/angular/package.json
  code/frameworks/nextjs/package.json
  code/yarn.lock
Labels: dependencies

#22964 Angular: Add --open/--no-open flag to dev command
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/schema.json
Labels: bug, cli, angular, patch

#22966 [Documentation]: Remove usage of <LinkWithVersion>
  docs/configure/babel.md
  docs/writing-docs/mdx.md
Labels: documentation, patch

#22967 Chore: (Docs) Removes typo in babel documentation
  docs/configure/babel.md
Labels: documentation

#22963 Maintenance: improve overlayscrollbars component
  code/ui/components/package.json
  code/ui/components/src/ScrollArea/OverlayScrollbars.tsx
  code/ui/components/src/ScrollArea/ScrollArea.tsx
  code/yarn.lock
Labels: maintenance

#22782 Core: Improve MDX of error in story index
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
Labels: maintenance, patch, story index

#22969 Dependencies: upgrade `type-fest`, `upath`, `magic-string`, `unplugin`, `js-yaml`, `danger` and remove `rimraf`, replace `isomorphic-unfetch` for `node-fetch`
  code/addons/jest/package.json
  code/addons/storyshots-core/package.json
  code/addons/storyshots-puppeteer/package.json
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/plugins/csf-plugin.ts
  code/frameworks/angular/package.json
  code/frameworks/html-vite/package.json
  code/frameworks/react-vite/package.json
  code/frameworks/svelte-vite/package.json
  code/frameworks/vue-vite/package.json
  code/frameworks/vue3-vite/package.json
  code/frameworks/web-components-vite/package.json
  code/jest.config.base.js
  code/lib/core-common/package.json
  code/lib/csf-plugin/package.json
  code/lib/csf-plugin/tsconfig.json
  code/lib/csf-tools/package.json
  code/lib/csf-tools/src/CsfFile.test.ts
  code/lib/telemetry/package.json
  code/lib/telemetry/src/storybook-metadata.test.ts
  code/lib/telemetry/src/telemetry.test.ts
  code/lib/telemetry/src/telemetry.ts
  code/lib/telemetry/tsconfig.json
  code/package.json
  code/renderers/react/package.json
  code/renderers/svelte/package.json
  code/renderers/vue/package.json
  code/renderers/vue3/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#22968 Maintenance: add jsdoc comments to manager-api APIs
  code/lib/manager-api/src/modules/addons.ts
  code/lib/manager-api/src/modules/channel.ts
  code/lib/manager-api/src/modules/globals.ts
  code/lib/manager-api/src/modules/layout.ts
  code/lib/manager-api/src/modules/notifications.ts
  code/lib/manager-api/src/modules/provider.ts
  code/lib/manager-api/src/modules/refs.ts
  code/lib/manager-api/src/modules/release-notes.ts
  code/lib/manager-api/src/modules/settings.ts
  code/lib/manager-api/src/modules/shortcuts.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/modules/url.ts
  code/lib/manager-api/src/modules/versions.ts
Labels: maintenance, core, typescript

#22518 Vue3: fix source decorator to generate proper story code
  code/renderers/vue3/src/docs/sourceDecorator.test.ts
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/renderers/vue3/src/docs/utils.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/SourceDecorator.stories.ts
Labels: bug, vue3, ci:daily

#22449 upgrade nx to add support for darwin-x64
  code/package.json
  code/yarn.lock
Labels: maintenance

#22976 Maintenance: update dependencies within existing semver range (regen lockfiles)
  code/yarn.lock
  scripts/yarn.lock
Labels: dependencies

#22974 fix: Build manager adding multiple dashes to relative path
  code/builders/builder-manager/src/utils/managerEntries.ts
Labels: bug, patch

#22959 Release: New release tooling
  .github/workflows/canary-release-pr.WIP
  .github/workflows/check-release-tasks.yml
  .github/workflows/danger-js.yml
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  .github/workflows/publish.yml
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  CHANGELOG.prerelease.md
  code/__mocks__/fs-extra.js
  scripts/__mocks__/simple-git.js
  scripts/__mocks__/uuid.ts
  scripts/dangerfile.ts
  scripts/package.json
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/__tests__/version.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/get-changelog-from-file.ts
  scripts/release/get-current-version.ts
  scripts/release/get-version-changelog.ts
  scripts/release/is-pr-frozen.ts
  scripts/release/is-prerelease.ts
  scripts/release/is-version-published.ts
  scripts/release/label-patches.ts
  scripts/release/pick-patches.ts
  scripts/release/publish.ts
  scripts/release/unreleased-changes-exists.ts
  scripts/release/utils/__mocks__/get-github-info.js
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-github-info.ts
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/utils/git-client.ts
  scripts/release/utils/github-client.ts
  scripts/release/version.ts
  scripts/release/write-changelog.ts
  scripts/yarn.lock
Labels: build

#22979 Maintenance: upgrades of jest related packages
  code/addons/interactions/package.json
  code/addons/interactions/preset.js
  code/addons/interactions/src/preset.ts
  code/addons/storyshots-core/package.json
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/frameworks/react-webpack5/package.json
  code/lib/codemod/package.json
  code/lib/core-server/package.json
  code/lib/csf-tools/package.json
  code/lib/docs-tools/package.json
  code/lib/postinstall/package.json
  code/lib/preview-api/package.json
  code/lib/source-loader/package.json
  code/package.json
  code/presets/server-webpack/package.json
  code/renderers/react/package.json
  code/renderers/vue3/src/docs/sourceDecorator.test.ts
  code/yarn.lock
Labels: maintenance

#22992 Build: Upgrade playwright to 1.35.0
  .circleci/config.yml
  code/package.json
  code/yarn.lock
  scripts/utils/yarn.ts
Labels: patch, build

#22996 Build: Fix CI with conflicting playwright version
  code/package.json
  code/yarn.lock
Labels: build

#22995 Maintenance: Remove `shelljs` use
  code/addons/storyshots-puppeteer/package.json
  code/frameworks/angular/package.json
  code/lib/cli/package.json
  code/lib/cli/src/link.ts
  code/lib/cli/src/repro-generators/scripts.ts
  code/lib/codemod/package.json
  code/yarn.lock
  scripts/package.json
  scripts/utils/command.ts
  scripts/yarn.lock
Labels: maintenance

#22997 Release: Rework versioning command
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  code/package.json
  scripts/release/__tests__/version.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/version.ts
  scripts/utils/workspace.ts
Labels: build

#23002 Process: Remove `CODEOWNERS`
  .github/CODEOWNERS
Labels: build

#23001 CI: Improve DangerJS workflow
  .github/workflows/danger-js.yml
Labels: build

#23003 Release: Don't pick patches when prereleasing
  .github/workflows/publish.yml
Labels: build

#22999 Build: Fix playwright issues on main
  .circleci/config.yml
  code/package.json
  code/yarn.lock
  scripts/utils/yarn.ts
Labels: build

#19183 Web-components: Fix custom-elements order of property application
  code/renderers/web-components/src/docs/__testfixtures__/lit-element-demo-card/properties.snapshot
  code/renderers/web-components/src/docs/custom-elements.ts
  code/renderers/web-components/template/stories/custom-elements.json
  code/renderers/web-components/template/stories/demo-wc-card.stories.js
  code/renderers/web-components/template/stories/demo-wc-card/DemoWcCard.js
Labels: bug, patch, web-components

#23004 Release: Fix references to repository
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/pick-patches.ts
  scripts/release/utils/get-unpicked-prs.ts
Labels: build

#23006 Release: Fix permissions for publish script
  .github/workflows/publish.yml
Labels: build

#23005 Dependencies: Upgrade `nanoid`, prebundle it, upgrade `remark`, cleanup some `.md` files for warnings
  code/addons/jest/README.md
  code/frameworks/nextjs/README.md
  code/frameworks/svelte-webpack5/README.md
  code/lib/preview-api/README-core-client.md
  code/lib/telemetry/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#23009 Release: Fix not escaping content of GH Releases
  scripts/release/get-changelog-from-file.ts
Labels: build

#23008 Build: Release tooling for main
  .github/workflows/canary-release-pr.WIP
  .github/workflows/check-release-tasks.yml
  .github/workflows/danger-js.yml
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  .github/workflows/publish.yml
  .yarnrc.yml
  CHANGELOG.prerelease.md
  code/__mocks__/fs-extra.js
  code/package.json
  scripts/__mocks__/simple-git.js
  scripts/__mocks__/uuid.ts
  scripts/dangerfile.ts
  scripts/package.json
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/__tests__/version.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/get-changelog-from-file.ts
  scripts/release/get-current-version.ts
  scripts/release/get-version-changelog.ts
  scripts/release/is-pr-frozen.ts
  scripts/release/is-prerelease.ts
  scripts/release/is-version-published.ts
  scripts/release/label-patches.ts
  scripts/release/pick-patches.ts
  scripts/release/publish.ts
  scripts/release/unreleased-changes-exists.ts
  scripts/release/utils/__mocks__/get-github-info.js
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-github-info.ts
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/utils/git-client.ts
  scripts/release/utils/github-client.ts
  scripts/release/version.ts
  scripts/release/write-changelog.ts
  scripts/utils/options.ts
  scripts/utils/workspace.ts
  scripts/yarn.lock
Labels: build

#23011 Dependencies: Use `latest` version of `vue-tsc` & sync versions of `angular`
  code/addons/storyshots-core/package.json
  code/renderers/vue/package.json
  code/renderers/vue3/package.json
  code/yarn.lock
Labels: dependencies

#22982 Build: Add template stories to our main storybook
  code/ui/.storybook/main.ts
  code/ui/.storybook/preview.tsx
Labels: build

#23015 Dependencies: Set vue-component-type-helpers to latest
  code/renderers/vue3/package.json
  code/yarn.lock
Labels: dependencies

#23016 Release: Fix release and changelog generation
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/generate-pr-description.ts
  scripts/release/unreleased-changes-exists.ts
  scripts/release/utils/get-changes.ts
Labels: patch, build

#23023 Revert "Build: Add template stories to our main storybook"
  code/ui/.storybook/main.ts
  code/ui/.storybook/preview.tsx
Labels: build

#23024 Release: Fix branch name in isPrFrozen
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/is-pr-frozen.ts
Labels: build

#23017 Build: Remove `babel-core` & upgrade `esbuild`
  code/builders/builder-manager/package.json
  code/lib/core-common/package.json
  code/package.json
  code/renderers/vue3/package.json
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/renderers/vue3/template/stories_vue3-vite-default-ts/GlobalSetup.stories.ts
  code/renderers/vue3/tsconfig.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#22984 Docs: Update useSWC API reference
  docs/api/main-config-core.md
  docs/api/main-config-features.md
  docs/api/main-config-framework.md
  docs/configure/babel.md
  docs/configure/overview.md
  docs/snippets/common/main-config-framework-options-builder-use-swc.js.mdx
  docs/snippets/common/main-config-framework-options-builder-use-swc.ts.mdx
Labels: documentation

#23018 Core: Disable esbuild on files imported from `node_modules`
  code/lib/core-common/src/utils/interpret-require.ts
Labels: maintenance, performance issue, core

#23019 React: Lazy import `react-docgen-typescript-plugin`
  code/presets/react-webpack/src/framework-preset-react-docs.ts
Labels: maintenance, react, performance issue

#22940 Core: Integrate serverChannel into channel, make serverChannel bi-directional and extendable
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/codegen-set-addon-channel.ts
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/frameworks/html-vite/package.json
  code/lib/channel-postmessage/package.json
  code/lib/channel-postmessage/src/index.ts
  code/lib/channel-postmessage/src/typings.d.ts
  code/lib/channel-websocket/src/index.ts
  code/lib/channel-websocket/src/typings.d.ts
  code/lib/channels/src/index.test.ts
  code/lib/channels/src/index.ts
  code/lib/core-server/package.json
  code/lib/core-server/src/dev-server.ts
  code/lib/core-server/src/utils/get-server-channel.ts
  code/lib/manager-api/src/lib/addons.ts
  code/lib/manager-api/src/modules/channel.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
  code/lib/preview-api/src/modules/addons/main.ts
  code/lib/preview-api/src/modules/preview-web/Preview.tsx
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.test.ts
  code/lib/types/src/modules/api.ts
  code/ui/blocks/src/blocks/external/ExternalPreview.ts
  code/ui/manager/package.json
  code/ui/manager/src/runtime.ts
  code/ui/manager/src/typings.d.ts
  code/yarn.lock
Labels: feature request, core

#23031 Build: Improve tasks and child-process spawning
  code/lib/cli/src/link.ts
  code/lib/cli/src/repro-generators/scripts.ts
  node_modules/.yarn-state.yml
  package.json
  scripts/check-dependencies.js
  scripts/tasks/install.ts
  scripts/utils/cli-utils.js
  yarn.lock
Labels: build

#22928 CLI: Run `storybook dev` as part of `storybook init`
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/schema.json
  code/lib/cli/src/dev.ts
  code/lib/cli/src/generate.ts
  code/lib/cli/src/initiate.ts
  code/lib/core-server/src/dev-server.ts
  code/lib/core-server/src/utils/server-address.test.ts
  code/lib/core-server/src/utils/server-address.ts
  code/lib/types/src/modules/core-common.ts
  scripts/task.ts
  scripts/tasks/sandbox-parts.ts
Labels: feature request, cli

#23032 Maintenance: Deprecate channel packages, merge into a single browserChannel, update builders
  code/addons/storyshots-core/src/frameworks/configure.ts
  code/addons/storyshots-core/src/typings.d.ts
  code/builders/builder-vite/src/codegen-set-addon-channel.ts
  code/builders/builder-vite/src/optimizeDeps.ts
  code/builders/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars
  code/deprecated/channel-postmessage/README.md
  code/deprecated/channel-postmessage/jest.config.js
  code/deprecated/channel-postmessage/package.json
  code/deprecated/channel-postmessage/project.json
  code/deprecated/channel-postmessage/src/entry.ts
  code/deprecated/channel-postmessage/tsconfig.json
  code/deprecated/channel-websocket/README.md
  code/deprecated/channel-websocket/jest.config.js
  code/deprecated/channel-websocket/package.json
  code/deprecated/channel-websocket/project.json
  code/deprecated/channel-websocket/src/entry.ts
  code/deprecated/channel-websocket/tsconfig.json
  code/lib/channel-websocket/src/typings.d.ts
  code/lib/channels/package.json
  code/lib/channels/src/index.ts
  code/lib/channels/src/main.ts
  code/lib/channels/src/postmessage/getEventSourceUrl.ts
  code/lib/channels/src/postmessage/index.ts
  code/lib/channels/src/types.ts
  code/lib/channels/src/typings.d.ts
  code/lib/channels/src/websocket/index.ts
  code/lib/preview-api/src/modules/core-client/start.test.ts
  code/lib/preview-api/src/modules/core-client/start.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.integration.test.ts
  code/lib/preview/package.json
  code/lib/preview/src/globals/runtime.ts
  code/ui/manager/src/globals/exports.ts
  code/ui/manager/src/runtime.ts
  code/yarn.lock
Labels: maintenance

#22079 Core: Unify cache location configurability
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/plugins/external-globals-plugin.ts
  code/builders/builder-vite/src/vite-config.ts
  code/lib/core-common/package.json
  code/lib/core-common/src/utils/resolve-path-in-sb-cache.ts
  code/yarn.lock
Labels: feature request, core

#23046 Release tooling: Give the full commit hash to the github API
  scripts/release/utils/get-github-info.ts
  scripts/release/utils/get-unpicked-prs.ts
Labels: patch, build

#23047 Release tooling: Fix commit comparing
  scripts/release/generate-pr-description.ts
Labels: patch, build

#23049 Bug: Add the missing dependency after the change to use lib/channels
  code/builders/builder-vite/package.json
  code/yarn.lock
Labels: bug

#23058 Docs: Clarify APIs of Controls doc block/addon/argTypes
  docs/api/doc-block-controls.md
Labels: documentation, patch

#23064 Bug: Fix for angular 16.1 compatibility
  code/frameworks/angular/src/server/angular-cli-webpack.js
Labels: bug, angular, patch

#23051 Build: Fix E2E and chromatic inconsistencies
  code/e2e-tests/addon-viewport.spec.ts
  code/renderers/react/template/stories/ts-argtypes.stories.tsx
  code/ui/.storybook/preview.tsx
  code/ui/blocks/src/blocks/DocsPage.stories.tsx
  code/ui/manager/src/components/layout/app.mockdata.tsx
Labels: build, ci:daily

#23066 Build: Use local registry for all packages
  code/lib/cli/src/repro-generators/scripts.ts
  scripts/utils/yarn.ts
Labels: patch, build

#22951 CLI: Change Button stories layout for React starter templates
  code/frameworks/nextjs/template/cli/js/Button.stories.js
  code/frameworks/nextjs/template/cli/ts-3-8/Button.stories.ts
  code/frameworks/nextjs/template/cli/ts-3-8/Introduction.mdx
  code/frameworks/nextjs/template/cli/ts-4-9/Button.stories.ts
  code/frameworks/nextjs/template/cli/ts-4-9/Button.tsx
  code/frameworks/nextjs/template/cli/ts-4-9/Header.stories.ts
  code/frameworks/nextjs/template/cli/ts-4-9/Header.tsx
  code/frameworks/nextjs/template/cli/ts-4-9/Introduction.mdx
  code/frameworks/nextjs/template/cli/ts-4-9/Page.stories.ts
  code/frameworks/nextjs/template/cli/ts-4-9/Page.tsx
  code/renderers/react/template/cli/js/Button.stories.js
  code/renderers/react/template/cli/ts-3-8/Button.stories.ts
  code/renderers/react/template/cli/ts-3-8/Header.stories.ts
  code/renderers/react/template/cli/ts-4-9/Button.stories.ts
  code/renderers/react/template/cli/ts-4-9/Header.stories.ts
  code/ui/manager/src/components/sidebar/Menu.stories.tsx
Labels: maintenance, cli, ci:daily

#23070 Bug: Fix angular ivy-preset
  code/frameworks/angular/src/server/framework-preset-angular-ivy.ts
Labels: bug, angular, patch

#23071 Release tooling: Trigger circle CI on pushes by github action bot
  .github/workflows/trigger-circle-ci-workflow.yml
Labels: build

#23042 CLI: Skip builder selection for react native
  code/lib/cli/src/detect.ts
Labels: bug, cli, patch

#23075 Release: Use release environment in release scripts
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
Labels: build

#23077 Bug: Make core-common use node-fetch
  code/lib/core-common/package.json
  code/lib/core-common/src/utils/get-storybook-refs.ts
  code/yarn.lock
Labels: bug, patch, core

#23083 Release: A bunch of fixes to the release tooling
  .github/workflows/check-release-tasks.yml
  .github/workflows/prepare-patch-release.yml
  .github/workflows/publish.yml
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/__tests__/label-patches.test.ts
  scripts/release/generate-pr-description.ts
Labels: patch, build

#23080 CLI: Prebundle boxen to resolve a ESM/CJS incompatibility
  code/lib/cli/package.json
  code/lib/core-server/package.json
Labels: bug, patch

#23092 Telemetry: Count onboarding stories
  code/lib/core-server/src/utils/summarizeIndex.test.ts
  code/lib/core-server/src/utils/summarizeIndex.ts
Labels: maintenance, patch, telemetry

#23099 Release: Changes to release PR titles and content
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
  scripts/release/generate-pr-description.ts
Labels: build

#23104 Docs: Add details for `defaultOrientation`
  docs/essentials/viewport.md
Labels: documentation, patch

#22946 NextJS: Fix `useParams` support
  code/frameworks/nextjs/README.md
  code/frameworks/nextjs/src/routing/app-router-provider.tsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Navigation.stories.jsx
Labels: bug, patch, nextjs, ci:daily

#23139 Server: Do not wrap data on channel in an array
  code/builders/builder-webpack5/src/index.ts
Labels: bug, core, server

#23145 CLI: Fix installing user's project before init
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
Labels: bug, cli

#23144 CLI: Fix storybook dev after storybook init via subprocess
  code/lib/cli/src/initiate.ts
Labels: bug, cli

#23158 Update button-story.ts.mdx
  docs/snippets/html/button-story.ts.mdx
Labels: documentation, patch

#23157 Docs: Add embedded video to Autodocs page
  docs/writing-docs/autodocs.md
Labels: documentation, patch

#22486 Core: Improve compatibility, do not mangle `names` in `interpret-requires` with `esbuild`
  code/lib/core-common/src/utils/interpret-require.ts
Labels: bug, patch

#23108 Addon-interactions: Support deeply nested nodes in the panel debugger
  code/addons/interactions/package.json
  code/addons/interactions/src/components/MethodCall.tsx
  code/addons/interactions/template/stories/basics.stories.ts
  code/e2e-tests/addon-interactions.spec.ts
  code/frameworks/angular/template/components/form.component.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/package.json
  code/renderers/html/template/components/Form.js
  code/renderers/preact/template/components/Form.jsx
  code/renderers/svelte/template/components/Form.svelte
  code/renderers/vue/template/components/Form.vue
  code/renderers/vue3/template/components/Form.vue
  code/yarn.lock
  scripts/package.json
  scripts/tasks/sandbox-parts.ts
  scripts/yarn.lock
Labels: bug, addon: interactions, ci:merged

#22714 Docs: Fix scroll location on docs navigation
  code/lib/preview-api/src/modules/preview-web/WebView.ts
Labels: bug, addon: docs

#23133 CLI: Suppress dev-server info table when `--quiet` is true
  code/lib/core-server/src/build-dev.ts
Labels: maintenance, cli

#23172 Build: Fix labels to release PRs
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-prerelease.yml
Labels: patch, build

#23169 CLI: Fix storybook package manager command in init
  code/lib/cli/src/initiate.ts
Labels: bug, cli

#23060 Docs: Remove "(deprecated)" & "(required)" from headings
  docs/api/arg-types.md
  docs/api/doc-block-canvas.md
  docs/api/doc-block-colorpalette.md
  docs/api/doc-block-description.md
  docs/api/doc-block-icongallery.md
  docs/api/doc-block-primary.md
  docs/api/doc-block-source.md
  docs/api/doc-block-story.md
  docs/api/doc-block-useof.md
  docs/api/main-config-config.md
  docs/api/main-config-framework.md
  docs/api/main-config-stories.md
  docs/api/main-config.md
  docs/snippets/angular/arg-types-default-value.ts.mdx
  docs/snippets/common/arg-types-default-value.js.mdx
  docs/snippets/common/arg-types-default-value.ts.mdx
  docs/snippets/web-components/arg-types-default-value.js.mdx
  docs/snippets/web-components/arg-types-default-value.ts.mdx
Labels: documentation, patch

#22972 React: Add addon-onboarding as part of init
  code/lib/cli/src/generators/NEXTJS/index.ts
  code/lib/cli/src/generators/REACT/index.ts
  code/lib/cli/src/generators/REACT_SCRIPTS/index.ts
  code/lib/cli/src/generators/WEBPACK_REACT/index.ts
  code/lib/cli/src/initiate.ts
  scripts/verdaccio.yaml
Labels: feature request, cli, react

#23184 Build: Fix regex that replaces globs for js/ts stories
  code/ui/.storybook/main.ts
  scripts/tasks/sandbox-parts.ts
Labels: build, ci:daily

#23195 PNPM: Hide ModuleNotFound error in pnpm pnp mode
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
Labels: bug

#23116 Build: Fix workflow link in release PR description
  scripts/release/generate-pr-description.ts
Labels: patch, build

#22905 Svelte: Support v4
  code/addons/storyshots-core/src/frameworks/svelte/renderTree.ts
  code/frameworks/svelte-vite/package.json
  code/frameworks/sveltekit/package.json
  code/renderers/svelte/package.json
  code/renderers/svelte/src/public-types.ts
  code/yarn.lock
Labels: maintenance, patch, ci:daily

#22161 Build: Add benchmark task
  .circleci/config.yml
  .gitignore
  code/builders/builder-manager/src/index.ts
  code/lib/cli/src/sandbox-templates.ts
  package.json
  scripts/bench/bench.schema
  scripts/bench/browse.ts
  scripts/bench/types.ts
  scripts/bench/utils.ts
  scripts/package.json
  scripts/task.ts
  scripts/tasks/bench.ts
  scripts/tasks/build.ts
  scripts/tasks/dev.ts
  scripts/tasks/sandbox-parts.ts
  scripts/tasks/sandbox.ts
  scripts/tasks/serve.ts
  scripts/typings.d.ts
  scripts/upload-bench.ts
  scripts/yarn.lock
Labels: build, ci:pr

#23198 Build: Don't auto-trigger CI on release PRs
  .github/workflows/trigger-circle-ci-workflow.yml
  scripts/release/__tests__/generate-pr-description.test.ts
  scripts/release/generate-pr-description.ts
Labels: patch, build

#23199 CLI: Parse pnp paths in storybook metadata
  code/lib/telemetry/src/get-framework-info.ts
  code/lib/telemetry/src/sanitize.test.ts
  code/lib/telemetry/src/storybook-metadata.test.ts
Labels: bug, cli, patch

#23203 Build: Fix parallelism count
  .circleci/config.yml
  code/builders/builder-vite/src/utils/process-preview-annotation.test.ts
  scripts/get-template.ts
Labels: build, ci:daily

#22876 added information that jest is not globally available
  docs/essentials/interactions.md
Labels: documentation, patch

#23221 Dependencies: Pin `file-system-cache` to 2.3.0
  code/lib/core-common/package.json
  code/lib/types/package.json
  code/yarn.lock
Labels: dependencies, patch, ci:daily

#23219 Release tooling: Label merges as "release"
  .github/workflows/prepare-patch-release.yml
Labels: patch, build

#23181 Docs: Document release tooling
  CONTRIBUTING/RELEASING.md
  CONTRIBUTING/prerelease-workflow-inputs.png
Labels: documentation

#23225 Release tooling: Cherry-pick #23024 to `main`
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/is-pr-frozen.ts
Labels: build

#23226 Build: Fix get-template --debug flag
  scripts/get-template.ts
Labels: build

#22993 Controls: Fix UI to add array items
  code/ui/blocks/src/controls/Object.tsx
Labels: bug, patch, addon: controls

#23167 Next.js: Support disableStaticImages setting
  code/frameworks/nextjs/src/images/webpack.ts
  code/frameworks/nextjs/src/next-image-loader-stub.ts
  code/frameworks/nextjs/src/preset.ts
Labels: bug, patch, ci:daily

#23259 CLI: Fix pnp paths logic in storybook metadata
  code/lib/telemetry/src/get-framework-info.test.ts
  code/lib/telemetry/src/get-framework-info.ts
Labels: bug, cli, patch

#23244 Release tooling: Fix "picked" labelling
  scripts/release/label-patches.ts
Labels: patch, build

#23258 docs(snippets/document-screen): fix typo
  docs/snippets/react/document-screen-with-graphql.ts.mdx
Labels: documentation, patch

#23239 Docs: Fix story hoisting snippets
  docs/snippets/common/button-story-hoisted.ts-4-9.mdx
  docs/snippets/common/button-story-hoisted.ts.mdx
  docs/snippets/web-components/button-story-hoisted.ts.mdx
Labels: documentation, patch
