Repository storybookjs/storybook, pull requests merged in 2023-01, with the labels that each got.

#20464 CLI: Use closest lockfile to determine package manager
  code/lib/cli/src/js-package-manager/JsPackageManagerFactory.test.ts
  code/lib/cli/src/js-package-manager/JsPackageManagerFactory.ts
  code/lib/cli/src/js-package-manager/fixtures/multiple-lockfiles/package.json
  code/lib/cli/src/js-package-manager/fixtures/multiple-lockfiles/pnpm-lock.yaml
  code/lib/cli/src/js-package-manager/fixtures/multiple-lockfiles/yarn.lock
  code/lib/cli/src/js-package-manager/fixtures/pnpm-workspace/package.json
  code/lib/cli/src/js-package-manager/fixtures/pnpm-workspace/package/package.json
  code/lib/cli/src/js-package-manager/fixtures/pnpm-workspace/pnpm-lock.yaml
  code/lib/cli/src/js-package-manager/fixtures/yarn.lock
Labels: bug, cli, pnpm

#20462 Core: Delete outdated onerror handler
  code/lib/core-common/templates/base-preview-head.html
Labels: maintenance, core

#20456 CLI: Do not use legacy-peer-deps for npm
  code/lib/cli/src/js-package-manager/NPMProxy.test.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
Labels: bug, cli

#20434 Vue3: Add TS / legacy TS CLI templates
  code/renderers/vue3/package.json
  code/renderers/vue3/template/cli/js/Button.stories.js
  code/renderers/vue3/template/cli/js/Button.vue
  code/renderers/vue3/template/cli/js/Header.stories.js
  code/renderers/vue3/template/cli/js/Header.vue
  code/renderers/vue3/template/cli/js/Page.stories.js
  code/renderers/vue3/template/cli/js/Page.vue
  code/renderers/vue3/template/cli/ts-legacy/Button.stories.ts
  code/renderers/vue3/template/cli/ts-legacy/Button.vue
  code/renderers/vue3/template/cli/ts-legacy/Header.stories.ts
  code/renderers/vue3/template/cli/ts-legacy/Header.vue
  code/renderers/vue3/template/cli/ts-legacy/Page.stories.ts
  code/renderers/vue3/template/cli/ts-legacy/Page.vue
  code/renderers/vue3/template/cli/ts/Button.stories.ts
  code/renderers/vue3/template/cli/ts/Button.vue
  code/renderers/vue3/template/cli/ts/Header.stories.ts
  code/renderers/vue3/template/cli/ts/Header.vue
  code/renderers/vue3/template/cli/ts/Page.stories.ts
  code/renderers/vue3/template/cli/ts/Page.vue
  code/yarn.lock
Labels: maintenance, cli, app: vue3

#20459 CLI: Add peer dependency on react
  code/lib/cli/package.json
  code/yarn.lock
Labels: dependencies, cli, pnpm

#20460 docs(addons/storysource): fix old link to "Theming" image
  code/addons/storysource/README.md
Labels: documentation

#20473 Chore: (Docs) Fix API CLI options documentation
  docs/api/cli-options.md
Labels: documentation

#20379 Migration: Update autodocs migration to deal with `docs.docsPage`
  code/lib/cli/src/automigrate/fixes/autodocs-true.ts
Labels: maintenance, addon: docs

#20469 Remove inDev flag for preact-vite framework
  code/lib/cli/src/repro-templates.ts
Labels: cleanup

#20409 Fix missing await in vite builder
  code/lib/builder-vite/src/vite-config.ts
Labels: bug, vite

#20477 Web-components: Restore missing script stories
  code/renderers/web-components/template/stories/script.stories.js
Labels: app: web-components, build

#20485 docs: fix broken links in MIGRATION.md
  MIGRATION.md
Labels: documentation, patch

#20489 Export Unstyled block in index.ts
  code/ui/blocks/src/blocks/index.ts
Labels: bug, mdx

#20492 Fix typo [ci-skip]
  code/lib/addons/README.md
Labels: cleanup

#20510 cleanup CI config
  .circleci/config.yml
Labels: build

#20150 Build: use tsup for csf-plugin
  code/lib/csf-plugin/package.json
  code/lib/csf-plugin/src/index.ts
  scripts/prepare/bundle.ts
Labels: maintenance

#20151 Build: cleanup prep script where possible
  code/lib/cli-sb/package.json
  code/lib/cli-storybook/package.json
  code/yarn.lock
Labels: build

#20483 Blocks: Use example Button for stories
  code/ui/.storybook/main.ts
  code/ui/blocks/src/blocks/Canvas.stories.tsx
  code/ui/blocks/src/blocks/Description.stories.tsx
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/blocks/internal/InternalCanvas.stories.tsx
  code/ui/blocks/src/blocks/internal/InternalDescription.stories.tsx
  code/ui/blocks/src/examples/Button.stories.tsx
  code/ui/blocks/src/examples/Button.tsx
Labels: build

#20380 Move 'dev'/'build' events to the end of the process
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/dev-server.ts
Labels: bug, telemetry

#20521 Build: fix InternalCanvas story tests
  code/ui/blocks/src/blocks/internal/InternalCanvas.stories.tsx
Labels: build

#20516 Build: create a tsc prepare script, use it for angular framework, add ESM to angular dist
  code/frameworks/angular/package.json
  code/yarn.lock
  scripts/prepare/tsc.ts
Labels: maintenance, ci:merged

#20524 Build: migrate the ember framework over to use tsc script
  code/frameworks/ember/package.json
  code/frameworks/ember/tsconfig.json
Labels: maintenance

#20532 Tech: downgrade find-cache-dir
  code/lib/builder-manager/package.json
  code/yarn.lock
Labels: maintenance

#20156 Tech: cleanup babel prepare related code & dependencies
  code/.eslintignore
  code/.gitignore
  code/.yarnrc.yml
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/src/api/integrityTestTemplate.ts
  code/addons/storyshots-core/tsconfig.build.json
  code/addons/storyshots-core/tsconfig.json
  code/addons/storyshots-puppeteer/package.json
  code/addons/storyshots-puppeteer/tsconfig.build.json
  code/cypress.json
  code/jest.init.base.ts
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/decorators.input.js
  code/lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/decorators.input.js
  code/lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/export-function.input.js
  code/lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/story-decorators.input.js
  code/lib/codemod/src/transforms/__testfixtures__/update-addon-info/update-addon-info.input.js
  code/lib/codemod/src/transforms/__testfixtures__/update-addon-info/update-addon-info.output.snapshot
  code/lib/core-server/package.json
  code/lib/csf-tools/package.json
  code/migrations.json
  code/package.json
  code/renderers/vue/template/cli/Header.vue
  code/renderers/vue/template/components/Html.vue
  code/renderers/vue3/template/cli/js/Button.vue
  code/renderers/vue3/template/cli/js/Header.vue
  code/renderers/vue3/template/cli/js/Page.vue
  code/renderers/vue3/template/components/Button.vue
  code/renderers/vue3/template/components/Html.vue
  code/yarn.lock
  scripts/.babelrc.js
  scripts/.yarn/releases/yarn-3.2.3.cjs
  scripts/package.json
  scripts/prepare.js
  scripts/utils/compile-babel.js
  scripts/utils/compile-tsc.js
  scripts/utils/watch-babel.js
  scripts/utils/watch-tsc.js
  scripts/yarn.lock
Labels: build

#20534 Build: remove usage of enzyme
  code/addons/storyshots-core/.eslintrc.js
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/stories/storyshot.enzyme.test.js
  code/addons/storyshots-puppeteer/package.json
  code/jest.init.base.ts
  code/package.json
  code/ui/manager/package.json
  code/ui/manager/src/settings/shortcuts.test.tsx
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: build

#20543 Build: downgrade slash to non-ESM
  code/lib/builder-webpack5/package.json
  code/yarn.lock
Labels: build

#20343 Tech: bundle @vitejs/plugin-vue in
  code/frameworks/vue3-vite/package.json
Labels: maintenance

#20546 Update GH action to use "linear-ghaction" label for sync
  .github/workflows/linear-export.yml
Labels: other

#20540 Add language to snippet filenames
  docs/snippets/vue/button-component-with-proptypes.2.js.mdx
  docs/snippets/vue/button-component-with-proptypes.3.js.mdx
  docs/snippets/vue/button-implementation.2.js.mdx
  docs/snippets/vue/button-implementation.3.js.mdx
  docs/snippets/vue/simple-page-implementation.2.js.mdx
  docs/snippets/vue/simple-page-implementation.3.js.mdx
  docs/writing-docs/doc-block-argstable.md
  docs/writing-stories/build-pages-with-storybook.md
Labels: documentation

#20488 Feature: added ability to compose with basic auth storybooks
  code/lib/manager-api/src/modules/refs.ts
  code/lib/manager-api/src/tests/refs.test.js
Labels: feature request, composition

#20531 Docs: Fix attachment logic
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/test-utils.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.ts
  code/ui/.storybook/preview.tsx
  code/ui/blocks/src/blocks/external/ExternalDocsContext.ts
Labels: bug, addon: docs

#20539 Telemetry: Add pageStoryCount
  code/lib/core-server/src/utils/summarizeIndex.test.ts
  code/lib/core-server/src/utils/summarizeIndex.ts
Labels: maintenance, telemetry

#20541 Telemetry: Count play function usage
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/summarizeIndex.ts
  code/lib/csf-tools/src/CsfFile.test.ts
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/store/template/stories/component-play.stories.ts
Labels: maintenance, telemetry

#20517 Rename `storyByModuleExport` to `resolveModuleExport`
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/test-utils.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/CsfDocsRender.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.ts
  code/lib/preview-api/src/modules/store/csf/processCSFFile.test.ts
  code/lib/preview-api/src/modules/store/csf/processCSFFile.ts
  code/lib/types/src/modules/docs.ts
  code/lib/types/src/modules/story.ts
  code/ui/.storybook/preview.tsx
  code/ui/blocks/src/blocks/Canvas.tsx
  code/ui/blocks/src/blocks/Meta.tsx
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/external/ExternalDocsContext.ts
  test-storybooks/external-docs/package.json
Labels: maintenance, addon: docs

#20553 Telemetry: Filter out example stories/docs from summary
  code/frameworks/ember/template/cli/Button.stories.js
  code/lib/core-server/src/utils/summarizeIndex.ts
  code/renderers/react/template/cli/ts-legacy/Button.stories.ts
  code/renderers/react/template/cli/ts-legacy/Header.stories.ts
  scripts/event-log-checker.ts
Labels: maintenance, telemetry

#20550 Fix: pathing of managerEntries containing long paths with hidden folders
  code/lib/builder-manager/src/utils/managerEntries.ts
Labels: bug

#20560 Tech: move reactPeerCheck to addon docs
  code/addons/docs/src/ensure-react-peer-deps.ts
  code/addons/docs/src/preset.ts
  code/lib/cli/package.json
  code/lib/cli/src/build.ts
  code/lib/cli/src/dev.ts
  code/yarn.lock
Labels: maintenance, cli, addon: docs

#20561 Build: upgrade verdaccio
  .circleci/config.yml
  .github/workflows/generate-repros-next.yml
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/run-registry.ts
  scripts/tsconfig.json
  scripts/typings.d.ts
  scripts/yarn.lock
Labels: build

#20542 Migrations: Add `preact-vite` to new frameworks automigration.
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: maintenance, app: preact

#20533 Build: remove unneeded dependencies & upgrades
  .circleci/config.yml
  .github/workflows/generate-repros-next.yml
  code/addons/storyshots-core/.eslintrc.js
  code/addons/storyshots-core/package.json
  code/addons/storyshots-core/stories/storyshot.enzyme.test.js
  code/addons/storyshots-puppeteer/package.json
  code/frameworks/ember/package.json
  code/jest.init.base.ts
  code/lib/docs-tools/package.json
  code/package.json
  code/renderers/react/package.json
  code/renderers/web-components/package.json
  code/renderers/web-components/src/docs/web-components-properties.test.ts
  code/ui/manager/package.json
  code/ui/manager/src/settings/shortcuts.test.tsx
  code/yarn.lock
  scripts/package.json
  scripts/run-registry.ts
  scripts/tsconfig.json
  scripts/typings.d.ts
  scripts/yarn.lock
Labels: build, ci:merged

#20563 Blocks: new Description API, introduce useOf
  MIGRATION.md
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/types/src/modules/docs.ts
  code/ui/blocks/src/blocks/Description.stories.tsx
  code/ui/blocks/src/blocks/Description.tsx
  code/ui/blocks/src/blocks/index.ts
  code/ui/blocks/src/blocks/useOf.ts
  code/ui/blocks/src/examples/Button.stories.tsx
  code/ui/blocks/src/examples/Button.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsBoth.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsComment.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsParameter.stories.tsx
Labels: maintenance, addon: docs, block: description, ci:pr

#20574 fix: remove standalone and export build from core-server
  code/lib/core-server/src/index.ts
  code/lib/core-server/standalone.js
Labels: bug

#20526 Security: Upgrade json5 dependency
  lib/cli/package.json
  lib/core-common/package.json
  yarn.lock
Labels: dependencies

#20536 vue3: rendering slots if are set and passed from controls
  code/renderers/vue3/src/render.ts
Labels: feature request, app: vue3

#20585 Vue Fontawesome, spelling change
  docs/get-started/setup.md
Labels: documentation, patch

#20054 Build: Allow creating internal templates that extend others and pass `main.js` options
  code/lib/cli/src/repro-next.ts
  code/lib/cli/src/repro-templates.ts
  scripts/task.ts
  scripts/tasks/sandbox-parts.ts
  scripts/tasks/sandbox.ts
Labels: build, ci:merged

#20349 add auto-migration for MDX html-type comments to JS-type comments
  code/lib/cli/src/automigrate/fixes/mdx-1-to-2.test.ts
  code/lib/cli/src/automigrate/fixes/mdx-1-to-2.ts
Labels: feature request, cli

#20575 feat: expose port from buildDevStandalone
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/withTelemetry.ts
Labels: feature request

#20590 Blocks: handle undefined extractComponentDescription
  code/ui/blocks/src/blocks/Description.tsx
Labels: bug, ui, ci:merged

#20455 Addons: Warn when addon is not installed
  code/lib/core-common/src/presets.test.ts
  code/lib/core-common/src/presets.ts
Labels: bug, core

#20591 Build: fix template stories to make them work with stricter Typescript settings
  code/addons/interactions/src/preview.ts
  code/lib/client-logger/src/index.ts
  code/lib/store/template/stories/argTypes.stories.ts
  code/lib/store/template/stories/args.stories.ts
  code/lib/store/template/stories/autotitle.stories.ts
  code/lib/store/template/stories/decorators.stories.ts
  code/lib/store/template/stories/global.d.ts
  code/lib/store/template/stories/globals.stories.ts
  code/lib/store/template/stories/hooks.stories.ts
  code/lib/store/template/stories/loaders.stories.ts
  code/lib/store/template/stories/names.stories.ts
  code/lib/store/template/stories/parameters.stories.ts
  code/lib/store/template/stories/preview.ts
  code/lib/store/template/stories/rendering.stories.ts
  code/lib/store/template/stories/shortcuts.stories.ts
  code/lib/store/template/stories/tags.stories.ts
  code/lib/store/template/stories/title.stories.ts
Labels: build

#20239 SvelteKit: Automatically support Kit-specific features
  code/frameworks/sveltekit/README.md
  code/frameworks/sveltekit/src/preset.ts
Labels: maintenance, app: svelte

#20601 Bug: Fix issue with jest projects matching `ui/node_modules`
  code/jest.config.js
Labels: maintenance

#20594 Ensure no duplicate code in preview when using vite
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/typings.d.ts
  code/lib/builder-vite/src/vite-config.ts
  code/lib/preview/src/globals/runtime.ts
  code/yarn.lock
Labels: bug

#20606 fix: cli repros creation not working on windows
  code/lib/cli/src/repro-generators/configs.ts
  code/lib/cli/src/repro-generators/scripts.ts
Labels: build

#20610 fix typing on useArgs
  code/lib/preview-api/src/modules/addons/hooks.ts
Labels: feature request, core, typescript

#19188 fix: simplify element before stringifying to avoid crash on docs page
  code/renderers/react/src/docs/jsxDecorator.tsx
Labels: bug, addon: docs, linear-ghaction

#20589 Maintenance: mention removal of --no-dll flag
  MIGRATION.md
  code/lib/types/src/modules/core-common.ts
  docs/api/cli-options.md
Labels: maintenance, documentation

#20609 fix(generator): use devDependencies to determine angular/core version for init
  code/lib/cli/src/generators/ANGULAR/index.ts
Labels: bug, app: angular

#20341 CLI: add "missing-babelrc" automigration
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.test.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
Labels: feature request, cli

#19463 Add e2e test for static JSON files
  code/e2e-tests/json-files.spec.ts
Labels: maintenance, build-storybook

#19755 Chore: Enable Scorecard Github Action and Badge
  .github/workflows/scorecards.yml
  README.md
Labels: linear-ghaction, build

#20451 add children to CanvasProps
  code/ui/blocks/src/blocks/Canvas.tsx
Labels: bug, typescript

#20592 prepareMeta function similar to prepareStory
  code/lib/preview-api/src/index.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/lib/types/src/modules/story.ts
  code/ui/blocks/src/blocks/Description.tsx
  code/ui/blocks/src/blocks/useOf.ts
Labels: maintenance, block: description

#18799 Svelte: don't add `svelte-loader` nor `svelte` when initializing Svelte projects
  code/lib/cli/src/generators/SVELTE/index.ts
Labels: maintenance, cli

#19956 vue: fix type.name check in extractArgTypes
  code/renderers/vue/src/docs/extractArgTypes.ts
Labels: bug, app: vue, argtypes

#19788 Blocks: Do not copy code snippet when text inside preview is selected
  code/ui/blocks/src/components/Preview.tsx
Labels: bug, ui, block: source

#20295 Angular: Fix isStandaloneComponent check
  code/frameworks/angular/src/client/angular-beta/utils/NgComponentAnalyzer.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/NgComponentAnalyzer.ts
Labels: bug, app: angular, ci:daily

#20571 Add @storybook/next to the list of available frameworks in Migration.md
  MIGRATION.md
Labels: documentation

#20327 Docs: migration documentation for MDX2 in storybook CLI
  code/lib/cli/src/automigrate/fixes/mdx-1-to-2.ts
  docs/writing-docs/mdx.md
Labels: documentation, cli

#19492 remove the defaultValue feature for argTypes
  code/lib/preview-api/src/modules/store/csf/prepareStory.test.ts
  code/lib/preview-api/src/modules/store/csf/prepareStory.ts
  code/renderers/react/src/__test__/__snapshots__/internals.test.tsx.snap
  code/renderers/react/src/__test__/internals.test.tsx
  code/renderers/vue3/template/stories/OverrideArgs.stories.js
Labels: maintenance, linear-ghaction

#20622 Addon-controls: Fix version of preview api
  code/addons/controls/package.json
  code/yarn.lock
Labels: dependencies

#20615 Fix the @storybook/nextjs image loader
  code/frameworks/nextjs/src/next-image-loader-stub.ts
Labels: bug, nextjs

#20273 Codemods: Fix `csf-2-to-3` ignores Typescript types
  code/jest.config.base.js
  code/lib/codemod/README.md
  code/lib/codemod/jest.config.js
  code/lib/codemod/package.json
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/basic.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/basic.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/component-id.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/component-id.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/decorators.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/decorators.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/exclude-stories.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/exclude-stories.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/parameters.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/parameters.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/story-function.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/story-function.output.snapshot
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/story-parameters.input.js
  code/lib/codemod/src/transforms/__testfixtures__/csf-to-mdx/story-parameters.output.snapshot
  code/lib/codemod/src/transforms/__tests__/csf-2-to-3.test.ts
  code/lib/codemod/src/transforms/csf-2-to-3.ts
  code/lib/codemod/src/transforms/csf-to-mdx.js
  code/lib/csf-tools/package.json
  code/lib/csf-tools/src/babelParse.ts
  code/yarn.lock
Labels: bug, cli, typescript, codemods

#20470 Fix: (Vue3 cli ts templates) add missing css import on button.vue
  code/renderers/vue3/template/cli/ts-legacy/Button.vue
  code/renderers/vue3/template/cli/ts/Button.vue
Labels: bug, app: vue3

#20577 Upgrade babel-loader to ^9.0.0
  code/addons/storyshots-core/package.json
  code/frameworks/vue3-webpack5/package.json
  code/lib/builder-webpack5/package.json
  code/presets/vue-webpack/package.json
  code/presets/vue3-webpack/package.json
  code/presets/web-components-webpack/package.json
  code/renderers/vue/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#20507 CLI: overhaul `storybook repro` command and rename it to `storybook sandbox`
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/generate-repros-next.yml
  .github/workflows/generate-repros.yml
  code/lib/cli/src/generate.ts
  code/lib/cli/src/link.ts
  code/lib/cli/src/repro.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/cli/src/sandbox.ts
  code/package.json
  docs/contribute/code.md
  docs/contribute/how-to-reproduce.md
  docs/contribute/storybook-reproduction-generator-location-optimized.png
  docs/contribute/storybook-reproduction-generator-location.png
  docs/contribute/storybook-reproduction-generator-template-optimized.png
  docs/contribute/storybook-reproduction-generator-template.png
  docs/contribute/storybook-reproductions-framework-selector-optimized.png
  generate-repros.sh
  generate-sandboxes.sh
  scripts/event-log-checker.ts
  scripts/get-template.ts
  scripts/repros-generator/fs-helper.mjs
  scripts/repros-generator/git-helper.mjs
  scripts/repros-generator/index.mjs
  scripts/repros-generator/templates/main/.stackblitzrc
  scripts/repros-generator/templates/main/README.md
  scripts/repros-generator/templates/next/.stackblitzrc
  scripts/repros-generator/templates/next/README.md
  scripts/sandbox-generators/generate-sandboxes.ts
  scripts/sandbox-generators/publish.ts
  scripts/sandbox-generators/templates/.stackblitzrc
  scripts/sandbox-generators/templates/item.ejs
  scripts/sandbox-generators/templates/root.ejs
  scripts/sandbox-generators/utils/git.ts
  scripts/sandbox-generators/utils/template.ts
  scripts/sandbox-generators/utils/types.ts
  scripts/sandbox-generators/utils/yarn.ts
  scripts/task.ts
  scripts/tasks/generate.ts
  scripts/utils/cli-step.ts
Labels: feature request, cli, ci:merged

#20619 fix: Change deprecated `React.VFC` to `React.FC`
  code/frameworks/nextjs/template/cli/ts-legacy/Page.tsx
  code/renderers/react/template/cli/ts-legacy/Page.tsx
  code/renderers/react/template/cli/ts/Page.tsx
  docs/snippets/common/custom-docs-page.ts-component.ts.mdx
Labels: maintenance, nextjs

#20612 bring back support for `favicon.ico`
  code/lib/builder-manager/src/index.ts
  code/lib/builder-manager/src/utils/data.ts
  code/lib/builder-manager/src/utils/template.ts
  code/lib/builder-manager/templates/template.ejs
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/presets/favicon.test.ts
  code/lib/core-server/src/utils/server-statics.ts
Labels: bug

#20630 Fix Storyshots transpilation
  code/addons/storyshots-core/tsconfig.json
  code/addons/storyshots-puppeteer/tsconfig.json
Labels: build

#20617 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#20618 CLI: Add codemod to upgrade deprecated types
  code/lib/codemod/package.json
  code/lib/codemod/src/transforms/__tests__/csf-2-to-3.test.ts
  code/lib/codemod/src/transforms/__tests__/upgrade-deprecated-types.test.ts
  code/lib/codemod/src/transforms/csf-2-to-3.ts
  code/lib/codemod/src/transforms/upgrade-deprecated-types.ts
Labels: feature request, cli, typescript

#20628 Docs: Update Vite builder README
  code/lib/builder-vite/README.md
Labels: documentation, vite

#20650 Svelte: Remove babel/core peer dep
  code/renderers/svelte/package.json
  code/yarn.lock
Labels: dependencies, app: svelte

#20642 Vite: TypeScript type cleanup
  MIGRATION.md
  code/frameworks/html-vite/src/index.ts
  code/frameworks/html-vite/src/preset.ts
  code/frameworks/html-vite/src/types.ts
  code/frameworks/preact-vite/src/index.ts
  code/frameworks/preact-vite/src/preset.ts
  code/frameworks/preact-vite/src/types.ts
  code/frameworks/react-vite/src/index.ts
  code/frameworks/react-vite/src/preset.ts
  code/frameworks/react-vite/src/types.ts
  code/frameworks/svelte-vite/src/index.ts
  code/frameworks/svelte-vite/src/preset.ts
  code/frameworks/svelte-vite/src/types.ts
  code/frameworks/sveltekit/src/index.ts
  code/frameworks/sveltekit/src/preset.ts
  code/frameworks/sveltekit/src/types.ts
  code/frameworks/vue-vite/src/index.ts
  code/frameworks/vue-vite/src/preset.ts
  code/frameworks/vue-vite/src/types.ts
  code/frameworks/vue3-vite/src/index.ts
  code/frameworks/vue3-vite/src/preset.ts
  code/frameworks/vue3-vite/src/types.ts
  code/frameworks/web-components-vite/src/index.ts
  code/frameworks/web-components-vite/src/preset.ts
  code/frameworks/web-components-vite/src/types.ts
  code/lib/builder-vite/input/iframe.html
  code/lib/builder-vite/src/build.ts
  code/lib/builder-vite/src/codegen-entries.ts
  code/lib/builder-vite/src/codegen-iframe-script.ts
  code/lib/builder-vite/src/codegen-modern-iframe-script.ts
  code/lib/builder-vite/src/envs.ts
  code/lib/builder-vite/src/index.ts
  code/lib/builder-vite/src/optimizeDeps.ts
  code/lib/builder-vite/src/plugins/code-generator-plugin.ts
  code/lib/builder-vite/src/plugins/csf-plugin.ts
  code/lib/builder-vite/src/transform-iframe-html.ts
  code/lib/builder-vite/src/types.ts
  code/lib/builder-vite/src/types/extended-options.type.ts
  code/lib/builder-vite/src/types/index.ts
  code/lib/builder-vite/src/vite-config.ts
  code/lib/builder-vite/src/vite-server.ts
  docs/snippets/common/storybook-vite-builder-ts-configure.ts.mdx
Labels: maintenance, vite

#20654 Fix HMR issue in Manager UI
  code/frameworks/react-vite/package.json
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/vite-config.ts
  code/ui/.storybook/main.ts
  code/yarn.lock
Labels: bug, vite

#20530 Docs: Refactor props of Story block
  MIGRATION.md
  code/__mocks__/inject-parameters.ts.csf.txt
  code/addons/docs/angular/README.md
  code/addons/docs/common/README.md
  code/addons/docs/ember/README.md
  code/addons/docs/react/README.md
  code/addons/docs/template/stories/docspage/autoplay.stories.ts
  code/addons/docs/template/stories/docspage/iframe.stories.ts
  code/addons/docs/vue/README.md
  code/addons/docs/vue3/README.md
  code/addons/docs/web-components/README.md
  code/frameworks/angular/src/client/docs/config.ts
  code/frameworks/ember/src/client/docs/config.js
  code/frameworks/ember/src/client/preview/docs/config.js
  code/renderers/html/src/docs/config.ts
  code/renderers/preact/src/docs/config.ts
  code/renderers/react/src/docs/config.ts
  code/renderers/svelte/src/docs/config.ts
  code/renderers/vue/src/docs/config.ts
  code/renderers/vue3/src/docs/config.ts
  code/renderers/web-components/src/docs/config.ts
  code/ui/.storybook/preview.tsx
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/external/ExternalPreview.ts
  code/ui/blocks/src/blocks/internal/InternalCanvas.stories.tsx
  code/ui/blocks/src/components/DocsPage.stories.tsx
  code/ui/blocks/src/components/Preview.stories.tsx
  code/ui/blocks/src/components/Preview.tsx
  code/ui/blocks/src/components/Story.stories.tsx
  code/ui/blocks/src/components/Story.tsx
  code/ui/blocks/src/components/index.ts
  code/ui/blocks/src/examples/Button.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsBoth.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsComment.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsParameter.stories.tsx
  docs/snippets/angular/storybook-preview-with-angular-polyfills.js.mdx
  docs/snippets/common/storybook-preview-optout-inline.js.mdx
  test-storybooks/ember-cli/stories/welcome-banner.stories.js
  test-storybooks/server-kitchen-sink/.storybook/preview.js
Labels: maintenance, addon: docs, BREAKING PRERELEASE

#20263 Add required jobs to daily workflow
  .circleci/config.yml
Labels: build, ci:daily

#20632 Csf-plugin: Support meta description comments
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/csf-tools/src/enrichCsf.test.ts
  code/lib/csf-tools/src/enrichCsf.ts
Labels: feature request, addon: docs

#20649 Addon-actions: Fix webpack hot reload code in manager bundle
  code/addons/actions/src/containers/ActionLogger/index.tsx
Labels: bug, addon: actions

#19860 Vue: Update events binding in Vue render
  code/lib/store/template/stories/hooks.stories.ts
  code/renderers/vue/src/render.ts
Labels: bug, app: vue, addon: interactions

#20425 Core: Show "booting" progress until story is specified or errors
  code/lib/manager-api/src/index.tsx
  code/lib/manager-api/src/lib/stories.ts
  code/lib/manager-api/src/modules/refs.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/refs.test.js
  code/lib/manager-api/src/tests/stories.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/preview-api/src/modules/preview-web/View.ts
  code/lib/preview-api/src/modules/preview-web/WebView.ts
  code/lib/types/src/modules/api-stories.ts
  code/lib/types/src/modules/api.ts
  code/ui/.storybook/main.ts
  code/ui/components/src/Colors/colorpalette.mdx
  code/ui/manager/src/app.stories.tsx
  code/ui/manager/src/components/layout/app.mockdata.tsx
  code/ui/manager/src/components/preview/FramesRenderer.tsx
  code/ui/manager/src/components/preview/preview.tsx
  code/ui/manager/src/components/sidebar/Explorer.stories.tsx
  code/ui/manager/src/components/sidebar/RefIndicator.tsx
  code/ui/manager/src/components/sidebar/Refs.stories.tsx
  code/ui/manager/src/components/sidebar/Refs.tsx
  code/ui/manager/src/components/sidebar/Search.stories.tsx
  code/ui/manager/src/components/sidebar/Search.tsx
  code/ui/manager/src/components/sidebar/SearchResults.stories.tsx
  code/ui/manager/src/components/sidebar/Sidebar.stories.tsx
  code/ui/manager/src/components/sidebar/Sidebar.tsx
  code/ui/manager/src/components/sidebar/Tree.stories.tsx
  code/ui/manager/src/components/sidebar/__tests__/Sidebar.test.tsx
  code/ui/manager/src/components/sidebar/mockdata.large.ts
  code/ui/manager/src/components/sidebar/utils.ts
  code/ui/manager/src/containers/sidebar.tsx
  code/ui/manager/src/index.tsx
Labels: bug, core

#20167 Addons: Fix Viewport resetting shortcut key not working
  code/lib/manager-api/src/lib/shortcut.ts
  code/lib/manager-api/src/tests/shortcut.test.js
Labels: bug, ui

#20154 Support @deprecated jsdoc tag
  code/lib/docs-tools/src/argTypes/jsdocParser.test.ts
  code/lib/docs-tools/src/argTypes/jsdocParser.ts
  code/ui/blocks/src/components/ArgsTable/ArgJsDoc.tsx
  code/ui/blocks/src/components/ArgsTable/types.ts
Labels: feature request

#20669 Bug: add error catching when template is not set
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: bug, reported

#20661 Addon-docs: Fix issue with unattached `.mdx` files
  code/addons/docs/template/stories/stories-mdx/unattached.stories.mdx
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/test-utils.ts
Labels: bug, addon: docs

#20621 UI: Add Sun, Moon, Sidebyside, and stacked icons
  code/addons/toolbars/template/stories/preview.ts
  code/ui/components/src/icon/icons.tsx
Labels: feature request, ui

#20646 Core: Fix `core` preset default value
  code/lib/core-server/src/build-dev.ts
  code/lib/core-server/src/build-static.ts
  code/lib/core-server/src/utils/get-builders.ts
Labels: bug, core, reported

#20602 Organize 7.0 migration guide
  MIGRATION.md
  code/lib/preview-api/src/modules/preview-web/Preview.tsx
  docs/configure/overview.md
Labels: documentation

#20665 Csf-plugin: Move source to docs.source.originalSource
  code/lib/csf-tools/src/enrichCsf.test.ts
  code/lib/csf-tools/src/enrichCsf.ts
Labels: maintenance, addon: docs

#20604 Docs: Show primary story description and headline in autodocs
  code/e2e-tests/addon-docs.spec.ts
  code/e2e-tests/preview-web.spec.ts
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/RendererFactory.ts
  code/lib/preview-api/src/modules/preview-web/Preview.tsx
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.test.ts
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts
  code/lib/types/src/modules/docs.ts
  code/ui/blocks/src/blocks/DocsStory.tsx
  code/ui/blocks/src/blocks/Primary.tsx
  code/ui/blocks/src/blocks/Stories.tsx
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/types.ts
  code/ui/blocks/src/components/Preview.stories.tsx
  code/ui/blocks/src/components/Story.stories.tsx
  code/ui/blocks/src/components/Story.tsx
Labels: feature request, addon: docs

#20662 Docs: Move validation logic into `context.resolveOf`
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.test.ts
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/lib/types/src/modules/docs.ts
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/useOf.ts
  code/ui/blocks/src/components/Preview.stories.tsx
  code/ui/blocks/src/components/Story.stories.tsx
Labels: maintenance, addon: docs

#20679 Addon-docs: Update story index generator
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
Labels: feature request, addon: docs

#20692 use correct method in ui example story
  code/ui/blocks/src/components/Story.stories.tsx
Labels: build

#20689 CLI: Make missing-babelrc an automatic migration
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/babel-config.ts
Labels: feature request, cli

#20664 Docs: Created `ArgTypes` component and stories
  code/ui/blocks/src/blocks/ArgTypes.stories.tsx
  code/ui/blocks/src/blocks/ArgTypes.tsx
  code/ui/blocks/src/blocks/index.ts
  code/ui/blocks/src/components/Story.stories.tsx
  code/ui/blocks/src/examples/ArgTypesParameters.stories.tsx
  code/ui/blocks/src/examples/ArgTypesParameters.tsx
Labels: feature request, addon: docs, block: argstable

#20683 Docs: Implement Controls block
  code/ui/blocks/src/blocks/ArgTypes.tsx
  code/ui/blocks/src/blocks/Controls.stories.tsx
  code/ui/blocks/src/blocks/Controls.tsx
  code/ui/blocks/src/blocks/DocsPage.tsx
  code/ui/blocks/src/examples/ControlsParameters.stories.tsx
  code/ui/blocks/src/examples/ControlsParameters.tsx
Labels: feature request, addon: docs, block: argstable

#20700 docs: add documentation for story indexers
  docs/configure/sidebar-and-urls.md
  docs/snippets/common/csf-2-example-title.js.mdx
  docs/snippets/common/csf-3-example-title.ts.mdx
  docs/snippets/common/storybook-main-csf-indexer.js.mdx
  docs/snippets/common/storybook-main-md-html-indexer.js.mdx
Labels: documentation, story index

#20603 Docs: Added source stories and updated API
  code/__mocks__/inject-decorator.ts.csf-meta-var.txt
  code/lib/csf-tools/src/enrichCsf.test.ts
  code/lib/csf-tools/src/enrichCsf.ts
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf-meta-var.test.js.posix.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/inject-decorator.csf.test.js
  code/lib/source-loader/src/abstract-syntax-tree/traverse-helpers.js
  code/ui/blocks/src/blocks/Source.stories.tsx
  code/ui/blocks/src/blocks/Source.tsx
  code/ui/blocks/src/blocks/SourceContainer.tsx
  code/ui/blocks/src/blocks/enhanceSource.test.ts
  code/ui/blocks/src/blocks/enhanceSource.ts
  code/ui/blocks/src/blocks/internal/InternalSource.stories.tsx
  code/ui/blocks/src/components/Source.stories.tsx
  code/ui/blocks/src/components/Source.tsx
  code/ui/blocks/src/examples/EmptyExample.tsx
  code/ui/blocks/src/examples/SourceParameters.stories.tsx
Labels: feature request, addon: docs

#20706 Build: remove preact-webpack5 from babelrc automigration
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
Labels: maintenance

#20691 Csf-tools: Add helpers to get name from node path
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: maintenance, csf

#20693 CLI: Upgrade automigrations to use new safe helpers
  code/lib/cli/src/automigrate/fixes/mainjsFramework.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.test.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
  code/lib/cli/src/automigrate/fixes/sveltekit-framework.ts
Labels: maintenance, cli

#20708 CLI: Fix package execution for npm package manager
  code/frameworks/angular/src/builders/utils/run-compodoc.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/js-package-manager/NPMProxy.test.ts
  code/lib/cli/src/js-package-manager/NPMProxy.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.test.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
  code/lib/cli/src/js-package-manager/Yarn1Proxy.test.ts
  code/lib/cli/src/js-package-manager/Yarn1Proxy.ts
  code/lib/cli/src/js-package-manager/Yarn2Proxy.test.ts
  code/lib/cli/src/js-package-manager/Yarn2Proxy.ts
Labels: bug, cli, app: angular

#20707 fix snapshot
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf-meta-var.test.js.posix.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.injectStoryParameters-posix.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.injectStoryParameters-windows.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.posix.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/__snapshots__/inject-decorator.csf.test.js.windows.snapshot
  code/lib/source-loader/src/abstract-syntax-tree/generate-helpers.js
  code/lib/source-loader/src/abstract-syntax-tree/inject-decorator.csf.test.js
  code/lib/source-loader/src/build.js
Labels: build

#20411 CLI: Add init support for qwik projects
  README.md
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/dirs.ts
  code/lib/cli/src/generators/QWIK/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/project_types.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
  docs/configure/frameworks.md
  docs/frameworks.js
  scripts/tasks/sandbox-parts.ts
Labels: feature request, cli, ci:daily

#20671 Fix the d.ts file of addon-links, mark LinkTo in index as deprecated
  code/addons/links/package.json
  code/addons/links/react.d.ts
  code/addons/links/react.js
  code/addons/links/scripts/fix-preview-api-reference.ts
  code/addons/links/src/index.ts
  code/yarn.lock
Labels: bug, addon: links

#20681 Vite: Allow specifying path to vite.config file
  code/lib/builder-vite/README.md
  code/lib/builder-vite/src/types.ts
  code/lib/builder-vite/src/vite-config.ts
  code/lib/core-common/src/index.ts
  code/lib/core-common/src/utils/get-builder-options.ts
Labels: feature request, vite

#20735 Docs: Fix one final usage of `@storybook/addon-docs/blocks`
  docs/snippets/angular/loader-story.mdx.mdx
Labels: documentation, addon: docs

#20702 Docs: Allow "declaring" stories with `story={}`
  code/addons/docs/template/stories/stories-mdx/csf-in-mdx.stories.mdx
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/internal/InternalStory.stories.tsx
  code/ui/blocks/src/examples/SourceParameters.stories.tsx
Labels: bug, addon: docs

#20736 Upgrade react-popper-tooltip
  code/ui/components/package.json
  code/ui/components/src/tooltip/Tooltip.tsx
  code/ui/components/src/tooltip/WithTooltip.tsx
  code/ui/manager/src/components/sidebar/Menu.stories.tsx
  code/ui/manager/src/components/sidebar/Menu.tsx
  code/yarn.lock
Labels: ui, maintenance

#20712 Vue3 ( fix ) implement reactive args + fix many vue app creation issue
  code/lib/store/template/stories/rendering.stories.ts
  code/renderers/vue3/src/render.ts
  code/renderers/vue3/template/stories/ReactiveArgs.stories.js
  code/renderers/vue3/template/stories/ReactiveArgs.vue
Labels: bug, app: vue3

#20757 Blocks: ignore known blocks with global CSS selector
  code/ui/blocks/src/components/DocsPage.tsx
Labels: bug, ui

#20762 Build: do not treat check as a cache-able operation && cleanup
  code/nx.json
Labels: build

#20723 Blocks: New Canvas API
  code/lib/preview-api/src/modules/preview-web/docs-context/DocsContext.ts
  code/ui/blocks/src/blocks/Canvas.stories.tsx
  code/ui/blocks/src/blocks/Canvas.tsx
  code/ui/blocks/src/blocks/DocsStory.tsx
  code/ui/blocks/src/blocks/Primary.tsx
  code/ui/blocks/src/blocks/Source.tsx
  code/ui/blocks/src/blocks/Stories.tsx
  code/ui/blocks/src/blocks/internal/InternalCanvas.stories.tsx
  code/ui/blocks/src/blocks/types.ts
  code/ui/blocks/src/blocks/useOf.ts
  code/ui/blocks/src/components/Preview.stories.tsx
  code/ui/blocks/src/components/Preview.tsx
  code/ui/blocks/src/examples/CanvasParameters.stories.tsx
Labels: ui, maintenance, block: other

#20724 Fixed paths in generated main.cjs for the default sandbox on Windows
  scripts/tasks/sandbox-parts.ts
  scripts/utils/main-js.ts
Labels: bug, windows

#20705 Core: Fix issue with inconsistent CSF ordering in sandboxes
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  scripts/tasks/sandbox-parts.ts
Labels: bug, core

#20759 Docs: Make reference stories consistent
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/internal/InternalCanvas.stories.tsx
  code/ui/blocks/src/blocks/internal/InternalDescription.stories.tsx
  code/ui/blocks/src/blocks/internal/InternalSource.stories.tsx
  code/ui/blocks/src/blocks/internal/InternalStory.stories.tsx
  code/ui/blocks/src/examples/ArgTypesParameters.stories.tsx
  code/ui/blocks/src/examples/Button.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsBoth.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsComment.stories.tsx
  code/ui/blocks/src/examples/ButtonWithMetaDescriptionAsParameter.stories.tsx
  code/ui/blocks/src/examples/CanvasParameters.stories.tsx
  code/ui/blocks/src/examples/ControlsParameters.stories.tsx
  code/ui/blocks/src/examples/SimpleSizeTest.tsx
  code/ui/blocks/src/examples/SourceParameters.stories.tsx
  code/ui/blocks/src/examples/StoryParameters.stories.tsx
Labels: maintenance, addon: docs

#20709 Angular: Fix issue if BrowserAnimationsModule is imported
  code/frameworks/angular/package.json
  code/frameworks/angular/src/builders/utils/run-compodoc.spec.ts
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/template/stories/core/moduleMetadata/angular-src/open-close-component/open-close.component.css
  code/frameworks/angular/template/stories/core/moduleMetadata/angular-src/open-close-component/open-close.component.html
  code/frameworks/angular/template/stories/core/moduleMetadata/angular-src/open-close-component/open-close.component.ts
  code/frameworks/angular/template/stories/core/moduleMetadata/with-browser-animations.stories.ts
  code/yarn.lock
  scripts/prettier.config.js
Labels: bug, app: angular

#20699 Docs: First version of doc blocks migration guide
  MIGRATION.md
  code/lib/preview-api/src/modules/store/csf/processCSFFile.ts
  code/ui/blocks/src/blocks/Story.tsx
  code/ui/blocks/src/blocks/internal/InternalStory.stories.tsx
Labels: documentation, addon: docs

#20765 Docs: Allow `<Story/>` to reference the first story
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/blocks/Story.tsx
Labels: feature request, addon: docs

#20768 Fix vue sandbox: remove the lang=ts in a file, that should remain agnostic
  code/renderers/vue3/template/stories/ReactiveArgs.vue
Labels: app: vue, app: vue3, build, ci:daily

#20767 Migration docs for Canvas
  MIGRATION.md
Labels: documentation

#20722 WebComponents: fix type error Button component
  code/renderers/web-components/template/cli/ts/Button.ts
Labels: bug, typescript, app: web-components

#20777 upgrade playwright
  .circleci/config.yml
  code/package.json
  code/yarn.lock
Labels: build

#20727 Minor markdown fix
  docs/essentials/controls.md
Labels: documentation, patch

#20778 Build: fix playwright unsynced version in CI
  scripts/utils/yarn.ts
Labels: build

#20772 Deps: Upgrade fs-extra to 11.1.0
  code/addons/docs/package.json
  code/addons/links/package.json
  code/frameworks/nextjs/package.json
  code/lib/builder-manager/package.json
  code/lib/builder-vite/package.json
  code/lib/builder-webpack5/package.json
  code/lib/cli/package.json
  code/lib/cli/src/repro-generators/scripts.ts
  code/lib/core-common/package.json
  code/lib/core-server/package.json
  code/lib/csf-tools/package.json
  code/lib/telemetry/package.json
  code/lib/theming/package.json
  code/package.json
  code/presets/react-webpack/package.json
  code/presets/server-webpack/package.json
  code/ui/manager/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#20711 Ensure Angular docsMode flag has effect
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/build-storybook/schema.json
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/schema.json
  code/lib/cli/src/build.ts
  code/lib/cli/src/dev.ts
  docs/get-started/installation-problems/angular.mdx
Labels: bug, app: angular, addon: docs

#20781 Verify consistency of anonymous id
  code/lib/telemetry/src/anonymous-id.test.ts
  code/lib/telemetry/src/anonymous-id.ts
  scripts/event-log-checker.ts
Labels: telemetry, build

#20785 CSF-tools: Fix ConfigFile string literal property handling
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: bug, csf

#20776 CLI: Fix global flag corner case
  code/lib/cli/src/generate.ts
  code/lib/cli/src/generators/types.ts
  code/lib/telemetry/src/sanitize.ts
Labels: bug, cli

#20746 Use Angular Providers in boostrapApplication option
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts
  code/frameworks/angular/src/client/angular-beta/utils/NgModulesAnalyzer.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/NgModulesAnalyzer.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
  code/nx.json
Labels: bug, app: angular

#20788 CLI: Fix new-frameworks automigration in angular projects
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: bug, cli, app: angular

#20792 fix test-coverage.md
  docs/writing-tests/test-coverage.md
Labels: documentation

#20787 Vite: Do not pre-bundle @vitejs/plugin-vue
  code/frameworks/vue3-vite/package.json
Labels: bug, builder-vite

#20799 Storysource: Support CSF3 object exports, co-exist with addon-docs
  code/__mocks__/inject-decorator.ts.csf3.txt
  code/addons/storysource/src/preset.ts
  code/lib/source-loader/src/abstract-syntax-tree/inject-decorator.csf.test.js
  code/lib/source-loader/src/abstract-syntax-tree/traverse-helpers.js
  code/lib/source-loader/src/build.js
Labels: bug, addon: storysource, source-loader, csf3

#20804 Sveltekit: Ensure SSR is disabled
  code/frameworks/sveltekit/src/plugins/config-overrides.ts
  code/frameworks/sveltekit/src/preset.ts
Labels: bug, ci:daily, sveltekit

#20698 Vite: Replace vite-plugin-externals with custom plugin
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/plugins/external-globals-plugin.test.ts
  code/lib/builder-vite/src/plugins/external-globals-plugin.ts
  code/lib/builder-vite/src/plugins/index.ts
  code/lib/builder-vite/src/vite-config.ts
  code/yarn.lock
Labels: bug, builder-vite

#20807 Docs: Allow using `<Source code=".." />` unattached.
  code/ui/blocks/src/blocks/Source.stories.tsx
  code/ui/blocks/src/blocks/Source.tsx
Labels: bug, addon: docs, block: source

#20815 docs: add notes about current state of SvelteKit features
  code/frameworks/sveltekit/README.md
Labels: documentation, sveltekit
