Repository storybookjs/storybook, pull requests merged in 2023-02, with the labels that each got.

#20820 feat: return address of dev server from buildDevStandalone
  code/lib/core-server/src/build-dev.ts
Labels: feature request, core

#20870 SvelteKit: Disable failing `vite-plugin-sveltekit-guard`
  code/frameworks/sveltekit/src/preset.ts
Labels: bug, sveltekit

#20842 Webpack: Support builder options from framework
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
Labels: bug, builder-webpack5

#20879 Update link to homepage for addons
  code/addons/a11y/package.json
  code/addons/actions/package.json
  code/addons/backgrounds/package.json
  code/addons/controls/package.json
  code/addons/docs/README.md
  code/addons/docs/package.json
  code/addons/essentials/package.json
  code/addons/highlight/package.json
  code/addons/interactions/package.json
  code/addons/jest/package.json
  code/addons/links/README.md
  code/addons/links/package.json
  code/addons/measure/package.json
  code/addons/outline/package.json
  code/addons/storyshots-core/package.json
  code/addons/storyshots-puppeteer/package.json
  code/addons/storysource/README.md
  code/addons/storysource/package.json
  code/addons/toolbars/README.md
  code/addons/toolbars/package.json
  code/addons/viewport/package.json
Labels: documentation

#20806 Docs: Export controls from doc blocks
  code/ui/blocks/src/blocks/index.ts
  code/ui/blocks/src/controls/types.ts
Labels: bug, addon: docs

#20854 Vue3: Fix args losing reactivity when using decorators
  code/renderers/vue3/src/decorateStory.ts
  code/renderers/vue3/src/render.ts
Labels: bug, app: vue3

#20880 Blocks: Added deprecation warnings
  MIGRATION.md
  code/ui/blocks/src/blocks/ArgsTable.tsx
  code/ui/blocks/src/blocks/Canvas.tsx
  code/ui/blocks/src/blocks/Source.tsx
Labels: documentation

#20818 fix: outline initial state
  code/addons/outline/src/OutlineSelector.tsx
  code/addons/outline/src/withOutline.ts
Labels: bug, addon: outline

#20894 Build: minor fixes
  code/lib/builder-webpack5/src/index.ts
  code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/lib/core-common/package.json
  code/yarn.lock
  scripts/package.json
  scripts/utils/yarn.ts
  scripts/yarn.lock
Labels: build

#20846 Add nunito sans font
  code/frameworks/nextjs/template/cli/js/Introduction.mdx
  code/frameworks/nextjs/template/cli/ts-legacy/Introduction.stories.mdx
  code/lib/builder-manager/templates/template.ejs
  code/lib/builder-vite/input/iframe.html
  code/lib/builder-webpack5/templates/preview.ejs
  code/lib/cli/rendererAssets/common/Introduction.mdx
  code/lib/cli/rendererAssets/common/header.css
  code/lib/cli/rendererAssets/common/page.css
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/theming/src/base.ts
  code/ui/blocks/src/components/ArgsTable/SectionRow.tsx
  code/ui/blocks/src/components/DocsPage.tsx
  code/ui/blocks/src/components/Title.tsx
  code/ui/blocks/src/components/Typeset.stories.tsx
  code/ui/components/src/tooltip/TooltipMessage.tsx
  code/ui/components/src/typography/DocumentWrapper.tsx
  code/ui/components/src/typography/elements/H1.tsx
  code/ui/components/src/typography/typography.stories.mdx
  code/ui/manager/package.json
  code/ui/manager/src/components/sidebar/Refs.tsx
  code/ui/manager/src/components/sidebar/TreeNode.tsx
  code/ui/manager/src/settings/about.tsx
  code/ui/manager/src/settings/shortcuts.tsx
  code/ui/manager/static/fonts.css
  code/ui/manager/static/nunito-sans-bold-italic.woff2
  code/ui/manager/static/nunito-sans-bold.woff2
  code/ui/manager/static/nunito-sans-italic.woff2
  code/ui/manager/static/nunito-sans-regular.woff2
  docs/snippets/common/typeset-doc.block.mdx.mdx
Labels: feature request, ui, builder-manager

#20116 Vite/Addon-docs: Fix customization of MDX plugins
  code/addons/docs/README.md
  code/addons/docs/src/preset.ts
  code/lib/builder-vite/src/plugins/mdx-plugin.ts
  docs/essentials/introduction.md
Labels: feature request, addon: docs

#20895 CLI: Remove the deprecated `--no-manager-cache` flag
  code/lib/cli/src/generate.ts
  code/package.json
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/standalone-preview/package.json
Labels: maintenance

#20902 Build: Improve task log and error messages for event log
  scripts/event-log-checker.ts
  scripts/task.ts
Labels: build

#20905 docs: fix `MINIMAL_VIEWPORTS` links
  docs/essentials/viewport.md
Labels: documentation, patch

#20911 Build: Change `rootDir` in TS plugin
  code/ui/.storybook/main.ts
Labels: build

#20906 Core: Fix index error handling
  code/lib/core-server/src/dev-server.ts
Labels: bug, core, telemetry

#20868 Support NoopAnimationsModule
  code/frameworks/angular/jest.config.js
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/__testfixtures__/test.module.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
  code/frameworks/angular/template/stories/core/moduleMetadata/with-noop-browser-animations.stories.ts
Labels: bug

#20844 Update PR template to properly link PRs to issues
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#20783 Tab UI Improvements
  code/addons/a11y/src/components/VisionSimulator.tsx
  code/addons/backgrounds/src/containers/BackgroundSelector.tsx
  code/addons/toolbars/src/components/ToolbarMenuList.tsx
  code/addons/viewport/src/Tool.tsx
  code/e2e-tests/addon-backgrounds.spec.ts
  code/e2e-tests/addon-viewport.spec.ts
  code/ui/blocks/src/components/ArgsTable/ArgValue.tsx
  code/ui/blocks/src/controls/Color.tsx
  code/ui/components/package.json
  code/ui/components/src/bar/bar.tsx
  code/ui/components/src/bar/button.tsx
  code/ui/components/src/tabs/tabs.helpers.tsx
  code/ui/components/src/tabs/tabs.hooks.tsx
  code/ui/components/src/tabs/tabs.stories.tsx
  code/ui/components/src/tabs/tabs.tsx
  code/ui/components/src/tooltip/ListItem.tsx
  code/ui/components/src/tooltip/Tooltip.tsx
  code/ui/components/src/tooltip/TooltipLinkList.tsx
  code/ui/components/src/tooltip/WithTooltip.stories.tsx
  code/ui/components/src/tooltip/WithTooltip.tsx
  code/ui/components/tsconfig.json
  code/ui/manager/src/components/hooks/useMedia.tsx
  code/ui/manager/src/components/notifications/NotificationItem.tsx
  code/ui/manager/src/components/panel/panel.stories.tsx
  code/ui/manager/src/components/panel/panel.tsx
  code/ui/manager/src/components/sidebar/Menu.tsx
  code/ui/manager/src/components/sidebar/RefBlocks.tsx
  code/yarn.lock
Labels: feature request, ui, ci:pr

#20887 CLI: add type annotations in javascript main config files
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
Labels: feature request, cli

#20924 Build: fix next
  code/ui/components/src/tabs/tabs.stories.tsx
Labels: build

#20927 Upgrade glob to 8.1.0
  code/lib/builder-vite/package.json
  code/lib/core-common/package.json
  code/package.json
  code/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies

#20923 CLI: Improve MDX2 automigration docs
  code/lib/cli/src/automigrate/fixes/mdx-1-to-2.ts
Labels: documentation

#20925 Upgrade jscodeshift to 0.14.0
  code/lib/cli/package.json
  code/lib/codemod/package.json
  code/lib/postinstall/package.json
  code/yarn.lock
Labels: dependencies

#20929 Core: Fix globs on windows
  code/lib/core-common/src/utils/validate-configuration-files.ts
  code/lib/core-server/src/utils/watch-story-specifiers.ts
Labels: bug, core, windows

#20809 Revert addon-docs: update story index generator
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
Labels: maintenance, addon: docs

#20930 Csf-tools: Fix error handling for storySort variable references
  code/lib/csf-tools/src/getStorySortParameter.test.ts
  code/lib/csf-tools/src/getStorySortParameter.ts
Labels: bug, csf

#20909 docs: update support for SvelteKit's `$app/paths`
  code/frameworks/sveltekit/README.md
Labels: documentation, sveltekit

#20945 docs: update SvelteKit readme
  code/frameworks/sveltekit/README.md
Labels: documentation, sveltekit

#20936 Csf-tools: Add `satisfies` support to ConfigFile
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: feature request, typescript, csf

#20952 Core: Undo AST main.js check in validateConfigFile
  code/lib/core-common/package.json
  code/lib/core-common/src/utils/validate-configuration-files.ts
  code/yarn.lock
Labels: bug, core

#20954 Tech: update glob for storyshots
  code/addons/storyshots-core/package.json
  code/yarn.lock
Labels: maintenance

#20957 Fix: fonts missing/warnings
  code/lib/core-server/src/presets/common-preset.ts
Labels: bug, ci:daily

#20962 Feature: Add woff2 support for builder-manager
  code/lib/builder-manager/src/index.ts
Labels: feature request

#20918 Correctly preserve existing vite envPrefix config
  code/lib/builder-vite/src/vite-config.test.ts
  code/lib/builder-vite/src/vite-config.ts
Labels: maintenance, builder-vite

#20892 Build: add more sandboxes to CI tests
  .circleci/config.yml
  code/e2e-tests/addon-docs.spec.ts
  code/e2e-tests/framework-nextjs.spec.ts
  code/e2e-tests/json-files.spec.ts
  code/lib/cli/src/sandbox-templates.ts
  scripts/event-log-checker.ts
  scripts/tasks/e2e-tests.ts
  scripts/tasks/test-runner.ts
Labels: build, ci:merged

#20944 fix: correctly detect JS projects with type checking
  code/lib/cli/src/detect.ts
Labels: bug

#20983 fix(angular): standalone components to be included in the imports array
  code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
Labels: bug, app: angular

#20942 fix: remove `svelte-options` from `svelte-vite`
  code/frameworks/svelte-vite/src/preset.ts
Labels: maintenance, app: svelte

#20982 Tech: add a default background to newly initialized storybooks
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
Labels: ui, maintenance, cli

#20984 fix(angular): changeDetectorRef should be defined
  code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts
Labels: bug, app: angular

#20986 Build: upgrade yarn
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.3.0.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  code/.yarnrc.yml
  code/yarn.lock
  scripts/.yarnrc.yml
  scripts/yarn.lock
Labels: build

#20989 Core: Fix missing dependency for core-server
  code/lib/core-server/package.json
  code/lib/core-server/src/typings.d.ts
  code/yarn.lock
Labels: maintenance, core

#20898 Menu design upgrade
  code/addons/a11y/src/components/VisionSimulator.tsx
  code/addons/backgrounds/src/containers/BackgroundSelector.tsx
  code/addons/toolbars/src/components/ToolbarMenuList.tsx
  code/addons/toolbars/src/components/ToolbarMenuListItem.tsx
  code/addons/viewport/src/Tool.tsx
  code/ui/blocks/src/components/ArgsTable/ArgValue.tsx
  code/ui/blocks/src/controls/Color.tsx
  code/ui/components/src/index.ts
  code/ui/components/src/tabs/tabs.hooks.tsx
  code/ui/components/src/tabs/tabs.stories.tsx
  code/ui/components/src/tooltip/ListItem.tsx
  code/ui/components/src/tooltip/Tooltip.tsx
  code/ui/components/src/tooltip/TooltipLinkList.stories.tsx
  code/ui/components/src/tooltip/TooltipLinkList.tsx
  code/ui/components/src/tooltip/TooltipMessage.stories.tsx
  code/ui/components/src/tooltip/TooltipNote.stories.tsx
  code/ui/components/src/tooltip/WithTooltip.stories.tsx
  code/ui/components/src/tooltip/WithTooltip.tsx
  code/ui/components/src/tooltip/assets/ellipse.png
  code/ui/components/src/typings.d.ts
  code/ui/manager/src/components/sidebar/Menu.stories.tsx
  code/ui/manager/src/components/sidebar/Menu.tsx
  code/ui/manager/src/components/sidebar/RefBlocks.tsx
  code/ui/manager/src/components/sidebar/RefIndicator.tsx
  code/ui/manager/src/containers/Menu.stories.tsx
  code/ui/manager/src/containers/menu.tsx
  code/ui/manager/src/globals/exports.ts
Labels: feature request, ui

#21000 docs: link to issue for SvelteKit mocks
  code/frameworks/sveltekit/README.md
Labels: documentation, sveltekit

#20990 Telemetry: Hash error messages
  code/lib/core-server/src/withTelemetry.ts
  code/lib/telemetry/src/index.ts
Labels: maintenance, telemetry

#21013 Vite: Use posix paths for glob
  code/lib/builder-vite/src/list-stories.ts
Labels: bug, builder-vite, windows

#21022 Build: Allow `stories` folder to be served by vite sandboxes
  scripts/tasks/sandbox-parts.ts
Labels: build

#21028 fix(angular): provideHttpClient when HttpClientModule is present in the imports array
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
Labels: bug, angular

#20917 Core: Detect mdx2 errors and provide guidance to fix them
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
Labels: bug, core

#20991 CLI: Add Solid integration
  code/lib/cli/src/dirs.ts
  code/lib/cli/src/generators/SOLID/index.ts
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/project_types.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
Labels: feature request, cli, ci:daily, solid

#21048 Add `defaultOrientation` parameter to viewport addon.
  code/addons/viewport/src/Tool.tsx
  code/addons/viewport/src/models/ViewportAddonParameter.ts
Labels: bug, addon: viewport

#21035 CLI: Automigration to update `mdx` stories config
  code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.test.ts
  code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.ts
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/helpers/cleanLog.ts
Labels: feature request, cli

#21037 Fix migration docs typo
  MIGRATION.md
Labels: documentation

#20970 CLI: Re-enable vue-vite in new-frameworks automigration
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: maintenance, vue, builder-vite, ci:daily

#21064 fix: conflicts static dirs.
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/utils/constants.ts
  code/lib/core-server/src/utils/server-statics.ts
Labels: bug, cli

#20458 CLI: Do not use modern TS assets in legacy TS projects
  code/frameworks/nextjs/template/cli/ts-3-8/Button.stories.ts
  code/frameworks/nextjs/template/cli/ts-3-8/Button.tsx
  code/frameworks/nextjs/template/cli/ts-3-8/Header.stories.ts
  code/frameworks/nextjs/template/cli/ts-3-8/Header.tsx
  code/frameworks/nextjs/template/cli/ts-3-8/Introduction.mdx
  code/frameworks/nextjs/template/cli/ts-3-8/Page.stories.ts
  code/frameworks/nextjs/template/cli/ts-3-8/Page.tsx
  code/frameworks/sveltekit/README.md
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
  code/lib/cli/src/helpers.test.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/project_types.ts
  code/renderers/react/template/cli/ts-3-8/Button.stories.ts
  code/renderers/react/template/cli/ts-3-8/Button.tsx
  code/renderers/react/template/cli/ts-3-8/Header.stories.ts
  code/renderers/react/template/cli/ts-3-8/Header.tsx
  code/renderers/react/template/cli/ts-3-8/Page.stories.ts
  code/renderers/react/template/cli/ts-3-8/Page.tsx
  code/renderers/react/template/cli/ts-4-9/Button.stories.ts
  code/renderers/react/template/cli/ts-4-9/Button.tsx
  code/renderers/react/template/cli/ts-4-9/Header.stories.ts
  code/renderers/react/template/cli/ts-4-9/Header.tsx
  code/renderers/react/template/cli/ts-4-9/Page.stories.ts
  code/renderers/react/template/cli/ts-4-9/Page.tsx
  code/renderers/svelte/template/cli/ts-3.8/Button.stories.ts
  code/renderers/svelte/template/cli/ts-3.8/Button.svelte
  code/renderers/svelte/template/cli/ts-3.8/Header.stories.ts
  code/renderers/svelte/template/cli/ts-3.8/Header.svelte
  code/renderers/svelte/template/cli/ts-3.8/Page.stories.ts
  code/renderers/svelte/template/cli/ts-3.8/Page.svelte
  code/renderers/svelte/template/cli/ts-4-9/Button.stories.ts
  code/renderers/svelte/template/cli/ts-4-9/Button.svelte
  code/renderers/svelte/template/cli/ts-4-9/Header.stories.ts
  code/renderers/svelte/template/cli/ts-4-9/Header.svelte
  code/renderers/svelte/template/cli/ts-4-9/Page.stories.ts
  code/renderers/svelte/template/cli/ts-4-9/Page.svelte
  code/renderers/vue3/template/cli/ts-3-8/Button.stories.ts
  code/renderers/vue3/template/cli/ts-3-8/Button.vue
  code/renderers/vue3/template/cli/ts-3-8/Header.stories.ts
  code/renderers/vue3/template/cli/ts-3-8/Header.vue
  code/renderers/vue3/template/cli/ts-3-8/Page.stories.ts
  code/renderers/vue3/template/cli/ts-3-8/Page.vue
  code/renderers/vue3/template/cli/ts-4-9/Button.stories.ts
  code/renderers/vue3/template/cli/ts-4-9/Button.vue
  code/renderers/vue3/template/cli/ts-4-9/Header.stories.ts
  code/renderers/vue3/template/cli/ts-4-9/Header.vue
  code/renderers/vue3/template/cli/ts-4-9/Page.stories.ts
  code/renderers/vue3/template/cli/ts-4-9/Page.vue
Labels: bug, cli

#20995 Vue3: Fix CSF2 support with decorators
  code/lib/store/template/stories/args.stories.ts
  code/lib/store/template/stories/rendering.stories.ts
  code/renderers/vue3/src/decorateStory.ts
  code/renderers/vue3/src/render.ts
Labels: bug, vue3

#20915 Docs: Show source of corresponding args in source block
  code/addons/docs/docs/multiframework.md
  code/e2e-tests/addon-docs.spec.ts
  code/frameworks/angular/src/client/docs/sourceDecorator.ts
  code/renderers/html/src/docs/sourceDecorator.test.ts
  code/renderers/html/src/docs/sourceDecorator.ts
  code/renderers/react/src/docs/jsxDecorator.test.tsx
  code/renderers/react/src/docs/jsxDecorator.tsx
  code/renderers/svelte/src/docs/sourceDecorator.ts
  code/renderers/vue/src/docs/sourceDecorator.ts
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/renderers/web-components/src/docs/sourceDecorator.test.ts
  code/renderers/web-components/src/docs/sourceDecorator.ts
  code/ui/blocks/package.json
  code/ui/blocks/src/blocks/Controls.tsx
  code/ui/blocks/src/blocks/DocsStory.tsx
  code/ui/blocks/src/blocks/Source.stories.tsx
  code/ui/blocks/src/blocks/Source.tsx
  code/ui/blocks/src/blocks/SourceContainer.tsx
  code/ui/blocks/src/blocks/useArgs.ts
  code/ui/blocks/src/blocks/useGlobals.ts
  code/yarn.lock
Labels: bug, addon: docs, ci:daily

#21081 Fix some unsound type check errors
  code/lib/builder-vite/src/plugins/mdx-plugin.types.d.ts
  code/ui/blocks/src/blocks/useArgs.ts
Labels: maintenance

#20994 fix: remove unused dependencies from core-common
  code/lib/core-common/package.json
  code/yarn.lock
Labels: maintenance

#20810 docs: improve storyIndexers & makeTitle documentation
  docs/configure/sidebar-and-urls.md
  docs/snippets/common/csf-3-example-title.mdx.mdx
  docs/snippets/common/csf-3-example-title.ts.mdx
  docs/snippets/common/storybook-main-csf-indexer.ts.mdx
  docs/snippets/common/storybook-main-md-html-indexer.js.mdx
  docs/snippets/common/storybook-main-story-indexer-main.ts.mdx
Labels: documentation

#21091 Add video callout to /docs/writing-stories/introduction
  docs/writing-stories/introduction.md
Labels: documentation

#21095 Upgrade react-docgen-typescript-plugin
  code/presets/react-webpack/package.json
  code/presets/react-webpack/src/framework-preset-react-docs.test.ts
  code/presets/react-webpack/src/framework-preset-react-docs.ts
  code/presets/react-webpack/src/types.ts
  code/yarn.lock
Labels: dependencies, react, typescript, argtypes

#21029 Fix Source View in Nextjs projects
  code/addons/controls/template/stories/basics.stories.ts
  code/addons/controls/template/stories/conditional.stories.ts
  code/addons/controls/template/stories/disable.stories.ts
  code/addons/controls/template/stories/filters.stories.ts
  code/addons/controls/template/stories/issues.stories.ts
  code/addons/controls/template/stories/matchers.stories.ts
  code/addons/controls/template/stories/sorting.stories.ts
  code/e2e-tests/addon-docs.spec.ts
  code/frameworks/nextjs/src/preview.tsx
Labels: bug

#21099 Build: Fix yarn build command
  scripts/build-package.js
Labels: build

#21096 Vite: Fix storysource addon support
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/plugins/index.ts
  code/lib/builder-vite/src/plugins/source-loader-plugin.ts
  code/lib/builder-vite/src/vite-config.ts
  code/yarn.lock
  scripts/tasks/sandbox-parts.ts
Labels: bug, addon: storysource, source-loader, builder-vite

#21088 Interactions: Add debugger to the addon panel
  code/addons/docs/src/typings.d.ts
  code/addons/interactions/README.md
  code/addons/interactions/src/Panel.tsx
  code/addons/interactions/src/components/InteractionsPanel.stories.tsx
  code/addons/interactions/src/components/InteractionsPanel.tsx
  code/addons/interactions/src/components/Subnav.stories.tsx
  code/frameworks/angular/src/typings.d.ts
  code/lib/core-server/src/__for-testing__/main.ts
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/core-server/src/typings.d.ts
  code/lib/core-server/src/utils/getStoryIndexGenerator.ts
  code/lib/instrumenter/README.md
  code/lib/instrumenter/src/instrumenter.ts
  code/lib/instrumenter/src/types.ts
  code/lib/instrumenter/src/typings.d.ts
  code/lib/manager-api/src/typings.d.ts
  code/lib/preview-api/src/typings.d.ts
  code/lib/telemetry/src/storybook-metadata.test.ts
  code/lib/types/src/modules/core-common.ts
  code/ui/.storybook/main.ts
  code/ui/manager/src/settings/typings.d.ts
  code/ui/manager/src/typings.d.ts
  docs/snippets/common/storybook-main-enable-interactive-debugger.js.mdx
  scripts/tasks/sandbox-parts.ts
Labels: feature request, addon: interactions, ci:daily

#21046 CLI: Fix pnp support & add auto-detection
  .circleci/config.yml
  .yarnrc.yml
  code/.yarnrc.yml
  code/lib/cli/package.json
  code/lib/cli/src/detect.test.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/dirs.ts
  code/lib/cli/src/generators/REACT_NATIVE/index.ts
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
  code/lib/cli/src/helpers.test.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/initiate.ts
  code/lib/cli/src/repro-generators/scripts.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/csf-tools/package.json
  code/lib/csf-tools/src/ConfigFile.ts
  code/yarn.lock
  node_modules/.yarn-state.yml
  scripts/.yarnrc.yml
  scripts/sandbox-generators/generate-sandboxes.ts
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: bug, cli, yarn / npm, ci:daily, yarn

#21102 Fix boolean arg types parsing and encoding
  code/lib/preview-api/src/modules/preview-web/parseArgsParam.test.ts
  code/lib/preview-api/src/modules/preview-web/parseArgsParam.ts
  code/lib/router/src/utils.test.ts
  code/lib/router/src/utils.ts
Labels: bug

#20908 Tech: improve treeshaking - add dist stats file (for comparison)
  code/addons/essentials/package.json
  code/addons/interactions/package.json
  code/frameworks/html-vite/package.json
  code/frameworks/html-webpack5/package.json
  code/frameworks/nextjs/package.json
  code/frameworks/preact-vite/package.json
  code/frameworks/preact-webpack5/package.json
  code/frameworks/react-webpack5/package.json
  code/frameworks/server-webpack5/package.json
  code/frameworks/svelte-vite/package.json
  code/frameworks/svelte-webpack5/package.json
  code/frameworks/sveltekit/README.md
  code/frameworks/sveltekit/package.json
  code/frameworks/vue-vite/package.json
  code/frameworks/vue3-vite/package.json
  code/frameworks/vue3-webpack5/package.json
  code/frameworks/web-components-vite/package.json
  code/frameworks/web-components-webpack5/package.json
  code/lib/builder-manager/package.json
  code/lib/builder-vite/package.json
  code/lib/builder-webpack5/package.json
  code/lib/cli/package.json
  code/lib/codemod/package.json
  code/lib/core-server/package.json
  code/lib/core-webpack/package.json
  code/lib/csf-plugin/package.json
  code/lib/source-loader/package.json
  code/lib/store/package.json
  code/lib/telemetry/package.json
  code/presets/html-webpack/package.json
  code/presets/preact-webpack/package.json
  code/presets/react-webpack/package.json
  code/presets/server-webpack/package.json
  code/presets/svelte-webpack/package.json
  code/presets/vue-webpack/package.json
  code/presets/vue3-webpack/package.json
  code/presets/web-components-webpack/package.json
  code/renderers/vue3/package.json
  code/renderers/vue3/src/docs/sourceDecorator.ts
  code/stats.json
  code/ui/manager/scripts/generate-exports-file.ts
  code/ui/manager/src/globals/exports.ts
  code/yarn.lock
  scripts/prepare/bundle.ts
Labels: maintenance

#21002 fix: use Vite by default for Svelte and Vue
  code/lib/cli/src/detect-nextjs.test.ts
  code/lib/cli/src/detect-nextjs.ts
  code/lib/cli/src/detect.ts
  code/lib/cli/src/initiate.ts
Labels: bug, svelte, vue3

#21126 Build: regen lockfiles
  code/yarn.lock
  scripts/yarn.lock
Labels: build

#20993 fix: remove unnecessary dependencies in types package
  code/lib/types/package.json
  code/yarn.lock
Labels: maintenance

#21107 Build: add cra preset to monorepo
  code/lib/cli/src/link.ts
  code/package.json
  code/presets/create-react-app/CHANGELOG.md
  code/presets/create-react-app/README.md
  code/presets/create-react-app/package.json
  code/presets/create-react-app/project.json
  code/presets/create-react-app/src/helpers/checkPresets.ts
  code/presets/create-react-app/src/helpers/getModulePath.ts
  code/presets/create-react-app/src/helpers/getReactScriptsPath.ts
  code/presets/create-react-app/src/helpers/mergePlugins.ts
  code/presets/create-react-app/src/helpers/processCraConfig.ts
  code/presets/create-react-app/src/index.ts
  code/presets/create-react-app/src/types.ts
  code/presets/create-react-app/src/typings.d.ts
  code/presets/create-react-app/tsconfig.json
  code/yarn.lock
  scripts/verdaccio.yaml
Labels: bug, presets, cra

#21119 Fix static dirs look up in Next.js projects
  code/lib/core-server/src/dev-server.ts
  code/lib/core-server/src/utils/server-statics.ts
Labels: bug

#21117 Fix some dependency warnings
  code/frameworks/nextjs/package.json
  code/lib/manager-api-shim/package.json
  code/yarn.lock
Labels: maintenance

#21128 Do not render issue template reproduction section with shell
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: other

#21069 Fix to css Zoom not working in safari
  code/ui/components/src/Zoom/browserSupportsCssZoom.ts
Labels: bug, components

#20660 Update border color to match Design System proposal
  code/lib/theming/src/base.ts
Labels: maintenance, theming

#21105 fix: Interaction's tooltips don't disappear correctly
  code/addons/interactions/src/components/Subnav.tsx
Labels: bug, ui

#21132 fix: Rename "Story" tab to "Code"
  code/addons/storysource/src/manager.tsx
Labels: feature request

#21138 UI: Fix Canvas zoom height
  code/ui/components/src/Zoom/ZoomElement.tsx
  code/ui/components/src/Zoom/browserSupportsCssZoom.ts
Labels: bug, ui

#20981 Maintenance: Fix `@ts-expect-error` strict types
  code/frameworks/angular/template/stories/argTypes/doc-button/doc-button.component.ts
  code/lib/csf-tools/src/ConfigFile.ts
  code/lib/csf-tools/src/CsfFile.ts
  code/lib/csf-tools/src/enrichCsf.ts
  code/lib/csf-tools/src/getStorySortParameter.ts
Labels: maintenance, typescript, ci:daily

#21143 README: Fix twitter badge
  README.md
Labels: documentation, patch

#21146 Revert #21096 Vite: Fix storysource addon support
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/plugins/index.ts
  code/lib/builder-vite/src/plugins/source-loader-plugin.ts
  code/lib/builder-vite/src/vite-config.ts
  code/yarn.lock
Labels: bug, performance issue, addon: storysource, source-loader, builder-vite

#21147 Revert upgrade to react-docgen-typescript-plugin
  code/presets/react-webpack/package.json
  code/presets/react-webpack/src/framework-preset-react-docs.test.ts
  code/presets/react-webpack/src/framework-preset-react-docs.ts
  code/presets/react-webpack/src/types.ts
  code/yarn.lock
Labels: bug, react, typescript, argtypes

#21123 Vite: Update dep range for @storybook/mdx1-csf
  code/lib/builder-vite/package.json
  code/yarn.lock
Labels: dependencies, builder-vite

#20754 Fix: vue2 events use bracket notation
  code/renderers/vue/src/render.ts
Labels: bug, vue

#21149 Fix (docs): react using args snippets
  docs/snippets/react/button-story-using-args.ts-4-9.mdx
  docs/snippets/react/button-story-using-args.ts.mdx
Labels: documentation

#21135 Chore: (Docs) Adds Args Youtube tutorial to the documentation
  docs/writing-stories/args.md
Labels: documentation, patch

#21098 Docs: Remove `DocsOptions.disable`
  code/addons/docs/src/preset.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/stories-json.test.ts
  code/lib/preview-api/src/modules/client-api/StoryStoreFacade.ts
  code/lib/preview-api/src/modules/core-client/start.test.ts
  code/lib/types/src/modules/core-common.ts
  docs/writing-docs/docs-page.md
Labels: maintenance, addon: docs

#21021 fix: skip to canvas link style
  code/ui/manager/src/components/sidebar/Heading.tsx
Labels: bug, ui

#20647 CLI: Improve monorepo support in `automigrate` and revamp framework-related migrations
  MIGRATION.md
  code/.swcrc
  code/frameworks/nextjs/README.md
  code/frameworks/svelte-vite/src/utils.ts
  code/jest.config.base.js
  code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.ts
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/fixes/mainjsFramework.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/new-frameworks.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/utils.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/utils.ts
  code/lib/cli/src/automigrate/fixes/nextjs-framework.test.ts
  code/lib/cli/src/automigrate/fixes/nextjs-framework.ts
  code/lib/cli/src/automigrate/fixes/nodejs-requirement.ts
  code/lib/cli/src/automigrate/fixes/sb-binary.test.ts
  code/lib/cli/src/automigrate/fixes/sb-binary.ts
  code/lib/cli/src/automigrate/fixes/sb-scripts.ts
  code/lib/cli/src/automigrate/fixes/sveltekit-framework.test.ts
  code/lib/cli/src/automigrate/fixes/sveltekit-framework.ts
  code/lib/cli/src/automigrate/fixes/webpack5.ts
  code/lib/cli/src/automigrate/helpers/detectRenderer.ts
  code/lib/cli/src/automigrate/helpers/mainConfigFile.ts
  code/lib/cli/src/automigrate/helpers/testing-helpers.ts
  code/lib/cli/src/automigrate/index.ts
  code/lib/cli/src/automigrate/types.ts
  code/lib/cli/src/babel-config.ts
  code/lib/cli/src/generate.ts
  code/lib/cli/src/js-package-manager/JsPackageManager.ts
  code/lib/cli/src/upgrade.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
  code/lib/core-common/src/utils/load-main-config.ts
  code/lib/core-common/src/utils/validate-config.ts
  code/lib/core-common/src/utils/validate-configuration-files.ts
  code/lib/csf-tools/src/ConfigFile.ts
  code/lib/types/src/modules/core-common.ts
  code/package.json
  code/renderers/svelte/src/public-types.test.ts
  code/renderers/svelte/template/stories/views/ButtonView.svelte
  code/yarn.lock
Labels: feature request, cli, ci:daily

#21159 Storysource: Fallback to the `docs.source.originalSource` parameter
  code/addons/storysource/src/StoryPanel.tsx
Labels: bug, addon: storysource, builder-vite

#21144 Fix StorybookConfig of webcomponents-webpack5 framework
  code/frameworks/web-components-webpack5/src/types.ts
Labels: bug, typescript, web-components

#21108 Core: Rename `framework` parameter to `renderer`
  MIGRATION.md
  code/addons/storyshots-core/src/test-bodies.ts
  code/frameworks/angular/src/client/config.ts
  code/frameworks/angular/src/client/public-api.ts
  code/frameworks/ember/src/client/preview/config.ts
  code/frameworks/ember/src/client/preview/index.ts
  code/lib/preview-api/src/modules/core-client/start.test.ts
  code/lib/preview-api/src/modules/core-client/start.ts
  code/renderers/html/src/config.ts
  code/renderers/html/src/public-api.ts
  code/renderers/preact/src/config.ts
  code/renderers/preact/src/public-api.ts
  code/renderers/react/src/config.ts
  code/renderers/react/src/public-api.tsx
  code/renderers/server/src/config.ts
  code/renderers/server/src/public-api.ts
  code/renderers/svelte/src/config.ts
  code/renderers/svelte/src/public-api.ts
  code/renderers/vue/src/config.ts
  code/renderers/vue/src/public-api.ts
  code/renderers/vue3/src/config.ts
  code/renderers/vue3/src/public-api.ts
  code/renderers/web-components/src/config.ts
  code/renderers/web-components/src/public-api.ts
Labels: maintenance

#21163 Correctly detect Safari in browser supports CSS Zoom
  code/ui/components/src/Zoom/browserSupportsCssZoom.ts
Labels: bug, ui

#21164 Maintenance: fix type errors on automigrate `check` step
  code/lib/cli/src/automigrate/types.ts
Labels: maintenance, cli

#21059 fix(angular): provide constructor dependencies
  code/frameworks/angular/package.json
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/StorybookWrapperComponent.ts
  code/frameworks/angular/src/client/angular-beta/__testfixtures__/test.module.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
  code/frameworks/angular/src/client/types.ts
  code/frameworks/angular/template/stories/others/app-initializer-use-factory/app-initializer-use-factory.stories.ts
  code/yarn.lock
Labels: bug, angular

#21162 Add missing dependencies to @storybook/nextjs to fix pnpm
  code/frameworks/nextjs/package.json
  code/yarn.lock
Labels: bug

#21167 Angular: Fix 'isStandalone' function not available error
  code/frameworks/angular/package.json
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.test.ts
  code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts
  code/yarn.lock
Labels: bug, angular, ci:daily

#21112 Core: Don't crash when there are errors indexing
  code/lib/core-server/src/utils/StoryIndexGenerator.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/doTelemetry.ts
  code/lib/core-server/src/withTelemetry.ts
  code/lib/manager-api/src/modules/stories.ts
  code/lib/manager-api/src/tests/stories.test.ts
Labels: feature request, core

#21114 Core: Coalesce multiple indexing errors into one
  code/addons/docs/template/stories/stories-mdx/csf-in-mdx.non-stories.js
  code/addons/docs/template/stories/stories-mdx/csf-in-mdx.stories.mdx
  code/lib/core-server/src/utils/IndexingError.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.test.ts
  code/lib/core-server/src/utils/StoryIndexGenerator.ts
  code/lib/core-server/src/utils/__tests__/IndexingError.test.ts
  code/lib/core-server/src/utils/stories-json.test.ts
  code/lib/core-server/src/utils/stories-json.ts
Labels: feature request, core

#21166 CLI: Fix CRA init, ensure the new version of the preset
  MIGRATION.md
  code/lib/cli/src/generators/REACT_SCRIPTS/index.ts
  code/lib/cli/src/versions.ts
Labels: bug, cli, cra

#21169 Build: Add check step to `ci:daily` workflow
  .circleci/config.yml
Labels: build

#21168 CLI: Improve how automigrations read `main.js`
  code/lib/cli/src/automigrate/fixes/angular12.test.ts
  code/lib/cli/src/automigrate/fixes/angular12.ts
  code/lib/cli/src/automigrate/fixes/autodocs-true.test.ts
  code/lib/cli/src/automigrate/fixes/autodocs-true.ts
  code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.test.ts
  code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.ts
  code/lib/cli/src/automigrate/fixes/builder-vite.test.ts
  code/lib/cli/src/automigrate/fixes/builder-vite.ts
  code/lib/cli/src/automigrate/fixes/cra5.test.ts
  code/lib/cli/src/automigrate/fixes/cra5.ts
  code/lib/cli/src/automigrate/fixes/eslint-plugin.test.ts
  code/lib/cli/src/automigrate/fixes/eslint-plugin.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.test.ts
  code/lib/cli/src/automigrate/fixes/missing-babelrc.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/new-frameworks.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks/utils.ts
  code/lib/cli/src/automigrate/fixes/nodejs-requirement.test.ts
  code/lib/cli/src/automigrate/fixes/nodejs-requirement.ts
  code/lib/cli/src/automigrate/fixes/remove-global-client-apis.ts
  code/lib/cli/src/automigrate/fixes/sb-binary.test.ts
  code/lib/cli/src/automigrate/fixes/sb-binary.ts
  code/lib/cli/src/automigrate/fixes/sb-scripts.test.ts
  code/lib/cli/src/automigrate/fixes/sb-scripts.ts
  code/lib/cli/src/automigrate/fixes/vue3.test.ts
  code/lib/cli/src/automigrate/fixes/vue3.ts
  code/lib/cli/src/automigrate/fixes/webpack5.test.ts
  code/lib/cli/src/automigrate/fixes/webpack5.ts
  code/lib/cli/src/automigrate/helpers/checkWebpack5Builder.ts
  code/lib/cli/src/automigrate/helpers/mainConfigFile.ts
Labels: bug, cli, ci:daily

#21150 Addon-docs: Fix style bleeding
  code/addons/docs/src/DocsRenderer.tsx
  code/ui/.storybook/preview.tsx
  code/ui/blocks/src/blocks/DocsContainer.tsx
  code/ui/blocks/src/blocks/Subtitle.tsx
  code/ui/blocks/src/blocks/Title.tsx
  code/ui/blocks/src/components/ArgsTable/ArgsTable.tsx
  code/ui/blocks/src/components/ColorPalette.tsx
  code/ui/blocks/src/components/DocsPage.tsx
  code/ui/blocks/src/components/EmptyBlock.tsx
  code/ui/blocks/src/components/IconGallery.tsx
  code/ui/blocks/src/components/Preview.tsx
  code/ui/blocks/src/components/Source.tsx
  code/ui/blocks/src/components/Story.tsx
  code/ui/blocks/src/components/Typeset.tsx
Labels: bug, ui, addon: docs

#21181 Fix Angular NG0800 error
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
Labels: bug, ci:daily

#21180 CLI: Fix jscodeshift error: env: node\r: No such file or directory
  code/lib/codemod/src/index.js
Labels: bug, cli

#21188 Csf Tools: Support satisfies and as TS operator with module.exports
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: bug, core

#21073 Codemod: Convert `.stories.mdx` to MDX and CSF
  code/jest.config.base.js
  code/lib/codemod/jest.config.js
  code/lib/codemod/package.json
  code/lib/codemod/src/index.js
  code/lib/codemod/src/transforms/__tests__/mdx-to-csf.test.ts
  code/lib/codemod/src/transforms/mdx-to-csf.ts
  code/lib/csf-tools/src/babelParse.ts
  code/lib/csf-tools/src/index.ts
  code/yarn.lock
Labels: feature request, cli, codemods

#21190 Csf Tools: Fix overriding scalar named export values
  code/lib/csf-tools/src/ConfigFile.test.ts
  code/lib/csf-tools/src/ConfigFile.ts
Labels: bug, cli, csf

#21194 Build: Fix Playwright to v1.30.0
  scripts/utils/yarn.ts
Labels: build, ci:daily

#21199 Build: add @storybook/bench
  .circleci/config.yml
  code/package.json
  code/yarn.lock
Labels: build

#21200 Build: pass debug option to sandbox generate task
  scripts/tasks/generate.ts
Labels: build

#21186 CLI: Add automigration for GFM in MDX
  code/addons/gfm/README.md
  code/addons/gfm/jest.config.js
  code/addons/gfm/package.json
  code/addons/gfm/preset.js
  code/addons/gfm/project.json
  code/addons/gfm/src/index.ts
  code/addons/gfm/tsconfig.json
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/fixes/mdx-gfm.test.ts
  code/lib/cli/src/automigrate/fixes/mdx-gfm.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
  code/lib/cli/src/automigrate/helpers/new-frameworks-utils.test.ts
  code/lib/cli/src/automigrate/helpers/new-frameworks-utils.ts
  code/package.json
  code/yarn.lock
  docs/snippets/common/storybook-main-config-remark-options.js.mdx
  docs/snippets/common/storybook-main-config-remark-options.ts.mdx
Labels: feature request, cli, codemods

#21202 Initialize .storybook folder without references to root for Angular sub projects
  code/lib/cli/src/generators/ANGULAR/index.ts
  code/lib/telemetry/src/storybook-metadata.ts
Labels: bug, ci:daily

#21178 Autodocs: Hide Stories block when only primary story exists
  code/ui/blocks/src/blocks/DocsPage.stories.tsx
  code/ui/blocks/src/blocks/DocsPage.tsx
  code/ui/blocks/src/examples/DocsPageParameters.stories.tsx
Labels: feature request, ui, addon: docs

#21203 CLI: Only run useful automigrations on init
  code/lib/cli/src/automigrate/fixes/index.ts
  code/lib/cli/src/automigrate/index.ts
  code/lib/cli/src/initiate.ts
Labels: maintenance, cli

#21210 CLI: Fix SvelteKit automigration package name
  MIGRATION.md
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.ts
Labels: bug, cli, sveltekit

#21205 Add preview type and update CLI template
  code/frameworks/angular/src/client/public-types.ts
  code/lib/cli/package.json
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/generators/configure.test.ts
  code/lib/cli/src/generators/configure.ts
  code/lib/types/src/modules/csf.ts
  code/renderers/html/src/public-types.ts
  code/renderers/preact/src/public-types.ts
  code/renderers/react/src/public-types.ts
  code/renderers/server/src/public-types.ts
  code/renderers/svelte/src/public-types.ts
  code/renderers/vue/src/public-types.ts
  code/renderers/vue3/src/public-types.ts
  code/renderers/web-components/src/public-types.ts
  code/yarn.lock
Labels: feature request, typescript

#21219 Angular: Properly destroy component when switching to another Story
  code/frameworks/angular/src/client/angular-beta/AbstractRenderer.ts
Labels: bug, ci:daily

#21165 pnpm: Fix run command for pnpm API
  code/lib/cli/src/js-package-manager/PNPMProxy.test.ts
  code/lib/cli/src/js-package-manager/PNPMProxy.ts
Labels: bug, pnpm

#21222 Chore: (Docs) Asset and snippet fixes
  docs/get-started/browse-stories.md
  docs/get-started/docblock-source.png
  docs/snippets/common/storybook-auto-docs-mdx-docs-story.mdx.mdx
  docs/writing-docs/autodocs-default-template.png
  docs/writing-docs/doc-blocks.md
Labels: documentation

#21225 Preact: Enable ts plugin by default
  code/presets/preact-webpack/package.json
  code/presets/preact-webpack/src/index.ts
  code/yarn.lock
Labels: bug, ci:daily

#21183 fix(docs): tiny error in react ts code snippets
  docs/snippets/react/list-story-reuse-data.ts-4-9.mdx
  docs/snippets/react/list-story-reuse-data.ts.mdx
Labels: documentation

#21228 Chore: (Docs) Remove interaction debugger flag from docs
  docs/snippets/common/storybook-addon-interaction-registration.js.mdx
  docs/snippets/common/storybook-interactions-addon-registration.js.mdx
  docs/snippets/common/storybook-interactions-addon-registration.ts.mdx
  docs/snippets/common/storybook-main-enable-interactive-debugger.js.mdx
  docs/writing-stories/play-function.md
  docs/writing-tests/interaction-testing.md
Labels: documentation

#21226 mdx-to-csf codemod: Fix wrong export referenced in generated mdx
  code/lib/codemod/src/transforms/__tests__/mdx-to-csf.test.ts
  code/lib/codemod/src/transforms/mdx-to-csf.ts
Labels: bug, cli, codemods

#21230 Build: Add mixed exports test case to composeConfigs
  code/lib/preview-api/src/modules/store/csf/composeConfigs.test.ts
Labels: build

#21227 Core: Add `preview.js` default export support
  .circleci/config.yml
  code/lib/builder-vite/src/codegen-iframe-script.ts
  code/lib/builder-webpack5/templates/virtualModuleEntry.template.js
  code/lib/cli/src/generators/baseGenerator.ts
  code/lib/cli/src/helpers.test.ts
  code/lib/cli/src/helpers.ts
  code/lib/cli/src/sandbox-templates.ts
  code/lib/preview-api/src/modules/store/csf/composeConfigs.test.ts
  code/lib/preview-api/src/modules/store/csf/composeConfigs.ts
  scripts/sandbox-generators/generate-sandboxes.ts
Labels: feature request, core, ci:daily

#21197 Docs: Remove `react-dom@18` warning in docs
  code/addons/docs/package.json
  code/addons/docs/src/DocsRenderer.tsx
  code/addons/docs/src/preset.ts
  code/lib/builder-vite/input/react-dom-client-placeholder.js
  code/lib/builder-vite/package.json
  code/lib/builder-vite/src/plugins/code-generator-plugin.ts
  code/lib/cli/src/versions.ts
  code/lib/react-dom-shim/README.md
  code/lib/react-dom-shim/package.json
  code/lib/react-dom-shim/project.json
  code/lib/react-dom-shim/src/preset.ts
  code/lib/react-dom-shim/src/react-16.tsx
  code/lib/react-dom-shim/src/react-18.tsx
  code/lib/react-dom-shim/tsconfig.json
  code/presets/react-webpack/package.json
  code/presets/react-webpack/src/framework-preset-react-dom-hack.ts
  code/presets/react-webpack/src/index.ts
  code/renderers/react/package.json
  code/renderers/react/preset.js
  code/renderers/react/src/preset.ts
  code/renderers/react/src/render.tsx
  code/yarn.lock
Labels: bug, react, addon: docs, builder-webpack5, builder-vite, ci:daily

#21237 Revert "Remove vue-cli as sandbox template is currently busted"
  .circleci/config.yml
  code/lib/cli/src/sandbox-templates.ts
Labels: build, ci:daily

#21238 Build: Disable broken cra-bench
  .circleci/config.yml
Labels: build

#21241 Build: upgrade playwright & re-enable bench
  .circleci/config.yml
  code/package.json
  code/yarn.lock
  scripts/utils/yarn.ts
Labels: build, ci:merged

#21220 Documentation: Update main.js exports migration
  MIGRATION.md
Labels: documentation

#21249 Build: Remove jest_workaround swc package by adding extra jest.mock functions
  code/jest.config.base.js
  code/lib/cli/src/automigrate/fixes/autodocs-true.test.ts
  code/lib/cli/src/automigrate/fixes/builder-vite.test.ts
  code/lib/cli/src/automigrate/fixes/cra5.test.ts
  code/lib/cli/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli/src/automigrate/fixes/sb-binary.test.ts
  code/lib/cli/src/automigrate/fixes/vue3.test.ts
  code/lib/cli/src/automigrate/fixes/webpack5.test.ts
  code/lib/cli/src/automigrate/helpers/testing-helpers.ts
  code/package.json
  code/yarn.lock
Labels: maintenance

#21148 Chore: (Docs) Renaming imports to new package name from @storybook/ui…
  code/ui/manager/README.md
Labels: documentation

#21254 Documentation: Add MIGRATION.md entry regarding preview.js default export
  MIGRATION.md
Labels: documentation

#21257 Documentation: Fix main.ts import for consistency
  docs/snippets/common/storybook-a11y-register.ts.mdx
  docs/snippets/common/storybook-main-add-ts-config.ts.mdx
  docs/snippets/common/storybook-main-baseline-setup.ts.mdx
  docs/snippets/common/storybook-main-disable-telemetry.main-ts.ts.mdx
  docs/snippets/common/storybook-main-extend-ts-config.ts.mdx
  docs/snippets/common/storybook-main-js-md-files.ts.mdx
  docs/snippets/common/storybook-on-demand-story-loading.ts.mdx
  docs/snippets/common/storybook-storyloading-custom-logic.ts.mdx
  docs/snippets/common/storybook-storyloading-with-custom-object.ts.mdx
  docs/snippets/common/storybook-storyloading-with-directory.ts.mdx
  docs/snippets/common/storybook-telemetry-main-enable-crash-reports.main-ts.ts.mdx
Labels: documentation

#21269 CLI: Fix performance regression of storybook dev
  code/lib/cli/src/generators/configure.ts
Labels: bug

#21212 Docs: Show errors when stories throw in docs
  code/addons/docs/template/stories/docspage/error.stories.ts
  code/e2e-tests/addon-docs.spec.ts
  code/lib/preview-api/src/modules/preview-web/Preview.tsx
  code/lib/preview-api/src/modules/preview-web/PreviewWeb.test.ts
  code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx
  code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts
  code/lib/types/src/modules/docs.ts
  code/ui/blocks/src/blocks/Canvas.stories.tsx
  code/ui/blocks/src/blocks/Story.stories.tsx
  code/ui/blocks/src/components/Story.stories.tsx
  code/ui/blocks/src/components/Story.tsx
  code/ui/blocks/src/examples/Button.stories.tsx
  code/ui/components/src/ErrorFormatter/ErrorFormatter.stories.tsx
  code/ui/components/src/ErrorFormatter/ErrorFormatter.tsx
  code/ui/components/src/index.ts
  code/ui/manager/src/components/sidebar/RefBlocks.tsx
  code/ui/manager/src/globals/exports.ts
Labels: bug, addon: docs, block: other

#21270 CLI: Pass config-dir cli arg from upgrade command to automigration step
  code/lib/cli/src/upgrade.ts
Labels: bug, cli

#21104 Taking care of next/babel preset
  code/frameworks/nextjs/package.json
  code/frameworks/nextjs/src/babel/plugins/amp-attributes.ts
  code/frameworks/nextjs/src/babel/plugins/commonjs.ts
  code/frameworks/nextjs/src/babel/plugins/jsx-pragma.ts
  code/frameworks/nextjs/src/babel/plugins/next-font-unsupported.ts
  code/frameworks/nextjs/src/babel/plugins/next-page-config.ts
  code/frameworks/nextjs/src/babel/plugins/next-page-disallow-re-export-all-exports.ts
  code/frameworks/nextjs/src/babel/plugins/next-ssg-transform.ts
  code/frameworks/nextjs/src/babel/plugins/optimize-hook-destructuring.ts
  code/frameworks/nextjs/src/babel/plugins/react-loadable-plugin.ts
  code/frameworks/nextjs/src/babel/preset.ts
  code/frameworks/nextjs/src/globals.d.ts
  code/frameworks/nextjs/src/preset.ts
  code/frameworks/nextjs/src/styledJsx/decorator.tsx
  code/yarn.lock
Labels: bug, ci:daily

#21182 Reverse order of project decorators
  MIGRATION.md
  code/frameworks/nextjs/src/routing/app-router-provider.tsx
  code/frameworks/nextjs/src/routing/decorator.tsx
  code/lib/core-server/src/presets/common-preset.ts
  code/lib/preview-api/src/modules/store/csf/composeConfigs.test.ts
  code/lib/preview-api/src/modules/store/csf/composeConfigs.ts
  code/lib/preview-api/src/typings.d.ts
  code/lib/types/src/modules/core-common.ts
Labels: bug, ci:daily

#21173 TypeScript: Add `env` type to BuilderOptions
  code/lib/types/src/modules/core-common.ts
Labels: bug, core, typescript, builder-webpack5, builder-vite

#21258 Documentation: Update preview.js snippets to default export
  docs/snippets/angular/storybook-preview-global-decorator.ts.mdx
  docs/snippets/angular/storybook-preview-with-angular-polyfills.js.mdx
  docs/snippets/angular/storybook-preview-with-styled-components-decorator.ts.mdx
  docs/snippets/common/button-story-project-args-theme.js.mdx
  docs/snippets/common/preview-story-custom-params.js.mdx
  docs/snippets/common/storybook-addon-a11y-global-config.js.mdx
  docs/snippets/common/storybook-addon-controls-custom-matchers.js.mdx
  docs/snippets/common/storybook-addon-preset-example.js.mdx
  docs/snippets/common/storybook-backgrounds-addon-default-params.js.mdx
  docs/snippets/common/storybook-preview-auto-docs-custom-docs-container.js.mdx
  docs/snippets/common/storybook-preview-auto-docs-custom-template-function.js.mdx
  docs/snippets/common/storybook-preview-auto-docs-override-mdx-container.js.mdx
  docs/snippets/common/storybook-preview-auto-docs-override-theme.js.mdx
  docs/snippets/common/storybook-preview-change-viewports.js.mdx
  docs/snippets/common/storybook-preview-configure-background-colors.js.mdx
  docs/snippets/common/storybook-preview-configure-globaltypes.js.mdx
  docs/snippets/common/storybook-preview-custom-canvas.js.mdx
  docs/snippets/common/storybook-preview-custom-code-renderer.js.mdx
  docs/snippets/common/storybook-preview-custom-params.js.mdx
  docs/snippets/common/storybook-preview-docs-dark-theme.js.mdx
  docs/snippets/common/storybook-preview-empty-sort-object.js.mdx
  docs/snippets/common/storybook-preview-expanded-controls.js.mdx
  docs/snippets/common/storybook-preview-global-loader.js.mdx
  docs/snippets/common/storybook-preview-global-parameters.js.mdx
  docs/snippets/common/storybook-preview-granular-viewports.js.mdx
  docs/snippets/common/storybook-preview-layout-param.js.mdx
  docs/snippets/common/storybook-preview-locales-globaltype.js.mdx
  docs/snippets/common/storybook-preview-matching-argtypes.js.mdx
  docs/snippets/common/storybook-preview-merge-viewports.js.mdx
  docs/snippets/common/storybook-preview-optout-inline.js.mdx
  docs/snippets/common/storybook-preview-parameters-color-swatches.js.mdx
  docs/snippets/common/storybook-preview-parameters-old-format.js.mdx
  docs/snippets/common/storybook-preview-prepareforinline.js.mdx
  docs/snippets/common/storybook-preview-register-language-globally.js.mdx
  docs/snippets/common/storybook-preview-register-msw-addon.js.mdx
  docs/snippets/common/storybook-preview-sort-function.js.mdx
  docs/snippets/common/storybook-preview-use-global-type.js.mdx
  docs/snippets/common/storybook-preview-viewport-use-new-devices.js.mdx
  docs/snippets/common/storybook-preview-with-mock-decorator.js.mdx
  docs/snippets/common/storybook-preview-with-ordered-pages-and-wildcard.js.mdx
  docs/snippets/common/storybook-preview-with-ordered-pages.js.mdx
  docs/snippets/react/mock-context-container-global.js.mdx
  docs/snippets/react/storybook-preview-global-decorator.js.mdx
  docs/snippets/react/storybook-preview-global-decorator.story-function.js.mdx
  docs/snippets/react/storybook-preview-with-styled-components-decorator.js.mdx
  docs/snippets/react/storybook-preview-with-styled-components-decorator.story-function.js.mdx
  docs/snippets/svelte/storybook-preview-global-decorator.js.mdx
  docs/snippets/vue/storybook-preview-global-decorator.js.mdx
  docs/snippets/vue/storybook-preview-with-hoc-component-decorator.2-component.js.mdx
  docs/snippets/vue/storybook-preview-with-hoc-component-decorator.3-component.js.mdx
  docs/snippets/vue/storybook-preview-with-library-decorator.2-library.js.mdx
  docs/snippets/vue/storybook-preview-with-library-decorator.3-library.js.mdx
  docs/snippets/vue/storybook-preview-with-mixin-decorator.2-mixin.js.mdx
  docs/snippets/web-components/storybook-preview-global-decorator.js.mdx
Labels: documentation

#21184 CLI: Account for legacy framework values in automigration
  code/lib/cli/src/automigrate/helpers/new-frameworks-utils.test.ts
  code/lib/cli/src/automigrate/helpers/new-frameworks-utils.ts
  code/lib/core-common/src/utils/get-storybook-info.ts
Labels: bug, cli

#21278 Tech: change to a regular dependencies removing peerDep warnings
  code/presets/react-webpack/package.json
  code/yarn.lock
Labels: maintenance

#21297 Chore (Docs) Fix the Preview type snippets in the migration guide
  MIGRATION.md
Labels: documentation
