Repository storybookjs/storybook, pull requests merged in 2024-11, with the labels that each got.

#29287 Build: Gracefully handle empty folders on dev machines
  scripts/prepare/tools.ts
Labels: build, ci:normal

#28965 Chore: Improve varous aspects of sandbox creation
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contribute/code.mdx
  scripts/sandbox/generate.ts
  scripts/sandbox/utils/yarn.ts
  scripts/utils/yarn.ts
Labels: build, ci:daily

#29444 Next.js: Fix bundled react and react-dom in monorepos
  code/frameworks/nextjs/src/config/webpack.ts
  code/frameworks/nextjs/src/utils.ts
Labels: bug, nextjs, monorepos, ci:normal

#29264 Next.js: Upgrade sass-loader from ^13.2.0 to ^14.2.1
  code/frameworks/nextjs/package.json
  code/yarn.lock
Labels: dependencies, nextjs, ci:normal

#29157 Build: Shim CJS-only globals in ESM output
  code/frameworks/sveltekit/src/plugins/mock-sveltekit-stores.ts
Labels: bug, ci:normal

#29501 Addon Test: Only render the TestingModule component in development mode
  code/core/src/manager/components/sidebar/Sidebar.stories.tsx
  code/core/src/manager/components/sidebar/Sidebar.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
Labels: bug, patch:yes, ci:normal, addon: test

#29507 Core: Add support for groups to `TooltipLinkList` and use it for main Storybook menu
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/components/components/tooltip/Tooltip.tsx
  code/core/src/components/components/tooltip/TooltipLinkList.stories.tsx
  code/core/src/components/components/tooltip/TooltipLinkList.tsx
  code/core/src/manager/components/sidebar/Menu.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.tsx
  code/core/src/manager/container/Menu.tsx
Labels: feature request, ui, ci:normal

#29514 CLI: Fix Solid init by installing `@storybook/test`
  code/lib/create-storybook/src/generators/baseGenerator.ts
Labels: bug, cli, patch:yes, solid, ci:normal

#29524 Addon Test: Enhance post-install logic for Next.js Vite framework support
  code/addons/test/src/postinstall.ts
Labels: bug, patch:yes, nextjs, ci:normal, addon: test

#29523 Core: Prevent clipping box shadow on file search modal
  code/core/src/manager/components/sidebar/FileSearchModal.tsx
Labels: bug, ci:normal

#29469 Next.js: Remove duplicate comments
  code/frameworks/nextjs/src/routing/app-router-provider.tsx
Labels: nextjs, ci:normal

#29534 Documentation: How to release changes to older minors
  CONTRIBUTING/RELEASING.md
Labels: documentation, ci:docs

#29548 Docs: Correct addon-themes README to align text with code example
  code/addons/themes/README.md
Labels: documentation, ci:docs

#29174 Docs: Code contribution WSL removal
  CONTRIBUTING.md
  docs/contribute/code.mdx
Labels: documentation, ci:docs

#29558 Build: Fix type issues
  code/addons/backgrounds/src/components/Tool.tsx
  code/addons/viewport/src/components/Tool.tsx
  scripts/prepare/tools.ts
Labels: build, ci:merged

#29566 Vite Ecosystem CI: Additionally test on a built Storybook
  package.json
Labels: build, ci:normal

#29356 Build: Benchmark individual package's sizes and dependencies
  .circleci/config.yml
  scripts/bench/bench-packages.ts
  scripts/package.json
  scripts/run-registry.ts
  scripts/yarn.lock
Labels: build, ci:normal

#29225 UI: Add Yarn to About Section
  code/core/src/manager/components/upgrade/UpgradeBlock.tsx
Labels: ui, maintenance, ci:normal

#29578 CI: Fix package benchmarking failing on `next`
  .circleci/config.yml
  scripts/bench/bench-packages.ts
Labels: build, ci:normal

#29587 Next.js: Add support for Next 15
  .circleci/config.yml
  code/e2e-tests/addon-docs.spec.ts
  code/e2e-tests/framework-nextjs.spec.ts
  code/frameworks/nextjs/package.json
  code/frameworks/nextjs/src/aliases/webpack.ts
  code/frameworks/nextjs/src/compatibility/compatibility-map.ts
  code/frameworks/nextjs/src/compatibility/draft-mode.compat.ts
  code/frameworks/nextjs/src/export-mocks/headers/index.ts
  code/frameworks/nextjs/src/export-mocks/webpack.ts
  code/frameworks/nextjs/src/preset.ts
  code/frameworks/nextjs/src/routing/app-router-provider.tsx
  code/frameworks/nextjs/template/stories/DynamicImport.stories.tsx
  code/frameworks/nextjs/template/stories/Font.stories.tsx
  code/frameworks/nextjs/template/stories/Font.tsx
  code/frameworks/nextjs/template/stories/GetImageProps.stories.tsx
  code/frameworks/nextjs/template/stories/Head.stories.tsx
  code/frameworks/nextjs/template/stories/Image.stories.tsx
  code/frameworks/nextjs/template/stories/ImageLegacy.stories.tsx
  code/frameworks/nextjs/template/stories/Link.stories.module.css
  code/frameworks/nextjs/template/stories/Link.stories.tsx
  code/frameworks/nextjs/template/stories/Navigation.stories.tsx
  code/frameworks/nextjs/template/stories/NextHeader.stories.tsx
  code/frameworks/nextjs/template/stories/NextHeader.tsx
  code/frameworks/nextjs/template/stories/RSC.jsx
  code/frameworks/nextjs/template/stories/RSC.stories.tsx
  code/frameworks/nextjs/template/stories/RSC.tsx
  code/frameworks/nextjs/template/stories/Redirect.stories.tsx
  code/frameworks/nextjs/template/stories/Router.stories.tsx
  code/frameworks/nextjs/template/stories/ServerActions.stories.tsx
  code/frameworks/nextjs/template/stories/StyledJsx.stories.tsx
  code/frameworks/nextjs/template/stories/dynamic-component.tsx
  code/frameworks/nextjs/template/stories/fonts/OFL.txt
  code/frameworks/nextjs/template/stories/fonts/RubikStorm-Regular.ttf
  code/frameworks/nextjs/template/stories/server-actions.tsx
  code/frameworks/nextjs/template/stories_nextjs-default-js/Font.stories.jsx
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.module.css
  code/frameworks/nextjs/template/stories_nextjs-default-ts/Link.stories.tsx
  code/frameworks/nextjs/template/typings.d.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
  code/yarn.lock
  test-storybooks/portable-stories-kitchen-sink/nextjs/stories/DynamicImport.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/nextjs/stories/Head.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/nextjs/stories/NextHeader.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/nextjs/stories/StyledJsx.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/react/stories/AddonTest.stories.tsx
Labels: maintenance, patch:yes, nextjs, ci:merged

#29592 Build: Exclude server action stories to run in next 13
  code/frameworks/nextjs/template/stories_nextjs-default-ts/ServerActions.stories.tsx
  code/frameworks/nextjs/template/stories_nextjs-default-ts/server-actions.tsx
  code/frameworks/nextjs/template/stories_nextjs-prerelease/ServerActions.stories.tsx
  code/frameworks/nextjs/template/stories_nextjs-prerelease/server-actions.tsx
Labels: patch:yes, build, ci:normal

#29589 Docs: Fix global viewports options example
  docs/_snippets/addon-viewport-options-in-preview.md
Labels: documentation, patch:yes, ci:docs

#29595 Addon Test: Optimize internal dependencies
  code/addons/test/src/vitest-plugin/index.ts
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/playwright.config.ts
  test-storybooks/portable-stories-kitchen-sink/react/.storybook/main.ts
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
  test-storybooks/portable-stories-kitchen-sink/react/stories/AddonTest.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/react/yarn.lock
Labels: bug, patch:yes, ci:normal

#29617 Addon Test: Only optimize react deps if applicable in vitest-plugin
  code/addons/test/src/vitest-plugin/index.ts
Labels: bug, patch:yes, ci:normal, addon: test

#29629 Improve Documentation clarity of Vite Framework limitations for test-addon
  docs/writing-tests/test-addon.mdx
Labels: documentation, patch:yes, ci:docs, addon: test

#29632 CLI: Fix qwik init
  code/lib/create-storybook/src/generators/baseGenerator.ts
Labels: bug, compatibility with other tools, cli, patch:yes, ci:normal

#29520 React Native Web: Add framework, CLI integration, sandboxes
  .circleci/config.yml
  code/core/src/cli/detect.ts
  code/core/src/cli/helpers.ts
  code/core/src/cli/project_types.ts
  code/core/src/common/utils/framework-to-renderer.ts
  code/core/src/common/versions.ts
  code/core/src/types/modules/frameworks.ts
  code/e2e-tests/addon-actions.spec.ts
  code/e2e-tests/addon-controls.spec.ts
  code/e2e-tests/addon-docs.spec.ts
  code/e2e-tests/addon-interactions.spec.ts
  code/frameworks/react-native-web-vite/README.md
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-native-web-vite/preset.js
  code/frameworks/react-native-web-vite/project.json
  code/frameworks/react-native-web-vite/src/index.ts
  code/frameworks/react-native-web-vite/src/preset.ts
  code/frameworks/react-native-web-vite/src/types.ts
  code/frameworks/react-native-web-vite/template/cli/.eslintrc.json
  code/frameworks/react-native-web-vite/template/cli/js/Button.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Button.stories.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Header.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Header.stories.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Page.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Page.stories.jsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Button.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Button.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Header.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Header.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Page.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-3-8/Page.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Button.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Button.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Header.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Header.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Page.stories.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Page.tsx
  code/frameworks/react-native-web-vite/tsconfig.json
  code/frameworks/react-native-web-vite/vitest.config.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
  code/lib/create-storybook/src/generators/REACT_NATIVE_WEB/index.ts
  code/lib/create-storybook/src/generators/baseGenerator.ts
  code/lib/create-storybook/src/initiate.ts
  code/package.json
  code/yarn.lock
  docs/_snippets/react-native-web-vite-add-framework.md
  docs/_snippets/react-native-web-vite-install.md
  docs/get-started/frameworks/react-native-web-vite.mdx
  docs/get-started/frameworks/svelte-vite.mdx
  docs/get-started/frameworks/svelte-webpack5.mdx
  docs/get-started/frameworks/sveltekit.mdx
  docs/get-started/frameworks/vue3-vite.mdx
  docs/get-started/frameworks/vue3-webpack5.mdx
  docs/get-started/frameworks/web-components-vite.mdx
  docs/get-started/frameworks/web-components-webpack5.mdx
  scripts/sandbox/generate.ts
  scripts/tasks/sandbox-parts.ts
Labels: feature request, ci:daily, react-native-web

#29627 CLI: Disable corepack auto pin behavior
  code/core/src/common/js-package-manager/JsPackageManagerFactory.ts
Labels: bug, cli, patch:yes, ci:normal

#29645 RNW-Vite: Integrate with experimental-addon-test
  code/addons/test/src/postinstall.ts
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-native-web-vite/src/preset.ts
  code/frameworks/react-native-web-vite/src/vite-plugin.ts
Labels: feature request, ci:daily, addon: test, react-native-web

#29630 Docs: Resolutions documentation minor cleanup
  RESOLUTIONS.md
Labels: documentation, ci:docs

#29614 Docs: Readme - Fix the Twitter links
  README.md
Labels: documentation, ci:docs

#29557 UI: Sidebar context menu addon API
  code/.storybook/preview.tsx
  code/addons/test/src/components/ContextMenuItem.tsx
  code/addons/test/src/components/Panel.test.ts
  code/addons/test/src/components/Panel.tsx
  code/addons/test/src/components/PanelTitle.tsx
  code/addons/test/src/components/RelativeTime.tsx
  code/addons/test/src/manager.tsx
  code/addons/test/src/node/test-manager.test.ts
  code/addons/test/src/node/vitest-manager.ts
  code/core/package.json
  code/core/scripts/entries.ts
  code/core/scripts/helpers/generateTypesFiles.ts
  code/core/scripts/helpers/modifyThemeTypes.ts
  code/core/scripts/prep.ts
  code/core/src/components/components/tooltip/TooltipLinkList.tsx
  code/core/src/components/components/tooltip/WithTooltip.tsx
  code/core/src/core-events/data/testing-module.ts
  code/core/src/manager-api/lib/store-setup.ts
  code/core/src/manager-api/modules/addons.ts
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager-api/root.tsx
  code/core/src/manager/components/sidebar/ContextMenu.tsx
  code/core/src/manager/components/sidebar/FileSearchList.stories.tsx
  code/core/src/manager/components/sidebar/FileSearchListSkeleton.stories.tsx
  code/core/src/manager/components/sidebar/FileSearchModal.stories.tsx
  code/core/src/manager/components/sidebar/FilterToggle.stories.ts
  code/core/src/manager/components/sidebar/IconSymbols.stories.tsx
  code/core/src/manager/components/sidebar/LegacyRender.tsx
  code/core/src/manager/components/sidebar/Menu.tsx
  code/core/src/manager/components/sidebar/RefIndicator.tsx
  code/core/src/manager/components/sidebar/Refs.stories.tsx
  code/core/src/manager/components/sidebar/Sidebar.stories.tsx
  code/core/src/manager/components/sidebar/Sidebar.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TagsFilter.stories.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/core/src/manager/components/sidebar/Tree.stories.tsx
  code/core/src/manager/components/sidebar/Tree.tsx
  code/core/src/types/modules/addons.ts
  code/lib/blocks/src/components/ArgsTable/ArgsTable.stories.tsx
  code/lib/blocks/src/examples/Button.stories.tsx
Labels: feature request, ui, ci:normal, addon: test

#29660 Manager: Fix size regression
  code/core/src/manager/components/sidebar/StatusContext.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/core/src/manager/settings/defaultShortcuts.tsx
Labels: bug, ui, ci:normal

#29661 Add discrepancy handling to A11yPanel
  code/addons/a11y/src/components/A11YPanel.tsx
  code/addons/a11y/src/components/A11yContext.test.tsx
  code/addons/a11y/src/components/A11yContext.tsx
  code/addons/a11y/src/components/TestDiscrepancyMessage.tsx
  code/addons/a11y/src/constants.ts
  code/addons/a11y/template/stories/A11YPanel.stories.tsx
  code/addons/a11y/template/stories/TestDiscrepancyMessage.stories.tsx
  code/core/src/manager-api/modules/stories.ts
Labels: feature request, accessibility, ci:normal

#29676 Addon Test: Use pathe for better windows support
  code/addons/test/package.json
  code/addons/test/src/node/boot-test-runner.ts
  code/addons/test/src/node/test-manager.test.ts
  code/addons/test/src/node/vitest-manager.ts
  code/addons/test/src/postinstall.ts
  code/addons/test/src/preset.ts
  code/addons/test/src/vitest-plugin/index.ts
  code/yarn.lock
Labels: bug, patch:yes, ci:normal, addon: test

#29682 Support new parameters and globals for a11y
  code/.storybook/preview.tsx
  code/.storybook/storybook.setup.ts
  code/addons/a11y/README.md
  code/addons/a11y/package.json
  code/addons/a11y/src/a11yRunner.ts
  code/addons/a11y/src/components/A11yContext.test.tsx
  code/addons/a11y/src/components/A11yContext.tsx
  code/addons/a11y/src/params.ts
  code/addons/a11y/src/preview.test.tsx
  code/addons/a11y/src/preview.tsx
  code/addons/test/src/node/vitest-manager.ts
  code/yarn.lock
  docs/_snippets/storybook-addon-a11y-component-config.md
  docs/_snippets/storybook-addon-a11y-disable.md
  docs/writing-tests/accessibility-testing.mdx
Labels: feature request, accessibility, addon: a11y, ci:normal

#29690 Build: Add workaround resolution for Angular sandboxes
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: build, ci:normal

#29397 Docs: Migration guide updates for Angular Initializer changes in v7
  MIGRATION.md
Labels: documentation, ci:docs

#29696 Docs: Set init/upgrade snippets to next on next
  docs/_snippets/init-command.md
  docs/_snippets/storybook-upgrade.md
Labels: documentation, ci:docs

#29695 Revert "Build: Add workaround resolution for Angular sandboxes"
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: build, ci:normal

#29552 fix(addon-a11y): Addon-a11y displays visual bug when running the tests
  code/addons/a11y/src/components/Tabs.tsx
Labels: bug, addon: a11y, ci:normal

#29656 Core + Addon Test: Refactor test API and fix total test count
  .circleci/config.yml
  code/addons/test/src/components/ContextMenuItem.tsx
  code/addons/test/src/manager.tsx
  code/addons/test/src/node/boot-test-runner.test.ts
  code/addons/test/src/node/boot-test-runner.ts
  code/addons/test/src/node/reporter.ts
  code/addons/test/src/node/test-manager.test.ts
  code/addons/test/src/node/test-manager.ts
  code/addons/test/src/node/vitest-manager.ts
  code/addons/test/src/preset.ts
  code/addons/test/src/vitest-plugin/index.ts
  code/core/src/core-events/data/testing-module.ts
  code/core/src/core-events/index.ts
  code/core/src/csf-tools/vitest-plugin/transformer.ts
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager/components/sidebar/ContextMenu.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/globals/exports.ts
  code/core/src/types/modules/addons.ts
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
Labels: bug, ci:normal

#29662 TestAddon: Refactor UI & add config options
  code/addons/test/src/components/Description.tsx
  code/addons/test/src/components/RelativeTime.tsx
  code/addons/test/src/components/Subnav.tsx
  code/addons/test/src/components/TestProviderRender.stories.tsx
  code/addons/test/src/components/TestProviderRender.tsx
  code/addons/test/src/constants.ts
  code/addons/test/src/manager.tsx
  code/addons/test/src/node/test-manager.ts
  code/core/src/core-events/data/testing-module.ts
  code/core/src/core-events/index.ts
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/core/src/manager/globals/exports.ts
  code/core/src/types/modules/addons.ts
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
Labels: feature request, ui, ci:normal, addon: test

#29711 Core: Emit deprecated `TESTING_MODULE_RUN_ALL_REQUEST` for backward compatibility
  code/core/src/core-events/index.ts
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager/globals/exports.ts
Labels: bug, ci:normal

#29518 Vue: Fix `vue-component-meta` docgen HMR not working
  code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts
Labels: bug, vue3, ci:normal

#29722 Build: Temporarily remove react native sandbox
  .circleci/config.yml
  code/lib/cli-storybook/src/sandbox-templates.ts
Labels: build, ci:docs

#29723 Build: Temporarily downgrade Vite to v5 in sandboxes
  .circleci/config.yml
  code/lib/cli-storybook/src/sandbox-templates.ts
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: build, ci:daily

#29672 Manager: Add tags property to GroupEntry objects
  code/core/src/manager-api/lib/intersect.ts
  code/core/src/manager-api/lib/stories.ts
  code/core/src/manager-api/tests/stories.test.ts
  code/core/src/manager/components/sidebar/__tests__/Sidebar.test.tsx
  code/core/src/types/modules/api-stories.ts
Labels: bug, ui, ci:normal

#29708 Core / Addon Test: Add config UI to Testing Module
  code/addons/onboarding/src/features/GuidedTour/GuidedTour.tsx
  code/addons/test/src/components/Description.tsx
  code/addons/test/src/components/TestProviderRender.stories.tsx
  code/addons/test/src/components/TestProviderRender.tsx
  code/addons/test/src/components/TestStatusIcon.stories.tsx
  code/addons/test/src/components/TestStatusIcon.tsx
  code/addons/test/src/manager.tsx
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager/components/sidebar/LegacyRender.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
Labels: feature request, ci:normal

#29731 Svelte: Support `@sveltejs/vite-plugin-svelte` v5
  code/frameworks/svelte-vite/package.json
  code/yarn.lock
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: dependencies, svelte, builder-vite, ci:daily

#29724 React: Upgrade react-docgen-typescript to support Vite 6
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-vite/package.json
  code/yarn.lock
  scripts/tasks/sandbox-parts.ts
  scripts/utils/yarn.ts
Labels: build, ci:daily

#29733 Portable stories: Support multiple annotation notations from preview
  code/core/src/preview-api/modules/store/csf/portable-stories.test.ts
  code/core/src/preview-api/modules/store/csf/portable-stories.ts
Labels: bug, patch:yes, ci:normal, portable stories

#29748 Build: Fix portable stories tests by moving from jsdom to happy-dom
  test-storybooks/portable-stories-kitchen-sink/nextjs/jest.config.js
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/stories/__snapshots__/portable-stories.test.tsx.snap
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/svelte/vite.config.ts
Labels: patch:yes, build, ci:normal

#29713 Test: Add coverage feature
  code/addons/test/package.json
  code/addons/test/src/components/TestProviderRender.stories.tsx
  code/addons/test/src/components/TestProviderRender.tsx
  code/addons/test/src/constants.ts
  code/addons/test/src/node/boot-test-runner.ts
  code/addons/test/src/node/coverage-reporter.ts
  code/addons/test/src/node/test-manager.ts
  code/addons/test/src/node/vitest-manager.ts
  code/addons/test/src/preset.ts
  code/core/src/core-events/data/testing-module.ts
  code/core/src/core-server/presets/common-preset.ts
  code/core/src/manager-api/modules/experimental_testmodule.ts
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/yarn.lock
Labels: feature request, ci:normal, addon: visual test

#29756 RNW-Vite: Add built-in Flow support
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-native-web-vite/src/preset.ts
  code/frameworks/react-native-web-vite/src/typings.d.ts
  code/yarn.lock
Labels: feature request, ci:normal, react-native-web

#29758 docs: correct file extension
  docs/_snippets/test-runner-custom-page-viewport.md
Labels: documentation, ci:docs
