Repository storybookjs/storybook, pull requests merged in 2025-09, with the labels that each got.

#32343 Core: Update tags filter UI
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/components/components/tooltip/WithTooltip.tsx
  code/core/src/manager/components/sidebar/TagsFilter.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.stories.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.tsx
  code/e2e-tests/tags.spec.ts
Labels: feature request, ci:daily

#32373 Core: Add default selection for tags in main config
  code/core/src/manager/components/sidebar/Sidebar.tsx
  code/core/src/manager/components/sidebar/TagsFilter.stories.tsx
  code/core/src/manager/components/sidebar/TagsFilter.tsx
  code/core/src/types/modules/core-common.ts
Labels: ui, tags, ci:normal

#32351 Cleanup: Removal of `lodash`
  code/.storybook/preview.tsx
  code/core/package.json
  code/yarn.lock
  scripts/.eslintrc.cjs
Labels: cleanup, ci:normal

#32385 CSF: Refactor CsfFile to support tests and tags
  code/core/src/csf-tools/CsfFile.test.ts
  code/core/src/csf-tools/CsfFile.ts
  code/core/src/csf-tools/vitest-plugin/transformer.ts
  code/core/src/preview-api/modules/store/csf/prepareStory.ts
Labels: csf, ci:normal, addon: vitest

#32341 Docs: Update CSF Next API reference
  docs/_snippets/csf-factories-automigrate.md
  docs/_snippets/csf-next-builder-aliases.md
  docs/api/csf/csf-factories.mdx
  docs/api/csf/csf-next.mdx
Labels: documentation, patch:yes, ci:docs

#32387 Docs: Add 9 -> 10 migration guide
  docs/releases/migration-guide-from-older-version.mdx
  docs/releases/migration-guide.mdx
Labels: documentation, ci:docs

#32296 Modernize: Replace `fs-extra` with native APIs
  scripts/bench/utils.ts
  scripts/build-package.ts
  scripts/check-package.ts
  scripts/combine-compodoc.ts
  scripts/get-report-message.ts
  scripts/get-template.ts
  scripts/package.json
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/__tests__/version.test.ts
  scripts/release/__tests__/write-changelog.test.ts
  scripts/release/get-changelog-from-file.ts
  scripts/release/get-current-version.ts
  scripts/release/is-pr-frozen.ts
  scripts/release/publish.ts
  scripts/release/version.ts
  scripts/release/write-changelog.ts
  scripts/reset.js
  scripts/run-registry.ts
  scripts/sandbox/generate.ts
  scripts/sandbox/publish.ts
  scripts/sandbox/utils/template.ts
  scripts/sandbox/utils/yarn.ts
  scripts/task.ts
  scripts/tasks/build.ts
  scripts/tasks/compile.ts
  scripts/tasks/generate.ts
  scripts/tasks/install.ts
  scripts/tasks/publish.ts
  scripts/tasks/sandbox-parts.ts
  scripts/tasks/sandbox.ts
  scripts/utils/filterExistsInCodeDir.ts
  scripts/utils/package-json.ts
  scripts/utils/paths.ts
  scripts/utils/tools.ts
  scripts/utils/yarn.ts
  scripts/yarn.lock
Labels: maintenance, ci:normal

#32414 CSF: Enhance csf-factories codemods
  code/lib/cli-storybook/src/codemod/helpers/config-to-csf-factory.test.ts
  code/lib/cli-storybook/src/codemod/helpers/config-to-csf-factory.ts
  code/lib/cli-storybook/src/codemod/helpers/story-to-csf-factory.test.ts
  code/lib/cli-storybook/src/codemod/helpers/story-to-csf-factory.ts
Labels: bug, csf, ci:normal

#32356 Release: Adds Sentry release creation after publishing to npm
  .github/workflows/publish.yml
Labels: build, ci:normal

#32417 Core: Add include/exclude toggle for each tag in tags filter UI
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/manager/components/sidebar/TagsFilter.stories.tsx
  code/core/src/manager/components/sidebar/TagsFilter.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.stories.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.tsx
  code/core/src/types/modules/core-common.ts
Labels: feature request, ci:normal

#32448 Telemetry: Record known CLI integrations
  code/lib/create-storybook/src/initiate.test.ts
  code/lib/create-storybook/src/initiate.ts
Labels: maintenance, cli, patch:yes, telemetry, ci:normal

#32451 Publish: Fix sentry in release yaml
  .github/workflows/publish.yml
Labels: build, ci:docs

#32383 Core: Switch from `mlly` to `exsolve`
  code/core/package.json
  code/core/src/builder-manager/index.ts
  code/core/src/common/presets.ts
  code/core/src/common/utils/strip-abs-node-modules-path.ts
  code/core/src/common/utils/validate-config.ts
  code/yarn.lock
Labels: maintenance, core, ci:normal

#32083 CLI: Add addon-console automigration
  code/core/src/actions/loaders.ts
  code/core/src/csf-tools/ConfigFile.test.ts
  code/core/src/csf-tools/ConfigFile.ts
  code/frameworks/angular/template/cli/button.stories.ts
  code/frameworks/angular/template/stories_angular-cli-default-ts/signal/button.stories.ts
  code/frameworks/angular/template/stories_angular-cli-prerelease/signal/button.stories.ts
  code/frameworks/html-vite/template/cli/js/Button.stories.js
  code/frameworks/html-vite/template/cli/ts/Button.stories.ts
  code/frameworks/nextjs-vite/template/cli/js/Button.stories.js
  code/frameworks/nextjs-vite/template/cli/ts/Button.stories.ts
  code/frameworks/nextjs/template/cli/js/Button.stories.js
  code/frameworks/nextjs/template/cli/ts/Button.stories.ts
  code/frameworks/preact-vite/template/cli/Button.stories.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Button.stories.jsx
  code/frameworks/react-native-web-vite/template/cli/ts/Button.stories.tsx
  code/frameworks/react-vite/template/cli/js/Button.stories.js
  code/frameworks/react-vite/template/cli/ts/Button.stories.ts
  code/frameworks/react-webpack5/template/cli/js/Button.stories.js
  code/frameworks/react-webpack5/template/cli/ts/Button.stories.ts
  code/frameworks/vue3-vite/template/cli/js/Button.stories.js
  code/frameworks/vue3-vite/template/cli/ts/Button.stories.ts
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/cli-storybook/src/automigrate/fixes/migrate-addon-console.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/migrate-addon-console.ts
  code/renderers/html/template/cli/js/Button.stories.js
  code/renderers/html/template/cli/ts/Button.stories.ts
  code/renderers/preact/template/cli/Button.stories.jsx
  code/renderers/react/template/cli/js/Button.stories.js
  code/renderers/react/template/cli/ts/Button.stories.ts
  code/renderers/vue3/template/cli/js/Button.stories.js
  code/renderers/vue3/template/cli/ts/Button.stories.ts
  docs/_snippets/actions-filtering-example.md
  docs/_snippets/actions-spyon-basic-example.md
  docs/essentials/actions.mdx
Labels: feature request, automigrations, ci:normal

#32442 React: Preserve `@ts-expect-error` in preview
  code/renderers/react/src/preview.tsx
Labels: bug, react, typescript, ci:normal

#31338 Replace: Use `empathic` over `find-up`
  code/addons/vitest/package.json
  code/addons/vitest/src/node/vitest-manager.ts
  code/addons/vitest/src/postinstall.ts
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/plugins/external-globals-plugin.ts
  code/core/package.json
  code/core/src/cli/detect.test.ts
  code/core/src/cli/detect.ts
  code/core/src/cli/eslintPlugin.test.ts
  code/core/src/cli/eslintPlugin.ts
  code/core/src/cli/helpers.test.ts
  code/core/src/cli/helpers.ts
  code/core/src/common/js-package-manager/BUNProxy.ts
  code/core/src/common/js-package-manager/JsPackageManager.ts
  code/core/src/common/js-package-manager/JsPackageManagerFactory.test.ts
  code/core/src/common/js-package-manager/JsPackageManagerFactory.ts
  code/core/src/common/js-package-manager/NPMProxy.ts
  code/core/src/common/js-package-manager/PNPMProxy.ts
  code/core/src/common/js-package-manager/Yarn1Proxy.ts
  code/core/src/common/js-package-manager/Yarn2Proxy.ts
  code/core/src/common/utils/__tests__/paths.test.ts
  code/core/src/common/utils/get-storybook-refs.ts
  code/core/src/common/utils/paths.ts
  code/core/src/common/utils/resolve-path-in-sb-cache.ts
  code/core/src/core-server/utils/StoryIndexGenerator.ts
  code/core/src/core-server/utils/__tests__/server-address.test.ts
  code/core/src/telemetry/package-json.ts
  code/core/src/telemetry/storybook-metadata.ts
  code/frameworks/angular/package.json
  code/frameworks/angular/src/builders/build-storybook/index.spec.ts
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/index.spec.ts
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/server/framework-preset-angular-cli.test.ts
  code/frameworks/angular/src/server/framework-preset-angular-cli.ts
  code/frameworks/ember/package.json
  code/frameworks/ember/src/util.ts
  code/frameworks/react-vite/package.json
  code/frameworks/react-vite/src/plugins/react-docgen.ts
  code/frameworks/vue3-vite/package.json
  code/lib/cli-storybook/package.json
  code/lib/cli-storybook/src/util.ts
  code/lib/create-storybook/package.json
  code/lib/create-storybook/src/initiate.ts
  code/lib/create-storybook/src/ink/steps/checks/vitestConfigFiles.test.ts
  code/lib/create-storybook/src/ink/steps/checks/vitestConfigFiles.tsx
  code/presets/react-webpack/package.json
  code/presets/react-webpack/src/loaders/react-docgen-loader.ts
  code/vitest.config.ts
  code/yarn.lock
  docs/_snippets/storybook-server-framework-options.md
  docs/_snippets/storybook-server-options.md
  scripts/package.json
  scripts/yarn.lock
Labels: dependencies, core, ci:normal

#32457 CLI: Init not running `dev` when it should fixed
  code/lib/create-storybook/build-config.ts
  code/lib/create-storybook/src/bin/run.ts
Labels: bug, cli, ci:normal

#32445 Fix: ESLint plugin homepage URL updates
  code/lib/eslint-plugin/package.json
Labels: maintenance, ci:normal, eslint-plugin

#32481 Core: Special UI for built-in tags
  code/core/src/manager/components/sidebar/TagsFilter.tsx
  code/core/src/manager/components/sidebar/TagsFilterPanel.tsx
Labels: feature request, tags, ci:normal

#32484 Upgrade: Packages `open`
  code/core/package.json
  code/core/src/core-server/dev-server.ts
  code/core/src/core-server/typings.d.ts
  code/core/src/core-server/utils/open-in-browser.ts
  code/core/src/typings.d.ts
  code/yarn.lock
Labels: dependencies, ci:normal

#32488 Dev: Improve the browser opening experience
  code/core/assets/server/openBrowser.applescript
  code/core/src/core-server/dev-server.ts
  code/core/src/core-server/utils/open-browser/open-in-browser.ts
  code/core/src/core-server/utils/open-browser/opener.ts
Labels: maintenance, ci:normal

#32491 Maintenance: Remove globalization for dropped entrypoints
  code/core/src/manager/globals/exports.ts
  code/core/src/manager/globals/globals.ts
  code/core/src/manager/globals/runtime.ts
Labels: maintenance, core, ci:normal

#32134 CLI: Drop contextual dependencies in `create-storybook`
  code/lib/create-storybook/src/ink/steps/checks/vitestConfigFiles.test.ts
  code/lib/create-storybook/src/ink/steps/checks/vitestConfigFiles.tsx
Labels: cleanup, needs triage, ci:normal, addon: vitest

#32498 CSF: Improve error handling in csf factories codemod
  code/lib/cli-storybook/src/codemod/helpers/story-to-csf-factory.test.ts
  code/lib/cli-storybook/src/codemod/helpers/story-to-csf-factory.ts
Labels: bug, csf, ci:normal

#32505 Release: Ensure newline at the end of `package.json`
  scripts/release/version.ts
Labels: build, ci:docs

#32509 Core: Fix sidebar status for stories with tests and running focused tests
  code/addons/vitest/src/components/TestProviderRender.tsx
  code/addons/vitest/src/node/vitest-manager.ts
  code/core/src/manager-api/lib/stories.ts
  code/core/src/manager-api/modules/stories.ts
  code/core/src/manager/components/sidebar/Tree.tsx
  code/core/src/manager/utils/status.tsx
  code/core/src/manager/utils/tree.ts
Labels: bug, ci:normal

#32503 Update color themes
  code/.storybook/preview.tsx
  code/addons/docs/src/blocks/components/ArgsTable/ArgsTable.tsx
  code/addons/docs/src/blocks/components/TableOfContents.tsx
  code/addons/docs/src/blocks/controls/Color.tsx
  code/addons/docs/src/blocks/controls/Date.tsx
  code/addons/docs/src/blocks/controls/Number.tsx
  code/addons/docs/src/blocks/controls/Object.tsx
  code/addons/docs/src/blocks/controls/Range.tsx
  code/addons/docs/src/blocks/controls/options/Select.tsx
  code/addons/onboarding/src/components/Button/Button.stories.tsx
  code/addons/onboarding/src/components/Button/Button.tsx
  code/addons/onboarding/src/features/GuidedTour/GuidedTour.tsx
  code/addons/vitest/src/components/TestStatusIcon.tsx
  code/core/src/components/components/Badge/Badge.tsx
  code/core/src/components/components/Button/Button.tsx
  code/core/src/components/components/Form/Checkbox.tsx
  code/core/src/components/components/Form/Radio.tsx
  code/core/src/components/components/Form/Select.tsx
  code/core/src/components/components/Form/styles.ts
  code/core/src/components/components/Select/Select.stories.tsx
  code/core/src/components/components/Select/Select.tsx
  code/core/src/components/components/Select/SelectOption.tsx
  code/core/src/components/components/ToggleButton/ToggleButton.tsx
  code/core/src/components/components/tabs/EmptyTabContent.tsx
  code/core/src/components/components/tabs/tabs.hooks.tsx
  code/core/src/components/components/tabs/tabs.stories.tsx
  code/core/src/components/components/typography/lib/common.tsx
  code/core/src/components/components/typography/link/link.tsx
  code/core/src/controls/components/SaveStory.tsx
  code/core/src/manager/components/layout/Layout.tsx
  code/core/src/manager/components/notifications/NotificationItem.tsx
  code/core/src/manager/components/preview/tools/open-in-editor.tsx
  code/core/src/manager/components/sidebar/FileList.tsx
  code/core/src/manager/components/sidebar/FileSearchList.tsx
  code/core/src/manager/components/sidebar/FileSearchModal.tsx
  code/core/src/manager/components/sidebar/RefIndicator.tsx
  code/core/src/manager/components/sidebar/Refs.tsx
  code/core/src/manager/components/sidebar/Sidebar.tsx
  code/core/src/manager/components/sidebar/StatusButton.tsx
  code/core/src/manager/components/sidebar/TagsFilter.tsx
  code/core/src/manager/components/sidebar/Tree.tsx
  code/core/src/manager/utils/status.tsx
  code/core/src/preview/preview-navigator.ts
  code/core/src/theming/base.ts
  code/core/src/theming/tests/convert.test.js
  code/core/src/theming/themes/dark.ts
  code/core/src/theming/themes/light.ts
  docs/_snippets/storybook-addon-toolkit-types.md
Labels: bug, ci:normal, a11y: contrast

#32461 Dts: Ensure `.tsx` files emit `.d.ts` type files
  scripts/build/utils/dts-process.ts
Labels: bug, typescript, build, ci:normal

#32515 UI: Add proper focus outline to Button
  code/core/src/components/components/Button/Button.stories.tsx
  code/core/src/components/components/Button/Button.tsx
Labels: ui, maintenance, accessibility, ci:normal, a11y: keyboard, a11y: contrast

#32523 Mobile About: Fix button height and an a11y label violation
  code/core/src/manager/components/mobile/about/MobileAbout.tsx
Labels: cleanup, ci:normal, a11y: aria

#32172 Core: Prevent `BAIL` state from showing in interactions panel when switching stories
  code/core/src/component-testing/components/Panel.tsx
  code/core/src/controls/components/SaveStory.stories.tsx
  code/core/src/preview-api/modules/preview-web/render/StoryRender.ts
Labels: bug, Stale, ci:normal

#32324 AddonViewport: Stricter types
  code/addons/vitest/src/vitest-plugin/viewports.ts
  code/core/src/viewport/components/Tool.tsx
  code/core/src/viewport/defaults.ts
  docs/essentials/viewport.mdx
Labels: feature request, addon: viewport, core, typescript, ci:normal

#32348 UI: Allow showing or hiding the addon panel
  code/core/src/manager-api/modules/layout.ts
  code/core/src/manager/components/layout/Layout.tsx
  code/core/src/types/modules/addons.ts
  code/core/src/types/modules/api.ts
  docs/_snippets/storybook-manager-addon-panel-hide-on-showcase.md
  docs/configure/user-interface/features-and-behavior.mdx
Labels: feature request, needs triage, ci:normal

#32549 Build: Fix failing react sandboxes
  code/lib/cli-storybook/src/sandbox-templates.ts
Labels: build, ci:daily

#32512 Controls: Fix adding new values to arrays
  code/addons/docs/src/blocks/controls/react-editable-json-tree/JsonNodes.tsx
Labels: bug, addon: docs, block: other, addon: controls, ci:normal

#32477 Core: Use `exsolve` `resolveModulePath` for `safeResolveModule`
  MIGRATION.md
  code/core/src/shared/utils/module.ts
  code/core/src/telemetry/package-json.ts
  code/frameworks/angular/preset.js
  code/frameworks/angular/src/preset.ts
  code/lib/cli-storybook/src/automigrate/fixes/__test__/main-config-with-wrappers.js
  code/lib/cli-storybook/src/automigrate/fixes/wrap-getAbsolutePath-utils.ts
  code/lib/cli-storybook/src/automigrate/fixes/wrap-getAbsolutePath.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/wrap-getAbsolutePath.ts
  code/lib/create-storybook/src/generators/baseGenerator.ts
  docs/_snippets/storybook-main-pnpm-with-module-resolution.md
  test-storybooks/yarn-pnp/.storybook/main.ts
Labels: maintenance, core, ci:normal

#32554 UI: Fix floating menu button background color
  code/core/src/manager/components/sidebar/ContextMenu.tsx
Labels: bug, ui, ci:normal

#32173 Svelte: Ignore inherited `HTMLAttributes` when using utility types on `svelte/elements` in docgen
  code/frameworks/svelte-vite/src/plugins/generateDocgen.ts
Labels: bug, patch:yes, svelte, ci:normal, docgen

#32558 AutoMigration: Fix sb10 migration when main config contains `require`
  code/core/src/common/utils/load-main-config.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-a11y-addon-test.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/fix-faux-esm-require.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/fix-faux-esm-require.ts
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/cli-storybook/src/automigrate/helpers/mainConfigFile.ts
Labels: bug, automigrations, ci:normal

#32507 Cleanup: Remove duplicated entrypoints in core
  code/addons/docs/src/blocks/components/TableOfContents.stories.tsx
  code/addons/pseudo-states/src/manager/PseudoStateTool.tsx
  code/addons/pseudo-states/src/stories/CSSAtRules.stories.tsx
  code/addons/vitest/src/components/SidebarContextMenu.tsx
  code/builders/builder-vite/src/constants.ts
  code/core/build-config.ts
  code/core/package.json
  code/core/src/components/components/Button/Button.stories.tsx
  code/core/src/components/components/Form/Checkbox.tsx
  code/core/src/components/components/Form/Radio.tsx
  code/core/src/highlight/useHighlights.stories.tsx
  code/core/src/manager/components/layout/Layout.stories.tsx
  code/core/src/manager/globals/globals-module-info.ts
  code/core/src/preview/globals/globals.ts
  code/core/src/preview/globals/runtime.ts
  code/lib/cli-storybook/src/automigrate/fixes/consolidated-imports.ts
  code/renderers/react/template/stories/decorators.stories.tsx
Labels: maintenance, core, automigrations, ci:normal

#32572 React Native: Fix document reference error in open-in-editor
  code/core/src/manager-api/modules/open-in-editor.tsx
Labels: bug, ui, react, ci:normal

#32577 Build: Fix layout stories
  code/core/src/manager/components/layout/Layout.stories.tsx
  code/core/src/manager/components/mobile/navigation/MobileNavigation.stories.tsx
Labels: build, ci:normal

#32579 Core: Fix `external-globals-plugin` handle `undefined` cache dir
  code/builders/builder-vite/src/plugins/external-globals-plugin.ts
Labels: bug, core, ci:normal

#32580 Angular: Enable experimental zoneless detection on Angular v21
  code/frameworks/angular/build-schema.json
  code/frameworks/angular/src/builders/build-storybook/index.ts
  code/frameworks/angular/src/builders/start-storybook/index.ts
  code/frameworks/angular/src/server/framework-preset-angular-cli.ts
  code/frameworks/angular/start-schema.json
  docs/get-started/frameworks/angular.mdx
Labels: bug, angular, patch:yes, ci:daily
