Repository storybookjs/storybook, pull requests merged in 2025-03, with the labels that each got.

#30731 Build: Pin typescript to avoid version conflicts with eslint-typescript
  scripts/utils/yarn.ts
Labels: patch:yes, typescript, build, ci:normal

#30606 Manager: Add Content-Type to prevent reliance on content type sniffing, fixing Cloud IDEs
  code/core/src/builder-manager/index.ts
Labels: bug, patch:yes, builder-manager, ci:normal

#30727 Test Addon: Stabilize and remove experimental status
  MIGRATION.md
  code/.storybook/main.ts
  code/.storybook/preview.tsx
  code/.storybook/vitest.config.ts
  code/addons/test/README.md
  code/addons/test/package.json
  code/addons/test/project.json
  code/addons/test/src/index.ts
  code/addons/test/src/node/vitest-manager.ts
  code/addons/test/src/postinstall.ts
  code/addons/test/src/preset.ts
  code/addons/test/src/updateVitestFile.test.ts
  code/addons/test/src/updateVitestFile.ts
  code/addons/test/src/vitest-plugin/index.ts
  code/addons/test/templates/vitest.config.template.ts
  code/addons/test/templates/vitest.workspace.template.ts
  code/builders/builder-vite/src/optimizeDeps.ts
  code/core/src/common/versions.ts
  code/core/src/csf-tools/vitest-plugin/transformer.test.ts
  code/core/src/csf-tools/vitest-plugin/transformer.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-a11y-addon-test.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-a11y-addon-test.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-experimental-test.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-experimental-test.ts
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/create-storybook/src/initiate.ts
  code/package.json
  code/yarn.lock
  docs/_snippets/addon-test-install.md
  docs/_snippets/vitest-plugin-vitest-config.md
  docs/_snippets/vitest-plugin-vitest-workspace.md
  docs/writing-tests/accessibility-testing.mdx
  docs/writing-tests/test-addon.mdx
  scripts/create-nx-sandbox-projects.ts
  scripts/tasks/sandbox-parts.ts
  scripts/tasks/sandbox.ts
  test-storybooks/portable-stories-kitchen-sink/react/.storybook/main.ts
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/react/vitest.workspace.ts
  test-storybooks/portable-stories-kitchen-sink/react/yarn.lock
Labels: BREAKING CHANGE, ci:normal, addon: test

#30719 Build: Use `storybook` from `node_modules` to run internal Storybook
  code/core/src/shared/universal-store/index.ts
  code/package.json
Labels: build, ci:normal

#30071 CLI: Add index command / API
  code/core/src/bin/index.ts
  code/core/src/cli/bin/index.ts
  code/core/src/cli/buildIndex.ts
  code/core/src/core-server/build-index.test.ts
  code/core/src/core-server/build-index.ts
  code/core/src/core-server/build-static.ts
  code/core/src/core-server/index.ts
  code/core/src/core-server/standalone.ts
  code/core/src/core-server/utils/__mockdata__/main.js
  code/core/src/telemetry/types.ts
  code/core/src/types/modules/core-common.ts
  docs/api/cli-options.mdx
Labels: feature request, api: addons, cli, ci:normal

#30711 Vite: Include `node_modules` in stats file
  code/builders/builder-vite/src/plugins/webpack-stats-plugin.ts
Labels: feature request, builder-vite, ci:normal

#30655 Docs: Add missing PRs to 8.6.0-beta.0 changelog entry
  CHANGELOG.md
  CHANGELOG.prerelease.md
Labels: documentation, ci:docs

#30659 Next.js: Use latest version when init in empty directory
  code/lib/create-storybook/src/scaffold-new-project.ts
Labels: bug, cli, nextjs, ci:daily

#26838 Svelte: Fix Vite crashing on virtual module imports
  code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts
Labels: bug, patch:yes, svelte, builder-vite, ci:normal

#30723 Addon A11y: Promote @storybook/global to full dependency
  code/addons/a11y/package.json
Labels: bug, addon: a11y, patch:yes, ci:normal

#30775 Build: Disable benchmark scripts
  .circleci/config.yml
Labels: build, ci:normal

#30766 Migration: Document dropped support legacy packages
  MIGRATION.md
Labels: documentation, ci:normal

#30769 Automigrate: Disable `missingStorybookDependencies` for 9.0
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/cli-storybook/src/automigrate/fixes/missing-storybook-dependencies.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/missing-storybook-dependencies.ts
Labels: feature request, automigrations, ci:normal

#30781 Universal Store: Don't use `crypto.randomUUID`
  code/core/src/shared/universal-store/index.test.ts
  code/core/src/shared/universal-store/index.ts
Labels: bug, patch:yes, core, ci:normal, addon: test

#30783 Svelte: Pin svelte2tsx to solve argType regression
  code/frameworks/svelte-vite/package.json
  code/yarn.lock
Labels: bug, ci:merged

#30755 Addon Test: Improve unhandled error messages
  code/.storybook/vitest.config.ts
  code/addons/test/package.json
  code/addons/test/src/index.ts
  code/addons/test/src/node/reporter.ts
  code/package.json
  code/yarn.lock
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/react/stories/UnhandledErrors.stories.tsx
  test-storybooks/portable-stories-kitchen-sink/react/vitest.workspace.ts
Labels: feature request, ci:normal, addon: test

#30786 CLI: Fix test install in RNW projects
  code/lib/create-storybook/src/generators/baseGenerator.ts
Labels: bug, cli, patch:yes, ci:normal, react-native-web

#30784 Svelte: Fix automatic argTypes inference coming up empty with `svelte2tsx@0.7.35`
  code/frameworks/svelte-vite/package.json
  code/frameworks/svelte-vite/src/plugins/generateDocgen.ts
  code/yarn.lock
Labels: bug, patch:yes, svelte, ci:merged

#30790 Angular: Add @angular-devkit/build-angular to default installed pacakages in angular
  code/core/src/common/js-package-manager/JsPackageManager.test.ts
  code/core/src/common/js-package-manager/JsPackageManager.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
  code/lib/create-storybook/src/generators/ANGULAR/index.ts
Labels: bug, patch:yes, ci:daily

#30792 Vite: Add new dependencies to Vite optimizeDeps to fix #30789
  code/builders/builder-vite/src/optimizeDeps.ts
Labels: bug, ci:merged

#30785 Automigrate: Prefer framework import
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/cli-storybook/src/automigrate/fixes/renderer-to-framework.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/renderer-to-framework.ts
Labels: feature request, automigrations, ci:normal

#30799 CLI: Do not install renderer package on `init`
  code/lib/create-storybook/src/generators/baseGenerator.ts
Labels: maintenance, cli, ci:normal

#30757 React: Remove react import in template files
  code/.eslintrc.js
  code/frameworks/experimental-nextjs-vite/template/cli/js/Button.jsx
  code/frameworks/experimental-nextjs-vite/template/cli/js/Header.jsx
  code/frameworks/experimental-nextjs-vite/template/cli/ts-4-9/Button.tsx
  code/frameworks/experimental-nextjs-vite/template/cli/ts-4-9/Header.tsx
  code/frameworks/nextjs/template/cli/js/Button.jsx
  code/frameworks/nextjs/template/cli/js/Header.jsx
  code/frameworks/nextjs/template/cli/ts-4-9/Button.tsx
  code/frameworks/nextjs/template/cli/ts-4-9/Header.tsx
  code/renderers/react/template/cli/js/Button.jsx
  code/renderers/react/template/cli/js/Header.jsx
  code/renderers/react/template/cli/ts-4-9/Button.tsx
  code/renderers/react/template/cli/ts-4-9/Header.tsx
  code/tsconfig.json
Labels: feature request, ci:merged

#30811 Angular: Make sure that polyfills are loaded before the storybook is loaded
  code/frameworks/angular/src/server/angular-cli-webpack.js
Labels: bug, patch:yes, ci:daily

#30729 CSF: Fix CSF subcomponent type
  code/core/src/csf/story.ts
Labels: bug, patch:yes, typescript, ci:normal

#30682 Ember: Fix `ember-template-compiler` import for ember 6+
  code/frameworks/ember/src/server/framework-preset-babel-ember.ts
  code/frameworks/ember/src/typings.d.ts
Labels: bug, ember, ci:normal

#30819 React-Native: Update config directory to .rnstorybook
  code/lib/create-storybook/src/generators/REACT_NATIVE/index.ts
  code/lib/create-storybook/src/initiate.ts
Labels: maintenance, BREAKING CHANGE, ci:normal

#30821 React-Native-Web: Fix errors in CLI template stories
  code/frameworks/react-native-web-vite/template/cli/js/Header.jsx
  code/frameworks/react-native-web-vite/template/cli/js/Page.jsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Header.tsx
  code/frameworks/react-native-web-vite/template/cli/ts-4-9/Page.tsx
Labels: bug, cli, patch:yes, ci:normal, react-native-web

#30820 React-Native: Fix `__STORYBOOK_ADDON_INTERACTIONS_INSTRUMENTER_STATE__` access
  code/core/src/instrumenter/instrumenter.ts
Labels: bug, react-native, ci:normal

#30805 Core: Remove `util`, `browser-assert`, `process` deps
  MIGRATION.md
  code/core/package.json
  code/core/src/builder-manager/index.ts
  code/package.json
  code/yarn.lock
Labels: dependencies, core, ci:normal

#30773 Core: Testing Module UI improvements
  code/addons/a11y/package.json
  code/addons/backgrounds/package.json
  code/addons/controls/package.json
  code/addons/interactions/package.json
  code/addons/jest/package.json
  code/addons/measure/package.json
  code/addons/onboarding/package.json
  code/addons/outline/package.json
  code/addons/test/package.json
  code/addons/test/src/components/TestProviderRender.stories.tsx
  code/addons/test/src/components/TestProviderRender.tsx
  code/addons/themes/package.json
  code/addons/viewport/package.json
  code/core/package.json
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/components/components/tooltip/WithTooltip.tsx
  code/core/src/manager/components/sidebar/LegacyRender.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/core/src/manager/globals/exports.ts
  code/lib/blocks/package.json
  code/yarn.lock
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
Labels: feature request, ci:normal

#30831 React-Native: Fix `userEvent.setup()` errors outside browser context
  code/core/src/test/preview.ts
Labels: bug, ci:normal

#30833 React-Native: Fix `userEvent.setup()` errors in jest
  code/core/src/test/preview.ts
Labels: bug, ci:normal

#30838 Core: Add "clear all statuses"-button
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  test-storybooks/portable-stories-kitchen-sink/react/.storybook/manager.ts
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
  test-storybooks/portable-stories-kitchen-sink/react/yarn.lock
Labels: feature request, ui, core, ci:normal

#30830 UI: Fix status missing from sidebar
  code/core/src/manager/components/sidebar/Sidebar.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.stories.tsx
  code/core/src/manager/components/sidebar/SidebarBottom.tsx
  code/core/src/manager/components/sidebar/TestingModule.stories.tsx
  code/core/src/manager/components/sidebar/TestingModule.tsx
  code/core/src/manager/components/sidebar/Tree.tsx
  test-storybooks/portable-stories-kitchen-sink/react/.storybook/manager.ts
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
  test-storybooks/portable-stories-kitchen-sink/react/yarn.lock
Labels: bug, ui, ci:normal

#30828 Core: New Test Provider Store
  code/core/src/core-server/index.ts
  code/core/src/core-server/stores/test-provider.ts
  code/core/src/manager-api/root.tsx
  code/core/src/manager-api/stores/__mocks__/test-provider.ts
  code/core/src/manager-api/stores/test-provider.ts
  code/core/src/manager/globals/exports.ts
  code/core/src/shared/test-provider-store/index.test-d.ts
  code/core/src/shared/test-provider-store/index.test.ts
  code/core/src/shared/test-provider-store/index.ts
  code/core/src/types/index.ts
  code/core/src/types/modules/test-provider.ts
Labels: maintenance, core, ci:normal

#30840 Test: Upgrade to vitest 3
  code/.yarn/patches/@vitest-expect-npm-3.0.9-e2a2210fb4.patch
  code/addons/test/package.json
  code/core/package.json
  code/package.json
  code/yarn.lock
Labels: maintenance, ci:normal

#30843 Build: Fix nuxi sandbox
  code/lib/cli-storybook/src/sandbox-templates.ts
Labels: patch:yes, build, ci:normal

#30812 Svelte: Adjust Svelte typings to include Svelte 5 function components
  code/renderers/svelte/src/__test__/ButtonV5.svelte
  code/renderers/svelte/src/public-types.test.ts
  code/renderers/svelte/src/public-types.ts
  code/renderers/svelte/src/types.ts
Labels: bug, patch:yes, ci:normal

#30845 Vite: Update HMR filter to target specific story file types
  code/builders/builder-vite/src/plugins/strip-story-hmr-boundaries.ts
Labels: bug, ci:normal

#30849 Angular: Export all files in Angular package.json
  code/frameworks/angular/package.json
  code/frameworks/ember/package.json
Labels: bug, patch:yes, ci:merged

#30847 React: Allow portable stories to be used in SSR
  code/renderers/react/src/act-compat.ts
  code/renderers/react/src/entry-preview.tsx
  code/renderers/react/src/renderToCanvas.tsx
Labels: bug, patch:yes, ci:normal

#30852 Svelte: Adjust Svelte typings to include Svelte 5 function components
  code/renderers/svelte/src/__test__/ButtonV5.svelte
  code/renderers/svelte/src/public-types.test.ts
  code/renderers/svelte/src/public-types.ts
  code/renderers/svelte/src/types.ts
Labels: bug, patch:yes, ci:normal

#30855 CLI: Don't add packageManager entry to package.json automatically
  code/core/package.json
  code/core/src/telemetry/storybook-metadata.test.ts
  code/core/src/telemetry/storybook-metadata.ts
  code/core/src/telemetry/types.ts
  code/yarn.lock
Labels: bug, patch:yes, ci:normal

#30857 Telemetry: Make sure that telemetry doesn't fail on init
  code/core/src/telemetry/storybook-metadata.ts
Labels: maintenance, patch:yes, ci:normal

#30876 Test: Handle non-configurable properties in instrumenter for expect.toThrow
  code/addons/test/template/stories/basics.stories.ts
  code/core/src/instrumenter/instrumenter.ts
Labels: bug, ci:normal

#30865 CLI: Make sure that the add commands logs all output to the console
  code/core/src/common/js-package-manager/BUNProxy.ts
  code/core/src/common/js-package-manager/JsPackageManager.ts
  code/core/src/common/js-package-manager/NPMProxy.ts
  code/core/src/common/js-package-manager/PNPMProxy.ts
  code/core/src/common/js-package-manager/Yarn1Proxy.ts
  code/core/src/common/js-package-manager/Yarn2Proxy.ts
  code/lib/cli-storybook/src/add.test.ts
  code/lib/cli-storybook/src/add.ts
Labels: bug, ci:normal

#30903 Build: Add spy mocking rules for Vitest tests
  .cursor/rules/spy-mocking.mdc
Labels: other, ci:docs

#30841 Addons: Update the Viewport and Background Addon
  MIGRATION.md
  code/.storybook/main.ts
  code/addons/backgrounds/src/components/Tool.tsx
  code/addons/backgrounds/src/decorator.ts
  code/addons/backgrounds/src/legacy/BackgroundSelectorLegacy.tsx
  code/addons/backgrounds/src/legacy/ColorIcon.tsx
  code/addons/backgrounds/src/legacy/GridSelectorLegacy.tsx
  code/addons/backgrounds/src/legacy/getBackgroundColorByName.ts
  code/addons/backgrounds/src/legacy/withBackgroundLegacy.ts
  code/addons/backgrounds/src/legacy/withGridLegacy.ts
  code/addons/backgrounds/src/manager.tsx
  code/addons/backgrounds/src/preview.ts
  code/addons/backgrounds/src/types.ts
  code/addons/backgrounds/template/stories/globals.stories.ts
  code/addons/backgrounds/template/stories/parameters.stories.ts
  code/addons/viewport/src/components/Tool.tsx
  code/addons/viewport/src/legacy/ToolLegacy.tsx
  code/addons/viewport/src/legacy/ViewportAddonParameter.ts
  code/addons/viewport/src/manager.tsx
  code/addons/viewport/src/preview.ts
  code/addons/viewport/src/types.ts
  code/addons/viewport/template/stories/globals.stories.ts
  code/addons/viewport/template/stories/parameters.stories.ts
  code/core/src/types/modules/core-common.ts
  code/e2e-tests/addon-viewport.spec.ts
  docs/api/main-config/main-config-features.mdx
Labels: BREAKING CHANGE, addon: viewport, addon: backgrounds, ci:daily

#30914 Next: Fix react aliases in next vite plugin
  code/frameworks/experimental-nextjs-vite/package.json
  code/yarn.lock
Labels: bug, patch:yes, ci:merged

#30856 Addon-Essentials: Remove addon-docs
  MIGRATION.md
  code/.storybook/main.ts
  code/addons/docs/src/preset.ts
  code/addons/essentials/README.md
  code/addons/essentials/package.json
  code/addons/essentials/src/docs/manager.ts
  code/addons/essentials/src/docs/mdx-react-shim.ts
  code/addons/essentials/src/docs/preset.ts
  code/addons/essentials/src/docs/preview.ts
  code/addons/essentials/src/preset.ts
  code/addons/essentials/src/preview.ts
  code/addons/essentials/src/types.ts
  code/builders/builder-vite/src/optimizeDeps.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-essentials-remove-docs.test.ts
  code/lib/cli-storybook/src/automigrate/fixes/addon-essentials-remove-docs.ts
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
  code/lib/create-storybook/src/generators/baseGenerator.ts
  code/yarn.lock
  scripts/tasks/sandbox-parts.ts
Labels: maintenance, addon: docs, addon: essentials, ci:normal

#30871 Toolbars: Embed addon-toolbars into the core
  code/.storybook/main.ts
  code/.storybook/preview.tsx
  code/addons/essentials/README.md
  code/addons/essentials/package.json
  code/addons/essentials/src/preset.ts
  code/addons/essentials/src/toolbars/manager.ts
  code/addons/toolbars/README.md
  code/addons/toolbars/manager.js
  code/addons/toolbars/package.json
  code/addons/toolbars/project.json
  code/addons/toolbars/src/constants.ts
  code/addons/toolbars/src/index.ts
  code/addons/toolbars/src/typings.d.ts
  code/addons/toolbars/template/stories/preview.ts
  code/addons/toolbars/tsconfig.json
  code/addons/toolbars/vitest.config.ts
  code/core/assets/docs/hero.gif
  code/core/src/common/utils/__tests__/check-addon-order.test.ts
  code/core/src/common/versions.ts
  code/core/src/components/components/tooltip/ListItem.tsx
  code/core/src/manager/runtime.tsx
  code/core/src/toolbar/components/ToolbarManager.tsx
  code/core/src/toolbar/components/ToolbarMenuButton.tsx
  code/core/src/toolbar/components/ToolbarMenuList.tsx
  code/core/src/toolbar/components/ToolbarMenuListItem.tsx
  code/core/src/toolbar/constants.ts
  code/core/src/toolbar/hoc/withKeyboardCycle.tsx
  code/core/src/toolbar/index.ts
  code/core/src/toolbar/manager.tsx
  code/core/src/toolbar/preview.ts
  code/core/src/toolbar/types.ts
  code/core/src/toolbar/utils/create-cycle-value-array.ts
  code/core/src/toolbar/utils/get-selected.ts
  code/core/src/toolbar/utils/normalize-toolbar-arg-type.ts
  code/core/src/toolbar/utils/register-shortcuts.ts
  code/core/template/stories/preview.ts
  code/core/template/stories/toolbars/globals.stories.ts
  code/e2e-tests/addon-toolbars.spec.ts
  code/lib/cli-storybook/src/automigrate/helpers/consolidated-packages.ts
  code/package.json
  code/yarn.lock
  scripts/prepare/tools.ts
  scripts/tasks/sandbox-parts.ts
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/react/yarn.lock
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/vue3/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: maintenance, core, addon: toolbars, ci:normal

#30909 Viewport: Embed addon-viewport in the core
  MIGRATION.md
  code/.storybook/main.ts
  code/addons/essentials/README.md
  code/addons/essentials/package.json
  code/addons/essentials/src/preset.ts
  code/addons/essentials/src/preview.ts
  code/addons/essentials/src/types.ts
  code/addons/essentials/src/viewport/manager.ts
  code/addons/essentials/src/viewport/preview.ts
  code/addons/test/src/vitest-plugin/viewports.test.ts
  code/addons/test/src/vitest-plugin/viewports.ts
  code/addons/viewport/manager.js
  code/addons/viewport/package.json
  code/addons/viewport/preview.js
  code/addons/viewport/project.json
  code/addons/viewport/src/constants.ts
  code/addons/viewport/src/index.ts
  code/addons/viewport/src/preview.ts
  code/addons/viewport/src/typings.d.ts
  code/addons/viewport/tsconfig.json
  code/addons/viewport/vitest.config.ts
  code/builders/builder-vite/src/optimizeDeps.ts
  code/core/assets/docs/viewport.png
  code/core/package.json
  code/core/scripts/dts.ts
  code/core/scripts/entries.ts
  code/core/scripts/prep.ts
  code/core/src/common/versions.ts
  code/core/src/core-server/presets/common-preset.ts
  code/core/src/preview-api/core-annotations.ts
  code/core/src/shared/preview/csf4.ts
  code/core/src/viewport/README.md
  code/core/src/viewport/components/Tool.tsx
  code/core/src/viewport/constants.ts
  code/core/src/viewport/defaults.ts
  code/core/src/viewport/index.ts
  code/core/src/viewport/manager.tsx
  code/core/src/viewport/preview.ts
  code/core/src/viewport/responsiveViewport.tsx
  code/core/src/viewport/shortcuts.ts
  code/core/src/viewport/types.ts
  code/core/src/viewport/utils.tsx
  code/core/template/stories/preview.ts
  code/core/template/stories/viewport/globals.stories.ts
  code/e2e-tests/addon-viewport.spec.ts
  code/lib/cli-storybook/src/automigrate/helpers/consolidated-packages.ts
  code/package.json
  code/yarn.lock
  test-storybooks/ember-cli/.storybook/main.js
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/vue3/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: maintenance, addon: viewport, core, ci:normal

#30923 Core: Prebundle jsdoc-type-pratt-parser again
  code/builders/builder-vite/src/optimizeDeps.ts
  code/core/package.json
  code/core/scripts/prep.ts
Labels: bug, core, ci:normal

#30869 React: Ensure render functions and decorators are react components
  MIGRATION.md
  code/core/src/csf/story.ts
  code/core/src/preview-api/modules/store/csf/normalizeStory.ts
  code/core/src/preview-api/modules/store/csf/prepareStory.ts
  code/core/src/types/modules/story.ts
  code/renderers/react/src/applyDecorators.ts
  code/renderers/react/src/docs/applyDecorators.ts
  code/renderers/react/src/docs/jsxDecorator.test.tsx
  code/renderers/react/src/docs/jsxDecorator.tsx
  code/renderers/react/src/entry-preview.tsx
  code/renderers/react/template/stories/decorators.stories.tsx
Labels: bug, ci:normal

#30934 Automigrate: Remove addonEssentialsRemoveDocs automigration temporarily
  code/lib/cli-storybook/src/automigrate/fixes/index.ts
Labels: build, ci:normal

#30939 Build: Fix docs usage in Storybook UI
  code/.storybook/preview.tsx
Labels: build, ci:normal

#30774 Addon-A11y: Various improvements
  code/.storybook/main.ts
  code/addons/a11y/package.json
  code/addons/a11y/src/components/A11YPanel.stories.tsx
  code/addons/a11y/src/components/A11YPanel.test.tsx
  code/addons/a11y/src/components/A11YPanel.tsx
  code/addons/a11y/src/components/A11yContext.test.tsx
  code/addons/a11y/src/components/A11yContext.tsx
  code/addons/a11y/src/components/Report/Details.tsx
  code/addons/a11y/src/components/Report/Elements.tsx
  code/addons/a11y/src/components/Report/HighlightToggle.test.tsx
  code/addons/a11y/src/components/Report/HighlightToggle.tsx
  code/addons/a11y/src/components/Report/Info.tsx
  code/addons/a11y/src/components/Report/Item.tsx
  code/addons/a11y/src/components/Report/Report.stories.tsx
  code/addons/a11y/src/components/Report/Report.tsx
  code/addons/a11y/src/components/Report/Rules.tsx
  code/addons/a11y/src/components/Report/Tags.tsx
  code/addons/a11y/src/components/Report/index.tsx
  code/addons/a11y/src/components/Tabs.tsx
  code/addons/a11y/src/components/TestDiscrepancyMessage.stories.tsx
  code/addons/a11y/src/constants.ts
  code/addons/a11y/src/results.mock.ts
  code/addons/a11y/src/types.ts
  code/addons/a11y/template/stories/tests.stories.ts
  code/addons/highlight/src/constants.ts
  code/addons/highlight/src/index.ts
  code/addons/highlight/src/preview.ts
  code/addons/test/src/node/reporter.ts
  code/chromatic.config.json
  code/core/src/component-testing/components/Subnav.tsx
  code/core/src/components/components/Badge/Badge.tsx
  code/e2e-tests/addon-a11y.spec.ts
  code/playwright.config.ts
  code/sandbox/qwik-vite-default-ts/project.json
  code/sandbox/solid-vite-default-js/project.json
  code/sandbox/solid-vite-default-ts/project.json
  code/yarn.lock
  scripts/tasks/sandbox.ts
Labels: feature request, ci:normal

#30941 Angular: Fix zone.js support for Angular libraries
  code/frameworks/angular/src/server/angular-cli-webpack.js
Labels: bug, angular, patch:yes, ci:normal

#30955 UI: Visual tweaks to badges and improved layout for a11y panel
  code/addons/a11y/src/components/A11YPanel.tsx
  code/addons/a11y/src/components/Report/Details.tsx
  code/addons/a11y/src/components/Report/Report.tsx
  code/addons/a11y/src/manager.test.tsx
  code/addons/a11y/src/manager.tsx
  code/core/src/actions/manager.tsx
  code/core/src/component-testing/components/PanelTitle.tsx
  code/core/src/components/components/Badge/Badge.stories.tsx
  code/core/src/components/components/Badge/Badge.tsx
  code/core/src/components/components/bar/bar.tsx
  code/core/src/controls/manager.tsx
Labels: feature request, ui, ci:normal

#30963 Core: Fix flaky unit tests related to stores
  code/addons/test/src/node/boot-test-runner.test.ts
  code/addons/test/src/node/boot-test-runner.ts
  code/core/src/core-server/stores/status.ts
  code/core/src/core-server/stores/test-provider.ts
Labels: bug, core, ci:normal

#30970 Manager: Fix `Uncaught ReferenceError: global is not defined`
  code/core/src/manager/globals-runtime.ts
Labels: bug, ui, ci:normal

#30957 Preact: Remove support for Preact Webpack 5
  MIGRATION.md
  code/core/src/cli/helpers.ts
  code/core/src/common/utils/framework-to-renderer.ts
  code/core/src/common/utils/get-storybook-info.ts
  code/core/src/common/versions.ts
  code/core/src/types/modules/frameworks.ts
  code/frameworks/preact-webpack5/README.md
  code/frameworks/preact-webpack5/package.json
  code/frameworks/preact-webpack5/preset.js
  code/frameworks/preact-webpack5/project.json
  code/frameworks/preact-webpack5/src/index.ts
  code/frameworks/preact-webpack5/src/node/index.ts
  code/frameworks/preact-webpack5/src/preset.ts
  code/frameworks/preact-webpack5/src/types.ts
  code/frameworks/preact-webpack5/tsconfig.json
  code/frameworks/preact-webpack5/vitest.config.ts
  code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts
  code/lib/cli-storybook/src/automigrate/helpers/new-frameworks-utils.ts
  code/lib/create-storybook/src/bin/modernInputs.ts
  code/package.json
  code/presets/preact-webpack/README.md
  code/presets/preact-webpack/package.json
  code/presets/preact-webpack/preset.js
  code/presets/preact-webpack/project.json
  code/presets/preact-webpack/src/index.ts
  code/presets/preact-webpack/src/types.ts
  code/presets/preact-webpack/tsconfig.json
  code/yarn.lock
  docs/get-started/install.mdx
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/vue3/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: BREAKING CHANGE, preact, ci:normal

#30958 Vue3: Remove support for Webpack 5
  .circleci/config.yml
  CODEOWNERS
  MIGRATION.md
  code/core/src/cli/helpers.ts
  code/core/src/common/utils/framework-to-renderer.ts
  code/core/src/common/utils/get-storybook-info.ts
  code/core/src/common/versions.ts
  code/core/src/types/modules/frameworks.ts
  code/frameworks/vue3-webpack5/README.md
  code/frameworks/vue3-webpack5/package.json
  code/frameworks/vue3-webpack5/preset.js
  code/frameworks/vue3-webpack5/project.json
  code/frameworks/vue3-webpack5/src/index.ts
  code/frameworks/vue3-webpack5/src/node/index.ts
  code/frameworks/vue3-webpack5/src/preset.ts
  code/frameworks/vue3-webpack5/src/types.ts
  code/frameworks/vue3-webpack5/src/typings.d.ts
  code/frameworks/vue3-webpack5/template/cli/js/Button.stories.js
  code/frameworks/vue3-webpack5/template/cli/js/Button.vue
  code/frameworks/vue3-webpack5/template/cli/js/Header.stories.js
  code/frameworks/vue3-webpack5/template/cli/js/Header.vue
  code/frameworks/vue3-webpack5/template/cli/js/Page.stories.js
  code/frameworks/vue3-webpack5/template/cli/js/Page.vue
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Button.stories.ts
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Button.vue
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Header.stories.ts
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Header.vue
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Page.stories.ts
  code/frameworks/vue3-webpack5/template/cli/ts-4-9/Page.vue
  code/frameworks/vue3-webpack5/tsconfig.json
  code/frameworks/vue3-webpack5/vitest.config.ts
  code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts
  code/lib/cli-storybook/src/automigrate/fixes/new-frameworks.test.ts
  code/lib/cli-storybook/src/automigrate/helpers/new-frameworks-utils.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
  code/lib/create-storybook/src/bin/modernInputs.ts
  code/package.json
  code/presets/vue3-webpack/README.md
  code/presets/vue3-webpack/package.json
  code/presets/vue3-webpack/preset.js
  code/presets/vue3-webpack/project.json
  code/presets/vue3-webpack/src/framework-preset-vue3-docs.ts
  code/presets/vue3-webpack/src/framework-preset-vue3.ts
  code/presets/vue3-webpack/src/index.ts
  code/presets/vue3-webpack/src/types.ts
  code/presets/vue3-webpack/src/typings.d.ts
  code/presets/vue3-webpack/tsconfig.json
  code/sandbox/vue-cli-default-js/project.json
  code/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/vue3/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: vue, BREAKING CHANGE, ci:normal

#30966 CLI: Only install Visual Test Addon if test feature is selected
  code/lib/create-storybook/src/generators/baseGenerator.ts
Labels: maintenance, cli, patch:yes, ci:normal, addon: visual test

#30991 Automigration: Update mapping for '@storybook/experimental-nextjs-vite'
  code/lib/cli-storybook/src/automigrate/helpers/consolidated-packages.ts
Labels: bug, ci:normal

#30989 Documentation: Update migration documentation
  MIGRATION.md
  code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts
Labels: documentation, ci:docs

#30993 Automigration: Add new Storybook addons to consolidated packages mapping
  code/lib/cli-storybook/src/automigrate/fixes/consolidated-imports.test.ts
  code/lib/cli-storybook/src/automigrate/helpers/consolidated-packages.ts
Labels: maintenance, ci:normal

#30990 HTML Framework: Remove support for HTML Webpack 5
  .circleci/config.yml
  CODEOWNERS
  MIGRATION.md
  code/core/src/cli/helpers.ts
  code/core/src/common/utils/framework-to-renderer.ts
  code/core/src/common/utils/get-storybook-info.ts
  code/core/src/common/versions.ts
  code/core/src/types/modules/frameworks.ts
  code/frameworks/html-webpack5/README.md
  code/frameworks/html-webpack5/package.json
  code/frameworks/html-webpack5/preset.js
  code/frameworks/html-webpack5/project.json
  code/frameworks/html-webpack5/src/index.ts
  code/frameworks/html-webpack5/src/node/index.ts
  code/frameworks/html-webpack5/src/preset.ts
  code/frameworks/html-webpack5/src/types.ts
  code/frameworks/html-webpack5/src/typings.d.ts
  code/frameworks/html-webpack5/tsconfig.json
  code/frameworks/html-webpack5/vitest.config.ts
  code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
  code/lib/create-storybook/src/bin/modernInputs.ts
  code/package.json
  code/presets/html-webpack/README.md
  code/presets/html-webpack/package.json
  code/presets/html-webpack/preset.js
  code/presets/html-webpack/project.json
  code/presets/html-webpack/src/index.ts
  code/presets/html-webpack/src/types.ts
  code/presets/html-webpack/tsconfig.json
  code/sandbox/html-webpack-default/project.json
  code/yarn.lock
  test-storybooks/ember-cli/package.json
  test-storybooks/external-docs/package.json
  test-storybooks/portable-stories-kitchen-sink/nextjs/package.json
  test-storybooks/portable-stories-kitchen-sink/react/package.json
  test-storybooks/portable-stories-kitchen-sink/svelte/package.json
  test-storybooks/portable-stories-kitchen-sink/vue3/package.json
  test-storybooks/server-kitchen-sink/package.json
  test-storybooks/standalone-preview/package.json
Labels: BREAKING CHANGE, html, ci:merged

#30952 Core: Add error boundary to tabs to prevent addon errors breaking Storybook
  code/core/src/components/components/tabs/tabs.stories.tsx
  code/core/src/components/components/tabs/tabs.tsx
Labels: bug, ci:normal

#30935 Test: Make sure that expect has no different behavior after instrumentation
  code/core/src/instrumenter/instrumenter.test.ts
  code/core/src/instrumenter/instrumenter.ts
  code/core/src/test/index.ts
  code/core/template/stories/expect.stories.tsx
Labels: bug, ci:normal

#30997 Next: Update vite-plugin-storybook-nextjs to 2.0.0--canary.33.17a2310.0
  code/frameworks/nextjs-vite/package.json
  code/yarn.lock
Labels: dependencies, patch:yes, ci:normal
