Repository storybookjs/storybook, pull requests merged in 2025-07, with the labels that each got.

#28672 A11y: Improved toolbar a11y by fixing semantics
  code/core/src/manager/components/preview/Toolbar.tsx
Labels: ui, maintenance, accessibility, ci:normal

#31885 Docs: Use stalebot with PR also
  .github/workflows/stale.yml
Labels: documentation, ci:docs

#31922 CLI: Fix `sb` CLI by explicitly exporting `bin/index.cjs` from `storybook` package
  code/core/package.json
  code/core/scripts/helpers/generatePackageJsonFile.ts
Labels: bug, cli, patch:yes, ci:normal

#31930 Docs: Fix type import in background code snippet
  docs/_snippets/addon-backgrounds-options-in-preview.md
Labels: documentation, patch:yes, ci:docs

#31845 E2E tests: Reevaluate locator with each assertion
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
  test-storybooks/portable-stories-kitchen-sink/react/playwright-e2e.config.ts
Labels: build, ci:normal

#31972 E2E: Skip check for `Starting` text as it may only appear very briefly
  test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/component-testing.spec.ts
Labels: build, ci:normal

#31923 Automigration: Fail with non-zero exit code on migration failure
  code/lib/cli-storybook/src/automigrate/index.test.ts
  code/lib/cli-storybook/src/automigrate/index.ts
Labels: bug, automigrations, ci:normal

#31968 Core: Fix Yarn PnP support
  .circleci/config.yml
  code/core/src/common/js-package-manager/Yarn2Proxy.ts
  code/core/src/common/presets.test.ts
  code/core/src/common/presets.ts
  code/core/src/core-server/build-dev.ts
  code/core/src/core-server/dev-server.ts
  code/core/src/core-server/utils/get-builders.ts
  code/core/src/shared/utils/module.ts
  test-storybooks/yarn-pnp/.gitignore
  test-storybooks/yarn-pnp/.storybook/main.ts
  test-storybooks/yarn-pnp/.storybook/preview.ts
  test-storybooks/yarn-pnp/.storybook/vitest.setup.ts
  test-storybooks/yarn-pnp/.yarnrc.yml
  test-storybooks/yarn-pnp/README.md
  test-storybooks/yarn-pnp/eslint.config.js
  test-storybooks/yarn-pnp/index.html
  test-storybooks/yarn-pnp/package.json
  test-storybooks/yarn-pnp/public/vite.svg
  test-storybooks/yarn-pnp/src/App.css
  test-storybooks/yarn-pnp/src/App.tsx
  test-storybooks/yarn-pnp/src/assets/react.svg
  test-storybooks/yarn-pnp/src/index.css
  test-storybooks/yarn-pnp/src/main.tsx
  test-storybooks/yarn-pnp/src/stories/Button.stories.ts
  test-storybooks/yarn-pnp/src/stories/Button.tsx
  test-storybooks/yarn-pnp/src/stories/Configure.mdx
  test-storybooks/yarn-pnp/src/stories/Header.stories.ts
  test-storybooks/yarn-pnp/src/stories/Header.tsx
  test-storybooks/yarn-pnp/src/stories/Page.stories.ts
  test-storybooks/yarn-pnp/src/stories/Page.tsx
  test-storybooks/yarn-pnp/src/stories/assets/accessibility.png
  test-storybooks/yarn-pnp/src/stories/assets/accessibility.svg
  test-storybooks/yarn-pnp/src/stories/assets/addon-library.png
  test-storybooks/yarn-pnp/src/stories/assets/assets.png
  test-storybooks/yarn-pnp/src/stories/assets/avif-test-image.avif
  test-storybooks/yarn-pnp/src/stories/assets/context.png
  test-storybooks/yarn-pnp/src/stories/assets/discord.svg
  test-storybooks/yarn-pnp/src/stories/assets/docs.png
  test-storybooks/yarn-pnp/src/stories/assets/figma-plugin.png
  test-storybooks/yarn-pnp/src/stories/assets/github.svg
  test-storybooks/yarn-pnp/src/stories/assets/share.png
  test-storybooks/yarn-pnp/src/stories/assets/styling.png
  test-storybooks/yarn-pnp/src/stories/assets/testing.png
  test-storybooks/yarn-pnp/src/stories/assets/theming.png
  test-storybooks/yarn-pnp/src/stories/assets/tutorials.svg
  test-storybooks/yarn-pnp/src/stories/assets/youtube.svg
  test-storybooks/yarn-pnp/src/stories/button.css
  test-storybooks/yarn-pnp/src/stories/header.css
  test-storybooks/yarn-pnp/src/stories/page.css
  test-storybooks/yarn-pnp/src/vite-env.d.ts
  test-storybooks/yarn-pnp/tsconfig.app.json
  test-storybooks/yarn-pnp/tsconfig.json
  test-storybooks/yarn-pnp/tsconfig.node.json
  test-storybooks/yarn-pnp/vite.config.ts
  test-storybooks/yarn-pnp/vitest.shims.d.ts
  test-storybooks/yarn-pnp/vitest.workspace.ts
  test-storybooks/yarn-pnp/yarn.lock
Labels: bug, core, ci:normal

#31944 Onboarding: Intent survey
  code/addons/onboarding/src/Onboarding.tsx
  code/addons/onboarding/src/constants.ts
  code/addons/onboarding/src/features/IntentSurvey/IntentSurvey.stories.tsx
  code/addons/onboarding/src/features/IntentSurvey/IntentSurvey.tsx
  code/addons/onboarding/src/preset.ts
  code/addons/pseudo-states/src/manager/PseudoStateTool.tsx
  code/addons/vitest/src/components/TestProviderRender.tsx
  code/core/src/components/components/Checkbox/Checkbox.stories.tsx
  code/core/src/components/components/Form/Checkbox.stories.tsx
  code/core/src/components/components/Form/Checkbox.tsx
  code/core/src/components/components/Form/Field.stories.tsx
  code/core/src/components/components/Form/Field.tsx
  code/core/src/components/components/Form/Form.tsx
  code/core/src/components/components/Form/Input.stories.tsx
  code/core/src/components/components/Form/Input.tsx
  code/core/src/components/components/Form/Radio.stories.tsx
  code/core/src/components/components/Form/Radio.tsx
  code/core/src/components/components/Form/Select.stories.tsx
  code/core/src/components/components/Form/Select.tsx
  code/core/src/components/components/Form/Textarea.stories.tsx
  code/core/src/components/components/Form/Textarea.tsx
  code/core/src/components/components/Form/styles.ts
  code/core/src/components/components/Modal/Modal.styled.tsx
  code/core/src/components/components/form/form.stories.tsx
  code/core/src/components/components/form/input/input.tsx
  code/core/src/components/index.ts
  code/core/src/manager/globals/exports.ts
  code/core/src/telemetry/types.ts
  code/e2e-tests/addon-onboarding.spec.ts
Labels: maintenance, patch:yes, ci:normal, addon: onboarding

#26003 Docs: Contribution guide updates
  CONTRIBUTING.md
Labels: documentation, ci:docs

#31970 ESM: Convert builders to ESM
  .circleci/config.yml
  MIGRATION.md
  code/addons/vitest/src/postinstall.ts
  code/addons/vitest/src/preset.ts
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/index.ts
  code/builders/builder-vite/src/plugins/code-generator-plugin.ts
  code/builders/builder-webpack5/package.json
  code/builders/builder-webpack5/src/index.ts
  code/builders/builder-webpack5/src/presets/custom-webpack-preset.ts
  code/builders/builder-webpack5/src/presets/preview-preset.ts
  code/builders/builder-webpack5/src/preview/base-webpack.config.ts
  code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts
  code/builders/builder-webpack5/src/preview/virtual-module-mapping.ts
  code/core/src/builder-manager/utils/framework.ts
  code/core/src/core-server/build-dev.ts
  code/core/src/core-server/dev-server.ts
  code/core/src/core-server/utils/get-builders.ts
  code/frameworks/angular/src/preset.ts
  code/frameworks/ember/src/preset.ts
  code/frameworks/html-vite/src/preset.ts
  code/frameworks/nextjs-vite/src/preset.ts
  code/frameworks/nextjs/src/preset.ts
  code/frameworks/preact-vite/src/preset.ts
  code/frameworks/react-native-web-vite/src/preset.ts
  code/frameworks/react-vite/src/preset.ts
  code/frameworks/react-webpack5/src/preset.ts
  code/frameworks/server-webpack5/src/preset.ts
  code/frameworks/svelte-vite/src/preset.ts
  code/frameworks/sveltekit/src/preset.ts
  code/frameworks/vue3-vite/src/preset.ts
  code/frameworks/web-components-vite/src/preset.ts
  code/vitest-setup.ts
  code/yarn.lock
  scripts/build/entries/index.ts
  scripts/build/utils/generate-bundle.ts
Labels: maintenance, builder-webpack5, builder-vite, ci:normal, esm

#32019 Build: Update Stalebot to not close stale PRs
  .github/workflows/stale.yml
Labels: build, ci:docs

#32035 Core: Support CJS presets in frameworks
  code/core/src/common/utils/validate-config.ts
Labels: bug, core, ci:normal

#31839 Core: Group hooks in a single folder
  code/core/src/manager/components/layout/LayoutProvider.tsx
  code/core/src/manager/hooks/useMedia.tsx
Labels: cleanup, ci:daily, Stale

#32036 CI: Add resolution to pin Rollup to v4.44.2 in sandboxes
  scripts/utils/yarn.ts
Labels: build, ci:normal

#32042 UI: Fix text color for failing stories in sidebar
  code/core/src/manager/utils/status.tsx
Labels: bug, patch:yes, ci:normal

#31980 Svelte: Fix union types generating invalid labels in argTypes
  code/renderers/svelte/src/extractArgTypes.ts
Labels: bug, patch:yes, argtypes, ci:normal

#32054 ESM: Remove unused bundle scripts
  scripts/prepare/addon-bundle.ts
  scripts/prepare/tsc.ts
Labels: build, ci:normal

#32065 Build: Cleanup configurations and remove old build scripts
  code/addons/a11y/build-config.ts
  code/addons/docs/build-config.ts
  code/addons/docs/package.json
  code/addons/jest/build-config.ts
  code/addons/links/build-config.ts
  code/addons/onboarding/build-config.ts
  code/addons/pseudo-states/build-config.ts
  code/addons/themes/build-config.ts
  code/addons/vitest/build-config.ts
  code/builders/builder-vite/build-config.ts
  code/builders/builder-webpack5/build-config.ts
  code/core/build-config.ts
  code/core/package.json
  code/core/scripts/generate-source-files.ts
  code/core/src/shared/constants/environments-support.ts
  code/frameworks/angular/build-config.ts
  code/frameworks/ember/build-config.ts
  code/frameworks/html-vite/build-config.ts
  code/frameworks/nextjs-vite/build-config.ts
  code/frameworks/nextjs/build-config.ts
  code/frameworks/preact-vite/build-config.ts
  code/frameworks/react-native-web-vite/build-config.ts
  code/frameworks/react-vite/build-config.ts
  code/frameworks/react-webpack5/build-config.ts
  code/frameworks/server-webpack5/build-config.ts
  code/frameworks/svelte-vite/build-config.ts
  code/frameworks/sveltekit/build-config.ts
  code/frameworks/vue3-vite/build-config.ts
  code/frameworks/web-components-vite/build-config.ts
  code/lib/cli-storybook/build-config.ts
  code/lib/codemod/build-config.ts
  code/lib/core-webpack/build-config.ts
  code/lib/create-storybook/build-config.ts
  code/lib/csf-plugin/build-config.ts
  code/lib/csf-plugin/package.json
  code/lib/eslint-plugin/build-config.ts
  code/lib/react-dom-shim/build-config.ts
  code/nx.json
  code/presets/create-react-app/build-config.ts
  code/presets/react-webpack/build-config.ts
  code/presets/server-webpack/build-config.ts
  code/renderers/html/build-config.ts
  code/renderers/preact/build-config.ts
  code/renderers/react/build-config.ts
  code/renderers/server/build-config.ts
  code/renderers/svelte/build-config.ts
  code/renderers/svelte/src/render.ts
  code/renderers/vue3/build-config.ts
  code/renderers/web-components/build-config.ts
  code/yarn.lock
  scripts/build/build-package.ts
  scripts/build/entries/index.ts
  scripts/build/entry-configs.ts
  scripts/package.json
  scripts/prepare/bundle.ts
  scripts/utils/tools.ts
  scripts/yarn.lock
Labels: build, ci:normal

#31987 Test: Add mock capabilities
  code/.storybook/preview.tsx
  code/.storybook/utils/todo.tsx
  code/__mocks__/lodash-es.js
  code/__mocks__/lodash-es/add.js
  code/addons/vitest/src/vitest-plugin/index.ts
  code/builders/builder-vite/src/codegen-modern-iframe-script.ts
  code/builders/builder-vite/src/vite-config.ts
  code/builders/builder-webpack5/src/loaders/export-order-loader.ts
  code/core/package.json
  code/core/scripts/entries.ts
  code/core/src/core-server/mocking-utils/automock.ts
  code/core/src/core-server/mocking-utils/esmWalker.ts
  code/core/src/core-server/mocking-utils/extract.test.ts
  code/core/src/core-server/mocking-utils/extract.ts
  code/core/src/core-server/mocking-utils/resolve.ts
  code/core/src/core-server/presets/common-preset.ts
  code/core/src/core-server/presets/vitePlugins/vite-inject-mocker/constants.ts
  code/core/src/core-server/presets/vitePlugins/vite-inject-mocker/plugin.ts
  code/core/src/core-server/presets/vitePlugins/vite-mock/plugin.ts
  code/core/src/core-server/presets/vitePlugins/vite-mock/utils.ts
  code/core/src/core-server/presets/webpack/loaders/storybook-mock-transform-loader.ts
  code/core/src/core-server/presets/webpack/loaders/webpack-automock-loader.ts
  code/core/src/core-server/presets/webpack/plugins/webpack-inject-mocker-runtime-plugin.ts
  code/core/src/core-server/presets/webpack/plugins/webpack-mock-plugin.ts
  code/core/src/manager/globals/exports.ts
  code/core/src/telemetry/types.ts
  code/core/src/test/index.ts
  code/core/src/typings.d.ts
  code/core/template/__mocks__/lodash-es.js
  code/core/template/__mocks__/lodash-es/add.js
  code/core/template/stories/test/ModuleAutoMocking.stories.ts
  code/core/template/stories/test/ModuleAutoMocking.utils.ts
  code/core/template/stories/test/ModuleMocking.stories.ts
  code/core/template/stories/test/ModuleMocking.utils.ts
  code/core/template/stories/test/ModuleSpyMocking.stories.ts
  code/core/template/stories/test/ModuleSpyMocking.utils.ts
  code/core/template/stories/test/NodeModuleMocking.stories.js
  code/core/template/stories/test/__mocks__/ModuleAutoMocking.utils.ts
  code/core/templates/mocker-runtime.template.js
  code/core/tsconfig.json
  code/e2e-tests/sb-module-mocking.spec.ts
  code/e2e-tests/util.ts
  code/frameworks/angular/template/components/html.component.ts
  code/lib/cli-storybook/src/sandbox.ts
  code/package.json
  code/playwright.config.ts
  code/renderers/react/template/components/Html.jsx
  code/renderers/vue3/template/components/Html.vue
  code/renderers/web-components/template/components/Html.js
  code/vitest-storybook.config.mts
  code/vitest.workspace.ts
  code/yarn.lock
  scripts/event-log-checker.ts
  scripts/tasks/sandbox-parts.ts
  scripts/tasks/sandbox.ts
  scripts/utils/options.test.ts
  scripts/utils/options.ts
  scripts/utils/yarn.ts
Labels: feature request, ci:daily

#32078 docs: remove deprecated vscode extension
  docs/writing-stories/typescript.mdx
Labels: documentation, patch:yes, ci:docs

#32077 CLI: Fix Storybook doctor compatibility checks
  code/lib/cli-storybook/src/doctor/getIncompatibleStorybookPackages.ts
Labels: bug, cli, patch:yes, ci:normal

#32068 Benchmarks: Fix package benchmark reports
  code/.storybook/bench.stories.tsx
  scripts/bench/bench-packages.ts
  scripts/bench/safe-args.ts
  scripts/build/build-package.ts
  scripts/build/utils/generate-bundle.ts
Labels: build, ci:normal

#32051 React Native Web: Simplify config by using vite-plugin-rnw
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-native-web-vite/src/preset.ts
  code/frameworks/react-native-web-vite/src/types.ts
  code/frameworks/react-native-web-vite/src/typings.d.ts
  code/frameworks/react-native-web-vite/src/vite-plugin.ts
  code/yarn.lock
  docs/get-started/frameworks/react-native-web-vite.mdx
Labels: maintenance, ci:normal, react-native-web

#32092 Build: Stop minifying build output
  code/addons/a11y/package.json
  code/addons/docs/package.json
  code/addons/jest/package.json
  code/addons/links/package.json
  code/addons/themes/package.json
  code/builders/builder-vite/package.json
  code/builders/builder-webpack5/package.json
  code/core/package.json
  code/frameworks/angular/package.json
  code/frameworks/ember/package.json
  code/frameworks/html-vite/package.json
  code/frameworks/nextjs-vite/package.json
  code/frameworks/nextjs/package.json
  code/frameworks/preact-vite/package.json
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-vite/package.json
  code/frameworks/react-webpack5/package.json
  code/frameworks/server-webpack5/package.json
  code/frameworks/svelte-vite/package.json
  code/frameworks/sveltekit/package.json
  code/frameworks/vue3-vite/package.json
  code/frameworks/web-components-vite/package.json
  code/lib/cli-sb/package.json
  code/lib/cli-storybook/package.json
  code/lib/codemod/package.json
  code/lib/core-webpack/package.json
  code/lib/create-storybook/package.json
  code/lib/csf-plugin/package.json
  code/lib/eslint-plugin/package.json
  code/lib/react-dom-shim/package.json
  code/presets/create-react-app/package.json
  code/presets/react-webpack/package.json
  code/presets/server-webpack/package.json
  code/renderers/html/package.json
  code/renderers/preact/package.json
  code/renderers/react/package.json
  code/renderers/server/package.json
  code/renderers/svelte/package.json
  code/renderers/vue3/package.json
  code/renderers/web-components/package.json
  scripts/build/build-package.ts
  scripts/build/utils/generate-bundle.ts
Labels: maintenance, ci:normal

#32111 Test: Fix missing source map for Webpack mock loaders
  code/core/src/core-server/presets/vitePlugins/vite-mock/plugin.ts
  code/core/src/core-server/presets/webpack/loaders/storybook-mock-transform-loader.ts
  code/core/src/core-server/presets/webpack/loaders/webpack-automock-loader.ts
Labels: bug, builder-webpack5, ci:normal, test utilities

#32109 Build: Support big metafiles in bundle analyzer
  code/.storybook/bench.stories.tsx
  code/.storybook/bench/bench.stories.tsx
  code/.storybook/bench/bundle-analyzer/index.css
  code/.storybook/bench/bundle-analyzer/index.html
  code/.storybook/bench/bundle-analyzer/index.js
  code/.storybook/main.ts
  code/addons/a11y/package.json
  code/addons/docs/package.json
  code/addons/jest/package.json
  code/addons/links/package.json
  code/addons/themes/package.json
  code/builders/builder-vite/package.json
  code/builders/builder-vite/src/vite-config.ts
  code/builders/builder-webpack5/package.json
  code/core/build-config.ts
  code/core/package.json
  code/frameworks/angular/package.json
  code/frameworks/ember/package.json
  code/frameworks/html-vite/package.json
  code/frameworks/nextjs-vite/package.json
  code/frameworks/nextjs/package.json
  code/frameworks/preact-vite/package.json
  code/frameworks/react-native-web-vite/package.json
  code/frameworks/react-vite/package.json
  code/frameworks/react-webpack5/package.json
  code/frameworks/server-webpack5/package.json
  code/frameworks/svelte-vite/package.json
  code/frameworks/sveltekit/package.json
  code/frameworks/vue3-vite/package.json
  code/frameworks/web-components-vite/package.json
  code/lib/cli-sb/package.json
  code/lib/cli-storybook/build-config.ts
  code/lib/cli-storybook/package.json
  code/lib/codemod/package.json
  code/lib/core-webpack/package.json
  code/lib/create-storybook/build-config.ts
  code/lib/create-storybook/package.json
  code/lib/csf-plugin/package.json
  code/lib/eslint-plugin/package.json
  code/lib/react-dom-shim/package.json
  code/presets/create-react-app/package.json
  code/presets/react-webpack/package.json
  code/presets/server-webpack/package.json
  code/renderers/html/package.json
  code/renderers/preact/package.json
  code/renderers/react/package.json
  code/renderers/server/package.json
  code/renderers/svelte/package.json
  code/renderers/vue3/package.json
  code/renderers/web-components/package.json
  scripts/bench/safe-args.ts
  scripts/build/utils/entry-utils.ts
  scripts/build/utils/generate-bundle.ts
Labels: build, ci:normal

#32115 Test: Remove source map generation from webpack automock-loader
  code/core/src/core-server/presets/webpack/loaders/webpack-automock-loader.ts
Labels: bug, nextjs, ci:normal, test utilities

#32123 Core: Avoid pausing animations in non-Vitest Playwright environments
  code/addons/onboarding/src/features/SplashScreen/SplashScreen.stories.tsx
  code/core/src/preview-api/modules/preview-web/render/animation-utils.ts
Labels: bug, patch:yes, ci:normal

#32142 Init: Exclude mdx stories when docs feature isn't selected during init
  code/lib/create-storybook/src/generators/NUXT/index.ts
  code/lib/create-storybook/src/generators/baseGenerator.ts
  code/lib/create-storybook/src/generators/configure.test.ts
  code/lib/create-storybook/src/generators/configure.ts
  code/lib/create-storybook/src/generators/types.ts
Labels: bug, cli, ci:normal

#32089 Build: Testing more e2e-dev instead of e2e build
  .circleci/config.yml
  code/e2e-tests/addon-onboarding.spec.ts
  code/e2e-tests/module-mocking.spec.ts
  code/e2e-tests/util.ts
  code/lib/cli-storybook/src/sandbox-templates.ts
Labels: build, ci:daily

#32128 Docs: Add automocking guide
  docs/_snippets/before-each-in-meta-mock-date.md
  docs/_snippets/interaction-test-complex.md
  docs/_snippets/mount-advanced.md
  docs/_snippets/storybook-test-fn-mock-spy.md
  docs/_snippets/storybook-test-mock-return-value.md
  docs/get-started/frameworks/nextjs.mdx
  docs/writing-stories/mocking-data-and-modules/mocking-modules.mdx
Labels: documentation, ci:docs

#32150 Core: Prevent interactions panel from flickering and showing incorrect state
  code/core/src/component-testing/components/InteractionsPanel.stories.tsx
  code/core/src/component-testing/components/InteractionsPanel.tsx
  code/core/src/component-testing/components/Panel.test.ts
  code/core/src/component-testing/components/Panel.tsx
  code/core/src/component-testing/components/PanelTitle.tsx
  code/core/src/preview-api/modules/preview-web/PreviewWithSelection.tsx
  code/core/src/preview-api/modules/preview-web/render/CsfDocsRender.ts
  code/core/src/preview-api/modules/preview-web/render/MdxDocsRender.ts
  code/core/src/preview-api/modules/preview-web/render/Render.ts
  code/core/src/preview-api/modules/preview-web/render/StoryRender.ts
Labels: bug, core, ci:normal

#32163 Core: Don't update interactions panel state until we reach the rendering phase
  code/core/src/component-testing/components/Panel.tsx
Labels: bug, ci:normal

#32147 Core: Disable dynamic favicon behavior when using custom favicon filename
  code/core/src/manager/components/sidebar/useDynamicFavicon.ts
Labels: bug, ci:normal, needs qa

#32126 Docs: Migration guide removes incorrect link
  MIGRATION.md
Labels: documentation, ci:docs
